-- lib/bitset/bitset_test.lua

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local bitset = require("lib.bitset")

-- ---------------------------------------------------------------------------
T.describe("bitset.new", function()
  T.it("creates a zeroed bitset of given size", function()
    local b = bitset.new(64)
    T.eq(b:size(), 64)
    T.eq(b:count(), 0)
    T.ok(b:none())
    T.ok(not b:any())
    T.ok(not b:all())
  end)

  T.it("rejects invalid sizes", function()
    local b, err = bitset.new(0)
    T.eq(b, nil)
    T.ok(err ~= nil)
    local b2, err2 = bitset.new(-5)
    T.eq(b2, nil)
    T.ok(err2 ~= nil)
    local b3, err3 = bitset.new(1.5)
    T.eq(b3, nil)
    T.ok(err3 ~= nil)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("set / get / clear / flip", function()
  T.it("set and get bit 1", function()
    local b = bitset.new(64)
    T.ok(not b:get(1))
    b:set(1)
    T.ok(b:get(1))
  end)

  T.it("set and get bit 32 (word boundary)", function()
    local b = bitset.new(64)
    b:set(32)
    T.ok(b:get(32))
    T.ok(not b:get(31))
    T.ok(not b:get(33))
  end)

  T.it("set and get bit 33 (second word)", function()
    local b = bitset.new(64)
    b:set(33)
    T.ok(b:get(33))
    T.ok(not b:get(32))
    T.ok(not b:get(34))
  end)

  T.it("set and get bit 64 (last bit)", function()
    local b = bitset.new(64)
    b:set(64)
    T.ok(b:get(64))
    T.ok(not b:get(63))
  end)

  T.it("clear a set bit", function()
    local b = bitset.new(64)
    b:set(10)
    T.ok(b:get(10))
    b:clear(10)
    T.ok(not b:get(10))
  end)

  T.it("clear an already-clear bit is a no-op", function()
    local b = bitset.new(64)
    b:clear(5)
    T.ok(not b:get(5))
  end)

  T.it("flip toggles bit on and off", function()
    local b = bitset.new(64)
    T.ok(not b:get(5))
    b:flip(5)
    T.ok(b:get(5))
    b:flip(5)
    T.ok(not b:get(5))
  end)

  T.it("out-of-range set returns error", function()
    local b = bitset.new(32)
    local ok, err = b:set(33)
    T.eq(ok, nil)
    T.ok(err ~= nil)
  end)

  T.it("out-of-range get returns error", function()
    local b = bitset.new(32)
    local ok, err = b:get(0)
    T.eq(ok, nil)
    T.ok(err ~= nil)
  end)

  T.it("out-of-range clear returns error", function()
    local b = bitset.new(32)
    local ok, err = b:clear(33)
    T.eq(ok, nil)
    T.ok(err ~= nil)
  end)

  T.it("out-of-range flip returns error", function()
    local b = bitset.new(32)
    local ok, err = b:flip(0)
    T.eq(ok, nil)
    T.ok(err ~= nil)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("count / any / none / all", function()
  T.it("count increases with each set", function()
    local b = bitset.new(64)
    T.eq(b:count(), 0)
    b:set(1)
    T.eq(b:count(), 1)
    b:set(32)
    T.eq(b:count(), 2)
    b:set(33)
    T.eq(b:count(), 3)
    b:set(64)
    T.eq(b:count(), 4)
  end)

  T.it("count decreases with clear", function()
    local b = bitset.new(64)
    b:set(1); b:set(2); b:set(3)
    T.eq(b:count(), 3)
    b:clear(2)
    T.eq(b:count(), 2)
  end)

  T.it("any / none / all on empty bitset", function()
    local b = bitset.new(8)
    T.ok(b:none())
    T.ok(not b:any())
    T.ok(not b:all())
  end)

  T.it("any is true when at least one bit set", function()
    local b = bitset.new(8)
    b:set(4)
    T.ok(b:any())
    T.ok(not b:none())
  end)

  T.it("all is true when every bit set (8-bit)", function()
    local b = bitset.new(8)
    for i = 1, 8 do b:set(i) end
    T.ok(b:all())
    T.ok(b:any())
    T.ok(not b:none())
  end)

  T.it("all is true when every bit set (64-bit)", function()
    local b = bitset.new(64)
    for i = 1, 64 do b:set(i) end
    T.ok(b:all())
  end)

  T.it("all is false if one bit missing (non-multiple-of-32 size)", function()
    local b = bitset.new(33)
    for i = 1, 33 do b:set(i) end
    T.ok(b:all())
    b:clear(17)
    T.ok(not b:all())
  end)

  T.it("popcount across word boundary", function()
    local b = bitset.new(64)
    -- Set bits 30, 31, 32, 33, 34 — spanning word 1 and word 2
    b:set(30); b:set(31); b:set(32); b:set(33); b:set(34)
    T.eq(b:count(), 5)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("band / bor / bxor / bnot / difference", function()
  T.it("band: intersection", function()
    local b1 = bitset.new(64)
    local b2 = bitset.new(64)
    b1:set(1); b1:set(32); b1:set(33)
    b2:set(32); b2:set(33); b2:set(64)
    local r = b1:band(b2)
    T.ok(not r:get(1))
    T.ok(r:get(32))
    T.ok(r:get(33))
    T.ok(not r:get(64))
    T.eq(r:count(), 2)
  end)

  T.it("bor: union", function()
    local b1 = bitset.new(64)
    local b2 = bitset.new(64)
    b1:set(1); b1:set(10)
    b2:set(10); b2:set(20)
    local r = b1:bor(b2)
    T.ok(r:get(1))
    T.ok(r:get(10))
    T.ok(r:get(20))
    T.eq(r:count(), 3)
  end)

  T.it("bxor: symmetric difference", function()
    local b1 = bitset.new(64)
    local b2 = bitset.new(64)
    b1:set(1); b1:set(10)
    b2:set(10); b2:set(20)
    local r = b1:bxor(b2)
    T.ok(r:get(1))
    T.ok(not r:get(10))  -- shared → xored out
    T.ok(r:get(20))
    T.eq(r:count(), 2)
  end)

  T.it("bnot: flips all bits within size", function()
    local b = bitset.new(8)
    b:set(1); b:set(3); b:set(5); b:set(7)
    local r = b:bnot()
    T.ok(not r:get(1))
    T.ok(r:get(2))
    T.ok(not r:get(3))
    T.ok(r:get(4))
    T.ok(not r:get(5))
    T.ok(r:get(6))
    T.ok(not r:get(7))
    T.ok(r:get(8))
    T.eq(r:count(), 4)
  end)

  T.it("bnot on size non-multiple-of-32 does not set extra bits", function()
    local b = bitset.new(33)  -- 2 words but only 33 bits
    -- all zeros; bnot should set exactly 33 bits
    local r = b:bnot()
    T.eq(r:count(), 33)
    T.ok(not r:get(33) == false)  -- bit 33 is set
    T.ok(r:get(33))
  end)

  T.it("difference: bits in b1 but not b2", function()
    local b1 = bitset.new(64)
    local b2 = bitset.new(64)
    b1:set(1); b1:set(5); b1:set(10)
    b2:set(5); b2:set(10); b2:set(20)
    local r = b1:difference(b2)
    T.ok(r:get(1))
    T.ok(not r:get(5))
    T.ok(not r:get(10))
    T.ok(not r:get(20))
    T.eq(r:count(), 1)
  end)

  T.it("size mismatch returns error", function()
    local b1 = bitset.new(32)
    local b2 = bitset.new(64)
    local r, err = b1:band(b2)
    T.eq(r, nil)
    T.ok(err ~= nil)
    local r2, err2 = b1:bor(b2)
    T.eq(r2, nil)
    T.ok(err2 ~= nil)
    local r3, err3 = b1:bxor(b2)
    T.eq(r3, nil)
    T.ok(err3 ~= nil)
    local r4, err4 = b1:difference(b2)
    T.eq(r4, nil)
    T.ok(err4 ~= nil)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("iter / to_array", function()
  T.it("iter returns positions in ascending order", function()
    local b = bitset.new(64)
    b:set(1); b:set(5); b:set(32); b:set(33); b:set(64)
    local positions = {}
    for pos in b:iter() do positions[#positions + 1] = pos end
    T.eq(#positions, 5)
    T.eq(positions[1], 1)
    T.eq(positions[2], 5)
    T.eq(positions[3], 32)
    T.eq(positions[4], 33)
    T.eq(positions[5], 64)
  end)

  T.it("iter on empty bitset yields nothing", function()
    local b = bitset.new(64)
    local count = 0
    for _ in b:iter() do count = count + 1 end
    T.eq(count, 0)
  end)

  T.it("iter only goes up to size for partial last word", function()
    local b = bitset.new(33)
    b:set(33)
    local positions = {}
    for pos in b:iter() do positions[#positions + 1] = pos end
    T.eq(#positions, 1)
    T.eq(positions[1], 33)
  end)

  T.it("to_array matches iter", function()
    local b = bitset.new(64)
    b:set(2); b:set(17); b:set(40); b:set(63)
    local arr = b:to_array()
    T.eq(#arr, 4)
    T.eq(arr[1], 2)
    T.eq(arr[2], 17)
    T.eq(arr[3], 40)
    T.eq(arr[4], 63)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("to_string", function()
  T.it("all zeros gives all-zero string", function()
    local b = bitset.new(8)
    T.eq(b:to_string(), "00000000")
  end)

  T.it("bit 1 set gives leading 1", function()
    local b = bitset.new(8)
    b:set(1)
    T.eq(b:to_string(), "10000000")
  end)

  T.it("bit 8 set gives trailing 1", function()
    local b = bitset.new(8)
    b:set(8)
    T.eq(b:to_string(), "00000001")
  end)

  T.it("alternating bits", function()
    local b = bitset.new(8)
    b:set(1); b:set(3); b:set(5); b:set(7)
    T.eq(b:to_string(), "10101010")
  end)

  T.it("length equals size", function()
    local b = bitset.new(33)
    T.eq(#b:to_string(), 33)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("to_hex / from_hex round-trip", function()
  T.it("all-zero round-trips", function()
    local b = bitset.new(64)
    local h = b:to_hex()
    T.eq(#h, 16)  -- 2 words × 8 hex digits
    local b2, err = bitset.from_hex(h, 64)
    T.eq(err, nil)
    T.eq(b2:count(), 0)
  end)

  T.it("round-trip preserves set bits", function()
    local b = bitset.new(64)
    b:set(1); b:set(32); b:set(33); b:set(64)
    local h = b:to_hex()
    local b2 = bitset.from_hex(h, 64)
    T.ok(b2:get(1))
    T.ok(b2:get(32))
    T.ok(b2:get(33))
    T.ok(b2:get(64))
    T.ok(not b2:get(2))
    T.eq(b2:count(), 4)
  end)

  T.it("from_hex error on wrong length", function()
    local b, err = bitset.from_hex("aabbccdd", 64)  -- need 16 chars for 64 bits
    T.eq(b, nil)
    T.ok(err ~= nil)
  end)

  T.it("from_hex error on invalid hex", function()
    local b, err = bitset.from_hex("zzzzzzzzzzzzzzzz", 64)
    T.eq(b, nil)
    T.ok(err ~= nil)
  end)

  T.it("round-trip with 32-bit bitset", function()
    local b = bitset.new(32)
    for i = 1, 32, 2 do b:set(i) end
    local h = b:to_hex()
    T.eq(#h, 8)
    local b2 = bitset.from_hex(h, 32)
    T.eq(b2:count(), 16)
    for i = 1, 32, 2 do T.ok(b2:get(i)) end
    for i = 2, 32, 2 do T.ok(not b2:get(i)) end
  end)

  T.it("round-trip with non-multiple-of-32 size", function()
    local b = bitset.new(33)
    b:set(1); b:set(33)
    local h = b:to_hex()
    local b2 = bitset.from_hex(h, 33)
    T.ok(b2:get(1))
    T.ok(b2:get(33))
    T.eq(b2:count(), 2)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("dynamic bitset", function()
  T.it("starts empty", function()
    local db = bitset.dynamic_new()
    T.eq(db:count(), 0)
    T.ok(db:none())
    T.ok(not db:any())
  end)

  T.it("set and get within first word", function()
    local db = bitset.dynamic_new()
    db:set(1)
    T.ok(db:get(1))
    T.ok(not db:get(2))
    T.eq(db:count(), 1)
  end)

  T.it("auto-grows to accommodate large bit positions", function()
    local db = bitset.dynamic_new()
    db:set(1000)
    T.ok(db:get(1000))
    T.eq(db:count(), 1)
    T.ok(not db:get(999))
    T.ok(not db:get(1001))
  end)

  T.it("set multiple sparse bits", function()
    local db = bitset.dynamic_new()
    db:set(1); db:set(100); db:set(500); db:set(1000)
    T.eq(db:count(), 4)
    T.ok(db:get(1))
    T.ok(db:get(100))
    T.ok(db:get(500))
    T.ok(db:get(1000))
  end)

  T.it("clear a set bit", function()
    local db = bitset.dynamic_new()
    db:set(50)
    T.ok(db:get(50))
    db:clear(50)
    T.ok(not db:get(50))
    T.eq(db:count(), 0)
  end)

  T.it("clear beyond allocated range is a no-op", function()
    local db = bitset.dynamic_new()
    db:set(10)
    db:clear(10000)  -- not allocated
    T.ok(db:get(10))
    T.eq(db:count(), 1)
  end)

  T.it("flip toggles", function()
    local db = bitset.dynamic_new()
    db:flip(7)
    T.ok(db:get(7))
    db:flip(7)
    T.ok(not db:get(7))
  end)

  T.it("get on unset position returns false (no error)", function()
    local db = bitset.dynamic_new()
    T.ok(not db:get(9999))
  end)

  T.it("iter yields set bits in order", function()
    local db = bitset.dynamic_new()
    db:set(3); db:set(32); db:set(33); db:set(200)
    local arr = db:to_array()
    T.eq(#arr, 4)
    T.eq(arr[1], 3)
    T.eq(arr[2], 32)
    T.eq(arr[3], 33)
    T.eq(arr[4], 200)
  end)

  T.it("size tracks max bit set", function()
    local db = bitset.dynamic_new()
    T.eq(db:size(), 0)
    db:set(50)
    T.eq(db:size(), 50)
    db:set(200)
    T.eq(db:size(), 200)
  end)

  T.it("count across word boundaries", function()
    local db = bitset.dynamic_new()
    -- set bits around word boundary 32/33
    db:set(31); db:set(32); db:set(33); db:set(34)
    T.eq(db:count(), 4)
  end)

  T.it("any/none after set and clear", function()
    local db = bitset.dynamic_new()
    T.ok(db:none())
    db:set(42)
    T.ok(db:any())
    T.ok(not db:none())
    db:clear(42)
    T.ok(db:none())
    T.ok(not db:any())
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("edge cases and regression", function()
  T.it("1-bit bitset works correctly", function()
    local b = bitset.new(1)
    T.eq(b:size(), 1)
    T.ok(not b:get(1))
    b:set(1)
    T.ok(b:get(1))
    T.ok(b:all())
    T.eq(b:count(), 1)
    b:clear(1)
    T.ok(b:none())
  end)

  T.it("32-bit bitset — bnot of all-ones gives empty", function()
    local b = bitset.new(32)
    for i = 1, 32 do b:set(i) end
    local r = b:bnot()
    T.eq(r:count(), 0)
    T.ok(r:none())
  end)

  T.it("bnot round-trip: bnot(bnot(b)) == b", function()
    local b = bitset.new(64)
    b:set(1); b:set(17); b:set(32); b:set(33); b:set(48); b:set(64)
    local arr_orig = b:to_array()
    local r = b:bnot():bnot()
    local arr_rt = r:to_array()
    T.eq(#arr_orig, #arr_rt)
    for i = 1, #arr_orig do
      T.eq(arr_orig[i], arr_rt[i])
    end
  end)

  T.it("band with self equals self", function()
    local b = bitset.new(64)
    b:set(7); b:set(8); b:set(9)
    local r = b:band(b)
    T.eq(r:to_string(), b:to_string())
  end)

  T.it("bxor with self gives empty", function()
    local b = bitset.new(64)
    b:set(7); b:set(40)
    local r = b:bxor(b)
    T.eq(r:count(), 0)
  end)

  T.it("bor with bnot gives all set", function()
    local b = bitset.new(32)
    b:set(1); b:set(15); b:set(32)
    local r = b:bor(b:bnot())
    T.ok(r:all())
  end)

  T.it("large bitset: 1024 bits", function()
    local b = bitset.new(1024)
    T.eq(b:size(), 1024)
    b:set(1)
    b:set(512)
    b:set(1024)
    T.eq(b:count(), 3)
    local arr = b:to_array()
    T.eq(arr[1], 1)
    T.eq(arr[2], 512)
    T.eq(arr[3], 1024)
  end)

  T.it("to_hex/from_hex round-trip on all-set 64-bit", function()
    local b = bitset.new(64)
    for i = 1, 64 do b:set(i) end
    local h = b:to_hex()
    local b2 = bitset.from_hex(h, 64)
    T.ok(b2:all())
    T.eq(b2:count(), 64)
  end)
end)
