if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T  = require("lib.test.assert")
local G  = require("lib.geometry_3d")

local function approx(a, b, eps)
  eps = eps or 1e-6
  return math.abs(a - b) < eps
end

local function approx_vec3(a, b, eps)
  return approx(a.x, b.x, eps) and approx(a.y, b.y, eps) and approx(a.z, b.z, eps)
end

T.describe("vec3 basics", function()
  T.it("vec3 constructor", function()
    local v = G.vec3(1, 2, 3)
    T.eq(v.x, 1)
    T.eq(v.y, 2)
    T.eq(v.z, 3)
  end)

  T.it("add3", function()
    local v = G.add3(G.vec3(1,2,3), G.vec3(4,5,6))
    T.eq(v.x, 5) T.eq(v.y, 7) T.eq(v.z, 9)
  end)

  T.it("sub3", function()
    local v = G.sub3(G.vec3(4,5,6), G.vec3(1,2,3))
    T.eq(v.x, 3) T.eq(v.y, 3) T.eq(v.z, 3)
  end)

  T.it("scale3", function()
    local v = G.scale3(G.vec3(1,2,3), 2)
    T.eq(v.x, 2) T.eq(v.y, 4) T.eq(v.z, 6)
  end)

  T.it("dot3", function()
    T.eq(G.dot3(G.vec3(1,0,0), G.vec3(0,1,0)), 0)
    T.eq(G.dot3(G.vec3(1,2,3), G.vec3(4,5,6)), 32)
  end)

  T.it("cross3", function()
    local c = G.cross3(G.vec3(1,0,0), G.vec3(0,1,0))
    T.eq(c.x, 0) T.eq(c.y, 0) T.eq(c.z, 1)
    local c2 = G.cross3(G.vec3(0,1,0), G.vec3(1,0,0))
    T.eq(c2.z, -1)
  end)

  T.it("len3", function()
    T.ok(approx(G.len3(G.vec3(3,4,0)), 5))
    T.ok(approx(G.len3(G.vec3(1,0,0)), 1))
  end)

  T.it("norm3", function()
    local n = G.norm3(G.vec3(3,0,0))
    T.ok(approx(n.x, 1)) T.ok(approx(n.y, 0)) T.ok(approx(n.z, 0))
    local n2 = G.norm3(G.vec3(1,1,0))
    T.ok(approx(G.len3(n2), 1))
  end)

  T.it("norm3 of zero vector", function()
    local n = G.norm3(G.vec3(0,0,0))
    T.eq(n.x, 0) T.eq(n.y, 0) T.eq(n.z, 0)
  end)

  T.it("neg3", function()
    local v = G.neg3(G.vec3(1,-2,3))
    T.eq(v.x, -1) T.eq(v.y, 2) T.eq(v.z, -3)
  end)
end)

T.describe("lerp3", function()
  T.it("t=0 returns a", function()
    local a = G.vec3(0,0,0)
    local b = G.vec3(10,10,10)
    local r = G.lerp3(a, b, 0)
    T.ok(approx_vec3(r, a))
  end)
  T.it("t=1 returns b", function()
    local a = G.vec3(0,0,0)
    local b = G.vec3(10,10,10)
    local r = G.lerp3(a, b, 1)
    T.ok(approx_vec3(r, b))
  end)
  T.it("t=0.5 returns midpoint", function()
    local a = G.vec3(0,0,0)
    local b = G.vec3(10,0,0)
    local r = G.lerp3(a, b, 0.5)
    T.ok(approx(r.x, 5))
  end)
end)

T.describe("ray_triangle (Möller-Trumbore)", function()
  local v0 = G.vec3(0,0,0)
  local v1 = G.vec3(1,0,0)
  local v2 = G.vec3(0,1,0)

  T.it("hits triangle from front", function()
    local r = G.ray(G.vec3(0.2, 0.2, -1), G.vec3(0,0,1))
    local t, u, v = G.ray_triangle(r, v0, v1, v2)
    T.ok(t ~= nil)
    T.ok(approx(t, 1))
    T.ok(u >= 0 and v >= 0 and u+v <= 1)
  end)

  T.it("misses triangle (off to side)", function()
    local r = G.ray(G.vec3(2, 0, -1), G.vec3(0,0,1))
    local t = G.ray_triangle(r, v0, v1, v2)
    T.eq(t, nil)
  end)

  T.it("parallel ray returns nil", function()
    local r = G.ray(G.vec3(0,0,1), G.vec3(1,0,0))
    local t = G.ray_triangle(r, v0, v1, v2)
    T.eq(t, nil)
  end)

  T.it("ray behind triangle returns nil", function()
    local r = G.ray(G.vec3(0.2, 0.2, 2), G.vec3(0,0,1))
    local t = G.ray_triangle(r, v0, v1, v2)
    T.eq(t, nil)
  end)
end)

T.describe("ray_sphere", function()
  local center = G.vec3(0,0,5)
  local radius = 1

  T.it("hits sphere (through center)", function()
    local r = G.ray(G.vec3(0,0,0), G.vec3(0,0,1))
    local t1, t2 = G.ray_sphere(r, center, radius)
    T.ok(t1 ~= nil)
    T.ok(approx(t1, 4))
    T.ok(approx(t2, 6))
  end)

  T.it("misses sphere", function()
    local r = G.ray(G.vec3(0,2,0), G.vec3(0,0,1))
    local t1 = G.ray_sphere(r, center, radius)
    T.eq(t1, nil)
  end)

  T.it("ray behind sphere returns negative t", function()
    local r = G.ray(G.vec3(0,0,10), G.vec3(0,0,1))
    local t1, t2 = G.ray_sphere(r, center, radius)
    -- t1 and t2 are both negative (sphere behind origin)
    T.ok(t1 ~= nil)
    T.ok(t2 < 0)
  end)
end)

T.describe("ray_aabb", function()
  local aabb = {min = G.vec3(-1,-1,-1), max = G.vec3(1,1,1)}

  T.it("hits AABB from -X side", function()
    local r = G.ray(G.vec3(-5,0,0), G.vec3(1,0,0))
    local tn, tf = G.ray_aabb(r, aabb)
    T.ok(tn ~= nil)
    T.ok(approx(tn, 4))
    T.ok(approx(tf, 6))
  end)

  T.it("misses AABB", function()
    local r = G.ray(G.vec3(0, 5, 0), G.vec3(1,0,0))
    local tn = G.ray_aabb(r, aabb)
    T.eq(tn, nil)
  end)

  T.it("ray origin inside AABB", function()
    local r = G.ray(G.vec3(0,0,0), G.vec3(1,0,0))
    local tn, tf = G.ray_aabb(r, aabb)
    T.ok(tn ~= nil)
    T.ok(tn <= 0)   -- near plane is behind
    T.ok(tf >= 1)   -- far plane is in front
  end)
end)

T.describe("ray_plane", function()
  -- XZ plane at y=0: normal=(0,1,0), d=0
  local plane = {normal = G.vec3(0,1,0), d = 0}

  T.it("hits plane", function()
    local r = G.ray(G.vec3(0,5,0), G.vec3(0,-1,0))
    local t = G.ray_plane(r, plane)
    T.ok(t ~= nil)
    T.ok(approx(t, 5))
  end)

  T.it("parallel ray returns nil", function()
    local r = G.ray(G.vec3(0,1,0), G.vec3(1,0,0))
    local t = G.ray_plane(r, plane)
    T.eq(t, nil)
  end)

  T.it("hits plane at offset", function()
    -- plane y=3: normal=(0,1,0), d=3
    local p2 = {normal = G.vec3(0,1,0), d = 3}
    local r = G.ray(G.vec3(0,0,0), G.vec3(0,1,0))
    local t = G.ray_plane(r, p2)
    T.ok(approx(t, 3))
  end)
end)

T.describe("mesh_aabb", function()
  T.it("unit cube bounding box", function()
    local mesh = G.cube_mesh()
    local bb = G.mesh_aabb(mesh)
    T.ok(approx(bb.min.x, -0.5))
    T.ok(approx(bb.min.y, -0.5))
    T.ok(approx(bb.min.z, -0.5))
    T.ok(approx(bb.max.x,  0.5))
    T.ok(approx(bb.max.y,  0.5))
    T.ok(approx(bb.max.z,  0.5))
  end)
end)

T.describe("mesh_area", function()
  T.it("unit cube surface area = 6", function()
    local mesh = G.cube_mesh()
    T.ok(approx(G.mesh_area(mesh), 6.0, 1e-5))
  end)

  T.it("plane mesh area", function()
    local mesh = G.plane_mesh(2, 3, 1, 1)
    -- 2x3 = 6 square units
    T.ok(approx(G.mesh_area(mesh), 6.0, 1e-5))
  end)
end)

T.describe("mesh_volume", function()
  T.it("unit cube volume = 1", function()
    local mesh = G.cube_mesh()
    local vol = G.mesh_volume(mesh)
    T.ok(approx(math.abs(vol), 1.0, 1e-5))
  end)
end)

T.describe("point_in_mesh", function()
  T.it("origin is inside unit cube", function()
    local mesh = G.cube_mesh()
    T.ok(G.point_in_mesh(mesh, G.vec3(0, 0, 0)))
  end)

  T.it("point outside cube is not inside", function()
    local mesh = G.cube_mesh()
    T.ok(not G.point_in_mesh(mesh, G.vec3(2, 0, 0)))
  end)

  T.it("point at corner vicinity outside", function()
    local mesh = G.cube_mesh()
    T.ok(not G.point_in_mesh(mesh, G.vec3(0.6, 0.6, 0.6)))
  end)
end)

T.describe("mat4 transforms", function()
  T.it("identity leaves point unchanged", function()
    local m = G.mat4_identity()
    local v = G.vec3(3, 4, 5)
    local r = G.mat4_transform_point(m, v)
    T.ok(approx_vec3(r, v))
  end)

  T.it("translate moves point", function()
    local m = G.mat4_translate(1, 2, 3)
    local v = G.vec3(0, 0, 0)
    local r = G.mat4_transform_point(m, v)
    T.ok(approx(r.x, 1))
    T.ok(approx(r.y, 2))
    T.ok(approx(r.z, 3))
  end)

  T.it("translate does not move direction", function()
    local m = G.mat4_translate(10, 10, 10)
    local v = G.vec3(1, 0, 0)
    local r = G.mat4_transform_dir(m, v)
    T.ok(approx_vec3(r, v))
  end)

  T.it("rotate_x: y-axis → z-axis", function()
    local m = G.mat4_rotate_x(math.pi / 2)
    local v = G.vec3(0, 1, 0)
    local r = G.mat4_transform_dir(m, v)
    T.ok(approx(r.x, 0, 1e-5))
    T.ok(approx(r.y, 0, 1e-5))
    T.ok(approx(r.z, 1, 1e-5))
  end)

  T.it("rotate_z: x-axis → y-axis", function()
    local m = G.mat4_rotate_z(math.pi / 2)
    local v = G.vec3(1, 0, 0)
    local r = G.mat4_transform_dir(m, v)
    T.ok(approx(r.x, 0, 1e-5))
    T.ok(approx(r.y, 1, 1e-5))
    T.ok(approx(r.z, 0, 1e-5))
  end)

  T.it("scale", function()
    local m = G.mat4_scale(2, 3, 4)
    local v = G.vec3(1, 1, 1)
    local r = G.mat4_transform_point(m, v)
    T.ok(approx(r.x, 2))
    T.ok(approx(r.y, 3))
    T.ok(approx(r.z, 4))
  end)

  T.it("mat4_mul: translate then scale", function()
    -- translate by (1,0,0), then scale by 2 → point (0,0,0) → (1,0,0) → (2,0,0)
    local t = G.mat4_translate(1, 0, 0)
    local s = G.mat4_scale(2, 2, 2)
    local m = G.mat4_mul(s, t)
    local r = G.mat4_transform_point(m, G.vec3(0,0,0))
    T.ok(approx(r.x, 2, 1e-5))
    T.ok(approx(r.y, 0, 1e-5))
    T.ok(approx(r.z, 0, 1e-5))
  end)

  T.it("mat4_mul: identity * M = M", function()
    local id = G.mat4_identity()
    local t = G.mat4_translate(3, 4, 5)
    local m = G.mat4_mul(id, t)
    local v = G.vec3(0,0,0)
    local r1 = G.mat4_transform_point(m, v)
    local r2 = G.mat4_transform_point(t, v)
    T.ok(approx_vec3(r1, r2))
  end)
end)

T.describe("quaternion", function()
  T.it("quat_from_axis_angle 90° around Z", function()
    local q = G.quat_from_axis_angle(G.vec3(0,0,1), math.pi/2)
    local cos45 = math.cos(math.pi/4)
    local sin45 = math.sin(math.pi/4)
    T.ok(approx(q.w, cos45, 1e-6))
    T.ok(approx(q.x, 0,    1e-6))
    T.ok(approx(q.y, 0,    1e-6))
    T.ok(approx(q.z, sin45,1e-6))
  end)

  T.it("quat_rotate: (1,0,0) by 90° around Z = (0,1,0)", function()
    local q = G.quat_from_axis_angle(G.vec3(0,0,1), math.pi/2)
    local r = G.quat_rotate(q, G.vec3(1,0,0))
    T.ok(approx(r.x, 0, 1e-5))
    T.ok(approx(r.y, 1, 1e-5))
    T.ok(approx(r.z, 0, 1e-5))
  end)

  T.it("quat_rotate: (0,1,0) by 90° around Z = (-1,0,0)", function()
    local q = G.quat_from_axis_angle(G.vec3(0,0,1), math.pi/2)
    local r = G.quat_rotate(q, G.vec3(0,1,0))
    T.ok(approx(r.x, -1, 1e-5))
    T.ok(approx(r.y, 0,  1e-5))
    T.ok(approx(r.z, 0,  1e-5))
  end)

  T.it("quat_normalize", function()
    local q = G.quat(2, 0, 0, 0)
    local n = G.quat_normalize(q)
    T.ok(approx(n.w, 1))
    T.ok(approx(n.x, 0))
  end)

  T.it("quat_conjugate", function()
    local q = G.quat(0.5, 0.1, 0.2, 0.3)
    local c = G.quat_conjugate(q)
    T.eq(c.w,  0.5)
    T.eq(c.x, -0.1)
    T.eq(c.y, -0.2)
    T.eq(c.z, -0.3)
  end)

  T.it("quat_mul: identity * q = q", function()
    local id = G.quat(1, 0, 0, 0)
    local q  = G.quat_from_axis_angle(G.vec3(1,0,0), math.pi/3)
    local r  = G.quat_mul(id, q)
    T.ok(approx(r.w, q.w, 1e-10))
    T.ok(approx(r.x, q.x, 1e-10))
    T.ok(approx(r.y, q.y, 1e-10))
    T.ok(approx(r.z, q.z, 1e-10))
  end)

  T.it("quat_mul: q * conjugate = identity", function()
    local q = G.quat_normalize(G.quat_from_axis_angle(G.vec3(1,1,0), math.pi/4))
    local c = G.quat_conjugate(q)
    local r = G.quat_mul(q, c)
    T.ok(approx(r.w, 1, 1e-10))
    T.ok(approx(r.x, 0, 1e-10))
    T.ok(approx(r.y, 0, 1e-10))
    T.ok(approx(r.z, 0, 1e-10))
  end)

  T.it("quat_slerp t=0 returns a", function()
    local a = G.quat_from_axis_angle(G.vec3(0,1,0), 0)
    local b = G.quat_from_axis_angle(G.vec3(0,1,0), math.pi/2)
    local r = G.quat_slerp(a, b, 0)
    T.ok(approx(r.w, a.w, 1e-6))
    T.ok(approx(r.y, a.y, 1e-6))
  end)

  T.it("quat_slerp t=1 returns b", function()
    local a = G.quat_from_axis_angle(G.vec3(0,1,0), 0)
    local b = G.quat_from_axis_angle(G.vec3(0,1,0), math.pi/2)
    local r = G.quat_slerp(a, b, 1)
    T.ok(approx(r.w, b.w, 1e-6))
    T.ok(approx(r.y, b.y, 1e-6))
  end)

  T.it("quat_slerp t=0.5 midpoint (unit length)", function()
    local a = G.quat_from_axis_angle(G.vec3(0,1,0), 0)
    local b = G.quat_from_axis_angle(G.vec3(0,1,0), math.pi/2)
    local r = G.quat_slerp(a, b, 0.5)
    local len = math.sqrt(r.w*r.w + r.x*r.x + r.y*r.y + r.z*r.z)
    T.ok(approx(len, 1, 1e-6))
    -- midpoint is 45° rotation around Y
    local expected = G.quat_from_axis_angle(G.vec3(0,1,0), math.pi/4)
    T.ok(approx(math.abs(r.w), math.abs(expected.w), 1e-5))
    T.ok(approx(math.abs(r.y), math.abs(expected.y), 1e-5))
  end)
end)

T.describe("primitives", function()
  T.it("cube_mesh has 8 vertices and 12 faces", function()
    local mesh = G.cube_mesh()
    T.eq(#mesh.vertices, 8)
    T.eq(#mesh.faces, 12)
  end)

  T.it("sphere_mesh vertex count", function()
    local mesh = G.sphere_mesh(1, 4, 8)
    -- poles (2) + (lat_segs-1)*lon_segs rings = 2 + 3*8 = 26
    T.eq(#mesh.vertices, 26)
  end)

  T.it("sphere_mesh face count", function()
    local mesh = G.sphere_mesh(1, 4, 8)
    -- top cap: 8 + bottom cap: 8 + middle: (lat_segs-2)*lon_segs*2 = 2*8*2=32 → 8+8+16=32
    -- lat_segs=4: top_cap=8, bot_cap=8, middle=(4-2)*8*2=32 → total=48
    T.eq(#mesh.faces, 48)
  end)

  T.it("sphere_mesh with more segments", function()
    local mesh = G.sphere_mesh(1, 8, 16)
    -- 2 + 7*16 = 114 vertices
    T.eq(#mesh.vertices, 114)
    -- top: 16, bot: 16, middle: 6*16*2 = 192 → total = 224
    T.eq(#mesh.faces, 224)
  end)

  T.it("plane_mesh vertex count", function()
    local mesh = G.plane_mesh(1, 1, 2, 3)
    -- (w_segs+1)*(h_segs+1) = 3*4 = 12
    T.eq(#mesh.vertices, 12)
  end)

  T.it("plane_mesh face count", function()
    local mesh = G.plane_mesh(1, 1, 2, 3)
    -- w_segs*h_segs*2 = 2*3*2 = 12
    T.eq(#mesh.faces, 12)
  end)
end)

T.describe("face_normal and vertex_normals", function()
  T.it("face_normal of bottom face points down", function()
    local mesh = G.cube_mesh()
    -- face 5 is {1,2,6}: all at y=-0.5, normal should have y component
    -- we just check it's non-zero
    local n = G.face_normal(mesh, 1)
    local len = G.len3(n)
    T.ok(len > 0)
  end)

  T.it("vertex_normals returns one per vertex", function()
    local mesh = G.cube_mesh()
    local vn = G.vertex_normals(mesh)
    T.eq(#vn, #mesh.vertices)
  end)

  T.it("vertex normals are unit vectors", function()
    local mesh = G.cube_mesh()
    local vn = G.vertex_normals(mesh)
    for _, n in ipairs(vn) do
      T.ok(approx(G.len3(n), 1, 1e-5))
    end
  end)
end)

T.describe("mesh_bsphere", function()
  T.it("unit cube bsphere center is origin", function()
    local mesh = G.cube_mesh()
    local c, r = G.mesh_bsphere(mesh)
    T.ok(approx(c.x, 0, 1e-6))
    T.ok(approx(c.y, 0, 1e-6))
    T.ok(approx(c.z, 0, 1e-6))
  end)

  T.it("unit cube bsphere radius = sqrt(3)/2", function()
    local mesh = G.cube_mesh()
    local c, r = G.mesh_bsphere(mesh)
    T.ok(approx(r, math.sqrt(3)/2, 1e-5))
  end)
end)
