if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.wire")

-- ---------------------------------------------------------------------------
-- uint8
-- ---------------------------------------------------------------------------
T.describe("uint8", function()
	T.it("round-trips 0", function()
		local w = M.writer()
		w:uint8(0)
		local r = M.reader(w:build())
		T.eq(r:uint8(), 0)
	end)
	T.it("round-trips 255", function()
		local w = M.writer()
		w:uint8(255)
		local r = M.reader(w:build())
		T.eq(r:uint8(), 255)
	end)
	T.it("round-trips 127", function()
		local w = M.writer()
		w:uint8(127)
		local r = M.reader(w:build())
		T.eq(r:uint8(), 127)
	end)
end)

-- ---------------------------------------------------------------------------
-- uint16 LE / BE
-- ---------------------------------------------------------------------------
T.describe("uint16", function()
	T.it("uint16_le round-trip", function()
		local w = M.writer()
		w:uint16_le(0x1234)
		local data = w:build()
		T.eq(#data, 2)
		local r = M.reader(data)
		T.eq(r:uint16_le(), 0x1234)
	end)
	T.it("uint16_be round-trip", function()
		local w = M.writer()
		w:uint16_be(0x1234)
		local data = w:build()
		T.eq(#data, 2)
		local r = M.reader(data)
		T.eq(r:uint16_be(), 0x1234)
	end)
	T.it("LE and BE byte order differs", function()
		local w1, w2 = M.writer(), M.writer()
		w1:uint16_le(0x0102)
		w2:uint16_be(0x0102)
		T.neq(w1:build(), w2:build())
	end)
	T.it("uint16_le byte order: LSB first", function()
		local w = M.writer()
		w:uint16_le(0x0102)
		local data = w:build()
		T.eq(string.byte(data, 1), 0x02)
		T.eq(string.byte(data, 2), 0x01)
	end)
	T.it("uint16_be byte order: MSB first", function()
		local w = M.writer()
		w:uint16_be(0x0102)
		local data = w:build()
		T.eq(string.byte(data, 1), 0x01)
		T.eq(string.byte(data, 2), 0x02)
	end)
end)

-- ---------------------------------------------------------------------------
-- uint32 LE / BE
-- ---------------------------------------------------------------------------
T.describe("uint32", function()
	T.it("uint32_le round-trip", function()
		local w = M.writer()
		w:uint32_le(0xdeadbeef)
		local data = w:build()
		T.eq(#data, 4)
		local r = M.reader(data)
		T.eq(r:uint32_le(), 0xdeadbeef)
	end)
	T.it("uint32_be round-trip", function()
		local w = M.writer()
		w:uint32_be(0xdeadbeef)
		local data = w:build()
		T.eq(#data, 4)
		local r = M.reader(data)
		T.eq(r:uint32_be(), 0xdeadbeef)
	end)
	T.it("LE vs BE produce different bytes", function()
		local w1, w2 = M.writer(), M.writer()
		w1:uint32_le(0x01020304)
		w2:uint32_be(0x01020304)
		T.neq(w1:build(), w2:build())
	end)
	T.it("uint32_le byte order", function()
		local w = M.writer()
		w:uint32_le(0x01020304)
		local data = w:build()
		T.eq(string.byte(data, 1), 0x04)
		T.eq(string.byte(data, 4), 0x01)
	end)
	T.it("uint32_be byte order", function()
		local w = M.writer()
		w:uint32_be(0x01020304)
		local data = w:build()
		T.eq(string.byte(data, 1), 0x01)
		T.eq(string.byte(data, 4), 0x04)
	end)
end)

-- ---------------------------------------------------------------------------
-- Signed integers
-- ---------------------------------------------------------------------------
T.describe("signed integers", function()
	T.it("int8(-1) round-trip", function()
		local w = M.writer()
		w:int8(-1)
		local r = M.reader(w:build())
		T.eq(r:int8(), -1)
	end)
	T.it("int8(-128) round-trip", function()
		local w = M.writer()
		w:int8(-128)
		local r = M.reader(w:build())
		T.eq(r:int8(), -128)
	end)
	T.it("int16_le(-1) round-trip", function()
		local w = M.writer()
		w:int16_le(-1)
		local r = M.reader(w:build())
		T.eq(r:int16_le(), -1)
	end)
	T.it("int16_be(-1) round-trip", function()
		local w = M.writer()
		w:int16_be(-1)
		local r = M.reader(w:build())
		T.eq(r:int16_be(), -1)
	end)
	T.it("int32_le(-1) round-trip", function()
		local w = M.writer()
		w:int32_le(-1)
		local r = M.reader(w:build())
		T.eq(r:int32_le(), -1)
	end)
	T.it("int32_be(-1) round-trip", function()
		local w = M.writer()
		w:int32_be(-1)
		local r = M.reader(w:build())
		T.eq(r:int32_be(), -1)
	end)
	T.it("int32_le(-2147483648) round-trip", function()
		local w = M.writer()
		w:int32_le(-2147483648)
		local r = M.reader(w:build())
		T.eq(r:int32_le(), -2147483648)
	end)
end)

-- ---------------------------------------------------------------------------
-- float / double
-- ---------------------------------------------------------------------------
T.describe("float/double", function()
	T.it("float_le round-trip (approx)", function()
		local w = M.writer()
		w:float_le(1.5)
		local r = M.reader(w:build())
		local v = r:float_le()
		T.ok(math.abs(v - 1.5) < 1e-6, "float_le 1.5")
	end)
	T.it("float_be round-trip (approx)", function()
		local w = M.writer()
		w:float_be(1.5)
		local r = M.reader(w:build())
		local v = r:float_be()
		T.ok(math.abs(v - 1.5) < 1e-6, "float_be 1.5")
	end)
	T.it("double_le round-trip exact", function()
		local w = M.writer()
		w:double_le(math.pi)
		local r = M.reader(w:build())
		T.eq(r:double_le(), math.pi)
	end)
	T.it("double_be round-trip exact", function()
		local w = M.writer()
		w:double_be(math.pi)
		local r = M.reader(w:build())
		T.eq(r:double_be(), math.pi)
	end)
	T.it("float LE vs BE differ", function()
		local w1, w2 = M.writer(), M.writer()
		w1:float_le(1.5)
		w2:float_be(1.5)
		T.neq(w1:build(), w2:build())
	end)
end)

-- ---------------------------------------------------------------------------
-- varint (LEB128 unsigned)
-- ---------------------------------------------------------------------------
T.describe("varint", function()
	local cases = {
		{ 0,      "\x00" },
		{ 1,      "\x01" },
		{ 127,    "\x7f" },
		{ 128,    "\x80\x01" },
		{ 300,    "\xac\x02" },
		{ 65535,  "\xff\xff\x03" },
		{ 268435455, "\xff\xff\xff\x7f" },
	}
	for _, c in ipairs(cases) do
		local n, expected = c[1], c[2]
		T.it("encodes " .. n, function()
			local w = M.writer()
			w:varint(n)
			T.eq(w:build(), expected)
		end)
		T.it("round-trips " .. n, function()
			local w = M.writer()
			w:varint(n)
			local r = M.reader(w:build())
			T.eq(r:varint(), n)
		end)
	end
end)

-- ---------------------------------------------------------------------------
-- varint_signed (zigzag)
-- ---------------------------------------------------------------------------
T.describe("varint_signed", function()
	-- zigzag: 0->0, -1->1, 1->2, -2->3, 2->4
	local cases = {
		{ 0,  0 },
		{ -1, 1 },
		{ 1,  2 },
		{ -2, 3 },
		{ 2,  4 },
		{ -64, 127 },
		{ 64,  128 },
	}
	for _, c in ipairs(cases) do
		local n, zz = c[1], c[2]
		T.it("zigzag " .. n .. " -> " .. zz, function()
			local w = M.writer()
			w:varint_signed(n)
			-- the encoded bytes should be the varint of zz
			local w2 = M.writer()
			w2:varint(zz)
			T.eq(w:build(), w2:build())
		end)
		T.it("round-trips " .. n, function()
			local w = M.writer()
			w:varint_signed(n)
			local r = M.reader(w:build())
			T.eq(r:varint_signed(), n)
		end)
	end
end)

-- ---------------------------------------------------------------------------
-- bytes / bytes_n
-- ---------------------------------------------------------------------------
T.describe("bytes", function()
	T.it("raw bytes round-trip", function()
		local w = M.writer()
		w:bytes("hello")
		T.eq(w:build(), "hello")
	end)
	T.it("bytes_n truncates", function()
		local w = M.writer()
		w:bytes_n("hello", 3)
		T.eq(w:build(), "hel")
	end)
	T.it("bytes_n pads with zeros", function()
		local w = M.writer()
		w:bytes_n("hi", 4)
		local data = w:build()
		T.eq(#data, 4)
		T.eq(string.byte(data, 3), 0)
		T.eq(string.byte(data, 4), 0)
	end)
	T.it("bytes_n exact length unchanged", function()
		local w = M.writer()
		w:bytes_n("abc", 3)
		T.eq(w:build(), "abc")
	end)
end)

-- ---------------------------------------------------------------------------
-- String methods
-- ---------------------------------------------------------------------------
T.describe("string methods", function()
	T.it("str8 round-trip", function()
		local w = M.writer()
		w:str8("hello")
		local r = M.reader(w:build())
		T.eq(r:str8(), "hello")
	end)
	T.it("str8 length prefix is 1 byte", function()
		local w = M.writer()
		w:str8("hi")
		local data = w:build()
		T.eq(#data, 3)
		T.eq(string.byte(data, 1), 2) -- length = 2
	end)
	T.it("str16 round-trip", function()
		local w = M.writer()
		w:str16("world")
		local r = M.reader(w:build())
		T.eq(r:str16(), "world")
	end)
	T.it("str16 length prefix is 2 bytes LE", function()
		local w = M.writer()
		w:str16("ab")
		local data = w:build()
		T.eq(#data, 4)
		T.eq(string.byte(data, 1), 2)  -- LSB of length
		T.eq(string.byte(data, 2), 0)  -- MSB of length
	end)
	T.it("str32 round-trip", function()
		local w = M.writer()
		w:str32("crescent")
		local r = M.reader(w:build())
		T.eq(r:str32(), "crescent")
	end)
	T.it("str_varint round-trip", function()
		local w = M.writer()
		w:str_varint("test")
		local r = M.reader(w:build())
		T.eq(r:str_varint(), "test")
	end)
	T.it("str_varint empty string", function()
		local w = M.writer()
		w:str_varint("")
		local r = M.reader(w:build())
		T.eq(r:str_varint(), "")
	end)
end)

-- ---------------------------------------------------------------------------
-- Writer state: len, reset
-- ---------------------------------------------------------------------------
T.describe("writer state", function()
	T.it("len() tracks bytes written", function()
		local w = M.writer()
		T.eq(w:len(), 0)
		w:uint8(1)
		T.eq(w:len(), 1)
		w:uint32_le(0)
		T.eq(w:len(), 5)
		w:bytes("abc")
		T.eq(w:len(), 8)
	end)
	T.it("reset() clears buffer", function()
		local w = M.writer()
		w:uint32_le(0xdeadbeef)
		w:reset()
		T.eq(w:len(), 0)
		T.eq(w:build(), "")
	end)
end)

-- ---------------------------------------------------------------------------
-- Reader position methods
-- ---------------------------------------------------------------------------
T.describe("reader position", function()
	T.it("pos() starts at 1", function()
		local r = M.reader("abc")
		T.eq(r:pos(), 1)
	end)
	T.it("pos() advances after reads", function()
		local r = M.reader("abcd")
		r:uint8()
		T.eq(r:pos(), 2)
		r:uint16_le()
		T.eq(r:pos(), 4)
	end)
	T.it("remaining() counts bytes left", function()
		local r = M.reader("abcde")
		T.eq(r:remaining(), 5)
		r:bytes(2)
		T.eq(r:remaining(), 3)
	end)
	T.it("at_end() false when data remains", function()
		local r = M.reader("a")
		T.ok(not r:at_end())
	end)
	T.it("at_end() true when exhausted", function()
		local r = M.reader("a")
		r:uint8()
		T.ok(r:at_end())
	end)
	T.it("seek() moves position", function()
		local r = M.reader("abcde")
		r:seek(3)
		T.eq(r:pos(), 3)
		T.eq(r:uint8(), string.byte("c"))
	end)
	T.it("peek() does not advance", function()
		local r = M.reader("abcde")
		local s = r:peek(3)
		T.eq(s, "abc")
		T.eq(r:pos(), 1)
	end)
	T.it("skip() advances without returning data", function()
		local r = M.reader("abcde")
		r:skip(2)
		T.eq(r:pos(), 3)
		T.eq(r:uint8(), string.byte("c"))
	end)
end)

-- ---------------------------------------------------------------------------
-- Error on truncated data
-- ---------------------------------------------------------------------------
T.describe("truncated data errors", function()
	T.it("uint8 on empty returns nil,errmsg", function()
		local r = M.reader("")
		local v, err = r:uint8()
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("uint32_le on 2 bytes returns nil,errmsg", function()
		local r = M.reader("\x01\x02")
		local v, err = r:uint32_le()
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("bytes(5) on 3-byte buffer returns nil,errmsg", function()
		local r = M.reader("abc")
		local v, err = r:bytes(5)
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("varint on empty returns nil,errmsg", function()
		local r = M.reader("")
		local v, err = r:varint()
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("str8 with declared length beyond data returns nil,errmsg", function()
		-- length byte says 10 but only 3 bytes follow
		local data = string.char(10) .. "abc"
		local r = M.reader(data)
		local v, err = r:str8()
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
end)

-- ---------------------------------------------------------------------------
-- Framing
-- ---------------------------------------------------------------------------
T.describe("M.frame / M.unframe", function()
	local prefixes = { "u32_be", "u32_le", "u16_be", "u16_le", "varint" }
	for _, p in ipairs(prefixes) do
		T.it("round-trips with prefix=" .. p, function()
			local payload = "hello world"
			local framed = M.frame(payload, { prefix = p })
			T.ok(framed ~= nil)
			local out, rem = M.unframe(framed, { prefix = p })
			T.eq(out, payload)
			T.eq(rem, "")
		end)
	end
	T.it("unframe leaves trailing bytes in remaining", function()
		local payload = "ping"
		local framed = M.frame(payload, { prefix = "u32_be" })
		local combined = framed .. "extra"
		local out, rem = M.unframe(combined, { prefix = "u32_be" })
		T.eq(out, payload)
		T.eq(rem, "extra")
	end)
	T.it("default prefix is u32_be", function()
		local payload = "test"
		local framed = M.frame(payload)
		local out = M.unframe(framed)
		T.eq(out, payload)
	end)
	T.it("frame length prefix is correct byte count", function()
		local payload = "abc"
		local framed = M.frame(payload, { prefix = "u32_be" })
		-- first 4 bytes = big-endian length = 3
		T.eq(string.byte(framed, 1), 0)
		T.eq(string.byte(framed, 2), 0)
		T.eq(string.byte(framed, 3), 0)
		T.eq(string.byte(framed, 4), 3)
	end)
end)

-- ---------------------------------------------------------------------------
-- Streaming unframer
-- ---------------------------------------------------------------------------
T.describe("M.unframer streaming", function()
	T.it("returns nil when no data fed", function()
		local uf = M.unframer()
		T.eq(uf:next(), nil)
	end)
	T.it("returns nil with partial length prefix", function()
		local uf = M.unframer({ prefix = "u32_be" })
		uf:feed("\x00\x00")  -- only 2 of 4 bytes of length
		T.eq(uf:next(), nil)
	end)
	T.it("returns nil with complete prefix but partial payload", function()
		local uf = M.unframer({ prefix = "u32_be" })
		-- length = 10, but only 3 bytes of payload
		uf:feed("\x00\x00\x00\x0a" .. "abc")
		T.eq(uf:next(), nil)
	end)
	T.it("returns message after full frame received in one feed", function()
		local uf = M.unframer({ prefix = "u32_be" })
		local framed = M.frame("hello", { prefix = "u32_be" })
		uf:feed(framed)
		T.eq(uf:next(), "hello")
	end)
	T.it("returns nil after consuming the only message", function()
		local uf = M.unframer({ prefix = "u32_be" })
		uf:feed(M.frame("hello", { prefix = "u32_be" }))
		uf:next()
		T.eq(uf:next(), nil)
	end)
	T.it("returns message after two partial feeds", function()
		local uf = M.unframer({ prefix = "u32_be" })
		local framed = M.frame("world", { prefix = "u32_be" })
		-- split at byte 5 (after 4-byte header + 1 byte payload)
		uf:feed(framed:sub(1, 5))
		T.eq(uf:next(), nil)  -- not yet complete
		uf:feed(framed:sub(6))
		T.eq(uf:next(), "world")
	end)
	T.it("returns two messages fed together", function()
		local uf = M.unframer({ prefix = "u32_be" })
		uf:feed(M.frame("first",  { prefix = "u32_be" }))
		uf:feed(M.frame("second", { prefix = "u32_be" }))
		T.eq(uf:next(), "first")
		T.eq(uf:next(), "second")
		T.eq(uf:next(), nil)
	end)
	T.it("works with varint prefix", function()
		local uf = M.unframer({ prefix = "varint" })
		uf:feed(M.frame("varint-msg", { prefix = "varint" }))
		T.eq(uf:next(), "varint-msg")
	end)
	T.it("works with u16_be prefix", function()
		local uf = M.unframer({ prefix = "u16_be" })
		uf:feed(M.frame("short", { prefix = "u16_be" }))
		T.eq(uf:next(), "short")
	end)
end)

-- ---------------------------------------------------------------------------
-- _tier
-- ---------------------------------------------------------------------------
T.describe("module meta", function()
	T.it("_tier is ffi (uses FFI unions for float/double)", function()
		T.eq(M._tier, "ffi")
	end)
end)
