if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local heap = require("lib.heap")

T.describe("heap", function()

  T.describe("min-heap", function()
    T.it("returns elements in ascending order", function()
      local h = heap.new()
      h:push(5)
      h:push(3)
      h:push(8)
      h:push(1)
      h:push(9)
      T.eq(h:pop(), 1)
      T.eq(h:pop(), 3)
      T.eq(h:pop(), 5)
      T.eq(h:pop(), 8)
      T.eq(h:pop(), 9)
    end)

    T.it("default mode is min", function()
      local h = heap.new("min")
      h:push(10)
      h:push(2)
      h:push(7)
      T.eq(h:pop(), 2)
      T.eq(h:pop(), 7)
      T.eq(h:pop(), 10)
    end)

    T.it("handles negative numbers", function()
      local h = heap.new()
      h:push(-3)
      h:push(0)
      h:push(-10)
      h:push(5)
      T.eq(h:pop(), -10)
      T.eq(h:pop(), -3)
      T.eq(h:pop(), 0)
      T.eq(h:pop(), 5)
    end)
  end)

  T.describe("max-heap", function()
    T.it("returns elements in descending order", function()
      local h = heap.new("max")
      h:push(5)
      h:push(3)
      h:push(8)
      h:push(1)
      h:push(9)
      T.eq(h:pop(), 9)
      T.eq(h:pop(), 8)
      T.eq(h:pop(), 5)
      T.eq(h:pop(), 3)
      T.eq(h:pop(), 1)
    end)

    T.it("handles single element", function()
      local h = heap.new("max")
      h:push(42)
      T.eq(h:pop(), 42)
      T.eq(h:pop(), nil)
    end)
  end)

  T.describe("custom comparator", function()
    T.it("sorts by custom field", function()
      local h = heap.new(function(a, b) return a.priority < b.priority end)
      h:push({ name = "low", priority = 10 })
      h:push({ name = "high", priority = 1 })
      h:push({ name = "med", priority = 5 })
      T.eq(h:pop().name, "high")
      T.eq(h:pop().name, "med")
      T.eq(h:pop().name, "low")
    end)

    T.it("reverse string sort", function()
      local h = heap.new(function(a, b) return a > b end)
      h:push("apple")
      h:push("cherry")
      h:push("banana")
      T.eq(h:pop(), "cherry")
      T.eq(h:pop(), "banana")
      T.eq(h:pop(), "apple")
    end)
  end)

  T.describe("peek", function()
    T.it("returns top without removing", function()
      local h = heap.new()
      h:push(3)
      h:push(1)
      h:push(5)
      T.eq(h:peek(), 1)
      T.eq(h:size(), 3)
      T.eq(h:peek(), 1)
      T.eq(h:size(), 3)
    end)

    T.it("returns nil on empty heap", function()
      local h = heap.new()
      T.eq(h:peek(), nil)
    end)
  end)

  T.describe("size and empty", function()
    T.it("tracks size correctly", function()
      local h = heap.new()
      T.eq(h:size(), 0)
      T.ok(h:empty())
      h:push(1)
      T.eq(h:size(), 1)
      T.ok(not h:empty())
      h:push(2)
      T.eq(h:size(), 2)
      h:pop()
      T.eq(h:size(), 1)
      h:pop()
      T.eq(h:size(), 0)
      T.ok(h:empty())
    end)

    T.it("pop on empty returns nil", function()
      local h = heap.new()
      T.eq(h:pop(), nil)
      T.eq(h:size(), 0)
    end)
  end)

  T.describe("clear", function()
    T.it("removes all elements", function()
      local h = heap.new()
      h:push(1)
      h:push(2)
      h:push(3)
      T.eq(h:size(), 3)
      h:clear()
      T.eq(h:size(), 0)
      T.ok(h:empty())
      T.eq(h:pop(), nil)
    end)
  end)

  T.describe("from_array", function()
    T.it("builds min-heap from array", function()
      local h = heap.from_array({ 5, 3, 8, 1, 9, 2 })
      T.eq(h:size(), 6)
      T.eq(h:pop(), 1)
      T.eq(h:pop(), 2)
      T.eq(h:pop(), 3)
      T.eq(h:pop(), 5)
      T.eq(h:pop(), 8)
      T.eq(h:pop(), 9)
    end)

    T.it("builds max-heap from array", function()
      local h = heap.from_array({ 5, 3, 8, 1, 9 }, "max")
      T.eq(h:pop(), 9)
      T.eq(h:pop(), 8)
      T.eq(h:pop(), 5)
      T.eq(h:pop(), 3)
      T.eq(h:pop(), 1)
    end)

    T.it("handles empty array", function()
      local h = heap.from_array({})
      T.ok(h:empty())
      T.eq(h:pop(), nil)
    end)

    T.it("handles single element array", function()
      local h = heap.from_array({ 42 })
      T.eq(h:size(), 1)
      T.eq(h:pop(), 42)
    end)

    T.it("does not modify original array", function()
      local arr = { 5, 3, 1 }
      heap.from_array(arr)
      T.eq(arr[1], 5)
      T.eq(arr[2], 3)
      T.eq(arr[3], 1)
    end)
  end)

  T.describe("drain", function()
    T.it("yields all elements in order", function()
      local h = heap.from_array({ 5, 3, 8, 1 })
      local result = {}
      for val in h:drain() do
        result[#result + 1] = val
      end
      T.eq(#result, 4)
      T.eq(result[1], 1)
      T.eq(result[2], 3)
      T.eq(result[3], 5)
      T.eq(result[4], 8)
      T.ok(h:empty())
    end)

    T.it("works on empty heap", function()
      local h = heap.new()
      local count = 0
      for _ in h:drain() do count = count + 1 end
      T.eq(count, 0)
    end)
  end)

  T.describe("to_sorted_array", function()
    T.it("returns sorted array without modifying heap", function()
      local h = heap.from_array({ 5, 3, 8, 1, 9 })
      local sorted = h:to_sorted_array()
      T.eq(#sorted, 5)
      T.eq(sorted[1], 1)
      T.eq(sorted[2], 3)
      T.eq(sorted[3], 5)
      T.eq(sorted[4], 8)
      T.eq(sorted[5], 9)
      -- Original heap is intact
      T.eq(h:size(), 5)
      T.eq(h:peek(), 1)
    end)

    T.it("works on empty heap", function()
      local h = heap.new()
      local sorted = h:to_sorted_array()
      T.eq(#sorted, 0)
    end)
  end)

  T.describe("merge", function()
    T.it("merges two min-heaps", function()
      local h1 = heap.from_array({ 1, 5, 9 })
      local h2 = heap.from_array({ 2, 4, 8 })
      local merged = heap.merge(h1, h2)
      T.eq(merged:size(), 6)
      T.eq(merged:pop(), 1)
      T.eq(merged:pop(), 2)
      T.eq(merged:pop(), 4)
      T.eq(merged:pop(), 5)
      T.eq(merged:pop(), 8)
      T.eq(merged:pop(), 9)
    end)

    T.it("merges with an empty heap", function()
      local h1 = heap.from_array({ 3, 1, 2 })
      local h2 = heap.new()
      local merged = heap.merge(h1, h2)
      T.eq(merged:size(), 3)
      T.eq(merged:pop(), 1)
    end)

    T.it("merges two empty heaps", function()
      local h1 = heap.new()
      local h2 = heap.new()
      local merged = heap.merge(h1, h2)
      T.ok(merged:empty())
    end)

    T.it("does not modify originals", function()
      local h1 = heap.from_array({ 1, 2 })
      local h2 = heap.from_array({ 3, 4 })
      heap.merge(h1, h2)
      T.eq(h1:size(), 2)
      T.eq(h2:size(), 2)
    end)
  end)

  T.describe("heap.sort", function()
    T.it("sorts ascending by default", function()
      local sorted = heap.sort({ 5, 3, 8, 1, 9, 2 })
      T.eq(sorted[1], 1)
      T.eq(sorted[2], 2)
      T.eq(sorted[3], 3)
      T.eq(sorted[4], 5)
      T.eq(sorted[5], 8)
      T.eq(sorted[6], 9)
    end)

    T.it("sorts descending", function()
      local sorted = heap.sort({ 5, 3, 8, 1, 9 }, "desc")
      T.eq(sorted[1], 9)
      T.eq(sorted[2], 8)
      T.eq(sorted[3], 5)
      T.eq(sorted[4], 3)
      T.eq(sorted[5], 1)
    end)

    T.it("handles empty array", function()
      local sorted = heap.sort({})
      T.eq(#sorted, 0)
    end)

    T.it("handles single element", function()
      local sorted = heap.sort({ 7 })
      T.eq(sorted[1], 7)
      T.eq(#sorted, 1)
    end)

    T.it("does not modify original", function()
      local arr = { 3, 1, 2 }
      heap.sort(arr)
      T.eq(arr[1], 3)
      T.eq(arr[2], 1)
      T.eq(arr[3], 2)
    end)

    T.it("handles duplicates", function()
      local sorted = heap.sort({ 3, 1, 3, 1, 2 })
      T.eq(sorted[1], 1)
      T.eq(sorted[2], 1)
      T.eq(sorted[3], 2)
      T.eq(sorted[4], 3)
      T.eq(sorted[5], 3)
    end)
  end)

  T.describe("separate priority mode", function()
    T.it("push with priority orders by priority", function()
      local h = heap.new()
      h:push("task_c", 3)
      h:push("task_a", 1)
      h:push("task_b", 2)
      T.eq(h:pop(), "task_a")
      T.eq(h:pop(), "task_b")
      T.eq(h:pop(), "task_c")
    end)

    T.it("peek returns the key not the pair", function()
      local h = heap.new()
      h:push("urgent", 1)
      h:push("lazy", 100)
      T.eq(h:peek(), "urgent")
    end)

    T.it("peek_priority returns priority of top", function()
      local h = heap.new()
      h:push("urgent", 1)
      h:push("lazy", 100)
      T.eq(h:peek_priority(), 1)
    end)

    T.it("returns nil on duplicate key push", function()
      local h = heap.new()
      h:push("a", 1)
      local ok, err = h:push("a", 2)
      T.eq(ok, nil)
      T.ok(err)
    end)

    T.it("max-heap with priorities", function()
      local h = heap.new("max")
      h:push("low", 1)
      h:push("high", 10)
      h:push("med", 5)
      T.eq(h:pop(), "high")
      T.eq(h:pop(), "med")
      T.eq(h:pop(), "low")
    end)
  end)

  T.describe("push_or_update", function()
    T.it("inserts new keys", function()
      local h = heap.new()
      h:push_or_update("a", 3)
      h:push_or_update("b", 1)
      h:push_or_update("c", 2)
      T.eq(h:size(), 3)
      T.eq(h:pop(), "b")
      T.eq(h:pop(), "c")
      T.eq(h:pop(), "a")
    end)

    T.it("updates existing key to higher priority", function()
      local h = heap.new()
      h:push_or_update("a", 10)
      h:push_or_update("b", 5)
      h:push_or_update("c", 20)
      -- Update 'c' to highest priority (lowest number for min-heap)
      h:push_or_update("c", 1)
      T.eq(h:peek(), "c")
      T.eq(h:pop(), "c")
      T.eq(h:pop(), "b")
      T.eq(h:pop(), "a")
    end)

    T.it("updates existing key to lower priority", function()
      local h = heap.new()
      h:push_or_update("a", 1)
      h:push_or_update("b", 2)
      h:push_or_update("c", 3)
      -- Demote 'a' to lowest priority
      h:push_or_update("a", 100)
      T.eq(h:pop(), "b")
      T.eq(h:pop(), "c")
      T.eq(h:pop(), "a")
    end)

    T.it("works with max-heap", function()
      local h = heap.new("max")
      h:push_or_update("a", 1)
      h:push_or_update("b", 10)
      h:push_or_update("a", 100)
      T.eq(h:pop(), "a")
      T.eq(h:pop(), "b")
    end)
  end)

  T.describe("remove", function()
    T.it("removes a key from keyed heap", function()
      local h = heap.new()
      h:push_or_update("a", 1)
      h:push_or_update("b", 2)
      h:push_or_update("c", 3)
      local ok = h:remove("a")
      T.ok(ok)
      T.eq(h:size(), 2)
      T.eq(h:pop(), "b")
      T.eq(h:pop(), "c")
    end)

    T.it("removes middle element", function()
      local h = heap.new()
      h:push_or_update("a", 1)
      h:push_or_update("b", 5)
      h:push_or_update("c", 10)
      h:push_or_update("d", 3)
      local ok = h:remove("b")
      T.ok(ok)
      T.eq(h:size(), 3)
      T.eq(h:pop(), "a")
      T.eq(h:pop(), "d")
      T.eq(h:pop(), "c")
    end)

    T.it("returns false for non-existent key", function()
      local h = heap.new()
      h:push_or_update("a", 1)
      T.eq(h:remove("nonexistent"), false)
    end)

    T.it("returns error on non-keyed heap", function()
      local h = heap.new()
      h:push(1)
      local ok, err = h:remove(1)
      T.eq(ok, nil)
      T.ok(err)
    end)

    T.it("removes last element", function()
      local h = heap.new()
      h:push_or_update("only", 1)
      T.ok(h:remove("only"))
      T.ok(h:empty())
    end)
  end)

  T.describe("edge cases", function()
    T.it("duplicate values in unkeyed heap", function()
      local h = heap.new()
      h:push(3)
      h:push(3)
      h:push(3)
      T.eq(h:size(), 3)
      T.eq(h:pop(), 3)
      T.eq(h:pop(), 3)
      T.eq(h:pop(), 3)
      T.ok(h:empty())
    end)

    T.it("alternating push and pop", function()
      local h = heap.new()
      h:push(5)
      h:push(3)
      T.eq(h:pop(), 3)
      h:push(1)
      T.eq(h:pop(), 1)
      h:push(4)
      T.eq(h:pop(), 4)
      T.eq(h:pop(), 5)
      T.eq(h:pop(), nil)
    end)

    T.it("string values", function()
      local h = heap.new()
      h:push("banana")
      h:push("apple")
      h:push("cherry")
      T.eq(h:pop(), "apple")
      T.eq(h:pop(), "banana")
      T.eq(h:pop(), "cherry")
    end)
  end)

  T.describe("large heap", function()
    T.it("maintains invariant with 200 elements", function()
      local h = heap.new()
      -- Insert 200 elements in pseudo-random order
      local vals = {}
      for i = 1, 200 do
        vals[i] = (i * 97 + 13) % 200
      end
      for i = 1, 200 do
        h:push(vals[i])
      end
      T.eq(h:size(), 200)
      -- Pop all and verify ascending
      local prev = h:pop()
      for _ = 2, 200 do
        local cur = h:pop()
        T.ok(cur >= prev, "expected ascending order")
        prev = cur
      end
      T.ok(h:empty())
    end)

    T.it("from_array with 150 elements", function()
      local arr = {}
      for i = 1, 150 do
        arr[i] = 151 - i
      end
      local h = heap.from_array(arr)
      T.eq(h:size(), 150)
      T.eq(h:peek(), 1)
      local prev = h:pop()
      for _ = 2, 150 do
        local cur = h:pop()
        T.ok(cur >= prev)
        prev = cur
      end
    end)

    T.it("heap.sort with 100 elements", function()
      local arr = {}
      for i = 1, 100 do
        arr[i] = (i * 53 + 7) % 100
      end
      local sorted = heap.sort(arr)
      T.eq(#sorted, 100)
      for i = 2, 100 do
        T.ok(sorted[i] >= sorted[i - 1], "expected sorted order")
      end
    end)
  end)

end)
