-- lib/format/yaml/yaml_test.lua
-- Tests for the YAML 1.2 decoder/encoder.

if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T    = require("lib.test.assert")
local yaml = require("lib.format.yaml")

-- ── Scalar decoding ───────────────────────────────────────────────────────────

T.describe("scalars", function()
	T.it("bare integer", function()
		T.eq(yaml.decode("42"), 42)
	end)
	T.it("negative integer", function()
		T.eq(yaml.decode("-7"), -7)
	end)
	T.it("float", function()
		T.eq(yaml.decode("3.14"), 3.14)
	end)
	T.it("true boolean", function()
		T.eq(yaml.decode("true"), true)
	end)
	T.it("false boolean", function()
		T.eq(yaml.decode("false"), false)
	end)
	T.it("null → nil", function()
		T.eq(yaml.decode("null"), nil)
	end)
	T.it("tilde → nil", function()
		T.eq(yaml.decode("~"), nil)
	end)
	T.it("empty string → nil", function()
		T.eq(yaml.decode(""), nil)
	end)
	T.it("double-quoted string", function()
		T.eq(yaml.decode('"hello world"'), "hello world")
	end)
	T.it("single-quoted string", function()
		T.eq(yaml.decode("'hello world'"), "hello world")
	end)
	T.it("plain string", function()
		T.eq(yaml.decode("hello"), "hello")
	end)
	T.it("double-quoted escape sequences", function()
		T.eq(yaml.decode('"tab:\\there"'), "tab:\there")
	end)
	T.it("double-quoted newline escape", function()
		T.eq(yaml.decode('"line1\\nline2"'), "line1\nline2")
	end)
end)

-- ── Block mappings ────────────────────────────────────────────────────────────

T.describe("block mappings", function()
	T.it("single key-value", function()
		local v = yaml.decode("key: value\n")
		T.eq(type(v), "table")
		T.eq(v.key, "value")
	end)
	T.it("multiple keys", function()
		local v = yaml.decode("a: 1\nb: 2\nc: 3\n")
		T.eq(v.a, 1)
		T.eq(v.b, 2)
		T.eq(v.c, 3)
	end)
	T.it("string values", function()
		local v = yaml.decode("name: Alice\ncity: London\n")
		T.eq(v.name, "Alice")
		T.eq(v.city, "London")
	end)
	T.it("integer values", function()
		local v = yaml.decode("x: 10\ny: 20\n")
		T.eq(v.x, 10)
		T.eq(v.y, 20)
	end)
	T.it("boolean values", function()
		local v = yaml.decode("flag: true\nother: false\n")
		T.eq(v.flag, true)
		T.eq(v.other, false)
	end)
	T.it("null values", function()
		local v = yaml.decode("a: null\nb: ~\n")
		T.eq(v.a, nil)
		T.eq(v.b, nil)
	end)
	T.it("nested mapping one level", function()
		local v = yaml.decode("outer:\n  inner: value\n")
		T.eq(type(v.outer), "table")
		T.eq(v.outer.inner, "value")
	end)
	T.it("nested mapping two levels", function()
		local v = yaml.decode("a:\n  b:\n    c: deep\n")
		T.eq(type(v.a), "table")
		T.eq(type(v.a.b), "table")
		T.eq(v.a.b.c, "deep")
	end)
	T.it("sibling keys after nested", function()
		local v = yaml.decode("a:\n  x: 1\nb: 2\n")
		T.eq(v.a.x, 1)
		T.eq(v.b, 2)
	end)
end)

-- ── Block sequences ───────────────────────────────────────────────────────────

T.describe("block sequences", function()
	T.it("sequence of strings", function()
		local v = yaml.decode("- one\n- two\n- three\n")
		T.eq(type(v), "table")
		T.eq(#v, 3)
		T.eq(v[1], "one")
		T.eq(v[2], "two")
		T.eq(v[3], "three")
	end)
	T.it("sequence of numbers", function()
		local v = yaml.decode("- 1\n- 2\n- 3\n")
		T.eq(v[1], 1)
		T.eq(v[2], 2)
		T.eq(v[3], 3)
	end)
	T.it("sequence under a key", function()
		local v = yaml.decode("items:\n  - a\n  - b\n")
		T.eq(type(v.items), "table")
		T.eq(#v.items, 2)
		T.eq(v.items[1], "a")
		T.eq(v.items[2], "b")
	end)
	T.it("sequence of mappings", function()
		local v = yaml.decode("- name: Alice\n  age: 30\n- name: Bob\n  age: 25\n")
		T.eq(type(v), "table")
		T.eq(#v, 2)
		T.eq(v[1].name, "Alice")
		T.eq(v[1].age, 30)
		T.eq(v[2].name, "Bob")
		T.eq(v[2].age, 25)
	end)
end)

-- ── Flow style ────────────────────────────────────────────────────────────────

T.describe("flow mappings", function()
	T.it("empty flow map", function()
		local v = yaml.decode("{}")
		T.eq(type(v), "table")
	end)
	T.it("single key flow map", function()
		local v = yaml.decode("{a: 1}")
		T.eq(v.a, 1)
	end)
	T.it("multi-key flow map", function()
		local v = yaml.decode("{x: 1, y: 2, z: 3}")
		T.eq(v.x, 1)
		T.eq(v.y, 2)
		T.eq(v.z, 3)
	end)
	T.it("flow map string values", function()
		local v = yaml.decode('{name: "Alice", city: London}')
		T.eq(v.name, "Alice")
		T.eq(v.city, "London")
	end)
end)

T.describe("flow sequences", function()
	T.it("empty flow seq", function()
		local v = yaml.decode("[]")
		T.eq(type(v), "table")
		T.eq(#v, 0)
	end)
	T.it("single element", function()
		local v = yaml.decode("[42]")
		T.eq(#v, 1)
		T.eq(v[1], 42)
	end)
	T.it("multiple elements", function()
		local v = yaml.decode("[1, 2, 3]")
		T.eq(#v, 3)
		T.eq(v[1], 1)
		T.eq(v[2], 2)
		T.eq(v[3], 3)
	end)
	T.it("mixed types", function()
		local v = yaml.decode('[1, "two", true, null]')
		T.eq(v[1], 1)
		T.eq(v[2], "two")
		T.eq(v[3], true)
		T.eq(v[4], nil)
	end)
end)

-- ── Anchors and aliases ───────────────────────────────────────────────────────

T.describe("anchors and aliases", function()
	T.it("basic alias", function()
		local v = yaml.decode("a: &anchor hello\nb: *anchor\n")
		T.eq(v.a, "hello")
		T.eq(v.b, "hello")
	end)
	T.it("anchor in sequence", function()
		local v = yaml.decode("- &x 42\n- *x\n")
		T.eq(v[1], 42)
		T.eq(v[2], 42)
	end)
end)

-- ── Literal/folded blocks ─────────────────────────────────────────────────────

T.describe("block scalars", function()
	T.it("literal block preserves newlines", function()
		local v = yaml.decode("text: |\n  line one\n  line two\n")
		T.ok(type(v.text) == "string")
		T.ok(v.text:find("line one") ~= nil)
		T.ok(v.text:find("line two") ~= nil)
	end)
	T.it("folded block folds newlines", function()
		local v = yaml.decode("text: >\n  folded\n  content\n")
		T.ok(type(v.text) == "string")
	end)
end)

-- ── Comments ──────────────────────────────────────────────────────────────────

T.describe("comments", function()
	T.it("comment after value", function()
		local v = yaml.decode("key: value # comment\n")
		T.eq(v.key, "value")
	end)
	T.it("standalone comment line", function()
		local v = yaml.decode("# comment\nkey: value\n")
		T.eq(v.key, "value")
	end)
end)

-- ── Multi-document ────────────────────────────────────────────────────────────

T.describe("decode_all", function()
	T.it("single document", function()
		local docs = yaml.decode_all("key: value\n")
		T.eq(#docs, 1)
		T.eq(docs[1].key, "value")
	end)
	T.it("two documents separated by ---", function()
		local docs = yaml.decode_all("a: 1\n---\nb: 2\n")
		T.eq(#docs, 2)
		T.eq(docs[1].a, 1)
		T.eq(docs[2].b, 2)
	end)
end)

-- ── Encoder ───────────────────────────────────────────────────────────────────

T.describe("encode", function()
	T.it("string scalar", function()
		local s = yaml.encode("hello")
		T.ok(type(s) == "string")
		T.ok(#s > 0)
	end)
	T.it("integer scalar", function()
		local s = yaml.encode(42)
		T.ok(s:find("42") ~= nil)
	end)
	T.it("boolean true", function()
		local s = yaml.encode(true)
		T.ok(s:find("true") ~= nil)
	end)
	T.it("nil scalar", function()
		local s = yaml.encode(nil)
		T.ok(s:find("null") ~= nil or s:find("~") ~= nil)
	end)
	T.it("table with keys", function()
		local s = yaml.encode({ a = 1, b = 2 })
		T.ok(type(s) == "string")
		T.ok(s:find("a") ~= nil)
	end)
	T.it("array", function()
		local s = yaml.encode({ 1, 2, 3 })
		T.ok(type(s) == "string")
		T.ok(s:find("1") ~= nil)
	end)
	T.it("round-trip mapping", function()
		local orig = { name = "test", value = 99 }
		local s = yaml.encode(orig)
		local v = yaml.decode(s)
		T.eq(v.name, "test")
		T.eq(v.value, 99)
	end)
end)

-- ── Error handling ────────────────────────────────────────────────────────────

T.describe("error handling", function()
	T.it("unknown alias returns error", function()
		local v, err = yaml.decode("key: *no_such_anchor\n")
		T.ok(v == nil or err ~= nil or type(v) == "table")
		-- Either returns nil,err or partial parse; must not crash
	end)
end)

-- ── Aliases ───────────────────────────────────────────────────────────────────

T.describe("module aliases", function()
	T.it("encode alias exists", function()
		T.ok(yaml.encode ~= nil)
	end)
	T.it("decode alias exists", function()
		T.ok(yaml.decode ~= nil)
	end)
end)
