if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local struct = require("lib.struct")

T.describe("struct", function()

  -- ─── calcsize ────────────────────────────────────────────────────────────
  T.describe("calcsize", function()
    T.it("B → 1", function()
      T.eq(struct.calcsize("B"), 1)
    end)
    T.it("HI → 6", function()
      T.eq(struct.calcsize("HI"), 6)
    end)
    T.it("4B → 4", function()
      T.eq(struct.calcsize("4B"), 4)
    end)
    T.it(">HI → 6", function()
      T.eq(struct.calcsize(">HI"), 6)
    end)
    T.it("d → 8", function()
      T.eq(struct.calcsize("d"), 8)
    end)
    T.it("4s → 4", function()
      T.eq(struct.calcsize("4s"), 4)
    end)
    T.it("x → 1", function()
      T.eq(struct.calcsize("x"), 1)
    end)
    T.it("? → 1", function()
      T.eq(struct.calcsize("?"), 1)
    end)
    T.it("bBhHiIqQfd → 1+1+2+2+4+4+8+8+4+8=42", function()
      T.eq(struct.calcsize("bBhHiIqQfd"), 42)
    end)
  end)

  -- ─── uint8 ───────────────────────────────────────────────────────────────
  T.describe("B uint8", function()
    T.it("round-trip 0", function()
      local s = struct.pack("B", 0)
      T.eq(#s, 1)
      local v, next_off = struct.unpack("B", s)
      T.eq(v, 0)
      T.eq(next_off, 2)
    end)
    T.it("round-trip 255", function()
      local s = struct.pack("B", 255)
      local v = struct.unpack("B", s)
      T.eq(v, 255)
    end)
  end)

  -- ─── int8 ────────────────────────────────────────────────────────────────
  T.describe("b int8", function()
    T.it("round-trip -128", function()
      local s = struct.pack("b", -128)
      local v = struct.unpack("b", s)
      T.eq(v, -128)
    end)
    T.it("round-trip 127", function()
      local s = struct.pack("b", 127)
      local v = struct.unpack("b", s)
      T.eq(v, 127)
    end)
  end)

  -- ─── uint16 ──────────────────────────────────────────────────────────────
  T.describe("H uint16", function()
    T.it("round-trip 0", function()
      local s = struct.pack("H", 0)
      T.eq(#s, 2)
      local v = struct.unpack("H", s)
      T.eq(v, 0)
    end)
    T.it("round-trip 65535", function()
      local s = struct.pack("H", 65535)
      local v = struct.unpack("H", s)
      T.eq(v, 65535)
    end)
  end)

  -- ─── uint32 ──────────────────────────────────────────────────────────────
  T.describe("I uint32", function()
    T.it("round-trip 0", function()
      local s = struct.pack("I", 0)
      T.eq(#s, 4)
      local v = struct.unpack("I", s)
      T.eq(v, 0)
    end)
    T.it("round-trip 2^32-1", function()
      local s = struct.pack("I", 2^32 - 1)
      local v = struct.unpack("I", s)
      T.eq(v, 2^32 - 1)
    end)
  end)

  -- ─── byte order ──────────────────────────────────────────────────────────
  T.describe("byte order", function()
    T.it("<I vs >I for 0x01020304 differ", function()
      local le = struct.pack("<I", 0x01020304)
      local be = struct.pack(">I", 0x01020304)
      T.neq(le, be)
    end)
    T.it("<I bytes are LE (LSB first)", function()
      local s = struct.pack("<I", 0x01020304)
      -- LE: 04 03 02 01
      T.eq(s:byte(1), 0x04)
      T.eq(s:byte(2), 0x03)
      T.eq(s:byte(3), 0x02)
      T.eq(s:byte(4), 0x01)
    end)
    T.it(">I bytes are BE (MSB first)", function()
      local s = struct.pack(">I", 0x01020304)
      -- BE: 01 02 03 04
      T.eq(s:byte(1), 0x01)
      T.eq(s:byte(2), 0x02)
      T.eq(s:byte(3), 0x03)
      T.eq(s:byte(4), 0x04)
    end)
    T.it("<I unpack round-trip", function()
      local s = struct.pack("<I", 0x01020304)
      local v = struct.unpack("<I", s)
      T.eq(v, 0x01020304)
    end)
    T.it(">I unpack round-trip", function()
      local s = struct.pack(">I", 0x01020304)
      local v = struct.unpack(">I", s)
      T.eq(v, 0x01020304)
    end)
  end)

  -- ─── float32 ─────────────────────────────────────────────────────────────
  T.describe("f float32", function()
    T.it("round-trip 1.0", function()
      local s = struct.pack("f", 1.0)
      T.eq(#s, 4)
      local v = struct.unpack("f", s)
      T.ok(math.abs(v - 1.0) < 1e-6, "f32 1.0 round-trip")
    end)
    T.it("round-trip -1.0", function()
      local s = struct.pack("f", -1.0)
      local v = struct.unpack("f", s)
      T.ok(math.abs(v - (-1.0)) < 1e-6, "f32 -1.0 round-trip")
    end)
    T.it("round-trip 3.14", function()
      local s = struct.pack("f", 3.14)
      local v = struct.unpack("f", s)
      T.ok(math.abs(v - 3.14) < 0.001, "f32 3.14 round-trip")
    end)
  end)

  -- ─── float64 ─────────────────────────────────────────────────────────────
  T.describe("d float64", function()
    T.it("round-trip math.pi", function()
      local s = struct.pack("d", math.pi)
      T.eq(#s, 8)
      local v = struct.unpack("d", s)
      T.ok(math.abs(v - math.pi) < 1e-15, "f64 pi round-trip")
    end)
  end)

  -- ─── bool ────────────────────────────────────────────────────────────────
  T.describe("? bool", function()
    T.it("pack true → 0x01", function()
      local s = struct.pack("?", true)
      T.eq(s:byte(1), 1)
    end)
    T.it("pack false → 0x00", function()
      local s = struct.pack("?", false)
      T.eq(s:byte(1), 0)
    end)
    T.it("unpack 0x01 → true", function()
      local v = struct.unpack("?", "\1")
      T.eq(v, true)
    end)
    T.it("unpack 0x00 → false", function()
      local v = struct.unpack("?", "\0")
      T.eq(v, false)
    end)
  end)

  -- ─── string ──────────────────────────────────────────────────────────────
  T.describe("Ns string", function()
    T.it("4s round-trip 'ABCD'", function()
      local s = struct.pack("4s", "ABCD")
      T.eq(#s, 4)
      local v = struct.unpack("4s", s)
      T.eq(v, "ABCD")
    end)
    T.it("4s short string gets zero-padded", function()
      local s = struct.pack("4s", "AB")
      T.eq(#s, 4)
      T.eq(s, "AB\0\0")
    end)
    T.it("4s long string gets truncated", function()
      local s = struct.pack("4s", "ABCDEF")
      T.eq(s, "ABCD")
    end)
    T.it("1s (c) round-trip", function()
      local s = struct.pack("1s", "Z")
      local v = struct.unpack("1s", s)
      T.eq(v, "Z")
    end)
  end)

  -- ─── pad byte ────────────────────────────────────────────────────────────
  T.describe("x pad", function()
    T.it("x adds zero byte and is skipped on unpack", function()
      -- pack B x B: value, pad, value
      local s = struct.pack("BxB", 10, 20)
      T.eq(#s, 3)
      T.eq(s:byte(1), 10)
      T.eq(s:byte(2), 0)   -- pad
      T.eq(s:byte(3), 20)
      local a, b, next_off = struct.unpack("BxB", s)
      T.eq(a, 10)
      T.eq(b, 20)
      T.eq(next_off, 4)
    end)
    T.it("2x skips 2 bytes", function()
      local s = struct.pack("B2xB", 1, 2)
      T.eq(#s, 4)
      local a, b = struct.unpack("B2xB", s)
      T.eq(a, 1)
      T.eq(b, 2)
    end)
  end)

  -- ─── compound ────────────────────────────────────────────────────────────
  T.describe("compound format", function()
    T.it("<BHI round-trip", function()
      local s = struct.pack("<BHI", 42, 1000, 100000)
      T.eq(#s, 7)
      local a, b, c = struct.unpack("<BHI", s)
      T.eq(a, 42)
      T.eq(b, 1000)
      T.eq(c, 100000)
    end)
    T.it("4B multi-byte", function()
      local s = struct.pack("4B", 1, 2, 3, 4)
      T.eq(#s, 4)
      local a, b, c, d = struct.unpack("4B", s)
      T.eq(a, 1)
      T.eq(b, 2)
      T.eq(c, 3)
      T.eq(d, 4)
    end)
  end)

  -- ─── int64 / uint64 ──────────────────────────────────────────────────────
  T.describe("q/Q 64-bit", function()
    T.it("q int64 round-trip 0", function()
      local s = struct.pack("q", 0)
      T.eq(#s, 8)
      local v = struct.unpack("q", s)
      T.eq(v, 0)
    end)
    T.it("Q uint64 round-trip 2^32", function()
      local s = struct.pack("Q", 2^32)
      local v = struct.unpack("Q", s)
      T.eq(v, 2^32)
    end)
    T.it("q int64 round-trip negative", function()
      local s = struct.pack("q", -1)
      local v = struct.unpack("q", s)
      T.eq(v, -1)
    end)
  end)

  -- ─── compile ─────────────────────────────────────────────────────────────
  T.describe("compile", function()
    T.it("compiled:pack matches direct pack", function()
      local c = struct.compile("<BHI")
      T.ok(c ~= nil, "compile returns object")
      local direct = struct.pack("<BHI", 7, 300, 70000)
      local compiled = c:pack(7, 300, 70000)
      T.eq(direct, compiled)
    end)
    T.it("compiled:unpack matches direct unpack", function()
      local c = struct.compile("<BHI")
      local s = struct.pack("<BHI", 7, 300, 70000)
      local a1, b1, c1 = struct.unpack("<BHI", s)
      local a2, b2, c2 = c:unpack(s)
      T.eq(a1, a2)
      T.eq(b1, b2)
      T.eq(c1, c2)
    end)
    T.it("compiled:size returns correct size", function()
      local c = struct.compile("<BHI")
      T.eq(c:size(), 7)
    end)
  end)

  -- ─── offset ──────────────────────────────────────────────────────────────
  T.describe("unpack offset", function()
    T.it("unpack at offset 2 skips leading byte", function()
      -- Prepend a junk byte, then pack B at position 2
      local prefix = "\xFF"
      local data = prefix .. struct.pack("B", 99)
      local v = struct.unpack("B", data, 2)
      T.eq(v, 99)
    end)
    T.it("unpack returns correct next_offset", function()
      local s = struct.pack("BH", 1, 500)
      -- Unpack just B at offset 1; next_off should be 2
      local v, next_off = struct.unpack("B", s)
      T.eq(v, 1)
      T.eq(next_off, 2)
      -- Then unpack H at offset 2
      local v2, next_off2 = struct.unpack("H", s, next_off)
      T.eq(v2, 500)
      T.eq(next_off2, 4)
    end)
  end)

  -- ─── error cases ─────────────────────────────────────────────────────────
  T.describe("errors", function()
    T.it("unknown format char returns nil, errmsg", function()
      local s, err = struct.pack("Z", 1)
      T.eq(s, nil)
      T.ok(err ~= nil, "error message present")
    end)
    T.it("buffer too short for unpack", function()
      local v, err = struct.unpack("I", "\x01\x02")  -- only 2 bytes, need 4
      T.eq(v, nil)
      T.ok(err ~= nil, "error message present")
    end)
    T.it("B out of range high", function()
      local s, err = struct.pack("B", 256)
      T.eq(s, nil)
      T.ok(err ~= nil, "error message present")
    end)
    T.it("B out of range low", function()
      local s, err = struct.pack("B", -1)
      T.eq(s, nil)
      T.ok(err ~= nil, "error message present")
    end)
    T.it("b out of range high", function()
      local s, err = struct.pack("b", 128)
      T.eq(s, nil)
      T.ok(err ~= nil, "error message present")
    end)
    T.it("calcsize unknown char returns nil, errmsg", function()
      local n, err = struct.calcsize("Z")
      T.eq(n, nil)
      T.ok(err ~= nil, "error message present")
    end)
    T.it("trailing count with no char returns error", function()
      local s, err = struct.pack("4", 1, 2, 3, 4)
      T.eq(s, nil)
      T.ok(err ~= nil, "error message present")
    end)
  end)

  -- ─── _tier ───────────────────────────────────────────────────────────────
  T.describe("module meta", function()
    T.it("_tier is 'ffi'", function()
      T.eq(struct._tier, "ffi")
    end)
  end)

end)
