if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.math_ext")

T.describe("math_ext", function()

  T.describe("number utilities", function()
    T.it("clamp", function()
      T.eq(M.clamp(5, 0, 10), 5)
      T.eq(M.clamp(-1, 0, 10), 0)
      T.eq(M.clamp(15, 0, 10), 10)
      T.eq(M.clamp(0, 0, 10), 0)
      T.eq(M.clamp(10, 0, 10), 10)
    end)

    T.it("lerp", function()
      T.eq(M.lerp(0, 10, 0), 0)
      T.eq(M.lerp(0, 10, 1), 10)
      T.eq(M.lerp(0, 10, 0.5), 5)
      T.eq(M.lerp(2, 6, 0.25), 3)
    end)

    T.it("lerp_inv", function()
      T.eq(M.lerp_inv(0, 10, 5), 0.5)
      T.eq(M.lerp_inv(0, 10, 0), 0)
      T.eq(M.lerp_inv(0, 10, 10), 1)
      local v, err = M.lerp_inv(5, 5, 3)
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)

    T.it("remap", function()
      T.eq(M.remap(5, 0, 10, 0, 100), 50)
      T.eq(M.remap(0, 0, 10, 0, 100), 0)
      T.eq(M.remap(10, 0, 10, 0, 100), 100)
    end)

    T.it("smoothstep", function()
      T.eq(M.smoothstep(0, 1, 0), 0)
      T.eq(M.smoothstep(0, 1, 1), 1)
      -- midpoint is 0.5
      T.ok(M.approx_eq(M.smoothstep(0, 1, 0.5), 0.5))
      -- monotonically between 0 and 1
      T.ok(M.smoothstep(0, 1, 0.25) > 0 and M.smoothstep(0, 1, 0.25) < 0.5)
    end)

    T.it("sign", function()
      T.eq(M.sign(5), 1)
      T.eq(M.sign(-3), -1)
      T.eq(M.sign(0), 0)
    end)

    T.it("round", function()
      T.eq(M.round(3.4), 3)
      T.eq(M.round(3.5), 4)
      T.eq(M.round(3.567, 2), 3.57)
      T.eq(M.round(3.565, 2), 3.57)
      T.eq(M.round(-2.5), -2)
    end)

    T.it("round_to", function()
      T.eq(M.round_to(7, 5), 5)
      T.eq(M.round_to(8, 5), 10)
      T.eq(M.round_to(10, 3), 9)
    end)

    T.it("floor_to / ceil_to", function()
      T.eq(M.floor_to(9, 4), 8)
      T.eq(M.ceil_to(9, 4), 12)
    end)

    T.it("trunc", function()
      T.eq(M.trunc(3.9), 3)
      T.eq(M.trunc(-3.9), -3)
    end)

    T.it("frac", function()
      T.ok(M.approx_eq(M.frac(3.75), 0.75))
      T.ok(M.approx_eq(M.frac(-0.25), 0.75))
    end)

    T.it("wrap", function()
      T.eq(M.wrap(0, 0, 10), 0)
      T.eq(M.wrap(10, 0, 10), 0)
      T.eq(M.wrap(11, 0, 10), 1)
      T.eq(M.wrap(-1, 0, 10), 9)
      T.eq(M.wrap(5, 0, 10), 5)
    end)

    T.it("snap", function()
      T.eq(M.snap(7, 5), 5)
      T.eq(M.snap(8, 5), 10)
    end)

    T.it("approx_eq", function()
      T.ok(M.approx_eq(1.0, 1.0))
      T.ok(M.approx_eq(1.0, 1.0 + 1e-10))
      T.ok(not M.approx_eq(1.0, 1.1))
      T.ok(M.approx_eq(1.0, 1.05, 0.1))
    end)
  end)

  T.describe("number theory", function()
    T.it("gcd", function()
      T.eq(M.gcd(12, 8), 4)
      T.eq(M.gcd(7, 3), 1)
      T.eq(M.gcd(0, 5), 5)
      T.eq(M.gcd(100, 25), 25)
    end)

    T.it("lcm", function()
      T.eq(M.lcm(4, 6), 12)
      T.eq(M.lcm(3, 7), 21)
      T.eq(M.lcm(0, 5), 0)
    end)

    T.it("is_prime", function()
      T.ok(not M.is_prime(1))
      T.ok(M.is_prime(2))
      T.ok(M.is_prime(3))
      T.ok(not M.is_prime(4))
      T.ok(M.is_prime(97))
      T.ok(not M.is_prime(100))
    end)

    T.it("next_prime", function()
      T.eq(M.next_prime(1), 2)
      T.eq(M.next_prime(2), 3)
      T.eq(M.next_prime(10), 11)
    end)

    T.it("primes", function()
      local p = M.primes(20)
      T.eq(#p, 8)
      T.eq(p[1], 2)
      T.eq(p[#p], 19)
      T.eq(#M.primes(1), 0)
    end)

    T.it("factorize", function()
      local f = M.factorize(12)
      T.eq(f[2], 2)
      T.eq(f[3], 1)
      local f2 = M.factorize(7)
      T.eq(f2[7], 1)
      local f3 = M.factorize(1)
      T.eq(next(f3), nil)
    end)

    T.it("is_power_of_two", function()
      T.ok(M.is_power_of_two(1))
      T.ok(M.is_power_of_two(2))
      T.ok(M.is_power_of_two(16))
      T.ok(not M.is_power_of_two(0))
      T.ok(not M.is_power_of_two(3))
      T.ok(not M.is_power_of_two(6))
    end)

    T.it("next_power_of_two", function()
      T.eq(M.next_power_of_two(1), 1)
      T.eq(M.next_power_of_two(5), 8)
      T.eq(M.next_power_of_two(8), 8)
      T.eq(M.next_power_of_two(9), 16)
    end)

    T.it("digits / from_digits round-trip base 10", function()
      local d = M.digits(12345)
      T.eq(d[1], 5); T.eq(d[2], 4); T.eq(d[3], 3); T.eq(d[4], 2); T.eq(d[5], 1)
      T.eq(M.from_digits(d, 10), 12345)
      T.eq(M.from_digits(M.digits(0)), 0)
    end)

    T.it("digits / from_digits round-trip base 2", function()
      local d = M.digits(10, 2)
      T.eq(M.from_digits(d, 2), 10)
      -- 10 in binary is 1010: digits LSB-first = {0,1,0,1}
      T.eq(d[1], 0); T.eq(d[2], 1); T.eq(d[3], 0); T.eq(d[4], 1)
    end)

    T.it("sum_digits / digit_count", function()
      T.eq(M.sum_digits(123), 6)
      T.eq(M.digit_count(999), 3)
      T.eq(M.digit_count(1000), 4)
    end)
  end)

  T.describe("statistics", function()
    T.it("mean", function()
      T.eq(M.mean({1, 2, 3, 4, 5}), 3)
      T.ok(M.approx_eq(M.mean({1.5, 2.5}), 2))
      local v, err = M.mean({})
      T.eq(v, nil); T.ok(err ~= nil)
    end)

    T.it("median odd", function()
      T.eq(M.median({3, 1, 2}), 2)
    end)

    T.it("median even", function()
      T.eq(M.median({1, 2, 3, 4}), 2.5)
    end)

    T.it("mode", function()
      local m = M.mode({1, 2, 2, 3})
      T.eq(#m, 1); T.eq(m[1], 2)
    end)

    T.it("variance and stddev", function()
      T.ok(M.approx_eq(M.variance({2, 4, 4, 4, 5, 5, 7, 9}), 4))
      T.ok(M.approx_eq(M.stddev({2, 4, 4, 4, 5, 5, 7, 9}), 2))
    end)

    T.it("percentile", function()
      local arr = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
      T.ok(M.approx_eq(M.percentile(arr, 0), 1))
      T.ok(M.approx_eq(M.percentile(arr, 100), 10))
      T.ok(M.approx_eq(M.percentile(arr, 50), 5.5))
    end)
  end)

  T.describe("easing", function()
    T.it("ease_in_quad", function()
      T.eq(M.ease_in_quad(0), 0)
      T.eq(M.ease_in_quad(1), 1)
      T.ok(M.approx_eq(M.ease_in_quad(0.5), 0.25))
    end)

    T.it("ease_out_quad", function()
      T.eq(M.ease_out_quad(0), 0)
      T.eq(M.ease_out_quad(1), 1)
      T.ok(M.approx_eq(M.ease_out_quad(0.5), 0.75))
    end)

    T.it("ease_in_out_quad", function()
      T.eq(M.ease_in_out_quad(0), 0)
      T.eq(M.ease_in_out_quad(1), 1)
      T.ok(M.approx_eq(M.ease_in_out_quad(0.5), 0.5))
    end)

    T.it("ease_in_cubic", function()
      T.eq(M.ease_in_cubic(0), 0)
      T.eq(M.ease_in_cubic(1), 1)
      T.ok(M.approx_eq(M.ease_in_cubic(0.5), 0.125))
    end)

    T.it("ease_out_cubic", function()
      T.eq(M.ease_out_cubic(0), 0)
      T.eq(M.ease_out_cubic(1), 1)
    end)

    T.it("ease_in_out_cubic", function()
      T.eq(M.ease_in_out_cubic(0), 0)
      T.eq(M.ease_in_out_cubic(1), 1)
      T.ok(M.approx_eq(M.ease_in_out_cubic(0.5), 0.5))
    end)

    T.it("ease_in/out_sine", function()
      T.ok(M.approx_eq(M.ease_in_sine(0), 0))
      T.ok(M.approx_eq(M.ease_in_sine(1), 1))
      T.ok(M.approx_eq(M.ease_out_sine(0), 0))
      T.ok(M.approx_eq(M.ease_out_sine(1), 1))
      T.ok(M.approx_eq(M.ease_in_out_sine(0), 0))
      T.ok(M.approx_eq(M.ease_in_out_sine(1), 1))
    end)
  end)

  T.describe("geometry", function()
    T.it("deg_to_rad / rad_to_deg round-trip", function()
      T.ok(M.approx_eq(M.rad_to_deg(M.deg_to_rad(90)), 90))
      T.ok(M.approx_eq(M.rad_to_deg(M.deg_to_rad(180)), 180))
      T.ok(M.approx_eq(M.deg_to_rad(180), math.pi))
    end)

    T.it("distance", function()
      T.ok(M.approx_eq(M.distance(0, 0, 3, 4), 5))
      T.ok(M.approx_eq(M.distance(1, 1, 1, 1), 0))
    end)

    T.it("distance_sq", function()
      T.eq(M.distance_sq(0, 0, 3, 4), 25)
    end)

    T.it("polar_to_cart / cart_to_polar round-trip", function()
      local x, y = M.polar_to_cart(5, math.pi / 4)
      local r, theta = M.cart_to_polar(x, y)
      T.ok(M.approx_eq(r, 5))
      T.ok(M.approx_eq(theta, math.pi / 4))
    end)

    T.it("polar_to_cart known values", function()
      local x, y = M.polar_to_cart(1, 0)
      T.ok(M.approx_eq(x, 1)); T.ok(M.approx_eq(y, 0))
      local x2, y2 = M.polar_to_cart(1, math.pi / 2)
      T.ok(M.approx_eq(x2, 0, 1e-9)); T.ok(M.approx_eq(y2, 1))
    end)

    T.it("dot2d and cross2d", function()
      T.eq(M.dot2d(1, 0, 0, 1), 0)
      T.eq(M.dot2d(1, 0, 1, 0), 1)
      T.eq(M.cross2d(1, 0, 0, 1), 1)
      T.eq(M.cross2d(1, 0, 1, 0), 0)
    end)

    T.it("angle_between", function()
      -- 90 degrees between (1,0) and (0,1)
      T.ok(M.approx_eq(math.abs(M.angle_between(1, 0, 0, 1)), math.pi / 2))
    end)
  end)

end)
