if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local S = require("lib.string_ext")

T.describe("string_ext", function()

  -- -------------------------------------------------------------------------
  -- Inspection
  -- -------------------------------------------------------------------------

  T.describe("starts_with", function()
    T.it("returns true when s starts with prefix", function()
      T.eq(S.starts_with("hello world", "hello"), true)
    end)
    T.it("returns false when s does not start with prefix", function()
      T.eq(S.starts_with("hello world", "world"), false)
    end)
    T.it("empty prefix always matches", function()
      T.eq(S.starts_with("abc", ""), true)
    end)
    T.it("prefix equal to string matches", function()
      T.eq(S.starts_with("abc", "abc"), true)
    end)
    T.it("prefix longer than string does not match", function()
      T.eq(S.starts_with("ab", "abc"), false)
    end)
  end)

  T.describe("ends_with", function()
    T.it("returns true when s ends with suffix", function()
      T.eq(S.ends_with("hello world", "world"), true)
    end)
    T.it("returns false when not ending", function()
      T.eq(S.ends_with("hello world", "hello"), false)
    end)
    T.it("empty suffix always matches", function()
      T.eq(S.ends_with("abc", ""), true)
    end)
    T.it("suffix longer than string does not match", function()
      T.eq(S.ends_with("ab", "abc"), false)
    end)
  end)

  T.describe("contains", function()
    T.it("finds substring in middle", function()
      T.eq(S.contains("hello world", "lo wo"), true)
    end)
    T.it("returns false when absent", function()
      T.eq(S.contains("hello world", "xyz"), false)
    end)
    T.it("works for single char", function()
      T.eq(S.contains("abc", "b"), true)
    end)
    T.it("plain match does not treat dots as patterns", function()
      T.eq(S.contains("a.b", "."), true)
      T.eq(S.contains("axb", "."), false)
    end)
  end)

  T.describe("count", function()
    T.it("counts non-overlapping occurrences", function()
      T.eq(S.count("banana", "an"), 2)
    end)
    T.it("returns 0 when not found", function()
      T.eq(S.count("hello", "xyz"), 0)
    end)
    T.it("returns 0 for empty sub", function()
      T.eq(S.count("hello", ""), 0)
    end)
    T.it("counts single chars", function()
      T.eq(S.count("mississippi", "s"), 4)
    end)
  end)

  T.describe("is_empty", function()
    T.it("true for empty string", function()
      T.eq(S.is_empty(""), true)
    end)
    T.it("true for nil", function()
      T.eq(S.is_empty(nil), true)
    end)
    T.it("false for non-empty", function()
      T.eq(S.is_empty("a"), false)
    end)
  end)

  T.describe("is_blank", function()
    T.it("true for empty string", function()
      T.eq(S.is_blank(""), true)
    end)
    T.it("true for whitespace only", function()
      T.eq(S.is_blank("   \t\n"), true)
    end)
    T.it("true for nil", function()
      T.eq(S.is_blank(nil), true)
    end)
    T.it("false for string with content", function()
      T.eq(S.is_blank("  a  "), false)
    end)
  end)

  -- -------------------------------------------------------------------------
  -- Transformation
  -- -------------------------------------------------------------------------

  T.describe("trim", function()
    T.it("strips both sides", function()
      T.eq(S.trim("  hello  "), "hello")
    end)
    T.it("leaves internal spaces", function()
      T.eq(S.trim("  hello world  "), "hello world")
    end)
    T.it("empty string stays empty", function()
      T.eq(S.trim(""), "")
    end)
    T.it("all whitespace becomes empty", function()
      T.eq(S.trim("   "), "")
    end)
  end)

  T.describe("trim_left", function()
    T.it("strips only leading", function()
      T.eq(S.trim_left("  hi  "), "hi  ")
    end)
  end)

  T.describe("trim_right", function()
    T.it("strips only trailing", function()
      T.eq(S.trim_right("  hi  "), "  hi")
    end)
  end)

  T.describe("pad_left", function()
    T.it("pads to width with spaces", function()
      T.eq(S.pad_left("hi", 5), "   hi")
    end)
    T.it("uses custom char", function()
      T.eq(S.pad_left("hi", 5, "0"), "000hi")
    end)
    T.it("no-op when already wide enough", function()
      T.eq(S.pad_left("hello", 3), "hello")
    end)
    T.it("exact width is no-op", function()
      T.eq(S.pad_left("hi", 2), "hi")
    end)
  end)

  T.describe("pad_right", function()
    T.it("pads to width with spaces", function()
      T.eq(S.pad_right("hi", 5), "hi   ")
    end)
    T.it("uses custom char", function()
      T.eq(S.pad_right("hi", 5, "-"), "hi---")
    end)
  end)

  T.describe("center", function()
    T.it("centers with even padding", function()
      T.eq(S.center("hi", 6), "  hi  ")
    end)
    T.it("extra space goes to left on odd", function()
      T.eq(S.center("hi", 5), "  hi ")
    end)
    T.it("uses custom char", function()
      T.eq(S.center("X", 5, "-"), "--X--")
    end)
    T.it("no-op when already wide enough", function()
      T.eq(S.center("hello", 3), "hello")
    end)
  end)

  T.describe("truncate", function()
    T.it("truncates long string with default ellipsis", function()
      T.eq(S.truncate("hello world", 8), "hello...")
    end)
    T.it("no-op when short enough", function()
      T.eq(S.truncate("hi", 5), "hi")
    end)
    T.it("uses custom ellipsis (byte-based: … is 3 bytes)", function()
      -- "…" is 3 bytes in UTF-8; keep = 7-3 = 4 bytes → "hell"
      T.eq(S.truncate("hello world", 7, "…"), "hell…")
    end)
    T.it("no ellipsis when empty string passed", function()
      T.eq(S.truncate("hello world", 5, ""), "hello")
    end)
  end)

  T.describe("wrap", function()
    T.it("wraps at word boundary", function()
      local lines = S.wrap("hello world foo bar", 11)
      T.eq(lines[1], "hello world")
      T.eq(lines[2], "foo bar")
    end)
    T.it("single long word on its own line", function()
      local lines = S.wrap("superlongword short", 5)
      T.eq(lines[1], "superlongword")
      T.eq(lines[2], "short")
    end)
    T.it("single word fits exactly", function()
      local lines = S.wrap("hello", 5)
      T.eq(#lines, 1)
      T.eq(lines[1], "hello")
    end)
    T.it("empty string returns empty array", function()
      T.eq(#S.wrap("", 10), 0)
    end)
  end)

  T.describe("repeat_str", function()
    T.it("repeats string n times", function()
      T.eq(S.repeat_str("ab", 3), "ababab")
    end)
    T.it("zero times gives empty string", function()
      T.eq(S.repeat_str("ab", 0), "")
    end)
  end)

  T.describe("reverse", function()
    T.it("reverses a string", function()
      T.eq(S.reverse("hello"), "olleh")
    end)
    T.it("empty string", function()
      T.eq(S.reverse(""), "")
    end)
  end)

  T.describe("capitalize", function()
    T.it("first char up, rest lower", function()
      T.eq(S.capitalize("hELLO"), "Hello")
    end)
    T.it("empty string", function()
      T.eq(S.capitalize(""), "")
    end)
  end)

  T.describe("title_case", function()
    T.it("capitalizes each word", function()
      T.eq(S.title_case("hello world"), "Hello World")
    end)
    T.it("lowercases non-first letters", function()
      T.eq(S.title_case("hELLO wORLD"), "Hello World")
    end)
  end)

  T.describe("snake_case", function()
    T.it("camelCase to snake_case", function()
      T.eq(S.snake_case("fooBar"), "foo_bar")
    end)
    T.it("PascalCase to snake_case", function()
      T.eq(S.snake_case("FooBar"), "foo_bar")
    end)
    T.it("space-separated to snake_case", function()
      T.eq(S.snake_case("Foo Bar"), "foo_bar")
    end)
    T.it("kebab to snake_case", function()
      T.eq(S.snake_case("foo-bar"), "foo_bar")
    end)
    T.it("already snake_case unchanged", function()
      T.eq(S.snake_case("foo_bar"), "foo_bar")
    end)
  end)

  T.describe("camel_case", function()
    T.it("snake_case to camelCase", function()
      T.eq(S.camel_case("foo_bar"), "fooBar")
    end)
    T.it("space-separated to camelCase", function()
      T.eq(S.camel_case("foo bar"), "fooBar")
    end)
    T.it("kebab to camelCase", function()
      T.eq(S.camel_case("foo-bar"), "fooBar")
    end)
    T.it("single word lowercases first char", function()
      T.eq(S.camel_case("Hello"), "hello")
    end)
  end)

  T.describe("pascal_case", function()
    T.it("snake_case to PascalCase", function()
      T.eq(S.pascal_case("foo_bar"), "FooBar")
    end)
    T.it("space-separated to PascalCase", function()
      T.eq(S.pascal_case("foo bar"), "FooBar")
    end)
    T.it("single word uppercases first char", function()
      T.eq(S.pascal_case("hello"), "Hello")
    end)
  end)

  T.describe("kebab_case", function()
    T.it("camelCase to kebab-case", function()
      T.eq(S.kebab_case("fooBar"), "foo-bar")
    end)
    T.it("PascalCase to kebab-case", function()
      T.eq(S.kebab_case("FooBar"), "foo-bar")
    end)
    T.it("snake_case to kebab-case", function()
      T.eq(S.kebab_case("foo_bar"), "foo-bar")
    end)
    T.it("space-separated to kebab-case", function()
      T.eq(S.kebab_case("foo bar"), "foo-bar")
    end)
  end)

  T.describe("upper_first", function()
    T.it("uppercases first char only", function()
      T.eq(S.upper_first("hello WORLD"), "Hello WORLD")
    end)
    T.it("empty string", function()
      T.eq(S.upper_first(""), "")
    end)
  end)

  T.describe("lower_first", function()
    T.it("lowercases first char only", function()
      T.eq(S.lower_first("HELLO world"), "hELLO world")
    end)
    T.it("empty string", function()
      T.eq(S.lower_first(""), "")
    end)
  end)

  -- -------------------------------------------------------------------------
  -- Splitting and joining
  -- -------------------------------------------------------------------------

  T.describe("split", function()
    T.it("splits on separator", function()
      local r = S.split("a,b,c", ",")
      T.eq(r[1], "a")
      T.eq(r[2], "b")
      T.eq(r[3], "c")
      T.eq(#r, 3)
    end)
    T.it("preserves empty parts", function()
      local r = S.split("a,,b", ",")
      T.eq(#r, 3)
      T.eq(r[2], "")
    end)
    T.it("no separator found returns whole string", function()
      local r = S.split("abc", ",")
      T.eq(#r, 1)
      T.eq(r[1], "abc")
    end)
    T.it("pattern separator when plain=false", function()
      local r = S.split("a1b2c", "%d", false)
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[3], "c")
    end)
  end)

  T.describe("split_n", function()
    T.it("splits into at most n parts", function()
      local r = S.split_n("a,b,c,d", ",", 3)
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[2], "b")
      T.eq(r[3], "c,d")
    end)
    T.it("n larger than parts returns all parts", function()
      local r = S.split_n("a,b", ",", 5)
      T.eq(#r, 2)
    end)
  end)

  T.describe("lines", function()
    T.it("splits on \\n", function()
      local r = S.lines("a\nb\nc")
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[3], "c")
    end)
    T.it("handles \\r\\n", function()
      local r = S.lines("a\r\nb\r\nc")
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[2], "b")
    end)
    T.it("trailing newline produces empty last line", function()
      local r = S.lines("a\nb\n")
      T.eq(#r, 3)
      T.eq(r[3], "")
    end)
  end)

  T.describe("chars", function()
    T.it("splits into individual chars", function()
      local r = S.chars("abc")
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[3], "c")
    end)
  end)

  T.describe("bytes", function()
    T.it("returns byte values", function()
      local r = S.bytes("ABC")
      T.eq(r[1], 65)
      T.eq(r[2], 66)
      T.eq(r[3], 67)
    end)
  end)

  T.describe("join", function()
    T.it("joins with separator", function()
      T.eq(S.join(", ", {"a", "b", "c"}), "a, b, c")
    end)
    T.it("empty separator concatenates", function()
      T.eq(S.join("", {"a", "b", "c"}), "abc")
    end)
  end)

  -- -------------------------------------------------------------------------
  -- Search and replace
  -- -------------------------------------------------------------------------

  T.describe("replace", function()
    T.it("replaces first n occurrences", function()
      T.eq(S.replace("aaa", "a", "b", 2), "bba")
    end)
    T.it("plain text replace ignores pattern chars", function()
      T.eq(S.replace("a.b.c", ".", "-"), "a-b-c")
    end)
    T.it("replaces all when n omitted", function()
      T.eq(S.replace("aaa", "a", "b"), "bbb")
    end)
  end)

  T.describe("replace_all", function()
    T.it("replaces all occurrences", function()
      T.eq(S.replace_all("hello world hello", "hello", "hi"), "hi world hi")
    end)
    T.it("empty string returns unchanged", function()
      T.eq(S.replace_all("hello", "", "x"), "hello")
    end)
  end)

  T.describe("index_of", function()
    T.it("returns 1-based position", function()
      T.eq(S.index_of("hello", "ll"), 3)
    end)
    T.it("returns 0 when not found", function()
      T.eq(S.index_of("hello", "xyz"), 0)
    end)
    T.it("respects init offset", function()
      T.eq(S.index_of("abcabc", "a", 2), 4)
    end)
  end)

  T.describe("last_index_of", function()
    T.it("returns last position", function()
      T.eq(S.last_index_of("abcabc", "a"), 4)
    end)
    T.it("returns 0 when not found", function()
      T.eq(S.last_index_of("hello", "xyz"), 0)
    end)
  end)

  T.describe("slice", function()
    T.it("positive indices work like string.sub", function()
      T.eq(S.slice("hello", 2, 4), "ell")
    end)
    T.it("negative index -1 is last char", function()
      T.eq(S.slice("hello", 1, -1), "hello")
    end)
    T.it("negative indices from end", function()
      T.eq(S.slice("hello", -3, -1), "llo")
    end)
  end)

  -- -------------------------------------------------------------------------
  -- Encoding helpers
  -- -------------------------------------------------------------------------

  T.describe("escape_pattern", function()
    T.it("escapes all Lua magic characters", function()
      local magic = "().+-*?[^$%"
      local escaped = S.escape_pattern(magic)
      -- should be usable in a find without error
      local ok = pcall(function() ("test"):find(escaped, 1, false) end)
      T.ok(ok)
    end)
    T.it("escapes dot so it matches literal dot only", function()
      -- plain dot matches any char; escaped dot matches only "."
      local pat = S.escape_pattern("a.b")
      T.eq(("axb"):find(pat), nil)
      T.eq(("a.b"):find(pat), 1)
    end)
    T.it("escapes percent sign", function()
      local pat = S.escape_pattern("100%")
      T.eq(("100%"):find(pat), 1)
    end)
  end)

  T.describe("escape_html / unescape_html", function()
    T.it("escapes & < > \" '", function()
      T.eq(S.escape_html("<script>"), "&lt;script&gt;")
      T.eq(S.escape_html("a & b"), "a &amp; b")
      T.eq(S.escape_html('"quoted"'), "&quot;quoted&quot;")
      T.eq(S.escape_html("it's"), "it&#39;s")
      T.eq(S.escape_html('a & b < c > d "e" \'f\''),
           "a &amp; b &lt; c &gt; d &quot;e&quot; &#39;f&#39;")
    end)
    T.it("round-trips through unescape", function()
      local original = '<div class="test">hello & world</div>'
      T.eq(S.unescape_html(S.escape_html(original)), original)
    end)
    T.it("unescape handles &amp; &lt; &gt; &quot; &#39;", function()
      T.eq(S.unescape_html("&lt;b&gt;"), "<b>")
      T.eq(S.unescape_html("&amp;"), "&")
      T.eq(S.unescape_html("&quot;"), '"')
      T.eq(S.unescape_html("&#39;"), "'")
    end)
  end)

  T.describe("escape_uri / unescape_uri", function()
    T.it("encodes spaces and special chars", function()
      T.eq(S.escape_uri("hello world"), "hello%20world")
      T.eq(S.escape_uri("a=1&b=2"), "a%3D1%26b%3D2")
    end)
    T.it("leaves unreserved chars untouched", function()
      T.eq(S.escape_uri("abc-_.~"), "abc-_.~")
    end)
    T.it("round-trips through unescape", function()
      local original = "hello world & foo=bar+baz"
      T.eq(S.unescape_uri(S.escape_uri(original)), original)
    end)
    T.it("unescape decodes percent sequences", function()
      T.eq(S.unescape_uri("hello%20world"), "hello world")
      T.eq(S.unescape_uri("%2F"), "/")
    end)
    T.it("uppercase hex is decoded", function()
      T.eq(S.unescape_uri("%2F"), "/")
      T.eq(S.unescape_uri("%2f"), "/")
    end)
  end)

end)
