if not package.path:find("./?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local codec = require("lib.codec")

T.describe("codec.hex", function()
  T.it("encodes bytes to hex", function()
    T.eq(codec.hex.encode("ABC"), "414243")
  end)
  T.it("decodes hex to bytes", function()
    T.eq(codec.hex.decode("414243"), "ABC")
  end)
  T.it("roundtrips", function()
    T.ok(codec.roundtrip(codec.hex, "hello world"))
  end)
  T.it("handles empty string", function()
    T.eq(codec.hex.encode(""), "")
    T.eq(codec.hex.decode(""), "")
  end)
  T.it("handles binary data", function()
    T.eq(codec.hex.encode("\x00\xff"), "00ff")
    T.eq(codec.hex.decode("00ff"), "\x00\xff")
  end)
  T.it("returns error on non-string encode", function()
    local v, err = codec.hex.encode(123)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error on non-string decode", function()
    local v, err = codec.hex.decode(123)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error on odd-length hex", function()
    local v, err = codec.hex.decode("abc")
    T.eq(v, nil)
    T.ok(err:find("odd"))
  end)
  T.it("returns error on invalid hex chars", function()
    local v, err = codec.hex.decode("zzzz")
    T.eq(v, nil)
    T.ok(err:find("invalid"))
  end)
end)

T.describe("codec.rot13", function()
  T.it("encodes letters", function()
    T.eq(codec.rot13.encode("Hello"), "Uryyb")
  end)
  T.it("is self-inverse", function()
    T.eq(codec.rot13.encode(codec.rot13.encode("Hello")), "Hello")
  end)
  T.it("roundtrips", function()
    T.ok(codec.roundtrip(codec.rot13, "The quick brown fox"))
  end)
  T.it("leaves non-alpha chars unchanged", function()
    T.eq(codec.rot13.encode("123!@#"), "123!@#")
  end)
  T.it("handles empty string", function()
    T.eq(codec.rot13.encode(""), "")
  end)
  T.it("returns error on non-string", function()
    local v, err = codec.rot13.encode(42)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.reverse", function()
  T.it("reverses a string", function()
    T.eq(codec.reverse.encode("abc"), "cba")
  end)
  T.it("decode reverses back", function()
    T.eq(codec.reverse.decode("cba"), "abc")
  end)
  T.it("roundtrips", function()
    T.ok(codec.roundtrip(codec.reverse, "hello"))
  end)
  T.it("handles empty string", function()
    T.eq(codec.reverse.encode(""), "")
  end)
  T.it("handles single char", function()
    T.eq(codec.reverse.encode("x"), "x")
  end)
  T.it("returns error on non-string", function()
    local v, err = codec.reverse.encode(true)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.xor", function()
  T.it("xors bytes with key", function()
    local c = codec.xor(0x42)
    local enc = c.encode("A")
    -- A=0x41, 0x41 XOR 0x42 = 0x03
    T.eq(enc, "\x03")
  end)
  T.it("is self-inverse", function()
    local c = codec.xor(0xAA)
    local data = "hello world"
    T.eq(c.decode(c.encode(data)), data)
  end)
  T.it("roundtrips", function()
    local c = codec.xor(0xFF)
    T.ok(codec.roundtrip(c, "test data"))
  end)
  T.it("handles empty string", function()
    local c = codec.xor(42)
    T.eq(c.encode(""), "")
  end)
  T.it("xor with 0 is identity", function()
    local c = codec.xor(0)
    T.eq(c.encode("abc"), "abc")
  end)
  T.it("wraps key mod 256", function()
    local c1 = codec.xor(256 + 42)
    local c2 = codec.xor(42)
    T.eq(c1.encode("test"), c2.encode("test"))
  end)
  T.it("returns error on non-number key", function()
    local v, err = codec.xor("bad")
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error on non-string input", function()
    local c = codec.xor(1)
    local v, err = c.encode(42)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.new", function()
  T.it("creates a codec from table", function()
    local c = codec.new({
      encode = function(s) return s .. "!" end,
      decode = function(s) return s:sub(1, -2) end,
    })
    T.eq(c.encode("hi"), "hi!")
    T.eq(c.decode("hi!"), "hi")
  end)
  T.it("returns error when nil", function()
    local v, err = codec.new(nil)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error when missing encode", function()
    local v, err = codec.new({ decode = function() end })
    T.eq(v, nil)
    T.ok(err:find("encode"))
  end)
  T.it("returns error when missing decode", function()
    local v, err = codec.new({ encode = function() end })
    T.eq(v, nil)
    T.ok(err:find("decode"))
  end)
end)

T.describe("codec.from", function()
  T.it("creates a codec from two functions", function()
    local c = codec.from(
      function(s) return s:upper() end,
      function(s) return s:lower() end
    )
    T.eq(c.encode("hello"), "HELLO")
    T.eq(c.decode("HELLO"), "hello")
  end)
  T.it("returns error when missing encode", function()
    local v, err = codec.from(nil, function() end)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error when missing decode", function()
    local v, err = codec.from(function() end, nil)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.chain", function()
  T.it("chains two codecs encode left-to-right", function()
    local upper = codec.from(
      function(s) return s:upper() end,
      function(s) return s:lower() end
    )
    local pipeline = codec.chain(upper, codec.hex)
    T.eq(pipeline.encode("hi"), "4849") -- "HI" -> hex
  end)
  T.it("chains two codecs decode right-to-left", function()
    local upper = codec.from(
      function(s) return s:upper() end,
      function(s) return s:lower() end
    )
    local pipeline = codec.chain(upper, codec.hex)
    T.eq(pipeline.decode("4849"), "hi") -- hex -> "HI" -> lower
  end)
  T.it("chains three codecs", function()
    local bang = codec.from(
      function(s) return s .. "!" end,
      function(s) return s:sub(1, -2) end
    )
    local pipeline = codec.chain(codec.reverse, bang, codec.hex)
    local enc = pipeline.encode("ab")
    -- "ab" -> reverse -> "ba" -> bang -> "ba!" -> hex -> "626121"
    T.eq(enc, "626121")
  end)
  T.it("chain of 1 returns the codec itself", function()
    local c = codec.chain(codec.hex)
    T.eq(c.encode("A"), "41")
    T.eq(c.decode("41"), "A")
  end)
  T.it("chain of 5 works", function()
    local id = codec.identity
    local pipeline = codec.chain(id, id, codec.hex, id, id)
    T.eq(pipeline.encode("Z"), "5a")
    T.eq(pipeline.decode("5a"), "Z")
  end)
  T.it("roundtrips through chain", function()
    local pipeline = codec.chain(codec.rot13, codec.hex, codec.reverse)
    T.ok(codec.roundtrip(pipeline, "hello world"))
  end)
  T.it("propagates encode errors", function()
    local bad = codec.from(
      function() return nil, "encode failed" end,
      function(s) return s end
    )
    local pipeline = codec.chain(codec.hex, bad)
    local v, err = pipeline.encode("test")
    T.eq(v, nil)
    T.eq(err, "encode failed")
  end)
  T.it("propagates decode errors", function()
    local bad = codec.from(
      function(s) return s end,
      function() return nil, "decode failed" end
    )
    local pipeline = codec.chain(bad, codec.hex)
    local v, err = pipeline.decode("74657374")
    T.eq(v, nil)
    T.eq(err, "decode failed")
  end)
  T.it("stops on first encode error in chain", function()
    local calls = 0
    local bad = codec.from(
      function() return nil, "fail" end,
      function(s) return s end
    )
    local counter = codec.from(
      function(s) calls = calls + 1; return s end,
      function(s) return s end
    )
    local pipeline = codec.chain(bad, counter)
    pipeline.encode("test")
    T.eq(calls, 0) -- counter should not be reached
  end)
  T.it("returns error on empty chain", function()
    local v, err = codec.chain()
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.when", function()
  T.it("applies codec when predicate is true", function()
    local c = codec.when(function() return true end, codec.hex)
    T.eq(c.encode("A"), "41")
  end)
  T.it("passes through when predicate is false", function()
    local c = codec.when(function() return false end, codec.hex)
    T.eq(c.encode("A"), "A")
  end)
  T.it("decode applies when predicate is true", function()
    local c = codec.when(function() return true end, codec.hex)
    T.eq(c.decode("41"), "A")
  end)
  T.it("decode passes through when predicate is false", function()
    local c = codec.when(function() return false end, codec.hex)
    T.eq(c.decode("41"), "41")
  end)
  T.it("predicate receives the data", function()
    local seen = nil
    local c = codec.when(function(d) seen = d; return false end, codec.hex)
    c.encode("test")
    T.eq(seen, "test")
  end)
  T.it("conditional on string length", function()
    local c = codec.when(
      function(s) return type(s) == "string" and #s > 3 end,
      codec.hex
    )
    T.eq(c.encode("hi"), "hi") -- too short, passthrough
    T.eq(c.encode("hello"), "68656c6c6f") -- long enough, hex
  end)
  T.it("returns error when missing predicate", function()
    local v, err = codec.when(nil, codec.hex)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error when missing codec", function()
    local v, err = codec.when(function() return true end, nil)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.map", function()
  T.it("maps encode and decode", function()
    local c = codec.map(string.upper, string.lower)
    T.eq(c.encode("hello"), "HELLO")
    T.eq(c.decode("HELLO"), "hello")
  end)
  T.it("roundtrips for case conversion", function()
    T.ok(codec.roundtrip(codec.map(string.upper, string.lower), "hello"))
  end)
  T.it("returns error when missing encode", function()
    local v, err = codec.map(nil, string.lower)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns error when missing decode", function()
    local v, err = codec.map(string.upper, nil)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("codec.identity", function()
  T.it("encode returns data unchanged", function()
    T.eq(codec.identity.encode("hello"), "hello")
  end)
  T.it("decode returns data unchanged", function()
    T.eq(codec.identity.decode("hello"), "hello")
  end)
  T.it("roundtrips", function()
    T.ok(codec.roundtrip(codec.identity, "test"))
  end)
  T.it("works with non-string data", function()
    T.eq(codec.identity.encode(42), 42)
    T.eq(codec.identity.decode(true), true)
  end)
end)

T.describe("codec.roundtrip", function()
  T.it("returns true for valid roundtrip", function()
    T.ok(codec.roundtrip(codec.hex, "hello"))
  end)
  T.it("returns false for broken codec", function()
    local bad = codec.from(
      function(s) return s .. "extra" end,
      function(s) return s end
    )
    T.eq(codec.roundtrip(bad, "test"), false)
  end)
  T.it("returns false when encode fails", function()
    local bad = codec.from(
      function() return nil, "fail" end,
      function(s) return s end
    )
    local ok, err = codec.roundtrip(bad, "test")
    T.eq(ok, false)
    T.eq(err, "fail")
  end)
  T.it("returns false when decode fails", function()
    local bad = codec.from(
      function(s) return s end,
      function() return nil, "fail" end
    )
    local ok, err = codec.roundtrip(bad, "test")
    T.eq(ok, false)
    T.eq(err, "fail")
  end)
end)

T.describe("codec edge cases", function()
  T.it("hex roundtrips all byte values", function()
    local bytes = {}
    for i = 0, 255 do bytes[i + 1] = string.char(i) end
    local all = table.concat(bytes)
    T.ok(codec.roundtrip(codec.hex, all))
  end)
  T.it("rot13 roundtrips all ASCII", function()
    local chars = {}
    for i = 0, 127 do chars[i + 1] = string.char(i) end
    local all = table.concat(chars)
    T.ok(codec.roundtrip(codec.rot13, all))
  end)
  T.it("xor roundtrips all byte values", function()
    local bytes = {}
    for i = 0, 255 do bytes[i + 1] = string.char(i) end
    local all = table.concat(bytes)
    local c = codec.xor(0x5A)
    T.ok(codec.roundtrip(c, all))
  end)
  T.it("chain with when conditional", function()
    local cond = codec.when(
      function(s) return type(s) == "string" and #s > 0 end,
      codec.rot13
    )
    local pipeline = codec.chain(cond, codec.hex)
    T.ok(codec.roundtrip(pipeline, "hello"))
    -- Empty string: rot13 passthrough, hex still works
    T.ok(codec.roundtrip(pipeline, ""))
  end)
  T.it("nested chain", function()
    local inner = codec.chain(codec.rot13, codec.reverse)
    local outer = codec.chain(inner, codec.hex)
    T.ok(codec.roundtrip(outer, "nested"))
  end)
end)
