if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T     = require("lib.test.assert")
local graph = require("lib.graph")

-- Sort an array for deterministic comparison
local function sorted(arr)
  local cp = {}
  for i = 1, #arr do cp[i] = arr[i] end
  table.sort(cp, function(a, b) return tostring(a) < tostring(b) end)
  return cp
end

-- Check whether arr contains val
local function has(arr, val)
  for i = 1, #arr do if arr[i] == val then return true end end
  return false
end

-- Find which component (index) contains vertex v
local function comp_of(comps, v)
  for i = 1, #comps do
    for j = 1, #comps[i] do
      if comps[i][j] == v then return i end
    end
  end
  return nil
end

-- ---------------------------------------------------------------------------
T.describe("graph", function()

  -- -------------------------------------------------------------------------
  T.describe("new", function()
    T.it("defaults to undirected", function()
      local g = graph.new()
      T.eq(g._directed, false)
    end)
    T.it("creates directed when requested", function()
      local dg = graph.new({directed = true})
      T.eq(dg._directed, true)
    end)
    T.it("empty graph starts with zero counts", function()
      local g = graph.new()
      T.eq(g:node_count(), 0)
      T.eq(g:edge_count(), 0)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("add_node / has_node / node_data", function()
    T.it("adds nodes", function()
      local g = graph.new()
      g:add_node("a", {label = "A"})
      g:add_node("b")
      T.ok(g:has_node("a"))
      T.ok(g:has_node("b"))
      T.eq(g:has_node("z"), false)
      T.eq(g:node_count(), 2)
    end)
    T.it("returns data for node", function()
      local g = graph.new()
      g:add_node("a", {label = "A"})
      g:add_node("b")
      T.eq(g:node_data("a").label, "A")
      T.eq(g:node_data("b"), nil)
      T.eq(g:node_data("z"), nil)
    end)
    T.it("updating node data", function()
      local g = graph.new()
      g:add_node("a", {x = 1})
      g:add_node("a", {x = 2})   -- update
      T.eq(g:node_count(), 1)
      T.eq(g:node_data("a").x, 2)
    end)
    T.it("numeric node ids", function()
      local g = graph.new()
      g:add_node(1)
      g:add_node(2)
      T.ok(g:has_node(1))
      T.ok(g:has_node(2))
      T.eq(g:node_count(), 2)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("remove_node", function()
    T.it("removes node and incident edges (undirected)", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c")
      T.ok(g:remove_node("b"))
      T.eq(g:has_node("b"), false)
      T.eq(g:node_count(), 2)
      T.eq(g:edge_count(), 0)
      T.eq(g:has_edge("a", "b"), false)
      T.eq(g:has_edge("c", "b"), false)
      T.eq(g:degree("a"), 0)
    end)
    T.it("removes node and incident edges (directed)", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("c", "b")
      T.ok(dg:remove_node("b"))
      T.eq(dg:edge_count(), 0)
      T.eq(dg:has_edge("a", "b"), false)
      T.eq(dg:out_degree("a"), 0)
    end)
    T.it("returns false for nonexistent node", function()
      local g = graph.new()
      T.eq(g:remove_node("x"), false)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("add_edge / has_edge / edge_data", function()
    T.it("adds edge with data", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b")
      g:add_edge("a", "b", {weight = 1.5})
      T.ok(g:has_edge("a", "b"))
      T.eq(g:edge_data("a", "b").weight, 1.5)
      T.eq(g:edge_count(), 1)
    end)
    T.it("auto-creates nodes", function()
      local g = graph.new()
      g:add_edge("x", "y")
      T.ok(g:has_node("x"))
      T.ok(g:has_node("y"))
      T.eq(g:node_count(), 2)
    end)
    T.it("edge without data returns nil from edge_data", function()
      local g = graph.new()
      g:add_edge("a", "b")
      T.eq(g:edge_data("a", "b"), nil)
    end)
    T.it("undirected edge is bidirectional", function()
      local g = graph.new()
      g:add_edge("a", "b", {weight = 3})
      T.ok(g:has_edge("a", "b"))
      T.ok(g:has_edge("b", "a"))
      T.eq(g:edge_data("b", "a").weight, 3)
      T.eq(g:edge_count(), 1)
    end)
    T.it("directed edge is one-way", function()
      local dg = graph.new({directed = true})
      dg:add_edge("a", "b")
      T.ok(dg:has_edge("a", "b"))
      T.eq(dg:has_edge("b", "a"), false)
    end)
    T.it("adding same edge twice updates data, keeps edge_count", function()
      local g = graph.new()
      g:add_edge("a", "b", {weight = 1})
      g:add_edge("a", "b", {weight = 5})
      T.eq(g:edge_count(), 1)
      T.eq(g:edge_data("a", "b").weight, 5)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("remove_edge", function()
    T.it("removes directed edge", function()
      local dg = graph.new({directed = true})
      dg:add_edge("a", "b")
      T.ok(dg:remove_edge("a", "b"))
      T.eq(dg:has_edge("a", "b"), false)
      T.eq(dg:edge_count(), 0)
    end)
    T.it("removes undirected edge (both directions)", function()
      local g = graph.new()
      g:add_edge("a", "b")
      T.ok(g:remove_edge("a", "b"))
      T.eq(g:has_edge("a", "b"), false)
      T.eq(g:has_edge("b", "a"), false)
      T.eq(g:edge_count(), 0)
    end)
    T.it("returns false for nonexistent edge", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b")
      T.eq(g:remove_edge("a", "b"), false)
      T.eq(g:remove_edge("x", "y"), false)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("neighbors / degree", function()
    T.it("undirected neighbors and degree", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("a", "c")
      local n = sorted(g:neighbors("a"))
      T.eq(#n, 2)
      T.eq(n[1], "b"); T.eq(n[2], "c")
      T.eq(g:degree("a"), 2)
      T.eq(g:degree("b"), 1)
    end)
    T.it("directed out/in neighbors and degree", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("a", "c"); dg:add_edge("c", "b")
      local out_a = sorted(dg:out_neighbors("a"))
      T.eq(#out_a, 2); T.eq(out_a[1], "b"); T.eq(out_a[2], "c")
      local in_b = sorted(dg:in_neighbors("b"))
      T.eq(#in_b, 2); T.eq(in_b[1], "a"); T.eq(in_b[2], "c")
      T.eq(dg:out_degree("a"), 2)
      T.eq(dg:in_degree("b"), 2)
      T.eq(dg:in_degree("a"), 0)
      T.eq(dg:out_degree("b"), 0)
    end)
    T.it("degree on nonexistent node is 0", function()
      local g = graph.new()
      T.eq(g:degree("z"), 0)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("nodes() iterator", function()
    T.it("iterates all node ids", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      local ids = {}
      for id in g:nodes() do ids[#ids+1] = id end
      T.eq(#sorted(ids), 3)
      T.ok(has(ids, "a")); T.ok(has(ids, "b")); T.ok(has(ids, "c"))
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("edges() iterator", function()
    T.it("yields each directed edge once", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("b", "c"); dg:add_edge("a", "c")
      local count = 0
      for _ in dg:edges() do count = count + 1 end
      T.eq(count, 3)
    end)
    T.it("yields each undirected edge once", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c"); g:add_edge("a", "c")
      local count = 0
      for _ in g:edges() do count = count + 1 end
      T.eq(count, 3)
    end)
    T.it("edge data is accessible from iterator", function()
      local g = graph.new()
      g:add_edge("a", "b", {weight = 7})
      for e in g:edges() do
        T.eq(e[3].weight, 7)
      end
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("bfs", function()
    T.it("traverses breadth-first and returns parent table", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c"); g:add_node("d")
      g:add_edge("a", "b"); g:add_edge("a", "c"); g:add_edge("b", "d"); g:add_edge("c", "d")
      local order, parent = graph.bfs(g, "a")
      T.eq(order[1], "a")
      T.eq(#order, 4)
      -- b and c must appear before d
      local pos = {}
      for i = 1, #order do pos[order[i]] = i end
      T.ok(pos["b"] < pos["d"])
      T.ok(pos["c"] < pos["d"])
      -- parent table populated
      T.ok(parent["b"] == "a" or parent["c"] == "a")
    end)
    T.it("single node BFS", function()
      local g = graph.new()
      g:add_node("x")
      local order, parent = graph.bfs(g, "x")
      T.eq(#order, 1); T.eq(order[1], "x")
      T.eq(next(parent), nil)   -- no parents
    end)
    T.it("returns nil for nonexistent start", function()
      local g = graph.new()
      local r, err = graph.bfs(g, "z")
      T.eq(r, nil)
      T.ok(err)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("dfs", function()
    T.it("traverses depth-first and returns parent table", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c"); g:add_node("d")
      g:add_edge("a", "b"); g:add_edge("b", "d"); g:add_edge("a", "c")
      local order, parent = graph.dfs(g, "a")
      T.eq(order[1], "a")
      T.eq(#order, 4)
      T.ok(has(order, "b")); T.ok(has(order, "c")); T.ok(has(order, "d"))
      -- parent: d's parent should be b
      T.eq(parent["d"], "b")
    end)
    T.it("returns nil for nonexistent start", function()
      local g = graph.new()
      local r, err = graph.dfs(g, "z")
      T.eq(r, nil); T.ok(err)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("shortest_path", function()
    T.it("finds weighted shortest path", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c"); g:add_node("d")
      g:add_edge("a", "b", {weight = 1})
      g:add_edge("b", "d", {weight = 5})
      g:add_edge("a", "c", {weight = 2})
      g:add_edge("c", "d", {weight = 1})
      local dist, path = graph.shortest_path(g, "a", "d")
      T.ok(dist)
      T.eq(dist["d"], 3)
      T.eq(#path, 3)
      T.eq(path[1], "a"); T.eq(path[2], "c"); T.eq(path[3], "d")
    end)
    T.it("defaults edge weight to 1", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c")
      local dist, path = graph.shortest_path(g, "a", "c")
      T.eq(dist["c"], 2)
      T.eq(#path, 3)
    end)
    T.it("direct single-hop path", function()
      local g = graph.new()
      g:add_edge("a", "b", {weight = 7})
      local dist, path = graph.shortest_path(g, "a", "b")
      T.eq(dist["b"], 7); T.eq(#path, 2)
    end)
    T.it("path to self is zero-distance", function()
      local g = graph.new()
      g:add_node("a")
      local dist, path = graph.shortest_path(g, "a", "a")
      T.eq(dist["a"], 0); T.eq(#path, 1); T.eq(path[1], "a")
    end)
    T.it("returns nil when no path", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b")
      local r, err = graph.shortest_path(g, "a", "b")
      T.eq(r, nil); T.ok(err)
    end)
    T.it("returns nil for nonexistent nodes", function()
      local g = graph.new()
      local r, err = graph.shortest_path(g, "a", "b")
      T.eq(r, nil); T.ok(err)
    end)
    T.it("directed graph: respects edge direction", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b")
      dg:add_edge("a", "b", {weight = 1})
      local dist, path = graph.shortest_path(dg, "a", "b")
      T.eq(dist["b"], 1); T.eq(#path, 2)
      -- reverse direction has no path
      local r2, err2 = graph.shortest_path(dg, "b", "a")
      T.eq(r2, nil); T.ok(err2)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("topological_sort", function()
    T.it("sorts a DAG correctly", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c"); dg:add_node("d")
      dg:add_edge("a", "b"); dg:add_edge("a", "c"); dg:add_edge("b", "d"); dg:add_edge("c", "d")
      local order, err = graph.topological_sort(dg)
      T.ok(order); T.eq(err, nil); T.eq(#order, 4)
      local pos = {}
      for i = 1, #order do pos[order[i]] = i end
      T.ok(pos["a"] < pos["b"])
      T.ok(pos["a"] < pos["c"])
      T.ok(pos["b"] < pos["d"])
      T.ok(pos["c"] < pos["d"])
    end)
    T.it("detects cycle", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("b", "c"); dg:add_edge("c", "a")
      local order, err = graph.topological_sort(dg)
      T.eq(order, nil); T.ok(err)
    end)
    T.it("errors on undirected graph", function()
      local g = graph.new()
      local order, err = graph.topological_sort(g)
      T.eq(order, nil); T.ok(err)
    end)
    T.it("single node DAG", function()
      local dg = graph.new({directed = true})
      dg:add_node("a")
      local order, err = graph.topological_sort(dg)
      T.ok(order); T.eq(err, nil); T.eq(#order, 1); T.eq(order[1], "a")
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("components", function()
    T.it("two disconnected components", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c"); g:add_node("d")
      g:add_edge("a", "b"); g:add_edge("c", "d")
      local comps = graph.components(g)
      T.eq(#comps, 2)
      local ca, cb = comp_of(comps, "a"), comp_of(comps, "b")
      local cc, cd = comp_of(comps, "c"), comp_of(comps, "d")
      T.eq(ca, cb); T.eq(cc, cd); T.neq(ca, cc)
    end)
    T.it("fully connected graph is one component", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c")
      local comps = graph.components(g)
      T.eq(#comps, 1); T.eq(#comps[1], 3)
    end)
    T.it("isolated nodes are own components", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b")
      local comps = graph.components(g)
      T.eq(#comps, 2)
    end)
    T.it("empty graph", function()
      local g = graph.new()
      T.eq(#graph.components(g), 0)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("has_cycle", function()
    T.it("directed cycle detected", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("b", "c"); dg:add_edge("c", "a")
      T.ok(graph.has_cycle(dg))
    end)
    T.it("DAG has no cycle", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("a", "c")
      T.eq(graph.has_cycle(dg), false)
    end)
    T.it("self-loop is a cycle", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_edge("a", "a")
      T.ok(graph.has_cycle(dg))
    end)
    T.it("undirected cycle detected", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c"); g:add_edge("c", "a")
      T.ok(graph.has_cycle(g))
    end)
    T.it("undirected tree has no cycle", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c")
      T.eq(graph.has_cycle(g), false)
    end)
    T.it("empty graph has no cycle", function()
      T.eq(graph.has_cycle(graph.new()), false)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("mst", function()
    T.it("Kruskal MST on weighted triangle", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b", {weight = 3})
      g:add_edge("b", "c", {weight = 1})
      g:add_edge("a", "c", {weight = 2})
      local mst = graph.mst(g)
      T.ok(mst)
      -- MST of triangle has 2 edges
      T.eq(#mst, 2)
      -- Smallest edges are b-c (1) and a-c (2) — total weight 3
      local total = 0
      for i = 1, #mst do
        local w = mst[i][3] and mst[i][3].weight or 1
        total = total + w
      end
      T.eq(total, 3)
    end)
    T.it("MST on four-node graph", function()
      --  a-1-b
      --  |   |
      --  4   2
      --  |   |
      --  d-3-c
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c"); g:add_node("d")
      g:add_edge("a", "b", {weight = 1})
      g:add_edge("b", "c", {weight = 2})
      g:add_edge("c", "d", {weight = 3})
      g:add_edge("a", "d", {weight = 4})
      local mst = graph.mst(g)
      T.eq(#mst, 3)  -- V-1 edges for connected graph
      local total = 0
      for i = 1, #mst do
        local w = mst[i][3] and mst[i][3].weight or 1
        total = total + w
      end
      T.eq(total, 6)  -- 1+2+3
    end)
    T.it("MST on unweighted graph uses weight=1", function()
      local g = graph.new()
      g:add_node("a"); g:add_node("b"); g:add_node("c")
      g:add_edge("a", "b"); g:add_edge("b", "c")
      local mst = graph.mst(g)
      T.eq(#mst, 2)
    end)
    T.it("returns nil for directed graph", function()
      local dg = graph.new({directed = true})
      local r, err = graph.mst(dg)
      T.eq(r, nil); T.ok(err)
    end)
    T.it("empty graph MST is empty", function()
      local g = graph.new()
      local mst = graph.mst(g)
      T.eq(#mst, 0)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("strongly_connected", function()
    T.it("finds SCCs with cycle + isolated node", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c"); dg:add_node("d")
      dg:add_edge("a", "b"); dg:add_edge("b", "c"); dg:add_edge("c", "a")
      dg:add_edge("c", "d")
      local sccs = graph.strongly_connected(dg)
      T.eq(#sccs, 2)
      local big, small
      for i = 1, #sccs do
        if #sccs[i] == 3 then big = sccs[i]
        elseif #sccs[i] == 1 then small = sccs[i] end
      end
      T.ok(big); T.ok(small)
      T.ok(has(big, "a")); T.ok(has(big, "b")); T.ok(has(big, "c"))
      T.eq(small[1], "d")
    end)
    T.it("each node is own SCC in DAG", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("b", "c")
      local sccs = graph.strongly_connected(dg)
      T.eq(#sccs, 3)
      for i = 1, #sccs do T.eq(#sccs[i], 1) end
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("transpose", function()
    T.it("reverses all edges", function()
      local dg = graph.new({directed = true})
      dg:add_node("a", {v = 1}); dg:add_node("b")
      dg:add_edge("a", "b", {weight = 5})
      local t = graph.transpose(dg)
      T.ok(t:has_edge("b", "a"))
      T.eq(t:has_edge("a", "b"), false)
      T.eq(t:edge_data("b", "a").weight, 5)
      T.eq(t:node_count(), 2)
      T.eq(t:edge_count(), 1)
      T.eq(t:node_data("a").v, 1)
    end)
    T.it("double transpose restores original edges", function()
      local dg = graph.new({directed = true})
      dg:add_node("a"); dg:add_node("b"); dg:add_node("c")
      dg:add_edge("a", "b"); dg:add_edge("b", "c")
      local tt = graph.transpose(graph.transpose(dg))
      T.ok(tt:has_edge("a", "b"))
      T.ok(tt:has_edge("b", "c"))
      T.eq(tt:has_edge("b", "a"), false)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("edge cases", function()
    T.it("large chain traversal", function()
      local g = graph.new({directed = true})
      local N = 50
      for i = 1, N do g:add_node(i) end
      for i = 1, N-1 do g:add_edge(i, i+1, {weight = 1}) end
      local order = graph.bfs(g, 1)
      T.eq(#order, N)
      T.eq(order[1], 1); T.eq(order[N], N)
      local dist, path = graph.shortest_path(g, 1, N)
      T.eq(dist[N], N-1)
      T.eq(#path, N)
    end)
    T.it("self-loop in undirected graph", function()
      local g = graph.new()
      g:add_node("a"); g:add_edge("a", "a")
      T.ok(g:has_edge("a", "a"))
      T.eq(g:edge_count(), 1)
    end)
  end)

end)
