if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local graph = require("lib.graph")

-- Helper: sort an array of values for deterministic comparison
local function sorted(arr)
	local copy = {}
	for i = 1, #arr do copy[i] = arr[i] end
	table.sort(copy)
	return copy
end

-- Helper: check if array contains a value
local function contains(arr, val)
	for i = 1, #arr do
		if arr[i] == val then return true end
	end
	return false
end

-- Helper: find which component contains a vertex
local function find_component(components, v)
	for i = 1, #components do
		for j = 1, #components[i] do
			if components[i][j] == v then return i end
		end
	end
	return nil
end

T.describe("graph", function()

	T.describe("new", function()
		T.it("creates a directed graph by default", function()
			local g = graph.new()
			T.ok(g, "graph created")
			T.eq(g._directed, true)
		end)

		T.it("creates an undirected graph", function()
			local g = graph.new({ directed = false })
			T.eq(g._directed, false)
		end)
	end)

	T.describe("vertices", function()
		T.it("adds and queries vertices", function()
			local g = graph.new()
			T.ok(g:add_vertex("a", { label = "Start" }))
			T.ok(g:add_vertex("b"))
			T.eq(g:vertex_count(), 2)
			T.ok(g:has_vertex("a"))
			T.ok(g:has_vertex("b"))
			T.eq(g:has_vertex("c"), false)
		end)

		T.it("returns vertex data", function()
			local g = graph.new()
			g:add_vertex("a", { label = "Start" })
			g:add_vertex("b")
			local data = g:vertex_data("a")
			T.eq(data.label, "Start")
			T.eq(g:vertex_data("b"), nil)
			T.eq(g:vertex_data("z"), nil)
		end)

		T.it("prevents duplicate vertices", function()
			local g = graph.new()
			T.ok(g:add_vertex("a"))
			T.eq(g:add_vertex("a"), false)
			T.eq(g:vertex_count(), 1)
		end)

		T.it("removes vertices", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b")
			T.ok(g:remove_vertex("a"))
			T.eq(g:has_vertex("a"), false)
			T.eq(g:vertex_count(), 1)
			T.eq(g:edge_count(), 0)
		end)

		T.it("returns false removing nonexistent vertex", function()
			local g = graph.new()
			T.eq(g:remove_vertex("x"), false)
		end)

		T.it("lists vertices", function()
			local g = graph.new()
			g:add_vertex("c")
			g:add_vertex("a")
			g:add_vertex("b")
			local verts = sorted(g:vertices())
			T.eq(#verts, 3)
			T.eq(verts[1], "a")
			T.eq(verts[2], "b")
			T.eq(verts[3], "c")
		end)
	end)

	T.describe("edges (directed)", function()
		T.it("adds and queries edges", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			local ok, err = g:add_edge("a", "b", 2.5)
			T.ok(ok)
			T.eq(err, nil)
			T.ok(g:has_edge("a", "b"))
			T.eq(g:has_edge("b", "a"), false) -- directed
			T.eq(g:edge_weight("a", "b"), 2.5)
			T.eq(g:edge_count(), 1)
		end)

		T.it("defaults weight to 1", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b")
			T.eq(g:edge_weight("a", "b"), 1)
		end)

		T.it("prevents duplicate edges", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b")
			local ok, err = g:add_edge("a", "b")
			T.eq(ok, false)
			T.ok(err)
		end)

		T.it("returns error for missing vertex", function()
			local g = graph.new()
			g:add_vertex("a")
			local ok, err = g:add_edge("a", "z")
			T.eq(ok, false)
			T.ok(err)
		end)

		T.it("removes edges", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b")
			T.ok(g:remove_edge("a", "b"))
			T.eq(g:has_edge("a", "b"), false)
			T.eq(g:edge_count(), 0)
		end)

		T.it("returns false removing nonexistent edge", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			T.eq(g:remove_edge("a", "b"), false)
			T.eq(g:remove_edge("x", "y"), false)
		end)

		T.it("lists all edges", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b", 1)
			g:add_edge("b", "c", 2)
			local edges = g:edges()
			T.eq(#edges, 2)
		end)
	end)

	T.describe("edges (undirected)", function()
		T.it("stores both directions", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b", 3)
			T.ok(g:has_edge("a", "b"))
			T.ok(g:has_edge("b", "a"))
			T.eq(g:edge_weight("a", "b"), 3)
			T.eq(g:edge_weight("b", "a"), 3)
			T.eq(g:edge_count(), 1)
		end)

		T.it("deduplicates edges in listing", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b")
			local edges = g:edges()
			T.eq(#edges, 1)
		end)

		T.it("removes both directions", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b")
			T.ok(g:remove_edge("a", "b"))
			T.eq(g:has_edge("a", "b"), false)
			T.eq(g:has_edge("b", "a"), false)
			T.eq(g:edge_count(), 0)
		end)
	end)

	T.describe("neighbors", function()
		T.it("returns outgoing neighbors (directed)", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("a", "c")
			local n = sorted(g:neighbors("a"))
			T.eq(#n, 2)
			T.eq(n[1], "b")
			T.eq(n[2], "c")
			T.eq(#g:neighbors("b"), 0)
		end)

		T.it("returns in-neighbors (directed)", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "c")
			g:add_edge("b", "c")
			local n = sorted(g:in_neighbors("c"))
			T.eq(#n, 2)
			T.eq(n[1], "a")
			T.eq(n[2], "b")
		end)

		T.it("degree and in_degree", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("a", "c")
			g:add_edge("b", "c")
			T.eq(g:degree("a"), 2)
			T.eq(g:degree("b"), 1)
			T.eq(g:in_degree("c"), 2)
			T.eq(g:in_degree("a"), 0)
		end)

		T.it("undirected neighbors", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			local n = sorted(g:neighbors("b"))
			T.eq(#n, 2)
			T.eq(n[1], "a")
			T.eq(n[2], "c")
			-- in_neighbors same as neighbors for undirected
			T.eq(#g:in_neighbors("b"), 2)
		end)
	end)

	T.describe("bfs", function()
		T.it("traverses in breadth-first order", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_vertex("d")
			g:add_edge("a", "b")
			g:add_edge("a", "c")
			g:add_edge("b", "d")
			g:add_edge("c", "d")
			local order = graph.bfs(g, "a")
			T.eq(order[1], "a")
			T.eq(#order, 4)
			-- b and c before d
			local pos = {}
			for i = 1, #order do pos[order[i]] = i end
			T.ok(pos["b"] < pos["d"])
			T.ok(pos["c"] < pos["d"])
		end)

		T.it("returns empty for nonexistent start", function()
			local g = graph.new()
			T.eq(#graph.bfs(g, "x"), 0)
		end)
	end)

	T.describe("dfs", function()
		T.it("traverses in depth-first order", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_vertex("d")
			g:add_edge("a", "b")
			g:add_edge("a", "c")
			g:add_edge("b", "d")
			local order = graph.dfs(g, "a")
			T.eq(order[1], "a")
			T.eq(#order, 4)
			T.ok(contains(order, "b"))
			T.ok(contains(order, "c"))
			T.ok(contains(order, "d"))
		end)

		T.it("returns empty for nonexistent start", function()
			local g = graph.new()
			T.eq(#graph.dfs(g, "x"), 0)
		end)
	end)

	T.describe("topological_sort", function()
		T.it("sorts a DAG", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_vertex("d")
			g:add_edge("a", "b")
			g:add_edge("a", "c")
			g:add_edge("b", "d")
			g:add_edge("c", "d")
			local order, err = graph.topological_sort(g)
			T.ok(order)
			T.eq(err, nil)
			T.eq(#order, 4)
			-- a before b and c; b and c before d
			local pos = {}
			for i = 1, #order do pos[order[i]] = i end
			T.ok(pos["a"] < pos["b"])
			T.ok(pos["a"] < pos["c"])
			T.ok(pos["b"] < pos["d"])
			T.ok(pos["c"] < pos["d"])
		end)

		T.it("detects cycles", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			g:add_edge("c", "a")
			local order, err = graph.topological_sort(g)
			T.eq(order, nil)
			T.eq(err, "cycle detected")
		end)

		T.it("errors on undirected graph", function()
			local g = graph.new({ directed = false })
			local order, err = graph.topological_sort(g)
			T.eq(order, nil)
			T.ok(err)
		end)
	end)

	T.describe("shortest_path", function()
		T.it("finds shortest path in weighted graph", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_vertex("d")
			g:add_edge("a", "b", 1)
			g:add_edge("b", "d", 5)
			g:add_edge("a", "c", 2)
			g:add_edge("c", "d", 1)
			local result = graph.shortest_path(g, "a", "d")
			T.ok(result)
			T.eq(result.distance, 3)
			T.eq(#result.path, 3)
			T.eq(result.path[1], "a")
			T.eq(result.path[2], "c")
			T.eq(result.path[3], "d")
		end)

		T.it("returns nil when no path exists", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			local result = graph.shortest_path(g, "a", "b")
			T.eq(result, nil)
		end)

		T.it("returns nil for nonexistent vertices", function()
			local g = graph.new()
			T.eq(graph.shortest_path(g, "a", "b"), nil)
		end)

		T.it("finds direct path", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_edge("a", "b", 7)
			local result = graph.shortest_path(g, "a", "b")
			T.ok(result)
			T.eq(result.distance, 7)
			T.eq(#result.path, 2)
		end)

		T.it("path to self is zero", function()
			local g = graph.new()
			g:add_vertex("a")
			local result = graph.shortest_path(g, "a", "a")
			T.ok(result)
			T.eq(result.distance, 0)
			T.eq(#result.path, 1)
			T.eq(result.path[1], "a")
		end)
	end)

	T.describe("has_cycle", function()
		T.it("detects cycle in directed graph", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			g:add_edge("c", "a")
			T.ok(graph.has_cycle(g))
		end)

		T.it("returns false for DAG", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("a", "c")
			T.eq(graph.has_cycle(g), false)
		end)

		T.it("detects self-loop", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_edge("a", "a")
			T.ok(graph.has_cycle(g))
		end)

		T.it("detects cycle in undirected graph", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			g:add_edge("c", "a")
			T.ok(graph.has_cycle(g))
		end)

		T.it("no cycle in undirected tree", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			T.eq(graph.has_cycle(g), false)
		end)

		T.it("empty graph has no cycle", function()
			local g = graph.new()
			T.eq(graph.has_cycle(g), false)
		end)
	end)

	T.describe("connected_components", function()
		T.it("finds components in undirected graph", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_vertex("d")
			g:add_edge("a", "b")
			g:add_edge("c", "d")
			local comps = graph.connected_components(g)
			T.eq(#comps, 2)
			-- a and b in same component
			local ca = find_component(comps, "a")
			local cb = find_component(comps, "b")
			local cc = find_component(comps, "c")
			local cd = find_component(comps, "d")
			T.eq(ca, cb)
			T.eq(cc, cd)
			T.neq(ca, cc)
		end)

		T.it("single connected component", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			local comps = graph.connected_components(g)
			T.eq(#comps, 1)
			T.eq(#comps[1], 3)
		end)

		T.it("isolated vertices are their own components", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			local comps = graph.connected_components(g)
			T.eq(#comps, 2)
		end)

		T.it("empty graph", function()
			local g = graph.new({ directed = false })
			local comps = graph.connected_components(g)
			T.eq(#comps, 0)
		end)
	end)

	T.describe("strongly_connected", function()
		T.it("finds SCCs in directed graph", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_vertex("d")
			-- a -> b -> c -> a (cycle), d is separate
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			g:add_edge("c", "a")
			g:add_edge("c", "d")
			local sccs = graph.strongly_connected(g)
			-- Should have 2 SCCs: {a,b,c} and {d}
			T.eq(#sccs, 2)
			local big, small
			for i = 1, #sccs do
				if #sccs[i] == 3 then big = sccs[i]
				elseif #sccs[i] == 1 then small = sccs[i]
				end
			end
			T.ok(big, "found SCC of size 3")
			T.ok(small, "found SCC of size 1")
			T.ok(contains(big, "a"))
			T.ok(contains(big, "b"))
			T.ok(contains(big, "c"))
			T.eq(small[1], "d")
		end)

		T.it("each vertex is its own SCC in DAG", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			local sccs = graph.strongly_connected(g)
			T.eq(#sccs, 3)
			for i = 1, #sccs do
				T.eq(#sccs[i], 1)
			end
		end)
	end)

	T.describe("transpose", function()
		T.it("reverses edges in directed graph", function()
			local g = graph.new()
			g:add_vertex("a", { label = "A" })
			g:add_vertex("b")
			g:add_edge("a", "b", 5)
			local t = graph.transpose(g)
			T.eq(t:has_edge("b", "a"), true)
			T.eq(t:has_edge("a", "b"), false)
			T.eq(t:edge_weight("b", "a"), 5)
			T.eq(t:vertex_count(), 2)
			T.eq(t:edge_count(), 1)
			-- Preserves vertex data
			T.eq(t:vertex_data("a").label, "A")
		end)

		T.it("transpose of transpose is original edges", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			local tt = graph.transpose(graph.transpose(g))
			T.ok(tt:has_edge("a", "b"))
			T.ok(tt:has_edge("b", "c"))
			T.eq(tt:has_edge("b", "a"), false)
		end)
	end)

	T.describe("edge cases", function()
		T.it("empty graph operations", function()
			local g = graph.new()
			T.eq(g:vertex_count(), 0)
			T.eq(g:edge_count(), 0)
			T.eq(#g:vertices(), 0)
			T.eq(#g:edges(), 0)
			T.eq(g:has_vertex("a"), false)
			T.eq(g:has_edge("a", "b"), false)
			T.eq(g:edge_weight("a", "b"), nil)
			T.eq(#g:neighbors("a"), 0)
			T.eq(g:degree("a"), 0)
		end)

		T.it("single vertex graph", function()
			local g = graph.new()
			g:add_vertex("a")
			T.eq(g:vertex_count(), 1)
			T.eq(g:edge_count(), 0)
			T.eq(#g:neighbors("a"), 0)
			local bfs_result = graph.bfs(g, "a")
			T.eq(#bfs_result, 1)
			T.eq(bfs_result[1], "a")
		end)

		T.it("self-loop", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_edge("a", "a", 1)
			T.ok(g:has_edge("a", "a"))
			T.eq(g:edge_count(), 1)
			T.eq(g:degree("a"), 1)
		end)

		T.it("numeric vertex ids", function()
			local g = graph.new()
			g:add_vertex(1)
			g:add_vertex(2)
			g:add_edge(1, 2)
			T.ok(g:has_edge(1, 2))
			T.eq(g:edge_weight(1, 2), 1)
		end)

		T.it("remove vertex cleans up directed in-edges", function()
			local g = graph.new()
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("c", "b")
			g:remove_vertex("b")
			T.eq(g:edge_count(), 0)
			T.eq(g:has_edge("a", "b"), false)
			T.eq(g:degree("a"), 0)
		end)

		T.it("remove vertex cleans up undirected edges", function()
			local g = graph.new({ directed = false })
			g:add_vertex("a")
			g:add_vertex("b")
			g:add_vertex("c")
			g:add_edge("a", "b")
			g:add_edge("b", "c")
			g:remove_vertex("b")
			T.eq(g:edge_count(), 0)
			T.eq(g:has_edge("a", "b"), false)
			T.eq(g:has_edge("c", "b"), false)
			T.eq(g:degree("a"), 0)
			T.eq(g:degree("c"), 0)
		end)
	end)

end)
