if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local ringbuf = require("lib.ringbuf")

T.describe("ringbuf", function()
	T.describe("new", function()
		T.it("creates a ring buffer", function()
			local rb = ringbuf.new(4)
			T.ok(rb)
			T.eq(rb:capacity(), 4)
			T.eq(rb:size(), 0)
			T.ok(rb:empty())
			T.ok(not rb:full())
		end)

		T.it("rejects invalid capacity", function()
			local r, err = ringbuf.new(0)
			T.eq(r, nil)
			T.ok(err)
			r, err = ringbuf.new(-1)
			T.eq(r, nil)
			T.ok(err)
			r, err = ringbuf.new(1.5)
			T.eq(r, nil)
			T.ok(err)
			r, err = ringbuf.new("abc")
			T.eq(r, nil)
			T.ok(err)
		end)
	end)

	T.describe("push_back / pop_front", function()
		T.it("basic FIFO", function()
			local rb = ringbuf.new(4)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			T.eq(rb:size(), 3)
			T.eq(rb:pop_front(), 1)
			T.eq(rb:pop_front(), 2)
			T.eq(rb:pop_front(), 3)
			T.eq(rb:pop_front(), nil)
			T.ok(rb:empty())
		end)
	end)

	T.describe("push_front / pop_back", function()
		T.it("basic LIFO from front", function()
			local rb = ringbuf.new(4)
			rb:push_front(1)
			rb:push_front(2)
			rb:push_front(3)
			T.eq(rb:size(), 3)
			T.eq(rb:pop_back(), 1)
			T.eq(rb:pop_back(), 2)
			T.eq(rb:pop_back(), 3)
			T.eq(rb:pop_back(), nil)
		end)
	end)

	T.describe("push_back / pop_back", function()
		T.it("stack behavior", function()
			local rb = ringbuf.new(4)
			rb:push_back(10)
			rb:push_back(20)
			rb:push_back(30)
			T.eq(rb:pop_back(), 30)
			T.eq(rb:pop_back(), 20)
			T.eq(rb:pop_back(), 10)
		end)
	end)

	T.describe("push_front / pop_front", function()
		T.it("stack behavior from front", function()
			local rb = ringbuf.new(4)
			rb:push_front(10)
			rb:push_front(20)
			rb:push_front(30)
			T.eq(rb:pop_front(), 30)
			T.eq(rb:pop_front(), 20)
			T.eq(rb:pop_front(), 10)
		end)
	end)

	T.describe("overflow wrapping", function()
		T.it("push_back overwrites oldest when full", function()
			local rb = ringbuf.new(3)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			T.ok(rb:full())
			rb:push_back(4) -- overwrites 1
			T.eq(rb:size(), 3)
			T.eq(rb:pop_front(), 2)
			T.eq(rb:pop_front(), 3)
			T.eq(rb:pop_front(), 4)
		end)

		T.it("push_front overwrites newest when full", function()
			local rb = ringbuf.new(3)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			rb:push_front(0) -- overwrites 3
			T.eq(rb:size(), 3)
			T.eq(rb:pop_front(), 0)
			T.eq(rb:pop_front(), 1)
			T.eq(rb:pop_front(), 2)
		end)

		T.it("multiple overwrites", function()
			local rb = ringbuf.new(2)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			rb:push_back(4)
			T.eq(rb:pop_front(), 3)
			T.eq(rb:pop_front(), 4)
		end)
	end)

	T.describe("peek", function()
		T.it("peek_front and peek_back", function()
			local rb = ringbuf.new(4)
			T.eq(rb:peek_front(), nil)
			T.eq(rb:peek_back(), nil)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			T.eq(rb:peek_front(), 1)
			T.eq(rb:peek_back(), 3)
			T.eq(rb:size(), 3) -- peek does not remove
		end)
	end)

	T.describe("get", function()
		T.it("1-based indexing from front", function()
			local rb = ringbuf.new(4)
			rb:push_back(10)
			rb:push_back(20)
			rb:push_back(30)
			T.eq(rb:get(1), 10)
			T.eq(rb:get(2), 20)
			T.eq(rb:get(3), 30)
			T.eq(rb:get(0), nil)
			T.eq(rb:get(4), nil)
		end)

		T.it("get after wraparound", function()
			local rb = ringbuf.new(3)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			rb:push_back(4) -- wraps, now [2,3,4]
			T.eq(rb:get(1), 2)
			T.eq(rb:get(2), 3)
			T.eq(rb:get(3), 4)
		end)
	end)

	T.describe("to_array", function()
		T.it("returns front-to-back order", function()
			local rb = ringbuf.new(4)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			local a = rb:to_array()
			T.eq(#a, 3)
			T.eq(a[1], 1)
			T.eq(a[2], 2)
			T.eq(a[3], 3)
		end)

		T.it("correct after wraparound", function()
			local rb = ringbuf.new(3)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			rb:push_back(4)
			rb:push_back(5) -- now [3,4,5]
			local a = rb:to_array()
			T.eq(#a, 3)
			T.eq(a[1], 3)
			T.eq(a[2], 4)
			T.eq(a[3], 5)
		end)

		T.it("empty buffer returns empty array", function()
			local rb = ringbuf.new(4)
			local a = rb:to_array()
			T.eq(#a, 0)
		end)
	end)

	T.describe("iter", function()
		T.it("iterates front-to-back", function()
			local rb = ringbuf.new(4)
			rb:push_back(10)
			rb:push_back(20)
			rb:push_back(30)
			local collected = {}
			for i, v in rb:iter() do
				collected[i] = v
			end
			T.eq(#collected, 3)
			T.eq(collected[1], 10)
			T.eq(collected[2], 20)
			T.eq(collected[3], 30)
		end)
	end)

	T.describe("clear", function()
		T.it("resets to empty", function()
			local rb = ringbuf.new(4)
			rb:push_back(1)
			rb:push_back(2)
			rb:clear()
			T.ok(rb:empty())
			T.eq(rb:size(), 0)
			T.eq(rb:pop_front(), nil)
		end)
	end)

	T.describe("drain", function()
		T.it("returns all elements and empties buffer", function()
			local rb = ringbuf.new(4)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			local a = rb:drain()
			T.eq(#a, 3)
			T.eq(a[1], 1)
			T.eq(a[2], 2)
			T.eq(a[3], 3)
			T.ok(rb:empty())
			T.eq(rb:size(), 0)
		end)
	end)

	T.describe("mixed push_front / push_back", function()
		T.it("interleaved operations", function()
			local rb = ringbuf.new(5)
			rb:push_back(3)
			rb:push_front(2)
			rb:push_back(4)
			rb:push_front(1)
			-- order: 1, 2, 3, 4
			T.eq(rb:get(1), 1)
			T.eq(rb:get(2), 2)
			T.eq(rb:get(3), 3)
			T.eq(rb:get(4), 4)
			T.eq(rb:size(), 4)
			local a = rb:to_array()
			T.eq(a[1], 1)
			T.eq(a[2], 2)
			T.eq(a[3], 3)
			T.eq(a[4], 4)
		end)
	end)

	T.describe("capacity 1 edge case", function()
		T.it("push_back overwrites the single slot", function()
			local rb = ringbuf.new(1)
			rb:push_back(1)
			T.ok(rb:full())
			T.eq(rb:peek_front(), 1)
			rb:push_back(2)
			T.eq(rb:size(), 1)
			T.eq(rb:pop_front(), 2)
			T.ok(rb:empty())
		end)

		T.it("push_front overwrites the single slot", function()
			local rb = ringbuf.new(1)
			rb:push_front(1)
			rb:push_front(2)
			T.eq(rb:size(), 1)
			T.eq(rb:pop_back(), 2)
		end)
	end)

	T.describe("large capacity", function()
		T.it("handles 1000 elements", function()
			local rb = ringbuf.new(1000)
			for i = 1, 1000 do
				rb:push_back(i)
			end
			T.ok(rb:full())
			T.eq(rb:size(), 1000)
			T.eq(rb:get(1), 1)
			T.eq(rb:get(1000), 1000)
			-- push more, causing wraparound
			for i = 1001, 1500 do
				rb:push_back(i)
			end
			T.eq(rb:size(), 1000)
			T.eq(rb:get(1), 501)
			T.eq(rb:get(1000), 1500)
		end)
	end)

	T.describe("sliding window use case", function()
		T.it("maintains last N items", function()
			local rb = ringbuf.new(3)
			for i = 1, 10 do
				rb:push_back(i)
			end
			-- should contain [8, 9, 10]
			T.eq(rb:size(), 3)
			T.eq(rb:get(1), 8)
			T.eq(rb:get(2), 9)
			T.eq(rb:get(3), 10)
		end)
	end)

	T.describe("pop then push reuse", function()
		T.it("correctly reuses slots after pop", function()
			local rb = ringbuf.new(3)
			rb:push_back(1)
			rb:push_back(2)
			rb:push_back(3)
			rb:pop_front() -- remove 1
			rb:pop_front() -- remove 2
			rb:push_back(4)
			rb:push_back(5)
			-- should be [3, 4, 5]
			T.eq(rb:size(), 3)
			T.eq(rb:get(1), 3)
			T.eq(rb:get(2), 4)
			T.eq(rb:get(3), 5)
		end)
	end)

	T.describe("nil values", function()
		T.it("can store false as a value", function()
			local rb = ringbuf.new(3)
			rb:push_back(false)
			rb:push_back(0)
			rb:push_back("")
			T.eq(rb:get(1), false)
			T.eq(rb:get(2), 0)
			T.eq(rb:get(3), "")
			T.eq(rb:pop_front(), false)
		end)
	end)
end)
