-- lib/unified/retext_indefinite_article/retext_indefinite_article_test.lua
local T      = require("lib.test.assert")
local retext = require("lib.unified.retext")
local plugin = require("lib.unified.retext_indefinite_article")

T.describe("retext_indefinite_article", function()
  T.it("populates root.data.indefinite_article", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("I saw a apple fall.")
    tree = proc:run(tree)
    T.ok(tree.data ~= nil, "data exists")
    T.ok(tree.data.indefinite_article ~= nil, "indefinite_article key exists")
    T.ok(type(tree.data.indefinite_article) == "table", "is table")
  end)

  T.it("flags 'a apple' (should be 'an apple')", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("I ate a apple.")
    tree = proc:run(tree)
    local ia = tree.data.indefinite_article
    T.ok(#ia > 0, "error found")
    T.eq(ia[1].actual, "a")
    T.eq(ia[1].expected, "an")
    T.eq(ia[1].word, "apple")
  end)

  T.it("flags 'an cat' (should be 'a cat')", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("I saw an cat.")
    tree = proc:run(tree)
    local ia = tree.data.indefinite_article
    T.ok(#ia > 0, "error found")
    T.eq(ia[1].actual, "an")
    T.eq(ia[1].expected, "a")
    T.eq(ia[1].word, "cat")
  end)

  T.it("accepts 'an hour' (silent h)", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("It took an hour.")
    tree = proc:run(tree)
    T.eq(#tree.data.indefinite_article, 0, "an hour is correct")
  end)

  T.it("flags 'an uniform' (you-sound u)", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("She wore an uniform.")
    tree = proc:run(tree)
    local ia = tree.data.indefinite_article
    T.ok(#ia > 0, "an uniform should be a uniform")
    T.eq(ia[1].expected, "a")
  end)

  T.it("accepts 'an FBI' (abbreviation, F has vowel sound)", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("She joined an FBI task force.")
    tree = proc:run(tree)
    T.eq(#tree.data.indefinite_article, 0, "an FBI is correct")
  end)

  T.it("returns empty for correct usage", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("I have an idea and a plan.")
    tree = proc:run(tree)
    T.eq(#tree.data.indefinite_article, 0, "correct usage produces no findings")
  end)

  T.it("each finding has actual, expected, word, sentence fields", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("I ate a orange.")
    tree = proc:run(tree)
    local ia = tree.data.indefinite_article
    T.ok(#ia > 0, "finding exists")
    T.ok(type(ia[1].actual) == "string", "actual is string")
    T.ok(type(ia[1].expected) == "string", "expected is string")
    T.ok(type(ia[1].word) == "string", "word is string")
    T.ok(type(ia[1].sentence) == "string", "sentence is string")
  end)
end)
