if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local mime = require("lib.mime")
local T = require("lib.test.assert")

T.describe("mime.lookup", function()
	T.it("html", function()
		T.eq(mime.lookup("file.html"), "text/html")
	end)
	T.it("htm", function()
		T.eq(mime.lookup("file.htm"), "text/html")
	end)
	T.it("css", function()
		T.eq(mime.lookup("style.css"), "text/css")
	end)
	T.it("js", function()
		T.eq(mime.lookup("app.js"), "text/javascript")
	end)
	T.it("mjs", function()
		T.eq(mime.lookup("mod.mjs"), "text/javascript")
	end)
	T.it("json", function()
		T.eq(mime.lookup("data.json"), "application/json")
	end)
	T.it("xml", function()
		T.eq(mime.lookup("feed.xml"), "text/xml")
	end)
	T.it("csv", function()
		T.eq(mime.lookup("data.csv"), "text/csv")
	end)
	T.it("txt", function()
		T.eq(mime.lookup("readme.txt"), "text/plain")
	end)
	T.it("markdown", function()
		T.eq(mime.lookup("doc.md"), "text/markdown")
	end)
	T.it("yaml", function()
		T.eq(mime.lookup("config.yaml"), "text/yaml")
	end)
	T.it("yml alias", function()
		T.eq(mime.lookup("config.yml"), "text/yaml")
	end)
	T.it("jpeg", function()
		T.eq(mime.lookup("photo.jpg"), "image/jpeg")
	end)
	T.it("jpeg long ext", function()
		T.eq(mime.lookup("photo.jpeg"), "image/jpeg")
	end)
	T.it("png", function()
		T.eq(mime.lookup("icon.png"), "image/png")
	end)
	T.it("gif", function()
		T.eq(mime.lookup("anim.gif"), "image/gif")
	end)
	T.it("svg", function()
		T.eq(mime.lookup("logo.svg"), "image/svg+xml")
	end)
	T.it("webp", function()
		T.eq(mime.lookup("img.webp"), "image/webp")
	end)
	T.it("ico", function()
		T.eq(mime.lookup("favicon.ico"), "image/x-icon")
	end)
	T.it("bmp", function()
		T.eq(mime.lookup("pic.bmp"), "image/bmp")
	end)
	T.it("tiff", function()
		T.eq(mime.lookup("scan.tiff"), "image/tiff")
	end)
	T.it("avif", function()
		T.eq(mime.lookup("photo.avif"), "image/avif")
	end)
	T.it("mp3", function()
		T.eq(mime.lookup("song.mp3"), "audio/mpeg")
	end)
	T.it("wav", function()
		T.eq(mime.lookup("sound.wav"), "audio/wav")
	end)
	T.it("ogg audio", function()
		T.eq(mime.lookup("track.ogg"), "audio/ogg")
	end)
	T.it("flac", function()
		T.eq(mime.lookup("lossless.flac"), "audio/flac")
	end)
	T.it("aac", function()
		T.eq(mime.lookup("audio.aac"), "audio/aac")
	end)
	T.it("mp4 video", function()
		T.eq(mime.lookup("clip.mp4"), "video/mp4")
	end)
	T.it("webm video", function()
		T.eq(mime.lookup("vid.webm"), "video/webm")
	end)
	T.it("avi", function()
		T.eq(mime.lookup("movie.avi"), "video/x-msvideo")
	end)
	T.it("mkv", function()
		T.eq(mime.lookup("film.mkv"), "video/x-matroska")
	end)
	T.it("mov", function()
		T.eq(mime.lookup("take.mov"), "video/quicktime")
	end)
	T.it("pdf", function()
		T.eq(mime.lookup("doc.pdf"), "application/pdf")
	end)
	T.it("zip", function()
		T.eq(mime.lookup("archive.zip"), "application/zip")
	end)
	T.it("gz", function()
		T.eq(mime.lookup("file.gz"), "application/gzip")
	end)
	T.it("tar", function()
		T.eq(mime.lookup("archive.tar"), "application/x-tar")
	end)
	T.it("wasm", function()
		T.eq(mime.lookup("module.wasm"), "application/wasm")
	end)
	T.it("protobuf", function()
		T.eq(mime.lookup("data.protobuf"), "application/protobuf")
	end)
	T.it("woff", function()
		T.eq(mime.lookup("font.woff"), "font/woff")
	end)
	T.it("woff2", function()
		T.eq(mime.lookup("font.woff2"), "font/woff2")
	end)
	T.it("ttf", function()
		T.eq(mime.lookup("font.ttf"), "font/ttf")
	end)
	T.it("otf", function()
		T.eq(mime.lookup("font.otf"), "font/otf")
	end)
	T.it("compound tar.gz", function()
		T.eq(mime.lookup("archive.tar.gz"), "application/gzip")
	end)
	T.it("compound tar.bz2", function()
		T.eq(mime.lookup("archive.tar.bz2"), "application/x-bzip2")
	end)
	T.it("compound tar.xz", function()
		T.eq(mime.lookup("archive.tar.xz"), "application/x-xz")
	end)
	T.it("bare extension with dot", function()
		T.eq(mime.lookup(".png"), "image/png")
	end)
	T.it("unknown extension returns nil", function()
		T.eq(mime.lookup("file.xyz"), nil)
	end)
	T.it("no extension returns nil", function()
		T.eq(mime.lookup("Makefile"), nil)
	end)
	T.it("case insensitive", function()
		T.eq(mime.lookup("FILE.HTML"), "text/html")
		T.eq(mime.lookup("image.PNG"), "image/png")
		T.eq(mime.lookup("DATA.JSON"), "application/json")
	end)
	T.it("path with directories", function()
		T.eq(mime.lookup("/var/www/index.html"), "text/html")
		T.eq(mime.lookup("assets/img/logo.svg"), "image/svg+xml")
	end)
	T.it("dotfiles with extension", function()
		T.eq(mime.lookup(".bashrc.json"), "application/json")
	end)
	T.it("multiple dots", function()
		T.eq(mime.lookup("app.min.js"), "text/javascript")
	end)
end)

T.describe("mime.extension", function()
	T.it("text/html -> html", function()
		T.eq(mime.extension("text/html"), "html")
	end)
	T.it("image/jpeg -> jpg", function()
		T.eq(mime.extension("image/jpeg"), "jpg")
	end)
	T.it("application/json -> json", function()
		T.eq(mime.extension("application/json"), "json")
	end)
	T.it("image/png -> png", function()
		T.eq(mime.extension("image/png"), "png")
	end)
	T.it("text/css -> css", function()
		T.eq(mime.extension("text/css"), "css")
	end)
	T.it("text/javascript -> js", function()
		T.eq(mime.extension("text/javascript"), "js")
	end)
	T.it("application/pdf -> pdf", function()
		T.eq(mime.extension("application/pdf"), "pdf")
	end)
	T.it("font/woff2 -> woff2", function()
		T.eq(mime.extension("font/woff2"), "woff2")
	end)
	T.it("unknown type returns nil", function()
		T.eq(mime.extension("application/x-unknown-thing"), nil)
	end)
	T.it("case insensitive", function()
		T.eq(mime.extension("TEXT/HTML"), "html")
		T.eq(mime.extension("Image/PNG"), "png")
	end)
end)

T.describe("mime.charset", function()
	T.it("text/html -> UTF-8", function()
		T.eq(mime.charset("text/html"), "UTF-8")
	end)
	T.it("text/css -> UTF-8", function()
		T.eq(mime.charset("text/css"), "UTF-8")
	end)
	T.it("text/javascript -> UTF-8", function()
		T.eq(mime.charset("text/javascript"), "UTF-8")
	end)
	T.it("application/json -> UTF-8", function()
		T.eq(mime.charset("application/json"), "UTF-8")
	end)
	T.it("image/svg+xml -> UTF-8", function()
		T.eq(mime.charset("image/svg+xml"), "UTF-8")
	end)
	T.it("image/png -> nil", function()
		T.eq(mime.charset("image/png"), nil)
	end)
	T.it("application/pdf -> nil", function()
		T.eq(mime.charset("application/pdf"), nil)
	end)
	T.it("application/zip -> nil", function()
		T.eq(mime.charset("application/zip"), nil)
	end)
	T.it("case insensitive", function()
		T.eq(mime.charset("TEXT/HTML"), "UTF-8")
	end)
end)

T.describe("mime.is_text", function()
	T.it("text/html is text", function()
		T.ok(mime.is_text("text/html"))
	end)
	T.it("text/plain is text", function()
		T.ok(mime.is_text("text/plain"))
	end)
	T.it("text/css is text", function()
		T.ok(mime.is_text("text/css"))
	end)
	T.it("application/json is text", function()
		T.ok(mime.is_text("application/json"))
	end)
	T.it("image/svg+xml is text", function()
		T.ok(mime.is_text("image/svg+xml"))
	end)
	T.it("image/png is not text", function()
		T.ok(not mime.is_text("image/png"))
	end)
	T.it("application/pdf is not text", function()
		T.ok(not mime.is_text("application/pdf"))
	end)
	T.it("application/wasm is not text", function()
		T.ok(not mime.is_text("application/wasm"))
	end)
end)

T.describe("mime.is_binary", function()
	T.it("image/png is binary", function()
		T.ok(mime.is_binary("image/png"))
	end)
	T.it("application/octet-stream is binary", function()
		T.ok(mime.is_binary("application/octet-stream"))
	end)
	T.it("text/html is not binary", function()
		T.ok(not mime.is_binary("text/html"))
	end)
	T.it("application/json is not binary", function()
		T.ok(not mime.is_binary("application/json"))
	end)
end)

T.describe("mime.content_type", function()
	T.it("html with charset", function()
		T.eq(mime.content_type("file.html"), "text/html; charset=utf-8")
	end)
	T.it("css with charset", function()
		T.eq(mime.content_type("style.css"), "text/css; charset=utf-8")
	end)
	T.it("json with charset", function()
		T.eq(mime.content_type(".json"), "application/json; charset=utf-8")
	end)
	T.it("js with charset", function()
		T.eq(mime.content_type("app.js"), "text/javascript; charset=utf-8")
	end)
	T.it("svg with charset", function()
		T.eq(mime.content_type("logo.svg"), "image/svg+xml; charset=utf-8")
	end)
	T.it("jpg without charset", function()
		T.eq(mime.content_type("photo.jpg"), "image/jpeg")
	end)
	T.it("png without charset", function()
		T.eq(mime.content_type("icon.png"), "image/png")
	end)
	T.it("pdf without charset", function()
		T.eq(mime.content_type("doc.pdf"), "application/pdf")
	end)
	T.it("wasm without charset", function()
		T.eq(mime.content_type("mod.wasm"), "application/wasm")
	end)
	T.it("unknown returns nil", function()
		T.eq(mime.content_type("file.xyz"), nil)
	end)
end)

T.describe("mime.types and mime.extensions tables", function()
	T.it("types table has entries", function()
		T.ok(mime.types.html ~= nil)
		T.eq(mime.types.html, "text/html")
	end)
	T.it("extensions table has entries", function()
		T.ok(mime.extensions["text/html"] ~= nil)
		T.eq(mime.extensions["text/html"], "html")
	end)
	T.it("types count >= 100", function()
		local count = 0
		for _ in pairs(mime.types) do count = count + 1 end
		T.ok(count >= 100, "expected >= 100 mime types, got " .. count)
	end)
end)
