if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local H = require("lib.humanize")

T.describe("humanize.bytes", function()
  T.it("0 bytes", function()
    T.eq(H.bytes(0), "0 B")
  end)
  T.it("sub-kilo", function()
    T.eq(H.bytes(500), "500 B")
    T.eq(H.bytes(1023), "1023 B")
  end)
  T.it("kilobytes boundary", function()
    T.eq(H.bytes(1024), "1.0 KB")
    T.eq(H.bytes(1536), "1.5 KB")
  end)
  T.it("megabytes", function()
    T.eq(H.bytes(1048576), "1.0 MB")
  end)
  T.it("gigabytes", function()
    T.eq(H.bytes(1073741824), "1.0 GB")
  end)
  T.it("SI mode", function()
    T.eq(H.bytes(1000, {si=true}), "1.0 kB")
    T.eq(H.bytes(1500, {si=true}), "1.5 kB")
    T.eq(H.bytes(1000000, {si=true}), "1.0 MB")
  end)
end)

T.describe("humanize.parse_bytes", function()
  T.it("bare bytes", function()
    T.eq(H.parse_bytes("512B"), 512)
    T.eq(H.parse_bytes("0B"), 0)
  end)
  T.it("kilobytes", function()
    T.eq(H.parse_bytes("1 KB"), 1024)
    T.eq(H.parse_bytes("1.5 MB"), 1572864)
  end)
  T.it("gigabytes", function()
    T.eq(H.parse_bytes("1 GB"), 1073741824)
  end)
  T.it("error on bad input", function()
    local v, err = H.parse_bytes("banana")
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("humanize.duration", function()
  T.it("zero", function()
    T.eq(H.duration(0), "0s")
  end)
  T.it("seconds", function()
    T.eq(H.duration(1), "1s")
    T.eq(H.duration(59), "59s")
  end)
  T.it("minutes", function()
    T.eq(H.duration(60), "1m")
    T.eq(H.duration(90), "1m 30s")
  end)
  T.it("hours", function()
    T.eq(H.duration(3661), "1h 1m 1s")
    T.eq(H.duration(3600), "1h")
  end)
  T.it("days", function()
    T.eq(H.duration(86400), "1d")
    T.eq(H.duration(3600 * 24 + 3600), "1d 1h")
  end)
  T.it("weeks", function()
    T.eq(H.duration(604800), "1w")
    T.eq(H.duration(604800 * 2), "2w")
  end)
  T.it("sub-second milliseconds", function()
    T.eq(H.duration(0.5), "500ms")
    T.eq(H.duration(0.001), "1ms")
  end)
  T.it("compact option", function()
    T.eq(H.duration(3661, {compact=true}), "1h1m1s")
    T.eq(H.duration(90, {compact=true}), "1m30s")
  end)
  T.it("long option", function()
    T.eq(H.duration(1, {long=true}), "1 second")
    T.eq(H.duration(2, {long=true}), "2 seconds")
    T.eq(H.duration(60, {long=true}), "1 minute")
    T.eq(H.duration(7200, {long=true}), "2 hours")
  end)
  T.it("max_parts option", function()
    T.eq(H.duration(3661, {max_parts=2}), "1h 1m")
    T.eq(H.duration(86461, {max_parts=2}), "1d 0h")
  end)
end)

T.describe("humanize.parse_duration", function()
  T.it("hours and minutes", function()
    T.eq(H.parse_duration("1h 30m"), 5400)
  end)
  T.it("days and hours", function()
    T.eq(H.parse_duration("2d 4h"), 2 * 86400 + 4 * 3600)
  end)
  T.it("milliseconds", function()
    T.eq(H.parse_duration("500ms"), 0.5)
  end)
  T.it("fractional seconds", function()
    T.eq(H.parse_duration("1.5s"), 1.5)
  end)
  T.it("error on bad input", function()
    local v, err = H.parse_duration("banana")
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("humanize.ordinal", function()
  T.it("basic suffixes", function()
    T.eq(H.ordinal(1), "1st")
    T.eq(H.ordinal(2), "2nd")
    T.eq(H.ordinal(3), "3rd")
    T.eq(H.ordinal(4), "4th")
  end)
  T.it("teens are all th", function()
    T.eq(H.ordinal(11), "11th")
    T.eq(H.ordinal(12), "12th")
    T.eq(H.ordinal(13), "13th")
  end)
  T.it("twenties", function()
    T.eq(H.ordinal(21), "21st")
    T.eq(H.ordinal(22), "22nd")
  end)
  T.it("101st", function()
    T.eq(H.ordinal(101), "101st")
  end)
  T.it("111th", function()
    T.eq(H.ordinal(111), "111th")
  end)
end)

T.describe("humanize.number", function()
  T.it("integer with thousands sep", function()
    T.eq(H.number(1234567), "1,234,567")
    T.eq(H.number(1000), "1,000")
  end)
  T.it("zero", function()
    T.eq(H.number(0), "0")
  end)
  T.it("negative", function()
    T.eq(H.number(-1234), "-1,234")
  end)
  T.it("fraction", function()
    T.eq(H.number(0.000123), "0.000123")
    T.eq(H.number(1234567.89), "1,234,567.89")
  end)
  T.it("large", function()
    T.eq(H.number(1e9), "1,000,000,000")
  end)
  T.it("custom sep", function()
    T.eq(H.number(1234567, {sep="."}), "1.234.567")
  end)
end)

T.describe("humanize.percentage", function()
  T.it("default 1 decimal", function()
    T.eq(H.percentage(0.156), "15.6%")
  end)
  T.it("zero decimals rounds", function()
    T.eq(H.percentage(0.156, 0), "16%")
  end)
  T.it("exact half", function()
    T.eq(H.percentage(0.5), "50.0%")
    T.eq(H.percentage(1.0), "100.0%")
  end)
end)

T.describe("humanize.relative", function()
  T.it("seconds ago", function()
    T.eq(H.relative(5), "5 seconds ago")
    T.eq(H.relative(1), "1 second ago")
  end)
  T.it("minutes ago", function()
    T.eq(H.relative(120), "2 minutes ago")
  end)
  T.it("hours ago", function()
    T.eq(H.relative(3660), "1 hour ago")
  end)
  T.it("yesterday", function()
    T.eq(H.relative(86400), "yesterday")
  end)
  T.it("future in seconds", function()
    T.eq(H.relative(-5), "in 5 seconds")
  end)
  T.it("future in hours", function()
    T.eq(H.relative(-3600), "in an hour")
  end)
  T.it("tomorrow", function()
    T.eq(H.relative(-86400), "in tomorrow")
  end)
end)

T.describe("humanize.plural", function()
  T.it("singular", function()
    T.eq(H.plural(1, "item"), "1 item")
  end)
  T.it("plural auto", function()
    T.eq(H.plural(2, "item"), "2 items")
    T.eq(H.plural(0, "item"), "0 items")
  end)
  T.it("irregular plural", function()
    T.eq(H.plural(1, "ox", "oxen"), "1 ox")
    T.eq(H.plural(2, "ox", "oxen"), "2 oxen")
  end)
end)

T.describe("humanize.list", function()
  T.it("empty", function()
    T.eq(H.list({}), "")
  end)
  T.it("single", function()
    T.eq(H.list({"a"}), "a")
  end)
  T.it("two items", function()
    T.eq(H.list({"a", "b"}), "a and b")
  end)
  T.it("three items Oxford comma", function()
    T.eq(H.list({"a", "b", "c"}), "a, b, and c")
  end)
  T.it("custom sep", function()
    T.eq(H.list({"a", "b", "c"}, {sep=" or "}), "a, b, or c")
  end)
end)
