-- lib/text_stats/text_stats_test.lua
-- Tests for text readability and statistics library.

if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local ts = require("lib.text_stats")

-- ---------------------------------------------------------------------------
-- Basic statistics
-- ---------------------------------------------------------------------------

T.describe("char_count", function()
	T.it("counts all characters including spaces", function()
		T.eq(ts.char_count("hello world"), 11)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.char_count(""), 0)
	end)
	T.it("counts newlines and punctuation", function()
		T.eq(ts.char_count("Hi!\nBye."), 8)
	end)
end)

T.describe("letter_count", function()
	T.it("counts only alphabetic characters", function()
		T.eq(ts.letter_count("hello world"), 10)
	end)
	T.it("excludes digits and punctuation", function()
		T.eq(ts.letter_count("abc 123 !@#"), 3)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.letter_count(""), 0)
	end)
	T.it("mixed case counts all letters", function()
		T.eq(ts.letter_count("Hello World"), 10)
	end)
end)

T.describe("word_count", function()
	T.it("counts simple space-separated words", function()
		T.eq(ts.word_count("one two three"), 3)
	end)
	T.it("handles multiple spaces", function()
		T.eq(ts.word_count("one  two   three"), 3)
	end)
	T.it("handles punctuation boundaries", function()
		T.eq(ts.word_count("Hello, world! How are you?"), 5)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.word_count(""), 0)
	end)
	T.it("single word", function()
		T.eq(ts.word_count("word"), 1)
	end)
end)

T.describe("sentence_count", function()
	T.it("counts period-terminated sentences", function()
		T.eq(ts.sentence_count("Hello. World."), 2)
	end)
	T.it("counts exclamation marks", function()
		T.eq(ts.sentence_count("Hi! Bye!"), 2)
	end)
	T.it("counts question marks", function()
		T.eq(ts.sentence_count("How are you? I am fine."), 2)
	end)
	T.it("ellipsis counts as one sentence terminator", function()
		T.eq(ts.sentence_count("Wait... okay."), 2)
	end)
	T.it("mixed punctuation", function()
		T.eq(ts.sentence_count("Really?! Yes! No."), 3)
	end)
	T.it("returns at least 1 for non-empty text without punctuation", function()
		T.eq(ts.sentence_count("no punctuation here"), 1)
	end)
	T.it("empty string returns 1 (minimum)", function()
		T.eq(ts.sentence_count(""), 1)
	end)
end)

T.describe("paragraph_count", function()
	T.it("single paragraph returns 1", function()
		T.eq(ts.paragraph_count("Hello world."), 1)
	end)
	T.it("two paragraphs separated by blank line", function()
		T.eq(ts.paragraph_count("Para one.\n\nPara two."), 2)
	end)
	T.it("three paragraphs", function()
		T.eq(ts.paragraph_count("A.\n\nB.\n\nC."), 3)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.paragraph_count(""), 0)
	end)
	T.it("whitespace-only returns 0", function()
		T.eq(ts.paragraph_count("   \n  "), 0)
	end)
end)

-- ---------------------------------------------------------------------------
-- Syllable counting
-- ---------------------------------------------------------------------------

T.describe("syllables_in_word", function()
	T.it("'the' = 1 syllable", function()
		T.eq(ts.syllables_in_word("the"), 1)
	end)
	T.it("'cat' = 1 syllable", function()
		T.eq(ts.syllables_in_word("cat"), 1)
	end)
	T.it("'hello' = 2 syllables", function()
		T.eq(ts.syllables_in_word("hello"), 2)
	end)
	T.it("'beautiful' = 3 syllables", function()
		T.eq(ts.syllables_in_word("beautiful"), 3)
	end)
	T.it("'education' = 4 syllables", function()
		T.eq(ts.syllables_in_word("education"), 4)
	end)
	T.it("'a' = 1 syllable (minimum)", function()
		T.eq(ts.syllables_in_word("a"), 1)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.syllables_in_word(""), 0)
	end)
	T.it("uppercase input works", function()
		T.eq(ts.syllables_in_word("HELLO"), 2)
	end)
	T.it("'simple' = 2 syllables", function()
		T.eq(ts.syllables_in_word("simple"), 2)
	end)
end)

T.describe("syllable_count", function()
	T.it("sums syllables across all words", function()
		-- "the"=1 "cat"=1 "sat"=1 → 3
		T.eq(ts.syllable_count("the cat sat"), 3)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.syllable_count(""), 0)
	end)
	T.it("multi-syllable sentence", function()
		-- "beautiful"=3 "education"=4 → 7
		T.eq(ts.syllable_count("beautiful education"), 7)
	end)
end)

-- ---------------------------------------------------------------------------
-- Readability scores
-- ---------------------------------------------------------------------------

-- Simple test text: short, common words, short sentences
local EASY_TEXT = "The cat sat on the mat. The dog ran far. The sun was hot."

-- Complex text: longer sentences, polysyllabic words
local HARD_TEXT =
	"The implementation of sophisticated computational algorithms " ..
	"requires considerable understanding of mathematical fundamentals. " ..
	"Professionals must demonstrate comprehensive knowledge of theoretical " ..
	"foundations and practical applications simultaneously."

T.describe("flesch_reading_ease", function()
	T.it("simple text scores higher than complex text", function()
		local easy = ts.flesch_reading_ease(EASY_TEXT)
		local hard = ts.flesch_reading_ease(HARD_TEXT)
		T.ok(easy > hard, "easy (" .. easy .. ") should be > hard (" .. hard .. ")")
	end)
	T.it("returns a number", function()
		T.ok(type(ts.flesch_reading_ease(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.flesch_reading_ease(""), 0)
	end)
	T.it("simple text scores above 60", function()
		local score = ts.flesch_reading_ease(EASY_TEXT)
		T.ok(score > 60, "expected > 60, got " .. score)
	end)
	T.it("complex text scores below 60", function()
		local score = ts.flesch_reading_ease(HARD_TEXT)
		T.ok(score < 60, "expected < 60, got " .. score)
	end)
end)

T.describe("flesch_kincaid_grade", function()
	T.it("returns a number", function()
		T.ok(type(ts.flesch_kincaid_grade(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.flesch_kincaid_grade(""), 0)
	end)
	T.it("simple text has lower grade than complex", function()
		local easy = ts.flesch_kincaid_grade(EASY_TEXT)
		local hard = ts.flesch_kincaid_grade(HARD_TEXT)
		T.ok(easy < hard, "easy grade (" .. easy .. ") should be < hard (" .. hard .. ")")
	end)
	T.it("complex text grade is above 10", function()
		local grade = ts.flesch_kincaid_grade(HARD_TEXT)
		T.ok(grade > 10, "expected > 10, got " .. grade)
	end)
end)

T.describe("gunning_fog", function()
	T.it("returns a number", function()
		T.ok(type(ts.gunning_fog(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.gunning_fog(""), 0)
	end)
	T.it("complex text scores higher than simple", function()
		local easy = ts.gunning_fog(EASY_TEXT)
		local hard = ts.gunning_fog(HARD_TEXT)
		T.ok(hard > easy, "hard (" .. hard .. ") should be > easy (" .. easy .. ")")
	end)
	T.it("complex text fog index above 12", function()
		local fog = ts.gunning_fog(HARD_TEXT)
		T.ok(fog > 12, "expected > 12, got " .. fog)
	end)
end)

T.describe("smog_grade", function()
	T.it("returns a number", function()
		T.ok(type(ts.smog_grade(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.smog_grade(""), 0)
	end)
	T.it("complex text scores at least 3", function()
		local grade = ts.smog_grade(HARD_TEXT)
		T.ok(grade >= 3, "expected >= 3, got " .. grade)
	end)
end)

T.describe("automated_readability_index", function()
	T.it("returns a number", function()
		T.ok(type(ts.automated_readability_index(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.automated_readability_index(""), 0)
	end)
	T.it("complex text ARI higher than simple", function()
		local easy = ts.automated_readability_index(EASY_TEXT)
		local hard = ts.automated_readability_index(HARD_TEXT)
		T.ok(hard > easy, "hard ARI (" .. hard .. ") should be > easy (" .. easy .. ")")
	end)
end)

T.describe("coleman_liau_index", function()
	T.it("returns a number", function()
		T.ok(type(ts.coleman_liau_index(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		-- wc == 0 branch
		T.eq(ts.coleman_liau_index(""), 0)
	end)
	T.it("complex text CLI higher than simple", function()
		local easy = ts.coleman_liau_index(EASY_TEXT)
		local hard = ts.coleman_liau_index(HARD_TEXT)
		T.ok(hard > easy, "hard CLI (" .. hard .. ") should be > easy (" .. easy .. ")")
	end)
end)

T.describe("dale_chall_score", function()
	T.it("returns a number", function()
		T.ok(type(ts.dale_chall_score(EASY_TEXT)) == "number")
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.dale_chall_score(""), 0)
	end)
	T.it("text with all familiar words scores below text with unfamiliar", function()
		local simple = ts.dale_chall_score("the cat sat on the mat")
		local complex = ts.dale_chall_score(
			"the photosynthetic chlorophyll synthesizes carbohydrates automatically")
		T.ok(complex > simple, "complex (" .. complex .. ") should be > simple (" .. simple .. ")")
	end)
end)

-- ---------------------------------------------------------------------------
-- Lexical diversity
-- ---------------------------------------------------------------------------

T.describe("avg_word_length", function()
	T.it("correct average for known input", function()
		-- "cat"=3, "dog"=3, "bird"=4 → avg = 10/3 ≈ 3.333
		local avg = ts.avg_word_length("cat dog bird")
		T.ok(avg > 3.3 and avg < 3.4, "expected ~3.33, got " .. avg)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.avg_word_length(""), 0)
	end)
	T.it("single word", function()
		T.eq(ts.avg_word_length("hello"), 5)
	end)
end)

T.describe("type_token_ratio", function()
	T.it("all unique words → ratio = 1.0", function()
		T.eq(ts.type_token_ratio("one two three"), 1.0)
	end)
	T.it("all same word → ratio = 1/n", function()
		local r = ts.type_token_ratio("cat cat cat cat")
		T.ok(r > 0.24 and r < 0.26, "expected 0.25, got " .. r)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.type_token_ratio(""), 0)
	end)
	T.it("partial repetition", function()
		-- "the the cat" → 2 unique / 3 total ≈ 0.667
		local r = ts.type_token_ratio("the the cat")
		T.ok(r > 0.66 and r < 0.68, "expected ~0.667, got " .. r)
	end)
end)

T.describe("lexical_density", function()
	T.it("returns a number between 0 and 1", function()
		local d = ts.lexical_density(EASY_TEXT)
		T.ok(d >= 0 and d <= 1, "expected 0-1, got " .. d)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.lexical_density(""), 0)
	end)
	T.it("all stopwords → low density", function()
		local d = ts.lexical_density("the and or but")
		T.ok(d < 0.1, "expected near 0, got " .. d)
	end)
	T.it("content-heavy text → high density", function()
		local d = ts.lexical_density("sophisticated algorithms generate beautiful mathematics")
		T.ok(d > 0.8, "expected > 0.8, got " .. d)
	end)
end)

-- ---------------------------------------------------------------------------
-- Frequency analysis
-- ---------------------------------------------------------------------------

T.describe("word_frequency", function()
	T.it("counts each word correctly", function()
		local freq = ts.word_frequency("the cat sat on the mat")
		T.eq(freq["the"], 2)
		T.eq(freq["cat"], 1)
		T.eq(freq["sat"], 1)
		T.eq(freq["on"], 1)
		T.eq(freq["mat"], 1)
	end)
	T.it("lowercases words", function()
		local freq = ts.word_frequency("Cat CAT cat")
		T.eq(freq["cat"], 3)
	end)
	T.it("empty string returns empty table", function()
		local freq = ts.word_frequency("")
		T.eq(next(freq), nil)
	end)
	T.it("ignores punctuation as word boundaries", function()
		local freq = ts.word_frequency("hello, world! hello.")
		T.eq(freq["hello"], 2)
		T.eq(freq["world"], 1)
	end)
end)

T.describe("top_words", function()
	T.it("returns top n words by frequency", function()
		local top = ts.top_words("the cat sat on the mat the cat", 2)
		T.eq(#top, 2)
		T.eq(top[1].word, "the")
		T.eq(top[1].count, 3)
		T.eq(top[2].word, "cat")
		T.eq(top[2].count, 2)
	end)
	T.it("n larger than unique words returns all", function()
		local top = ts.top_words("one two three", 10)
		T.eq(#top, 3)
	end)
	T.it("empty string returns empty list", function()
		local top = ts.top_words("", 5)
		T.eq(#top, 0)
	end)
	T.it("first element is most frequent", function()
		local top = ts.top_words("a a a b b c", 3)
		T.eq(top[1].count, 3)
		T.eq(top[2].count, 2)
		T.eq(top[3].count, 1)
	end)
end)

T.describe("unique_words", function()
	T.it("counts distinct words", function()
		T.eq(ts.unique_words("the cat sat on the mat"), 5)
	end)
	T.it("case-insensitive", function()
		T.eq(ts.unique_words("Cat cat CAT"), 1)
	end)
	T.it("empty string returns 0", function()
		T.eq(ts.unique_words(""), 0)
	end)
	T.it("all unique", function()
		T.eq(ts.unique_words("one two three four"), 4)
	end)
end)

-- ---------------------------------------------------------------------------
-- analyze (summary)
-- ---------------------------------------------------------------------------

T.describe("analyze", function()
	local result = ts.analyze(EASY_TEXT)

	T.it("returns char_count", function()
		T.ok(result.char_count > 0)
	end)
	T.it("returns letter_count", function()
		T.ok(result.letter_count > 0)
	end)
	T.it("returns word_count", function()
		T.ok(result.word_count > 0)
	end)
	T.it("returns sentence_count", function()
		T.ok(result.sentence_count > 0)
	end)
	T.it("returns paragraph_count", function()
		T.ok(result.paragraph_count >= 0)
	end)
	T.it("returns syllable_count", function()
		T.ok(result.syllable_count > 0)
	end)
	T.it("returns avg_words_per_sentence", function()
		T.ok(result.avg_words_per_sentence > 0)
	end)
	T.it("returns avg_syllables_per_word", function()
		T.ok(result.avg_syllables_per_word > 0)
	end)
	T.it("returns flesch_reading_ease", function()
		T.ok(type(result.flesch_reading_ease) == "number")
	end)
	T.it("returns flesch_kincaid_grade", function()
		T.ok(type(result.flesch_kincaid_grade) == "number")
	end)
	T.it("returns gunning_fog", function()
		T.ok(type(result.gunning_fog) == "number")
	end)
	T.it("returns smog_grade", function()
		T.ok(type(result.smog_grade) == "number")
	end)
	T.it("returns automated_readability_index", function()
		T.ok(type(result.automated_readability_index) == "number")
	end)
	T.it("returns coleman_liau_index", function()
		T.ok(type(result.coleman_liau_index) == "number")
	end)
	T.it("returns reading_level string", function()
		T.ok(type(result.reading_level) == "string")
		T.ok(result.reading_level ~= "")
	end)
	T.it("reading_level is a valid category", function()
		local valid = {
			["very easy"]=true, ["easy"]=true, ["fairly easy"]=true,
			["standard"]=true, ["fairly hard"]=true, ["hard"]=true,
			["very hard"]=true,
		}
		T.ok(valid[result.reading_level], "unknown level: " .. result.reading_level)
	end)
	T.it("empty string returns zero-valued table", function()
		local r = ts.analyze("")
		T.eq(r.char_count, 0)
		T.eq(r.word_count, 0)
		T.eq(r.syllable_count, 0)
		T.eq(r.flesch_reading_ease, 0)
	end)
end)

T.describe("_tier", function()
	T.it("is 'pure'", function()
		T.eq(ts._tier, "pure")
	end)
end)
