if not package.path:find("?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local F = require("lib.functional")

-- helper: deep equal for arrays
local function arr_eq(a, b)
  if #a ~= #b then return false end
  for i = 1, #a do
    if a[i] ~= b[i] then return false end
  end
  return true
end

local function arr2_eq(a, b)
  if #a ~= #b then return false end
  for i = 1, #a do
    if not arr_eq(a[i], b[i]) then return false end
  end
  return true
end

-- ---------------------------------------------------------------------------
T.describe("map", function()
  T.it("doubles each element", function()
    local r = F.map({1,2,3}, function(x) return x * 2 end)
    T.ok(arr_eq(r, {2,4,6}))
  end)
  T.it("passes index as second argument", function()
    local r = F.map({"a","b"}, function(v, i) return i end)
    T.ok(arr_eq(r, {1,2}))
  end)
  T.it("empty input", function()
    T.ok(arr_eq(F.map({}, function(x) return x end), {}))
  end)
end)

T.describe("filter", function()
  T.it("keeps evens", function()
    local r = F.filter({1,2,3,4,5}, function(x) return x % 2 == 0 end)
    T.ok(arr_eq(r, {2,4}))
  end)
  T.it("empty result", function()
    T.ok(arr_eq(F.filter({1,3,5}, function(x) return x % 2 == 0 end), {}))
  end)
end)

T.describe("reduce", function()
  T.it("sums", function()
    T.eq(F.reduce({1,2,3,4}, function(a,v) return a+v end, 0), 10)
  end)
  T.it("builds string left-to-right", function()
    T.eq(F.reduce({"a","b","c"}, function(a,v) return a..v end, ""), "abc")
  end)
end)

T.describe("reduce_right", function()
  T.it("builds string right-to-left", function()
    T.eq(F.reduce_right({"a","b","c"}, function(a,v) return a..v end, ""), "cba")
  end)
  T.it("right fold arithmetic", function()
    -- (1 - (2 - (3 - 0))) = 2
    T.eq(F.reduce_right({1,2,3}, function(a,v) return v - a end, 0), 2)
  end)
end)

T.describe("each", function()
  T.it("iterates with side effects", function()
    local s = 0
    F.each({10,20,30}, function(v) s = s + v end)
    T.eq(s, 60)
  end)
end)

T.describe("flat_map", function()
  T.it("maps then flattens one level", function()
    local r = F.flat_map({1,2,3}, function(x) return {x, x*10} end)
    T.ok(arr_eq(r, {1,10,2,20,3,30}))
  end)
  T.it("empty sub-arrays", function()
    local r = F.flat_map({1,2}, function(_) return {} end)
    T.ok(arr_eq(r, {}))
  end)
end)

T.describe("zip", function()
  T.it("zips two arrays", function()
    local r = F.zip({1,2,3}, {"a","b","c"})
    T.ok(arr2_eq(r, {{1,"a"},{2,"b"},{3,"c"}}))
  end)
  T.it("truncates to shortest", function()
    local r = F.zip({1,2,3}, {"x","y"})
    T.eq(#r, 2)
  end)
  T.it("three arrays", function()
    local r = F.zip({1,2}, {3,4}, {5,6})
    T.ok(arr2_eq(r, {{1,3,5},{2,4,6}}))
  end)
end)

T.describe("zip_with", function()
  T.it("adds pairs", function()
    local r = F.zip_with(function(a,b) return a+b end, {1,2,3}, {10,20,30})
    T.ok(arr_eq(r, {11,22,33}))
  end)
end)

T.describe("unzip", function()
  T.it("splits pairs", function()
    local cols = F.unzip({{1,"a"},{2,"b"},{3,"c"}})
    T.ok(arr_eq(cols[1], {1,2,3}))
    T.ok(arr_eq(cols[2], {"a","b","c"}))
  end)
  T.it("empty", function()
    T.ok(arr_eq(F.unzip({}), {}))
  end)
end)

T.describe("take", function()
  T.it("takes first n", function()
    T.ok(arr_eq(F.take({1,2,3,4,5}, 3), {1,2,3}))
  end)
  T.it("take more than length", function()
    T.ok(arr_eq(F.take({1,2}, 5), {1,2}))
  end)
  T.it("take 0", function()
    T.ok(arr_eq(F.take({1,2,3}, 0), {}))
  end)
end)

T.describe("drop", function()
  T.it("drops first n", function()
    T.ok(arr_eq(F.drop({1,2,3,4,5}, 2), {3,4,5}))
  end)
  T.it("drop all", function()
    T.ok(arr_eq(F.drop({1,2,3}, 3), {}))
  end)
  T.it("drop 0", function()
    T.ok(arr_eq(F.drop({1,2,3}, 0), {1,2,3}))
  end)
end)

T.describe("take_while", function()
  T.it("takes while lt 4", function()
    T.ok(arr_eq(F.take_while({1,2,3,4,5}, function(x) return x < 4 end), {1,2,3}))
  end)
  T.it("empty when first fails", function()
    T.ok(arr_eq(F.take_while({5,1,2}, function(x) return x < 4 end), {}))
  end)
end)

T.describe("drop_while", function()
  T.it("drops while lt 4", function()
    T.ok(arr_eq(F.drop_while({1,2,3,4,5}, function(x) return x < 4 end), {4,5}))
  end)
  T.it("nothing dropped when first fails", function()
    T.ok(arr_eq(F.drop_while({5,1,2}, function(x) return x < 4 end), {5,1,2}))
  end)
end)

T.describe("chunk", function()
  T.it("even chunks", function()
    T.ok(arr2_eq(F.chunk({1,2,3,4}, 2), {{1,2},{3,4}}))
  end)
  T.it("uneven last chunk", function()
    local r = F.chunk({1,2,3,4,5}, 2)
    T.eq(#r, 3)
    T.ok(arr_eq(r[3], {5}))
  end)
  T.it("empty input", function()
    T.ok(arr_eq(F.chunk({}, 3), {}))
  end)
end)

T.describe("window", function()
  T.it("sliding window of 3", function()
    local r = F.window({1,2,3,4,5}, 3)
    T.ok(arr2_eq(r, {{1,2,3},{2,3,4},{3,4,5}}))
  end)
  T.it("window size equals length", function()
    local r = F.window({1,2,3}, 3)
    T.eq(#r, 1)
    T.ok(arr_eq(r[1], {1,2,3}))
  end)
  T.it("window larger than array is empty", function()
    T.ok(arr_eq(F.window({1,2}, 5), {}))
  end)
end)

T.describe("flatten", function()
  T.it("deep flatten", function()
    T.ok(arr_eq(F.flatten({1,{2,{3,4}},5}), {1,2,3,4,5}))
  end)
  T.it("already flat", function()
    T.ok(arr_eq(F.flatten({1,2,3}), {1,2,3}))
  end)
end)

T.describe("flatten1", function()
  T.it("one level", function()
    T.ok(arr_eq(F.flatten1({{1,2},{3,4},{5}}), {1,2,3,4,5}))
  end)
  T.it("mixed flat and nested", function()
    T.ok(arr_eq(F.flatten1({1,{2,3},4}), {1,2,3,4}))
  end)
  T.it("does not recurse deep", function()
    local r = F.flatten1({{{1}},2})
    T.eq(type(r[1]), "table")  -- {{1}} flattened one level is {1} (still table)
    T.eq(r[2], 2)
  end)
end)

T.describe("unique", function()
  T.it("removes duplicates", function()
    T.ok(arr_eq(F.unique({1,2,2,3,1,4}), {1,2,3,4}))
  end)
  T.it("with key fn", function()
    local r = F.unique({"foo","bar","baz","fo"}, function(s) return #s end)
    T.eq(#r, 2)  -- "foo"(3) and "fo"(2)
  end)
end)

T.describe("group_by", function()
  T.it("groups by mod", function()
    local g = F.group_by({1,2,3,4,5,6}, function(x) return x % 3 end)
    T.ok(arr_eq(g[1], {1,4}))
    T.ok(arr_eq(g[2], {2,5}))
    T.ok(arr_eq(g[0], {3,6}))
  end)
  T.it("groups strings by first char", function()
    local g = F.group_by({"ant","bear","ape"}, function(s) return s:sub(1,1) end)
    T.eq(#g["a"], 2)
    T.eq(#g["b"], 1)
  end)
end)

T.describe("sort_by", function()
  T.it("sorts by length", function()
    local r = F.sort_by({"banana","apple","fig","kiwi"}, function(s) return #s end)
    T.eq(r[1], "fig")
    T.eq(r[2], "kiwi")
    T.eq(r[4], "banana")
  end)
  T.it("does not mutate input", function()
    local t = {3,1,2}
    F.sort_by(t, F.identity)
    T.eq(t[1], 3)
  end)
end)

T.describe("count_by", function()
  T.it("counts by parity", function()
    local c = F.count_by({1,2,3,4,5,6}, function(x) return x % 2 == 0 and "even" or "odd" end)
    T.eq(c["even"], 3)
    T.eq(c["odd"], 3)
  end)
end)

T.describe("partition", function()
  T.it("splits evens and odds", function()
    local yes, no = F.partition({1,2,3,4,5}, function(x) return x % 2 == 0 end)
    T.ok(arr_eq(yes, {2,4}))
    T.ok(arr_eq(no, {1,3,5}))
  end)
end)

T.describe("find", function()
  T.it("finds first match", function()
    T.eq(F.find({1,2,3,4}, function(x) return x > 2 end), 3)
  end)
  T.it("returns nil when not found", function()
    T.eq(F.find({1,2,3}, function(x) return x > 10 end), nil)
  end)
end)

T.describe("find_index", function()
  T.it("finds index of first match", function()
    T.eq(F.find_index({10,20,30,40}, function(x) return x > 15 end), 2)
  end)
  T.it("returns nil when not found", function()
    T.eq(F.find_index({1,2,3}, function(x) return x > 10 end), nil)
  end)
end)

T.describe("any", function()
  T.it("true when match exists", function()
    T.ok(F.any({1,2,3}, function(x) return x == 2 end))
  end)
  T.it("false when no match", function()
    T.ok(not F.any({1,2,3}, function(x) return x > 10 end))
  end)
end)

T.describe("all", function()
  T.it("true when all match", function()
    T.ok(F.all({2,4,6}, function(x) return x % 2 == 0 end))
  end)
  T.it("false when one fails", function()
    T.ok(not F.all({2,3,6}, function(x) return x % 2 == 0 end))
  end)
end)

T.describe("none", function()
  T.it("true when no match", function()
    T.ok(F.none({1,3,5}, function(x) return x % 2 == 0 end))
  end)
  T.it("false when match exists", function()
    T.ok(not F.none({1,2,3}, function(x) return x == 2 end))
  end)
end)

T.describe("sum", function()
  T.it("sums numbers", function()
    T.eq(F.sum({1,2,3,4,5}), 15)
  end)
  T.it("empty is 0", function()
    T.eq(F.sum({}), 0)
  end)
end)

T.describe("product", function()
  T.it("product of numbers", function()
    T.eq(F.product({1,2,3,4}), 24)
  end)
  T.it("empty is 1", function()
    T.eq(F.product({}), 1)
  end)
end)

T.describe("min", function()
  T.it("minimum value", function()
    T.eq(F.min({3,1,4,1,5,9}), 1)
  end)
  T.it("min by key fn", function()
    T.eq(F.min({"banana","fig","apple"}, function(s) return #s end), "fig")
  end)
  T.it("empty returns nil", function()
    T.eq(F.min({}), nil)
  end)
end)

T.describe("max", function()
  T.it("maximum value", function()
    T.eq(F.max({3,1,4,1,5,9}), 9)
  end)
  T.it("max by key fn", function()
    T.eq(F.max({"banana","fig","apple"}, function(s) return #s end), "banana")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("identity", function()
  T.it("returns its argument", function()
    T.eq(F.identity(42), 42)
    T.eq(F.identity("hello"), "hello")
  end)
end)

T.describe("constant", function()
  T.it("always returns the bound value", function()
    local always5 = F.constant(5)
    T.eq(always5(), 5)
    T.eq(always5(99), 5)
  end)
end)

T.describe("compose", function()
  T.it("applies right-to-left", function()
    local f = F.compose(function(x) return x + 1 end, function(x) return x * 2 end)
    T.eq(f(3), 7)  -- (3*2)+1
  end)
  T.it("single fn is identity", function()
    local double = function(x) return x * 2 end
    T.eq(F.compose(double)(5), 10)
  end)
  T.it("three functions", function()
    local f = F.compose(
      function(x) return x .. "!" end,
      function(x) return x:upper() end,
      function(x) return x .. "x" end
    )
    T.eq(f("a"), "AX!")
  end)
end)

T.describe("pipe", function()
  T.it("applies left-to-right", function()
    local f = F.pipe(function(x) return x * 2 end, function(x) return x + 1 end)
    T.eq(f(3), 7)  -- (3*2)+1
  end)
  T.it("three functions", function()
    local f = F.pipe(
      function(x) return x .. "x" end,
      function(x) return x:upper() end,
      function(x) return x .. "!" end
    )
    T.eq(f("a"), "AX!")
  end)
end)

T.describe("memoize", function()
  T.it("returns same result for same input", function()
    local calls = 0
    local fn = F.memoize(function(x)
      calls = calls + 1
      return x * x
    end)
    T.eq(fn(4), 16)
    T.eq(fn(4), 16)
    T.eq(calls, 1)
  end)
  T.it("different inputs call fn each time", function()
    local calls = 0
    local fn = F.memoize(function(x)
      calls = calls + 1
      return x + 1
    end)
    fn(1); fn(2); fn(3)
    T.eq(calls, 3)
  end)
end)

T.describe("once", function()
  T.it("calls fn exactly once", function()
    local calls = 0
    local fn = F.once(function()
      calls = calls + 1
      return 42
    end)
    T.eq(fn(), 42)
    T.eq(fn(), 42)
    T.eq(fn(), 42)
    T.eq(calls, 1)
  end)
end)

T.describe("partial", function()
  T.it("binds first argument", function()
    local add = function(a, b) return a + b end
    local add10 = F.partial(add, 10)
    T.eq(add10(5), 15)
    T.eq(add10(20), 30)
  end)
  T.it("binds multiple arguments", function()
    local f = function(a,b,c) return a..b..c end
    T.eq(F.partial(f, "x", "y")("z"), "xyz")
  end)
end)

T.describe("curry", function()
  T.it("curries 2-arg function", function()
    local add = F.curry(function(a, b) return a + b end, 2)
    T.eq(add(3)(4), 7)
  end)
  T.it("curries 3-arg function", function()
    local f = F.curry(function(a,b,c) return a+b+c end, 3)
    T.eq(f(1)(2)(3), 6)
  end)
  T.it("accepts multiple args at once", function()
    local f = F.curry(function(a,b,c) return a*b+c end, 3)
    T.eq(f(2,3)(4), 10)
  end)
end)

T.describe("flip", function()
  T.it("swaps first two args", function()
    local sub = function(a,b) return a - b end
    T.eq(F.flip(sub)(3,10), 7)  -- 10-3
  end)
end)

T.describe("negate", function()
  T.it("negates predicate", function()
    local is_even = function(x) return x % 2 == 0 end
    local is_odd = F.negate(is_even)
    T.ok(is_odd(3))
    T.ok(not is_odd(4))
  end)
end)

T.describe("juxt", function()
  T.it("applies multiple functions to same arg", function()
    local r = F.juxt(
      function(x) return x + 1 end,
      function(x) return x * 2 end,
      function(x) return x * x end
    )(5)
    T.ok(arr_eq(r, {6, 10, 25}))
  end)
end)

T.describe("apply", function()
  T.it("applies fn to args array", function()
    T.eq(F.apply(function(a,b,c) return a+b+c end, {1,2,3}), 6)
  end)
end)

T.describe("tap", function()
  T.it("returns original value unchanged", function()
    local side = {}
    local tapped = F.tap(function(x) side[#side+1] = x end)
    T.eq(tapped(42), 42)
    T.eq(side[1], 42)
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("transducers", function()
  local append = function(acc, v) acc[#acc+1] = v; return acc end

  T.it("map_xf transforms values", function()
    local r = F.transduce(F.map_xf(function(x) return x * 2 end), append, {}, {1,2,3})
    T.ok(arr_eq(r, {2,4,6}))
  end)

  T.it("filter_xf keeps matching values", function()
    local r = F.transduce(F.filter_xf(function(x) return x % 2 == 0 end), append, {}, {1,2,3,4,5})
    T.ok(arr_eq(r, {2,4}))
  end)

  T.it("take_xf takes first n", function()
    local r = F.transduce(F.take_xf(3), append, {}, {10,20,30,40,50})
    T.ok(arr_eq(r, {10,20,30}))
  end)

  T.it("comp_xf composes map then filter", function()
    local xf = F.comp_xf(
      F.map_xf(function(x) return x * 3 end),
      F.filter_xf(function(x) return x > 6 end)
    )
    local r = F.transduce(xf, append, {}, {1,2,3,4,5})
    T.ok(arr_eq(r, {9,12,15}))
  end)

  T.it("comp_xf with take", function()
    local xf = F.comp_xf(
      F.filter_xf(function(x) return x % 2 == 0 end),
      F.take_xf(2)
    )
    local r = F.transduce(xf, append, {}, {1,2,3,4,5,6,7,8})
    T.ok(arr_eq(r, {2,4}))
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("range", function()
  T.it("range(n) produces 1..n", function()
    T.ok(arr_eq(F.range(5), {1,2,3,4,5}))
  end)
  T.it("range(start,stop)", function()
    T.ok(arr_eq(F.range(3,7), {3,4,5,6,7}))
  end)
  T.it("range(start,stop,step)", function()
    T.ok(arr_eq(F.range(0,10,3), {0,3,6,9}))
  end)
  T.it("range with step=2", function()
    T.ok(arr_eq(F.range(1,9,2), {1,3,5,7,9}))
  end)
  T.it("range(1,1)", function()
    T.ok(arr_eq(F.range(1,1), {1}))
  end)
end)

T.describe("repeat_val", function()
  T.it("repeats value n times", function()
    T.ok(arr_eq(F.repeat_val(7, 4), {7,7,7,7}))
  end)
  T.it("zero times is empty", function()
    T.ok(arr_eq(F.repeat_val("x", 0), {}))
  end)
end)

T.describe("iterate", function()
  T.it("builds sequence from seed and fn", function()
    local r = F.iterate(function(x) return x * 2 end, 1, 4)
    T.ok(arr_eq(r, {1,2,4,8,16}))
  end)
  T.it("n=0 returns just seed", function()
    T.ok(arr_eq(F.iterate(function(x) return x+1 end, 5, 0), {5}))
  end)
end)

T.describe("cycle", function()
  T.it("cycles array to n items", function()
    T.ok(arr_eq(F.cycle({1,2,3}, 7), {1,2,3,1,2,3,1}))
  end)
  T.it("empty cycle is empty", function()
    T.ok(arr_eq(F.cycle({}, 5), {}))
  end)
  T.it("cycle exactly one period", function()
    T.ok(arr_eq(F.cycle({"a","b"}, 2), {"a","b"}))
  end)
end)

T.describe("_tier", function()
  T.it("is pure", function()
    T.eq(F._tier, "pure")
  end)
end)
