if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local automata = require("lib.automata")

-- ── NFA construction ────────────────────────────────────────────────────────

T.describe("NFA construction", function()
  T.it("add_state returns sequential ids", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    T.eq(s0, 1)
    T.eq(s1, 2)
    T.eq(s2, 3)
    T.eq(nfa.states[s2].accept, true)
    T.eq(nfa.states[s0].accept, false)
  end)

  T.it("set_start sets start state", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    nfa:set_start(s0)
    T.eq(nfa.start, s0)
  end)

  T.it("add_transition stores transitions", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    nfa:add_transition(s0, "a", s1)
    T.ok(nfa.trans[s0] ~= nil)
    T.ok(nfa.trans[s0]["a"] ~= nil)
    T.ok(nfa.trans[s0]["a"][s1])
  end)

  T.it("add_transition stores epsilon (nil key = false)", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    nfa:add_transition(s0, nil, s1)
    T.ok(nfa.trans[s0][false] ~= nil)
    T.ok(nfa.trans[s0][false][s1])
  end)
end)

-- ── NFA epsilon closure ─────────────────────────────────────────────────────

T.describe("NFA epsilon_closure", function()
  T.it("trivial: no eps transitions", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    nfa:add_transition(s0, "a", s1)
    local cl = nfa:epsilon_closure({ [s0] = true })
    T.ok(cl[s0])
    T.eq(cl[s1], nil)
  end)

  T.it("follows epsilon transitions", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state()
    nfa:add_transition(s0, nil, s1)
    nfa:add_transition(s1, nil, s2)
    local cl = nfa:epsilon_closure({ [s0] = true })
    T.ok(cl[s0])
    T.ok(cl[s1])
    T.ok(cl[s2])
  end)

  T.it("does not follow non-epsilon transitions", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    nfa:add_transition(s0, "a", s1)
    local cl = nfa:epsilon_closure({ [s0] = true })
    T.ok(cl[s0])
    T.eq(cl[s1], nil)
  end)
end)

-- ── NFA simulation ──────────────────────────────────────────────────────────

T.describe("NFA accepts", function()
  T.it("accepts simple literal sequence", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    nfa:add_transition(s0, "a", s1)
    nfa:add_transition(s1, "b", s2)
    T.ok(nfa:accepts("ab"))
    T.fail(nfa:accepts("a"))
    T.fail(nfa:accepts("b"))
    T.fail(nfa:accepts("abc"))
    T.fail(nfa:accepts(""))
  end)

  T.it("accepts via epsilon transition", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    nfa:add_transition(s0, nil, s1)   -- epsilon from s0 to s1
    nfa:add_transition(s1, "b", s2)
    T.ok(nfa:accepts("b"))
    T.fail(nfa:accepts("ab"))
    T.fail(nfa:accepts(""))
  end)

  T.it("rejects when no start state", function()
    local nfa = automata.nfa_new()
    T.fail(nfa:accepts("anything"))
  end)

  T.it("accepts empty string if start is accepting", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    T.ok(nfa:accepts(""))
  end)

  T.it("NFA with branching paths", function()
    -- Language: {ab, ac}
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    local s3 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    nfa:add_transition(s0, "a", s1)
    nfa:add_transition(s1, "b", s2)
    nfa:add_transition(s1, "c", s3)
    T.ok(nfa:accepts("ab"))
    T.ok(nfa:accepts("ac"))
    T.fail(nfa:accepts("a"))
    T.fail(nfa:accepts("ad"))
  end)
end)

-- ── DFA construction ────────────────────────────────────────────────────────

T.describe("DFA construction", function()
  T.it("add_state with start=true sets start", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    T.eq(dfa.start, q0)
  end)

  T.it("add_state returns sequential ids", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state()
    local q1 = dfa:add_state()
    T.eq(q0, 1)
    T.eq(q1, 2)
  end)

  T.it("add_transition stores deterministic transition", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state()
    local q1 = dfa:add_state()
    dfa:add_transition(q0, "a", q1)
    T.eq(dfa.trans[q0]["a"], q1)
  end)
end)

-- ── DFA simulation ──────────────────────────────────────────────────────────

T.describe("DFA accepts", function()
  T.it("accepts simple sequence", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    local q2 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q1, "b", q2)
    T.ok(dfa:accepts("ab"))
    T.fail(dfa:accepts("b"))
    T.fail(dfa:accepts("a"))
    T.fail(dfa:accepts("abb"))
    T.fail(dfa:accepts(""))
  end)

  T.it("rejects when no start", function()
    local dfa = automata.dfa_new()
    T.fail(dfa:accepts("ab"))
  end)

  T.it("accepts empty string if start is accepting", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true, accept = true })
    T.ok(dfa:accepts(""))
  end)
end)

-- ── DFA run (step by step) ──────────────────────────────────────────────────

T.describe("DFA run", function()
  T.it("single step returns correct next state", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    local q2 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q1, "b", q2)
    T.eq(dfa:run(q0, "a"), q1)
    T.eq(dfa:run(q1, "b"), q2)
  end)

  T.it("returns nil on missing transition", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    T.eq(dfa:run(q0, "x"), nil)
  end)

  T.it("multi-char run traverses states", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    local q2 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q1, "b", q2)
    T.eq(dfa:run(q0, "ab"), q2)
  end)

  T.it("multi-char run returns nil if path breaks", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    dfa:add_transition(q0, "a", q1)
    T.eq(dfa:run(q0, "ax"), nil)
  end)
end)

-- ── NFA → DFA conversion ────────────────────────────────────────────────────

T.describe("nfa_to_dfa", function()
  T.it("same language: simple literal", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    nfa:add_transition(s0, "a", s1)
    nfa:add_transition(s1, "b", s2)
    local dfa = automata.nfa_to_dfa(nfa)
    T.ok(dfa:accepts("ab"))
    T.fail(dfa:accepts("a"))
    T.fail(dfa:accepts("b"))
    T.fail(dfa:accepts("abc"))
  end)

  T.it("same language: epsilon transitions", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    nfa:add_transition(s0, nil, s1)
    nfa:add_transition(s1, "b", s2)
    local dfa = automata.nfa_to_dfa(nfa)
    T.ok(dfa:accepts("b"))
    T.fail(dfa:accepts("ab"))
    T.fail(dfa:accepts(""))
  end)

  T.it("empty NFA gives DFA with no start", function()
    local nfa = automata.nfa_new()
    local dfa = automata.nfa_to_dfa(nfa)
    T.fail(dfa:accepts(""))
    T.fail(dfa:accepts("a"))
  end)

  T.it("NFA with branching paths", function()
    -- {ab, ac}
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    local s2 = nfa:add_state({ accept = true })
    local s3 = nfa:add_state({ accept = true })
    nfa:set_start(s0)
    nfa:add_transition(s0, "a", s1)
    nfa:add_transition(s1, "b", s2)
    nfa:add_transition(s1, "c", s3)
    local dfa = automata.nfa_to_dfa(nfa)
    T.ok(dfa:accepts("ab"))
    T.ok(dfa:accepts("ac"))
    T.fail(dfa:accepts("a"))
    T.fail(dfa:accepts("ad"))
  end)
end)

-- ── DFA minimization ────────────────────────────────────────────────────────

T.describe("minimize", function()
  T.it("minimized DFA accepts same language", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    local q2 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q1, "b", q2)
    local min = automata.minimize(dfa)
    T.ok(min:accepts("ab"))
    T.fail(min:accepts("a"))
    T.fail(min:accepts("b"))
    T.fail(min:accepts(""))
  end)

  T.it("minimizes redundant states", function()
    -- DFA with two equivalent accepting states
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state({ accept = true })
    local q2 = dfa:add_state({ accept = true }) -- equivalent to q1
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q0, "b", q2)
    -- Both q1 and q2 are accepting and have no outgoing transitions
    -- They should merge to 1 accepting state
    local min = automata.minimize(dfa)
    T.ok(min:accepts("a"))
    T.ok(min:accepts("b"))
    T.fail(min:accepts(""))
    T.fail(min:accepts("ab"))
  end)

  T.it("empty DFA minimizes ok", function()
    local dfa = automata.dfa_new()
    local min = automata.minimize(dfa)
    T.fail(min:accepts(""))
    T.fail(min:accepts("a"))
  end)
end)

-- ── DFA complement ──────────────────────────────────────────────────────────

T.describe("complement", function()
  T.it("accepts exactly strings the original rejects", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    local q2 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q1, "b", q2)
    local comp = automata.complement(dfa)
    T.fail(comp:accepts("ab"))  -- original accepted
    T.ok(comp:accepts("b"))     -- original rejected
    T.ok(comp:accepts("a"))     -- original rejected
    T.ok(comp:accepts(""))      -- original rejected
  end)

  T.it("double complement = original", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state()
    local q2 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    dfa:add_transition(q1, "b", q2)
    local comp2 = automata.complement(automata.complement(dfa))
    T.ok(comp2:accepts("ab"))
    T.fail(comp2:accepts("b"))
    T.fail(comp2:accepts("a"))
  end)
end)

-- ── DFA intersection / union ────────────────────────────────────────────────

T.describe("intersection", function()
  T.it("intersection: only strings in both languages", function()
    -- dfa1: accepts "ab"
    local dfa1 = automata.dfa_new()
    local a0 = dfa1:add_state({ start = true })
    local a1 = dfa1:add_state()
    local a2 = dfa1:add_state({ accept = true })
    dfa1:add_transition(a0, "a", a1)
    dfa1:add_transition(a1, "b", a2)

    -- dfa2: accepts "ab" or "ac"
    local dfa2 = automata.dfa_new()
    local b0 = dfa2:add_state({ start = true })
    local b1 = dfa2:add_state()
    local b2 = dfa2:add_state({ accept = true })
    local b3 = dfa2:add_state({ accept = true })
    dfa2:add_transition(b0, "a", b1)
    dfa2:add_transition(b1, "b", b2)
    dfa2:add_transition(b1, "c", b3)

    local inter = automata.intersection(dfa1, dfa2)
    T.ok(inter:accepts("ab"))   -- in both
    T.fail(inter:accepts("ac")) -- only in dfa2
    T.fail(inter:accepts("a"))
  end)
end)

T.describe("union", function()
  T.it("union: strings in either language", function()
    -- dfa1: accepts "a"
    local dfa1 = automata.dfa_new()
    local a0 = dfa1:add_state({ start = true })
    local a1 = dfa1:add_state({ accept = true })
    dfa1:add_transition(a0, "a", a1)

    -- dfa2: accepts "b"
    local dfa2 = automata.dfa_new()
    local b0 = dfa2:add_state({ start = true })
    local b1 = dfa2:add_state({ accept = true })
    dfa2:add_transition(b0, "b", b1)

    local uni = automata.union(dfa1, dfa2)
    T.ok(uni:accepts("a"))
    T.ok(uni:accepts("b"))
    T.fail(uni:accepts("ab"))
    T.fail(uni:accepts(""))
  end)

  T.it("union with self = self", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    local uni = automata.union(dfa, dfa)
    T.ok(uni:accepts("a"))
    T.fail(uni:accepts("b"))
    T.fail(uni:accepts(""))
  end)
end)

-- ── DOT serialization ───────────────────────────────────────────────────────

T.describe("to_dot", function()
  T.it("contains digraph keyword", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    local dot = dfa:to_dot()
    T.ok(dot:find("digraph") ~= nil)
  end)

  T.it("contains doublecircle for accepting state", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    local dot = dfa:to_dot()
    T.ok(dot:find("doublecircle") ~= nil)
  end)

  T.it("contains transition label", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    local q1 = dfa:add_state({ accept = true })
    dfa:add_transition(q0, "a", q1)
    local dot = dfa:to_dot()
    T.ok(dot:find('"a"') ~= nil)
  end)
end)

-- ── Thompson's construction (from_regex) ────────────────────────────────────

T.describe("from_regex: literals", function()
  T.it("single literal", function()
    local nfa = automata.from_regex("a")
    T.ok(nfa:accepts("a"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("b"))
    T.fail(nfa:accepts("aa"))
  end)

  T.it("literal sequence (implicit concat)", function()
    local nfa = automata.from_regex("ab")
    T.ok(nfa:accepts("ab"))
    T.fail(nfa:accepts("a"))
    T.fail(nfa:accepts("b"))
    T.fail(nfa:accepts("ba"))
  end)

  T.it("three-char sequence", function()
    local nfa = automata.from_regex("abc")
    T.ok(nfa:accepts("abc"))
    T.fail(nfa:accepts("ab"))
    T.fail(nfa:accepts("abcd"))
  end)
end)

T.describe("from_regex: alternation", function()
  T.it("simple alternation a|b", function()
    local nfa = automata.from_regex("a|b")
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("b"))
    T.fail(nfa:accepts("ab"))
    T.fail(nfa:accepts(""))
  end)

  T.it("alternation with sequences ab|cd", function()
    local nfa = automata.from_regex("ab|cd")
    T.ok(nfa:accepts("ab"))
    T.ok(nfa:accepts("cd"))
    T.fail(nfa:accepts("ac"))
    T.fail(nfa:accepts("ad"))
  end)
end)

T.describe("from_regex: Kleene star", function()
  T.it("a* accepts zero or more a's", function()
    local nfa = automata.from_regex("a*")
    T.ok(nfa:accepts(""))
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("aaa"))
    T.fail(nfa:accepts("b"))
    T.fail(nfa:accepts("ab"))
  end)

  T.it("ab* accepts a followed by zero or more b's", function()
    local nfa = automata.from_regex("ab*")
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("ab"))
    T.ok(nfa:accepts("abbb"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("b"))
  end)
end)

T.describe("from_regex: plus", function()
  T.it("a+ accepts one or more a's", function()
    local nfa = automata.from_regex("a+")
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("aaa"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("b"))
  end)
end)

T.describe("from_regex: optional", function()
  T.it("a? accepts empty or single a", function()
    local nfa = automata.from_regex("a?")
    T.ok(nfa:accepts(""))
    T.ok(nfa:accepts("a"))
    T.fail(nfa:accepts("aa"))
    T.fail(nfa:accepts("b"))
  end)

  T.it("ab? accepts a or ab", function()
    local nfa = automata.from_regex("ab?")
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("ab"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("abb"))
  end)
end)

T.describe("from_regex: grouping", function()
  T.it("(ab)* accepts zero or more 'ab' repetitions", function()
    local nfa = automata.from_regex("(ab)*")
    T.ok(nfa:accepts(""))
    T.ok(nfa:accepts("ab"))
    T.ok(nfa:accepts("abab"))
    T.fail(nfa:accepts("a"))
    T.fail(nfa:accepts("aba"))
  end)

  T.it("a(b|c)*d from spec", function()
    local nfa = automata.from_regex("a(b|c)*d")
    T.ok(nfa:accepts("ad"))
    T.ok(nfa:accepts("abd"))
    T.ok(nfa:accepts("acd"))
    T.ok(nfa:accepts("abcd"))
    T.ok(nfa:accepts("abbbccd"))
    T.fail(nfa:accepts("ae"))
    T.fail(nfa:accepts("a"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("abcde"))
  end)

  T.it("(a|b)+ accepts one or more a/b chars", function()
    local nfa = automata.from_regex("(a|b)+")
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("b"))
    T.ok(nfa:accepts("ab"))
    T.ok(nfa:accepts("ba"))
    T.ok(nfa:accepts("aabb"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("c"))
  end)
end)

T.describe("from_regex: dot (any char)", function()
  T.it(". matches any single character", function()
    local nfa = automata.from_regex(".")
    T.ok(nfa:accepts("a"))
    T.ok(nfa:accepts("b"))
    T.ok(nfa:accepts("z"))
    T.ok(nfa:accepts("1"))
    T.fail(nfa:accepts(""))
    T.fail(nfa:accepts("ab"))
  end)

  T.it(".* matches any string", function()
    local nfa = automata.from_regex(".*")
    T.ok(nfa:accepts(""))
    T.ok(nfa:accepts("abc"))
    T.ok(nfa:accepts("xyz123"))
  end)

  T.it("a.b matches a<any>b", function()
    local nfa = automata.from_regex("a.b")
    T.ok(nfa:accepts("axb"))
    T.ok(nfa:accepts("a1b"))
    T.fail(nfa:accepts("ab"))
    T.fail(nfa:accepts("axxb"))
  end)
end)

T.describe("from_regex: error handling", function()
  T.it("unmatched ) returns nil, errmsg", function()
    local nfa, err = automata.from_regex("a)")
    T.eq(nfa, nil)
    T.ok(err ~= nil)
  end)

  T.it("unmatched ( returns nil, errmsg", function()
    local nfa, err = automata.from_regex("(a")
    T.eq(nfa, nil)
    T.ok(err ~= nil)
  end)
end)

T.describe("from_regex: edge cases", function()
  T.it("empty language: DFA with no accepting states rejects all", function()
    local dfa = automata.dfa_new()
    local q0 = dfa:add_state({ start = true })
    -- no accepting states
    T.fail(dfa:accepts(""))
    T.fail(dfa:accepts("a"))
  end)

  T.it("NFA with no accepting states", function()
    local nfa = automata.nfa_new()
    local s0 = nfa:add_state()
    local s1 = nfa:add_state()
    nfa:set_start(s0)
    nfa:add_transition(s0, "a", s1)
    T.fail(nfa:accepts("a"))
    T.fail(nfa:accepts(""))
  end)

  T.it("single char regex via nfa_to_dfa", function()
    local nfa = automata.from_regex("x")
    local dfa = automata.nfa_to_dfa(nfa)
    T.ok(dfa:accepts("x"))
    T.fail(dfa:accepts(""))
    T.fail(dfa:accepts("y"))
  end)

  T.it("complex regex via nfa_to_dfa + minimize", function()
    local nfa = automata.from_regex("(a|b)*abb")
    local dfa = automata.nfa_to_dfa(nfa)
    local min = automata.minimize(dfa)
    T.ok(min:accepts("abb"))
    T.ok(min:accepts("aabb"))
    T.ok(min:accepts("babb"))
    T.ok(min:accepts("ababb"))
    T.fail(min:accepts("ab"))
    T.fail(min:accepts(""))
    T.fail(min:accepts("ab"))
  end)
end)

-- Print summary
local summary = T._summary()
local total = summary.pass + summary.fail
io.write(string.format("\n%d/%d assertions passed", summary.pass, total))
if summary.fail > 0 then
  io.write(string.format(", %d FAILED\n", summary.fail))
  for _, test in ipairs(summary.tests) do
    if not test.ok then
      io.write(string.format("  FAIL: %s\n", test.name))
      if test.err then io.write(string.format("        %s\n", test.err)) end
    end
  end
  os.exit(1)
else
  io.write("\n")
end
