if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T       = require("lib.test.assert")
local account = require("lib.bookkeeping.account")

T.describe("lib.bookkeeping.account", function()

  T.describe("is_account_type / is_debit_normal / normal_side", function()
    T.it("recognizes the 5 standard types", function()
      T.ok(account.is_account_type("asset"))
      T.ok(account.is_account_type("liability"))
      T.ok(account.is_account_type("equity"))
      T.ok(account.is_account_type("revenue"))
      T.ok(account.is_account_type("expense"))
    end)

    T.it("rejects unknown types", function()
      T.ok(not account.is_account_type("bogus"))
      T.ok(not account.is_account_type(""))
    end)

    T.it("asset and expense are debit-normal", function()
      T.eq(account.is_debit_normal("asset"), true)
      T.eq(account.is_debit_normal("expense"), true)
    end)

    T.it("liability, equity, revenue are credit-normal", function()
      T.eq(account.is_debit_normal("liability"), false)
      T.eq(account.is_debit_normal("equity"), false)
      T.eq(account.is_debit_normal("revenue"), false)
    end)

    T.it("is_debit_normal returns nil, err for unknown type", function()
      local v, err = account.is_debit_normal("bogus")
      T.eq(v, nil)
      T.ok(type(err) == "string")
    end)

    T.it("normal_side maps to 'debit'/'credit'", function()
      T.eq(account.normal_side("asset"), "debit")
      T.eq(account.normal_side("liability"), "credit")
    end)
  end)

  T.describe("new / add_account / get / list", function()
    T.it("starts empty", function()
      local chart = account.new()
      T.eq(#account.list(chart), 0)
    end)

    T.it("adds an account and retrieves it", function()
      local chart = account.new()
      local acct, err = account.add_account(chart, { id = "cash", name = "Cash", type = "asset" })
      T.ok(acct ~= nil, err)
      T.eq(account.get(chart, "cash").name, "Cash")
      T.eq(account.get(chart, "cash").type, "asset")
    end)

    T.it("accepts optional code and description", function()
      local chart = account.new()
      account.add_account(chart, {
        id = "cash", name = "Cash", type = "asset",
        code = "1000", description = "Cash on hand",
      })
      local acct = account.get(chart, "cash")
      T.eq(acct.code, "1000")
      T.eq(acct.description, "Cash on hand")
    end)

    T.it("code and description default to nil", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset" })
      local acct = account.get(chart, "cash")
      T.eq(acct.code, nil)
      T.eq(acct.description, nil)
    end)

    T.it("get returns nil for unknown id", function()
      local chart = account.new()
      T.eq(account.get(chart, "nope"), nil)
    end)

    T.it("rejects duplicate id", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset" })
      local acct, err = account.add_account(chart, { id = "cash", name = "Cash 2", type = "asset" })
      T.eq(acct, nil)
      T.ok(type(err) == "string")
    end)

    T.it("rejects unknown account type", function()
      local chart = account.new()
      local acct, err = account.add_account(chart, { id = "x", name = "X", type = "bogus" })
      T.eq(acct, nil)
      T.ok(type(err) == "string")
    end)

    T.it("rejects empty id/name", function()
      local chart = account.new()
      local a1, e1 = account.add_account(chart, { id = "", name = "X", type = "asset" })
      T.eq(a1, nil); T.ok(type(e1) == "string")
      local a2, e2 = account.add_account(chart, { id = "x", name = "", type = "asset" })
      T.eq(a2, nil); T.ok(type(e2) == "string")
    end)

    T.it("list preserves insertion order", function()
      local chart = account.new()
      account.add_account(chart, { id = "b", name = "B", type = "asset" })
      account.add_account(chart, { id = "a", name = "A", type = "asset" })
      local list = account.list(chart)
      T.eq(#list, 2)
      T.eq(list[1].id, "b")
      T.eq(list[2].id, "a")
    end)
  end)

  T.describe("hierarchy (parent/children)", function()
    T.it("accepts a parent that already exists", function()
      local chart = account.new()
      account.add_account(chart, { id = "assets", name = "Assets", type = "asset" })
      local acct, err = account.add_account(chart, { id = "cash", name = "Cash", type = "asset", parent = "assets" })
      T.ok(acct ~= nil, err)
      T.eq(acct.parent, "assets")
    end)

    T.it("rejects a parent that does not exist yet", function()
      local chart = account.new()
      local acct, err = account.add_account(chart, { id = "cash", name = "Cash", type = "asset", parent = "assets" })
      T.eq(acct, nil)
      T.ok(type(err) == "string")
    end)

    T.it("children returns direct children in insertion order", function()
      local chart = account.new()
      account.add_account(chart, { id = "assets", name = "Assets", type = "asset" })
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset", parent = "assets" })
      account.add_account(chart, { id = "bank", name = "Bank", type = "asset", parent = "assets" })
      account.add_account(chart, { id = "cash-sub", name = "Cash sub", type = "asset", parent = "cash" })

      local children = account.children(chart, "assets")
      T.eq(#children, 2)
      T.eq(children[1].id, "cash")
      T.eq(children[2].id, "bank")

      T.eq(#account.children(chart, "cash"), 1)
      T.eq(#account.children(chart, "bank"), 0)
    end)
  end)

  T.describe("update_account", function()
    T.it("updates name, code, description, and type", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset", code = "1000" })
      local acct, err = account.update_account(chart, "cash", {
        name = "Petty Cash", code = "1001", description = "Till float", type = "expense",
      })
      T.ok(acct ~= nil, err)
      T.eq(account.get(chart, "cash").name, "Petty Cash")
      T.eq(account.get(chart, "cash").code, "1001")
      T.eq(account.get(chart, "cash").description, "Till float")
      T.eq(account.get(chart, "cash").type, "expense")
    end)

    T.it("leaves omitted fields unchanged", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset", code = "1000" })
      account.update_account(chart, "cash", { name = "Cash on Hand" })
      T.eq(account.get(chart, "cash").code, "1000")
      T.eq(account.get(chart, "cash").type, "asset")
    end)

    T.it("clears code/description via account.CLEAR", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset", code = "1000", description = "d" })
      account.update_account(chart, "cash", { code = account.CLEAR, description = account.CLEAR })
      T.eq(account.get(chart, "cash").code, nil)
      T.eq(account.get(chart, "cash").description, nil)
    end)

    T.it("rejects changing parent", function()
      local chart = account.new()
      account.add_account(chart, { id = "assets", name = "Assets", type = "asset" })
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset" })
      local acct, err = account.update_account(chart, "cash", { parent = "assets" })
      T.eq(acct, nil)
      T.ok(type(err) == "string")
      T.eq(account.get(chart, "cash").parent, nil)
    end)

    T.it("rejects an unknown account id", function()
      local chart = account.new()
      local acct, err = account.update_account(chart, "nope", { name = "X" })
      T.eq(acct, nil)
      T.ok(type(err) == "string")
    end)

    T.it("rejects an unknown account type", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset" })
      local acct, err = account.update_account(chart, "cash", { type = "bogus" })
      T.eq(acct, nil)
      T.ok(type(err) == "string")
      T.eq(account.get(chart, "cash").type, "asset")
    end)
  end)

  T.describe("delete_account", function()
    T.it("deletes a leaf account", function()
      local chart = account.new()
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset" })
      local ok, err = account.delete_account(chart, "cash")
      T.ok(ok, err)
      T.eq(account.get(chart, "cash"), nil)
      T.eq(#account.list(chart), 0)
    end)

    T.it("fails when the account has children", function()
      local chart = account.new()
      account.add_account(chart, { id = "assets", name = "Assets", type = "asset" })
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset", parent = "assets" })
      local ok, err = account.delete_account(chart, "assets")
      T.eq(ok, nil)
      T.ok(type(err) == "string")
      T.ok(account.get(chart, "assets") ~= nil)
    end)

    T.it("fails for an unknown account id", function()
      local chart = account.new()
      local ok, err = account.delete_account(chart, "nope")
      T.eq(ok, nil)
      T.ok(type(err) == "string")
    end)

    T.it("deleting a child then its former parent succeeds", function()
      local chart = account.new()
      account.add_account(chart, { id = "assets", name = "Assets", type = "asset" })
      account.add_account(chart, { id = "cash", name = "Cash", type = "asset", parent = "assets" })
      local ok1, err1 = account.delete_account(chart, "cash")
      T.ok(ok1, err1)
      local ok2, err2 = account.delete_account(chart, "assets")
      T.ok(ok2, err2)
      T.eq(#account.list(chart), 0)
    end)
  end)
end)
