if not package.path:find("?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local doc = require("lib.y_crdt.doc")
local array = require("lib.y_crdt.array")
local text = require("lib.y_crdt.text")

-- T.eq is plain Lua `~=` (see lib/test/assert.lua) -- it does not do deep
-- table comparison, so a list-valued result must be compared element by
-- element instead of via a single T.eq against a fresh table literal.
--: (actual: unknown[], expected: unknown[]) -> nil
local function eq_list(actual, expected)
  T.eq(#actual, #expected, "list length")
  for i = 1, #expected do
    T.eq(actual[i], expected[i], "list[" .. i .. "]")
  end
end

T.describe("array.insert", function()
  T.it("inserts a single value", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      T.ok(array.insert(a, txn, 0, { 42 }))
    end)
    T.eq(array.length(a), 1)
    T.eq(array.get(a, 0), 42)
  end)

  T.it("inserts multiple values in one call", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, 2, 3 })
    end)
    T.eq(array.length(a), 3)
    T.eq(array.get(a, 0), 1)
    T.eq(array.get(a, 1), 2)
    T.eq(array.get(a, 2), 3)
  end)

  T.it("inserts mixed types", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, "two", true })
    end)
    T.eq(array.length(a), 3)
    T.eq(array.get(a, 0), 1)
    T.eq(array.get(a, 1), "two")
    T.eq(array.get(a, 2), true)
  end)

  T.it("inserts a table value as JSON/Any content", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { { x = 1 } })
    end)
    local v = array.get(a, 0)
    T.eq(v.x, 1)
  end)

  T.it("inserts a nested shared type and wires it back", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    local nested = text.new()
    doc.transact(d, function(txn)
      -- text.insert before array.insert: passing `nested` into
      -- array.insert's `values: unknown[]` widens the checker's tracked
      -- type for that same variable in this closure for any later use
      -- (confirmed by minimal repro) -- ordering the SharedType-typed use
      -- first sidesteps it; semantically the two calls are independent.
      text.insert(nested, txn, 0, "hi")
      array.insert(a, txn, 0, { nested })
    end)
    T.eq(array.length(a), 1)
    T.eq(array.get(a, 0), nested)
    T.eq(text.to_string(nested), "hi")
  end)

  T.it("inserts at an index in the middle", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, 3 })
      array.insert(a, txn, 1, { 2 })
    end)
    eq_list(array.to_array(a), { 1, 2, 3 })
  end)

  T.it("rejects an out-of-range index", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      local ok, err = array.insert(a, txn, 5, { 1 })
      T.eq(ok, nil)
      T.ok(err ~= nil)
    end)
  end)
end)

T.describe("array.delete", function()
  T.it("deletes a range from the beginning", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, 2, 3, 4 })
      array.delete(a, txn, 0, 2)
    end)
    eq_list(array.to_array(a), { 3, 4 })
  end)

  T.it("deletes a range from the middle", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, 2, 3, 4 })
      array.delete(a, txn, 1, 2)
    end)
    eq_list(array.to_array(a), { 1, 4 })
  end)

  T.it("deletes a range from the end", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, 2, 3, 4 })
      array.delete(a, txn, 2, 2)
    end)
    eq_list(array.to_array(a), { 1, 2 })
  end)

  T.it("rejects an out-of-range range", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1 })
      local ok, err = array.delete(a, txn, 0, 5)
      T.eq(ok, nil)
      T.ok(err ~= nil)
    end)
  end)
end)

T.describe("array.get / array.to_array / array.length", function()
  T.it("get returns nil for an out-of-range index", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1 })
    end)
    T.eq(array.get(a, 5), nil)
  end)

  T.it("to_array reflects deletes", function()
    local d = doc.new({ client_id = 1 })
    local a = doc.get_array(d, "items")
    doc.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, 2, 3 })
      array.delete(a, txn, 1, 1)
    end)
    eq_list(array.to_array(a), { 1, 3 })
    T.eq(array.length(a), 2)
  end)
end)
