-- lib/y_crdt/encoding_test.lua
-- Tests for the lib0-compatible binary encoding layer.

if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local encoding = require("lib.y_crdt.encoding")
local float_ffi_ok, float_ffi = pcall(require, "lib.y_crdt.float_ffi")
local float_pure = require("lib.y_crdt.float_pure")

--: (string) -> string
local function hex(s)
	local out = s:gsub(".", function(c) return ("%02x"):format(c:byte()) end)
	return out
end

T.describe("tier", function()
	T.it("_tier is ffi or pure", function()
		T.ok(encoding._tier == "ffi" or encoding._tier == "pure")
	end)
end)

T.describe("write_uint8 / read_uint8", function()
	local cases = { 0, 1, 127, 128, 255 }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_uint8(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_uint8(), n)
		end)
	end
	T.it("encodes as exactly one byte", function()
		local enc = encoding.encoder()
		enc:write_uint8(200)
		T.eq(#enc:to_string(), 1)
		T.eq(hex(enc:to_string()), "c8")
	end)
	T.it("rejects out-of-range value", function()
		local enc = encoding.encoder()
		T.throws(function() enc:write_uint8(256) end)
	end)
	T.it("rejects negative value", function()
		local enc = encoding.encoder()
		T.throws(function() enc:write_uint8(-1) end)
	end)
	T.it("read past end of buffer returns (nil, errmsg)", function()
		local dec = encoding.decoder("")
		local n, err = dec:read_uint8()
		T.eq(n, nil)
		T.ok(err)
	end)
end)

T.describe("write_uint16 / read_uint16 (little-endian)", function()
	local cases = { 0, 1, 255, 256, 65535 }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_uint16(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_uint16(), n)
		end)
	end
	T.it("known byte sequence: 300 -> 2c 01", function()
		local enc = encoding.encoder()
		enc:write_uint16(300)
		T.eq(hex(enc:to_string()), "2c01")
	end)
end)

T.describe("write_uint32 / read_uint32 (little-endian)", function()
	local cases = { 0, 1, 65535, 65536, 4294967295 }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_uint32(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_uint32(), n)
		end)
	end
	T.it("known byte sequence: 300 -> 2c 01 00 00", function()
		local enc = encoding.encoder()
		enc:write_uint32(300)
		T.eq(hex(enc:to_string()), "2c010000")
	end)
end)

T.describe("write_var_uint / read_var_uint", function()
	local cases = { 0, 1, 127, 128, 255, 256, 2 ^ 14, 2 ^ 21, 2 ^ 28, 2 ^ 35, 2 ^ 49 }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_var_uint(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_var_uint(), n)
		end)
	end
	T.it("0 encodes as a single zero byte", function()
		local enc = encoding.encoder()
		enc:write_var_uint(0)
		T.eq(hex(enc:to_string()), "00")
	end)
	T.it("127 encodes as a single byte (no continuation)", function()
		local enc = encoding.encoder()
		enc:write_var_uint(127)
		T.eq(hex(enc:to_string()), "7f")
	end)
	T.it("128 encodes as two bytes (continuation set)", function()
		local enc = encoding.encoder()
		enc:write_var_uint(128)
		T.eq(hex(enc:to_string()), "8001")
	end)
	T.it("known byte sequence: 300 -> ac 02", function()
		local enc = encoding.encoder()
		enc:write_var_uint(300)
		T.eq(hex(enc:to_string()), "ac02")
	end)
	T.it("rejects negative value", function()
		local enc = encoding.encoder()
		T.throws(function() enc:write_var_uint(-1) end)
	end)
	T.it("rejects non-integer value", function()
		local enc = encoding.encoder()
		T.throws(function() enc:write_var_uint(1.5) end)
	end)
	T.it("truncated buffer returns (nil, errmsg)", function()
		local enc = encoding.encoder()
		enc:write_var_uint(128) -- two bytes, continuation set on the first
		local truncated = enc:to_string():sub(1, 1)
		local dec = encoding.decoder(truncated)
		local n, err = dec:read_var_uint()
		T.eq(n, nil)
		T.ok(err)
	end)
end)

T.describe("write_var_int / read_var_int", function()
	local cases = { 0, 1, -1, 63, 64, -63, -64, 100, -100, 1000000, -1000000, 2 ^ 30, -(2 ^ 30) }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_var_int(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_var_int(), n)
		end)
	end
	T.it("known byte sequence: 5 -> 05", function()
		local enc = encoding.encoder()
		enc:write_var_int(5)
		T.eq(hex(enc:to_string()), "05")
	end)
	T.it("known byte sequence: -5 -> 45", function()
		-- sign bit (0x40) set, magnitude 5 in the low 6 bits
		local enc = encoding.encoder()
		enc:write_var_int(-5)
		T.eq(hex(enc:to_string()), "45")
	end)
	T.it("known byte sequence: 0 -> 00", function()
		local enc = encoding.encoder()
		enc:write_var_int(0)
		T.eq(hex(enc:to_string()), "00")
	end)
end)

T.describe("write_var_string / read_var_string", function()
	local cases = { "", "hello", "a", "hello world", "line1\nline2\ttab" }
	for _, s in ipairs(cases) do
		T.it("round-trips " .. (#s == 0 and "(empty)" or s), function()
			local enc = encoding.encoder()
			enc:write_var_string(s)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_var_string(), s)
		end)
	end
	T.it("round-trips multi-byte UTF-8", function()
		local s = "héllo wörld 日本語 emoji: 🎉"
		local enc = encoding.encoder()
		enc:write_var_string(s)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_var_string(), s)
	end)
	T.it("empty string encodes as a single zero length byte", function()
		local enc = encoding.encoder()
		enc:write_var_string("")
		T.eq(hex(enc:to_string()), "00")
	end)
	T.it("length-prefixes with varUint", function()
		local enc = encoding.encoder()
		enc:write_var_string("AB")
		T.eq(hex(enc:to_string()), "024142")
	end)
end)

T.describe("write_var_buffer / read_var_buffer (varUint8Array)", function()
	T.it("round-trips arbitrary binary data", function()
		local buf = "\0\1\2\255\254\253"
		local enc = encoding.encoder()
		enc:write_var_buffer(buf)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_var_buffer(), buf)
	end)
	T.it("round-trips empty buffer", function()
		local enc = encoding.encoder()
		enc:write_var_buffer("")
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_var_buffer(), "")
	end)
	T.it("write_var_uint8_array / read_var_uint8_array aliases work", function()
		local enc = encoding.encoder()
		enc:write_var_uint8_array("xyz")
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_var_uint8_array(), "xyz")
	end)
end)

T.describe("write_float32 / read_float32", function()
	local cases = { 0, 1, -1, 0.5, 3.5, -3.5, 100, -100 }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_float32(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_float32(), n)
		end)
	end
	T.it("known byte sequence: 1.0 -> 3f 80 00 00 (big-endian)", function()
		local enc = encoding.encoder()
		enc:write_float32(1.0)
		T.eq(hex(enc:to_string()), "3f800000")
	end)
	T.it("known byte sequence: -1.0 -> bf 80 00 00", function()
		local enc = encoding.encoder()
		enc:write_float32(-1.0)
		T.eq(hex(enc:to_string()), "bf800000")
	end)
	T.it("known byte sequence: 0.0 -> 00 00 00 00", function()
		local enc = encoding.encoder()
		enc:write_float32(0.0)
		T.eq(hex(enc:to_string()), "00000000")
	end)
end)

T.describe("write_float64 / read_float64", function()
	local cases = { 0, 1, -1, 0.5, 3.14159, -3.14159, 1e300, -1e300, 1e-300 }
	for _, n in ipairs(cases) do
		T.it("round-trips " .. n, function()
			local enc = encoding.encoder()
			enc:write_float64(n)
			local dec = encoding.decoder(enc:to_string())
			T.eq(dec:read_float64(), n)
		end)
	end
	T.it("known byte sequence: 1.0 -> 3f f0 00 00 00 00 00 00 (big-endian)", function()
		local enc = encoding.encoder()
		enc:write_float64(1.0)
		T.eq(hex(enc:to_string()), "3ff0000000000000")
	end)
	T.it("known byte sequence: -1.0 -> bf f0 00 00 00 00 00 00", function()
		local enc = encoding.encoder()
		enc:write_float64(-1.0)
		T.eq(hex(enc:to_string()), "bff0000000000000")
	end)
	T.it("known byte sequence: 2.0 -> 40 00 00 00 00 00 00 00", function()
		local enc = encoding.encoder()
		enc:write_float64(2.0)
		T.eq(hex(enc:to_string()), "4000000000000000")
	end)
end)

if float_ffi_ok then
	T.describe("float tier parity (ffi vs pure)", function()
		local samples = {
			0, 1, -1, 0.5, -0.5, 3.14159, -3.14159, 100, -100,
			1e10, -1e10, 1e-10, -1e-10, 1e300, -1e300, 1e-300,
			123456789.123, 0.1, 0.2, 0.3, 1 / 3, 2 ^ 52, -(2 ^ 52),
		}
		for _, n in ipairs(samples) do
			T.it("float32 pack matches for " .. n, function()
				T.eq(float_ffi.pack_float32(n), float_pure.pack_float32(n))
			end)
			T.it("float64 pack matches for " .. n, function()
				T.eq(float_ffi.pack_float64(n), float_pure.pack_float64(n))
			end)
		end
		T.it("float32 unpack matches across tiers", function()
			for _, n in ipairs(samples) do
				local packed = float_ffi.pack_float32(n)
				local b0, b1, b2, b3 = packed:byte(1, 4)
				T.eq(float_ffi.unpack_float32(b0, b1, b2, b3), float_pure.unpack_float32(b0, b1, b2, b3))
			end
		end)
		T.it("float64 unpack matches across tiers", function()
			for _, n in ipairs(samples) do
				local packed = float_ffi.pack_float64(n)
				local b0, b1, b2, b3, b4, b5, b6, b7 = packed:byte(1, 8)
				T.eq(
					float_ffi.unpack_float64(b0, b1, b2, b3, b4, b5, b6, b7),
					float_pure.unpack_float64(b0, b1, b2, b3, b4, b5, b6, b7)
				)
			end
		end)
	end)
end

T.describe("write_any / read_any", function()
	T.it("round-trips undefined (nil)", function()
		local enc = encoding.encoder()
		enc:write_any(nil)
		local dec = encoding.decoder(enc:to_string())
		local v, err = dec:read_any()
		T.eq(v, nil)
		T.eq(err, nil)
	end)
	T.it("round-trips null sentinel", function()
		local enc = encoding.encoder()
		enc:write_any(encoding.null)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), encoding.null)
	end)
	T.it("round-trips true", function()
		local enc = encoding.encoder()
		enc:write_any(true)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), true)
	end)
	T.it("round-trips false", function()
		local enc = encoding.encoder()
		enc:write_any(false)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), false)
	end)
	T.it("round-trips small integer via varInt (tag 125)", function()
		local enc = encoding.encoder()
		enc:write_any(42)
		T.eq(hex(enc:to_string()), "7d2a") -- tag 125 = 0x7d, varint(42) = 0x2a
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), 42)
	end)
	T.it("round-trips negative integer", function()
		local enc = encoding.encoder()
		enc:write_any(-42)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), -42)
	end)
	T.it("round-trips a float64 (non-integer)", function()
		local enc = encoding.encoder()
		enc:write_any(3.14159)
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), 3.14159)
	end)
	T.it("round-trips a float32-exact fraction", function()
		local enc = encoding.encoder()
		enc:write_any(0.5)
		local dec = encoding.decoder(enc:to_string())
		local tag = enc:to_string():byte(1)
		T.eq(tag, 124) -- 0.5 is exactly representable in float32
		T.eq(dec:read_any(), 0.5)
	end)
	T.it("round-trips a string", function()
		local enc = encoding.encoder()
		enc:write_any("hello")
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), "hello")
	end)
	T.it("round-trips an array", function()
		local enc = encoding.encoder()
		enc:write_any({ 1, 2, 3 })
		local dec = encoding.decoder(enc:to_string())
		local arr = dec:read_any()
		T.eq(arr[1], 1)
		T.eq(arr[2], 2)
		T.eq(arr[3], 3)
	end)
	T.it("round-trips an empty array", function()
		local enc = encoding.encoder()
		enc:write_any({})
		T.eq(hex(enc:to_string()), "7500") -- tag 117 (array), length 0
		local dec = encoding.decoder(enc:to_string())
		local arr = dec:read_any()
		T.eq(next(arr), nil)
	end)
	T.it("round-trips a map/object", function()
		local enc = encoding.encoder()
		enc:write_any({ a = 1, b = "two" })
		local dec = encoding.decoder(enc:to_string())
		local obj = dec:read_any()
		T.eq(obj.a, 1)
		T.eq(obj.b, "two")
	end)
	T.it("round-trips a Uint8Array-equivalent buffer via write_var_buffer tag", function()
		-- writeAny doesn't have a direct "give me a Uint8Array" input from
		-- plain Lua values (Lua has no separate binary-string type), so this
		-- exercises tag 116 by decoding a hand-built frame instead.
		local enc = encoding.encoder()
		enc:write_uint8(116)
		enc:write_var_buffer("\1\2\3")
		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_any(), "\1\2\3")
	end)
	T.it("round-trips nested structures", function()
		local enc = encoding.encoder()
		enc:write_any({ list = { 1, 2, { x = true, y = encoding.null } }, name = "crdt" })
		local dec = encoding.decoder(enc:to_string())
		local obj = dec:read_any()
		T.eq(obj.name, "crdt")
		T.eq(obj.list[1], 1)
		T.eq(obj.list[2], 2)
		T.eq(obj.list[3].x, true)
		T.eq(obj.list[3].y, encoding.null)
	end)
	T.it("rejects a non-string map key", function()
		local enc = encoding.encoder()
		-- sparse/non-sequential integer-keyed table is neither a clean array
		-- nor string-keyed map by our rules once mixed with a non-integer
		-- numeric key: forces the map path, and 2.5 is not a string key either
		local t = { [1] = "a", [2.5] = "b" }
		local ok, err = enc:write_any(t)
		T.eq(ok, nil)
		T.ok(err)
	end)
	T.it("encodes unrecognized types (function) as undefined", function()
		local enc = encoding.encoder()
		enc:write_any(print)
		T.eq(hex(enc:to_string()), "7f") -- tag 127
	end)
end)

T.describe("decoder position tracking", function()
	T.it("has_content reflects remaining bytes", function()
		local enc = encoding.encoder()
		enc:write_uint8(1)
		enc:write_uint8(2)
		local dec = encoding.decoder(enc:to_string())
		T.ok(dec:has_content())
		T.eq(dec:remaining(), 2)
		dec:read_uint8()
		T.ok(dec:has_content())
		T.eq(dec:remaining(), 1)
		dec:read_uint8()
		T.fail(dec:has_content())
		T.eq(dec:remaining(), 0)
	end)
end)

T.describe("mixed-primitive stream", function()
	T.it("round-trips a sequence of heterogeneous writes in order", function()
		local enc = encoding.encoder()
		enc:write_var_uint(7)
		enc:write_var_string("clientID")
		enc:write_var_int(-3)
		enc:write_float64(2.5)
		enc:write_uint8(9)

		local dec = encoding.decoder(enc:to_string())
		T.eq(dec:read_var_uint(), 7)
		T.eq(dec:read_var_string(), "clientID")
		T.eq(dec:read_var_int(), -3)
		T.eq(dec:read_float64(), 2.5)
		T.eq(dec:read_uint8(), 9)
		T.fail(dec:has_content())
	end)
end)
