-- lib/y_crdt/parity_test.lua
--
-- Wire-compatibility parity tests against binary fixtures produced by REAL
-- yjs/lib0 (lib/y_crdt/fixtures/, generated by fixtures/generate.js -- see
-- that file's header for how/why). Each fixture's companion .json (also
-- under fixtures/) documents the exact operations performed and the
-- expected content/state-vector/hex; the values hardcoded in this file's
-- test cases below are transcribed directly from those .json files (see
-- each test's fixture path comment), not re-derived independently, so a
-- fixture regeneration that changes a value is caught by a literal mismatch
-- here rather than silently accepted.
--
-- Four kinds of check, per the task brief:
--   decode      -- does Lua's decoder read the yjs-produced bytes correctly?
--   encode      -- does performing the same ops in Lua produce the same bytes?
--   round-trip  -- decode the fixture, re-encode, same bytes back out?
--   convergence -- for concurrent edits, do independently-applied updates
--                  reach the same final state?

if not package.path:find("?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local encoding = require("lib.y_crdt.encoding")
local doc_mod = require("lib.y_crdt.doc")
local text = require("lib.y_crdt.text")
local array = require("lib.y_crdt.array")
local map = require("lib.y_crdt.map")
local update = require("lib.y_crdt.update")

-- Hand-restated (not `typeof`-captured), matching item.lua's/text.lua's/
-- array.lua's own declarations structurally -- see integrate.lua's
-- matching restatement for why (a self-referential record loses precision
-- under `typeof`). Needed only so `map.get`'s `unknown` return (a nested
-- Y.Text/Y.Array retrieved from a Y.Map, in the nested_types test below)
-- can be checked-cast to the concrete type text.to_string/array.to_array
-- require -- a bare `unknown` VALUE (not a record with `unknown` fields)
-- casts directly to a concrete type here, matching integrate.lua's own
-- `ContentType.shared_type` trust boundary comment.
--:: Id = { client: integer, clock: integer }
--:: ParentPendingId = { kind: "pending_parent_id", client: integer, clock: integer }
--:: Content = { kind: "deleted", ref: integer, len: integer } | { kind: "string", ref: integer, str: string } | { kind: "json", ref: integer, arr: unknown[] } | { kind: "embed", ref: integer, embed: unknown } | { kind: "any", ref: integer, arr: unknown[] } | { kind: "format", ref: integer, key: string, value: unknown } | { kind: "type", ref: integer, shared_type: unknown } | { kind: "doc", ref: integer, guid: string, opts: unknown } | { kind: "binary", ref: integer, bytes: string }
--:: Item = {
--::   kind: "item",
--::   id: Id,
--::   origin: Id | nil,
--::   origin_right: Id | nil,
--::   left: Item | nil,
--::   right: Item | nil,
--::   parent: SharedType | ParentPendingId | nil,
--::   parent_sub: string | nil,
--::   content: Content,
--::   length: integer,
--::   deleted: boolean,
--::   keep: boolean,
--:: }
--:: SharedType = { kind: "shared_type", type_name: string, start: Item | nil, map: { [string]: Item }, length: number, item: Item | nil }
local sync = require("lib.y_crdt.sync")

local FIXTURES = "lib/y_crdt/fixtures"

--: (string) -> string
local function slurp(path)
  local f = io.open(path, "rb")
  if not f then error("parity_test: cannot open fixture " .. path, 2) end
  local s = f:read("*a") or ""
  f:close()
  return s
end

--------------------------------------------------------------------------
-- 1. Encoding primitives (fixtures/encoding/*.bin)
--------------------------------------------------------------------------
-- Values transcribed from fixtures/encoding/*.json (generate.js's
-- varUintCases/varIntCases/varStringCases/anyCases tables).

T.describe("parity: encoding primitives vs real lib0", function()
  local var_uint_cases = {
    { name = "varuint_0", value = 0 }, { name = "varuint_1", value = 1 }, { name = "varuint_127", value = 127 },
    { name = "varuint_128", value = 128 }, { name = "varuint_255", value = 255 }, { name = "varuint_256", value = 256 },
    { name = "varuint_16383", value = 16383 }, { name = "varuint_16384", value = 16384 },
    { name = "varuint_2_21", value = 2 ^ 21 }, { name = "varuint_2_28", value = 2 ^ 28 },
    { name = "varuint_2_35", value = 2 ^ 35 }, { name = "varuint_2_49", value = 2 ^ 49 },
  }
  for _, c in ipairs(var_uint_cases) do
    local name, value = c.name, c.value
    T.it("decode+encode " .. name, function()
      local fixture = slurp(FIXTURES .. "/encoding/" .. name .. ".bin")
      local dec = encoding.decoder(fixture)
      local got, err = dec:read_var_uint()
      T.eq(got, value, err)
      local enc = encoding.encoder()
      enc:write_var_uint(value)
      T.eq(enc:to_string(), fixture)
    end)
  end

  local var_int_cases = {
    { name = "varint_0", value = 0 }, { name = "varint_1", value = 1 }, { name = "varint_neg1", value = -1 },
    { name = "varint_63", value = 63 }, { name = "varint_64", value = 64 }, { name = "varint_neg64", value = -64 },
    { name = "varint_neg65", value = -65 }, { name = "varint_2_20", value = 2 ^ 20 }, { name = "varint_neg2_20", value = -(2 ^ 20) },
  }
  for _, c in ipairs(var_int_cases) do
    local name, value = c.name, c.value
    T.it("decode+encode " .. name, function()
      local fixture = slurp(FIXTURES .. "/encoding/" .. name .. ".bin")
      local dec = encoding.decoder(fixture)
      local got, err = dec:read_var_int()
      T.eq(got, value, err)
      local enc = encoding.encoder()
      enc:write_var_int(value)
      T.eq(enc:to_string(), fixture)
    end)
  end

  local var_string_cases = {
    { name = "varstring_empty", value = "" },
    { name = "varstring_ascii", value = "hello" },
    { name = "varstring_multibyte", value = "héllo wörld 日本語 emoji: 🎉" },
  }
  for _, c in ipairs(var_string_cases) do
    local name, value = c.name, c.value
    T.it("decode+encode " .. name, function()
      local fixture = slurp(FIXTURES .. "/encoding/" .. name .. ".bin")
      local dec = encoding.decoder(fixture)
      local got, err = dec:read_var_string()
      T.eq(got, value, err)
      local enc = encoding.encoder()
      enc:write_var_string(value)
      T.eq(enc:to_string(), fixture)
    end)
  end

  -- writeAny: one case per lib0 tag. `nil` in this list means the wire
  -- "undefined" tag (127); `encoding.null` is the wire "null" tag (126) --
  -- same sentinel convention encoding.lua documents.
  local any_cases = {
    { name = "any_undefined", value = nil },
    { name = "any_null", value = encoding.null },
    { name = "any_true", value = true },
    { name = "any_false", value = false },
    { name = "any_integer", value = 42 },
    { name = "any_negative_integer", value = -42 },
    { name = "any_float32", value = 0.5 },
    { name = "any_float64", value = 3.14159 },
    { name = "any_string", value = "hello" },
  }
  for _, c in ipairs(any_cases) do
    local name, value = c.name, c.value
    T.it("decode+encode " .. name, function()
      local fixture = slurp(FIXTURES .. "/encoding/" .. name .. ".bin")
      local dec = encoding.decoder(fixture)
      local got, err = dec:read_any()
      if value == nil then
        T.eq(got, nil)
      else
        T.eq(got, value, err)
      end
      local enc = encoding.encoder()
      local ok, werr = enc:write_any(value)
      T.ok(ok, werr)
      T.eq(enc:to_string(), fixture)
    end)
  end

  T.it("decode+encode any_array ([1,2,3], tag 117)", function()
    local fixture = slurp(FIXTURES .. "/encoding/any_array.bin")
    local dec = encoding.decoder(fixture)
    local got = dec:read_any()
    T.eq(got[1], 1)
    T.eq(got[2], 2)
    T.eq(got[3], 3)
    local enc = encoding.encoder()
    enc:write_any({ 1, 2, 3 })
    T.eq(enc:to_string(), fixture)
  end)

  T.it("decode+encode any_empty_array (tag 117, len 0)", function()
    local fixture = slurp(FIXTURES .. "/encoding/any_empty_array.bin")
    local dec = encoding.decoder(fixture)
    local got = dec:read_any()
    T.eq(next(got), nil)
    local enc = encoding.encoder()
    enc:write_any({})
    T.eq(enc:to_string(), fixture)
  end)

  T.it("decode+encode any_map ({a=1, b='two'}, tag 118)", function()
    local fixture = slurp(FIXTURES .. "/encoding/any_map.bin")
    local dec = encoding.decoder(fixture)
    local got = dec:read_any()
    T.eq(got.a, 1)
    T.eq(got.b, "two")
    -- Map key order is not wire-stable across Lua's `pairs` vs JS's
    -- insertion order, so this only checks decode fidelity, not a
    -- byte-identical re-encode (the fixture's own key order is
    -- {a,b}, matching JS insertion order; Lua re-encode order is
    -- unspecified by `pairs`).
  end)

  T.it("decode+encode any_nested (nested list/map, tag 117/118)", function()
    local fixture = slurp(FIXTURES .. "/encoding/any_nested.bin")
    local dec = encoding.decoder(fixture)
    local got = dec:read_any()
    T.eq(got.name, "crdt")
    T.eq(got.list[1], 1)
    T.eq(got.list[2], 2)
    T.eq(got.list[3].x, true)
    T.eq(got.list[3].y, encoding.null)
  end)

  T.it("decode any_uint8array (tag 116, raw bytes [1,2,3,254,255])", function()
    local fixture = slurp(FIXTURES .. "/encoding/any_uint8array.bin")
    local dec = encoding.decoder(fixture)
    local got = dec:read_any()
    T.eq(got, "\1\2\3\254\255")
  end)
end)

--------------------------------------------------------------------------
-- 2. Update fixtures (fixtures/updates/*.bin)
--------------------------------------------------------------------------

T.describe("parity: single_text_insert", function()
  -- fixtures/updates/single_text_insert.json: client 1, insert(0,'hello')
  local fixture = slurp(FIXTURES .. "/updates/single_text_insert.bin")

  T.it("decode: applies onto a fresh doc and matches expected content", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    T.eq(text.to_string(t), "hello")
  end)

  T.it("decode: state vector after apply is {1=5}", function()
    local d = doc_mod.new({ client_id = 1 })
    doc_mod.get_text(d, "content")
    update.apply_v1(d, fixture)
    local sv = update.decode_state_vector(update.encode_state_vector(d))
    T.eq(sv[1], 5)
  end)

  T.it("encode: performing the same op in Lua produces the same bytes", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    local txn = doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello") end)
    local bytes, err = update.encode_v1(d, txn)
    T.ok(bytes ~= nil, err)
    T.eq(bytes, fixture)
  end)

  T.it("round trip: decode fixture then re-encode via encode_diff_v1 matches byte-for-byte", function()
    local d = doc_mod.new({ client_id = 1 })
    doc_mod.get_text(d, "content")
    update.apply_v1(d, fixture)
    local empty_sv = update.encode_state_vector_from_table({})
    local reencoded, err = update.encode_diff_v1(d, empty_sv)
    T.ok(reencoded ~= nil, err)
    T.eq(reencoded, fixture)
  end)
end)

T.describe("parity: multiple_inserts", function()
  -- fixtures/updates/multiple_inserts.json: insert(0,'hello') then insert(5,' world')
  local fixture = slurp(FIXTURES .. "/updates/multiple_inserts.bin")

  T.it("decode: applies and matches 'hello world'", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    T.eq(text.to_string(t), "hello world")
  end)

  -- KNOWN DIFFERENCE (not a bug -- see TODO.md "item compaction"): real yjs
  -- merges adjacent same-client Items with mergeable content during
  -- transaction cleanup (`tryToMergeWithLefts`, confirmed in
  -- node_modules/yjs/dist/yjs.cjs), so its wire output for two sequential
  -- inserts is a single 11-byte "hello world" Item. This port doesn't
  -- perform that compaction (doc.lua's own header already documents this
  -- scope cut), so the same two Lua ops produce two separate wire Items
  -- ("hello" then " world") -- semantically identical content, different
  -- byte layout. Checked here via content-after-decode instead of a raw
  -- byte comparison.
  T.it("encode: two sequential Lua inserts produce semantically-equivalent content (byte layout differs -- no item compaction, see TODO.md)", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello") end)
    doc_mod.transact(d, function(txn) text.insert(t, txn, 5, " world") end)
    local empty_sv = update.encode_state_vector_from_table({})
    local bytes, err = update.encode_diff_v1(d, empty_sv)
    T.ok(bytes ~= nil, err)

    local d2 = doc_mod.new({ client_id = 99 })
    local t2 = doc_mod.get_text(d2, "content")
    update.apply_v1(d2, bytes)
    T.eq(text.to_string(t2), "hello world")

    T.skip("byte-for-byte comparison against the fixture skipped: real yjs merges adjacent same-client items during transaction cleanup, which this port does not yet implement (TODO.md 'item compaction') -- content is verified equivalent above instead")
  end)
end)

T.describe("parity: delete_middle", function()
  -- fixtures/updates/delete_middle.json: insert(0,'hello world'), delete(3,5) -> 'helrld'
  local fixture = slurp(FIXTURES .. "/updates/delete_middle.bin")

  T.it("decode: applies and matches 'helrld'", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    T.eq(text.to_string(t), "helrld")
  end)

  -- KNOWN DIFFERENCE (not a bug -- see TODO.md "item compaction"): real
  -- yjs's default `gc: true` behavior replaces a deleted-and-superseded
  -- Item's content with a bare `ContentDeleted` placeholder (dropping the
  -- actual "lo wo" bytes, keeping only its length) once nothing can
  -- reference the original content anymore. This port marks the item
  -- `.deleted = true` (which apply_v1's decode side already handles
  -- correctly, per the "decode" test above) but never GC-compacts its
  -- content afterward, so Lua's own re-encode still carries the original
  -- string bytes for that (deleted) middle item. Same "extra yjs cleanup
  -- pass this port doesn't perform yet" family as multiple_inserts' item
  -- compaction above -- checked via content-after-decode instead.
  T.it("encode: matching Lua ops produce semantically-equivalent content (byte layout differs -- no deleted-content GC compaction, see TODO.md)", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello world") end)
    doc_mod.transact(d, function(txn) text.delete(t, txn, 3, 5) end)
    local empty_sv = update.encode_state_vector_from_table({})
    local bytes, err = update.encode_diff_v1(d, empty_sv)
    T.ok(bytes ~= nil, err)

    local d2 = doc_mod.new({ client_id = 99 })
    local t2 = doc_mod.get_text(d2, "content")
    update.apply_v1(d2, bytes)
    T.eq(text.to_string(t2), "helrld")

    T.skip("byte-for-byte comparison against the fixture skipped: real yjs GC-compacts deleted item content (dropping superseded bytes), which this port does not yet implement (TODO.md 'item compaction') -- content is verified equivalent above instead")
  end)
end)

T.describe("parity: text_format (bold/italic)", function()
  -- fixtures/updates/text_format.json: insert 'hello world', format[0,5)=bold, format[6,5)=italic
  local fixture = slurp(FIXTURES .. "/updates/text_format.bin")

  T.it("decode: applies and matches content + delta shape", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    T.eq(text.to_string(t), "hello world")
    local delta = text.to_delta(t)
    T.eq(#delta, 3)
    T.eq(delta[1].insert, "hello")
    T.eq(delta[1].attributes.bold, true)
    T.eq(delta[2].insert, " ")
    T.eq(delta[2].attributes, nil)
    T.eq(delta[3].insert, "world")
    T.eq(delta[3].attributes.italic, true)
  end)

  T.it("encode: matching Lua ops produce the same full-doc bytes", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello world") end)
    doc_mod.transact(d, function(txn) text.format(t, txn, 0, 5, { bold = true }) end)
    doc_mod.transact(d, function(txn) text.format(t, txn, 6, 5, { italic = true }) end)
    local empty_sv = update.encode_state_vector_from_table({})
    local bytes, err = update.encode_diff_v1(d, empty_sv)
    T.ok(bytes ~= nil, err)
    T.eq(bytes, fixture)
  end)
end)

T.describe("parity: array_mixed", function()
  -- fixtures/updates/array_mixed.json: insert(0, [1,'two',true,false,null,[1,2,3]])
  local fixture = slurp(FIXTURES .. "/updates/array_mixed.bin")

  T.it("decode: applies and matches expected values", function()
    local d = doc_mod.new({ client_id = 1 })
    local a = doc_mod.get_array(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    local vals = array.to_array(a)
    T.eq(vals[1], 1)
    T.eq(vals[2], "two")
    T.eq(vals[3], true)
    T.eq(vals[4], false)
    T.eq(vals[5], encoding.null)
    T.eq(vals[6][1], 1)
    T.eq(vals[6][2], 2)
    T.eq(vals[6][3], 3)
  end)

  T.it("encode: matching Lua op produces the same bytes", function()
    local d = doc_mod.new({ client_id = 1 })
    local a = doc_mod.get_array(d, "content")
    local txn = doc_mod.transact(d, function(txn)
      array.insert(a, txn, 0, { 1, "two", true, false, encoding.null, { 1, 2, 3 } })
    end)
    local bytes, err = update.encode_v1(d, txn)
    T.ok(bytes ~= nil, err)
    T.eq(bytes, fixture)
  end)
end)

T.describe("parity: map_operations", function()
  -- fixtures/updates/map_operations.json: set(a,1) set(b,'two') set(c,true) delete(b) set(a,100)
  local fixture = slurp(FIXTURES .. "/updates/map_operations.bin")

  T.it("decode: applies and matches final table {a=100, c=true}", function()
    local d = doc_mod.new({ client_id = 1 })
    local m = doc_mod.get_map(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    T.eq(map.get(m, "a"), 100)
    T.eq(map.get(m, "b"), nil)
    T.eq(map.has(m, "b"), false)
    T.eq(map.get(m, "c"), true)
  end)

  -- KNOWN DIFFERENCE (not a bug -- see TODO.md "item compaction"): same
  -- deleted-content GC-compaction family as delete_middle above -- real
  -- yjs's default `gc: true` replaces the superseded `set(a,1)` and the
  -- explicitly deleted `set(b,'two')` entries' content with bare
  -- `ContentDeleted` placeholders (dropping the actual value bytes), which
  -- this port doesn't perform. Checked via content-after-decode instead.
  T.it("encode: matching Lua ops produce semantically-equivalent content (byte layout differs -- no deleted-content GC compaction, see TODO.md)", function()
    local d = doc_mod.new({ client_id = 1 })
    local m = doc_mod.get_map(d, "content")
    doc_mod.transact(d, function(txn) map.set(m, txn, "a", 1) end)
    doc_mod.transact(d, function(txn) map.set(m, txn, "b", "two") end)
    doc_mod.transact(d, function(txn) map.set(m, txn, "c", true) end)
    doc_mod.transact(d, function(txn) map.delete(m, txn, "b") end)
    doc_mod.transact(d, function(txn) map.set(m, txn, "a", 100) end)
    local empty_sv = update.encode_state_vector_from_table({})
    local bytes, err = update.encode_diff_v1(d, empty_sv)
    T.ok(bytes ~= nil, err)

    local d2 = doc_mod.new({ client_id = 99 })
    local m2 = doc_mod.get_map(d2, "content")
    update.apply_v1(d2, bytes)
    T.eq(map.get(m2, "a"), 100)
    T.eq(map.has(m2, "b"), false)
    T.eq(map.get(m2, "c"), true)

    T.skip("byte-for-byte comparison against the fixture skipped: real yjs GC-compacts superseded/deleted map entry content (dropping the old value's bytes), which this port does not yet implement (TODO.md 'item compaction') -- content is verified equivalent above instead")
  end)
end)

T.describe("parity: nested_types (Y.Map containing Y.Text + Y.Array)", function()
  -- fixtures/updates/nested_types.json
  local fixture = slurp(FIXTURES .. "/updates/nested_types.bin")

  T.it("decode: applies and matches nested content", function()
    local d = doc_mod.new({ client_id = 1 })
    local m = doc_mod.get_map(d, "content")
    local txn, err = update.apply_v1(d, fixture)
    T.ok(txn ~= nil, err)
    local nested_text_raw = map.get(m, "text")
    T.ok(nested_text_raw ~= nil)
    if type(nested_text_raw) ~= "table" then error("parity_test: expected nested 'text' entry to be a SharedType table", 2) end
    local nested_text = nested_text_raw --[[: SharedType]]
    T.eq(text.to_string(nested_text), "nested hello")

    local nested_array_raw = map.get(m, "array")
    T.ok(nested_array_raw ~= nil)
    if type(nested_array_raw) ~= "table" then error("parity_test: expected nested 'array' entry to be a SharedType table", 2) end
    local nested_array = nested_array_raw --[[: SharedType]]
    local vals = array.to_array(nested_array)
    T.eq(vals[1], 1)
    T.eq(vals[2], 2)
    T.eq(vals[3], 3)
  end)

  T.it("encode: matching Lua ops produce the same full-doc bytes", function()
    local d = doc_mod.new({ client_id = 1 })
    local m = doc_mod.get_map(d, "content")
    local nested_text = text.new()
    doc_mod.transact(d, function(txn) map.set(m, txn, "text", nested_text) end)
    doc_mod.transact(d, function(txn) text.insert(nested_text, txn, 0, "nested hello") end)
    local nested_array = array.new()
    doc_mod.transact(d, function(txn) map.set(m, txn, "array", nested_array) end)
    doc_mod.transact(d, function(txn) array.insert(nested_array, txn, 0, { 1, 2, 3 }) end)
    local empty_sv = update.encode_state_vector_from_table({})
    local bytes, err = update.encode_diff_v1(d, empty_sv)
    T.ok(bytes ~= nil, err)
    T.eq(bytes, fixture)
  end)
end)

T.describe("parity: concurrent_inserts (convergence)", function()
  -- fixtures/updates/concurrent_inserts.json: client 1 and 2 both start from
  -- 'hello', then concurrently insert at index 5 without seeing each other.
  local base_fixture = slurp(FIXTURES .. "/updates/concurrent_inserts_base.bin")
  local a_diff_fixture = slurp(FIXTURES .. "/updates/concurrent_inserts_a.bin")
  local b_diff_fixture = slurp(FIXTURES .. "/updates/concurrent_inserts_b.bin")

  T.it("encode: base update ('hello' from client 1) matches fixture bytes", function()
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    local txn = doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello") end)
    local bytes = update.encode_v1(d, txn)
    T.eq(bytes, base_fixture)
  end)

  T.it("encode: each client's concurrent diff matches fixture bytes, and both converge to the same content", function()
    local doc_a = doc_mod.new({ client_id = 1 })
    local text_a = doc_mod.get_text(doc_a, "content")
    doc_mod.transact(doc_a, function(txn) text.insert(text_a, txn, 0, "hello") end)

    local doc_b = doc_mod.new({ client_id = 2 })
    doc_mod.get_text(doc_b, "content")
    update.apply_v1(doc_b, base_fixture)
    local text_b = doc_b.share["content"]

    doc_mod.transact(doc_a, function(txn) text.insert(text_a, txn, 5, " A-side") end)
    doc_mod.transact(doc_b, function(txn) text.insert(text_b, txn, 5, " B-side") end)

    T.eq(text.to_string(text_a), "hello A-side")
    T.eq(text.to_string(text_b), "hello B-side")

    local sv_b = update.encode_state_vector(doc_b)
    local a_diff, aerr = update.encode_diff_v1(doc_a, sv_b)
    T.ok(a_diff ~= nil, aerr)
    T.eq(a_diff, a_diff_fixture)

    local sv_a = update.encode_state_vector(doc_a)
    local b_diff, berr = update.encode_diff_v1(doc_b, sv_a)
    T.ok(b_diff ~= nil, berr)
    T.eq(b_diff, b_diff_fixture)

    -- Convergence: apply each side's diff to the other; both must reach the
    -- same final content (fixtures/updates/concurrent_inserts.json's
    -- "converged_content": "hello A-side B-side").
    local applied_to_a, aerr2 = update.apply_v1(doc_a, b_diff)
    T.ok(applied_to_a ~= nil, aerr2)
    local applied_to_b, berr2 = update.apply_v1(doc_b, a_diff)
    T.ok(applied_to_b ~= nil, berr2)

    T.eq(text.to_string(text_a), "hello A-side B-side")
    T.eq(text.to_string(text_b), "hello A-side B-side")
  end)
end)

--------------------------------------------------------------------------
-- 3. State vector fixtures (fixtures/state_vectors/*.bin)
--------------------------------------------------------------------------

T.describe("parity: state vectors", function()
  T.it("empty: decodes to {} and re-encodes byte-identical", function()
    local fixture = slurp(FIXTURES .. "/state_vectors/empty.bin")
    local sv, err = update.decode_state_vector(fixture)
    T.ok(sv ~= nil, err)
    T.eq(next(sv), nil)
    T.eq(update.encode_state_vector_from_table(sv), fixture)
  end)

  T.it("single_client: decodes to {1=5} and re-encodes byte-identical", function()
    local fixture = slurp(FIXTURES .. "/state_vectors/single_client.bin")
    local sv, err = update.decode_state_vector(fixture)
    T.ok(sv ~= nil, err)
    T.eq(sv[1], 5)
    T.eq(update.encode_state_vector_from_table(sv), fixture)
  end)

  T.it("multi_client: decodes to {1=5, 2=5} and re-encodes byte-identical", function()
    local fixture = slurp(FIXTURES .. "/state_vectors/multi_client.bin")
    local sv, err = update.decode_state_vector(fixture)
    T.ok(sv ~= nil, err)
    T.eq(sv[1], 5)
    T.eq(sv[2], 5)
    T.eq(update.encode_state_vector_from_table(sv), fixture)
  end)

  T.it("single_client: matches Lua-side encode of the same doc state", function()
    local fixture = slurp(FIXTURES .. "/state_vectors/single_client.bin")
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello") end)
    T.eq(update.encode_state_vector(d), fixture)
  end)
end)

--------------------------------------------------------------------------
-- 4. Sync protocol fixtures (fixtures/sync/*.bin)
--------------------------------------------------------------------------

T.describe("parity: sync messages", function()
  T.it("step1: read_message tags it 'step1' and payload decodes to {1=5}", function()
    local fixture = slurp(FIXTURES .. "/sync/step1.bin")
    local msg_type, payload = sync.read_message(fixture)
    T.eq(msg_type, "step1")
    local sv, err = update.decode_state_vector(payload)
    T.ok(sv ~= nil, err)
    T.eq(sv[1], 5)
  end)

  T.it("step1: Lua-produced message for the same doc state matches byte-for-byte", function()
    local fixture = slurp(FIXTURES .. "/sync/step1.bin")
    local d = doc_mod.new({ client_id = 1 })
    local t = doc_mod.get_text(d, "content")
    doc_mod.transact(d, function(txn) text.insert(t, txn, 0, "hello") end)
    T.eq(sync.write_step1(d), fixture)
  end)

  T.it("step2: read_message tags it 'step2' and applies to carry 'hello'", function()
    local fixture = slurp(FIXTURES .. "/sync/step2.bin")
    local msg_type, payload = sync.read_message(fixture)
    T.eq(msg_type, "step2")
    local d = doc_mod.new({ client_id = 99 })
    local t = doc_mod.get_text(d, "content")
    local applied, err = update.apply_v1(d, payload)
    T.ok(applied ~= nil, err)
    T.eq(text.to_string(t), "hello")
  end)

  T.it("update_msg: read_message tags it 'update' and applies to carry 'x'", function()
    local fixture = slurp(FIXTURES .. "/sync/update_msg.bin")
    local msg_type, payload = sync.read_message(fixture)
    T.eq(msg_type, "update")
    local d = doc_mod.new({ client_id = 99 })
    local t = doc_mod.get_text(d, "content")
    local applied, err = update.apply_v1(d, payload)
    T.ok(applied ~= nil, err)
    T.eq(text.to_string(t), "x")
  end)

  T.it("update_msg: Lua write_update wrapping the fixture's own update payload matches byte-for-byte", function()
    local fixture = slurp(FIXTURES .. "/sync/update_msg.bin")
    local _msg_type, payload = sync.read_message(fixture)
    T.eq(sync.write_update(payload), fixture)
  end)
end)

T.describe("parity: full_handshake (real yjs two-peer sync, replayed against Lua)", function()
  -- fixtures/sync/full_handshake/handshake.json: A ('hello from A', client 1)
  -- and B (empty, client 2) run the 3-message sync protocol to convergence,
  -- then A broadcasts a further local edit ('!!' appended) as an Update
  -- message. Every step below checks BOTH that Lua's own emitted message
  -- bytes match the corresponding fixture (encode parity) and that
  -- applying the fixture's own bytes drives Lua to the same state yjs
  -- reached (decode parity).
  local dir = FIXTURES .. "/sync/full_handshake"
  local msg1 = slurp(dir .. "/01_a_to_b_step1.bin")
  local msg2 = slurp(dir .. "/02_b_to_a_step2.bin")
  local msg3 = slurp(dir .. "/03_b_to_a_step1.bin")
  local msg4 = slurp(dir .. "/04_a_to_b_step2.bin")
  local msg5 = slurp(dir .. "/05_a_to_b_update.bin")

  T.it("full sequence converges both peers to 'hello from A!!'", function()
    local a = doc_mod.new({ client_id = 1 })
    local text_a = doc_mod.get_text(a, "content")
    doc_mod.transact(a, function(txn) text.insert(text_a, txn, 0, "hello from A") end)

    local b = doc_mod.new({ client_id = 2 })
    local text_b = doc_mod.get_text(b, "content")

    -- 1. A -> B step1: Lua's own emission must match the real yjs bytes.
    local step1 = sync.write_step1(a)
    T.eq(step1, msg1)

    -- 2. B handles the fixture's own step1 bytes (decode parity), replies
    -- with step2; Lua's reply must match the real yjs bytes (encode parity).
    local reply1, rerr1 = sync.handle_message(b, msg1)
    T.ok(reply1 ~= nil, rerr1)
    T.eq(reply1, msg2)

    -- 3. A applies the fixture's own step2 bytes; no reply expected (B had
    -- nothing new), content unchanged.
    local reply2, rerr2 = sync.handle_message(a, msg2)
    T.eq(reply2, nil)
    T.eq(rerr2, nil)
    T.eq(text.to_string(text_a), "hello from A")

    -- 4. B -> A step1: Lua's own emission must match the real yjs bytes.
    local step1b = sync.write_step1(b)
    T.eq(step1b, msg3)

    -- 5. A handles the fixture's own step1 bytes, replies with step2
    -- (carrying "hello from A"); Lua's reply must match the real yjs bytes.
    local reply3, rerr3 = sync.handle_message(a, msg3)
    T.ok(reply3 ~= nil, rerr3)
    T.eq(reply3, msg4)

    -- 6. B applies the fixture's own step2 bytes -- now has "hello from A".
    local reply4, rerr4 = sync.handle_message(b, msg4)
    T.eq(reply4, nil)
    T.eq(rerr4, nil)
    T.eq(text.to_string(text_b), "hello from A")

    -- 7. A makes a further local edit and broadcasts it as an Update
    -- message; Lua's own emission must match the real yjs bytes.
    local txn = doc_mod.transact(a, function(txn) text.insert(text_a, txn, 12, "!!") end)
    local update_bytes, uerr = update.encode_v1(a, txn)
    T.ok(update_bytes ~= nil, uerr)
    local update_msg = sync.write_update(update_bytes)
    T.eq(update_msg, msg5)

    -- 8. B applies the fixture's own update bytes -- both sides converge.
    local reply5, rerr5 = sync.handle_message(b, msg5)
    T.eq(reply5, nil)
    T.eq(rerr5, nil)

    T.eq(text.to_string(text_a), "hello from A!!")
    T.eq(text.to_string(text_b), "hello from A!!")
  end)
end)
