if not package.path:find("?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local doc = require("lib.y_crdt.doc")
local text = require("lib.y_crdt.text")
local id = require("lib.y_crdt.id")
local content = require("lib.y_crdt.content")
local item = require("lib.y_crdt.item")
local integrate = require("lib.y_crdt.integrate")

T.describe("text.insert", function()
  T.it("inserts into an empty text", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      T.ok(text.insert(t, txn, 0, "hello"))
    end)
    T.eq(text.to_string(t), "hello")
    T.eq(text.length(t), 5)
  end)

  T.it("inserts at the beginning", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "world")
      text.insert(t, txn, 0, "hello ")
    end)
    T.eq(text.to_string(t), "hello world")
  end)

  T.it("inserts in the middle", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "helloworld")
      text.insert(t, txn, 5, " ")
    end)
    T.eq(text.to_string(t), "hello world")
  end)

  T.it("inserts at the end", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello")
      text.insert(t, txn, 5, " world")
    end)
    T.eq(text.to_string(t), "hello world")
  end)

  T.it("rejects an out-of-range index", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      local ok, err = text.insert(t, txn, 5, "x")
      T.eq(ok, nil)
      T.ok(err ~= nil)
    end)
  end)
end)

T.describe("text.delete", function()
  T.it("deletes from the beginning", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello world")
      text.delete(t, txn, 0, 6)
    end)
    T.eq(text.to_string(t), "world")
  end)

  T.it("deletes from the middle", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello world")
      text.delete(t, txn, 5, 1)
    end)
    T.eq(text.to_string(t), "helloworld")
  end)

  T.it("deletes from the end", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello world")
      text.delete(t, txn, 5, 6)
    end)
    T.eq(text.to_string(t), "hello")
  end)

  T.it("insert then delete round-trips to empty", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello")
      text.delete(t, txn, 0, 5)
    end)
    T.eq(text.to_string(t), "")
    T.eq(text.length(t), 0)
  end)

  T.it("deleted items are excluded from a later insert's neighbor walk", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello")
      text.delete(t, txn, 1, 3) -- "h" + "o" survive, "ell" deleted
      text.insert(t, txn, 1, "i")
    end)
    T.eq(text.to_string(t), "hio")
  end)

  T.it("rejects an out-of-range range", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hi")
      local ok, err = text.delete(t, txn, 0, 5)
      T.eq(ok, nil)
      T.ok(err ~= nil)
    end)
  end)
end)

T.describe("text.length", function()
  T.it("tracks visible length across inserts and deletes", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    T.eq(text.length(t), 0)
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "abcdef")
    end)
    T.eq(text.length(t), 6)
    doc.transact(d, function(txn)
      text.delete(t, txn, 2, 2)
    end)
    T.eq(text.length(t), 4)
  end)
end)

T.describe("text.format / text.to_delta", function()
  T.it("insert with attrs produces a delta run with those attributes", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello", { bold = true })
    end)
    local delta = text.to_delta(t)
    T.eq(#delta, 1)
    T.eq(delta[1].insert, "hello")
    T.ok(delta[1].attributes ~= nil)
    T.eq(delta[1].attributes.bold, true)
  end)

  T.it("plain insert produces a delta run with no attributes", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello")
    end)
    local delta = text.to_delta(t)
    T.eq(#delta, 1)
    T.eq(delta[1].insert, "hello")
    T.eq(delta[1].attributes, nil)
  end)

  T.it("format applies attributes to an existing range", function()
    local d = doc.new({ client_id = 1 })
    local t = doc.get_text(d, "content")
    doc.transact(d, function(txn)
      text.insert(t, txn, 0, "hello world")
      T.ok(text.format(t, txn, 0, 5, { bold = true }))
    end)
    local delta = text.to_delta(t)
    -- "hello" bold, " world" unformatted
    T.eq(#delta, 2)
    T.eq(delta[1].insert, "hello")
    T.eq(delta[1].attributes.bold, true)
    T.eq(delta[2].insert, " world")
    T.eq(delta[2].attributes, nil)
  end)
end)

T.describe("text concurrent inserts (YATA convergence)", function()
  T.it("converges to the same visible order regardless of integration order", function()
    -- Two items from different clients, both targeting index 0 of an empty
    -- text (same origin/origin_right: nil/nil). YATA must place them in a
    -- deterministic order (lower client id wins the left position) no
    -- matter which one is integrated first -- this is the core correctness
    -- property this whole library exists to guarantee, exercised here at
    -- the text.lua level rather than item.lua's (see item_test.lua/
    -- struct_store_test.lua for the lower-level version).
    --: (first: "a" | "b") -> string
    local function build(first)
      local d = doc.new({ client_id = 99 })
      local t = doc.get_text(d, "content")
      doc.transact(d, function(txn)
        local item_a = item.new(id.new(1, 0), nil, nil, t, nil, content.string("A"))
        local item_b = item.new(id.new(2, 0), nil, nil, t, nil, content.string("B"))
        if first == "a" then
          integrate.integrate(txn, item_a)
          integrate.integrate(txn, item_b)
        else
          integrate.integrate(txn, item_b)
          integrate.integrate(txn, item_a)
        end
      end)
      return text.to_string(t)
    end

    local s1 = build("a")
    local s2 = build("b")
    T.eq(s1, s2)
    T.eq(#s1, 2)
  end)
end)
