if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local url = require("lib.url")
local T = require("lib.test.assert")

-- ============================================================
-- Percent encoding
-- ============================================================

T.describe("url.encode", function()
  T.it("passes through unreserved characters", function()
    T.eq(url.encode("abcXYZ0123456789-._~"), "abcXYZ0123456789-._~")
  end)
  T.it("encodes spaces", function()
    T.eq(url.encode("hello world"), "hello%20world")
  end)
  T.it("encodes special characters", function()
    T.eq(url.encode("hello world!"), "hello%20world%21")
  end)
  T.it("encodes empty string", function()
    T.eq(url.encode(""), "")
  end)
  T.it("encodes all bytes", function()
    T.eq(url.encode("\0\1\255"), "%00%01%FF")
  end)
  T.it("encodes unicode bytes", function()
    -- UTF-8 for 'e' with acute: \xC3\xA9
    T.eq(url.encode("\xC3\xA9"), "%C3%A9")
  end)
  T.it("encodes slash", function()
    T.eq(url.encode("/path/to"), "%2Fpath%2Fto")
  end)
  T.it("encodes query special chars", function()
    T.eq(url.encode("a=1&b=2"), "a%3D1%26b%3D2")
  end)
end)

T.describe("url.decode", function()
  T.it("decodes percent-encoded", function()
    T.eq(url.decode("hello%20world"), "hello world")
  end)
  T.it("decodes plus as space", function()
    T.eq(url.decode("hello+world"), "hello world")
  end)
  T.it("decodes empty string", function()
    T.eq(url.decode(""), "")
  end)
  T.it("decodes lowercase hex", function()
    T.eq(url.decode("%c3%a9"), "\xC3\xA9")
  end)
  T.it("decodes uppercase hex", function()
    T.eq(url.decode("%C3%A9"), "\xC3\xA9")
  end)
  T.it("passes through plain text", function()
    T.eq(url.decode("hello"), "hello")
  end)
  T.it("round-trips with encode", function()
    local original = "hello world! /path?q=1&r=2#frag"
    T.eq(url.decode(url.encode(original)), original)
  end)
end)

-- ============================================================
-- Query string parsing
-- ============================================================

T.describe("url.parse_query", function()
  T.it("parses simple params", function()
    local q = url.parse_query("a=1&b=2")
    T.eq(q.a, "1")
    T.eq(q.b, "2")
  end)
  T.it("parses encoded values", function()
    local q = url.parse_query("msg=hello%20world")
    T.eq(q.msg, "hello world")
  end)
  T.it("parses plus as space", function()
    local q = url.parse_query("c=hello+world")
    T.eq(q.c, "hello world")
  end)
  T.it("parses empty value", function()
    local q = url.parse_query("key=")
    T.eq(q.key, "")
  end)
  T.it("parses key without value", function()
    local q = url.parse_query("key")
    T.eq(q.key, "")
  end)
  T.it("parses empty string", function()
    local q = url.parse_query("")
    T.eq(next(q), nil)
  end)
  T.it("parses nil", function()
    local q = url.parse_query(nil)
    T.eq(next(q), nil)
  end)
  T.it("parses semicolon separator", function()
    local q = url.parse_query("a=1;b=2")
    T.eq(q.a, "1")
    T.eq(q.b, "2")
  end)
  T.it("last value wins for duplicate keys", function()
    local q = url.parse_query("a=1&a=2")
    T.eq(q.a, "2")
  end)
  T.it("parses encoded keys", function()
    local q = url.parse_query("hello%20world=yes")
    T.eq(q["hello world"], "yes")
  end)
  T.it("parses multiple params", function()
    local q = url.parse_query("a=1&b=2&c=3&d=4&e=5")
    T.eq(q.a, "1")
    T.eq(q.e, "5")
  end)
end)

T.describe("url.build_query", function()
  T.it("builds simple query", function()
    local qs = url.build_query({ a = "1", b = "2" })
    T.eq(qs, "a=1&b=2")
  end)
  T.it("encodes special characters", function()
    local qs = url.build_query({ msg = "hello world" })
    T.eq(qs, "msg=hello%20world")
  end)
  T.it("builds empty table", function()
    T.eq(url.build_query({}), "")
  end)
  T.it("round-trips with parse_query", function()
    local orig = { x = "10", y = "20" }
    local q = url.parse_query(url.build_query(orig))
    T.eq(q.x, "10")
    T.eq(q.y, "20")
  end)
end)

-- ============================================================
-- URL parsing
-- ============================================================

T.describe("url.parse", function()
  T.it("parses full URL", function()
    local u = url.parse("https://user:pass@example.com:8080/path?q=1&r=2#frag")
    T.eq(u.scheme, "https")
    T.eq(u.userinfo, "user:pass")
    T.eq(u.host, "example.com")
    T.eq(u.port, 8080)
    T.eq(u.path, "/path")
    T.eq(u.query, "q=1&r=2")
    T.eq(u.fragment, "frag")
  end)
  T.it("parses http URL", function()
    local u = url.parse("http://example.com/")
    T.eq(u.scheme, "http")
    T.eq(u.host, "example.com")
    T.eq(u.path, "/")
  end)
  T.it("parses URL without port", function()
    local u = url.parse("https://example.com/path")
    T.eq(u.scheme, "https")
    T.eq(u.host, "example.com")
    T.eq(u.port, nil)
    T.eq(u.path, "/path")
  end)
  T.it("parses URL without path", function()
    local u = url.parse("https://example.com")
    T.eq(u.scheme, "https")
    T.eq(u.host, "example.com")
    T.eq(u.path, "")
  end)
  T.it("parses URL without query", function()
    local u = url.parse("https://example.com/path#frag")
    T.eq(u.query, nil)
    T.eq(u.fragment, "frag")
  end)
  T.it("parses URL without fragment", function()
    local u = url.parse("https://example.com/path?q=1")
    T.eq(u.fragment, nil)
    T.eq(u.query, "q=1")
  end)
  T.it("parses URL with userinfo", function()
    local u = url.parse("ftp://admin@host.com/files")
    T.eq(u.userinfo, "admin")
    T.eq(u.host, "host.com")
  end)
  T.it("parses URL with empty query", function()
    local u = url.parse("http://example.com/?")
    T.eq(u.query, "")
  end)
  T.it("parses URL with empty fragment", function()
    local u = url.parse("http://example.com/#")
    T.eq(u.fragment, "")
  end)
  T.it("lowercases scheme", function()
    local u = url.parse("HTTPS://Example.com")
    T.eq(u.scheme, "https")
  end)
  T.it("parses protocol-relative URL", function()
    local u = url.parse("//example.com/path")
    T.eq(u.scheme, nil)
    T.eq(u.host, "example.com")
    T.eq(u.path, "/path")
  end)
  T.it("parses just a path", function()
    local u = url.parse("/path/to/resource")
    T.eq(u.scheme, nil)
    T.eq(u.host, nil)
    T.eq(u.path, "/path/to/resource")
  end)
  T.it("parses relative path", function()
    local u = url.parse("path/to/resource")
    T.eq(u.scheme, nil)
    T.eq(u.host, nil)
    T.eq(u.path, "path/to/resource")
  end)
  T.it("parses empty string", function()
    local u = url.parse("")
    T.eq(u.scheme, nil)
    T.eq(u.host, nil)
    T.eq(u.path, "")
  end)
  T.it("returns error for non-string", function()
    local u, err = url.parse(123)
    T.eq(u, nil)
    T.ok(err)
  end)
  T.it("parses IPv6 host", function()
    local u = url.parse("http://[::1]:8080/path")
    T.eq(u.host, "[::1]")
    T.eq(u.port, 8080)
    T.eq(u.path, "/path")
  end)
  T.it("parses IPv6 without port", function()
    local u = url.parse("http://[2001:db8::1]/path")
    T.eq(u.host, "[2001:db8::1]")
    T.eq(u.port, nil)
  end)
  T.it("parses data URI", function()
    local u = url.parse("data:text/html,<h1>Hello</h1>")
    T.eq(u.scheme, "data")
    T.eq(u.path, "text/html,<h1>Hello</h1>")
  end)
  T.it("parses mailto URI", function()
    local u = url.parse("mailto:user@example.com")
    T.eq(u.scheme, "mailto")
    T.eq(u.path, "user@example.com")
  end)
  T.it("parses URL with encoded path", function()
    local u = url.parse("http://example.com/path%20with%20spaces")
    T.eq(u.path, "/path%20with%20spaces")
  end)
  T.it("parses URL with multiple query params", function()
    local u = url.parse("http://example.com/?a=1&b=2&c=3")
    T.eq(u.query, "a=1&b=2&c=3")
  end)
  T.it("parses ws URL", function()
    local u = url.parse("ws://localhost:3000/socket")
    T.eq(u.scheme, "ws")
    T.eq(u.host, "localhost")
    T.eq(u.port, 3000)
  end)
  T.it("parses file URL", function()
    local u = url.parse("file:///home/user/file.txt")
    T.eq(u.scheme, "file")
    T.eq(u.host, "")
    T.eq(u.path, "/home/user/file.txt")
  end)
end)

-- ============================================================
-- URL building
-- ============================================================

T.describe("url.build", function()
  T.it("builds full URL", function()
    local s = url.build({
      scheme = "https", userinfo = "user:pass",
      host = "example.com", port = 8080,
      path = "/path", query = "q=1", fragment = "frag"
    })
    T.eq(s, "https://user:pass@example.com:8080/path?q=1#frag")
  end)
  T.it("builds simple URL", function()
    T.eq(url.build({ scheme = "https", host = "example.com", path = "/api", query = "k=v" }),
         "https://example.com/api?k=v")
  end)
  T.it("builds URL without optional parts", function()
    T.eq(url.build({ scheme = "http", host = "localhost" }), "http://localhost")
  end)
  T.it("builds protocol-relative URL", function()
    T.eq(url.build({ host = "example.com", path = "/path" }), "//example.com/path")
  end)
  T.it("builds bare path", function()
    T.eq(url.build({ path = "/just/a/path" }), "/just/a/path")
  end)
  T.it("builds with fragment only", function()
    T.eq(url.build({ path = "", fragment = "top" }), "#top")
  end)
  T.it("round-trips with parse", function()
    local original = "https://user:pass@example.com:8080/path?q=1&r=2#frag"
    local u = url.parse(original)
    T.eq(url.build(u), original)
  end)
  T.it("round-trips http URL", function()
    local original = "http://example.com/"
    T.eq(url.build(url.parse(original)), original)
  end)
  T.it("round-trips complex query", function()
    local original = "https://search.example.com/q?term=lua+jit&page=2&sort=relevance#results"
    T.eq(url.build(url.parse(original)), original)
  end)
end)

-- ============================================================
-- Path join / resolve
-- ============================================================

T.describe("url.join", function()
  T.it("resolves relative path with ..", function()
    T.eq(url.join("https://example.com/api/v1/", "../v2/users"),
         "https://example.com/api/v2/users")
  end)
  T.it("resolves absolute path", function()
    T.eq(url.join("https://example.com/api/v1/", "/v2/users"),
         "https://example.com/v2/users")
  end)
  T.it("resolves with query", function()
    T.eq(url.join("https://example.com/path", "?q=1"),
         "https://example.com/path?q=1")
  end)
  T.it("resolves empty reference", function()
    T.eq(url.join("https://example.com/path?q=1", ""),
         "https://example.com/path?q=1")
  end)
  T.it("resolves with fragment", function()
    T.eq(url.join("https://example.com/path", "#section"),
         "https://example.com/path#section")
  end)
  T.it("resolves full URL override", function()
    T.eq(url.join("https://example.com/path", "http://other.com/new"),
         "http://other.com/new")
  end)
  T.it("resolves sibling path", function()
    T.eq(url.join("https://example.com/a/b/c", "d"),
         "https://example.com/a/b/d")
  end)
  T.it("resolves with double ..", function()
    T.eq(url.join("https://example.com/a/b/c/d", "../../e"),
         "https://example.com/a/e")
  end)
end)

T.describe("url.resolve", function()
  -- RFC 3986 Section 5.4 reference resolution examples
  -- Base: http://a/b/c/d;p?q
  local base = "http://a/b/c/d;p?q"

  T.it("resolves g:h", function()
    T.eq(url.resolve(base, "g:h"), "g:h")
  end)
  T.it("resolves g", function()
    T.eq(url.resolve(base, "g"), "http://a/b/c/g")
  end)
  T.it("resolves ./g", function()
    T.eq(url.resolve(base, "./g"), "http://a/b/c/g")
  end)
  T.it("resolves g/", function()
    T.eq(url.resolve(base, "g/"), "http://a/b/c/g/")
  end)
  T.it("resolves /g", function()
    T.eq(url.resolve(base, "/g"), "http://a/g")
  end)
  T.it("resolves //g", function()
    T.eq(url.resolve(base, "//g"), "http://g")
  end)
  T.it("resolves ?y", function()
    T.eq(url.resolve(base, "?y"), "http://a/b/c/d;p?y")
  end)
  T.it("resolves g?y", function()
    T.eq(url.resolve(base, "g?y"), "http://a/b/c/g?y")
  end)
  T.it("resolves #s", function()
    T.eq(url.resolve(base, "#s"), "http://a/b/c/d;p?q#s")
  end)
  T.it("resolves g#s", function()
    T.eq(url.resolve(base, "g#s"), "http://a/b/c/g#s")
  end)
  T.it("resolves g?y#s", function()
    T.eq(url.resolve(base, "g?y#s"), "http://a/b/c/g?y#s")
  end)
  T.it("resolves ;x", function()
    T.eq(url.resolve(base, ";x"), "http://a/b/c/;x")
  end)
  T.it("resolves g;x", function()
    T.eq(url.resolve(base, "g;x"), "http://a/b/c/g;x")
  end)
  T.it("resolves g;x?y#s", function()
    T.eq(url.resolve(base, "g;x?y#s"), "http://a/b/c/g;x?y#s")
  end)
  T.it("resolves empty string", function()
    T.eq(url.resolve(base, ""), "http://a/b/c/d;p?q")
  end)
  T.it("resolves ../", function()
    T.eq(url.resolve(base, "../"), "http://a/b/")
  end)
  T.it("resolves ../g", function()
    T.eq(url.resolve(base, "../g"), "http://a/b/g")
  end)
  T.it("resolves ../../", function()
    T.eq(url.resolve(base, "../../"), "http://a/")
  end)
  T.it("resolves ../../g", function()
    T.eq(url.resolve(base, "../../g"), "http://a/g")
  end)
end)

-- ============================================================
-- Normalize
-- ============================================================

T.describe("url.normalize", function()
  T.it("lowercases scheme and host", function()
    T.eq(url.normalize("HTTPS://Example.COM/path"), "https://example.com/path")
  end)
  T.it("removes default https port", function()
    T.eq(url.normalize("https://example.com:443/path"), "https://example.com/path")
  end)
  T.it("removes default http port", function()
    T.eq(url.normalize("http://example.com:80/"), "http://example.com/")
  end)
  T.it("keeps non-default port", function()
    T.eq(url.normalize("http://example.com:8080/"), "http://example.com:8080/")
  end)
  T.it("removes dot segments", function()
    T.eq(url.normalize("https://example.com/a/../b/./c"), "https://example.com/b/c")
  end)
  T.it("normalizes complex dot segments", function()
    T.eq(url.normalize("https://Example.COM:443/a/../b/./c"), "https://example.com/b/c")
  end)
  T.it("adds slash for authority without path", function()
    T.eq(url.normalize("http://example.com"), "http://example.com/")
  end)
  T.it("decodes unreserved percent-encoded chars in path", function()
    T.eq(url.normalize("http://example.com/%61%62%63"), "http://example.com/abc")
  end)
  T.it("preserves reserved percent-encoded chars", function()
    T.eq(url.normalize("http://example.com/a%2Fb"), "http://example.com/a%2Fb")
  end)
  T.it("uppercases hex in percent-encoding", function()
    T.eq(url.normalize("http://example.com/a%2fb"), "http://example.com/a%2Fb")
  end)
end)

-- ============================================================
-- Edge cases
-- ============================================================

T.describe("url edge cases", function()
  T.it("handles URL with only scheme", function()
    local u = url.parse("http:")
    T.eq(u.scheme, "http")
    T.eq(u.path, "")
  end)
  T.it("handles URL with only query", function()
    local u = url.parse("?query=1")
    T.eq(u.query, "query=1")
    T.eq(u.path, "")
  end)
  T.it("handles URL with only fragment", function()
    local u = url.parse("#fragment")
    T.eq(u.fragment, "fragment")
    T.eq(u.path, "")
  end)
  T.it("handles consecutive slashes in path", function()
    local u = url.parse("http://example.com//a//b")
    T.eq(u.path, "//a//b")
  end)
  T.it("handles port 0", function()
    local u = url.parse("http://example.com:0/path")
    T.eq(u.port, 0)
  end)
  T.it("handles large port", function()
    local u = url.parse("http://example.com:65535/path")
    T.eq(u.port, 65535)
  end)
  T.it("parses URL with @ in path", function()
    local u = url.parse("http://example.com/user@host")
    T.eq(u.host, "example.com")
    T.eq(u.path, "/user@host")
  end)
  T.it("preserves query encoding", function()
    local u = url.parse("http://example.com/?q=hello%20world")
    T.eq(u.query, "q=hello%20world")
  end)
  T.it("handles very long URL", function()
    local long_path = "/" .. string.rep("a", 10000)
    local u = url.parse("http://example.com" .. long_path)
    T.eq(u.path, long_path)
  end)
end)

-- ============================================================
-- Codec aliases
-- ============================================================

T.describe("url codec aliases", function()
  T.it("string_to_url is parse", function()
    T.eq(url.string_to_url, url.parse)
  end)
  T.it("url_to_string is build", function()
    T.eq(url.url_to_string, url.build)
  end)
end)
