-- lib/rational/rational_test.lua

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local R = require("lib.rational")

T.describe("rational", function()

  T.describe("construction", function()
    T.it("integer shorthand", function()
      local r = R.new(3)
      T.eq(r.p, 3)
      T.eq(r.q, 1)
    end)

    T.it("fraction", function()
      local r = R.new(2, 4)
      T.eq(r.p, 1)
      T.eq(r.q, 2)
    end)

    T.it("already reduced", function()
      local r = R.new(3, 7)
      T.eq(r.p, 3)
      T.eq(r.q, 7)
    end)

    T.it("negative numerator", function()
      local r = R.new(-3, 4)
      T.eq(r.p, -3)
      T.eq(r.q, 4)
    end)

    T.it("negative denominator normalized to positive", function()
      local r = R.new(3, -4)
      T.eq(r.p, -3)
      T.eq(r.q, 4)
    end)

    T.it("both negative", function()
      local r = R.new(-3, -4)
      T.eq(r.p, 3)
      T.eq(r.q, 4)
    end)

    T.it("zero numerator", function()
      local r = R.new(0, 5)
      T.eq(r.p, 0)
      T.eq(r.q, 1)
    end)

    T.it("copy from rational", function()
      local a = R.new(2, 3)
      local b = R.new(a)
      T.eq(b.p, 2)
      T.eq(b.q, 3)
    end)

    T.it("error: zero denominator", function()
      local r, err = R.new(1, 0)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)

    T.it("error: non-integer numerator", function()
      local r, err = R.new(1.5, 2)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)

    T.it("error: non-integer denominator", function()
      local r, err = R.new(1, 2.5)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
  end)

  T.describe("is_integer", function()
    T.it("whole number", function()
      T.ok(R.new(6, 2):is_integer())
    end)

    T.it("fraction", function()
      T.fail(R.new(1, 3):is_integer())
    end)
  end)

  T.describe("to_string", function()
    T.it("integer", function()
      T.eq(R.to_string(R.new(4)), "4")
    end)

    T.it("fraction", function()
      T.eq(R.to_string(R.new(3, 4)), "3/4")
    end)

    T.it("negative fraction", function()
      T.eq(R.to_string(R.new(-3, 4)), "-3/4")
    end)

    T.it("via metamethod", function()
      T.eq(tostring(R.new(1, 3)), "1/3")
    end)
  end)

  T.describe("to_number", function()
    T.it("exact", function()
      T.eq(R.to_number(R.new(1, 4)), 0.25)
    end)

    T.it("integer", function()
      T.eq(R.to_number(R.new(7)), 7)
    end)
  end)

  T.describe("add", function()
    T.it("same denominator", function()
      local r = R.add(R.new(1, 4), R.new(3, 4))
      T.eq(r.p, 1)
      T.eq(r.q, 1)
    end)

    T.it("different denominators", function()
      local r = R.add(R.new(1, 3), R.new(1, 6))
      T.eq(r.p, 1)
      T.eq(r.q, 2)
    end)

    T.it("with integer", function()
      local r = R.add(R.new(1, 2), 1)
      T.eq(r.p, 3)
      T.eq(r.q, 2)
    end)

    T.it("metamethod", function()
      local r = R.new(1, 4) + R.new(1, 4)
      T.eq(r.p, 1)
      T.eq(r.q, 2)
    end)
  end)

  T.describe("sub", function()
    T.it("basic", function()
      local r = R.sub(R.new(3, 4), R.new(1, 4))
      T.eq(r.p, 1)
      T.eq(r.q, 2)
    end)

    T.it("result zero", function()
      local r = R.sub(R.new(1, 3), R.new(1, 3))
      T.eq(r.p, 0)
      T.eq(r.q, 1)
    end)

    T.it("metamethod", function()
      local r = R.new(1, 1) - R.new(1, 3)
      T.eq(r.p, 2)
      T.eq(r.q, 3)
    end)
  end)

  T.describe("mul", function()
    T.it("basic", function()
      local r = R.mul(R.new(2, 3), R.new(3, 4))
      T.eq(r.p, 1)
      T.eq(r.q, 2)
    end)

    T.it("by integer", function()
      local r = R.mul(R.new(1, 3), 3)
      T.eq(r.p, 1)
      T.eq(r.q, 1)
    end)

    T.it("metamethod", function()
      local r = R.new(2, 5) * R.new(5, 2)
      T.eq(r.p, 1)
      T.eq(r.q, 1)
    end)
  end)

  T.describe("div", function()
    T.it("basic", function()
      local r = R.div(R.new(1, 2), R.new(1, 4))
      T.eq(r.p, 2)
      T.eq(r.q, 1)
    end)

    T.it("by integer", function()
      local r = R.div(R.new(3, 4), 3)
      T.eq(r.p, 1)
      T.eq(r.q, 4)
    end)

    T.it("error: divide by zero rational", function()
      local r, err = R.div(R.new(1, 2), R.new(0))
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)

    T.it("error: divide by zero integer", function()
      local r, err = R.div(R.new(1, 2), 0)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)

    T.it("metamethod", function()
      local r = R.new(3, 4) / R.new(3, 8)
      T.eq(r.p, 2)
      T.eq(r.q, 1)
    end)
  end)

  T.describe("neg", function()
    T.it("positive becomes negative", function()
      local r = R.neg(R.new(3, 4))
      T.eq(r.p, -3)
      T.eq(r.q, 4)
    end)

    T.it("negative becomes positive", function()
      local r = R.neg(R.new(-3, 4))
      T.eq(r.p, 3)
      T.eq(r.q, 4)
    end)

    T.it("metamethod unary minus", function()
      local r = -R.new(2, 5)
      T.eq(r.p, -2)
      T.eq(r.q, 5)
    end)
  end)

  T.describe("abs", function()
    T.it("positive unchanged", function()
      local r = R.abs(R.new(3, 4))
      T.eq(r.p, 3)
      T.eq(r.q, 4)
    end)

    T.it("negative flipped", function()
      local r = R.abs(R.new(-5, 7))
      T.eq(r.p, 5)
      T.eq(r.q, 7)
    end)
  end)

  T.describe("inv", function()
    T.it("basic", function()
      local r = R.inv(R.new(3, 4))
      T.eq(r.p, 4)
      T.eq(r.q, 3)
    end)

    T.it("integer inverted", function()
      local r = R.inv(R.new(5))
      T.eq(r.p, 1)
      T.eq(r.q, 5)
    end)

    T.it("negative inv", function()
      local r = R.inv(R.new(-2, 3))
      T.eq(r.p, -3)
      T.eq(r.q, 2)
    end)

    T.it("error: inv of zero", function()
      local r, err = R.inv(R.new(0))
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
  end)

  T.describe("pow", function()
    T.it("positive exponent", function()
      local r = R.pow(R.new(2, 3), 3)
      T.eq(r.p, 8)
      T.eq(r.q, 27)
    end)

    T.it("exponent zero", function()
      local r = R.pow(R.new(7, 11), 0)
      T.eq(r.p, 1)
      T.eq(r.q, 1)
    end)

    T.it("negative exponent", function()
      local r = R.pow(R.new(2, 3), -2)
      T.eq(r.p, 9)
      T.eq(r.q, 4)
    end)

    T.it("exponent 1", function()
      local r = R.pow(R.new(5, 7), 1)
      T.eq(r.p, 5)
      T.eq(r.q, 7)
    end)

    T.it("error: zero to negative power", function()
      local r, err = R.pow(R.new(0), -1)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)

    T.it("error: non-integer exponent", function()
      local r, err = R.pow(R.new(2, 3), 1.5)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
  end)

  T.describe("eq", function()
    T.it("equal rationals", function()
      T.ok(R.eq(R.new(1, 2), R.new(2, 4)))
    end)

    T.it("unequal rationals", function()
      T.fail(R.eq(R.new(1, 3), R.new(1, 2)))
    end)

    T.it("metamethod ==", function()
      T.ok(R.new(3, 6) == R.new(1, 2))
    end)

    T.it("metamethod ~= (not equal)", function()
      T.ok(R.new(1, 3) ~= R.new(1, 2))
    end)
  end)

  T.describe("lt", function()
    T.it("less than", function()
      T.ok(R.lt(R.new(1, 3), R.new(1, 2)))
    end)

    T.it("not less when equal", function()
      T.fail(R.lt(R.new(1, 2), R.new(2, 4)))
    end)

    T.it("not less when greater", function()
      T.fail(R.lt(R.new(3, 4), R.new(1, 4)))
    end)

    T.it("metamethod <", function()
      T.ok(R.new(1, 4) < R.new(1, 3))
    end)
  end)

  T.describe("le", function()
    T.it("less than", function()
      T.ok(R.le(R.new(1, 3), R.new(1, 2)))
    end)

    T.it("equal", function()
      T.ok(R.le(R.new(1, 2), R.new(2, 4)))
    end)

    T.it("not less-equal when greater", function()
      T.fail(R.le(R.new(3, 4), R.new(1, 4)))
    end)

    T.it("metamethod <=", function()
      T.ok(R.new(1, 3) <= R.new(1, 3))
    end)
  end)

  T.describe("from_float", function()
    T.it("exact half", function()
      local r = R.from_float(0.5)
      T.eq(r.p, 1)
      T.eq(r.q, 2)
    end)

    T.it("pi approx with small max_denom", function()
      local r = R.from_float(math.pi, 10)
      -- best rational approx of pi with denom <= 10 is 22/7
      T.eq(r.p, 22)
      T.eq(r.q, 7)
    end)

    T.it("integer value", function()
      local r = R.from_float(3.0)
      T.eq(r.p, 3)
      T.eq(r.q, 1)
    end)

    T.it("negative", function()
      local r = R.from_float(-0.25)
      T.eq(r.p, -1)
      T.eq(r.q, 4)
    end)
  end)

  T.describe("method syntax on object", function()
    T.it("add via colon", function()
      local r = R.new(1, 3):add(R.new(1, 3))
      T.eq(r.p, 2)
      T.eq(r.q, 3)
    end)

    T.it("to_string via colon", function()
      T.eq(R.new(3, 5):to_string(), "3/5")
    end)

    T.it("is_integer via colon", function()
      T.ok(R.new(10, 2):is_integer())
      T.fail(R.new(10, 3):is_integer())
    end)
  end)

  T.describe("chained arithmetic", function()
    T.it("(1/2 + 1/3) * 6 = 5", function()
      local r = (R.new(1, 2) + R.new(1, 3)) * R.new(6)
      T.eq(r.p, 5)
      T.eq(r.q, 1)
    end)

    T.it("(1/2)^3 / (1/8) = 1", function()
      local r = R.pow(R.new(1, 2), 3) / R.new(1, 8)
      T.eq(r.p, 1)
      T.eq(r.q, 1)
    end)
  end)

end)
