if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local bencode = require("lib.bencode")

T.describe("bencode", function()

	T.describe("encode integers", function()
		T.it("encodes zero", function()
			T.eq(bencode.encode(0), "i0e")
		end)
		T.it("encodes positive integer", function()
			T.eq(bencode.encode(42), "i42e")
		end)
		T.it("encodes negative integer", function()
			T.eq(bencode.encode(-7), "i-7e")
		end)
		T.it("encodes large integer", function()
			T.eq(bencode.encode(1000000), "i1000000e")
		end)
		T.it("encodes large negative integer", function()
			T.eq(bencode.encode(-999999), "i-999999e")
		end)
		T.it("rejects NaN", function()
			local val, err = bencode.encode(0/0)
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects infinity", function()
			local val, err = bencode.encode(1/0)
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects negative infinity", function()
			local val, err = bencode.encode(-1/0)
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects non-integer number", function()
			local val, err = bencode.encode(3.14)
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("encode strings", function()
		T.it("encodes empty string", function()
			T.eq(bencode.encode(""), "0:")
		end)
		T.it("encodes short string", function()
			T.eq(bencode.encode("spam"), "4:spam")
		end)
		T.it("encodes string with spaces", function()
			T.eq(bencode.encode("hello world"), "11:hello world")
		end)
		T.it("encodes binary data", function()
			local bin = "\0\1\2\255"
			T.eq(bencode.encode(bin), "4:" .. bin)
		end)
		T.it("encodes single character", function()
			T.eq(bencode.encode("a"), "1:a")
		end)
	end)

	T.describe("encode lists", function()
		T.it("encodes empty list", function()
			T.eq(bencode.encode({}), "le")
		end)
		T.it("encodes list of integers", function()
			T.eq(bencode.encode({1, 2, 3}), "li1ei2ei3ee")
		end)
		T.it("encodes list of strings", function()
			T.eq(bencode.encode({"spam", "eggs"}), "l4:spam4:eggse")
		end)
		T.it("encodes mixed list", function()
			T.eq(bencode.encode({"hello", 42}), "l5:helloi42ee")
		end)
		T.it("encodes nested list", function()
			T.eq(bencode.encode({{1, 2}, {3, 4}}), "lli1ei2eeli3ei4eee")
		end)
	end)

	T.describe("encode dictionaries", function()
		T.it("encodes simple dict", function()
			T.eq(bencode.encode({cow = "moo", spam = "eggs"}), "d3:cow3:moo4:spam4:eggse")
		end)
		T.it("encodes dict with integer values", function()
			T.eq(bencode.encode({age = 25}), "d3:agei25ee")
		end)
		T.it("sorts keys", function()
			-- keys z, a, m should be sorted to a, m, z
			T.eq(bencode.encode({z = 1, a = 2, m = 3}), "d1:ai2e1:mi3e1:zi1ee")
		end)
		T.it("encodes dict with list value", function()
			T.eq(bencode.encode({list = {1, 2}}), "d4:listli1ei2eee")
		end)
		T.it("encodes nested dict", function()
			T.eq(bencode.encode({a = {b = 1}}), "d1:ad1:bi1eee")
		end)
		T.it("rejects non-string keys", function()
			local val, err = bencode.encode({[1] = "x", [2] = "y", [3] = "z", extra = "w"})
			-- has both integer and string keys, not a pure list
			-- the integer keys should cause an error
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("encode errors", function()
		T.it("rejects nil", function()
			local val, err = bencode.encode(nil)
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects boolean", function()
			local val, err = bencode.encode(true)
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("decode integers", function()
		T.it("decodes zero", function()
			T.eq(bencode.decode("i0e"), 0)
		end)
		T.it("decodes positive integer", function()
			T.eq(bencode.decode("i42e"), 42)
		end)
		T.it("decodes negative integer", function()
			T.eq(bencode.decode("i-7e"), -7)
		end)
		T.it("decodes large integer", function()
			T.eq(bencode.decode("i1000000e"), 1000000)
		end)
		T.it("rejects leading zeros", function()
			local val, err = bencode.decode("i03e")
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects negative zero", function()
			local val, err = bencode.decode("i-0e")
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects empty integer", function()
			local val, err = bencode.decode("ie")
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects unterminated integer", function()
			local val, err = bencode.decode("i42")
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("decode strings", function()
		T.it("decodes empty string", function()
			T.eq(bencode.decode("0:"), "")
		end)
		T.it("decodes short string", function()
			T.eq(bencode.decode("4:spam"), "spam")
		end)
		T.it("decodes binary data", function()
			T.eq(bencode.decode("4:\0\1\2\255"), "\0\1\2\255")
		end)
		T.it("rejects truncated string", function()
			local val, err = bencode.decode("10:short")
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects missing colon", function()
			local val, err = bencode.decode("4spam")
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("decode lists", function()
		T.it("decodes empty list", function()
			local val = bencode.decode("le")
			T.ok(val)
			T.eq(#val, 0)
		end)
		T.it("decodes list of integers", function()
			local val = bencode.decode("li1ei2ei3ee")
			T.eq(val[1], 1)
			T.eq(val[2], 2)
			T.eq(val[3], 3)
			T.eq(#val, 3)
		end)
		T.it("decodes list of strings", function()
			local val = bencode.decode("l4:spam4:eggse")
			T.eq(val[1], "spam")
			T.eq(val[2], "eggs")
		end)
		T.it("rejects unterminated list", function()
			local val, err = bencode.decode("li1e")
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("decode dictionaries", function()
		T.it("decodes simple dict", function()
			local val = bencode.decode("d3:cow3:moo4:spam4:eggse")
			T.eq(val.cow, "moo")
			T.eq(val.spam, "eggs")
		end)
		T.it("decodes dict with integer values", function()
			local val = bencode.decode("d3:agei25ee")
			T.eq(val.age, 25)
		end)
		T.it("decodes nested dict", function()
			local val = bencode.decode("d1:ad1:bi1eee")
			T.eq(val.a.b, 1)
		end)
		T.it("rejects unsorted keys", function()
			local val, err = bencode.decode("d4:spam4:eggs3:cow3:mooe")
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects unterminated dict", function()
			local val, err = bencode.decode("d3:cow3:moo")
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("decode errors", function()
		T.it("rejects empty input", function()
			local val, err = bencode.decode("")
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects non-string input", function()
			local val, err = bencode.decode(42)
			T.eq(val, nil)
			T.ok(err)
		end)
		T.it("rejects invalid start byte", function()
			local val, err = bencode.decode("x")
			T.eq(val, nil)
			T.ok(err)
		end)
	end)

	T.describe("roundtrip", function()
		T.it("roundtrips integer", function()
			T.eq(bencode.decode(bencode.encode(42)), 42)
		end)
		T.it("roundtrips string", function()
			T.eq(bencode.decode(bencode.encode("hello")), "hello")
		end)
		T.it("roundtrips empty string", function()
			T.eq(bencode.decode(bencode.encode("")), "")
		end)
		T.it("roundtrips complex structure", function()
			local original = {
				announce = "http://tracker.example.com/announce",
				info = {
					length = 12345,
					name = "test.txt",
					pieces = "abcdefghijklmnopqrst",
				},
			}
			local encoded = bencode.encode(original)
			T.ok(encoded)
			local decoded = bencode.decode(encoded)
			T.eq(decoded.announce, original.announce)
			T.eq(decoded.info.length, original.info.length)
			T.eq(decoded.info.name, original.info.name)
			T.eq(decoded.info.pieces, original.info.pieces)
		end)
		T.it("roundtrips nested list", function()
			local encoded = bencode.encode({{1, 2}, {3}})
			local decoded = bencode.decode(encoded)
			T.eq(decoded[1][1], 1)
			T.eq(decoded[1][2], 2)
			T.eq(decoded[2][1], 3)
		end)
	end)

	T.describe("aliases", function()
		T.it("string_to_table is decode", function()
			T.eq(bencode.string_to_table, bencode.decode)
		end)
		T.it("table_to_string is encode", function()
			T.eq(bencode.table_to_string, bencode.encode)
		end)
	end)
end)
