-- lib/platform/runtime.lua
-- Generate browser-side JavaScript runtime for cap bridging.
--
-- API:
--   runtime.generate(caps) -> js_string
--
-- Introspects a caps table to discover cap names and their methods, then
-- generates an ES module that exports a `caps` object. Each method is an
-- async function that calls POST /api/cap via fetch().
--
-- Browser-side convention:
--   const [result, error] = await caps.llm.call(messages);
--   // result is the value on success (may be null)
--   // error is the error string on failure (undefined on success)
--
-- The generated module exports { caps }.

local M = {}

-- Collect cap names and method names from a caps table.
-- Returns { cap_name = { method_name, ... }, ... } (sorted for determinism).
--: ({ [string]: { [string]: (...) -> ... } }) -> { [string]: string[] }
local function introspect(caps)
	local result = {}
	local cap_names = {}
	for name, cap in pairs(caps) do
		if type(cap) == "table" then
			cap_names[#cap_names + 1] = name
			local methods = {}
			for mname, fn in pairs(cap) do
				if type(fn) == "function" then
					methods[#methods + 1] = mname
				end
			end
			table.sort(methods)
			result[name] = methods
		end
	end
	table.sort(cap_names)
	return result, cap_names
end

-- generate(caps) -> js_string
-- Produces an ES module with async cap proxy methods.
--: ({ [string]: { [string]: (...) -> ... } }) -> string
function M.generate(caps)
	local schema, cap_names = introspect(caps)

	local lines = {}
	local function emit(s)
		lines[#lines + 1] = s
	end

	emit("// Generated by lib/platform/runtime.lua — do not edit")
	emit("")
	emit("async function rpc(cap, method, args) {")
	emit("  const res = await fetch('/api/cap', {")
	emit("    method: 'POST',")
	emit("    headers: { 'Content-Type': 'application/json' },")
	emit("    body: JSON.stringify({ cap, method, args }),")
	emit("  });")
	emit("  const data = await res.json();")
	emit("  if (data.error !== undefined) return [null, data.error];")
	emit("  return [data.result];")
	emit("}")
	emit("")

	emit("export const caps = {")
	for i, cap_name in ipairs(cap_names) do
		local methods = schema[cap_name]
		emit("  " .. cap_name .. ": {")
		for j, mname in ipairs(methods) do
			local comma = (j < #methods) and "," or ""
			emit("    " .. mname .. ": (...args) => rpc('" .. cap_name .. "', '" .. mname .. "', args)" .. comma)
		end
		local cap_comma = (i < #cap_names) and "," or ""
		emit("  }" .. cap_comma)
	end
	emit("};")

	return table.concat(lines, "\n") .. "\n"
end

return M
