if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T   = require("lib.test.assert")
local crc = require("lib.hash.crc32")

T.describe("crc32 – standard test vectors", function()
	T.it("empty string → 0x00000000", function()
		T.eq(crc.crc32(""), 0x00000000)
	end)
	T.it('"123456789" → 0xCBF43926 (ISO-HDLC)', function()
		T.eq(crc.crc32("123456789"), 0xCBF43926)
	end)
	T.it('"a" → 0xE8B7BE43', function()
		T.eq(crc.crc32("a"), 0xE8B7BE43)
	end)
	T.it('"abc" → 0x352441C2', function()
		T.eq(crc.crc32("abc"), 0x352441C2)
	end)
	T.it('"message digest" → 0x20159D7F', function()
		T.eq(crc.crc32("message digest"), 0x20159D7F)
	end)
	T.it('"abcdefghijklmnopqrstuvwxyz" → 0x4C2750BD', function()
		T.eq(crc.crc32("abcdefghijklmnopqrstuvwxyz"), 0x4C2750BD)
	end)
end)

T.describe("crc32 – single byte inputs", function()
	T.it('"\\0" is unsigned', function()
		local v = crc.crc32("\0")
		T.ok(v >= 0, "must be >= 0")
		T.ok(v <= 4294967295, "must be <= 0xFFFFFFFF")
	end)
	T.it('"\\xff"', function()
		local v = crc.crc32("\255")
		T.ok(v >= 0)
		T.ok(v <= 4294967295)
	end)
end)

T.describe("crc32 – seed / chaining", function()
	T.it("seed=0 is the default", function()
		T.eq(crc.crc32("abc", 0), crc.crc32("abc"))
	end)
	T.it("chaining matches concatenation: crc32(b, crc32(a)) == crc32(a..b)", function()
		local a, b = "hello, ", "world"
		T.eq(crc.crc32(b, crc.crc32(a)), crc.crc32(a .. b))
	end)
	T.it("three-part chain", function()
		local p1, p2, p3 = "foo", "bar", "baz"
		local expected = crc.crc32(p1 .. p2 .. p3)
		local chained  = crc.crc32(p3, crc.crc32(p2, crc.crc32(p1)))
		T.eq(chained, expected)
	end)
	T.it("seeded empty string equals seed unsigned", function()
		-- crc32("", s) should return s (no bytes processed → final XOR undoes init XOR)
		-- i.e. bxor(bxor(s, 0xFFFFFFFF), 0xFFFFFFFF) = s, then unsigned
		local s = 0xDEADBEEF
		T.eq(crc.crc32("", s), s)
	end)
end)

T.describe("crc32 – output properties", function()
	T.it("returns a number", function()
		T.ok(type(crc.crc32("test")) == "number")
	end)
	T.it("always >= 0", function()
		T.ok(crc.crc32("") >= 0)
		T.ok(crc.crc32("123456789") >= 0)
		T.ok(crc.crc32("abcdefghijklmnopqrstuvwxyz") >= 0)
		T.ok(crc.crc32("\255\255\255\255") >= 0)
	end)
	T.it("always <= 0xFFFFFFFF", function()
		T.ok(crc.crc32("") <= 0xFFFFFFFF)
		T.ok(crc.crc32("123456789") <= 0xFFFFFFFF)
	end)
end)

T.describe("crc32_hex", function()
	T.it("empty string → '00000000'", function()
		T.eq(crc.crc32_hex(""), "00000000")
	end)
	T.it('"123456789" → "cbf43926"', function()
		T.eq(crc.crc32_hex("123456789"), "cbf43926")
	end)
	T.it('"abc" → "352441c2"', function()
		T.eq(crc.crc32_hex("abc"), "352441c2")
	end)
	T.it("always 8 characters", function()
		T.eq(#crc.crc32_hex(""), 8)
		T.eq(#crc.crc32_hex("a"), 8)
		T.eq(#crc.crc32_hex("123456789"), 8)
	end)
	T.it("lowercase hex only", function()
		local h = crc.crc32_hex("123456789")
		T.ok(h:match("^[0-9a-f]+$") ~= nil, "must be lowercase hex")
	end)
	T.it("matches numeric result", function()
		local n = crc.crc32("abc")
		local h = crc.crc32_hex("abc")
		T.eq(tonumber(h, 16), n)
	end)
end)

T.describe("streaming hasher – basic", function()
	T.it("whole string matches one-shot", function()
		local h = crc.new()
		h:update("123456789")
		T.eq(h:digest(), crc.crc32("123456789"))
	end)
	T.it("byte-by-byte matches one-shot", function()
		local s = "abcdefghijklmnopqrstuvwxyz"
		local h = crc.new()
		for i = 1, #s do h:update(s:sub(i, i)) end
		T.eq(h:digest(), crc.crc32(s))
	end)
	T.it("chunk streaming matches one-shot", function()
		local h = crc.new()
		h:update("hello, ")
		h:update("world")
		T.eq(h:digest(), crc.crc32("hello, world"))
	end)
	T.it("empty update has no effect", function()
		local h = crc.new()
		h:update("")
		h:update("abc")
		h:update("")
		T.eq(h:digest(), crc.crc32("abc"))
	end)
end)

T.describe("streaming hasher – hex()", function()
	T.it("hex() matches crc32_hex one-shot", function()
		local h = crc.new()
		h:update("123456789")
		T.eq(h:hex(), crc.crc32_hex("123456789"))
	end)
	T.it("hex() is 8 chars", function()
		local h = crc.new()
		h:update("abc")
		T.eq(#h:hex(), 8)
	end)
end)

T.describe("streaming hasher – reset()", function()
	T.it("reset() restores to fresh state", function()
		local h = crc.new()
		h:update("abc")
		h:reset()
		h:update("123456789")
		T.eq(h:digest(), crc.crc32("123456789"))
	end)
	T.it("reset(seed) with explicit seed", function()
		local h = crc.new()
		h:update("abc")
		h:reset(0)
		h:update("abc")
		T.eq(h:digest(), crc.crc32("abc"))
	end)
	T.it("new hasher with seed matches seeded one-shot", function()
		local prior = crc.crc32("hello, ")
		local h = crc.new(prior)
		h:update("world")
		T.eq(h:digest(), crc.crc32("hello, world"))
	end)
end)

T.describe("M._tier", function()
	T.it('_tier is "pure"', function()
		T.eq(crc._tier, "pure")
	end)
end)
