-- lib/type/static/stdlib_types.lua
-- Lua 5.1 / LuaJIT standard library type declarations.
-- Loaded via pkg.lua typecheck.globals (not hardcoded in prelude).
-- New globals use --:: declare name = type.
-- Library tables use --:: augment name { ... } (merge into existing primitive).
-- Type aliases (for primitive meta types) use --:: name = type.

---------------------------------------------------------------------------
-- Global functions
---------------------------------------------------------------------------

--:: declare print = (...unknown) -> ()
--:: declare tostring = (val: unknown) -> string
--:: declare tonumber = (val: unknown, base: integer | nil) -> number | nil
--:: declare type = (val: unknown) -> string
--:: declare error = (msg: unknown, level: integer | nil) -> never
--:: declare assert = <T>(val: T, ...unknown) -> T
--:: PcallReturn<F> = match F { (...%P) -> %R => (true, ...R) | (false, string) }
--:: declare pcall = <F: (...P) -> R, P, R>(f: F, ...P) -> ...(PcallReturn<F>)
--:: declare xpcall = <F: (...P) -> R, P, R>(f: F, handler: (string) -> string, ...P) -> ...(PcallReturn<F>)
--:: declare require = <T: string>(module: T) -> $Require<T>
--:: declare select = (("#") -> integer) & ((integer, ...unknown) -> unknown)
--:: declare rawget = <T>(t: T, k: unknown) -> Values<T> | nil
--:: declare rawset = <T>(t: T, k: unknown, v: unknown) -> T
--:: declare rawequal = (a: unknown, b: unknown) -> boolean
--:: declare rawlen = (t: string | { [integer]: unknown, ... }) -> integer
--:: declare unpack = <V>(t: { [integer]: V, ... }, i: integer | nil, j: integer | nil) -> ...(V)
--:: declare pairs = <T>(t: T) -> ...(PairsReturn<T>)
--:: declare ipairs = <T>(t: T) -> ...(IpairsReturn<T>)

--:: PairsReturn<T>  = match T { { ...[%K]: %V } => (K, V) }
--:: IpairsReturn<T> = match T { { ...[%K]: %V } => match K { number => (integer, V), _ => never } }
--:: Keys<T>         = match T { { ...[%K]: %V } => K }
--:: Values<T>       = match T { { ...[%K]: %V } => V }
--:: Open<T>         = match T { { ...%Rest } => { ...Rest, ... } }
--:: Closed<T>       = match T { { ...%Rest } => { ...Rest } }
--:: declare next = <T>(t: T, k: Keys<T> | nil) -> (Keys<T> | nil, Values<T> | nil)
--:: declare setmetatable = <T, MT>(t: T, mt: MT) -> T & MT & { #...MT }
--:: MetaOf<T> = match T { { #...%M } => M, _ => nil }
--:: declare getmetatable = <T>(t: T) -> MetaOf<T>
--:: declare collectgarbage = (opt: string | nil, arg: number | nil) -> number | boolean
--:: declare gcinfo = () -> integer
--:: declare dofile = (filename: string | nil) -> unknown
--:: declare loadfile = (filename: string | nil) -> (((...never) -> unknown) | nil, string | nil)
--:: declare loadstring = (s: string, chunkname: string | nil) -> (((...never) -> unknown) | nil, string | nil)
--:: declare load = (chunk: string | (() -> string | nil), chunkname: string | nil, mode: string | nil, env: { [string]: unknown, ... } | nil) -> (((...never) -> unknown) | nil, string | nil)
--:: declare newproxy = (mt: boolean | { [string]: unknown, ... } | nil) -> unknown
--:: declare rawprint = (s: string) -> ()
--:: declare _VERSION = string
--:: Ctype<T> = $Opaque<T> & ((...unknown) -> T)
--:: Ptr<T> = T & { [0]: T }
--:: Arr<T> = { [integer]: T, ... }
--:: CTypeMap = {
--::   int8_t: integer,  uint8_t: integer,
--::   int16_t: integer, uint16_t: integer,
--::   int32_t: integer, uint32_t: integer,
--::   int64_t: integer, uint64_t: integer,
--::   char: integer,    short: integer,
--::   int: integer,     long: integer,
--::   float: number,    double: number,
--::   bool: boolean,
--::   ...
--:: }
--:: module "ffi": {
--::   cdef:     (string) -> nil,
--::   new:      (<T>(ct: Ctype<T>, init: T | nil) -> T) & (<S: Keys<CTypeMap>>(ct: S, init: CTypeMap[S] | nil) -> CTypeMap[S]) & ((ct: string, count: integer, init: unknown | nil) -> cdata) & ((ct: string, init: unknown | nil) -> cdata),
--::   cast:     (<T, U>(ct: Ctype<T>, obj: U) -> T) & (<S: Keys<CTypeMap>, U>(ct: S, obj: U) -> CTypeMap[S]) & ((ct: string, obj: unknown) -> cdata),
--::   sizeof:   (ct: string | Ctype<unknown>) -> integer,
--::   typeof:   (<T>(ct: Ctype<T>) -> Ctype<T>) & (<S: Keys<CTypeMap>>(ct: S) -> Ctype<CTypeMap[S]>),
--::   copy:     <T, U>(dst: Ptr<T>, src: Ptr<U>, n: integer) -> nil,
--::   fill:     <T>(dst: Ptr<T>, n: integer, c: integer | nil) -> nil,
--::   string:   (ptr: Ptr<integer>, len: integer | nil) -> string,
--::   load:     (name: string, global: boolean | nil) -> $FfiC,
--::   gc:       <T>(cdata: T, finalizer: ((T) -> ()) | nil) -> T,
--::   metatype: <T>(ct: Ctype<T>, metatable: { [string]: unknown, ... }) -> Ctype<T>,
--::   istype:   (ct: string | Ctype<unknown>, obj: unknown) -> boolean,
--::   alignof:  (ct: string | Ctype<unknown>) -> integer,
--::   offsetof: (ct: string | Ctype<unknown>, field: string) -> integer,
--::   abi:      (param: string) -> boolean,
--::   errno:    (newerr: integer | nil) -> integer,
--::   C:        $FfiC,
--::   ...
--:: }
-- LuaJIT's bit module operates on 32-bit integers. While the runtime accepts
-- any number (coercing via tobit() semantics), typing the inputs as `integer`
-- prevents silent precision loss from float inputs and — critically —
-- propagates integer inference into unannotated parameters that flow into bit
-- ops. `tobit` and `tohex` remain `number` because they are the documented
-- coercion entry points. The return type is a signed 32-bit integer per
-- https://bitop.luajit.org/api.html.
--:: BitLib = {
--::   tobit:   (x: number) -> integer,
--::   tohex:   (x: number, n: integer | nil) -> string,
--::   bnot:    (x: integer) -> integer,
--::   band:    (x: integer, ...integer) -> integer,
--::   bor:     (x: integer, ...integer) -> integer,
--::   bxor:    (x: integer, ...integer) -> integer,
--::   lshift:  (x: integer, n: integer) -> integer,
--::   rshift:  (x: integer, n: integer) -> integer,
--::   arshift: (x: integer, n: integer) -> integer,
--::   bswap:   (x: integer) -> integer,
--::   rol:     (x: integer, n: integer) -> integer,
--::   ror:     (x: integer, n: integer) -> integer
--:: }
--:: module "bit": BitLib
--:: declare bit = BitLib
--:: declare _G = $GlobalScope
--:: declare package = { path: string, cpath: string, config: string, loaded: { [string]: unknown, ... }, preload: { [string]: unknown, ... }, ... }
--:: declare arg = { [integer]: string, ... }
--:: declare jit = { version: string, version_num: integer, os: string, arch: string, ... }
--:: declare register_ffi_module = ((string) -> nil) | nil

---------------------------------------------------------------------------
-- string table
---------------------------------------------------------------------------

--:: augment string {
--::     format:  (fmt: string, ...unknown) -> string,
--::     len:     (s: string) -> integer,
--::     sub:     (s: string, i: integer, j: integer | nil) -> string,
--::     find:    <P: string>(s: string, pattern: P, init: integer | nil, plain: boolean | nil) -> ...($FindReturn<P>),
--::     match:   <P: string>(s: string, pattern: P, init: integer | nil) -> $PatternReturn<P>,
--::     gmatch:  <P: string>(s: string, pattern: P) -> (() -> $PatternReturn<P>),
--::     gsub:    (s: string, pattern: string, repl: string | ((string) -> (string | nil)) | { [string]: string, ... }, n: integer | nil) -> (string, integer),
--::     rep:     (s: string, n: integer, sep: string | nil) -> string,
--::     byte:    ((s: string, i: integer | nil) -> integer | nil) & ((s: string, i: integer, j: integer) -> ...(integer)),
--::     char:    (...integer) -> string,
--::     upper:   (s: string) -> string,
--::     lower:   (s: string) -> string,
--::     reverse: (s: string) -> string,
--::     dump:    (fn: (...never) -> unknown, strip: boolean | nil) -> string
--:: }

---------------------------------------------------------------------------
-- table table
---------------------------------------------------------------------------

--:: augment table {
--::     insert:  <V>(t: { [integer]: V, ... }, v: V) -> (),
--::     remove:  <V>(t: { [integer]: V, ... }, pos: integer | nil) -> V | nil,
--::     concat:  (t: { [integer]: string | number, ... }, sep: string | nil, i: integer | nil, j: integer | nil) -> string,
--::     sort:    <V>(t: { [integer]: V, ... }, comp: ((V, V) -> boolean) | nil) -> (),
--::     unpack:  <V>(t: { [integer]: V, ... }, i: integer | nil, j: integer | nil) -> ...(V),
--::     move:    <V>(a1: { [integer]: V, ... }, f: integer, e: integer, t: integer, a2: { [integer]: V, ... } | nil) -> { [integer]: V, ... },
--::     maxn:    (t: { [integer]: unknown, ... }) -> integer
--:: }

---------------------------------------------------------------------------
-- math table
---------------------------------------------------------------------------

--:: augment math {
--::     floor:      (x: number) -> integer,
--::     ceil:       (x: number) -> integer,
--::     abs:        (x: number) -> number,
--::     sqrt:       (x: number) -> number,
--::     max:        ((x: integer, ...integer) -> integer) & ((x: number, ...number) -> number),
--::     min:        ((x: integer, ...integer) -> integer) & ((x: number, ...number) -> number),
--::     random:     (m: integer | nil, n: integer | nil) -> number,
--::     randomseed: (x: number) -> (),
--::     sin:        (x: number) -> number,
--::     cos:        (x: number) -> number,
--::     tan:        (x: number) -> number,
--::     asin:       (x: number) -> number,
--::     acos:       (x: number) -> number,
--::     atan:       (x: number) -> number,
--::     atan2:      (y: number, x: number) -> number,
--::     exp:        (x: number) -> number,
--::     log:        (x: number, base: number | nil) -> number,
--::     log10:      (x: number) -> number,
--::     pow:        (x: number, y: number) -> number,
--::     fmod:       (x: number, y: number) -> number,
--::     modf:       (x: number) -> (number, number),
--::     frexp:      (x: number) -> (number, integer),
--::     ldexp:      (m: number, e: integer) -> number,
--::     huge:       number,
--::     pi:         number,
--::     max_integer: integer,
--::     min_integer: integer,
--::     rad:        (x: number) -> number,
--::     deg:        (x: number) -> number,
--::     tanh:       (x: number) -> number,
--::     sinh:       (x: number) -> number,
--::     cosh:       (x: number) -> number
--:: }

---------------------------------------------------------------------------
-- io table
---------------------------------------------------------------------------

--:: File = {
--::     read:    (File, ...string | number) -> string | nil,
--::     write:   (File, ...string | number) -> (File | nil, string | nil),
--::     close:   (File) -> (boolean | nil, string | nil),
--::     lines:   (File) -> () -> string | nil,
--::     seek:    (File, string | nil, integer | nil) -> (integer | nil, string | nil),
--::     flush:   (File) -> (boolean | nil, string | nil),
--::     setvbuf: (File, string, integer | nil) -> (boolean | nil, string | nil)
--:: }
--:: augment io {
--::     open:    (path: string, mode: string | nil) -> (File | nil, string | nil),
--::     close:   (file: File | nil) -> (boolean | nil, string | nil),
--::     write:   (...string | number) -> (File | nil, string | nil),
--::     read:    (...string | number) -> string | nil,
--::     lines:   (filename: string | nil) -> () -> string | nil,
--::     popen:   (cmd: string, mode: string | nil) -> (File | nil, string | nil),
--::     tmpfile: () -> File | nil,
--::     flush:   () -> (boolean | nil, string | nil),
--::     input:   (file: string | File | nil) -> File,
--::     output:  (file: string | File | nil) -> File,
--::     stdin:   File,
--::     stdout:  File,
--::     stderr:  File
--:: }

---------------------------------------------------------------------------
-- os table
---------------------------------------------------------------------------

--:: augment os {
--::     time:     (t: { [string]: integer, ... } | nil) -> integer,
--::     clock:    () -> number,
--::     date:     (format: string | nil, time: integer | nil) -> string | { [string]: integer, ... },
--::     exit:     (code: integer | boolean | nil, close: boolean | nil) -> (),
--::     getenv:   (name: string) -> string | nil,
--::     difftime: (t2: number, t1: number) -> number,
--::     rename:   (oldname: string, newname: string) -> (boolean, string | nil),
--::     remove:   (path: string) -> (boolean, string | nil),
--::     tmpname:  () -> string,
--::     execute:  (cmd: string | nil) -> (boolean | nil, string | nil, integer | nil)
--:: }

---------------------------------------------------------------------------
-- coroutine table
---------------------------------------------------------------------------

--:: Thread = $Opaque<"Thread">
--:: augment coroutine {
--::     create:     (fn: (...never) -> unknown) -> Thread,
--::     resume:     (co: Thread, ...unknown) -> (boolean, ...unknown),
--::     yield:      (...unknown) -> (...unknown),
--::     wrap:       (fn: (...never) -> unknown) -> ((...never) -> unknown),
--::     status:     (co: Thread) -> "running" | "suspended" | "normal" | "dead",
--::     running:    () -> (Thread | nil, boolean),
--::     isyieldable: () -> boolean
--:: }

---------------------------------------------------------------------------
-- debug table (minimal)
---------------------------------------------------------------------------

--:: augment debug {
--::     getinfo:      (thread_or_f: integer | ((...never) -> unknown) | Thread, what: string | nil) -> { [string]: unknown, ... } | nil,
--::     traceback:    (thread_or_msg: Thread | string | nil, msg: string | integer | nil, level: integer | nil) -> string,
--::     sethook:      (thread_or_fn: Thread | ((string, integer | nil) -> ()) | nil, mask: string | nil, count: integer | nil) -> (),
--::     gethook:      (thread: Thread | nil) -> (((string, integer | nil) -> ()) | nil, string, integer),
--::     getlocal:     (level: integer, local_: integer) -> (string, unknown),
--::     setlocal:     (level: integer, local_: integer, value: unknown) -> string,
--::     getmetatable: (t: unknown) -> unknown,
--::     setmetatable: (t: unknown, mt: unknown) -> unknown
--:: }

---------------------------------------------------------------------------
-- Primitive meta type aliases
-- Type aliases (no 'declare') for ctx.number_meta_tid etc.
-- Used by unify.lua when checking structural meta constraints.
---------------------------------------------------------------------------

--:: number_meta = {
--::     #__add:    (a: number, b: number) -> number,
--::     #__sub:    (a: number, b: number) -> number,
--::     #__mul:    (a: number, b: number) -> number,
--::     #__div:    (a: number, b: number) -> number,
--::     #__mod:    (a: number, b: number) -> number,
--::     #__pow:    (a: number, b: number) -> number,
--::     #__unm:    (a: number) -> number,
--::     #__lt:     (a: number, b: number) -> boolean,
--::     #__le:     (a: number, b: number) -> boolean,
--::     #__concat: (a: string | number, b: string | number) -> string
--:: }

--:: integer_meta = {
--::     #__add:    (a: integer, b: integer) -> integer,
--::     #__sub:    (a: integer, b: integer) -> integer,
--::     #__mul:    (a: integer, b: integer) -> integer,
--::     #__div:    (a: integer, b: integer) -> number,
--::     #__mod:    (a: integer, b: integer) -> integer,
--::     #__pow:    (a: integer, b: number) -> number,
--::     #__unm:    (a: integer) -> integer,
--::     #__lt:     (a: number, b: number) -> boolean,
--::     #__le:     (a: number, b: number) -> boolean,
--::     #__concat: (a: string | number, b: string | number) -> string
--:: }

--:: string_meta_ops = {
--::     #__concat: (a: string, b: string | number) -> string,
--::     #__len:    (s: string) -> integer,
--::     #__lt:     (a: string, b: string) -> boolean,
--::     #__le:     (a: string, b: string) -> boolean
--:: }
