-- lib/type/static/stdlib_types.lua
-- Lua 5.1 / LuaJIT standard library type declarations.
-- Loaded by prelude.populate(); no executable code here.
-- Variable bindings use --:: declare name = type.
-- Type aliases (for primitive meta types) use --:: name = type.

---------------------------------------------------------------------------
-- Global functions
---------------------------------------------------------------------------

--:: declare print = (...any) -> ()
--:: declare tostring = (val: any) -> string
--:: declare tonumber = (val: any, base: any | nil) -> number | nil
--:: declare type = (val: any) -> string
--:: declare error = (msg: any, level: any | nil) -> never
--:: declare assert = (val: any, ...any) -> any
--:: PcallReturn<F> = match F { (...%P) -> %R => (true, ...R) | (false, string) }
--:: declare pcall = <F: (...P) -> R, P, R>(f: F, ...P) -> ...(PcallReturn<F>)
--:: declare xpcall = <F: (...P) -> R, P, R>(f: F, handler: (string) -> string, ...P) -> ...(PcallReturn<F>)
--:: declare require = <T: string>(module: T) -> $Require<T>
--:: declare select = (("#") -> integer) & ((integer, ...any) -> any)
--:: declare rawget = (t: any, k: any) -> any
--:: declare rawset = (t: any, k: any, v: any) -> any
--:: declare rawequal = (a: any, b: any) -> boolean
--:: declare rawlen = (t: any) -> integer
--:: declare unpack = (t: any, i: any | nil, j: any | nil) -> any
--:: declare pairs = <T>(t: T) -> ...(PairsReturn<T>)
--:: declare ipairs = <T>(t: T) -> ...(IpairsReturn<T>)

--:: PairsReturn<T>  = match T { { ...[%K]: %V } => (K, V) }
--:: IpairsReturn<T> = match T { { ...[%K]: %V } => match K { number => (integer, V), _ => never } }
--:: Keys<T>         = match T { { ...[%K]: %V } => K }
--:: Values<T>       = match T { { ...[%K]: %V } => V }
--:: Open<T>         = match T { { ...%Rest } => { ...Rest, ... } }
--:: Closed<T>       = match T { { ...%Rest } => { ...Rest } }
--:: declare next = (t: any, k: any | nil) -> (any, any)
--:: declare setmetatable = <T, MT>(t: T, mt: MT) -> T & { #...MT }
--:: MetaOf<T> = match T { { #...%M } => M, _ => nil }
--:: declare getmetatable = <T>(t: T) -> MetaOf<T>
--:: declare collectgarbage = (opt: any | nil, arg: any | nil) -> any
--:: declare gcinfo = () -> integer
--:: declare dofile = (filename: any | nil) -> any
--:: declare loadfile = (filename: any | nil) -> (any, any | nil)
--:: declare loadstring = (s: string, chunkname: any | nil) -> (any, any | nil)
--:: declare load = (chunk: any, chunkname: any | nil, mode: any | nil, env: any | nil) -> (any, any | nil)
--:: declare newproxy = (mt: any | nil) -> any
--:: declare rawprint = (s: any) -> ()
--:: declare _VERSION = string
--:: module "ffi": {
--::   cdef:   (string) -> nil,
--::   new:    (string, ...any) -> unknown,
--::   cast:   (string, unknown) -> unknown,
--::   sizeof: (string) -> integer,
--::   typeof: (string) -> unknown,
--::   copy:   (unknown, unknown, integer) -> nil,
--::   fill:   (unknown, integer) -> nil,
--::   string: (unknown, integer | nil) -> string,
--::   load:      (name: string, global: boolean | nil) -> any,
--::   gc:        (cdata: any, finalizer: ((...any) -> any) | nil) -> any,
--::   metatype:  (ct: any, metatable: { [string]: any }) -> any,
--::   istype:    (ct: any, obj: any) -> boolean,
--::   alignof:   (ct: any) -> integer,
--::   offsetof:  (ct: any, field: string) -> integer,
--::   abi:       (param: string) -> boolean,
--::   errno:     (newerr: integer | nil) -> integer,
--::   C:         $FfiC,
--:: }
--:: module "bit": {
--::   tobit:   (x: number) -> integer,
--::   tohex:   (x: integer, n: integer | nil) -> string,
--::   bnot:    (x: integer) -> integer,
--::   band:    (x: integer, ...integer) -> integer,
--::   bor:     (x: integer, ...integer) -> integer,
--::   bxor:    (x: integer, ...integer) -> integer,
--::   lshift:  (x: integer, n: integer) -> integer,
--::   rshift:  (x: integer, n: integer) -> integer,
--::   arshift: (x: integer, n: integer) -> integer,
--::   bswap:   (x: integer) -> integer,
--::   rol:     (x: integer, n: integer) -> integer,
--::   ror:     (x: integer, n: integer) -> integer
--:: }
--:: declare _G = $GlobalScope
--:: declare package = { path: string, cpath: string, loaded: { [string]: any, ... }, preload: { [string]: any, ... }, ... }
--:: declare arg = { [integer]: string, ... }
--:: declare jit = any

---------------------------------------------------------------------------
-- string table
---------------------------------------------------------------------------

--:: declare string = {
--::     format:  (fmt: string, ...any) -> string,
--::     len:     (s: string) -> integer,
--::     sub:     (s: string, i: integer, j: any | nil) -> string,
--::     find:    (s: string, pattern: string, init: any | nil, plain: any | nil) -> ...((integer, integer) | (nil, nil)),
--::     match:   (s: string, pattern: string, init: any | nil) -> any,
--::     gmatch:  (s: string, pattern: string) -> function,
--::     gsub:    (s: string, pattern: string, repl: any, n: any | nil) -> (string, integer),
--::     rep:     (s: string, n: integer, sep: any | nil) -> string,
--::     byte:    (s: string, i: any | nil, j: any | nil) -> ...(integer),
--::     char:    (...integer) -> string,
--::     upper:   (s: string) -> string,
--::     lower:   (s: string) -> string,
--::     reverse: (s: string) -> string,
--::     dump:    (fn: any, strip: any | nil) -> string
--:: }

---------------------------------------------------------------------------
-- table table
---------------------------------------------------------------------------

--:: declare table = {
--::     insert:  (t: any, v: any) -> (),
--::     remove:  (t: any, pos: any | nil) -> any | nil,
--::     concat:  (t: any, sep: any | nil, i: any | nil, j: any | nil) -> string,
--::     sort:    (t: any, comp: any | nil) -> (),
--::     unpack:  (t: any, i: any | nil, j: any | nil) -> any,
--::     move:    (a1: any, f: integer, e: integer, t: integer, a2: any | nil) -> any,
--::     maxn:    (t: any) -> integer
--:: }

---------------------------------------------------------------------------
-- math table
---------------------------------------------------------------------------

--:: declare math = {
--::     floor:      (x: number) -> integer,
--::     ceil:       (x: number) -> integer,
--::     abs:        (x: number) -> number,
--::     sqrt:       (x: number) -> number,
--::     max:        (x: number, ...number) -> number,
--::     min:        (x: number, ...number) -> number,
--::     random:     (m: any | nil, n: any | nil) -> number,
--::     randomseed: (x: number) -> (),
--::     sin:        (x: number) -> number,
--::     cos:        (x: number) -> number,
--::     tan:        (x: number) -> number,
--::     asin:       (x: number) -> number,
--::     acos:       (x: number) -> number,
--::     atan:       (x: number) -> number,
--::     atan2:      (y: number, x: number) -> number,
--::     exp:        (x: number) -> number,
--::     log:        (x: number, base: any | nil) -> number,
--::     log10:      (x: number) -> number,
--::     pow:        (x: number, y: number) -> number,
--::     fmod:       (x: number, y: number) -> number,
--::     modf:       (x: number) -> (number, number),
--::     frexp:      (x: number) -> (number, integer),
--::     ldexp:      (m: number, e: integer) -> number,
--::     huge:       number,
--::     pi:         number,
--::     max_integer: integer,
--::     min_integer: integer
--:: }

---------------------------------------------------------------------------
-- io table
---------------------------------------------------------------------------

--:: declare io = {
--::     open:    (path: string, mode: any | nil) -> (any, any | nil),
--::     close:   (file: any | nil) -> any,
--::     write:   (...any) -> any,
--::     read:    (...any) -> any,
--::     lines:   (filename: any | nil, ...any) -> any,
--::     popen:   (cmd: string, mode: any | nil) -> (any, any | nil),
--::     tmpfile: () -> any,
--::     flush:   () -> boolean | nil, string | nil,
--::     input:   (file: string | nil) -> any,
--::     output:  (file: string | nil) -> any,
--::     stdin:   any,
--::     stdout:  any,
--::     stderr:  any
--:: }

---------------------------------------------------------------------------
-- os table
---------------------------------------------------------------------------

--:: declare os = {
--::     time:     (t: any | nil) -> integer,
--::     clock:    () -> number,
--::     date:     (format: any | nil, time: any | nil) -> any,
--::     exit:     (code: any | nil, close: any | nil) -> (),
--::     getenv:   (name: string) -> string | nil,
--::     difftime: (t2: number, t1: number) -> number,
--::     rename:   (oldname: string, newname: string) -> (boolean, any | nil),
--::     remove:   (path: string) -> (boolean, any | nil),
--::     tmpname:  () -> string,
--::     execute:  (cmd: any | nil) -> (any, any | nil, integer | nil)
--:: }

---------------------------------------------------------------------------
-- coroutine table
---------------------------------------------------------------------------

--:: declare coroutine = {
--::     create:     (fn: (...any) -> ...any) -> any,
--::     resume:     (co: any, ...any) -> (boolean, ...any),
--::     yield:      (...any) -> ...any,
--::     wrap:       (fn: (...any) -> ...any) -> (...any) -> ...any,
--::     status:     (co: any) -> "running" | "suspended" | "normal" | "dead",
--::     running:    () -> (any, boolean),
--::     isyieldable: () -> boolean
--:: }

---------------------------------------------------------------------------
-- debug table (minimal)
---------------------------------------------------------------------------

--:: declare debug = {
--::     getinfo:      (thread_or_f: any, what: any | nil) -> any,
--::     traceback:    (thread_or_msg: any | nil, msg: any | nil, level: any | nil) -> string,
--::     sethook:      (thread_or_fn: any, mask: any, count: any | nil) -> (),
--::     getlocal:     (level: any, local_: integer) -> (string, any),
--::     setlocal:     (level: any, local_: integer, value: any) -> string,
--::     getmetatable: (t: any) -> any,
--::     setmetatable: (t: any, mt: any | nil) -> any
--:: }

---------------------------------------------------------------------------
-- Primitive meta type aliases
-- Type aliases (no 'declare') for ctx.number_meta_tid etc.
-- Used by unify.lua when checking structural meta constraints.
---------------------------------------------------------------------------

--:: number_meta = {
--::     #__add:    (a: number, b: number) -> number,
--::     #__sub:    (a: number, b: number) -> number,
--::     #__mul:    (a: number, b: number) -> number,
--::     #__div:    (a: number, b: number) -> number,
--::     #__mod:    (a: number, b: number) -> number,
--::     #__pow:    (a: number, b: number) -> number,
--::     #__unm:    (a: number) -> number,
--::     #__lt:     (a: number, b: number) -> boolean,
--::     #__le:     (a: number, b: number) -> boolean,
--::     #__concat: (a: any, b: any) -> string
--:: }

--:: integer_meta = {
--::     #__add:    (a: integer, b: integer) -> integer,
--::     #__sub:    (a: integer, b: integer) -> integer,
--::     #__mul:    (a: integer, b: integer) -> integer,
--::     #__div:    (a: integer, b: integer) -> number,
--::     #__mod:    (a: integer, b: integer) -> integer,
--::     #__pow:    (a: integer, b: number) -> number,
--::     #__unm:    (a: integer) -> integer,
--::     #__lt:     (a: number, b: number) -> boolean,
--::     #__le:     (a: number, b: number) -> boolean,
--::     #__concat: (a: any, b: any) -> string
--:: }

--:: string_meta_ops = {
--::     #__concat: (a: string, b: any) -> string,
--::     #__len:    (s: string) -> integer,
--::     #__lt:     (a: string, b: string) -> boolean,
--::     #__le:     (a: string, b: string) -> boolean
--:: }
