-- lib/base32/base32_test.lua
-- Tests for lib/base32 — RFC 4648 standard, hex, and Crockford variants.

if not package.path:find("./?/init.lua", 1, true) then
    package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local b32 = require("lib.base32")

-- ── Standard Base32 (RFC 4648 §6) ─────────────────────────────────────────────

T.describe("base32 standard encode", function()
    -- RFC 4648 §10 test vectors
    T.it("encodes empty string", function()
        T.eq(b32.encode(""), "")
    end)
    T.it("encodes 'f'", function()
        T.eq(b32.encode("f"), "MY======")
    end)
    T.it("encodes 'fo'", function()
        T.eq(b32.encode("fo"), "MZXQ====")
    end)
    T.it("encodes 'foo'", function()
        T.eq(b32.encode("foo"), "MZXW6===")
    end)
    T.it("encodes 'foob'", function()
        T.eq(b32.encode("foob"), "MZXW6YQ=")
    end)
    T.it("encodes 'fooba'", function()
        T.eq(b32.encode("fooba"), "MZXW6YTB")
    end)
    T.it("encodes 'foobar'", function()
        T.eq(b32.encode("foobar"), "MZXW6YTBOI======")
    end)
end)

T.describe("base32 standard decode", function()
    T.it("decodes empty string", function()
        T.eq(b32.decode(""), "")
    end)
    T.it("decodes MY======", function()
        T.eq(b32.decode("MY======"), "f")
    end)
    T.it("decodes MZXQ====", function()
        T.eq(b32.decode("MZXQ===="), "fo")
    end)
    T.it("decodes MZXW6===", function()
        T.eq(b32.decode("MZXW6==="), "foo")
    end)
    T.it("decodes MZXW6YQ=", function()
        T.eq(b32.decode("MZXW6YQ="), "foob")
    end)
    T.it("decodes MZXW6YTB", function()
        T.eq(b32.decode("MZXW6YTB"), "fooba")
    end)
    T.it("decodes MZXW6YTBOI======", function()
        T.eq(b32.decode("MZXW6YTBOI======"), "foobar")
    end)
    T.it("decodes lowercase my======", function()
        T.eq(b32.decode("my======"), "f")
    end)
    T.it("decodes mixed case", function()
        T.eq(b32.decode("mZxW6YtB"), "fooba")
    end)
end)

T.describe("base32 standard round-trips", function()
    T.it("round-trips single byte 0x00", function()
        local s = "\000"
        T.eq(b32.decode(b32.encode(s)), s)
    end)
    T.it("round-trips single byte 0xff", function()
        local s = "\255"
        T.eq(b32.decode(b32.encode(s)), s)
    end)
    T.it("round-trips binary with null bytes", function()
        local s = "\000\001\002\003\004\255\254\253"
        T.eq(b32.decode(b32.encode(s)), s)
    end)
    T.it("round-trips all printable ASCII", function()
        local chars = {}
        for i = 32, 126 do chars[#chars + 1] = string.char(i) end
        local s = table.concat(chars)
        T.eq(b32.decode(b32.encode(s)), s)
    end)
    T.it("round-trips 1-byte boundary", function()
        T.eq(b32.decode(b32.encode("A")), "A")
    end)
    T.it("round-trips 2-byte boundary", function()
        T.eq(b32.decode(b32.encode("AB")), "AB")
    end)
    T.it("round-trips 3-byte boundary", function()
        T.eq(b32.decode(b32.encode("ABC")), "ABC")
    end)
    T.it("round-trips 4-byte boundary", function()
        T.eq(b32.decode(b32.encode("ABCD")), "ABCD")
    end)
    T.it("round-trips 5-byte boundary", function()
        T.eq(b32.decode(b32.encode("ABCDE")), "ABCDE")
    end)
    T.it("round-trips 10-byte boundary", function()
        T.eq(b32.decode(b32.encode("ABCDEFGHIJ")), "ABCDEFGHIJ")
    end)
end)

T.describe("base32 decode errors", function()
    T.it("errors on invalid character", function()
        local result, err = b32.decode("M1======")
        T.eq(result, nil)
        T.ok(err ~= nil, "expected error message")
    end)
    T.it("errors on invalid character 0x80", function()
        local result, err = b32.decode("M\128=====")
        T.eq(result, nil)
        T.ok(err ~= nil, "expected error message")
    end)
end)

-- ── Base32hex (RFC 4648 §7) ────────────────────────────────────────────────────

T.describe("base32hex encode", function()
    -- RFC 4648 §10 hex test vectors
    T.it("encodes empty string", function()
        T.eq(b32.encode_hex(""), "")
    end)
    T.it("encodes 'f'", function()
        T.eq(b32.encode_hex("f"), "CO======")
    end)
    T.it("encodes 'fo'", function()
        T.eq(b32.encode_hex("fo"), "CPNG====")
    end)
    T.it("encodes 'foo'", function()
        T.eq(b32.encode_hex("foo"), "CPNMU===")
    end)
    T.it("encodes 'foob'", function()
        T.eq(b32.encode_hex("foob"), "CPNMUOG=")
    end)
    T.it("encodes 'fooba'", function()
        T.eq(b32.encode_hex("fooba"), "CPNMUOJ1")
    end)
    T.it("encodes 'foobar'", function()
        T.eq(b32.encode_hex("foobar"), "CPNMUOJ1E8======")
    end)
end)

T.describe("base32hex decode", function()
    T.it("decodes empty string", function()
        T.eq(b32.decode_hex(""), "")
    end)
    T.it("decodes CO======", function()
        T.eq(b32.decode_hex("CO======"), "f")
    end)
    T.it("decodes CPNMUOJ1E8======", function()
        T.eq(b32.decode_hex("CPNMUOJ1E8======"), "foobar")
    end)
    T.it("round-trips foobar", function()
        T.eq(b32.decode_hex(b32.encode_hex("foobar")), "foobar")
    end)
    T.it("round-trips binary data", function()
        local s = "\000\128\255\001\254"
        T.eq(b32.decode_hex(b32.encode_hex(s)), s)
    end)
    T.it("errors on invalid character", function()
        local result, err = b32.decode_hex("WX======")
        T.eq(result, nil)
        T.ok(err ~= nil, "expected error message")
    end)
end)

-- ── Crockford Base32 ──────────────────────────────────────────────────────────

T.describe("crockford encode", function()
    T.it("encodes empty string", function()
        T.eq(b32.encode_crockford(""), "")
    end)
    T.it("encodes 'f'", function()
        -- 'f' = 0x66 = 0110 0110
        -- 5 bits: 01100 = 12 = 'C', 11000 = 24 = 'R' (but only 3 bits used: 110 00 = last 3 bits of 0x66 = 6, pad to 5: 01100)
        -- Actually: 0x66 = 102 decimal
        -- first 5 bits: 102 >> 3 = 12 → 'C'
        -- last 3 bits << 2: (102 & 7) << 2 = 6<<2 = 24 → 'R'
        -- So: "CR" (no padding for Crockford)
        T.eq(b32.encode_crockford("f"), "CR")
    end)
    T.it("encodes 'foo'", function()
        -- same 5 chars as standard but with crockford alphabet (no padding)
        local result = b32.encode_crockford("foo")
        T.eq(#result, 5)
        T.eq(b32.decode_crockford(result), "foo")
    end)
    T.it("encodes 'foobar'", function()
        local result = b32.encode_crockford("foobar")
        T.eq(#result, 10)  -- ceil(6*8/5) = ceil(9.6) = 10
        T.eq(b32.decode_crockford(result), "foobar")
    end)
    T.it("no padding characters in output", function()
        local result = b32.encode_crockford("f")
        T.ok(not result:find("="), "crockford output should not contain padding")
    end)
end)

T.describe("crockford decode", function()
    T.it("decodes empty string", function()
        T.eq(b32.decode_crockford(""), "")
    end)
    T.it("case-insensitive: lowercase", function()
        local upper = b32.encode_crockford("foo")
        T.eq(b32.decode_crockford(upper:lower()), "foo")
    end)
    T.it("maps I to 1", function()
        -- encode "0" as crockford, then replace digit '1' with 'I' and re-decode
        -- 0x30 = 48: first 5 bits = 6 → '6', last 3 = 0, padded = 0 → '0'
        -- So encode("0") = "60" (no pad)
        -- encode uses value 6 → char '6', value 0 → char '0'
        -- Now '1' has value 1, same as 'I'
        -- Let's just check that a string with 'I' and the same string with '1' decode the same
        local with_one  = b32.decode_crockford("0I")
        local with_i    = b32.decode_crockford("01")
        T.eq(with_one, with_i)
    end)
    T.it("maps L to 1", function()
        local with_l = b32.decode_crockford("0L")
        local with_1 = b32.decode_crockford("01")
        T.eq(with_l, with_1)
    end)
    T.it("maps O to 0", function()
        local with_o = b32.decode_crockford("O0")
        local with_0 = b32.decode_crockford("00")
        T.eq(with_o, with_0)
    end)
    T.it("round-trips binary data", function()
        local s = "\000\128\255\001\254"
        T.eq(b32.decode_crockford(b32.encode_crockford(s)), s)
    end)
    T.it("errors on invalid character (U is not in crockford)", function()
        local result, err = b32.decode_crockford("OU======")
        T.eq(result, nil)
        T.ok(err ~= nil, "expected error message")
    end)
end)

-- ── Codec aliases ──────────────────────────────────────────────────────────────

T.describe("codec aliases", function()
    T.it("string_to_base32 == encode", function()
        T.eq(b32.string_to_base32("foo"), b32.encode("foo"))
    end)
    T.it("base32_to_string == decode", function()
        T.eq(b32.base32_to_string("MZXW6==="), b32.decode("MZXW6==="))
    end)
    T.it("_tier is pure", function()
        T.eq(b32._tier, "pure")
    end)
end)
