if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.markup")

-- ============================================================
-- Markdown: Headings
-- ============================================================
T.describe("markdown headings", function()
  T.it("h1", function()
    T.eq(M.markdown("# Hello"), "<h1>Hello</h1>\n")
  end)
  T.it("h2", function()
    T.eq(M.markdown("## World"), "<h2>World</h2>\n")
  end)
  T.it("h3 through h6", function()
    T.eq(M.markdown("### A"), "<h3>A</h3>\n")
    T.eq(M.markdown("#### B"), "<h4>B</h4>\n")
    T.eq(M.markdown("##### C"), "<h5>C</h5>\n")
    T.eq(M.markdown("###### D"), "<h6>D</h6>\n")
  end)
  T.it("clamps at h6", function()
    T.eq(M.markdown("####### Too deep"), "<h6>Too deep</h6>\n")
  end)
  T.it("setext h1 with ===", function()
    local html = M.markdown("Title\n=====")
    T.eq(html, "<h1>Title</h1>\n")
  end)
  T.it("setext h2 with ---", function()
    local html = M.markdown("Section\n-------")
    T.eq(html, "<h2>Section</h2>\n")
  end)
  T.it("heading strips trailing hashes", function()
    T.eq(M.markdown("## Heading ##"), "<h2>Heading</h2>\n")
  end)
end)

-- ============================================================
-- Markdown: Paragraphs
-- ============================================================
T.describe("markdown paragraphs", function()
  T.it("single paragraph", function()
    T.eq(M.markdown("Hello world"), "<p>Hello world</p>\n")
  end)
  T.it("two paragraphs separated by blank line", function()
    local html = M.markdown("First\n\nSecond")
    T.eq(html, "<p>First</p>\n<p>Second</p>\n")
  end)
  T.it("multi-line paragraph", function()
    local html = M.markdown("Line one\nLine two")
    T.eq(html, "<p>Line one\nLine two</p>\n")
  end)
end)

-- ============================================================
-- Markdown: Bold, Italic, Code
-- ============================================================
T.describe("markdown inline formatting", function()
  T.it("bold **", function()
    T.eq(M.markdown("**bold**"), "<p><strong>bold</strong></p>\n")
  end)
  T.it("bold __", function()
    T.eq(M.markdown("__bold__"), "<p><strong>bold</strong></p>\n")
  end)
  T.it("italic *", function()
    T.eq(M.markdown("*italic*"), "<p><em>italic</em></p>\n")
  end)
  T.it("italic _", function()
    T.eq(M.markdown("_italic_"), "<p><em>italic</em></p>\n")
  end)
  T.it("inline code", function()
    T.eq(M.markdown("`code`"), "<p><code>code</code></p>\n")
  end)
  T.it("inline code escapes HTML", function()
    T.eq(M.markdown("`<b>`"), "<p><code>&lt;b&gt;</code></p>\n")
  end)
  T.it("bold and italic in sentence", function()
    local html = M.markdown("This is **bold** and *italic* text.")
    T.ok(html:find("<strong>bold</strong>"))
    T.ok(html:find("<em>italic</em>"))
  end)
  T.it("HTML entities escaped in text", function()
    local html = M.markdown("a < b & c > d")
    T.ok(html:find("&lt;"))
    T.ok(html:find("&amp;"))
    T.ok(html:find("&gt;"))
  end)
end)

-- ============================================================
-- Markdown: Code blocks
-- ============================================================
T.describe("markdown code blocks", function()
  T.it("fenced code block no lang", function()
    local html = M.markdown("```\nhello\n```")
    T.eq(html, "<pre><code>hello</code></pre>\n")
  end)
  T.it("fenced code block with lang", function()
    local html = M.markdown("```lua\nlocal x = 1\n```")
    T.eq(html, '<pre><code class="language-lua">local x = 1</code></pre>\n')
  end)
  T.it("code block escapes HTML", function()
    local html = M.markdown("```\n<div>\n```")
    T.ok(html:find("&lt;div&gt;"))
  end)
  T.it("multiline code block", function()
    local html = M.markdown("```\nline1\nline2\nline3\n```")
    T.ok(html:find("line1"))
    T.ok(html:find("line2"))
    T.ok(html:find("line3"))
  end)
end)

-- ============================================================
-- Markdown: Lists
-- ============================================================
T.describe("markdown unordered lists", function()
  T.it("basic unordered list with -", function()
    local html = M.markdown("- item1\n- item2\n- item3")
    T.ok(html:find("<ul>"))
    T.ok(html:find("<li>item1</li>"))
    T.ok(html:find("<li>item2</li>"))
    T.ok(html:find("<li>item3</li>"))
    T.ok(html:find("</ul>"))
  end)
  T.it("unordered list with *", function()
    local html = M.markdown("* alpha\n* beta")
    T.ok(html:find("<ul>"))
    T.ok(html:find("<li>alpha</li>"))
    T.ok(html:find("<li>beta</li>"))
  end)
  T.it("unordered list with +", function()
    local html = M.markdown("+ one\n+ two")
    T.ok(html:find("<ul>"))
    T.ok(html:find("<li>one</li>"))
  end)
end)

T.describe("markdown ordered lists", function()
  T.it("basic ordered list", function()
    local html = M.markdown("1. first\n2. second\n3. third")
    T.ok(html:find("<ol>"))
    T.ok(html:find("<li>first</li>"))
    T.ok(html:find("<li>second</li>"))
    T.ok(html:find("<li>third</li>"))
    T.ok(html:find("</ol>"))
  end)
  T.it("ordered list with inline formatting", function()
    local html = M.markdown("1. **bold item**\n2. *italic item*")
    T.ok(html:find("<strong>bold item</strong>"))
    T.ok(html:find("<em>italic item</em>"))
  end)
end)

-- ============================================================
-- Markdown: Links and Images
-- ============================================================
T.describe("markdown links and images", function()
  T.it("link", function()
    local html = M.markdown("[click here](https://example.com)")
    T.eq(html, '<p><a href="https://example.com">click here</a></p>\n')
  end)
  T.it("link with formatted text", function()
    local html = M.markdown("[**bold link**](https://x.com)")
    T.ok(html:find('<a href="https://x.com">'))
    T.ok(html:find("<strong>bold link</strong>"))
  end)
  T.it("image", function()
    local html = M.markdown("![alt text](image.png)")
    T.eq(html, '<p><img src="image.png" alt="alt text"></p>\n')
  end)
  T.it("link escapes URL special chars", function()
    local html = M.markdown('[x]("url")')
    T.ok(html:find("&quot;url&quot;"))
  end)
end)

-- ============================================================
-- Markdown: Blockquotes
-- ============================================================
T.describe("markdown blockquotes", function()
  T.it("simple blockquote", function()
    local html = M.markdown("> quoted text")
    T.ok(html:find("<blockquote>"))
    T.ok(html:find("quoted text"))
    T.ok(html:find("</blockquote>"))
  end)
  T.it("blockquote renders inner paragraph", function()
    local html = M.markdown("> hello world")
    T.ok(html:find("<p>hello world</p>"))
  end)
  T.it("multi-line blockquote", function()
    local html = M.markdown("> line one\n> line two")
    T.ok(html:find("<blockquote>"))
    T.ok(html:find("line one"))
    T.ok(html:find("line two"))
  end)
end)

-- ============================================================
-- Markdown: Horizontal rule
-- ============================================================
T.describe("markdown horizontal rule", function()
  T.it("--- rule", function()
    T.ok(M.markdown("---"):find("<hr>"))
  end)
  T.it("*** rule", function()
    T.ok(M.markdown("***"):find("<hr>"))
  end)
  T.it("___ rule", function()
    T.ok(M.markdown("___"):find("<hr>"))
  end)
  T.it("rule does not parse as heading", function()
    local html = M.markdown("---")
    T.ok(not html:find("<h%d"))
    T.ok(html:find("<hr>"))
  end)
end)

-- ============================================================
-- Markdown: AST structure
-- ============================================================
T.describe("markdown parse_markdown returns AST", function()
  T.it("document node", function()
    local ast = M.parse_markdown("# Hello")
    T.eq(ast.tag, "Document")
    T.ok(#ast.children >= 1)
  end)
  T.it("heading node structure", function()
    local ast = M.parse_markdown("## Hi")
    local h = ast.children[1]
    T.eq(h.tag, "Heading")
    T.eq(h.level, 2)
    T.eq(h.children[1].tag, "Text")
    T.eq(h.children[1].value, "Hi")
  end)
  T.it("paragraph node structure", function()
    local ast = M.parse_markdown("Hello")
    local p = ast.children[1]
    T.eq(p.tag, "Paragraph")
    T.eq(p.children[1].tag, "Text")
    T.eq(p.children[1].value, "Hello")
  end)
  T.it("bold node structure", function()
    local ast = M.parse_markdown("**bold**")
    local p = ast.children[1]
    local b = p.children[1]
    T.eq(b.tag, "Bold")
    T.eq(b.children[1].value, "bold")
  end)
end)

-- ============================================================
-- ast_to_text: strip markup
-- ============================================================
T.describe("ast_to_text strips markup", function()
  T.it("plain text passes through", function()
    local ast = M.parse_markdown("Hello world")
    T.eq(M.ast_to_text(ast):gsub("\n+$", ""), "Hello world")
  end)
  T.it("strips bold markers", function()
    local ast = M.parse_markdown("**bold text**")
    T.ok(M.ast_to_text(ast):find("bold text"))
    T.ok(not M.ast_to_text(ast):find("%*%*"))
  end)
  T.it("strips italic markers", function()
    local ast = M.parse_markdown("*italic text*")
    T.ok(M.ast_to_text(ast):find("italic text"))
    T.ok(not M.ast_to_text(ast):find("%*"))
  end)
  T.it("strips link brackets and keeps text", function()
    local ast = M.parse_markdown("[link text](url)")
    local plain = M.ast_to_text(ast)
    T.ok(plain:find("link text"))
    T.ok(not plain:find("%["))
    T.ok(not plain:find("%]"))
  end)
  T.it("image: uses alt text", function()
    local ast = M.parse_markdown("![my image](foo.png)")
    local plain = M.ast_to_text(ast)
    T.ok(plain:find("my image"))
  end)
  T.it("heading text extracted", function()
    local ast = M.parse_markdown("# Title Here")
    local plain = M.ast_to_text(ast)
    T.ok(plain:find("Title Here"))
  end)
  T.it("code block value extracted", function()
    local ast = M.parse_markdown("```\nfn main() {}\n```")
    local plain = M.ast_to_text(ast)
    T.ok(plain:find("fn main"))
  end)
end)

-- ============================================================
-- Error handling
-- ============================================================
T.describe("error handling", function()
  T.it("nil input returns nil+errmsg", function()
    local result, err = M.markdown(nil)
    T.eq(result, nil)
    T.ok(err ~= nil)
  end)
  T.it("number input returns nil+errmsg", function()
    local result, err = M.rst(42)
    T.eq(result, nil)
    T.ok(err ~= nil)
  end)
  T.it("empty string produces empty output", function()
    local html = M.markdown("")
    T.eq(html, "")
  end)
end)

-- ============================================================
-- RST: Headings and inline formatting
-- ============================================================
T.describe("rst headings", function()
  T.it("underline-style heading", function()
    local html = M.rst("Title\n=====")
    T.ok(html:find("<h1>Title</h1>"))
  end)
  T.it("different chars get different levels", function()
    local input = "Chapter\n=======\n\nSection\n-------"
    local html = M.rst(input)
    T.ok(html:find("<h1>Chapter</h1>"))
    T.ok(html:find("<h2>Section</h2>"))
  end)
  T.it("same char = same level", function()
    local input = "One\n===\n\nTwo\n==="
    local html = M.rst(input)
    -- Both should be h1
    local _, n1 = html:gsub("<h1>", "")
    T.eq(n1, 2)
  end)
end)

T.describe("rst inline formatting", function()
  T.it("bold **text**", function()
    local html = M.rst("**bold**")
    T.ok(html:find("<strong>bold</strong>"))
  end)
  T.it("italic *text*", function()
    local html = M.rst("*italic*")
    T.ok(html:find("<em>italic</em>"))
  end)
  T.it("inline code ``text``", function()
    local html = M.rst("``code here``")
    T.ok(html:find("<code>code here</code>"))
  end)
end)

T.describe("rst lists", function()
  T.it("unordered list", function()
    local html = M.rst("- alpha\n- beta")
    T.ok(html:find("<ul>"))
    T.ok(html:find("<li>alpha</li>"))
    T.ok(html:find("<li>beta</li>"))
  end)
  T.it("ordered list", function()
    local html = M.rst("#. first\n#. second")
    T.ok(html:find("<ol>"))
    T.ok(html:find("<li>first</li>"))
  end)
end)

T.describe("rst code-block directive", function()
  T.it("code-block directive", function()
    local input = ".. code-block:: python\n\n   x = 1\n   y = 2"
    local html = M.rst(input)
    T.ok(html:find("<pre>"))
    T.ok(html:find("x = 1"))
  end)
end)

-- ============================================================
-- AsciiDoc: Headings and inline formatting
-- ============================================================
T.describe("asciidoc headings", function()
  T.it("= h1", function()
    local html = M.asciidoc("= Document Title")
    T.ok(html:find("<h1>Document Title</h1>"))
  end)
  T.it("== h2", function()
    local html = M.asciidoc("== Section")
    T.ok(html:find("<h2>Section</h2>"))
  end)
  T.it("=== h3", function()
    local html = M.asciidoc("=== Subsection")
    T.ok(html:find("<h3>Subsection</h3>"))
  end)
  T.it("clamps at h6", function()
    local html = M.asciidoc("======= Deep")
    T.ok(html:find("<h6>Deep</h6>"))
  end)
end)

T.describe("asciidoc inline formatting", function()
  T.it("bold *text*", function()
    local html = M.asciidoc("*bold*")
    T.ok(html:find("<strong>bold</strong>"))
  end)
  T.it("italic _text_", function()
    local html = M.asciidoc("_italic_")
    T.ok(html:find("<em>italic</em>"))
  end)
  T.it("inline code `text`", function()
    local html = M.asciidoc("`code`")
    T.ok(html:find("<code>code</code>"))
  end)
end)

T.describe("asciidoc lists", function()
  T.it("unordered list", function()
    local html = M.asciidoc("* item1\n* item2")
    T.ok(html:find("<ul>"))
    T.ok(html:find("<li>item1</li>"))
  end)
  T.it("ordered list", function()
    local html = M.asciidoc(". step1\n. step2")
    T.ok(html:find("<ol>"))
    T.ok(html:find("<li>step1</li>"))
  end)
end)

T.describe("asciidoc horizontal rule", function()
  T.it("---- horizontal rule", function()
    local html = M.asciidoc("----")
    T.ok(html:find("<hr>"))
  end)
end)

T.describe("asciidoc code block", function()
  T.it(".... delimited code block", function()
    local html = M.asciidoc("....\nsome code\n....")
    T.ok(html:find("<pre>"))
    T.ok(html:find("some code"))
  end)
  T.it("[source,lua] with ---- delimiter", function()
    local html = M.asciidoc("[source,lua]\n----\nlocal x = 1\n----")
    T.ok(html:find('language%-lua'))
    T.ok(html:find("local x = 1"))
  end)
end)

-- ============================================================
-- Combined: document with multiple elements
-- ============================================================
T.describe("markdown complex document", function()
  T.it("heading + paragraph + list", function()
    local input = "# Title\n\nSome text here.\n\n- item A\n- item B\n"
    local html = M.markdown(input)
    T.ok(html:find("<h1>Title</h1>"))
    T.ok(html:find("<p>Some text here.</p>"))
    T.ok(html:find("<ul>"))
    T.ok(html:find("<li>item A</li>"))
  end)
  T.it("heading + code block + paragraph", function()
    local input = "## Code Example\n\n```lua\nprint('hi')\n```\n\nAfter block."
    local html = M.markdown(input)
    T.ok(html:find("<h2>Code Example</h2>"))
    T.ok(html:find("language%-lua"))
    T.ok(html:find("<p>After block.</p>"))
  end)
end)
