if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local bigint = require("lib.bigint")

-- ── Construction ─────────────────────────────────────────────────────────────

T.describe("bigint.new", function()
  T.it("creates from small number", function()
    local a = bigint.new(42)
    T.eq(a:to_string(), "42")
  end)
  T.it("creates from zero", function()
    T.eq(bigint.new(0):to_string(), "0")
  end)
  T.it("creates from negative number", function()
    T.eq(bigint.new(-123):to_string(), "-123")
  end)
  T.it("creates from string", function()
    T.eq(bigint.new("12345678901234567890"):to_string(), "12345678901234567890")
  end)
  T.it("creates from negative string", function()
    T.eq(bigint.new("-99999999999999"):to_string(), "-99999999999999")
  end)
  T.it("creates from string with leading zeros", function()
    T.eq(bigint.new("000123"):to_string(), "123")
  end)
  T.it("clones another bigint", function()
    local a = bigint.new(42)
    local b = bigint.new(a)
    T.eq(b:to_string(), "42")
    -- mutation of b should not affect a
    b.d[1] = 99
    T.eq(a:to_string(), "42")
  end)
  T.it("returns nil,errmsg for empty string", function()
    local v, err = bigint.new("")
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns nil,errmsg for non-digit string", function()
    local v, err = bigint.new("abc")
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("returns nil,errmsg for bad type", function()
    local v, err = bigint.new(true)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("handles very large number string", function()
    local s = "9" .. ("0"):rep(99)
    local a = bigint.new(s)
    T.eq(a:to_string(), s)
  end)
end)

-- ── Hex construction ─────────────────────────────────────────────────────────

T.describe("bigint.from_hex", function()
  T.it("parses simple hex", function()
    T.eq(bigint.from_hex("FF"):to_string(), "255")
  end)
  T.it("parses DEADBEEF", function()
    T.eq(bigint.from_hex("DEADBEEF"):to_string(), "3735928559")
  end)
  T.it("parses lowercase", function()
    T.eq(bigint.from_hex("deadbeef"):to_string(), "3735928559")
  end)
  T.it("parses with 0x prefix", function()
    T.eq(bigint.from_hex("0xFF"):to_string(), "255")
  end)
  T.it("parses negative hex", function()
    T.eq(bigint.from_hex("-A"):to_string(), "-10")
  end)
  T.it("parses zero", function()
    T.eq(bigint.from_hex("0"):to_string(), "0")
  end)
  T.it("parses large hex", function()
    T.eq(bigint.from_hex("FFFFFFFFFFFFFFFF"):to_string(), "18446744073709551615")
  end)
  T.it("returns nil,errmsg for invalid hex", function()
    local v, err = bigint.from_hex("GG")
    T.eq(v, nil)
    T.ok(err)
  end)
end)

-- ── Basic arithmetic ─────────────────────────────────────────────────────────

T.describe("addition", function()
  T.it("adds two positive numbers", function()
    T.eq(bigint.new(123):add(bigint.new(456)):to_string(), "579")
  end)
  T.it("adds with carry across chunks", function()
    T.eq(bigint.new(9999999):add(bigint.new(1)):to_string(), "10000000")
  end)
  T.it("adds large numbers", function()
    local a = bigint.new("99999999999999999999999999999")
    local b = bigint.new("1")
    T.eq(a:add(b):to_string(), "100000000000000000000000000000")
  end)
  T.it("adds positive and negative", function()
    T.eq(bigint.new(10):add(bigint.new(-3)):to_string(), "7")
  end)
  T.it("adds negative and positive", function()
    T.eq(bigint.new(-10):add(bigint.new(3)):to_string(), "-7")
  end)
  T.it("adds two negatives", function()
    T.eq(bigint.new(-5):add(bigint.new(-3)):to_string(), "-8")
  end)
  T.it("adds to zero result", function()
    T.eq(bigint.new(42):add(bigint.new(-42)):to_string(), "0")
  end)
  T.it("adds zero", function()
    T.eq(bigint.new(42):add(bigint.new(0)):to_string(), "42")
  end)
end)

T.describe("subtraction", function()
  T.it("subtracts smaller from larger", function()
    T.eq(bigint.new(10):sub(bigint.new(3)):to_string(), "7")
  end)
  T.it("subtracts larger from smaller", function()
    T.eq(bigint.new(3):sub(bigint.new(10)):to_string(), "-7")
  end)
  T.it("subtracts equal values", function()
    T.eq(bigint.new(42):sub(bigint.new(42)):to_string(), "0")
  end)
  T.it("subtracts with borrow across chunks", function()
    T.eq(bigint.new(10000000):sub(bigint.new(1)):to_string(), "9999999")
  end)
  T.it("subtracts negative from positive", function()
    T.eq(bigint.new(5):sub(bigint.new(-3)):to_string(), "8")
  end)
end)

T.describe("multiplication", function()
  T.it("multiplies small numbers", function()
    T.eq(bigint.new(6):mul(bigint.new(7)):to_string(), "42")
  end)
  T.it("multiplies by zero", function()
    T.eq(bigint.new(123456):mul(bigint.new(0)):to_string(), "0")
  end)
  T.it("multiplies by one", function()
    T.eq(bigint.new(42):mul(bigint.new(1)):to_string(), "42")
  end)
  T.it("multiplies large numbers", function()
    local a = bigint.new("12345678901234567890")
    local b = bigint.new("98765432109876543210")
    T.eq(a:mul(b):to_string(), "1219326311370217952237463801111263526900")
  end)
  T.it("multiplies with different signs", function()
    T.eq(bigint.new(-6):mul(bigint.new(7)):to_string(), "-42")
    T.eq(bigint.new(6):mul(bigint.new(-7)):to_string(), "-42")
    T.eq(bigint.new(-6):mul(bigint.new(-7)):to_string(), "42")
  end)
end)

-- ── Division ─────────────────────────────────────────────────────────────────

T.describe("division", function()
  T.it("divides evenly", function()
    T.eq(bigint.new(42):div(bigint.new(6)):to_string(), "7")
  end)
  T.it("divides with truncation", function()
    T.eq(bigint.new(10):div(bigint.new(3)):to_string(), "3")
  end)
  T.it("divides large by small", function()
    T.eq(bigint.new("1000000000000"):div(bigint.new(7)):to_string(), "142857142857")
  end)
  T.it("divides large by large", function()
    local a = bigint.new("100000000000000000000")
    local b = bigint.new("33333333333")
    T.eq(a:div(b):to_string(), "3000000000")
  end)
  T.it("divides smaller by larger gives zero", function()
    T.eq(bigint.new(3):div(bigint.new(10)):to_string(), "0")
  end)
  T.it("returns nil,errmsg for division by zero", function()
    local v, err = bigint.new(1):div(bigint.new(0))
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("handles negative division", function()
    T.eq(bigint.new(-42):div(bigint.new(6)):to_string(), "-7")
    T.eq(bigint.new(42):div(bigint.new(-6)):to_string(), "-7")
    T.eq(bigint.new(-42):div(bigint.new(-6)):to_string(), "7")
  end)
end)

T.describe("mod", function()
  T.it("computes remainder", function()
    T.eq(bigint.new(10):mod(bigint.new(3)):to_string(), "1")
  end)
  T.it("zero remainder", function()
    T.eq(bigint.new(42):mod(bigint.new(6)):to_string(), "0")
  end)
  T.it("returns nil,errmsg for mod by zero", function()
    local v, err = bigint.new(1):mod(bigint.new(0))
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("divmod", function()
  T.it("returns quotient and remainder", function()
    local q, r = bigint.new(17):divmod(bigint.new(5))
    T.eq(q:to_string(), "3")
    T.eq(r:to_string(), "2")
  end)
  T.it("returns nil,errmsg for zero divisor", function()
    local q, err = bigint.new(1):divmod(bigint.new(0))
    T.eq(q, nil)
    T.ok(err)
  end)
  T.it("quotient * divisor + remainder = dividend", function()
    local a = bigint.new("123456789012345678901234567890")
    local b = bigint.new("9876543210")
    local q, r = a:divmod(b)
    T.eq(q:mul(b):add(r):to_string(), a:to_string())
  end)
end)

-- ── Exponentiation ───────────────────────────────────────────────────────────

T.describe("pow", function()
  T.it("raises to power 0", function()
    T.eq(bigint.new(42):pow(0):to_string(), "1")
  end)
  T.it("raises to power 1", function()
    T.eq(bigint.new(42):pow(1):to_string(), "42")
  end)
  T.it("raises to power 2", function()
    T.eq(bigint.new(99):pow(2):to_string(), "9801")
  end)
  T.it("computes 2^64", function()
    T.eq(bigint.new(2):pow(64):to_string(), "18446744073709551616")
  end)
  T.it("computes 10^20", function()
    T.eq(bigint.new(10):pow(20):to_string(), "1" .. ("0"):rep(20))
  end)
  T.it("returns nil,errmsg for negative exponent", function()
    local v, err = bigint.new(2):pow(-1)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("negative base even exponent", function()
    T.eq(bigint.new(-3):pow(4):to_string(), "81")
  end)
  T.it("negative base odd exponent", function()
    T.eq(bigint.new(-3):pow(3):to_string(), "-27")
  end)
end)

-- ── Unary operations ─────────────────────────────────────────────────────────

T.describe("unary", function()
  T.it("abs of positive", function()
    T.eq(bigint.new(42):abs():to_string(), "42")
  end)
  T.it("abs of negative", function()
    T.eq(bigint.new(-42):abs():to_string(), "42")
  end)
  T.it("abs of zero", function()
    T.eq(bigint.new(0):abs():to_string(), "0")
  end)
  T.it("neg of positive", function()
    T.eq(bigint.new(42):neg():to_string(), "-42")
  end)
  T.it("neg of negative", function()
    T.eq(bigint.new(-42):neg():to_string(), "42")
  end)
  T.it("neg of zero", function()
    T.eq(bigint.new(0):neg():to_string(), "0")
  end)
  T.it("sign of positive", function()
    T.eq(bigint.new(42):sign(), 1)
  end)
  T.it("sign of negative", function()
    T.eq(bigint.new(-42):sign(), -1)
  end)
  T.it("sign of zero", function()
    T.eq(bigint.new(0):sign(), 0)
  end)
end)

-- ── Comparison ───────────────────────────────────────────────────────────────

T.describe("comparison", function()
  T.it("eq with equal values", function()
    T.ok(bigint.new(42):eq(bigint.new(42)))
  end)
  T.it("eq with different values", function()
    T.fail(bigint.new(42):eq(bigint.new(43)))
  end)
  T.it("eq zero variants", function()
    T.ok(bigint.new(0):eq(bigint.new("-0")))
  end)
  T.it("lt positive", function()
    T.ok(bigint.new(3):lt(bigint.new(10)))
    T.fail(bigint.new(10):lt(bigint.new(3)))
    T.fail(bigint.new(5):lt(bigint.new(5)))
  end)
  T.it("lt negative", function()
    T.ok(bigint.new(-10):lt(bigint.new(-3)))
  end)
  T.it("lt mixed signs", function()
    T.ok(bigint.new(-1):lt(bigint.new(1)))
    T.fail(bigint.new(1):lt(bigint.new(-1)))
  end)
  T.it("le", function()
    T.ok(bigint.new(3):le(bigint.new(3)))
    T.ok(bigint.new(3):le(bigint.new(10)))
    T.fail(bigint.new(10):le(bigint.new(3)))
  end)
  T.it("gt", function()
    T.ok(bigint.new(10):gt(bigint.new(3)))
    T.fail(bigint.new(3):gt(bigint.new(10)))
  end)
  T.it("ge", function()
    T.ok(bigint.new(10):ge(bigint.new(10)))
    T.ok(bigint.new(10):ge(bigint.new(3)))
    T.fail(bigint.new(3):ge(bigint.new(10)))
  end)
end)

-- ── Predicates ───────────────────────────────────────────────────────────────

T.describe("predicates", function()
  T.it("is_zero", function()
    T.ok(bigint.new(0):is_zero())
    T.fail(bigint.new(1):is_zero())
  end)
  T.it("is_positive", function()
    T.ok(bigint.new(1):is_positive())
    T.fail(bigint.new(0):is_positive())
    T.fail(bigint.new(-1):is_positive())
  end)
  T.it("is_negative", function()
    T.ok(bigint.new(-1):is_negative())
    T.fail(bigint.new(0):is_negative())
    T.fail(bigint.new(1):is_negative())
  end)
  T.it("is_even", function()
    T.ok(bigint.new(0):is_even())
    T.ok(bigint.new(2):is_even())
    T.ok(bigint.new(-4):is_even())
    T.fail(bigint.new(3):is_even())
  end)
  T.it("is_odd", function()
    T.ok(bigint.new(1):is_odd())
    T.ok(bigint.new(-3):is_odd())
    T.fail(bigint.new(0):is_odd())
    T.fail(bigint.new(2):is_odd())
  end)
end)

-- ── Conversion ───────────────────────────────────────────────────────────────

T.describe("to_number", function()
  T.it("converts small bigint to number", function()
    T.eq(bigint.new(42):to_number(), 42)
  end)
  T.it("converts negative to number", function()
    T.eq(bigint.new(-7):to_number(), -7)
  end)
  T.it("converts zero to number", function()
    T.eq(bigint.new(0):to_number(), 0)
  end)
end)

T.describe("to_hex", function()
  T.it("converts 255 to FF", function()
    T.eq(bigint.new(255):to_hex(), "FF")
  end)
  T.it("converts DEADBEEF roundtrip", function()
    T.eq(bigint.from_hex("DEADBEEF"):to_hex(), "DEADBEEF")
  end)
  T.it("converts zero", function()
    T.eq(bigint.new(0):to_hex(), "0")
  end)
  T.it("converts negative", function()
    T.eq(bigint.new(-255):to_hex(), "-FF")
  end)
  T.it("converts 2^64", function()
    T.eq(bigint.new(2):pow(64):to_hex(), "10000000000000000")
  end)
  T.it("converts large hex roundtrip", function()
    T.eq(bigint.from_hex("FFFFFFFFFFFFFFFF"):to_hex(), "FFFFFFFFFFFFFFFF")
  end)
end)

T.describe("to_string", function()
  T.it("preserves all digits of large number", function()
    local s = "12345678901234567890123456789012345678901234567890"
    T.eq(bigint.new(s):to_string(), s)
  end)
  T.it("pads internal chunks with leading zeros", function()
    -- 10000001 = chunk[1]=0000001, chunk[2]=1 => "10000001"
    T.eq(bigint.new(10000001):to_string(), "10000001")
  end)
end)

-- ── GCD / LCM ────────────────────────────────────────────────────────────────

T.describe("gcd", function()
  T.it("gcd(12, 8) = 4", function()
    T.eq(bigint.gcd(bigint.new(12), bigint.new(8)):to_string(), "4")
  end)
  T.it("gcd(0, 5) = 5", function()
    T.eq(bigint.gcd(bigint.new(0), bigint.new(5)):to_string(), "5")
  end)
  T.it("gcd(7, 13) = 1 (coprime)", function()
    T.eq(bigint.gcd(bigint.new(7), bigint.new(13)):to_string(), "1")
  end)
  T.it("gcd ignores sign", function()
    T.eq(bigint.gcd(bigint.new(-12), bigint.new(8)):to_string(), "4")
  end)
  T.it("gcd of large numbers", function()
    local a = bigint.new("123456789012345678901234567890")
    local b = bigint.new("987654321098765432109876543210")
    local g = bigint.gcd(a, b)
    -- Verify it divides both
    T.eq(a:mod(g):to_string(), "0")
    T.eq(b:mod(g):to_string(), "0")
  end)
end)

T.describe("lcm", function()
  T.it("lcm(4, 6) = 12", function()
    T.eq(bigint.lcm(bigint.new(4), bigint.new(6)):to_string(), "12")
  end)
  T.it("lcm(0, 5) = 0", function()
    T.eq(bigint.lcm(bigint.new(0), bigint.new(5)):to_string(), "0")
  end)
  T.it("lcm(7, 13) = 91", function()
    T.eq(bigint.lcm(bigint.new(7), bigint.new(13)):to_string(), "91")
  end)
end)

-- ── Min / Max ────────────────────────────────────────────────────────────────

T.describe("min/max", function()
  T.it("max of two positives", function()
    T.eq(bigint.max(bigint.new(3), bigint.new(10)):to_string(), "10")
  end)
  T.it("min of two positives", function()
    T.eq(bigint.min(bigint.new(3), bigint.new(10)):to_string(), "3")
  end)
  T.it("max with negative", function()
    T.eq(bigint.max(bigint.new(-5), bigint.new(3)):to_string(), "3")
  end)
  T.it("min with negative", function()
    T.eq(bigint.min(bigint.new(-5), bigint.new(3)):to_string(), "-5")
  end)
end)

-- ── Factorial ────────────────────────────────────────────────────────────────

T.describe("factorial", function()
  T.it("0! = 1", function()
    T.eq(bigint.factorial(0):to_string(), "1")
  end)
  T.it("1! = 1", function()
    T.eq(bigint.factorial(1):to_string(), "1")
  end)
  T.it("5! = 120", function()
    T.eq(bigint.factorial(5):to_string(), "120")
  end)
  T.it("10! = 3628800", function()
    T.eq(bigint.factorial(10):to_string(), "3628800")
  end)
  T.it("20! = 2432902008176640000", function()
    T.eq(bigint.factorial(20):to_string(), "2432902008176640000")
  end)
  T.it("50! has correct value", function()
    T.eq(bigint.factorial(50):to_string(),
      "30414093201713378043612608166064768844377641568960512000000000000")
  end)
  T.it("returns nil,errmsg for negative", function()
    local v, err = bigint.factorial(-1)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

-- ── Metamethods ──────────────────────────────────────────────────────────────

T.describe("metamethods", function()
  T.it("tostring", function()
    T.eq(tostring(bigint.new(42)), "42")
  end)
  T.it("__add", function()
    T.eq((bigint.new(3) + bigint.new(4)):to_string(), "7")
  end)
  T.it("__sub", function()
    T.eq((bigint.new(10) - bigint.new(3)):to_string(), "7")
  end)
  T.it("__mul", function()
    T.eq((bigint.new(6) * bigint.new(7)):to_string(), "42")
  end)
  T.it("__div", function()
    T.eq((bigint.new(42) / bigint.new(6)):to_string(), "7")
  end)
  T.it("__mod", function()
    T.eq((bigint.new(10) % bigint.new(3)):to_string(), "1")
  end)
  T.it("__unm", function()
    T.eq((-bigint.new(42)):to_string(), "-42")
  end)
  T.it("__eq", function()
    T.ok(bigint.new(42) == bigint.new(42))
  end)
  T.it("__lt", function()
    T.ok(bigint.new(3) < bigint.new(10))
    T.fail(bigint.new(10) < bigint.new(3))
  end)
  T.it("__le", function()
    T.ok(bigint.new(3) <= bigint.new(3))
    T.ok(bigint.new(3) <= bigint.new(10))
  end)
  T.it("__pow", function()
    T.eq((bigint.new(2) ^ 10):to_string(), "1024")
  end)
end)

-- ── Edge cases ───────────────────────────────────────────────────────────────

T.describe("edge cases", function()
  T.it("negative zero normalizes to zero", function()
    local a = bigint.new("-0")
    T.eq(a:to_string(), "0")
    T.eq(a:sign(), 0)
    T.ok(a:is_zero())
  end)
  T.it("one", function()
    T.eq(bigint.new(1):to_string(), "1")
  end)
  T.it("negative one", function()
    T.eq(bigint.new(-1):to_string(), "-1")
  end)
  T.it("add identity", function()
    local a = bigint.new("99999999999999999999")
    T.eq(a:add(bigint.new(0)):to_string(), a:to_string())
  end)
  T.it("mul identity", function()
    local a = bigint.new("99999999999999999999")
    T.eq(a:mul(bigint.new(1)):to_string(), a:to_string())
  end)
  T.it("sub self", function()
    local a = bigint.new("12345678901234567890")
    T.eq(a:sub(a):to_string(), "0")
  end)
  T.it("div self", function()
    local a = bigint.new("12345678901234567890")
    T.eq(a:div(a):to_string(), "1")
  end)
  T.it("constants are immutable-ish", function()
    -- ZERO and ONE should remain unchanged after operations
    T.eq(bigint.ZERO:to_string(), "0")
    T.eq(bigint.ONE:to_string(), "1")
  end)
  T.it("many chunk boundary", function()
    -- 7 digits per chunk: 28-digit number = 4 chunks
    local a = bigint.new("1234567890123456789012345678")
    local b = bigint.new("8765432109876543210987654322")
    T.eq(a:add(b):to_string(), "10000000000000000000000000000")
  end)
  T.it("large multiplication result", function()
    local a = bigint.new(2):pow(128)
    T.eq(a:to_string(), "340282366920938463463374607431768211456")
  end)
end)
