if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local V = require("lib.validate")

T.describe("validate", function()

  T.describe("V.string()", function()
    T.it("accepts strings", function()
      local ok, err = V.string()("hello")
      T.eq(ok, true)
      T.eq(err, nil)
    end)
    T.it("rejects non-strings", function()
      local ok, err = V.string()(123)
      T.eq(ok, nil)
      T.ok(err:find("expected string"))
    end)
    T.it("rejects nil", function()
      local ok, err = V.string()(nil)
      T.eq(ok, nil)
      T.ok(err:find("expected string, got nil"))
    end)
    T.it("rejects booleans", function()
      local ok, err = V.string()(true)
      T.eq(ok, nil)
      T.ok(err:find("expected string, got boolean"))
    end)
  end)

  T.describe("V.string() with constraints", function()
    T.it("enforces min length", function()
      local v = V.string({ min = 3 })
      T.eq(v("abc"), true)
      local ok, err = v("ab")
      T.eq(ok, nil)
      T.ok(err:find("less than minimum"))
    end)
    T.it("enforces max length", function()
      local v = V.string({ max = 3 })
      T.eq(v("abc"), true)
      local ok, err = v("abcd")
      T.eq(ok, nil)
      T.ok(err:find("greater than maximum"))
    end)
    T.it("enforces pattern", function()
      local v = V.string({ pattern = "^%d+$" })
      T.eq(v("123"), true)
      local ok, err = v("abc")
      T.eq(ok, nil)
      T.ok(err:find("does not match pattern"))
    end)
    T.it("enforces enum", function()
      local v = V.string({ enum = { "a", "b", "c" } })
      T.eq(v("a"), true)
      T.eq(v("b"), true)
      T.eq(v("c"), true)
      local ok, err = v("d")
      T.eq(ok, nil)
      T.ok(err:find("not one of"))
    end)
    T.it("combines constraints", function()
      local v = V.string({ min = 1, max = 5, pattern = "^%a+$" })
      T.eq(v("abc"), true)
      local ok1, _ = v("")
      T.eq(ok1, nil)
      local ok2, _ = v("abcdef")
      T.eq(ok2, nil)
      local ok3, _ = v("123")
      T.eq(ok3, nil)
    end)
  end)

  T.describe("V.number()", function()
    T.it("accepts numbers", function()
      T.eq(V.number()(42), true)
      T.eq(V.number()(3.14), true)
      T.eq(V.number()(0), true)
      T.eq(V.number()(-1), true)
    end)
    T.it("rejects non-numbers", function()
      local ok, err = V.number()("42")
      T.eq(ok, nil)
      T.ok(err:find("expected number"))
    end)
    T.it("enforces min", function()
      local v = V.number({ min = 0 })
      T.eq(v(0), true)
      T.eq(v(1), true)
      local ok, err = v(-1)
      T.eq(ok, nil)
      T.ok(err:find("less than minimum"))
    end)
    T.it("enforces max", function()
      local v = V.number({ max = 100 })
      T.eq(v(100), true)
      local ok, err = v(101)
      T.eq(ok, nil)
      T.ok(err:find("greater than maximum"))
    end)
    T.it("enforces integer option", function()
      local v = V.number({ integer = true })
      T.eq(v(5), true)
      local ok, err = v(5.5)
      T.eq(ok, nil)
      T.ok(err:find("expected integer"))
    end)
  end)

  T.describe("V.integer()", function()
    T.it("accepts integers", function()
      T.eq(V.integer()(0), true)
      T.eq(V.integer()(42), true)
      T.eq(V.integer()(-10), true)
    end)
    T.it("rejects floats", function()
      local ok, err = V.integer()(3.14)
      T.eq(ok, nil)
      T.ok(err:find("expected integer, got float"))
    end)
    T.it("rejects non-numbers", function()
      local ok, err = V.integer()("5")
      T.eq(ok, nil)
      T.ok(err:find("expected integer, got string"))
    end)
    T.it("enforces min", function()
      local v = V.integer({ min = 1 })
      T.eq(v(1), true)
      local ok, err = v(0)
      T.eq(ok, nil)
      T.ok(err:find("less than minimum"))
    end)
    T.it("enforces max", function()
      local v = V.integer({ max = 10 })
      T.eq(v(10), true)
      local ok, err = v(11)
      T.eq(ok, nil)
      T.ok(err:find("greater than maximum"))
    end)
  end)

  T.describe("V.boolean()", function()
    T.it("accepts booleans", function()
      T.eq(V.boolean()(true), true)
      T.eq(V.boolean()(false), true)
    end)
    T.it("rejects non-booleans", function()
      local ok, err = V.boolean()(1)
      T.eq(ok, nil)
      T.ok(err:find("expected boolean"))
      ok, err = V.boolean()("true")
      T.eq(ok, nil)
      T.ok(err:find("expected boolean"))
    end)
  end)

  T.describe("V.table()", function()
    T.it("accepts tables", function()
      T.eq(V.table()({}), true)
      T.eq(V.table()({ 1, 2, 3 }), true)
    end)
    T.it("rejects non-tables", function()
      local ok, err = V.table()("hello")
      T.eq(ok, nil)
      T.ok(err:find("expected table"))
    end)
  end)

  T.describe("V.func()", function()
    T.it("accepts functions", function()
      T.eq(V.func()(print), true)
      T.eq(V.func()(function() end), true)
    end)
    T.it("rejects non-functions", function()
      local ok, err = V.func()("hello")
      T.eq(ok, nil)
      T.ok(err:find("expected function"))
    end)
  end)

  T.describe("V.any()", function()
    T.it("accepts anything", function()
      T.eq(V.any()(nil), true)
      T.eq(V.any()("hello"), true)
      T.eq(V.any()(42), true)
      T.eq(V.any()(true), true)
      T.eq(V.any()({}), true)
    end)
  end)

  T.describe("V.nil_()", function()
    T.it("accepts nil", function()
      T.eq(V.nil_()(nil), true)
    end)
    T.it("rejects non-nil", function()
      local ok, err = V.nil_()(0)
      T.eq(ok, nil)
      T.ok(err:find("expected nil"))
      ok, err = V.nil_()("")
      T.eq(ok, nil)
      T.ok(err:find("expected nil"))
    end)
  end)

  T.describe("V.literal()", function()
    T.it("accepts exact match", function()
      T.eq(V.literal(42)(42), true)
      T.eq(V.literal("hello")("hello"), true)
      T.eq(V.literal(true)(true), true)
    end)
    T.it("rejects non-match", function()
      local ok, err = V.literal(42)(43)
      T.eq(ok, nil)
      T.ok(err:find("expected literal 42"))
      ok, err = V.literal("a")("b")
      T.eq(ok, nil)
      T.ok(err:find("expected literal 'a'"))
    end)
  end)

  T.describe("V.optional()", function()
    T.it("accepts nil", function()
      T.eq(V.optional(V.string())(nil), true)
    end)
    T.it("accepts valid value", function()
      T.eq(V.optional(V.string())("hello"), true)
    end)
    T.it("rejects invalid value", function()
      local ok, err = V.optional(V.string())(123)
      T.eq(ok, nil)
      T.ok(err:find("expected string"))
    end)
  end)

  T.describe("V.one_of()", function()
    T.it("accepts if any validator passes", function()
      local v = V.one_of(V.string(), V.number())
      T.eq(v("hello"), true)
      T.eq(v(42), true)
    end)
    T.it("rejects if all fail", function()
      local v = V.one_of(V.string(), V.number())
      local ok, err = v(true)
      T.eq(ok, nil)
      T.ok(err:find("none of the validators matched"))
    end)
    T.it("works with one validator", function()
      local v = V.one_of(V.string())
      T.eq(v("ok"), true)
      local ok, _ = v(1)
      T.eq(ok, nil)
    end)
  end)

  T.describe("V.all_of()", function()
    T.it("passes when all pass", function()
      local v = V.all_of(V.number(), V.number({ min = 0 }))
      T.eq(v(5), true)
    end)
    T.it("fails on first failure", function()
      local v = V.all_of(V.number(), V.number({ min = 10 }))
      local ok, err = v(5)
      T.eq(ok, nil)
      T.ok(err:find("less than minimum"))
    end)
    T.it("fails if type is wrong", function()
      local v = V.all_of(V.number(), V.number({ min = 0 }))
      local ok, err = v("hello")
      T.eq(ok, nil)
      T.ok(err:find("expected number"))
    end)
  end)

  T.describe("V.array()", function()
    T.it("accepts valid arrays", function()
      T.eq(V.array(V.string())({"a", "b", "c"}), true)
      T.eq(V.array(V.number())({1, 2, 3}), true)
    end)
    T.it("accepts empty arrays", function()
      T.eq(V.array(V.string())({}), true)
    end)
    T.it("rejects non-tables", function()
      local ok, err = V.array(V.string())("hello")
      T.eq(ok, nil)
      T.ok(err:find("expected array"))
    end)
    T.it("rejects invalid elements", function()
      local ok, err = V.array(V.string())({"a", 2, "c"})
      T.eq(ok, nil)
      T.ok(err:find("%[2%]"))
      T.ok(err:find("expected string"))
    end)
    T.it("reports multiple element errors", function()
      local ok, err = V.array(V.string())({1, 2, 3})
      T.eq(ok, nil)
      T.ok(err:find("%[1%]"))
      T.ok(err:find("%[2%]"))
      T.ok(err:find("%[3%]"))
    end)
    T.it("enforces min length", function()
      local v = V.array(V.string(), { min = 2 })
      T.eq(v({"a", "b"}), true)
      local ok, err = v({"a"})
      T.eq(ok, nil)
      T.ok(err:find("less than minimum"))
    end)
    T.it("enforces max length", function()
      local v = V.array(V.string(), { max = 2 })
      T.eq(v({"a", "b"}), true)
      local ok, err = v({"a", "b", "c"})
      T.eq(ok, nil)
      T.ok(err:find("greater than maximum"))
    end)
  end)

  T.describe("V.map()", function()
    T.it("accepts valid maps", function()
      T.eq(V.map(V.string(), V.number())({ x = 1, y = 2 }), true)
    end)
    T.it("accepts empty maps", function()
      T.eq(V.map(V.string(), V.number())({}), true)
    end)
    T.it("rejects non-tables", function()
      local ok, err = V.map(V.string(), V.number())("hello")
      T.eq(ok, nil)
      T.ok(err:find("expected map"))
    end)
    T.it("rejects invalid keys", function()
      local t = {}
      t[1] = "hello"
      local ok, err = V.map(V.string(), V.string())(t)
      T.eq(ok, nil)
      T.ok(err:find("key 1"))
    end)
    T.it("rejects invalid values", function()
      local ok, err = V.map(V.string(), V.number())({ x = "oops" })
      T.eq(ok, nil)
      T.ok(err:find("%[x%]"))
      T.ok(err:find("expected number"))
    end)
  end)

  T.describe("V.record()", function()
    T.it("accepts valid records", function()
      local v = V.record({ name = V.string(), age = V.integer() })
      T.eq(v({ name = "Alice", age = 30 }), true)
    end)
    T.it("allows extra fields", function()
      local v = V.record({ name = V.string() })
      T.eq(v({ name = "Alice", extra = true }), true)
    end)
    T.it("rejects missing required fields", function()
      local v = V.record({ name = V.string(), age = V.integer() })
      local ok, err = v({ name = "Alice" })
      T.eq(ok, nil)
      T.ok(err:find("age"))
      T.ok(err:find("expected integer, got nil"))
    end)
    T.it("rejects wrong field types", function()
      local v = V.record({ name = V.string(), age = V.integer() })
      local ok, err = v({ name = 123, age = "old" })
      T.eq(ok, nil)
      T.ok(err:find("name: expected string"))
      T.ok(err:find("age: expected integer"))
    end)
    T.it("rejects non-tables", function()
      local v = V.record({ name = V.string() })
      local ok, err = v("hello")
      T.eq(ok, nil)
      T.ok(err:find("expected record"))
    end)
    T.it("accepts empty record schema", function()
      local v = V.record({})
      T.eq(v({}), true)
      T.eq(v({ anything = true }), true)
    end)
    T.it("nil input to record", function()
      local v = V.record({ name = V.string() })
      local ok, err = v(nil)
      T.eq(ok, nil)
      T.ok(err:find("expected record, got nil"))
    end)
  end)

  T.describe("V.record() with optional fields", function()
    T.it("accepts missing optional fields", function()
      local v = V.record({
        name = V.string(),
        email = V.optional(V.string()),
      })
      T.eq(v({ name = "Alice" }), true)
    end)
    T.it("validates present optional fields", function()
      local v = V.record({
        name = V.string(),
        email = V.optional(V.string()),
      })
      local ok, err = v({ name = "Alice", email = 123 })
      T.eq(ok, nil)
      T.ok(err:find("email"))
    end)
  end)

  T.describe("nested records", function()
    T.it("validates nested structures", function()
      local v = V.record({
        user = V.record({
          name = V.string(),
          role = V.string({ enum = { "admin", "user" } }),
        }),
      })
      T.eq(v({ user = { name = "Alice", role = "admin" } }), true)
    end)
    T.it("reports nested errors with path", function()
      local v = V.record({
        user = V.record({
          name = V.string(),
          role = V.string({ enum = { "admin", "user" } }),
        }),
      })
      local ok, err = v({ user = { name = 123, role = "guest" } })
      T.eq(ok, nil)
      T.ok(err:find("user"))
      -- Inner record collects its own errors with field names
      T.ok(err:find("name: expected string"))
      T.ok(err:find("role"))
    end)
    T.it("reports missing nested record", function()
      local v = V.record({
        user = V.record({ name = V.string() }),
      })
      local ok, err = v({})
      T.eq(ok, nil)
      T.ok(err:find("user: expected record, got nil"))
    end)
  end)

  T.describe("array error paths", function()
    T.it("uses bracket notation for indices", function()
      local v = V.array(V.string())({1, "ok", 3})
      -- v is nil since it failed
      local ok, err = V.array(V.string())({1, "ok", 3})
      T.eq(ok, nil)
      T.ok(err:find("%[1%]"))
      T.ok(err:find("%[3%]"))
      -- [2] should not appear since "ok" is valid
      T.eq(err:find("%[2%]"), nil)
    end)
  end)

  T.describe("V.custom()", function()
    T.it("uses custom function", function()
      local even = V.custom(function(value)
        if type(value) ~= "number" then return nil, "expected number" end
        if value % 2 == 0 then return true end
        return nil, "must be even"
      end)
      T.eq(even(4), true)
      local ok, err = even(3)
      T.eq(ok, nil)
      T.eq(err, "must be even")
    end)
    T.it("works in records", function()
      local v = V.record({
        n = V.custom(function(value)
          if type(value) ~= "number" then return nil, "expected number" end
          if value > 0 then return true end
          return nil, "must be positive"
        end),
      })
      T.eq(v({ n = 5 }), true)
      local ok, err = v({ n = -1 })
      T.eq(ok, nil)
      T.ok(err:find("must be positive"))
    end)
  end)

  T.describe("complex nested structures", function()
    T.it("validates record with arrays of records", function()
      local v = V.record({
        name = V.string({ min = 1 }),
        tags = V.array(V.string()),
        addresses = V.array(V.record({
          street = V.string(),
          city = V.string(),
          zip = V.string({ pattern = "^%d%d%d%d%d$" }),
        })),
      })

      T.eq(v({
        name = "Alice",
        tags = { "vip", "active" },
        addresses = {
          { street = "123 Main St", city = "Springfield", zip = "12345" },
        },
      }), true)
    end)
    T.it("rejects nested invalid data", function()
      local v = V.record({
        items = V.array(V.record({
          id = V.integer({ min = 1 }),
          label = V.string(),
        })),
      })
      local ok, err = v({
        items = {
          { id = 1, label = "ok" },
          { id = -1, label = 42 },
        },
      })
      T.eq(ok, nil)
      T.ok(err:find("%[2%]"))
    end)
    T.it("validates deeply nested", function()
      local v = V.record({
        a = V.record({
          b = V.record({
            c = V.string(),
          }),
        }),
      })
      T.eq(v({ a = { b = { c = "deep" } } }), true)
      local ok, err = v({ a = { b = { c = 123 } } })
      T.eq(ok, nil)
      T.ok(err:find("expected string"))
    end)
  end)

  T.describe("edge cases", function()
    T.it("integer rejects NaN", function()
      local ok, err = V.integer()(0/0)
      T.eq(ok, nil)
      -- NaN ~= floor(NaN)
      T.ok(err:find("expected integer"))
    end)
    T.it("integer rejects inf", function()
      local ok, err = V.integer()(1/0)
      T.eq(ok, nil)
      T.ok(err:find("expected integer"))
    end)
    T.it("number accepts inf", function()
      T.eq(V.number()(1/0), true)
      T.eq(V.number()(-1/0), true)
    end)
    T.it("number accepts NaN", function()
      T.eq(V.number()(0/0), true)
    end)
    T.it("literal nil", function()
      T.eq(V.literal(nil)(nil), true)
      local ok, err = V.literal(nil)(0)
      T.eq(ok, nil)
    end)
    T.it("one_of with three types", function()
      local v = V.one_of(V.string(), V.number(), V.boolean())
      T.eq(v("a"), true)
      T.eq(v(1), true)
      T.eq(v(true), true)
      local ok, _ = v({})
      T.eq(ok, nil)
    end)
    T.it("all_of with custom validators", function()
      local positive = V.custom(function(v)
        if type(v) == "number" and v > 0 then return true end
        return nil, "must be positive"
      end)
      local small = V.custom(function(v)
        if type(v) == "number" and v < 100 then return true end
        return nil, "must be less than 100"
      end)
      local v = V.all_of(positive, small)
      T.eq(v(50), true)
      local ok1, err1 = v(-1)
      T.eq(ok1, nil)
      T.ok(err1:find("must be positive"))
      local ok2, err2 = v(200)
      T.eq(ok2, nil)
      T.ok(err2:find("must be less than 100"))
    end)
    T.it("array of arrays", function()
      local v = V.array(V.array(V.number()))
      T.eq(v({{1, 2}, {3, 4}}), true)
      local ok, err = v({{1, "x"}, {3, 4}})
      T.eq(ok, nil)
      T.ok(err:find("%[1%]"))
    end)
    T.it("map with number keys", function()
      local v = V.map(V.number(), V.string())
      local t = {}
      t[1] = "a"
      t[2] = "b"
      T.eq(v(t), true)
    end)
    T.it("optional with nil_()", function()
      -- optional(nil_()) should accept nil
      T.eq(V.optional(V.nil_())(nil), true)
    end)
    T.it("string with empty enum", function()
      local v = V.string({ enum = {} })
      local ok, err = v("anything")
      T.eq(ok, nil)
      T.ok(err:find("not one of"))
    end)
  end)
end)
