-- lib/unified/retext_sentence_spacing/retext_sentence_spacing_test.lua
local T      = require("lib.test.assert")
local retext = require("lib.unified.retext")
local plugin = require("lib.unified.retext_sentence_spacing")

T.describe("retext_sentence_spacing", function()
  T.it("populates root.data.sentence_spacing", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("Hello. World.")
    tree = proc:run(tree)
    T.ok(tree.data ~= nil, "data exists")
    T.ok(tree.data.sentence_spacing ~= nil, "sentence_spacing key exists")
    T.ok(type(tree.data.sentence_spacing) == "table", "is table")
  end)

  T.it("returns empty for correct single-space separation", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("Hello. World.")
    tree = proc:run(tree)
    T.eq(#tree.data.sentence_spacing, 0, "single space is correct")
  end)

  T.it("flags double space between sentences", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("Hello.  World.")
    tree = proc:run(tree)
    local ss = tree.data.sentence_spacing
    T.ok(#ss > 0, "double space flagged")
    T.eq(ss[1].actual, 2, "actual is 2")
    T.eq(ss[1].expected, 1, "expected is 1")
  end)

  T.it("opts.preferred=2 accepts double space", function()
    local proc = retext():use(function(processor)
      plugin.plugin(processor, { preferred = 2 })
    end)
    local tree = proc:parse("Hello.  World.")
    tree = proc:run(tree)
    T.eq(#tree.data.sentence_spacing, 0, "double space correct when preferred=2")
  end)

  T.it("opts.preferred=2 flags single space", function()
    local proc = retext():use(function(processor)
      plugin.plugin(processor, { preferred = 2 })
    end)
    local tree = proc:parse("Hello. World.")
    tree = proc:run(tree)
    local ss = tree.data.sentence_spacing
    T.ok(#ss > 0, "single space flagged when preferred=2")
    T.eq(ss[1].actual, 1)
    T.eq(ss[1].expected, 2)
  end)

  T.it("each finding has actual, expected, and sentence fields", function()
    local proc = retext():use(plugin.plugin)
    local tree = proc:parse("Hi.  There.")
    tree = proc:run(tree)
    local ss = tree.data.sentence_spacing
    T.ok(#ss > 0, "finding exists")
    T.ok(type(ss[1].actual) == "number", "actual is number")
    T.ok(type(ss[1].expected) == "number", "expected is number")
    T.ok(type(ss[1].sentence) == "string", "sentence is string")
  end)
end)
