if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local S = require("lib.soundex")

T.describe("soundex", function()

  T.describe("soundex (US National Archives standard)", function()
    T.it("Robert → R163", function()
      T.eq(S.soundex("Robert"), "R163")
    end)
    T.it("Rupert → R163 (sounds like Robert)", function()
      T.eq(S.soundex("Rupert"), "R163")
    end)
    T.it("Rubin → R150", function()
      T.eq(S.soundex("Rubin"), "R150")
    end)
    T.it("Tymczak → T522", function()
      T.eq(S.soundex("Tymczak"), "T522")
    end)
    T.it("Pfister → P236", function()
      T.eq(S.soundex("Pfister"), "P236")
    end)
    T.it("Honeyman → H555", function()
      T.eq(S.soundex("Honeyman"), "H555")
    end)
    T.it("Euler → E460", function()
      T.eq(S.soundex("Euler"), "E460")
    end)
    T.it("Ellery → E460", function()
      T.eq(S.soundex("Ellery"), "E460")
    end)
    T.it("Gauss → G200", function()
      T.eq(S.soundex("Gauss"), "G200")
    end)
    T.it("Ghosh → G200", function()
      T.eq(S.soundex("Ghosh"), "G200")
    end)
    T.it("Heilbronn → H416", function()
      T.eq(S.soundex("Heilbronn"), "H416")
    end)
    T.it("Kant → K530", function()
      T.eq(S.soundex("Kant"), "K530")
    end)
    T.it("Ladd → L300", function()
      T.eq(S.soundex("Ladd"), "L300")
    end)
    T.it("Lukasiewicz → L222", function()
      T.eq(S.soundex("Lukasiewicz"), "L222")
    end)
    T.it("Jackson → J250", function()
      T.eq(S.soundex("Jackson"), "J250")
    end)
    T.it("empty string returns nil+error", function()
      local v, err = S.soundex("")
      T.eq(v, nil)
      T.ok(err ~= nil, "error message returned")
    end)
    T.it("lowercase input is handled", function()
      T.eq(S.soundex("robert"), "R163")
    end)
    T.it("mixed case input is handled", function()
      T.eq(S.soundex("RoBerT"), "R163")
    end)
  end)

  T.describe("soundex_refined", function()
    T.it("returns a string for Robert", function()
      local r = S.soundex_refined("Robert")
      T.ok(type(r) == "string", "returns string")
      T.ok(r:sub(1, 1) == "R", "starts with R")
    end)
    T.it("returns a string for Rupert", function()
      local r = S.soundex_refined("Rupert")
      T.ok(type(r) == "string")
    end)
    T.it("empty string returns nil+error", function()
      local v, err = S.soundex_refined("")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("result is at least 1 character", function()
      local r = S.soundex_refined("Smith")
      T.ok(#r >= 1)
    end)
  end)

  T.describe("metaphone", function()
    T.it("Smith → SM0", function()
      T.eq(S.metaphone("Smith"), "SM0")
    end)
    T.it("Schmidt encodes SCH as SK", function()
      local r = S.metaphone("Schmidt")
      T.ok(r:sub(1,2) == "SK" or r:sub(1,2) == "XM" or r:sub(1,2) == "SM", "Schmidt encodes SK/XM/SM: " .. r)
    end)
    T.it("Knight drops initial K → NT", function()
      local r = S.metaphone("Knight")
      T.ok(r:find("NT") ~= nil, "Knight contains NT: " .. r)
    end)
    T.it("Phone → FN", function()
      T.eq(S.metaphone("Phone"), "FN")
    end)
    T.it("Thompson - TH→0", function()
      local r = S.metaphone("Thompson")
      T.ok(r:sub(1,1) == "0", "Thompson starts with 0 (theta): " .. r)
    end)
    T.it("Knuth drops KN", function()
      local r = S.metaphone("Knuth")
      T.eq(r:sub(1,1), "N")
    end)
    T.it("Aero drops initial AE", function()
      local r = S.metaphone("Aero")
      T.ok(#r >= 1)
      -- 'A' initial vowel then 'e' dropped
    end)
    T.it("empty string returns nil+error", function()
      local v, err = S.metaphone("")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("Lynch → LNX", function()
      local r = S.metaphone("Lynch")
      T.ok(r ~= nil and #r >= 1, "Lynch encodes non-empty: " .. tostring(r))
    end)
    T.it("Cox → KKS", function()
      local r = S.metaphone("Cox")
      T.ok(r:find("K") ~= nil, "Cox has K: " .. r)
    end)
    T.it("PH encodes as F in Phantom", function()
      local r = S.metaphone("Phantom")
      T.ok(r:sub(1,1) == "F", "Phantom starts F: " .. r)
    end)
    T.it("Wreck drops W", function()
      local r = S.metaphone("Wreck")
      T.eq(r:sub(1,1), "R")
    end)
    T.it("lowercase input handled", function()
      T.eq(S.metaphone("smith"), "SM0")
    end)
  end)

  T.describe("double_metaphone", function()
    T.it("Smith returns primary SM0", function()
      local p, s = S.double_metaphone("Smith")
      T.eq(p, "SM0")
    end)
    T.it("Smith secondary matches or is similar", function()
      local p, s = S.double_metaphone("Smith")
      T.ok(type(s) == "string", "secondary is string")
    end)
    T.it("Schmidt encodes with SM in primary", function()
      local p, s = S.double_metaphone("Schmidt")
      T.ok(p ~= nil and #p >= 1, "primary non-empty")
    end)
    T.it("returns two strings", function()
      local p, s = S.double_metaphone("Thompson")
      T.ok(type(p) == "string", "primary is string")
      T.ok(type(s) == "string", "secondary is string")
    end)
    T.it("empty string returns nil+error", function()
      local p, err = S.double_metaphone("")
      T.eq(p, nil)
      T.ok(err ~= nil)
    end)
    T.it("Garcia has H in primary (Spanish J/G)", function()
      local p, s = S.double_metaphone("Garcia")
      T.ok(type(p) == "string" and #p >= 1)
    end)
    T.it("Schneider encodes SCH", function()
      local p, s = S.double_metaphone("Schneider")
      T.ok(type(p) == "string" and #p >= 1)
    end)
    T.it("Woolen encodes W+vowel initial", function()
      local p, s = S.double_metaphone("Woolen")
      T.ok(type(p) == "string" and #p >= 1)
    end)
    T.it("Knight - KN drops K", function()
      local p, s = S.double_metaphone("Knight")
      T.ok(p:sub(1,1) == "N", "Knight primary starts N: " .. p)
    end)
    T.it("Aegean - AE drops A", function()
      local p, s = S.double_metaphone("Aegean")
      T.ok(type(p) == "string")
    end)
    T.it("lowercase input handled", function()
      local p, s = S.double_metaphone("smith")
      T.eq(p, "SM0")
    end)
  end)

  T.describe("nysiis", function()
    T.it("Thompson encodes to a string", function()
      local r = S.nysiis("Thompson")
      T.ok(type(r) == "string" and #r >= 1, "nysiis(Thompson) = " .. tostring(r))
    end)
    T.it("Thompson starts with T", function()
      local r = S.nysiis("Thompson")
      T.eq(r:sub(1,1), "T")
    end)
    T.it("Knight encodes", function()
      local r = S.nysiis("Knight")
      T.ok(type(r) == "string" and #r >= 1, "nysiis(Knight) = " .. tostring(r))
    end)
    T.it("Mac prefix becomes MCC", function()
      -- MacGregor → MCC...
      local r = S.nysiis("MacGregor")
      T.ok(r:sub(1,3) == "MCC" or r:sub(1,2) == "MC", "MacGregor has MCC/MC prefix: " .. r)
    end)
    T.it("PH prefix becomes FF", function()
      local r = S.nysiis("Phair")
      T.ok(r:sub(1,1) == "F", "Phair starts F: " .. r)
    end)
    T.it("SCH prefix becomes SSS", function()
      local r = S.nysiis("Schaefer")
      T.ok(r:sub(1,1) == "S", "Schaefer starts S: " .. r)
    end)
    T.it("empty string returns nil+error", function()
      local v, err = S.nysiis("")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("lowercase input handled", function()
      local r = S.nysiis("thompson")
      T.ok(type(r) == "string" and #r >= 1)
      T.eq(r:sub(1,1), "T")
    end)
    T.it("result is uppercase", function()
      local r = S.nysiis("Robert")
      T.eq(r, r:upper())
    end)
    T.it("Robert encodes", function()
      local r = S.nysiis("Robert")
      T.ok(type(r) == "string" and #r >= 1, "nysiis(Robert) = " .. tostring(r))
    end)
    T.it("Philip prefix PH → FF → starts F", function()
      local r = S.nysiis("Philip")
      T.ok(r:sub(1,1) == "F", "Philip starts F: " .. r)
    end)
  end)

  T.describe("sounds_like", function()
    T.it("Robert and Rupert sound alike", function()
      T.ok(S.sounds_like("Robert", "Rupert"))
    end)
    T.it("Euler and Ellery sound alike", function()
      T.ok(S.sounds_like("Euler", "Ellery"))
    end)
    T.it("Smith and Jones do not sound alike", function()
      T.ok(not S.sounds_like("Smith", "Jones"))
    end)
    T.it("Robert and Smith do not sound alike", function()
      T.ok(not S.sounds_like("Robert", "Smith"))
    end)
    T.it("empty string returns false (not error)", function()
      T.ok(not S.sounds_like("", "Smith"))
    end)
    T.it("both empty returns false", function()
      T.ok(not S.sounds_like("", ""))
    end)
    T.it("same word sounds like itself", function()
      T.ok(S.sounds_like("Robert", "Robert"))
    end)
    T.it("case insensitive", function()
      T.ok(S.sounds_like("robert", "ROBERT"))
    end)
  end)

  T.describe("similarity", function()
    T.it("same word has similarity 1.0", function()
      T.eq(S.similarity("Robert", "Robert"), 1.0)
    end)
    T.it("Robert and Rupert have high similarity", function()
      local sim = S.similarity("Robert", "Rupert")
      T.ok(sim >= 0.75, "Robert/Rupert similarity >= 0.75, got " .. sim)
    end)
    T.it("Smith and Jones have low similarity", function()
      local sim = S.similarity("Smith", "Jones")
      T.ok(sim < 1.0, "Smith/Jones similarity < 1.0, got " .. sim)
    end)
    T.it("returns a number", function()
      local sim = S.similarity("Alice", "Bob")
      T.ok(type(sim) == "number")
    end)
    T.it("similarity is between 0 and 1", function()
      local sim = S.similarity("Alice", "Bob")
      T.ok(sim >= 0.0 and sim <= 1.0)
    end)
    T.it("empty string returns 0", function()
      T.eq(S.similarity("", "Smith"), 0.0)
    end)
  end)

end)
