-- lib/schema/schema_test.lua — tests for lib/schema/init.lua

if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local schema = require("lib.schema")

-- ── create_table basics ──────────────────────────────────────────────────────

T.describe("create_table", function()
	T.it("creates a table with a single column", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:integer("id")
		end)
		local stmts = s:to_sql()
		T.eq(#stmts, 1)
		T.eq(stmts[1], "CREATE TABLE users (\n  id INTEGER\n)")
	end)

	T.it("creates a table with multiple columns", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:integer("id")
			t:text("name")
			t:real("score")
		end)
		local stmts = s:to_sql()
		T.eq(#stmts, 1)
		T.eq(stmts[1], "CREATE TABLE users (\n  id INTEGER,\n  name TEXT,\n  score REAL\n)")
	end)

	T.it("returns self for chaining", function()
		local s = schema.new()
		local ret = s:create_table("a", function(t) t:integer("id") end)
		T.eq(ret, s)
	end)
end)

-- ── column types ─────────────────────────────────────────────────────────────

T.describe("column types", function()
	T.it("integer type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:integer("col") end)
		T.ok(s:to_sql()[1]:find("col INTEGER"))
	end)

	T.it("text type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:text("col") end)
		T.ok(s:to_sql()[1]:find("col TEXT"))
	end)

	T.it("real type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:real("col") end)
		T.ok(s:to_sql()[1]:find("col REAL"))
	end)

	T.it("blob type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:blob("col") end)
		T.ok(s:to_sql()[1]:find("col BLOB"))
	end)

	T.it("boolean type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:boolean("col") end)
		T.ok(s:to_sql()[1]:find("col BOOLEAN"))
	end)

	T.it("timestamp type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:timestamp("col") end)
		T.ok(s:to_sql()[1]:find("col TIMESTAMP"))
	end)

	T.it("numeric type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:numeric("col") end)
		T.ok(s:to_sql()[1]:find("col NUMERIC"))
	end)

	T.it("varchar type with length", function()
		local s = schema.new()
		s:create_table("t", function(t) t:varchar("col", 255) end)
		T.ok(s:to_sql()[1]:find("col VARCHAR%(255%)"))
	end)

	T.it("arbitrary column type", function()
		local s = schema.new()
		s:create_table("t", function(t) t:column("col", "JSONB") end)
		T.ok(s:to_sql()[1]:find("col JSONB"))
	end)
end)

-- ── constraints ──────────────────────────────────────────────────────────────

T.describe("constraints", function()
	T.it("primary_key", function()
		local s = schema.new()
		s:create_table("t", function(t) t:integer("id"):primary_key() end)
		T.ok(s:to_sql()[1]:find("PRIMARY KEY"))
	end)

	T.it("autoincrement", function()
		local s = schema.new()
		s:create_table("t", function(t) t:integer("id"):primary_key():autoincrement() end)
		local sql = s:to_sql()[1]
		T.ok(sql:find("PRIMARY KEY"))
		T.ok(sql:find("AUTOINCREMENT"))
	end)

	T.it("not_null", function()
		local s = schema.new()
		s:create_table("t", function(t) t:text("name"):not_null() end)
		T.ok(s:to_sql()[1]:find("NOT NULL"))
	end)

	T.it("unique", function()
		local s = schema.new()
		s:create_table("t", function(t) t:text("email"):unique() end)
		T.ok(s:to_sql()[1]:find("UNIQUE"))
	end)

	T.it("default with number", function()
		local s = schema.new()
		s:create_table("t", function(t) t:integer("age"):default(0) end)
		T.ok(s:to_sql()[1]:find("DEFAULT 0"))
	end)

	T.it("default with string", function()
		local s = schema.new()
		s:create_table("t", function(t) t:text("status"):default("active") end)
		T.ok(s:to_sql()[1]:find("DEFAULT 'active'"))
	end)

	T.it("default with SQL keyword (CURRENT_TIMESTAMP)", function()
		local s = schema.new()
		s:create_table("t", function(t) t:timestamp("created_at"):default("CURRENT_TIMESTAMP") end)
		T.ok(s:to_sql()[1]:find("DEFAULT CURRENT_TIMESTAMP"))
	end)

	T.it("default with true", function()
		local s = schema.new()
		s:create_table("t", function(t) t:boolean("active"):default(true) end)
		T.ok(s:to_sql()[1]:find("DEFAULT 1"))
	end)

	T.it("default with false", function()
		local s = schema.new()
		s:create_table("t", function(t) t:boolean("active"):default(false) end)
		T.ok(s:to_sql()[1]:find("DEFAULT 0"))
	end)

	T.it("check constraint", function()
		local s = schema.new()
		s:create_table("t", function(t) t:integer("age"):check("age >= 0") end)
		T.ok(s:to_sql()[1]:find("CHECK %(age >= 0%)"))
	end)

	T.it("multiple constraints chain", function()
		local s = schema.new()
		s:create_table("t", function(t)
			t:text("email"):not_null():unique()
		end)
		local sql = s:to_sql()[1]
		T.ok(sql:find("NOT NULL"))
		T.ok(sql:find("UNIQUE"))
	end)

	T.it("references constraint on column", function()
		local s = schema.new()
		s:create_table("t", function(t)
			t:integer("org_id"):references("organizations", "id")
		end)
		T.ok(s:to_sql()[1]:find("REFERENCES organizations%(id%)"))
	end)
end)

-- ── foreign keys ─────────────────────────────────────────────────────────────

T.describe("foreign_key", function()
	T.it("adds column and FOREIGN KEY clause", function()
		local s = schema.new()
		s:create_table("posts", function(t)
			t:integer("id"):primary_key()
			t:foreign_key("user_id", "users", "id")
		end)
		local sql = s:to_sql()[1]
		T.ok(sql:find("user_id INTEGER"))
		T.ok(sql:find("FOREIGN KEY %(user_id%) REFERENCES users%(id%)"))
	end)

	T.it("multiple foreign keys", function()
		local s = schema.new()
		s:create_table("posts", function(t)
			t:integer("id"):primary_key()
			t:foreign_key("user_id", "users", "id")
			t:foreign_key("category_id", "categories", "id")
		end)
		local sql = s:to_sql()[1]
		T.ok(sql:find("FOREIGN KEY %(user_id%) REFERENCES users%(id%)"))
		T.ok(sql:find("FOREIGN KEY %(category_id%) REFERENCES categories%(id%)"))
	end)
end)

-- ── indexes ──────────────────────────────────────────────────────────────────

T.describe("indexes on create_table", function()
	T.it("single-column index", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:text("email")
			t:index("idx_email", "email")
		end)
		local stmts = s:to_sql()
		T.eq(#stmts, 2)
		T.eq(stmts[2], "CREATE INDEX idx_email ON users (email)")
	end)

	T.it("multi-column index", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:text("first")
			t:text("last")
			t:index("idx_name", "first", "last")
		end)
		T.eq(s:to_sql()[2], "CREATE INDEX idx_name ON users (first, last)")
	end)

	T.it("unique index", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:text("email")
			t:unique_index("idx_email", "email")
		end)
		T.eq(s:to_sql()[2], "CREATE UNIQUE INDEX idx_email ON users (email)")
	end)

	T.it("multi-column unique index", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:text("name")
			t:text("email")
			t:unique_index("idx_name_email", "name", "email")
		end)
		T.eq(s:to_sql()[2], "CREATE UNIQUE INDEX idx_name_email ON users (name, email)")
	end)

	T.it("multiple indexes produce multiple statements", function()
		local s = schema.new()
		s:create_table("users", function(t)
			t:text("name")
			t:text("email")
			t:index("idx_name", "name")
			t:unique_index("idx_email", "email")
		end)
		local stmts = s:to_sql()
		T.eq(#stmts, 3)
		T.eq(stmts[2], "CREATE INDEX idx_name ON users (name)")
		T.eq(stmts[3], "CREATE UNIQUE INDEX idx_email ON users (email)")
	end)
end)

-- ── alter_table ──────────────────────────────────────────────────────────────

T.describe("alter_table", function()
	T.it("add_column", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:add_column("bio", "text")
		end)
		T.eq(s:to_sql()[1], "ALTER TABLE users ADD COLUMN bio text")
	end)

	T.it("add_column with constraints", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:add_column("bio", "TEXT", "NOT NULL DEFAULT ''")
		end)
		T.eq(s:to_sql()[1], "ALTER TABLE users ADD COLUMN bio TEXT NOT NULL DEFAULT ''")
	end)

	T.it("drop_column", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:drop_column("score")
		end)
		T.eq(s:to_sql()[1], "ALTER TABLE users DROP COLUMN score")
	end)

	T.it("rename_column", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:rename_column("name", "full_name")
		end)
		T.eq(s:to_sql()[1], "ALTER TABLE users RENAME COLUMN name TO full_name")
	end)

	T.it("add_index", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:add_index("idx_age", "age")
		end)
		T.eq(s:to_sql()[1], "CREATE INDEX idx_age ON users (age)")
	end)

	T.it("add_unique_index", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:add_unique_index("idx_email", "email")
		end)
		T.eq(s:to_sql()[1], "CREATE UNIQUE INDEX idx_email ON users (email)")
	end)

	T.it("add_index with multiple columns", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:add_index("idx_name_age", "name", "age")
		end)
		T.eq(s:to_sql()[1], "CREATE INDEX idx_name_age ON users (name, age)")
	end)

	T.it("drop_index", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:drop_index("idx_age")
		end)
		T.eq(s:to_sql()[1], "DROP INDEX idx_age")
	end)

	T.it("multiple operations produce multiple statements", function()
		local s = schema.new()
		s:alter_table("users", function(t)
			t:add_column("bio", "TEXT")
			t:drop_column("score")
			t:rename_column("name", "full_name")
			t:add_index("idx_age", "age")
		end)
		local stmts = s:to_sql()
		T.eq(#stmts, 4)
		T.eq(stmts[1], "ALTER TABLE users ADD COLUMN bio TEXT")
		T.eq(stmts[2], "ALTER TABLE users DROP COLUMN score")
		T.eq(stmts[3], "ALTER TABLE users RENAME COLUMN name TO full_name")
		T.eq(stmts[4], "CREATE INDEX idx_age ON users (age)")
	end)

	T.it("returns self for chaining", function()
		local s = schema.new()
		local ret = s:alter_table("t", function(t) t:add_column("x", "TEXT") end)
		T.eq(ret, s)
	end)
end)

-- ── drop_table ───────────────────────────────────────────────────────────────

T.describe("drop_table", function()
	T.it("generates DROP TABLE", function()
		local s = schema.new()
		s:drop_table("users")
		T.eq(s:to_sql()[1], "DROP TABLE users")
	end)

	T.it("returns self for chaining", function()
		local s = schema.new()
		local ret = s:drop_table("users")
		T.eq(ret, s)
	end)
end)

T.describe("drop_table_if_exists", function()
	T.it("generates DROP TABLE IF EXISTS", function()
		local s = schema.new()
		s:drop_table_if_exists("users")
		T.eq(s:to_sql()[1], "DROP TABLE IF EXISTS users")
	end)
end)

-- ── rename_table ─────────────────────────────────────────────────────────────

T.describe("rename_table", function()
	T.it("generates ALTER TABLE RENAME TO", function()
		local s = schema.new()
		s:rename_table("users", "accounts")
		T.eq(s:to_sql()[1], "ALTER TABLE users RENAME TO accounts")
	end)

	T.it("returns self for chaining", function()
		local s = schema.new()
		local ret = s:rename_table("users", "accounts")
		T.eq(ret, s)
	end)
end)

-- ── create_table_if_not_exists ───────────────────────────────────────────────

T.describe("create_table_if_not_exists", function()
	T.it("generates CREATE TABLE IF NOT EXISTS", function()
		local s = schema.new()
		s:create_table_if_not_exists("users", function(t)
			t:integer("id"):primary_key()
		end)
		T.ok(s:to_sql()[1]:find("CREATE TABLE IF NOT EXISTS users"))
	end)
end)

-- ── raw SQL ──────────────────────────────────────────────────────────────────

T.describe("raw", function()
	T.it("injects raw SQL statement", function()
		local s = schema.new()
		s:raw("PRAGMA foreign_keys = ON")
		T.eq(s:to_sql()[1], "PRAGMA foreign_keys = ON")
	end)

	T.it("returns self for chaining", function()
		local s = schema.new()
		local ret = s:raw("SELECT 1")
		T.eq(ret, s)
	end)
end)

-- ── to_sql / to_string ──────────────────────────────────────────────────────

T.describe("to_sql", function()
	T.it("returns array of statements", function()
		local s = schema.new()
		s:create_table("a", function(t) t:integer("id") end)
		s:create_table("b", function(t) t:text("name") end)
		local stmts = s:to_sql()
		T.eq(#stmts, 2)
		T.ok(stmts[1]:find("CREATE TABLE a"))
		T.ok(stmts[2]:find("CREATE TABLE b"))
	end)

	T.it("returns empty array for empty schema", function()
		local s = schema.new()
		T.eq(#s:to_sql(), 0)
	end)

	T.it("returns a copy (not internal array)", function()
		local s = schema.new()
		s:drop_table("x")
		local a = s:to_sql()
		local b = s:to_sql()
		T.neq(a, b) -- different table identity
		T.eq(a[1], b[1]) -- same content
	end)
end)

T.describe("to_string", function()
	T.it("joins statements with semicolon-newline by default", function()
		local s = schema.new()
		s:drop_table("a")
		s:drop_table("b")
		T.eq(s:to_string(), "DROP TABLE a;\nDROP TABLE b")
	end)

	T.it("accepts custom separator", function()
		local s = schema.new()
		s:drop_table("a")
		s:drop_table("b")
		T.eq(s:to_string(";\n\n"), "DROP TABLE a;\n\nDROP TABLE b")
	end)

	T.it("returns empty string for empty schema", function()
		local s = schema.new()
		T.eq(s:to_string(), "")
	end)
end)

-- ── error handling ───────────────────────────────────────────────────────────

T.describe("error handling", function()
	T.it("create_table with empty name returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:create_table("", function() end)
		T.eq(ret, nil)
		T.ok(err:find("non%-empty string"))
	end)

	T.it("create_table with non-function callback returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:create_table("t", "not a function")
		T.eq(ret, nil)
		T.ok(err:find("function"))
	end)

	T.it("alter_table with empty name returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:alter_table("", function() end)
		T.eq(ret, nil)
		T.ok(err:find("non%-empty string"))
	end)

	T.it("drop_table with empty name returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:drop_table("")
		T.eq(ret, nil)
		T.ok(err:find("non%-empty string"))
	end)

	T.it("rename_table with empty old name returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:rename_table("", "new")
		T.eq(ret, nil)
		T.ok(err:find("non%-empty string"))
	end)

	T.it("rename_table with empty new name returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:rename_table("old", "")
		T.eq(ret, nil)
		T.ok(err:find("non%-empty string"))
	end)

	T.it("raw with non-string returns nil, errmsg", function()
		local s = schema.new()
		local ret, err = s:raw(42)
		T.eq(ret, nil)
		T.ok(err:find("string"))
	end)
end)

-- ── full integration ─────────────────────────────────────────────────────────

T.describe("full schema example", function()
	T.it("matches the API example from the spec", function()
		local s = schema.new()

		s:create_table("users", function(t)
			t:integer("id"):primary_key():autoincrement()
			t:text("name"):not_null()
			t:text("email"):not_null():unique()
			t:integer("age"):default(0)
			t:real("score")
			t:blob("data")
			t:boolean("active"):default(true)
			t:timestamp("created_at"):default("CURRENT_TIMESTAMP")
			t:foreign_key("org_id", "organizations", "id")
			t:index("idx_email", "email")
			t:unique_index("idx_name_email", "name", "email")
		end)

		local stmts = s:to_sql()
		-- 1 CREATE TABLE + 2 index statements
		T.eq(#stmts, 3)

		local ct = stmts[1]
		T.ok(ct:find("CREATE TABLE users"))
		T.ok(ct:find("id INTEGER PRIMARY KEY AUTOINCREMENT"))
		T.ok(ct:find("name TEXT NOT NULL"))
		T.ok(ct:find("email TEXT NOT NULL UNIQUE"))
		T.ok(ct:find("age INTEGER DEFAULT 0"))
		T.ok(ct:find("score REAL"))
		T.ok(ct:find("data BLOB"))
		T.ok(ct:find("active BOOLEAN DEFAULT 1"))
		T.ok(ct:find("created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"))
		T.ok(ct:find("org_id INTEGER"))
		T.ok(ct:find("FOREIGN KEY %(org_id%) REFERENCES organizations%(id%)"))

		T.eq(stmts[2], "CREATE INDEX idx_email ON users (email)")
		T.eq(stmts[3], "CREATE UNIQUE INDEX idx_name_email ON users (name, email)")
	end)

	T.it("full migration with create, alter, drop, rename", function()
		local s = schema.new()

		s:create_table("users", function(t)
			t:integer("id"):primary_key()
			t:text("name"):not_null()
		end)

		s:alter_table("users", function(t)
			t:add_column("bio", "TEXT")
			t:drop_column("name")
			t:rename_column("bio", "description")
			t:add_index("idx_desc", "description")
		end)

		s:rename_table("users", "accounts")
		s:drop_table("old_accounts")

		local stmts = s:to_sql()
		T.eq(#stmts, 7)
		T.ok(stmts[1]:find("CREATE TABLE users"))
		T.eq(stmts[2], "ALTER TABLE users ADD COLUMN bio TEXT")
		T.eq(stmts[3], "ALTER TABLE users DROP COLUMN name")
		T.eq(stmts[4], "ALTER TABLE users RENAME COLUMN bio TO description")
		T.eq(stmts[5], "CREATE INDEX idx_desc ON users (description)")
		T.eq(stmts[6], "ALTER TABLE users RENAME TO accounts")
		T.eq(stmts[7], "DROP TABLE old_accounts")
	end)

	T.it("multiple tables with foreign keys", function()
		local s = schema.new()

		s:create_table("organizations", function(t)
			t:integer("id"):primary_key():autoincrement()
			t:text("name"):not_null()
		end)

		s:create_table("users", function(t)
			t:integer("id"):primary_key():autoincrement()
			t:text("name"):not_null()
			t:foreign_key("org_id", "organizations", "id")
		end)

		s:create_table("posts", function(t)
			t:integer("id"):primary_key():autoincrement()
			t:text("title"):not_null()
			t:text("body")
			t:foreign_key("user_id", "users", "id")
		end)

		local stmts = s:to_sql()
		T.eq(#stmts, 3)
		T.ok(stmts[1]:find("CREATE TABLE organizations"))
		T.ok(stmts[2]:find("CREATE TABLE users"))
		T.ok(stmts[2]:find("FOREIGN KEY %(org_id%) REFERENCES organizations%(id%)"))
		T.ok(stmts[3]:find("CREATE TABLE posts"))
		T.ok(stmts[3]:find("FOREIGN KEY %(user_id%) REFERENCES users%(id%)"))
	end)

	T.it("to_string produces valid multi-statement SQL", function()
		local s = schema.new()
		s:create_table("t", function(t) t:integer("id"):primary_key() end)
		s:drop_table("old_t")
		local str = s:to_string()
		-- Should contain both statements separated by ;\n
		T.ok(str:find("CREATE TABLE t"))
		T.ok(str:find(";\n"))
		T.ok(str:find("DROP TABLE old_t"))
	end)
end)

-- ── edge cases ───────────────────────────────────────────────────────────────

T.describe("edge cases", function()
	T.it("column with all constraints combined", function()
		local s = schema.new()
		s:create_table("t", function(t)
			t:integer("id"):primary_key():autoincrement():not_null():unique()
		end)
		local sql = s:to_sql()[1]
		T.ok(sql:find("PRIMARY KEY"))
		T.ok(sql:find("AUTOINCREMENT"))
		T.ok(sql:find("NOT NULL"))
		T.ok(sql:find("UNIQUE"))
	end)

	T.it("default string with single quotes is escaped", function()
		local s = schema.new()
		s:create_table("t", function(t)
			t:text("msg"):default("it's")
		end)
		T.ok(s:to_sql()[1]:find("DEFAULT 'it''s'"))
	end)

	T.it("empty schema produces empty output", function()
		local s = schema.new()
		T.eq(#s:to_sql(), 0)
		T.eq(s:to_string(), "")
	end)

	T.it("schema operations are ordered", function()
		local s = schema.new()
		s:drop_table("a")
		s:drop_table("b")
		s:drop_table("c")
		local stmts = s:to_sql()
		T.eq(stmts[1], "DROP TABLE a")
		T.eq(stmts[2], "DROP TABLE b")
		T.eq(stmts[3], "DROP TABLE c")
	end)

	T.it("chaining multiple schema operations", function()
		local s = schema.new()
		s:drop_table("a")
		s:drop_table("b")
		s:rename_table("c", "d")
		T.eq(#s:to_sql(), 3)
	end)

	T.it("default with float", function()
		local s = schema.new()
		s:create_table("t", function(t)
			t:real("val"):default(3.14)
		end)
		T.ok(s:to_sql()[1]:find("DEFAULT 3.14"))
	end)

	T.it("default with negative number", function()
		local s = schema.new()
		s:create_table("t", function(t)
			t:integer("val"):default(-1)
		end)
		T.ok(s:to_sql()[1]:find("DEFAULT %-1"))
	end)

	T.it("table with only foreign keys (no plain columns)", function()
		local s = schema.new()
		s:create_table("join_table", function(t)
			t:foreign_key("a_id", "a", "id")
			t:foreign_key("b_id", "b", "id")
		end)
		local sql = s:to_sql()[1]
		T.ok(sql:find("a_id INTEGER"))
		T.ok(sql:find("b_id INTEGER"))
		T.ok(sql:find("FOREIGN KEY %(a_id%) REFERENCES a%(id%)"))
		T.ok(sql:find("FOREIGN KEY %(b_id%) REFERENCES b%(id%)"))
	end)

	T.it("raw SQL mixed with schema operations", function()
		local s = schema.new()
		s:raw("PRAGMA foreign_keys = ON")
		s:create_table("t", function(t) t:integer("id") end)
		s:raw("INSERT INTO t (id) VALUES (1)")
		local stmts = s:to_sql()
		T.eq(#stmts, 3)
		T.eq(stmts[1], "PRAGMA foreign_keys = ON")
		T.ok(stmts[2]:find("CREATE TABLE t"))
		T.eq(stmts[3], "INSERT INTO t (id) VALUES (1)")
	end)
end)
