if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local MS = require("lib.multiset")

T.describe("multiset", function()

  T.describe("construction", function()
    T.it("new creates empty multiset", function()
      local s = MS.new()
      T.ok(s:is_empty())
      T.eq(s:total(), 0)
      T.eq(s:distinct(), 0)
    end)

    T.it("from counts duplicates in array", function()
      local s = MS.from({1, 1, 2, 3, 3, 3})
      T.eq(s:count(1), 2)
      T.eq(s:count(2), 1)
      T.eq(s:count(3), 3)
      T.eq(s:total(), 6)
      T.eq(s:distinct(), 3)
    end)

    T.it("from empty array", function()
      local s = MS.from({})
      T.ok(s:is_empty())
    end)

    T.it("from_counts builds from table", function()
      local s = MS.from_counts({ a = 2, b = 3, c = 1 })
      T.eq(s:count("a"), 2)
      T.eq(s:count("b"), 3)
      T.eq(s:count("c"), 1)
      T.eq(s:total(), 6)
    end)

    T.it("from_counts ignores zero counts", function()
      local s = MS.from_counts({ a = 2, b = 0 })
      T.eq(s:count("b"), 0)
      T.eq(s:distinct(), 1)
    end)
  end)

  T.describe("add/remove", function()
    T.it("add single occurrence", function()
      local s = MS.new()
      s:add("x")
      T.eq(s:count("x"), 1)
    end)

    T.it("add multiple occurrences", function()
      local s = MS.new()
      s:add("x", 5)
      T.eq(s:count("x"), 5)
    end)

    T.it("add accumulates", function()
      local s = MS.new()
      s:add("x", 2)
      s:add("x", 3)
      T.eq(s:count("x"), 5)
    end)

    T.it("remove single occurrence", function()
      local s = MS.from_counts({ a = 3 })
      s:remove("a")
      T.eq(s:count("a"), 2)
    end)

    T.it("remove multiple occurrences", function()
      local s = MS.from_counts({ a = 5 })
      s:remove("a", 3)
      T.eq(s:count("a"), 2)
    end)

    T.it("remove floors at 0 (no negative counts)", function()
      local s = MS.from_counts({ a = 2 })
      s:remove("a", 10)
      T.eq(s:count("a"), 0)
      T.ok(s:is_empty())
    end)

    T.it("remove absent element is no-op", function()
      local s = MS.new()
      s:remove("missing")
      T.eq(s:count("missing"), 0)
      T.ok(s:is_empty())
    end)

    T.it("remove_all removes element entirely", function()
      local s = MS.from_counts({ a = 5, b = 2 })
      s:remove_all("a")
      T.eq(s:count("a"), 0)
      T.eq(s:count("b"), 2)
      T.eq(s:distinct(), 1)
    end)

    T.it("remove last occurrence cleans up storage", function()
      local s = MS.from_counts({ a = 1 })
      s:remove("a")
      T.ok(s:is_empty())
      T.eq(s:total(), 0)
    end)
  end)

  T.describe("queries", function()
    T.it("count returns 0 for absent element", function()
      local s = MS.new()
      T.eq(s:count("z"), 0)
    end)

    T.it("contains returns true when count > 0", function()
      local s = MS.from_counts({ a = 1 })
      T.ok(s:contains("a"))
    end)

    T.it("contains returns false for absent element", function()
      local s = MS.new()
      T.fail(s:contains("a"))
    end)

    T.it("total sums all counts", function()
      local s = MS.from_counts({ a = 3, b = 2, c = 5 })
      T.eq(s:total(), 10)
    end)

    T.it("distinct counts unique elements", function()
      local s = MS.from_counts({ a = 3, b = 1 })
      T.eq(s:distinct(), 2)
    end)

    T.it("is_empty on non-empty returns false", function()
      local s = MS.from_counts({ a = 1 })
      T.fail(s:is_empty())
    end)
  end)

  T.describe("elements", function()
    T.it("returns each element repeated by count, sorted", function()
      local s = MS.from_counts({ b = 2, a = 3 })
      local elems = s:elements()
      T.eq(#elems, 5)
      T.eq(elems[1], "a")
      T.eq(elems[2], "a")
      T.eq(elems[3], "a")
      T.eq(elems[4], "b")
      T.eq(elems[5], "b")
    end)

    T.it("empty multiset returns empty array", function()
      local s = MS.new()
      T.eq(#s:elements(), 0)
    end)
  end)

  T.describe("pairs and keys", function()
    T.it("pairs returns element-count pairs", function()
      local s = MS.from_counts({ x = 2 })
      local ps = s:pairs()
      T.eq(#ps, 1)
      T.eq(ps[1][1], "x")
      T.eq(ps[1][2], 2)
    end)

    T.it("keys returns distinct elements", function()
      local s = MS.from_counts({ a = 3, b = 1 })
      local ks = s:keys()
      table.sort(ks)
      T.eq(ks[1], "a")
      T.eq(ks[2], "b")
      T.eq(#ks, 2)
    end)
  end)

  T.describe("set operations", function()
    T.it("union takes max of counts", function()
      local a = MS.from_counts({ x = 3, y = 1 })
      local b = MS.from_counts({ x = 1, y = 4, z = 2 })
      local u = a:union(b)
      T.eq(u:count("x"), 3)
      T.eq(u:count("y"), 4)
      T.eq(u:count("z"), 2)
    end)

    T.it("union does not mutate inputs", function()
      local a = MS.from_counts({ x = 2 })
      local b = MS.from_counts({ x = 5 })
      local _ = a:union(b)
      T.eq(a:count("x"), 2)
      T.eq(b:count("x"), 5)
    end)

    T.it("intersection takes min of counts", function()
      local a = MS.from_counts({ x = 3, y = 1, z = 2 })
      local b = MS.from_counts({ x = 1, y = 4 })
      local i = a:intersection(b)
      T.eq(i:count("x"), 1)
      T.eq(i:count("y"), 1)
      T.eq(i:count("z"), 0)
    end)

    T.it("intersection does not mutate inputs", function()
      local a = MS.from_counts({ x = 3 })
      local b = MS.from_counts({ x = 1 })
      local _ = a:intersection(b)
      T.eq(a:count("x"), 3)
    end)

    T.it("sum adds counts", function()
      local a = MS.from_counts({ x = 2, y = 1 })
      local b = MS.from_counts({ x = 3, z = 4 })
      local s = a:sum(b)
      T.eq(s:count("x"), 5)
      T.eq(s:count("y"), 1)
      T.eq(s:count("z"), 4)
    end)

    T.it("sum does not mutate inputs", function()
      local a = MS.from_counts({ x = 2 })
      local b = MS.from_counts({ x = 3 })
      local _ = a:sum(b)
      T.eq(a:count("x"), 2)
      T.eq(b:count("x"), 3)
    end)

    T.it("difference subtracts counts, floors at 0", function()
      local a = MS.from_counts({ x = 5, y = 2 })
      local b = MS.from_counts({ x = 3, y = 4 })
      local d = a:difference(b)
      T.eq(d:count("x"), 2)
      T.eq(d:count("y"), 0)
    end)

    T.it("difference does not include keys only in other", function()
      local a = MS.from_counts({ x = 2 })
      local b = MS.from_counts({ x = 1, z = 5 })
      local d = a:difference(b)
      T.eq(d:count("z"), 0)
      T.eq(d:count("x"), 1)
    end)

    T.it("scale multiplies all counts", function()
      local a = MS.from_counts({ x = 2, y = 3 })
      local s = a:scale(3)
      T.eq(s:count("x"), 6)
      T.eq(s:count("y"), 9)
    end)

    T.it("scale 0 returns empty multiset", function()
      local a = MS.from_counts({ x = 2 })
      local s = a:scale(0)
      T.ok(s:is_empty())
    end)

    T.it("scale does not mutate input", function()
      local a = MS.from_counts({ x = 2 })
      local _ = a:scale(5)
      T.eq(a:count("x"), 2)
    end)
  end)

  T.describe("predicates", function()
    T.it("subset: a is subset of b when all counts <=", function()
      local a = MS.from_counts({ x = 1, y = 2 })
      local b = MS.from_counts({ x = 3, y = 2, z = 1 })
      T.ok(a:subset(b))
    end)

    T.it("subset: false when a has more of some element", function()
      local a = MS.from_counts({ x = 4 })
      local b = MS.from_counts({ x = 2 })
      T.fail(a:subset(b))
    end)

    T.it("subset: empty is subset of anything", function()
      local a = MS.new()
      local b = MS.from_counts({ x = 5 })
      T.ok(a:subset(b))
    end)

    T.it("eq: true when counts match exactly", function()
      local a = MS.from_counts({ x = 2, y = 3 })
      local b = MS.from_counts({ x = 2, y = 3 })
      T.ok(a:eq(b))
    end)

    T.it("eq: false when counts differ", function()
      local a = MS.from_counts({ x = 2 })
      local b = MS.from_counts({ x = 3 })
      T.fail(a:eq(b))
    end)

    T.it("eq: false when keys differ", function()
      local a = MS.from_counts({ x = 2 })
      local b = MS.from_counts({ y = 2 })
      T.fail(a:eq(b))
    end)

    T.it("eq: two empty multisets are equal", function()
      T.ok(MS.new():eq(MS.new()))
    end)
  end)

  T.describe("conversion", function()
    T.it("to_set returns element=true table", function()
      local s = MS.from_counts({ a = 3, b = 1 })
      local st = s:to_set()
      T.ok(st["a"])
      T.ok(st["b"])
      T.eq(st["c"], nil)
    end)

    T.it("to_counts returns element=count table", function()
      local s = MS.from_counts({ a = 3, b = 1 })
      local ct = s:to_counts()
      T.eq(ct["a"], 3)
      T.eq(ct["b"], 1)
    end)

    T.it("most_common returns pairs sorted by count desc", function()
      local s = MS.from_counts({ a = 1, b = 5, c = 3 })
      local mc = s:most_common()
      T.eq(mc[1][2], 5)
      T.eq(mc[2][2], 3)
      T.eq(mc[3][2], 1)
    end)

    T.it("most_common(n) limits to n results", function()
      local s = MS.from_counts({ a = 1, b = 5, c = 3, d = 2 })
      local mc = s:most_common(2)
      T.eq(#mc, 2)
      T.eq(mc[1][2], 5)
      T.eq(mc[2][2], 3)
    end)

    T.it("least_common returns pairs sorted by count asc", function()
      local s = MS.from_counts({ a = 1, b = 5, c = 3 })
      local lc = s:least_common()
      T.eq(lc[1][2], 1)
      T.eq(lc[2][2], 3)
      T.eq(lc[3][2], 5)
    end)

    T.it("least_common(n) limits to n results", function()
      local s = MS.from_counts({ a = 1, b = 5, c = 3, d = 2 })
      local lc = s:least_common(2)
      T.eq(#lc, 2)
      T.eq(lc[1][2], 1)
      T.eq(lc[2][2], 2)
    end)
  end)

  T.describe("functional", function()
    T.it("map transforms elements and merges counts", function()
      local s = MS.from_counts({ a = 2, b = 3, c = 1 })
      -- map a->x, b->x, c->y: x gets 2+3=5, y gets 1
      local mapped = s:map(function(e)
        if e == "a" or e == "b" then return "x" end
        return "y"
      end)
      T.eq(mapped:count("x"), 5)
      T.eq(mapped:count("y"), 1)
    end)

    T.it("map identity returns equal multiset", function()
      local s = MS.from_counts({ a = 2, b = 3 })
      local mapped = s:map(function(e) return e end)
      T.ok(mapped:eq(s))
    end)

    T.it("filter keeps matching elements", function()
      local s = MS.from_counts({ a = 2, b = 3, c = 1 })
      local filtered = s:filter(function(e, _) return e ~= "b" end)
      T.eq(filtered:count("a"), 2)
      T.eq(filtered:count("b"), 0)
      T.eq(filtered:count("c"), 1)
    end)

    T.it("filter can use count in predicate", function()
      local s = MS.from_counts({ a = 2, b = 5, c = 1 })
      local filtered = s:filter(function(_, c) return c >= 2 end)
      T.ok(filtered:contains("a"))
      T.ok(filtered:contains("b"))
      T.fail(filtered:contains("c"))
    end)

    T.it("each iterates all distinct elements", function()
      local s = MS.from_counts({ a = 2, b = 3 })
      local sum = 0
      s:each(function(_, c) sum = sum + c end)
      T.eq(sum, 5)
    end)
  end)

  T.describe("edge cases", function()
    T.it("empty union empty is empty", function()
      local u = MS.new():union(MS.new())
      T.ok(u:is_empty())
    end)

    T.it("empty intersection empty is empty", function()
      local i = MS.new():intersection(MS.new())
      T.ok(i:is_empty())
    end)

    T.it("empty sum empty is empty", function()
      local s = MS.new():sum(MS.new())
      T.ok(s:is_empty())
    end)

    T.it("nonempty union empty equals original", function()
      local a = MS.from_counts({ x = 3 })
      local u = a:union(MS.new())
      T.ok(u:eq(a))
    end)

    T.it("nonempty intersection empty is empty", function()
      local a = MS.from_counts({ x = 3 })
      local i = a:intersection(MS.new())
      T.ok(i:is_empty())
    end)

    T.it("single element multiset", function()
      local s = MS.from({ "only" })
      T.eq(s:total(), 1)
      T.eq(s:distinct(), 1)
      T.ok(s:contains("only"))
      s:remove("only")
      T.ok(s:is_empty())
    end)

    T.it("_tier is pure", function()
      T.eq(MS._tier, "pure")
    end)
  end)

end)
