// lib/y_crdt/fixtures/generate.js
//
// Generates binary fixtures from the REAL yjs/lib0 implementations
// (node_modules/yjs, node_modules/lib0 -- both pulled in via
// lib/y_crdt/fixtures/package.json, `bun install`). These are the wire-
// compatibility contract lib/y_crdt/*_test.lua and parity_test.lua check the
// Lua port against; they are committed to the repo (not regenerated by CI),
// so `bun run generate.js` is a dev-time-only step, matching the
// js_caps/parity_test.lua precedent of driving bun optionally at test time.
//
// Every scenario uses FIXED client ids (never random) so the output is
// byte-for-byte reproducible across runs -- verified by re-running this
// script and diffing.
//
// Run: cd lib/y_crdt/fixtures && bun run generate.js

import * as fs from "node:fs";
import * as path from "node:path";
import * as encoding from "lib0/encoding";
import * as decoding from "lib0/decoding";
import * as Y from "yjs";
import * as syncProtocol from "y-protocols/sync";

const ROOT = import.meta.dir;

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

function hex(buf) {
  return Buffer.from(buf).toString("hex");
}

function writeBin(relPath, buf) {
  const full = path.join(ROOT, relPath);
  ensureDir(path.dirname(full));
  fs.writeFileSync(full, Buffer.from(buf));
  console.log(`wrote ${relPath} (${buf.length} bytes)`);
}

function writeJson(relPath, obj) {
  const full = path.join(ROOT, relPath);
  ensureDir(path.dirname(full));
  fs.writeFileSync(full, JSON.stringify(obj, null, 2) + "\n");
  console.log(`wrote ${relPath}`);
}

function docWithId(clientId) {
  const doc = new Y.Doc();
  doc.clientID = clientId;
  return doc;
}

// Plain-object state vector (client id -> clock), decoded via yjs's own
// Y.decodeStateVector rather than reaching into `doc.store` internals
// (getState is not part of the public API surface).
function svToObject(doc) {
  const sv = Y.decodeStateVector(Y.encodeStateVector(doc));
  const out = {};
  for (const [client, clock] of sv) out[client] = clock;
  return out;
}

// =====================================================================
// 1. Encoding primitive fixtures (fixtures/encoding/)
// =====================================================================

function genEncodingFixtures() {
  const dir = "encoding";

  const varUintCases = {
    varuint_0: 0,
    varuint_1: 1,
    varuint_127: 127,
    varuint_128: 128,
    varuint_255: 255,
    varuint_256: 256,
    varuint_16383: 16383,
    varuint_16384: 16384,
    varuint_2_21: 2 ** 21,
    varuint_2_28: 2 ** 28,
    varuint_2_35: 2 ** 35,
    varuint_2_49: 2 ** 49,
  };
  for (const [name, value] of Object.entries(varUintCases)) {
    const enc = encoding.createEncoder();
    encoding.writeVarUint(enc, value);
    const buf = encoding.toUint8Array(enc);
    writeBin(`${dir}/${name}.bin`, buf);
    writeJson(`${dir}/${name}.json`, { kind: "varUint", value, hex: hex(buf) });
  }

  const varIntCases = {
    varint_0: 0,
    varint_1: 1,
    varint_neg1: -1,
    varint_63: 63,
    varint_64: 64,
    varint_neg64: -64,
    varint_neg65: -65,
    varint_2_20: 2 ** 20,
    varint_neg2_20: -(2 ** 20),
  };
  for (const [name, value] of Object.entries(varIntCases)) {
    const enc = encoding.createEncoder();
    encoding.writeVarInt(enc, value);
    const buf = encoding.toUint8Array(enc);
    writeBin(`${dir}/${name}.bin`, buf);
    writeJson(`${dir}/${name}.json`, { kind: "varInt", value, hex: hex(buf) });
  }

  const varStringCases = {
    varstring_empty: "",
    varstring_ascii: "hello",
    varstring_multibyte: "héllo wörld 日本語 emoji: 🎉",
  };
  for (const [name, value] of Object.entries(varStringCases)) {
    const enc = encoding.createEncoder();
    encoding.writeVarString(enc, value);
    const buf = encoding.toUint8Array(enc);
    writeBin(`${dir}/${name}.bin`, buf);
    writeJson(`${dir}/${name}.json`, { kind: "varString", value, hex: hex(buf) });
  }

  // writeAny: one fixture per tag type (127 undefined .. 116 Uint8Array).
  const anyCases = {
    any_undefined: undefined,
    any_null: null,
    any_true: true,
    any_false: false,
    any_integer: 42,
    any_negative_integer: -42,
    any_float32: 0.5,
    any_float64: 3.14159,
    any_string: "hello",
    any_array: [1, 2, 3],
    any_empty_array: [],
    any_map: { a: 1, b: "two" },
    any_nested: { list: [1, 2, { x: true, y: null }], name: "crdt" },
  };
  for (const [name, value] of Object.entries(anyCases)) {
    const enc = encoding.createEncoder();
    encoding.writeAny(enc, value);
    const buf = encoding.toUint8Array(enc);
    writeBin(`${dir}/${name}.bin`, buf);
    writeJson(`${dir}/${name}.json`, { kind: "any", value: value === undefined ? "<undefined>" : value, hex: hex(buf) });
  }
  // any_uint8array: tag 116, only reachable by feeding writeAny an actual
  // Uint8Array (JSON.stringify can't round-trip binary, so this fixture's
  // .json records the byte array instead of `value`).
  {
    const bytes = new Uint8Array([1, 2, 3, 254, 255]);
    const enc = encoding.createEncoder();
    encoding.writeAny(enc, bytes);
    const buf = encoding.toUint8Array(enc);
    writeBin(`${dir}/any_uint8array.bin`, buf);
    writeJson(`${dir}/any_uint8array.json`, { kind: "any", value_bytes: Array.from(bytes), hex: hex(buf) });
  }
}

// =====================================================================
// 2. Update fixtures (fixtures/updates/)
// =====================================================================

function genUpdateFixtures() {
  const dir = "updates";

  // single_text_insert
  {
    const doc = docWithId(1);
    const ytext = doc.getText("content");
    ytext.insert(0, "hello");
    const update = Y.encodeStateAsUpdate(doc);
    const sv = Y.encodeStateVector(doc);
    writeBin(`${dir}/single_text_insert.bin`, update);
    writeJson(`${dir}/single_text_insert.json`, {
      description: "Y.Doc(clientID=1).getText('content').insert(0, 'hello')",
      client_id: 1,
      content: ytext.toString(),
      state_vector: svToObject(doc),
      update_hex: hex(update),
      state_vector_hex: hex(sv),
    });
  }

  // multiple_inserts: sequential inserts building "hello world"
  {
    const doc = docWithId(1);
    const ytext = doc.getText("content");
    ytext.insert(0, "hello");
    ytext.insert(5, " world");
    const update = Y.encodeStateAsUpdate(doc);
    writeBin(`${dir}/multiple_inserts.bin`, update);
    writeJson(`${dir}/multiple_inserts.json`, {
      description: "insert(0,'hello') then insert(5,' world')",
      client_id: 1,
      content: ytext.toString(),
      state_vector: svToObject(doc),
      update_hex: hex(update),
    });
  }

  // delete_middle: insert "hello world", delete "lo wo" (indices 3..8)
  {
    const doc = docWithId(1);
    const ytext = doc.getText("content");
    ytext.insert(0, "hello world");
    ytext.delete(3, 5); // "lo wo"
    const update = Y.encodeStateAsUpdate(doc);
    writeBin(`${dir}/delete_middle.bin`, update);
    writeJson(`${dir}/delete_middle.json`, {
      description: "insert(0,'hello world') then delete(3,5) removing 'lo wo'",
      client_id: 1,
      content: ytext.toString(),
      expected_content: "helrld",
      state_vector: svToObject(doc),
      update_hex: hex(update),
    });
  }

  // concurrent_inserts: two clients insert at the same position independently
  {
    const docA = docWithId(1);
    const textA = docA.getText("content");
    textA.insert(0, "hello");
    const updateBase = Y.encodeStateAsUpdate(docA);

    const docB = docWithId(2);
    Y.applyUpdate(docB, updateBase);
    const textB = docB.getText("content");

    // Both clients insert at position 5 (end of "hello") independently,
    // without seeing each other's change first.
    textA.insert(5, " A-side");
    textB.insert(5, " B-side");

    const updateA = Y.encodeStateAsUpdate(docA, Y.encodeStateVector(docB));
    const updateB = Y.encodeStateAsUpdate(docB, Y.encodeStateVector(docA));

    // Converge: replay A's full history plus B's diff into a fresh doc to
    // compute the merged result both sides should reach independently. A
    // throwaway client id (99, distinct from both 1 and 2) is used here --
    // reusing 1 would collide with client 1's own structs arriving via a
    // remote (non-local) update and trip yjs's built-in same-id collision
    // detector (silently reassigning clientID), which is irrelevant noise
    // since only this doc's resulting text content is read below, never its
    // own encoded output.
    const docAMerged = docWithId(99);
    Y.applyUpdate(docAMerged, Y.encodeStateAsUpdate(docA));
    Y.applyUpdate(docAMerged, updateB);
    const converged = docAMerged.getText("content").toString();

    writeBin(`${dir}/concurrent_inserts_base.bin`, updateBase);
    writeBin(`${dir}/concurrent_inserts_a.bin`, updateA);
    writeBin(`${dir}/concurrent_inserts_b.bin`, updateB);
    writeJson(`${dir}/concurrent_inserts.json`, {
      description:
        "client 1 and client 2 both start from 'hello' (base update), then concurrently insert at index 5 without seeing each other first",
      client_a_id: 1,
      client_b_id: 2,
      base_content: "hello",
      client_a_insert: " A-side",
      client_b_insert: " B-side",
      client_a_final_content: textA.toString(),
      client_b_final_content: textB.toString(),
      converged_content: converged,
      base_update_hex: hex(updateBase),
      a_diff_update_hex: hex(updateA),
      b_diff_update_hex: hex(updateB),
      state_vector_a: svToObject(docA),
      state_vector_b: svToObject(docB),
    });
  }

  // text_format: bold/italic formatting via Y.Text attributes
  {
    const doc = docWithId(1);
    const ytext = doc.getText("content");
    ytext.insert(0, "hello world");
    ytext.format(0, 5, { bold: true });
    ytext.format(6, 5, { italic: true });
    const update = Y.encodeStateAsUpdate(doc);
    writeBin(`${dir}/text_format.bin`, update);
    writeJson(`${dir}/text_format.json`, {
      description: "insert 'hello world', format [0,5) bold, format [6,5) italic",
      client_id: 1,
      content: ytext.toString(),
      delta: ytext.toDelta(),
      update_hex: hex(update),
    });
  }

  // array_mixed: Y.Array with mixed types
  {
    const doc = docWithId(1);
    const yarr = doc.getArray("content");
    yarr.insert(0, [1, "two", true, false, null, [1, 2, 3]]);
    const update = Y.encodeStateAsUpdate(doc);
    writeBin(`${dir}/array_mixed.bin`, update);
    writeJson(`${dir}/array_mixed.json`, {
      description: "Y.Array.insert(0, [1, 'two', true, false, null, [1,2,3]])",
      client_id: 1,
      content: yarr.toJSON(),
      update_hex: hex(update),
    });
  }

  // map_operations: set/delete/overwrite
  {
    const doc = docWithId(1);
    const ymap = doc.getMap("content");
    ymap.set("a", 1);
    ymap.set("b", "two");
    ymap.set("c", true);
    ymap.delete("b");
    ymap.set("a", 100); // overwrite
    const update = Y.encodeStateAsUpdate(doc);
    writeBin(`${dir}/map_operations.bin`, update);
    writeJson(`${dir}/map_operations.json`, {
      description: "set(a,1) set(b,'two') set(c,true) delete(b) set(a,100) [overwrite]",
      client_id: 1,
      content: ymap.toJSON(),
      update_hex: hex(update),
    });
  }

  // nested_types: Y.Map containing a Y.Text and Y.Array
  {
    const doc = docWithId(1);
    const ymap = doc.getMap("content");
    const nestedText = new Y.Text();
    ymap.set("text", nestedText);
    nestedText.insert(0, "nested hello");
    const nestedArray = new Y.Array();
    ymap.set("array", nestedArray);
    nestedArray.insert(0, [1, 2, 3]);
    const update = Y.encodeStateAsUpdate(doc);
    writeBin(`${dir}/nested_types.bin`, update);
    writeJson(`${dir}/nested_types.json`, {
      description: "Y.Map containing a nested Y.Text ('nested hello') and nested Y.Array ([1,2,3])",
      client_id: 1,
      content: ymap.toJSON(),
      update_hex: hex(update),
    });
  }
}

// =====================================================================
// 3. State vector fixtures (fixtures/state_vectors/)
// =====================================================================

function genStateVectorFixtures() {
  const dir = "state_vectors";

  // empty
  {
    const doc = docWithId(1);
    const sv = Y.encodeStateVector(doc);
    writeBin(`${dir}/empty.bin`, sv);
    writeJson(`${dir}/empty.json`, { description: "state vector of a doc with no ops", client_id: 1, state_vector: {}, hex: hex(sv) });
  }

  // single_client
  {
    const doc = docWithId(1);
    doc.getText("content").insert(0, "hello");
    const sv = Y.encodeStateVector(doc);
    writeBin(`${dir}/single_client.bin`, sv);
    writeJson(`${dir}/single_client.json`, {
      description: "state vector after client 1 inserts 'hello'",
      client_id: 1,
      state_vector: svToObject(doc),
      hex: hex(sv),
    });
  }

  // multi_client: merge updates from two clients into one doc, take its SV
  {
    const docA = docWithId(1);
    docA.getText("content").insert(0, "hello");
    const updateA = Y.encodeStateAsUpdate(docA);

    const docB = docWithId(2);
    docB.getText("content").insert(0, "world");
    const updateB = Y.encodeStateAsUpdate(docB);

    const merged = docWithId(3);
    merged.getText("content");
    Y.applyUpdate(merged, updateA);
    Y.applyUpdate(merged, updateB);
    const sv = Y.encodeStateVector(merged);
    writeBin(`${dir}/multi_client.bin`, sv);
    writeJson(`${dir}/multi_client.json`, {
      description: "state vector of a doc holding client 1's 'hello' and client 2's 'world'",
      state_vector: svToObject(merged),
      hex: hex(sv),
    });
  }
}

// =====================================================================
// 4. Sync protocol fixtures (fixtures/sync/)
// =====================================================================

function writeSyncStep1Message(doc) {
  const enc = encoding.createEncoder();
  syncProtocol.writeSyncStep1(enc, doc);
  return encoding.toUint8Array(enc);
}

function writeSyncStep2Message(doc, encodedStateVector) {
  const enc = encoding.createEncoder();
  syncProtocol.writeSyncStep2(enc, doc, encodedStateVector);
  return encoding.toUint8Array(enc);
}

function writeUpdateMessage(updateBytes) {
  const enc = encoding.createEncoder();
  syncProtocol.writeUpdate(enc, updateBytes);
  return encoding.toUint8Array(enc);
}

function genSyncFixtures() {
  const dir = "sync";

  // step1
  {
    const doc = docWithId(1);
    doc.getText("content").insert(0, "hello");
    const msg = writeSyncStep1Message(doc);
    writeBin(`${dir}/step1.bin`, msg);
    writeJson(`${dir}/step1.json`, {
      description: "SyncStep1 message from client 1 (state vector after inserting 'hello')",
      client_id: 1,
      message_type: 0,
      state_vector: svToObject(doc),
      hex: hex(msg),
    });
  }

  // step2
  {
    const doc = docWithId(1);
    doc.getText("content").insert(0, "hello");
    const emptySv = Y.encodeStateVector(docWithId(99));
    const msg = writeSyncStep2Message(doc, emptySv);
    writeBin(`${dir}/step2.bin`, msg);
    writeJson(`${dir}/step2.json`, {
      description: "SyncStep2 response from client 1, replying to an empty state vector (so it carries everything)",
      client_id: 1,
      message_type: 1,
      content: "hello",
      hex: hex(msg),
    });
  }

  // update_msg
  {
    const doc = docWithId(1);
    doc.getText("content").insert(0, "x");
    const updateBytes = Y.encodeStateAsUpdate(doc);
    const msg = writeUpdateMessage(updateBytes);
    writeBin(`${dir}/update_msg.bin`, msg);
    writeJson(`${dir}/update_msg.json`, {
      description: "Update broadcast message wrapping client 1's encodeStateAsUpdate() after inserting 'x'",
      client_id: 1,
      message_type: 2,
      update_hex: hex(updateBytes),
      hex: hex(msg),
    });
  }

  // full_handshake: ordered messages from a complete two-peer sync, driven
  // through y-protocols' own high-level `readSyncMessage` dispatcher (the
  // same entry point a real client/server pair would call) rather than
  // hand-rolling message decode order -- so this fixture's message
  // sequencing is exactly what upstream y-protocols produces, not a
  // reimplementation of it.
  {
    const handshakeDir = `${dir}/full_handshake`;

    const a = docWithId(1);
    a.getText("content").insert(0, "hello from A");

    const b = docWithId(2);
    b.getText("content"); // establish the root before applying, per update.lua's documented precondition

    // 1. A -> B: SyncStep1 (A's state vector)
    const msg1_step1 = writeSyncStep1Message(a);
    writeBin(`${handshakeDir}/01_a_to_b_step1.bin`, msg1_step1);

    // 2. B receives step1, replies with SyncStep2 (everything, since B is empty)
    const enc2 = encoding.createEncoder();
    syncProtocol.readSyncMessage(decoding.createDecoder(new Uint8Array(msg1_step1)), enc2, b, "test-origin");
    const msg2_step2 = encoding.toUint8Array(enc2);
    writeBin(`${handshakeDir}/02_b_to_a_step2.bin`, msg2_step2);

    // 3. A receives B's step2, applies it (no-op content-wise: B had nothing new)
    const enc3 = encoding.createEncoder();
    syncProtocol.readSyncMessage(decoding.createDecoder(new Uint8Array(msg2_step2)), enc3, a, "test-origin");
    // readSyncMessage's reply encoder is unused for a step2/update message
    // (only step1 produces a reply) -- no fixture written for enc3.

    // 4. B -> A: SyncStep1 (B's state vector, still nothing new to report)
    const msg3_step1 = writeSyncStep1Message(b);
    writeBin(`${handshakeDir}/03_b_to_a_step1.bin`, msg3_step1);

    // 5. A receives step1, replies with SyncStep2 (empty diff: A has nothing new from B)
    const enc4 = encoding.createEncoder();
    syncProtocol.readSyncMessage(decoding.createDecoder(new Uint8Array(msg3_step1)), enc4, a, "test-origin");
    const msg4_step2 = encoding.toUint8Array(enc4);
    writeBin(`${handshakeDir}/04_a_to_b_step2.bin`, msg4_step2);

    // 6. B applies A's (empty) step2 reply.
    const enc5 = encoding.createEncoder();
    syncProtocol.readSyncMessage(decoding.createDecoder(new Uint8Array(msg4_step2)), enc5, b, "test-origin");

    // 7. A makes a further local edit, broadcasts an Update message to B --
    // captured via Y.Doc's own 'update' event, which fires with exactly the
    // transaction-local update bytes (matching update.lua's encode_v1, not
    // encode_diff_v1/encodeStateAsUpdate's full-history form).
    let capturedUpdate = null;
    const updateHandler = (update) => {
      capturedUpdate = update;
    };
    a.on("update", updateHandler);
    a.getText("content").insert(12, "!!");
    a.off("update", updateHandler);
    const msg5_update = writeUpdateMessage(capturedUpdate);
    writeBin(`${handshakeDir}/05_a_to_b_update.bin`, msg5_update);

    const enc6 = encoding.createEncoder();
    syncProtocol.readSyncMessage(decoding.createDecoder(new Uint8Array(msg5_update)), enc6, b, "test-origin");

    writeJson(`${handshakeDir}/handshake.json`, {
      description:
        "Ordered messages of a full two-peer sync driven through y-protocols' readSyncMessage: " +
        "A starts with 'hello from A', B starts empty. " +
        "01: A->B step1 (A's SV). 02: B->A step2 (diff, everything since B is empty). " +
        "03: B->A step1 (B's SV, still nothing new). 04: A->B step2 (empty diff, A has nothing new from B). " +
        "05: A->B update (broadcast of A's further local edit appending '!!').",
      client_a_id: 1,
      client_b_id: 2,
      messages: [
        "01_a_to_b_step1.bin",
        "02_b_to_a_step2.bin",
        "03_b_to_a_step1.bin",
        "04_a_to_b_step2.bin",
        "05_a_to_b_update.bin",
      ],
      final_content_a: a.getText("content").toString(),
      final_content_b: b.getText("content").toString(),
    });
  }
}

// =====================================================================
// main
// =====================================================================

console.log("Generating y_crdt parity fixtures from yjs " + JSON.stringify(await getYjsVersion()) + " ...");
genEncodingFixtures();
genUpdateFixtures();
genStateVectorFixtures();
genSyncFixtures();
console.log("Done.");

async function getYjsVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "node_modules/yjs/package.json"), "utf8"));
  return pkg.version;
}
