-- lib/spreadsheet/spreadsheet_test.lua

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T  = require("lib.test.assert")
local ss = require("lib.spreadsheet")

T.describe("spreadsheet", function()

  T.it("integer value set/get", function()
    local sheet = ss.new()
    sheet:set("A1", 42)
    T.eq(sheet:get("A1"), 42)
  end)

  T.it("string value set/get", function()
    local sheet = ss.new()
    sheet:set("A1", "hello")
    T.eq(sheet:get("A1"), "hello")
  end)

  T.it("formula: A1+A2 evaluates correctly", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 20)
    sheet:set("B1", "=A1+A2")
    T.eq(sheet:get("B1"), 30)
  end)

  T.it("SUM range: correct total", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 20)
    sheet:set("A3", 30)
    sheet:set("B1", "=SUM(A1:A3)")
    T.eq(sheet:get("B1"), 60)
  end)

  T.it("AVERAGE: correct mean", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 20)
    sheet:set("A3", 30)
    sheet:set("B1", "=AVERAGE(A1:A3)")
    T.eq(sheet:get("B1"), 20)
  end)

  T.it("MIN: correct minimum", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 5)
    sheet:set("A3", 30)
    sheet:set("B1", "=MIN(A1:A3)")
    T.eq(sheet:get("B1"), 5)
  end)

  T.it("MAX: correct maximum", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 5)
    sheet:set("A3", 30)
    sheet:set("B1", "=MAX(A1:A3)")
    T.eq(sheet:get("B1"), 30)
  end)

  T.it("IF: true branch", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("B1", "=IF(A1>5,1,0)")
    T.eq(sheet:get("B1"), 1)
  end)

  T.it("IF: false branch", function()
    local sheet = ss.new()
    sheet:set("A1", 3)
    sheet:set("B1", "=IF(A1>5,1,0)")
    T.eq(sheet:get("B1"), 0)
  end)

  T.it("dependency: changing A1 recalculates B1", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 20)
    sheet:set("B1", "=A1+A2")
    T.eq(sheet:get("B1"), 30)
    sheet:set("A1", 15)
    T.eq(sheet:get("B1"), 35)
  end)

  T.it("absolute reference $A$1 evaluates correctly", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("B1", "=$A$1*2")
    T.eq(sheet:get("B1"), 20)
  end)

  T.it("circular reference: detected, returns error", function()
    local sheet = ss.new()
    sheet:set("A1", "=B1+1")
    sheet:set("B1", "=A1+1")
    local v = sheet:get("A1")
    T.eq(v, "#CIRC!")
  end)

  T.it("DIV/0: returns #DIV/0! error", function()
    local sheet = ss.new()
    sheet:set("A1", "=1/0")
    T.eq(sheet:get("A1"), "#DIV/0!")
  end)

  T.it("IFERROR: catches error values", function()
    local sheet = ss.new()
    sheet:set("A1", "=IFERROR(1/0,99)")
    T.eq(sheet:get("A1"), 99)
  end)

  T.it("CONCAT: string concatenation", function()
    local sheet = ss.new()
    sheet:set("A1", "hello")
    sheet:set("A2", " world")
    sheet:set("B1", "=CONCAT(A1,A2)")
    T.eq(sheet:get("B1"), "hello world")
  end)

  T.it("to_csv / from_csv round-trip", function()
    local sheet = ss.new()
    sheet:set("A1", 1)
    sheet:set("B1", 2)
    sheet:set("A2", 3)
    sheet:set("B2", 4)
    local csv = sheet:to_csv()
    local sheet2 = ss.from_csv(csv)
    T.eq(sheet2:get("A1"), 1)
    T.eq(sheet2:get("B1"), 2)
    T.eq(sheet2:get("A2"), 3)
    T.eq(sheet2:get("B2"), 4)
  end)

  T.it("COUNT: counts numbers only", function()
    local sheet = ss.new()
    sheet:set("A1", 1)
    sheet:set("A2", "text")
    sheet:set("A3", 3)
    sheet:set("B1", "=COUNT(A1:A3)")
    T.eq(sheet:get("B1"), 2)
  end)

  T.it("COUNTA: counts non-empty values", function()
    local sheet = ss.new()
    sheet:set("A1", 1)
    sheet:set("A2", "text")
    sheet:set("A3", 3)
    -- A4 is empty
    sheet:set("B1", "=COUNTA(A1:A4)")
    T.eq(sheet:get("B1"), 3)
  end)

  T.it("VLOOKUP: basic lookup in range", function()
    local sheet = ss.new()
    sheet:set("A1", 1)
    sheet:set("B1", "apple")
    sheet:set("A2", 2)
    sheet:set("B2", "banana")
    sheet:set("A3", 3)
    sheet:set("B3", "cherry")
    sheet:set("C1", "=VLOOKUP(2,A1:B3,2,TRUE)")
    T.eq(sheet:get("C1"), "banana")
  end)

  T.it("range() returns array of row/col/value", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("A2", 20)
    local r = sheet:range("A1:A2")
    T.eq(#r, 2)
    T.eq(r[1].value, 10)
    T.eq(r[2].value, 20)
  end)

  T.it("set_range fills cells", function()
    local sheet = ss.new()
    sheet:set_range("A1:A3", {100, 200, 300})
    T.eq(sheet:get("A1"), 100)
    T.eq(sheet:get("A2"), 200)
    T.eq(sheet:get("A3"), 300)
  end)

  T.it("#REF! for out-of-bounds row", function()
    local sheet = ss.new({ rows = 10 })
    sheet:set("A1", "=A11")
    T.eq(sheet:get("A1"), "#REF!")
  end)

  T.it("#NAME? for unknown function", function()
    local sheet = ss.new()
    sheet:set("A1", "=FOO()")
    T.eq(sheet:get("A1"), "#NAME?")
  end)

  T.it("string concatenation with & operator", function()
    local sheet = ss.new()
    sheet:set("A1", "foo")
    sheet:set("A2", "bar")
    sheet:set("B1", "=A1&A2")
    T.eq(sheet:get("B1"), "foobar")
  end)

  T.it("nested formula with SUM and arithmetic", function()
    local sheet = ss.new()
    sheet:set("A1", 5)
    sheet:set("A2", 10)
    sheet:set("B1", "=SUM(A1:A2)*2")
    T.eq(sheet:get("B1"), 30)
  end)

  T.it("IF with string result", function()
    local sheet = ss.new()
    sheet:set("A1", 10)
    sheet:set("B1", '=IF(A1>5,"big","small")')
    T.eq(sheet:get("B1"), "big")
  end)

end)
