-- lib/regexp/regexp_test.lua
-- Tests for the Thompson NFA regexp engine.

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local R = require("lib.regexp")

T.describe("regexp", function()

  -- ── Basic matching ──────────────────────────────────────────────────────────

  T.describe("literal chars", function()
    T.it("matches exact string", function()
      T.ok(R.test("hello", "hello"))
      T.ok(R.test("hello", "say hello world"))
      T.ok(not R.test("hello", "world"))
    end)
    T.it("is case-sensitive", function()
      T.ok(not R.test("Hello", "hello"))
      T.ok(R.test("Hello", "Hello"))
    end)
  end)

  T.describe("dot (.)", function()
    T.it("matches any char except newline", function()
      T.ok(R.test(".", "a"))
      T.ok(R.test(".", "z"))
      T.ok(R.test(".", "5"))
      T.ok(not R.test("^.$", "\n"))
    end)
    T.it("dot in sequence", function()
      T.ok(R.test("a.c", "abc"))
      T.ok(R.test("a.c", "axc"))
      T.ok(not R.test("^a.c$", "ac"))
    end)
  end)

  -- ── Quantifiers ─────────────────────────────────────────────────────────────

  T.describe("* quantifier", function()
    T.it("matches zero or more", function()
      T.ok(R.test("^a*$", ""))
      T.ok(R.test("^a*$", "a"))
      T.ok(R.test("^a*$", "aaa"))
      T.ok(not R.test("^a*$", "b"))
    end)
  end)

  T.describe("+ quantifier", function()
    T.it("matches one or more", function()
      T.ok(not R.test("^a+$", ""))
      T.ok(R.test("^a+$", "a"))
      T.ok(R.test("^a+$", "aaa"))
      T.ok(not R.test("^a+$", "b"))
    end)
  end)

  T.describe("? quantifier", function()
    T.it("matches zero or one", function()
      T.ok(R.test("^ab?c$", "ac"))
      T.ok(R.test("^ab?c$", "abc"))
      T.ok(not R.test("^ab?c$", "abbc"))
    end)
  end)

  -- ── Counted quantifiers ──────────────────────────────────────────────────────

  T.describe("{n} quantifier", function()
    T.it("matches exactly n", function()
      T.ok(R.test("^a{3}$", "aaa"))
      T.ok(not R.test("^a{3}$", "aa"))
      T.ok(not R.test("^a{3}$", "aaaa"))
    end)
  end)

  T.describe("{n,} quantifier", function()
    T.it("matches n or more", function()
      T.ok(R.test("^a{2,}$", "aa"))
      T.ok(R.test("^a{2,}$", "aaaa"))
      T.ok(not R.test("^a{2,}$", "a"))
    end)
  end)

  T.describe("{n,m} quantifier", function()
    T.it("matches between n and m", function()
      T.ok(R.test("^a{2,4}$", "aa"))
      T.ok(R.test("^a{2,4}$", "aaa"))
      T.ok(R.test("^a{2,4}$", "aaaa"))
      T.ok(not R.test("^a{2,4}$", "a"))
      T.ok(not R.test("^a{2,4}$", "aaaaa"))
    end)
  end)

  -- ── Character classes ────────────────────────────────────────────────────────

  T.describe("[abc] class", function()
    T.it("matches listed chars", function()
      T.ok(R.test("^[abc]$", "a"))
      T.ok(R.test("^[abc]$", "b"))
      T.ok(R.test("^[abc]$", "c"))
      T.ok(not R.test("^[abc]$", "d"))
    end)
  end)

  T.describe("[^abc] negated class", function()
    T.it("matches chars not listed", function()
      T.ok(not R.test("^[^abc]$", "a"))
      T.ok(not R.test("^[^abc]$", "b"))
      T.ok(R.test("^[^abc]$", "d"))
      T.ok(R.test("^[^abc]$", "z"))
    end)
  end)

  T.describe("[a-z] range", function()
    T.it("matches range of chars", function()
      T.ok(R.test("^[a-z]$", "a"))
      T.ok(R.test("^[a-z]$", "z"))
      T.ok(R.test("^[a-z]$", "m"))
      T.ok(not R.test("^[a-z]$", "A"))
      T.ok(not R.test("^[a-z]$", "0"))
    end)
    T.it("multiple ranges", function()
      T.ok(R.test("^[a-zA-Z]$", "A"))
      T.ok(R.test("^[a-zA-Z]$", "z"))
      T.ok(not R.test("^[a-zA-Z]$", "0"))
    end)
  end)

  -- ── Anchors ──────────────────────────────────────────────────────────────────

  T.describe("^ anchor", function()
    T.it("anchors to start", function()
      T.ok(R.test("^hello", "hello world"))
      T.ok(not R.test("^hello", "say hello"))
    end)
  end)

  T.describe("$ anchor", function()
    T.it("anchors to end", function()
      T.ok(R.test("world$", "hello world"))
      T.ok(not R.test("world$", "world peace"))
    end)
  end)

  T.describe("^ and $ together", function()
    T.it("anchors full string", function()
      T.ok(R.test("^hello$", "hello"))
      T.ok(not R.test("^hello$", "hello world"))
      T.ok(not R.test("^hello$", "say hello"))
    end)
  end)

  -- ── Alternation ─────────────────────────────────────────────────────────────

  T.describe("| alternation", function()
    T.it("matches either branch", function()
      T.ok(R.test("^(cat|dog)$", "cat"))
      T.ok(R.test("^(cat|dog)$", "dog"))
      T.ok(not R.test("^(cat|dog)$", "bird"))
    end)
    T.it("three alternatives", function()
      T.ok(R.test("^(red|green|blue)$", "red"))
      T.ok(R.test("^(red|green|blue)$", "green"))
      T.ok(R.test("^(red|green|blue)$", "blue"))
      T.ok(not R.test("^(red|green|blue)$", "yellow"))
    end)
  end)

  -- ── Capture groups ───────────────────────────────────────────────────────────

  T.describe("capture groups", function()
    T.it("find returns captures", function()
      local s, e, c1 = R.find("(hello)", "say hello world")
      T.eq(c1, "hello")
      T.eq(s, 5)
      T.eq(e, 9)
    end)
    T.it("multiple captures", function()
      local s, e, year, month, day = R.find("(\\d+)-(\\d+)-(\\d+)", "date: 2024-01-15 end")
      T.eq(year, "2024")
      T.eq(month, "01")
      T.eq(day, "15")
    end)
    T.it("nested groups", function()
      local s, e, outer, inner = R.find("((ab)c)", "xabcy")
      T.eq(outer, "abc")
      T.eq(inner, "ab")
    end)
  end)

  T.describe("non-capturing groups (?:...)", function()
    T.it("groups without capture", function()
      local s, e = R.find("(?:foo|bar)baz", "foobaz")
      T.eq(s, 1)
      T.eq(e, 6)
    end)
    T.it("alternation via non-capturing group", function()
      T.ok(R.test("^(?:cat|dog)s?$", "cats"))
      T.ok(R.test("^(?:cat|dog)s?$", "dog"))
      T.ok(not R.test("^(?:cat|dog)s?$", "bird"))
    end)
    T.it("no captures from non-capturing group", function()
      local s, e, c1 = R.find("(?:foo)(bar)", "foobar")
      T.eq(c1, "bar")
      T.eq(s, 1)
      T.eq(e, 6)
    end)
  end)

  -- ── Shorthand classes ────────────────────────────────────────────────────────

  T.describe("\\d digit", function()
    T.it("matches digits", function()
      T.ok(R.test("^\\d$", "0"))
      T.ok(R.test("^\\d$", "9"))
      T.ok(not R.test("^\\d$", "a"))
      T.ok(not R.test("^\\d$", " "))
    end)
  end)

  T.describe("\\w word char", function()
    T.it("matches word chars", function()
      T.ok(R.test("^\\w$", "a"))
      T.ok(R.test("^\\w$", "Z"))
      T.ok(R.test("^\\w$", "5"))
      T.ok(R.test("^\\w$", "_"))
      T.ok(not R.test("^\\w$", " "))
      T.ok(not R.test("^\\w$", "-"))
    end)
  end)

  T.describe("\\s space", function()
    T.it("matches whitespace", function()
      T.ok(R.test("^\\s$", " "))
      T.ok(R.test("^\\s$", "\t"))
      T.ok(R.test("^\\s$", "\n"))
      T.ok(not R.test("^\\s$", "a"))
    end)
  end)

  T.describe("\\D \\W \\S negated shorthands", function()
    T.it("\\D matches non-digit", function()
      T.ok(R.test("^\\D$", "a"))
      T.ok(not R.test("^\\D$", "5"))
    end)
    T.it("\\W matches non-word", function()
      T.ok(R.test("^\\W$", "-"))
      T.ok(not R.test("^\\W$", "a"))
    end)
    T.it("\\S matches non-space", function()
      T.ok(R.test("^\\S$", "a"))
      T.ok(not R.test("^\\S$", " "))
    end)
  end)

  T.describe("escape sequences", function()
    T.it("\\n matches newline", function()
      T.ok(R.test("a\\nb", "a\nb"))
      T.ok(not R.test("a\\nb", "ab"))
    end)
    T.it("\\t matches tab", function()
      T.ok(R.test("a\\tb", "a\tb"))
    end)
    T.it("\\r matches carriage return", function()
      T.ok(R.test("a\\rb", "a\rb"))
    end)
  end)

  -- ── find() ───────────────────────────────────────────────────────────────────

  T.describe("find()", function()
    T.it("returns start, stop positions", function()
      local s, e = R.find("world", "hello world")
      T.eq(s, 7)
      T.eq(e, 11)
    end)
    T.it("returns nil if no match", function()
      local s = R.find("xyz", "hello world")
      T.eq(s, nil)
    end)
    T.it("respects init parameter", function()
      local s, e = R.find("a", "banana", 4)
      T.eq(s, 4)  -- first 'a' at or after pos 4 (banana[4]='a')
    end)
    T.it("init skips earlier matches", function()
      local s1 = R.find("a", "banana", 1)
      local s2 = R.find("a", "banana", 3)
      T.eq(s1, 2)
      T.eq(s2, 4)
    end)
  end)

  -- ── find_all() ───────────────────────────────────────────────────────────────

  T.describe("find_all()", function()
    T.it("finds all non-overlapping matches", function()
      local matches = R.find_all("\\d+", "abc 123 def 456 ghi 789")
      T.eq(#matches, 3)
      T.eq(matches[1][1], 5)
      T.eq(matches[1][2], 7)
      T.eq(matches[2][1], 13)
      T.eq(matches[2][2], 15)
      T.eq(matches[3][1], 21)
      T.eq(matches[3][2], 23)
    end)
    T.it("returns empty table if no match", function()
      local matches = R.find_all("xyz", "hello world")
      T.eq(#matches, 0)
    end)
    T.it("returns captures in each match entry", function()
      local matches = R.find_all("(\\w+)=(\\w+)", "a=1 b=2 c=3")
      T.eq(#matches, 3)
      T.eq(matches[1][3], "a")
      T.eq(matches[1][4], "1")
      T.eq(matches[2][3], "b")
      T.eq(matches[2][4], "2")
    end)
  end)

  -- ── gsub() ───────────────────────────────────────────────────────────────────

  T.describe("gsub()", function()
    T.it("replaces all occurrences with string", function()
      local result, count = R.gsub("a", "banana", "o")
      T.eq(result, "bonono")
      T.eq(count, 3)
    end)
    T.it("replaces with function", function()
      local result, count = R.gsub("\\d+", "abc 123 def 456", function(m) return "[" .. m .. "]" end)
      T.eq(result, "abc [123] def [456]")
      T.eq(count, 2)
    end)
    T.it("replaces with capture backrefs %1", function()
      local result, count = R.gsub("(\\w+)", "hello world", "%1%1")
      T.eq(result, "hellohello worldworld")
      T.eq(count, 2)
    end)
    T.it("%0 = whole match", function()
      local result = R.gsub("\\d+", "abc 123", "[%0]")
      T.eq(result, "abc [123]")
    end)
    T.it("no match returns original", function()
      local result, count = R.gsub("xyz", "hello", "Q")
      T.eq(result, "hello")
      T.eq(count, 0)
    end)
  end)

  -- ── sub() ────────────────────────────────────────────────────────────────────

  T.describe("sub()", function()
    T.it("replaces first occurrence by default (n=1)", function()
      local result, count = R.sub("a", "banana", "o", 1)
      T.eq(result, "bonana")
      T.eq(count, 1)
    end)
    T.it("replaces up to n occurrences", function()
      local result, count = R.sub("a", "banana", "o", 2)
      T.eq(result, "bonona")
      T.eq(count, 2)
    end)
  end)

  -- ── split() ─────────────────────────────────────────────────────────────────

  T.describe("split()", function()
    T.it("splits on separator", function()
      local parts = R.split(",", "a,b,c,d")
      T.eq(#parts, 4)
      T.eq(parts[1], "a")
      T.eq(parts[2], "b")
      T.eq(parts[3], "c")
      T.eq(parts[4], "d")
    end)
    T.it("splits on whitespace", function()
      local parts = R.split("\\s+", "hello world  foo")
      T.eq(#parts, 3)
      T.eq(parts[1], "hello")
      T.eq(parts[2], "world")
      T.eq(parts[3], "foo")
    end)
    T.it("respects max_splits", function()
      local parts = R.split(",", "a,b,c,d", 2)
      T.eq(#parts, 3)
      T.eq(parts[1], "a")
      T.eq(parts[2], "b")
      T.eq(parts[3], "c,d")
    end)
    T.it("no match returns whole string", function()
      local parts = R.split("x", "hello")
      T.eq(#parts, 1)
      T.eq(parts[1], "hello")
    end)
  end)

  -- ── Compiled object ──────────────────────────────────────────────────────────

  T.describe("compiled regex object", function()
    T.it("compile returns re object", function()
      local re, err = R.compile("\\d+")
      T.ok(re ~= nil)
      T.eq(err, nil)
    end)
    T.it("re:test()", function()
      local re = R.compile("^\\d+$")
      T.ok(re:test("123"))
      T.ok(not re:test("abc"))
    end)
    T.it("re:find()", function()
      local re = R.compile("\\d+")
      local s, e = re:find("abc 123 def")
      T.eq(s, 5)
      T.eq(e, 7)
    end)
    T.it("re:find_all()", function()
      local re = R.compile("\\d+")
      local m = re:find_all("1 22 333")
      T.eq(#m, 3)
    end)
    T.it("re:gsub()", function()
      local re = R.compile("\\d+")
      local r, c = re:gsub("a1b2c3", "N")
      T.eq(r, "aNbNcN")
      T.eq(c, 3)
    end)
    T.it("re:split()", function()
      local re = R.compile(",")
      local parts = re:split("a,b,c")
      T.eq(#parts, 3)
    end)
  end)

  -- ── Complex patterns ─────────────────────────────────────────────────────────

  T.describe("complex patterns", function()
    T.it("email-like pattern", function()
      local re = R.compile("^[\\w.+-]+@[\\w-]+\\.[a-z]{2,}$")
      T.ok(re:test("user@example.com"))
      T.ok(re:test("user.name+tag@sub-domain.org"))
      T.ok(not re:test("notanemail"))
      T.ok(not re:test("@nodomain.com"))
    end)
    T.it("date-like pattern", function()
      local re = R.compile("^(\\d{4})-(\\d{2})-(\\d{2})$")
      local s, e, yr, mo, dy = re:find("2024-01-15")
      T.eq(yr, "2024")
      T.eq(mo, "01")
      T.eq(dy, "15")
      T.ok(not re:test("24-1-5"))
    end)
    T.it("ip-address-like pattern", function()
      local re = R.compile("^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$")
      T.ok(re:test("192.168.1.1"))
      T.ok(re:test("0.0.0.0"))
      T.ok(not re:test("192.168.1"))
      T.ok(not re:test("192.168.1.1.1"))
    end)
    T.it("word boundary simulation", function()
      -- Extract all words
      local words = {}
      for _, m in ipairs(R.find_all("\\w+", "the quick brown fox")) do
        words[#words + 1] = ("the quick brown fox"):sub(m[1], m[2])
      end
      T.eq(#words, 4)
      T.eq(words[1], "the")
      T.eq(words[4], "fox")
    end)
    T.it("nested quantifiers", function()
      T.ok(R.test("^(ab)+$", "ab"))
      T.ok(R.test("^(ab)+$", "ababab"))
      T.ok(not R.test("^(ab)+$", "aba"))
    end)
    T.it("alternation with anchors", function()
      T.ok(R.test("^(foo|bar|baz)$", "foo"))
      T.ok(R.test("^(foo|bar|baz)$", "bar"))
      T.ok(R.test("^(foo|bar|baz)$", "baz"))
      T.ok(not R.test("^(foo|bar|baz)$", "qux"))
    end)
  end)

  -- ── Error handling ───────────────────────────────────────────────────────────

  T.describe("error handling", function()
    T.it("unterminated group returns error", function()
      local re, err = R.compile("(hello")
      T.eq(re, nil)
      T.ok(err ~= nil)
      T.ok(type(err) == "string")
    end)
    T.it("unterminated character class returns error", function()
      local re, err = R.compile("[abc")
      T.eq(re, nil)
      T.ok(err ~= nil)
    end)
    T.it("unexpected character in pattern", function()
      local re, err = R.compile("hello)")
      T.eq(re, nil)
      T.ok(err ~= nil)
    end)
  end)

  -- ── match() ──────────────────────────────────────────────────────────────────

  T.describe("match()", function()
    T.it("returns end position of match anywhere in string", function()
      local e = R.match("\\d+", "abc 123 def")
      T.eq(e, 7)
    end)
    T.it("returns captures", function()
      local e, cap = R.match("(\\w+)", "hello world")
      T.eq(cap, "hello")
      T.eq(e, 5)
    end)
    T.it("returns nil if no match", function()
      local e = R.match("xyz", "hello")
      T.eq(e, nil)
    end)
  end)

  -- ── Shorthand in character class ─────────────────────────────────────────────

  T.describe("shorthands inside []", function()
    T.it("[\\d] matches digits", function()
      T.ok(R.test("^[\\d]+$", "123"))
      T.ok(not R.test("^[\\d]+$", "abc"))
    end)
    T.it("[\\w\\s] matches word or space", function()
      T.ok(R.test("^[\\w\\s]+$", "hello world"))
      T.ok(not R.test("^[\\w\\s]+$", "hello!"))
    end)
  end)

end)
