-- lib/ordered_map/ordered_map_test.lua

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local OrderedMap = require("lib.ordered_map")

T.describe("ordered_map", function()

  T.it("insertion order preserved in each()", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "a")
    T.eq(keys[2], "b")
    T.eq(keys[3], "c")
  end)

  T.it("update keeps existing position", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    m:set("a", 10)
    T.eq(m:get("a"), 10)
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "a")
    T.eq(keys[2], "b")
    T.eq(keys[3], "c")
  end)

  T.it("delete removes key from iteration", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local ok = m:delete("b")
    T.ok(ok)
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(#keys, 2)
    T.eq(keys[1], "a")
    T.eq(keys[2], "c")
  end)

  T.it("delete returns false for missing key", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    T.fail(m:delete("z"))
  end)

  T.it("len() is correct", function()
    local m = OrderedMap.new()
    T.eq(m:len(), 0)
    m:set("a", 1)
    T.eq(m:len(), 1)
    m:set("b", 2)
    T.eq(m:len(), 2)
    m:set("a", 99)   -- update, no change in len
    T.eq(m:len(), 2)
    m:delete("a")
    T.eq(m:len(), 1)
  end)

  T.it("has() returns true/false", function()
    local m = OrderedMap.new()
    m:set("x", 42)
    T.ok(m:has("x"))
    T.fail(m:has("y"))
    m:delete("x")
    T.fail(m:has("x"))
  end)

  T.it("at(1) returns first entry", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local k, v = m:at(1)
    T.eq(k, "a")
    T.eq(v, 1)
  end)

  T.it("at(-1) returns last entry", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local k, v = m:at(-1)
    T.eq(k, "c")
    T.eq(v, 3)
  end)

  T.it("at(n) returns nth entry", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local k, v = m:at(2)
    T.eq(k, "b")
    T.eq(v, 2)
  end)

  T.it("at() returns nil for out-of-range", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    local k, v = m:at(5)
    T.eq(k, nil)
    T.eq(v, nil)
    k, v = m:at(0)
    T.eq(k, nil)
  end)

  T.it("move_to_end: key becomes last in iteration", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    m:move_to_end("a")
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "b")
    T.eq(keys[2], "c")
    T.eq(keys[3], "a")
  end)

  T.it("move_to_front: key becomes first in iteration", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    m:move_to_front("c")
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "c")
    T.eq(keys[2], "a")
    T.eq(keys[3], "b")
  end)

  T.it("keys() returns array in insertion order", function()
    local m = OrderedMap.new()
    m:set("x", 10)
    m:set("y", 20)
    m:set("z", 30)
    local ks = m:keys()
    T.eq(ks[1], "x")
    T.eq(ks[2], "y")
    T.eq(ks[3], "z")
    T.eq(#ks, 3)
  end)

  T.it("values() returns array in insertion order", function()
    local m = OrderedMap.new()
    m:set("x", 10)
    m:set("y", 20)
    m:set("z", 30)
    local vs = m:values()
    T.eq(vs[1], 10)
    T.eq(vs[2], 20)
    T.eq(vs[3], 30)
    T.eq(#vs, 3)
  end)

  T.it("entries() returns array of {k,v} pairs in insertion order", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    local ents = m:entries()
    T.eq(ents[1][1], "a")
    T.eq(ents[1][2], 1)
    T.eq(ents[2][1], "b")
    T.eq(ents[2][2], 2)
    T.eq(#ents, 2)
  end)

  T.it("each_reverse() iterates in reverse order", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local keys = {}
    for k, _ in m:each_reverse() do keys[#keys + 1] = k end
    T.eq(keys[1], "c")
    T.eq(keys[2], "b")
    T.eq(keys[3], "a")
  end)

  T.it("copy() is independent and preserves order", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local m2 = m:copy()
    -- Same order
    local k1, v1 = m2:at(1)
    T.eq(k1, "a")
    T.eq(v1, 1)
    -- Independent
    m2:set("a", 99)
    T.eq(m:get("a"), 1)
    T.eq(m2:get("a"), 99)
  end)

  T.it("from_entries() preserves given order", function()
    local m = OrderedMap.from_entries({ {"z", 3}, {"a", 1}, {"m", 2} })
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "z")
    T.eq(keys[2], "a")
    T.eq(keys[3], "m")
  end)

  T.it("from_table() with explicit key order", function()
    local m = OrderedMap.from_table({x=1, y=2, z=3}, {"z", "x", "y"})
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "z")
    T.eq(keys[2], "x")
    T.eq(keys[3], "y")
    T.eq(m:len(), 3)
  end)

  T.it("map() transforms values and returns new ordered_map", function()
    local m = OrderedMap.new()
    m:set("a", 2)
    m:set("b", 4)
    local doubled = m:map(function(k, v) return k, v * 2 end)
    T.eq(doubled:get("a"), 4)
    T.eq(doubled:get("b"), 8)
    -- original unchanged
    T.eq(m:get("a"), 2)
    -- order preserved
    local k1 = doubled:at(1)
    T.eq(k1, "a")
  end)

  T.it("filter() removes non-matching entries", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 10)
    m:set("c", 5)
    local big = m:filter(function(_, v) return v > 5 end)
    T.eq(big:len(), 1)
    T.ok(big:has("b"))
    T.fail(big:has("a"))
    T.fail(big:has("c"))
  end)

  T.it("slice() returns correct subsequence as new ordered_map", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    m:set("d", 4)
    local sub = m:slice(2, 3)
    T.eq(sub:len(), 2)
    local k1, v1 = sub:at(1)
    local k2, v2 = sub:at(2)
    T.eq(k1, "b")
    T.eq(v1, 2)
    T.eq(k2, "c")
    T.eq(v2, 3)
  end)

  T.it("to_table() contains all key-value pairs", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:set("c", 3)
    local t = m:to_table()
    T.eq(t["a"], 1)
    T.eq(t["b"], 2)
    T.eq(t["c"], 3)
  end)

  T.it("move_to_end on already-tail is no-op", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:move_to_end("b")
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "a")
    T.eq(keys[2], "b")
  end)

  T.it("move_to_front on already-head is no-op", function()
    local m = OrderedMap.new()
    m:set("a", 1)
    m:set("b", 2)
    m:move_to_front("a")
    local keys = {}
    for k, _ in m:each() do keys[#keys + 1] = k end
    T.eq(keys[1], "a")
    T.eq(keys[2], "b")
  end)

  T.it("_tier is 'pure'", function()
    local OM = require("lib.ordered_map")
    T.eq(OM._tier, "pure")
  end)

end)
