if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local D = require("lib.duration")

-- ---------------------------------------------------------------------------
-- D.new
-- ---------------------------------------------------------------------------

T.describe("D.new", function()
  T.it("total_seconds returns the exact value", function()
    T.eq(D.new(90):total_seconds(), 90)
  end)
  T.it("accepts float seconds", function()
    T.eq(D.new(5445.5):total_seconds(), 5445.5)
  end)
  T.it("total_minutes", function()
    T.eq(D.new(90):total_minutes(), 1.5)
  end)
  T.it("total_hours", function()
    T.eq(D.new(7200):total_hours(), 2)
  end)
  T.it("total_days", function()
    T.eq(D.new(86400 * 2):total_days(), 2)
  end)
  T.it("total_milliseconds", function()
    T.eq(D.new(1.5):total_milliseconds(), 1500)
  end)
  T.it("zero", function()
    T.eq(D.new(0):total_seconds(), 0)
  end)
  T.it("negative seconds", function()
    T.eq(D.new(-30):total_seconds(), -30)
  end)
end)

-- ---------------------------------------------------------------------------
-- D.from_parts
-- ---------------------------------------------------------------------------

T.describe("D.from_parts", function()
  T.it("computes correct total from mixed parts", function()
    local d = D.from_parts({ days = 1, hours = 2, minutes = 30, seconds = 45, milliseconds = 500 })
    local expected = 86400 + 7200 + 1800 + 45 + 0.5
    T.eq(d:total_seconds(), expected)
  end)
  T.it("rounds-trip through parts()", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    local p = d:parts()
    T.eq(p.sign, 1)
    T.eq(p.days, 0)
    T.eq(p.hours, 1)
    T.eq(p.minutes, 30)
    T.eq(p.seconds, 45)
    T.eq(p.milliseconds, 0)
  end)
  T.it("parts() with milliseconds", function()
    local d = D.from_parts({ seconds = 1, milliseconds = 500 })
    local p = d:parts()
    T.eq(p.seconds, 1)
    T.eq(p.milliseconds, 500)
  end)
  T.it("parts() with days", function()
    local d = D.from_parts({ days = 2, hours = 3 })
    local p = d:parts()
    T.eq(p.days, 2)
    T.eq(p.hours, 3)
  end)
  T.it("from_parts with weeks", function()
    local d = D.from_parts({ weeks = 1 })
    T.eq(d:total_seconds(), 604800)
  end)
  T.it("negative parts sum correctly", function()
    local d = D.from_parts({ hours = 1, minutes = -30 })
    T.eq(d:total_seconds(), 1800)
  end)
  T.it("empty parts = zero", function()
    T.eq(D.from_parts({}):total_seconds(), 0)
  end)
end)

-- ---------------------------------------------------------------------------
-- D.parse — success cases
-- ---------------------------------------------------------------------------

T.describe("D.parse", function()
  T.it("1h30m45s", function()
    local d = D.parse("1h30m45s")
    T.eq(d:total_seconds(), 3600 + 1800 + 45)
  end)
  T.it("1:30:45 (HH:MM:SS)", function()
    local d = D.parse("1:30:45")
    T.eq(d:total_seconds(), 3600 + 1800 + 45)
  end)
  T.it("90m", function()
    T.eq(D.parse("90m"):total_seconds(), 5400)
  end)
  T.it("1.5h", function()
    T.eq(D.parse("1.5h"):total_seconds(), 5400)
  end)
  T.it("2d 4h 30m", function()
    local d = D.parse("2d 4h 30m")
    T.eq(d:total_seconds(), 2 * 86400 + 4 * 3600 + 30 * 60)
  end)
  T.it("-30s (negative)", function()
    T.eq(D.parse("-30s"):total_seconds(), -30)
  end)
  T.it("bare number → seconds", function()
    T.eq(D.parse("90"):total_seconds(), 90)
  end)
  T.it("0 → zero duration", function()
    T.eq(D.parse("0"):total_seconds(), 0)
  end)
  T.it("500ms", function()
    T.eq(D.parse("500ms"):total_seconds(), 0.5)
  end)
  T.it("1h30m (no seconds)", function()
    T.eq(D.parse("1h30m"):total_seconds(), 5400)
  end)
  T.it("MM:SS colon format", function()
    T.eq(D.parse("30:45"):total_seconds(), 30 * 60 + 45)
  end)
  T.it("HH:MM:SS.mmm with milliseconds", function()
    local d = D.parse("1:00:00.500")
    T.eq(d:total_seconds(), 3600.5)
  end)
  T.it("1w parses as 7 days", function()
    T.eq(D.parse("1w"):total_seconds(), 604800)
  end)
  T.it("case-insensitive: 1H30M", function()
    T.eq(D.parse("1H30M"):total_seconds(), 5400)
  end)
  T.it("hours unit word", function()
    T.eq(D.parse("2hours"):total_seconds(), 7200)
  end)
  T.it("minutes unit word", function()
    T.eq(D.parse("45minutes"):total_seconds(), 2700)
  end)
  T.it("seconds unit word", function()
    T.eq(D.parse("10seconds"):total_seconds(), 10)
  end)
  T.it("days unit word", function()
    T.eq(D.parse("3days"):total_seconds(), 3 * 86400)
  end)
  T.it("negative HH:MM:SS", function()
    T.eq(D.parse("-1:00:00"):total_seconds(), -3600)
  end)
end)

-- ---------------------------------------------------------------------------
-- D.parse — error cases
-- ---------------------------------------------------------------------------

T.describe("D.parse errors", function()
  T.it("bad input returns nil+err", function()
    local d, err = D.parse("1x")
    T.eq(d, nil)
    T.ok(type(err) == "string")
  end)
  T.it("non-string returns nil+err", function()
    local d, err = D.parse(42)
    T.eq(d, nil)
    T.ok(type(err) == "string")
  end)
  T.it("empty string returns nil+err", function()
    local d, err = D.parse("")
    T.eq(d, nil)
    T.ok(type(err) == "string")
  end)
end)

-- ---------------------------------------------------------------------------
-- Formatting
-- ---------------------------------------------------------------------------

T.describe("format() default", function()
  T.it("1h 30m 45s", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    T.eq(d:format(), "1h 30m 45s")
  end)
  T.it("omits zero parts", function()
    T.eq(D.new(3600):format(), "1h")
  end)
  T.it("500ms sub-second", function()
    T.eq(D.from_parts({ milliseconds = 500 }):format(), "500ms")
  end)
  T.it("zero duration → 0s", function()
    T.eq(D.new(0):format(), "0s")
  end)
  T.it("negative duration prepends -", function()
    T.eq(D.new(-30):format(), "-30s")
  end)
  T.it("negative with multiple parts", function()
    local d = D.from_parts({ hours = -1, minutes = -30 })
    T.eq(d:format(), "-1h 30m")
  end)
end)

T.describe("format('HH:MM:SS')", function()
  T.it("basic", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    T.eq(d:format("HH:MM:SS"), "01:30:45")
  end)
  T.it("zero is 00:00:00", function()
    T.eq(D.new(0):format("HH:MM:SS"), "00:00:00")
  end)
  T.it("days roll into hours", function()
    local d = D.from_parts({ days = 1, hours = 2 })
    T.eq(d:format("HH:MM:SS"), "26:00:00")
  end)
  T.it("with milliseconds shows decimal", function()
    local d = D.from_parts({ hours = 1, milliseconds = 500 })
    T.eq(d:format("HH:MM:SS"), "01:00:00.500")
  end)
  T.it("negative", function()
    T.eq(D.new(-3661):format("HH:MM:SS"), "-01:01:01")
  end)
end)

T.describe("format('compact')", function()
  T.it("basic", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    T.eq(d:format("compact"), "1h30m45s")
  end)
  T.it("zero → 0s", function()
    T.eq(D.new(0):format("compact"), "0s")
  end)
  T.it("negative", function()
    T.eq(D.new(-30):format("compact"), "-30s")
  end)
end)

T.describe("format('long')", function()
  T.it("singular", function()
    T.eq(D.new(1):format("long"), "1 second")
  end)
  T.it("plural", function()
    T.eq(D.new(2):format("long"), "2 seconds")
  end)
  T.it("multiple parts joined with and", function()
    local d = D.from_parts({ hours = 1, minutes = 30 })
    T.eq(d:format("long"), "1 hour and 30 minutes")
  end)
  T.it("three parts joined with Oxford comma", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    T.eq(d:format("long"), "1 hour, 30 minutes, and 45 seconds")
  end)
  T.it("zero → 0 seconds", function()
    T.eq(D.new(0):format("long"), "0 seconds")
  end)
  T.it("negative", function()
    T.eq(D.new(-60):format("long"), "-1 minute")
  end)
end)

T.describe("format('iso')", function()
  T.it("basic PT1H30M45S", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    T.eq(d:format("iso"), "PT1H30M45S")
  end)
  T.it("with days P1DT2H", function()
    local d = D.from_parts({ days = 1, hours = 2 })
    T.eq(d:format("iso"), "P1DT2H")
  end)
  T.it("zero → PT0S", function()
    T.eq(D.new(0):format("iso"), "PT0S")
  end)
  T.it("milliseconds in decimal seconds", function()
    local d = D.from_parts({ seconds = 1, milliseconds = 500 })
    T.eq(d:format("iso"), "PT1.500S")
  end)
  T.it("negative", function()
    T.eq(D.new(-3600):format("iso"), "-PT1H")
  end)
end)

T.describe("format('clock')", function()
  T.it("basic", function()
    local d = D.from_parts({ hours = 1, minutes = 30, seconds = 45 })
    T.eq(d:format("clock"), "1:30:45")
  end)
  T.it("zero", function()
    T.eq(D.new(0):format("clock"), "0:00:00")
  end)
  T.it("negative", function()
    T.eq(D.new(-90):format("clock"), "-0:01:30")
  end)
end)

-- ---------------------------------------------------------------------------
-- Arithmetic
-- ---------------------------------------------------------------------------

T.describe("arithmetic", function()
  T.it("add", function()
    T.eq(D.new(30):add(D.new(60)):total_seconds(), 90)
  end)
  T.it("sub", function()
    T.eq(D.new(90):sub(D.new(30)):total_seconds(), 60)
  end)
  T.it("mul", function()
    T.eq(D.new(60):mul(3):total_seconds(), 180)
  end)
  T.it("div", function()
    T.eq(D.new(180):div(3):total_seconds(), 60)
  end)
  T.it("neg", function()
    T.eq(D.new(30):neg():total_seconds(), -30)
  end)
  T.it("abs of negative", function()
    T.eq(D.new(-30):abs():total_seconds(), 30)
  end)
  T.it("abs of positive unchanged", function()
    T.eq(D.new(30):abs():total_seconds(), 30)
  end)
  T.it("add negative", function()
    T.eq(D.new(60):add(D.new(-30)):total_seconds(), 30)
  end)
  T.it("chained arithmetic", function()
    T.eq(D.new(60):mul(2):add(D.new(30)):total_seconds(), 150)
  end)
end)

-- ---------------------------------------------------------------------------
-- Comparison
-- ---------------------------------------------------------------------------

T.describe("comparison", function()
  T.it("eq same", function()
    T.ok(D.new(60):eq(D.new(60)))
  end)
  T.it("eq different is false", function()
    T.fail(D.new(60):eq(D.new(61)))
  end)
  T.it("lt", function()
    T.ok(D.new(30):lt(D.new(60)))
  end)
  T.it("lt false when equal", function()
    T.fail(D.new(60):lt(D.new(60)))
  end)
  T.it("lte equal", function()
    T.ok(D.new(60):lte(D.new(60)))
  end)
  T.it("lte less", function()
    T.ok(D.new(30):lte(D.new(60)))
  end)
  T.it("lte false when greater", function()
    T.fail(D.new(61):lte(D.new(60)))
  end)
  T.it("gt", function()
    T.ok(D.new(60):gt(D.new(30)))
  end)
  T.it("gt false when equal", function()
    T.fail(D.new(60):gt(D.new(60)))
  end)
  T.it("gte equal", function()
    T.ok(D.new(60):gte(D.new(60)))
  end)
  T.it("gte greater", function()
    T.ok(D.new(61):gte(D.new(60)))
  end)
  T.it("gte false when less", function()
    T.fail(D.new(59):gte(D.new(60)))
  end)
  T.it("negative vs positive", function()
    T.ok(D.new(-1):lt(D.new(1)))
  end)
end)

-- ---------------------------------------------------------------------------
-- Constants
-- ---------------------------------------------------------------------------

T.describe("constants", function()
  T.it("D.SECOND = 1s", function()
    T.eq(D.SECOND:total_seconds(), 1)
  end)
  T.it("D.MINUTE = 60s", function()
    T.eq(D.MINUTE:total_seconds(), 60)
  end)
  T.it("D.HOUR = 3600s", function()
    T.eq(D.HOUR:total_seconds(), 3600)
  end)
  T.it("D.DAY = 86400s", function()
    T.eq(D.DAY:total_seconds(), 86400)
  end)
  T.it("D.WEEK = 604800s", function()
    T.eq(D.WEEK:total_seconds(), 604800)
  end)
  T.it("MINUTE = 60 * SECOND", function()
    T.ok(D.MINUTE:eq(D.SECOND:mul(60)))
  end)
  T.it("HOUR = 60 * MINUTE", function()
    T.ok(D.HOUR:eq(D.MINUTE:mul(60)))
  end)
  T.it("DAY = 24 * HOUR", function()
    T.ok(D.DAY:eq(D.HOUR:mul(24)))
  end)
  T.it("WEEK = 7 * DAY", function()
    T.ok(D.WEEK:eq(D.DAY:mul(7)))
  end)
end)

-- ---------------------------------------------------------------------------
-- D.zero and D.between
-- ---------------------------------------------------------------------------

T.describe("utilities", function()
  T.it("D.zero() = 0s", function()
    T.eq(D.zero():total_seconds(), 0)
  end)
  T.it("D.between(t1, t2) = t2 - t1", function()
    T.eq(D.between(1000, 1090):total_seconds(), 90)
  end)
  T.it("D.between negative when t1 > t2", function()
    T.eq(D.between(1090, 1000):total_seconds(), -90)
  end)
  T.it("D._tier is 'pure'", function()
    T.eq(D._tier, "pure")
  end)
end)
