if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local matrix = require("lib.matrix")

T.describe("matrix", function()

  T.describe("construction", function()
    T.it("new creates zero matrix", function()
      local m = matrix.new(2, 3)
      T.eq(m:rows(), 2)
      T.eq(m:cols(), 3)
      T.eq(m:get(1, 1), 0)
      T.eq(m:get(2, 3), 0)
    end)

    T.it("new with data", function()
      local m = matrix.new(2, 2, {1, 2, 3, 4})
      T.eq(m:get(1, 1), 1)
      T.eq(m:get(1, 2), 2)
      T.eq(m:get(2, 1), 3)
      T.eq(m:get(2, 2), 4)
    end)

    T.it("new rejects bad dimensions", function()
      local m, err = matrix.new(0, 3)
      T.eq(m, nil)
      T.ok(err)
    end)

    T.it("new rejects mismatched data length", function()
      local m, err = matrix.new(2, 2, {1, 2, 3})
      T.eq(m, nil)
      T.ok(err)
    end)

    T.it("from_rows", function()
      local m = matrix.from_rows({{1, 2, 3}, {4, 5, 6}})
      T.eq(m:rows(), 2)
      T.eq(m:cols(), 3)
      T.eq(m:get(1, 1), 1)
      T.eq(m:get(2, 3), 6)
    end)

    T.it("from_rows rejects jagged", function()
      local m, err = matrix.from_rows({{1, 2}, {3}})
      T.eq(m, nil)
      T.ok(err)
    end)

    T.it("from_rows rejects empty", function()
      local m, err = matrix.from_rows({})
      T.eq(m, nil)
      T.ok(err)
    end)

    T.it("identity", function()
      local m = matrix.identity(3)
      T.eq(m:get(1, 1), 1)
      T.eq(m:get(2, 2), 1)
      T.eq(m:get(3, 3), 1)
      T.eq(m:get(1, 2), 0)
      T.eq(m:get(2, 3), 0)
    end)

    T.it("zeros", function()
      local m = matrix.zeros(2, 3)
      T.eq(m:get(1, 1), 0)
      T.eq(m:get(2, 3), 0)
    end)

    T.it("ones", function()
      local m = matrix.ones(2, 2)
      T.eq(m:get(1, 1), 1)
      T.eq(m:get(1, 2), 1)
      T.eq(m:get(2, 1), 1)
      T.eq(m:get(2, 2), 1)
    end)

    T.it("diag", function()
      local m = matrix.diag({2, 3, 5})
      T.eq(m:rows(), 3)
      T.eq(m:cols(), 3)
      T.eq(m:get(1, 1), 2)
      T.eq(m:get(2, 2), 3)
      T.eq(m:get(3, 3), 5)
      T.eq(m:get(1, 2), 0)
    end)

    T.it("random produces values in range", function()
      local m = matrix.random(3, 3, 10, 20)
      for i = 1, 3 do
        for j = 1, 3 do
          local v = m:get(i, j)
          T.ok(v >= 10, "value >= lo")
          T.ok(v < 20, "value < hi")
        end
      end
    end)
  end)

  T.describe("accessors", function()
    T.it("size returns rows and cols", function()
      local m = matrix.new(3, 4)
      local r, c = m:size()
      T.eq(r, 3)
      T.eq(c, 4)
    end)

    T.it("set and get", function()
      local m = matrix.new(2, 2)
      m:set(1, 2, 42)
      T.eq(m:get(1, 2), 42)
      T.eq(m:get(1, 1), 0)
    end)

    T.it("row returns array", function()
      local m = matrix.from_rows({{1, 2, 3}, {4, 5, 6}})
      local r = m:row(2)
      T.eq(r[1], 4)
      T.eq(r[2], 5)
      T.eq(r[3], 6)
    end)

    T.it("col returns array", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}, {5, 6}})
      local c = m:col(2)
      T.eq(c[1], 2)
      T.eq(c[2], 4)
      T.eq(c[3], 6)
    end)
  end)

  T.describe("arithmetic", function()
    T.it("add", function()
      local a = matrix.from_rows({{1, 2}, {3, 4}})
      local b = matrix.from_rows({{5, 6}, {7, 8}})
      local c = a:add(b)
      T.eq(c:get(1, 1), 6)
      T.eq(c:get(1, 2), 8)
      T.eq(c:get(2, 1), 10)
      T.eq(c:get(2, 2), 12)
    end)

    T.it("add rejects dimension mismatch", function()
      local a = matrix.new(2, 2)
      local b = matrix.new(2, 3)
      local c, err = a:add(b)
      T.eq(c, nil)
      T.ok(err)
    end)

    T.it("sub", function()
      local a = matrix.from_rows({{5, 6}, {7, 8}})
      local b = matrix.from_rows({{1, 2}, {3, 4}})
      local c = a:sub(b)
      T.eq(c:get(1, 1), 4)
      T.eq(c:get(2, 2), 4)
    end)

    T.it("mul 2x3 * 3x2", function()
      local a = matrix.from_rows({{1, 2, 3}, {4, 5, 6}})
      local b = matrix.from_rows({{7, 8}, {9, 10}, {11, 12}})
      local c = a:mul(b)
      T.eq(c:rows(), 2)
      T.eq(c:cols(), 2)
      T.eq(c:get(1, 1), 58)   -- 1*7+2*9+3*11
      T.eq(c:get(1, 2), 64)   -- 1*8+2*10+3*12
      T.eq(c:get(2, 1), 139)  -- 4*7+5*9+6*11
      T.eq(c:get(2, 2), 154)  -- 4*8+5*10+6*12
    end)

    T.it("mul rejects inner dim mismatch", function()
      local a = matrix.new(2, 3)
      local b = matrix.new(2, 2)
      local c, err = a:mul(b)
      T.eq(c, nil)
      T.ok(err)
    end)

    T.it("scale", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      local s = m:scale(3)
      T.eq(s:get(1, 1), 3)
      T.eq(s:get(2, 2), 12)
    end)

    T.it("neg", function()
      local m = matrix.from_rows({{1, -2}, {3, 0}})
      local n = m:neg()
      T.eq(n:get(1, 1), -1)
      T.eq(n:get(1, 2), 2)
      T.eq(n:get(2, 1), -3)
      T.eq(n:get(2, 2), 0)
    end)
  end)

  T.describe("transpose", function()
    T.it("transposes non-square", function()
      local m = matrix.from_rows({{1, 2, 3}, {4, 5, 6}})
      local t = m:transpose()
      T.eq(t:rows(), 3)
      T.eq(t:cols(), 2)
      T.eq(t:get(1, 1), 1)
      T.eq(t:get(1, 2), 4)
      T.eq(t:get(2, 1), 2)
      T.eq(t:get(3, 2), 6)
    end)

    T.it("double transpose is identity", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      T.ok(m:transpose():transpose():eq(m))
    end)
  end)

  T.describe("trace", function()
    T.it("trace of identity", function()
      T.eq(matrix.identity(4):trace(), 4)
    end)

    T.it("trace of custom", function()
      local m = matrix.from_rows({{1, 0}, {0, 5}})
      T.eq(m:trace(), 6)
    end)

    T.it("trace rejects non-square", function()
      local m = matrix.new(2, 3)
      local t, err = m:trace()
      T.eq(t, nil)
      T.ok(err)
    end)
  end)

  T.describe("determinant", function()
    T.it("1x1", function()
      local m = matrix.new(1, 1, {7})
      T.eq(m:det(), 7)
    end)

    T.it("2x2", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      T.eq(m:det(), -2)
    end)

    T.it("3x3", function()
      local m = matrix.from_rows({{6, 1, 1}, {4, -2, 5}, {2, 8, 7}})
      -- det = 6(-2*7-5*8) - 1(4*7-5*2) + 1(4*8-(-2)*2) = 6(-54) - 1(18) + 1(36) = -324 - 18 + 36 = -306
      local d = m:det()
      T.ok(math.abs(d - (-306)) < 1e-9, "3x3 det")
    end)

    T.it("identity det is 1", function()
      T.eq(matrix.identity(4):det(), 1)
    end)

    T.it("singular det is 0", function()
      local m = matrix.from_rows({{1, 2}, {2, 4}})
      T.eq(m:det(), 0)
    end)

    T.it("det rejects non-square", function()
      local m = matrix.new(2, 3)
      local d, err = m:det()
      T.eq(d, nil)
      T.ok(err)
    end)
  end)

  T.describe("inverse", function()
    T.it("2x2 inverse", function()
      local m = matrix.from_rows({{4, 7}, {2, 6}})
      local inv = m:inverse()
      T.ok(inv, "inverse should exist")
      local prod = m:mul(inv)
      T.ok(prod:eq(matrix.identity(2), 1e-9), "M * M^-1 = I")
    end)

    T.it("3x3 inverse", function()
      local m = matrix.from_rows({{1, 2, 3}, {0, 1, 4}, {5, 6, 0}})
      local inv = m:inverse()
      T.ok(inv, "inverse should exist")
      local prod = m:mul(inv)
      T.ok(prod:eq(matrix.identity(3), 1e-9), "M * M^-1 = I")
    end)

    T.it("singular returns nil", function()
      local m = matrix.from_rows({{1, 2}, {2, 4}})
      local inv, err = m:inverse()
      T.eq(inv, nil)
      T.ok(err)
    end)

    T.it("inverse rejects non-square", function()
      local m = matrix.new(2, 3)
      local inv, err = m:inverse()
      T.eq(inv, nil)
      T.ok(err)
    end)

    T.it("identity inverse is identity", function()
      local I = matrix.identity(3)
      local inv = I:inverse()
      T.ok(inv:eq(I, 1e-9))
    end)
  end)

  T.describe("solve", function()
    T.it("2x2 system", function()
      -- x + 2y = 5, 3x + 4y = 11 => x=1, y=2
      local A = matrix.from_rows({{1, 2}, {3, 4}})
      local b = matrix.new(2, 1, {5, 11})
      local x = matrix.solve(A, b)
      T.ok(x, "solution should exist")
      T.ok(math.abs(x:get(1, 1) - 1) < 1e-9, "x=1")
      T.ok(math.abs(x:get(2, 1) - 2) < 1e-9, "y=2")
    end)

    T.it("3x3 system", function()
      local A = matrix.from_rows({{2, 1, -1}, {-3, -1, 2}, {-2, 1, 2}})
      local b = matrix.new(3, 1, {8, -11, -3})
      local x = matrix.solve(A, b)
      T.ok(x, "solution should exist")
      T.ok(math.abs(x:get(1, 1) - 2) < 1e-9, "x1=2")
      T.ok(math.abs(x:get(2, 1) - 3) < 1e-9, "x2=3")
      T.ok(math.abs(x:get(3, 1) - (-1)) < 1e-9, "x3=-1")
    end)

    T.it("singular system returns nil", function()
      local A = matrix.from_rows({{1, 2}, {2, 4}})
      local b = matrix.new(2, 1, {3, 6})
      local x, err = matrix.solve(A, b)
      T.eq(x, nil)
      T.ok(err)
    end)

    T.it("verify Ax=b", function()
      local A = matrix.from_rows({{1, 2}, {3, 4}})
      local b = matrix.new(2, 1, {5, 11})
      local x = matrix.solve(A, b)
      local Ax = A:mul(x)
      T.ok(Ax:eq(b, 1e-9), "Ax should equal b")
    end)
  end)

  T.describe("map", function()
    T.it("doubles all elements", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      local doubled = m:map(function(v) return v * 2 end)
      T.eq(doubled:get(1, 1), 2)
      T.eq(doubled:get(2, 2), 8)
    end)

    T.it("absolute value", function()
      local m = matrix.from_rows({{-1, 2}, {-3, 4}})
      local a = m:map(math.abs)
      T.eq(a:get(1, 1), 1)
      T.eq(a:get(2, 1), 3)
    end)
  end)

  T.describe("reshape", function()
    T.it("2x3 to 3x2", function()
      local m = matrix.from_rows({{1, 2, 3}, {4, 5, 6}})
      local r = m:reshape(3, 2)
      T.eq(r:rows(), 3)
      T.eq(r:cols(), 2)
      T.eq(r:get(1, 1), 1)
      T.eq(r:get(1, 2), 2)
      T.eq(r:get(2, 1), 3)
      T.eq(r:get(3, 2), 6)
    end)

    T.it("rejects incompatible reshape", function()
      local m = matrix.new(2, 3)
      local r, err = m:reshape(2, 2)
      T.eq(r, nil)
      T.ok(err)
    end)

    T.it("reshape to 1xN", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      local r = m:reshape(1, 4)
      T.eq(r:rows(), 1)
      T.eq(r:cols(), 4)
      T.eq(r:get(1, 3), 3)
    end)
  end)

  T.describe("to_array and to_rows", function()
    T.it("to_array returns flat copy", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      local a = m:to_array()
      T.eq(#a, 4)
      T.eq(a[1], 1)
      T.eq(a[4], 4)
      -- mutating copy doesn't affect matrix
      a[1] = 99
      T.eq(m:get(1, 1), 1)
    end)

    T.it("to_rows returns nested arrays", function()
      local m = matrix.from_rows({{1, 2, 3}, {4, 5, 6}})
      local rows = m:to_rows()
      T.eq(#rows, 2)
      T.eq(#rows[1], 3)
      T.eq(rows[1][1], 1)
      T.eq(rows[2][3], 6)
    end)
  end)

  T.describe("norm and dot", function()
    T.it("frobenius norm", function()
      local m = matrix.from_rows({{3, 4}})
      T.eq(m:norm(), 5) -- sqrt(9+16)
    end)

    T.it("frobenius norm of identity", function()
      local n = matrix.identity(3):norm()
      T.ok(math.abs(n - math.sqrt(3)) < 1e-9)
    end)

    T.it("dot product", function()
      local a = matrix.from_rows({{1, 2}, {3, 4}})
      local b = matrix.from_rows({{5, 6}, {7, 8}})
      -- 1*5 + 2*6 + 3*7 + 4*8 = 5+12+21+32 = 70
      T.eq(a:dot(b), 70)
    end)

    T.it("dot rejects mismatch", function()
      local a = matrix.new(2, 2)
      local b = matrix.new(2, 3)
      local d, err = a:dot(b)
      T.eq(d, nil)
      T.ok(err)
    end)
  end)

  T.describe("eq", function()
    T.it("equal matrices", function()
      local a = matrix.from_rows({{1, 2}, {3, 4}})
      local b = matrix.from_rows({{1, 2}, {3, 4}})
      T.ok(a:eq(b))
    end)

    T.it("unequal matrices", function()
      local a = matrix.from_rows({{1, 2}, {3, 4}})
      local b = matrix.from_rows({{1, 2}, {3, 5}})
      T.ok(not a:eq(b))
    end)

    T.it("different dimensions", function()
      local a = matrix.new(2, 2)
      local b = matrix.new(2, 3)
      T.ok(not a:eq(b))
    end)

    T.it("epsilon tolerance", function()
      local a = matrix.from_rows({{1.0, 2.0}})
      local b = matrix.from_rows({{1.0000001, 2.0000001}})
      T.ok(not a:eq(b))
      T.ok(a:eq(b, 1e-6))
    end)
  end)

  T.describe("edge cases", function()
    T.it("1x1 matrix operations", function()
      local m = matrix.new(1, 1, {5})
      T.eq(m:det(), 5)
      T.eq(m:trace(), 5)
      local inv = m:inverse()
      T.ok(math.abs(inv:get(1, 1) - 0.2) < 1e-9)
      T.eq(m:norm(), 5)
    end)

    T.it("non-square transpose round-trip", function()
      local m = matrix.from_rows({{1, 2, 3}})
      local t = m:transpose()
      T.eq(t:rows(), 3)
      T.eq(t:cols(), 1)
      T.ok(t:transpose():eq(m))
    end)

    T.it("mul by identity is identity", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      local I = matrix.identity(2)
      T.ok(m:mul(I):eq(m))
      T.ok(I:mul(m):eq(m))
    end)

    T.it("tostring works", function()
      local m = matrix.from_rows({{1, 2}, {3, 4}})
      local s = tostring(m)
      T.ok(type(s) == "string")
      T.ok(#s > 0)
    end)

    T.it("data is copied, not shared", function()
      local data = {1, 2, 3, 4}
      local m = matrix.new(2, 2, data)
      data[1] = 99
      T.eq(m:get(1, 1), 1, "matrix data should be independent copy")
    end)
  end)
end)
