if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local V = require("lib.validation")

T.describe("V.string()", function()
  T.it("passes for strings", function()
    T.ok(V.string():check("hello"))
  end)
  T.it("fails for non-strings", function()
    local ok, err = V.string():check(42)
    T.fail(ok)
    T.ok(err)
    T.eq(err.errors[1].message, "expected string, got number")
  end)
  T.it("min: too short", function()
    local ok, err = V.string():min(3):check("ab")
    T.fail(ok)
    T.ok(err.errors[1].message:find("min 3"))
  end)
  T.it("min: exact length passes", function()
    T.ok(V.string():min(3):check("abc"))
  end)
  T.it("max: too long", function()
    local ok, err = V.string():max(5):check("toolong")
    T.fail(ok)
    T.ok(err.errors[1].message:find("max 5"))
  end)
  T.it("max: exact length passes", function()
    T.ok(V.string():max(5):check("hello"))
  end)
  T.it("pattern: match passes", function()
    T.ok(V.string():pattern("^%a+$"):check("abc"))
  end)
  T.it("pattern: mismatch fails", function()
    local ok, err = V.string():pattern("^%a+$", "only letters"):check("abc123")
    T.fail(ok)
    T.eq(err.errors[1].message, "only letters")
  end)
  T.it("email: valid", function()
    T.ok(V.string():email():check("user@example.com"))
  end)
  T.it("email: invalid", function()
    local ok, err = V.string():email():check("notanemail")
    T.fail(ok)
    T.ok(err.errors[1].message:find("email"))
  end)
  T.it("url: valid", function()
    T.ok(V.string():url():check("https://example.com/path"))
  end)
  T.it("url: invalid", function()
    local ok, err = V.string():url():check("notaurl")
    T.fail(ok)
    T.ok(err.errors[1].message:find("URL"))
  end)
  T.it("non_empty: non-empty passes", function()
    T.ok(V.string():non_empty():check("x"))
  end)
  T.it("non_empty: empty fails", function()
    local ok, err = V.string():non_empty():check("")
    T.fail(ok)
    T.ok(err.errors[1].message:find("empty"))
  end)
  T.it("required by default: nil fails", function()
    local ok, err = V.string():check(nil)
    T.fail(ok)
    T.eq(err.errors[1].message, "required")
  end)
end)

T.describe("V.number()", function()
  T.it("passes for numbers", function()
    T.ok(V.number():check(3.14))
  end)
  T.it("fails for non-numbers", function()
    local ok, err = V.number():check("hello")
    T.fail(ok)
    T.ok(err.errors[1].message:find("number"))
  end)
  T.it("min: too small", function()
    local ok, err = V.number():min(0):check(-1)
    T.fail(ok)
    T.ok(err.errors[1].message:find("min 0"))
  end)
  T.it("min: boundary passes", function()
    T.ok(V.number():min(0):check(0))
  end)
  T.it("max: too large", function()
    local ok, err = V.number():max(100):check(101)
    T.fail(ok)
    T.ok(err.errors[1].message:find("max 100"))
  end)
  T.it("positive: positive passes", function()
    T.ok(V.number():positive():check(1))
  end)
  T.it("positive: zero fails", function()
    local ok, _ = V.number():positive():check(0)
    T.fail(ok)
  end)
  T.it("int: whole number passes", function()
    T.ok(V.number():int():check(3))
  end)
  T.it("int: fraction fails", function()
    local ok, err = V.number():int():check(3.5)
    T.fail(ok)
    T.ok(err.errors[1].message:find("whole"))
  end)
end)

T.describe("V.integer()", function()
  T.it("passes for integers", function()
    T.ok(V.integer():check(7))
  end)
  T.it("fails for floats", function()
    local ok, err = V.integer():check(7.5)
    T.fail(ok)
    T.ok(err.errors[1].message:find("integer"))
  end)
  T.it("fails for non-numbers", function()
    local ok, _ = V.integer():check("7")
    T.fail(ok)
  end)
  T.it("between: in range passes", function()
    T.ok(V.integer():between(1, 10):check(5))
  end)
  T.it("between: out of range fails", function()
    local ok, err = V.integer():between(1, 10):check(11)
    T.fail(ok)
    T.ok(err.errors[1].message:find("max 10"))
  end)
  T.it("between: below range fails", function()
    local ok, _ = V.integer():between(1, 10):check(0)
    T.fail(ok)
  end)
end)

T.describe("V.boolean()", function()
  T.it("passes for booleans", function()
    T.ok(V.boolean():check(true))
    T.ok(V.boolean():check(false))
  end)
  T.it("fails for non-booleans", function()
    local ok, err = V.boolean():check(1)
    T.fail(ok)
    T.ok(err.errors[1].message:find("boolean"))
  end)
end)

T.describe("V.nil_val()", function()
  T.it("passes for nil", function()
    T.ok(V.nil_val():check(nil))
  end)
  T.it("fails for non-nil", function()
    local ok, err = V.nil_val():check(false)
    T.fail(ok)
    T.ok(err.errors[1].message:find("nil"))
  end)
  T.it("is_optional returns true", function()
    T.ok(V.nil_val():is_optional())
  end)
end)

T.describe("V.any()", function()
  T.it("passes for any value", function()
    T.ok(V.any():check(nil))
    T.ok(V.any():check(42))
    T.ok(V.any():check("x"))
    T.ok(V.any():check({}))
  end)
end)

T.describe("coercion", function()
  T.it("string:coerce: tostrings value", function()
    local v, err = V.string():coerce():parse(42)
    T.eq(err, nil)
    T.eq(v, "42")
  end)
  T.it("number:coerce: parses string", function()
    local v, err = V.number():coerce():parse("3.14")
    T.eq(err, nil)
    T.eq(v, 3.14)
  end)
  T.it("number:coerce: fails on non-numeric string", function()
    local v, err = V.number():coerce():parse("abc")
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("boolean:coerce: 'true' → true", function()
    local v, err = V.boolean():coerce():parse("true")
    T.eq(err, nil)
    T.eq(v, true)
  end)
  T.it("boolean:coerce: '1' → true", function()
    local v, err = V.boolean():coerce():parse("1")
    T.eq(err, nil)
    T.eq(v, true)
  end)
  T.it("boolean:coerce: 'yes' → true", function()
    local v, err = V.boolean():coerce():parse("yes")
    T.eq(err, nil)
    T.eq(v, true)
  end)
  T.it("boolean:coerce: 'false' → false", function()
    local v, err = V.boolean():coerce():parse("false")
    T.eq(err, nil)
    T.eq(v, false)
  end)
  T.it("boolean:coerce: 'no' → false", function()
    local v, err = V.boolean():coerce():parse("no")
    T.eq(err, nil)
    T.eq(v, false)
  end)
  T.it("boolean:coerce: unknown value fails", function()
    local v, err = V.boolean():coerce():parse("maybe")
    T.eq(v, nil)
    T.ok(err)
  end)
end)

T.describe("optional / nullable / default", function()
  T.it("optional: nil passes", function()
    T.ok(V.string():optional():check(nil))
  end)
  T.it("optional: non-nil still validated", function()
    local ok, err = V.string():optional():check(42)
    T.fail(ok)
    T.ok(err)
  end)
  T.it("nullable: nil passes", function()
    T.ok(V.number():nullable():check(nil))
  end)
  T.it("default: nil becomes default", function()
    local v, err = V.string():default("hello"):parse(nil)
    T.eq(err, nil)
    T.eq(v, "hello")
  end)
  T.it("default: non-nil still validated", function()
    local v, err = V.string():default("x"):parse(42)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("is_optional: true when optional", function()
    T.ok(V.string():optional():is_optional())
  end)
  T.it("is_optional: false for plain string", function()
    T.fail(V.string():is_optional())
  end)
end)

T.describe("V.array()", function()
  T.it("valid array of strings", function()
    T.ok(V.array(V.string()):check({"a", "b", "c"}))
  end)
  T.it("wrong element type fails", function()
    local ok, err = V.array(V.string()):check({"a", 2, "c"})
    T.fail(ok)
    T.ok(#err.errors > 0)
    T.ok(err.errors[1].path:find("%[2%]"))
  end)
  T.it("empty array passes", function()
    T.ok(V.array(V.number()):check({}))
  end)
  T.it("non-table fails", function()
    local ok, _ = V.array(V.string()):check("oops")
    T.fail(ok)
  end)
  T.it("min length: too few fails", function()
    local ok, err = V.array(V.string()):min(2):check({"a"})
    T.fail(ok)
    T.ok(err.errors[1].message:find("min 2"))
  end)
  T.it("max length: too many fails", function()
    local ok, err = V.array(V.string()):max(2):check({"a","b","c"})
    T.fail(ok)
    T.ok(err.errors[1].message:find("max 2"))
  end)
  T.it("parse: returns coerced array", function()
    local v, err = V.array(V.number():coerce()):parse({"1", "2", "3"})
    T.eq(err, nil)
    T.eq(v[1], 1)
    T.eq(v[2], 2)
    T.eq(v[3], 3)
  end)
end)

T.describe("V.record()", function()
  local schema = V.record({
    name  = V.string():min(1),
    age   = V.number():int():min(0),
    email = V.string():email():optional(),
  })

  T.it("valid record passes", function()
    T.ok(schema:check({ name = "Alice", age = 30 }))
  end)
  T.it("valid record with optional email passes", function()
    T.ok(schema:check({ name = "Alice", age = 30, email = "a@b.com" }))
  end)
  T.it("missing required field fails", function()
    local ok, err = schema:check({ age = 30 })
    T.fail(ok)
    T.ok(#err.errors > 0)
    local found_name = false
    for _, e in ipairs(err.errors) do
      if e.path == "name" then found_name = true end
    end
    T.ok(found_name)
  end)
  T.it("wrong field type fails", function()
    local ok, err = schema:check({ name = "Alice", age = "old" })
    T.fail(ok)
    local found_age = false
    for _, e in ipairs(err.errors) do
      if e.path:find("age") then found_age = true end
    end
    T.ok(found_age)
  end)
  T.it("extra keys are ignored", function()
    T.ok(schema:check({ name = "Alice", age = 1, extra = "ignored" }))
  end)
  T.it("non-table fails", function()
    local ok, _ = schema:check("not a table")
    T.fail(ok)
  end)
  T.it("parse: returns parsed values", function()
    local v, err = V.record({ x = V.number():coerce() }):parse({ x = "7" })
    T.eq(err, nil)
    T.eq(v.x, 7)
  end)
end)

T.describe("V.map()", function()
  T.it("valid map passes", function()
    T.ok(V.map(V.string(), V.number()):check({ a = 1, b = 2 }))
  end)
  T.it("wrong value type fails", function()
    local ok, err = V.map(V.string(), V.number()):check({ a = "one" })
    T.fail(ok)
    T.ok(#err.errors > 0)
  end)
  T.it("wrong key type fails", function()
    -- Lua table keys can be numbers; check that number key fails string validation
    local ok, err = V.map(V.string(), V.number()):check({ [1] = 10 })
    T.fail(ok)
    T.ok(#err.errors > 0)
  end)
  T.it("empty map passes", function()
    T.ok(V.map(V.string(), V.number()):check({}))
  end)
  T.it("non-table fails", function()
    local ok, _ = V.map(V.string(), V.number()):check("x")
    T.fail(ok)
  end)
end)

T.describe("V.tuple()", function()
  T.it("valid tuple passes", function()
    T.ok(V.tuple(V.string(), V.number()):check({"hello", 42}))
  end)
  T.it("wrong element type fails", function()
    local ok, err = V.tuple(V.string(), V.number()):check({42, "hello"})
    T.fail(ok)
    T.ok(#err.errors > 0)
  end)
  T.it("wrong arity fails", function()
    local ok, err = V.tuple(V.string(), V.number()):check({"hello"})
    T.fail(ok)
    T.ok(err.errors[1].message:find("2 elements"))
  end)
  T.it("non-table fails", function()
    local ok, _ = V.tuple(V.string()):check("x")
    T.fail(ok)
  end)
  T.it("parse: coerces elements", function()
    local v, err = V.tuple(V.string():coerce(), V.number():coerce()):parse({42, "3"})
    T.eq(err, nil)
    T.eq(v[1], "42")
    T.eq(v[2], 3)
  end)
end)

T.describe("V.union()", function()
  local schema = V.union(V.string(), V.number())

  T.it("string matches", function()
    T.ok(schema:check("hello"))
  end)
  T.it("number matches", function()
    T.ok(schema:check(42))
  end)
  T.it("boolean fails", function()
    local ok, err = schema:check(true)
    T.fail(ok)
    T.ok(err)
  end)
  T.it("first match wins in parse", function()
    -- string coerce comes first — 42 will be valid number
    local v, err = V.union(V.number(), V.string()):parse(42)
    T.eq(err, nil)
    T.eq(v, 42)
  end)
end)

T.describe("V.intersection()", function()
  -- A record with name field AND a record with age field
  local schema = V.intersection(
    V.record({ name = V.string() }),
    V.record({ age  = V.number() })
  )

  T.it("satisfies both schemas passes", function()
    T.ok(schema:check({ name = "Alice", age = 30 }))
  end)
  T.it("missing a required field from one schema fails", function()
    local ok, err = schema:check({ name = "Alice" })
    T.fail(ok)
    T.ok(#err.errors > 0)
  end)
end)

T.describe("V.literal()", function()
  T.it("exact value passes", function()
    T.ok(V.literal("admin"):check("admin"))
    T.ok(V.literal(true):check(true))
    T.ok(V.literal(42):check(42))
  end)
  T.it("different value fails", function()
    local ok, err = V.literal("admin"):check("user")
    T.fail(ok)
    T.ok(err.errors[1].message:find("admin"))
  end)
end)

T.describe("V.enum()", function()
  local schema = V.enum({"red", "green", "blue"})

  T.it("member passes", function()
    T.ok(schema:check("red"))
    T.ok(schema:check("blue"))
  end)
  T.it("non-member fails", function()
    local ok, err = schema:check("purple")
    T.fail(ok)
    T.ok(err.errors[1].message:find("purple"))
  end)
end)

T.describe("V.not_()", function()
  T.it("passes when inner fails", function()
    T.ok(V.not_(V.string()):check(42))
  end)
  T.it("fails when inner passes", function()
    local ok, err = V.not_(V.string()):check("hello")
    T.fail(ok)
    T.ok(err.errors[1].message:find("must not"))
  end)
end)

T.describe("V.custom()", function()
  local even = V.custom(function(v)
    if type(v) ~= "number" then return "must be a number" end
    if v % 2 ~= 0 then return "must be even" end
  end)

  T.it("passes for even number", function()
    T.ok(even:check(4))
  end)
  T.it("fails for odd number with custom message", function()
    local ok, err = even:check(3)
    T.fail(ok)
    T.eq(err.errors[1].message, "must be even")
  end)
  T.it("fails for wrong type with custom message", function()
    local ok, err = even:check("x")
    T.fail(ok)
    T.eq(err.errors[1].message, "must be a number")
  end)
end)

T.describe("parse method", function()
  T.it("returns coerced value on success", function()
    local v, err = V.number():coerce():parse("42")
    T.eq(err, nil)
    T.eq(v, 42)
  end)
  T.it("returns nil + error on failure", function()
    local v, err = V.number():parse("abc")
    T.eq(v, nil)
    T.ok(err)
    T.ok(#err.errors > 0)
  end)
  T.it("check returns true on success", function()
    local ok = V.string():check("hello")
    T.eq(ok, true)
  end)
  T.it("check returns false + error on failure", function()
    local ok, err = V.string():check(123)
    T.eq(ok, false)
    T.ok(err)
  end)
end)

T.describe("nested error paths", function()
  T.it("record within record has dotted path", function()
    local schema = V.record({
      address = V.record({
        zip = V.string():pattern("^%d%d%d%d%d$", "must be 5 digits"),
      }),
    })
    local ok, err = schema:check({ address = { zip = "bad" } })
    T.fail(ok)
    local found = false
    for _, e in ipairs(err.errors) do
      if e.path == "address.zip" then found = true end
    end
    T.ok(found)
  end)
  T.it("array element has indexed path", function()
    local schema = V.record({
      tags = V.array(V.string()),
    })
    local ok, err = schema:check({ tags = {"ok", 99, "also ok"} })
    T.fail(ok)
    local found = false
    for _, e in ipairs(err.errors) do
      if e.path:find("tags") and e.path:find("%[2%]") then found = true end
    end
    T.ok(found)
  end)
end)

T.describe("format_errors", function()
  T.it("returns non-empty string for errors", function()
    local _, err = V.record({ name = V.string() }):check({ name = 42 })
    local s = V.format_errors(err)
    T.ok(type(s) == "string")
    T.ok(#s > 0)
    T.ok(s:find("name"))
  end)
  T.it("returns empty string for nil", function()
    T.eq(V.format_errors(nil), "")
  end)
end)

T.describe("type_name", function()
  T.it("returns correct type names", function()
    T.eq(V.string():type_name(), "string")
    T.eq(V.number():type_name(), "number")
    T.eq(V.integer():type_name(), "integer")
    T.eq(V.boolean():type_name(), "boolean")
    T.eq(V.nil_val():type_name(), "nil")
    T.eq(V.any():type_name(), "any")
    T.eq(V.array(V.string()):type_name(), "array")
    T.eq(V.record({}):type_name(), "record")
    T.eq(V.map(V.string(), V.number()):type_name(), "map")
    T.eq(V.tuple(V.string()):type_name(), "tuple")
    T.eq(V.union(V.string(), V.number()):type_name(), "union")
    T.eq(V.literal("x"):type_name(), "literal")
    T.eq(V.enum({"a"}):type_name(), "enum")
    T.eq(V.not_(V.string()):type_name(), "not")
    T.eq(V.custom(function() end):type_name(), "custom")
  end)
end)
