if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T  = require("lib.test.assert")
local ts = require("lib.time_series")

local function approx(a, b, eps)
  eps = eps or 1e-9
  return math.abs(a - b) <= eps
end

T.describe("time_series", function()

  T.describe("push / len / at exact lookup", function()
    T.it("stores and retrieves values", function()
      local s = ts.series()
      s:push(1000, 10.5)
      s:push(1010, 12.0)
      s:push(1020, 11.8)
      T.eq(s:len(), 3)
      T.eq(s:at(1000), 10.5)
      T.eq(s:at(1010), 12.0)
      T.eq(s:at(1020), 11.8)
      T.eq(s:at(1005), nil)  -- not exact
    end)
  end)

  T.describe("at with linear interpolation", function()
    T.it("interpolates between two points", function()
      local s = ts.series()
      s:push(1000, 10.0)
      s:push(1010, 20.0)
      -- midpoint should be 15
      local v = s:at(1005, "linear")
      T.ok(v ~= nil, "interpolated value should not be nil")
      T.ok(approx(v, 15.0, 1e-9), "expected 15.0, got " .. tostring(v))
    end)

    T.it("exact hit returns exact value", function()
      local s = ts.series()
      s:push(1000, 10.0)
      s:push(1010, 20.0)
      T.eq(s:at(1000, "linear"), 10.0)
    end)

    T.it("returns nil for out-of-range t", function()
      local s = ts.series()
      s:push(1000, 10.0)
      s:push(1010, 20.0)
      T.eq(s:at(500, "linear"),  nil)
      T.eq(s:at(2000, "linear"), nil)
    end)
  end)

  T.describe("range query", function()
    T.it("returns correct subset", function()
      local s = ts.series()
      s:push(1000, 1.0)
      s:push(1005, 2.0)
      s:push(1010, 3.0)
      s:push(1015, 4.0)
      s:push(1020, 5.0)
      local r = s:range(1005, 1015)
      T.eq(#r, 3)
      T.eq(r[1][1], 1005); T.eq(r[1][2], 2.0)
      T.eq(r[2][1], 1010); T.eq(r[2][2], 3.0)
      T.eq(r[3][1], 1015); T.eq(r[3][2], 4.0)
    end)

    T.it("returns empty for out-of-range window", function()
      local s = ts.series()
      s:push(1000, 1.0)
      local r = s:range(2000, 3000)
      T.eq(#r, 0)
    end)
  end)

  T.describe("stats", function()
    T.it("computes min/max/mean/stddev over window", function()
      local s = ts.series()
      s:push(1,  2.0)
      s:push(2,  4.0)
      s:push(3,  4.0)
      s:push(4,  4.0)
      s:push(5,  5.0)
      s:push(6,  5.0)
      s:push(7,  7.0)
      s:push(8,  9.0)
      -- mean = (2+4+4+4+5+5+7+9)/8 = 40/8 = 5
      local st = s:stats()
      T.eq(st.min,   2.0)
      T.eq(st.max,   9.0)
      T.eq(st.sum,   40.0)
      T.eq(st.count, 8)
      T.ok(approx(st.mean, 5.0, 1e-9), "mean")
      -- sample stddev ~ 2.0
      T.ok(st.stddev > 0, "stddev positive")
      T.eq(st.first, 2.0)
      T.eq(st.last,  9.0)
    end)

    T.it("respects time window", function()
      local s = ts.series()
      s:push(1, 10.0)
      s:push(2, 20.0)
      s:push(3, 30.0)
      local st = s:stats(1, 2)
      T.eq(st.count, 2)
      T.eq(st.min,   10.0)
      T.eq(st.max,   20.0)
      T.ok(approx(st.mean, 15.0, 1e-9))
    end)
  end)

  T.describe("resample", function()
    T.it("mean aggregation", function()
      local s = ts.series()
      s:push(0,  10.0)
      s:push(1,  20.0)
      s:push(5,  30.0)
      s:push(6,  40.0)
      -- interval=5: bucket 0 gets t=0,1 → mean=15; bucket 5 gets t=5,6 → mean=35
      local r = s:resample(5, "mean")
      T.eq(r:len(), 2)
      T.ok(approx(r:at(0), 15.0, 1e-9), "bucket 0 mean")
      T.ok(approx(r:at(5), 35.0, 1e-9), "bucket 5 mean")
    end)

    T.it("sum aggregation", function()
      local s = ts.series()
      s:push(0, 10.0)
      s:push(1, 20.0)
      s:push(5, 30.0)
      s:push(6, 40.0)
      local r = s:resample(5, "sum")
      T.eq(r:len(), 2)
      T.ok(approx(r:at(0), 30.0, 1e-9), "bucket 0 sum")
      T.ok(approx(r:at(5), 70.0, 1e-9), "bucket 5 sum")
    end)
  end)

  T.describe("rolling", function()
    T.it("3-point rolling mean", function()
      local s = ts.series()
      s:push(1, 1.0)
      s:push(2, 2.0)
      s:push(3, 3.0)
      s:push(4, 4.0)
      s:push(5, 5.0)
      local r = s:rolling(3, "mean")
      -- windows: [1,2,3]→2, [2,3,4]→3, [3,4,5]→4
      T.eq(r:len(), 3)
      T.ok(approx(r:at(3), 2.0, 1e-9), "window ending at t=3")
      T.ok(approx(r:at(4), 3.0, 1e-9), "window ending at t=4")
      T.ok(approx(r:at(5), 4.0, 1e-9), "window ending at t=5")
    end)
  end)

  T.describe("diff", function()
    T.it("first differences", function()
      local s = ts.series()
      s:push(1, 1.0)
      s:push(2, 3.0)
      s:push(3, 6.0)
      s:push(4, 10.0)
      local d = s:diff()
      T.eq(d:len(), 3)
      T.ok(approx(d:at(2), 2.0, 1e-9))
      T.ok(approx(d:at(3), 3.0, 1e-9))
      T.ok(approx(d:at(4), 4.0, 1e-9))
    end)
  end)

  T.describe("cumsum", function()
    T.it("running totals", function()
      local s = ts.series()
      s:push(1, 1.0)
      s:push(2, 2.0)
      s:push(3, 3.0)
      local c = s:cumsum()
      T.eq(c:len(), 3)
      T.ok(approx(c:at(1), 1.0, 1e-9))
      T.ok(approx(c:at(2), 3.0, 1e-9))
      T.ok(approx(c:at(3), 6.0, 1e-9))
    end)
  end)

  T.describe("apply", function()
    T.it("transforms all values", function()
      local s = ts.series()
      s:push(1, 1.0)
      s:push(2, 4.0)
      s:push(3, 9.0)
      local r = s:apply(math.sqrt)
      T.eq(r:len(), 3)
      T.ok(approx(r:at(1), 1.0, 1e-9))
      T.ok(approx(r:at(2), 2.0, 1e-9))
      T.ok(approx(r:at(3), 3.0, 1e-9))
    end)
  end)

  T.describe("normalize", function()
    T.it("maps to [0,1]", function()
      local s = ts.series()
      s:push(1, 0.0)
      s:push(2, 5.0)
      s:push(3, 10.0)
      local n = s:normalize()
      T.eq(n:len(), 3)
      T.ok(approx(n:at(1), 0.0, 1e-9))
      T.ok(approx(n:at(2), 0.5, 1e-9))
      T.ok(approx(n:at(3), 1.0, 1e-9))
    end)
  end)

  T.describe("outliers (zscore)", function()
    T.it("detects obvious spike", function()
      local s = ts.series()
      -- clustered around 10 with a huge spike
      for i = 1, 10 do s:push(i, 10.0) end
      s:push(11, 10.0)
      s:push(12, 1000.0)  -- obvious outlier
      local out = s:outliers({ method = "zscore", threshold = 2.5 })
      T.ok(#out >= 1, "should detect at least one outlier")
      local found = false
      for _, o in ipairs(out) do
        if o[1] == 12 then found = true end
      end
      T.ok(found, "spike at t=12 should be flagged")
    end)
  end)

  T.describe("merge", function()
    T.it("combines two series by function", function()
      local s1 = ts.series()
      s1:push(1, 10.0); s1:push(2, 20.0); s1:push(3, 30.0)
      local s2 = ts.series()
      s2:push(1, 1.0); s2:push(2, 2.0); s2:push(3, 3.0)
      local m = ts.merge(s1, s2, function(a, b) return a + b end)
      T.eq(m:len(), 3)
      T.ok(approx(m:at(1), 11.0, 1e-9))
      T.ok(approx(m:at(2), 22.0, 1e-9))
      T.ok(approx(m:at(3), 33.0, 1e-9))
    end)

    T.it("only includes common timestamps", function()
      local s1 = ts.series()
      s1:push(1, 10.0); s1:push(2, 20.0)
      local s2 = ts.series()
      s2:push(2, 5.0); s2:push(3, 6.0)
      local m = ts.merge(s1, s2, function(a, b) return a * b end)
      T.eq(m:len(), 1)
      T.ok(approx(m:at(2), 100.0, 1e-9))
    end)
  end)

  T.describe("align", function()
    T.it("fills gaps with linear interpolation", function()
      local s1 = ts.series()
      s1:push(0, 0.0); s1:push(10, 10.0)
      local s2 = ts.series()
      s2:push(0, 100.0); s2:push(5, 50.0); s2:push(10, 0.0)
      local aligned = ts.align(s1, s2, { method = "linear" })
      local a1 = aligned[1]
      local a2 = aligned[2]
      -- union timestamps: 0, 5, 10
      T.eq(a1:len(), 3)
      T.eq(a2:len(), 3)
      -- s1 at t=5 interpolated = 5.0
      T.ok(approx(a1:at(5), 5.0, 1e-9), "s1 interpolated at t=5")
      -- s2 at t=5 is exact = 50.0
      T.ok(approx(a2:at(5), 50.0, 1e-9), "s2 at t=5")
    end)
  end)

  T.describe("monotonicity enforcement", function()
    T.it("push out-of-order returns error", function()
      local s = ts.series()
      s:push(100, 1.0)
      s:push(200, 2.0)
      local ok, err = s:push(150, 3.0)
      T.eq(ok, nil)
      T.ok(err ~= nil, "error message should be non-nil")
      T.ok(type(err) == "string", "error should be a string")
      -- series unchanged
      T.eq(s:len(), 2)
    end)

    T.it("duplicate timestamp is allowed", function()
      local s = ts.series()
      s:push(100, 1.0)
      local ok, err = s:push(100, 2.0)
      T.ok(ok == true, "duplicate t should succeed")
      T.eq(err, nil)
    end)
  end)

  T.describe("downsample", function()
    T.it("reduces point count", function()
      local s = ts.series()
      for i = 1, 200 do
        s:push(i, math.sin(i * 0.1))
      end
      local d = s:downsample(50)
      T.ok(d:len() <= 50, "downsampled length should be <= 50, got " .. d:len())
      T.ok(d:len() >= 2, "should retain at least 2 points")
    end)

    T.it("preserves first and last points", function()
      local s = ts.series()
      for i = 1, 100 do s:push(i, i * 1.0) end
      local d = s:downsample(20)
      T.eq(d:at(1),   1.0)
      T.eq(d:at(100), 100.0)
    end)

    T.it("passthrough when count <= max_points", function()
      local s = ts.series()
      s:push(1, 1.0); s:push(2, 2.0)
      local d = s:downsample(100)
      T.eq(d:len(), 2)
    end)
  end)

end)
