-- lib/ecs/ecs_test.lua

if not package.path:find("?/init.lua", 1, true) then
	package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local sqlite = require("lib.sqlite")
local ecs = require("lib.ecs")

local function new_store()
	local db, err = sqlite.open(":memory:")
	assert(db, "sqlite open failed: " .. tostring(err))
	local store, serr = ecs.new(db)
	assert(store, "ecs.new failed: " .. tostring(serr))
	return store, db
end

T.describe("ecs.create", function()
	T.it("returns incrementing integer IDs", function()
		local store = new_store()
		local id1 = store:create()
		local id2 = store:create()
		T.ok(type(id1) == "number", "id1 is a number")
		T.ok(type(id2) == "number", "id2 is a number")
		T.ok(id2 > id1, "id2 > id1")
	end)
end)

T.describe("ecs.destroy", function()
	T.it("removes the entity", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "hp", 100)
		store:destroy(id)
		-- after destroy, get should return nil (no entity row, cascade removes components)
		local val = store:get(id, "hp")
		T.eq(val, nil)
	end)

	T.it("removes all components via cascade", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "name", "Alice")
		store:set(id, "hp", 50)
		store:destroy(id)
		local comps, err = store:components(id)
		T.ok(comps ~= nil, "components after destroy: " .. tostring(err))
		T.eq(next(comps), nil) -- empty table
	end)
end)

T.describe("ecs.set / ecs.get", function()
	T.it("stores and retrieves a string component", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "name", "Alice")
		local val = store:get(id, "name")
		T.eq(val, "Alice")
	end)

	T.it("stores and retrieves a number component", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "hp", 100)
		local val = store:get(id, "hp")
		T.eq(val, 100)
	end)

	T.it("stores and retrieves a boolean component", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "alive", true)
		local val = store:get(id, "alive")
		T.eq(val, true)
	end)

	T.it("stores and retrieves a table component", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "pos", { x = 1, y = 2 })
		local val = store:get(id, "pos")
		T.eq(val.x, 1)
		T.eq(val.y, 2)
	end)

	T.it("overwrites existing component on set", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "hp", 100)
		store:set(id, "hp", 50)
		local val = store:get(id, "hp")
		T.eq(val, 50)
	end)

	T.it("returns nil for missing component", function()
		local store = new_store()
		local id = store:create()
		local val = store:get(id, "missing")
		T.eq(val, nil)
	end)
end)

T.describe("ecs.remove", function()
	T.it("removes a specific component", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "hp", 100)
		store:set(id, "name", "Bob")
		store:remove(id, "hp")
		local hp = store:get(id, "hp")
		T.eq(hp, nil)
		local name = store:get(id, "name")
		T.eq(name, "Bob")
	end)

	T.it("is a no-op when component doesn't exist", function()
		local store = new_store()
		local id = store:create()
		local ok, err = store:remove(id, "nonexistent")
		T.ok(ok, "remove nonexistent: " .. tostring(err))
	end)
end)

T.describe("ecs.query", function()
	T.it("returns all entities with a component", function()
		local store = new_store()
		local id1 = store:create()
		local id2 = store:create()
		local id3 = store:create()
		store:set(id1, "hp", 100)
		store:set(id2, "hp", 0)
		store:set(id3, "name", "Carol") -- no hp
		local results, err = store:query("hp")
		T.ok(results ~= nil, "query error: " .. tostring(err))
		T.eq(#results, 2)
	end)

	T.it("returns id and data fields", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "hp", 42)
		local results = store:query("hp")
		T.eq(#results, 1)
		T.eq(results[1].id, id)
		T.eq(results[1].data, 42)
	end)

	T.it("filters with predicate", function()
		local store = new_store()
		local id1 = store:create()
		local id2 = store:create()
		local id3 = store:create()
		store:set(id1, "hp", 100)
		store:set(id2, "hp", 0)
		store:set(id3, "hp", 50)
		local alive, err = store:query("hp", function(hp) return hp > 0 end)
		T.ok(alive ~= nil, "query predicate error: " .. tostring(err))
		T.eq(#alive, 2)
	end)

	T.it("returns empty array when no entities have component", function()
		local store = new_store()
		store:create()
		local results = store:query("nonexistent")
		T.eq(#results, 0)
	end)
end)

T.describe("ecs.components", function()
	T.it("returns all components on an entity as a map", function()
		local store = new_store()
		local id = store:create()
		store:set(id, "name", "Dave")
		store:set(id, "hp", 75)
		store:set(id, "alive", true)
		local comps, err = store:components(id)
		T.ok(comps ~= nil, "components error: " .. tostring(err))
		T.eq(comps.name, "Dave")
		T.eq(comps.hp, 75)
		T.eq(comps.alive, true)
	end)

	T.it("returns empty table for entity with no components", function()
		local store = new_store()
		local id = store:create()
		local comps = store:components(id)
		T.eq(next(comps), nil)
	end)

	T.it("does not include components from other entities", function()
		local store = new_store()
		local id1 = store:create()
		local id2 = store:create()
		store:set(id1, "name", "Eve")
		store:set(id2, "name", "Frank")
		local comps = store:components(id1)
		T.eq(comps.name, "Eve")
	end)
end)
