if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local SVG = require("lib.svg")

-- ---------------------------------------------------------------------------
T.describe("SVG._tier", function()
  T.it("is pure", function()
    T.eq(SVG._tier, "pure")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("SVG.new / to_string basics", function()
  T.it("produces <svg> and </svg>", function()
    local doc = SVG.new(100, 100)
    local s = doc:to_string()
    T.ok(s:find("<svg", 1, true) ~= nil, "has <svg")
    T.ok(s:find("</svg>", 1, true) ~= nil, "has </svg>")
  end)

  T.it("includes width and height attributes", function()
    local doc = SVG.new(200, 150)
    local s = doc:to_string()
    T.ok(s:find('width="200"', 1, true) ~= nil, "width attr")
    T.ok(s:find('height="150"', 1, true) ~= nil, "height attr")
  end)

  T.it("includes xmlns by default", function()
    local doc = SVG.new(100, 100)
    local s = doc:to_string()
    T.ok(s:find("http://www.w3.org/2000/svg", 1, true) ~= nil, "xmlns present")
  end)

  T.it("omits xmlns when opts.xmlns=false", function()
    local doc = SVG.new(100, 100, {xmlns = false})
    local s = doc:to_string()
    T.ok(s:find("http://www.w3.org/2000/svg", 1, true) == nil, "xmlns absent")
  end)

  T.it("includes viewBox when provided", function()
    local doc = SVG.new(100, 100, {viewBox = "0 0 100 100"})
    local s = doc:to_string()
    T.ok(s:find('viewBox="0 0 100 100"', 1, true) ~= nil, "viewBox attr")
  end)

  T.it("includes XML declaration", function()
    local doc = SVG.new(10, 10)
    local s = doc:to_string()
    T.ok(s:find("<?xml", 1, true) ~= nil, "xml decl")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("rect", function()
  T.it("produces <rect/> with x, y, width, height", function()
    local doc = SVG.new(100, 100)
    doc:rect(10, 20, 50, 30)
    local s = doc:to_string()
    T.ok(s:find("<rect", 1, true) ~= nil, "<rect tag")
    T.ok(s:find('x="10"', 1, true) ~= nil, "x attr")
    T.ok(s:find('y="20"', 1, true) ~= nil, "y attr")
    T.ok(s:find('width="50"', 1, true) ~= nil, "width attr")
    T.ok(s:find('height="30"', 1, true) ~= nil, "height attr")
  end)

  T.it("passes fill and stroke attrs", function()
    local doc = SVG.new(100, 100)
    doc:rect(0, 0, 10, 10, {fill = "red", stroke = "blue"})
    local s = doc:to_string()
    T.ok(s:find('fill="red"', 1, true) ~= nil, "fill attr")
    T.ok(s:find('stroke="blue"', 1, true) ~= nil, "stroke attr")
  end)

  T.it("converts stroke_width underscore to hyphen", function()
    local doc = SVG.new(100, 100)
    doc:rect(0, 0, 10, 10, {stroke_width = "2"})
    local s = doc:to_string()
    T.ok(s:find('stroke-width="2"', 1, true) ~= nil, "stroke-width hyphen")
    T.ok(s:find("stroke_width", 1, true) == nil, "no underscored key in output")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("circle", function()
  T.it("produces <circle/> with cx, cy, r", function()
    local doc = SVG.new(100, 100)
    doc:circle(50, 50, 25)
    local s = doc:to_string()
    T.ok(s:find("<circle", 1, true) ~= nil, "<circle tag")
    T.ok(s:find('cx="50"', 1, true) ~= nil, "cx attr")
    T.ok(s:find('cy="50"', 1, true) ~= nil, "cy attr")
    T.ok(s:find('r="25"', 1, true) ~= nil, "r attr")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("ellipse", function()
  T.it("produces <ellipse/> with cx, cy, rx, ry", function()
    local doc = SVG.new(100, 100)
    doc:ellipse(50, 50, 30, 20, {fill = "green"})
    local s = doc:to_string()
    T.ok(s:find("<ellipse", 1, true) ~= nil, "<ellipse tag")
    T.ok(s:find('cx="50"', 1, true) ~= nil, "cx")
    T.ok(s:find('cy="50"', 1, true) ~= nil, "cy")
    T.ok(s:find('rx="30"', 1, true) ~= nil, "rx")
    T.ok(s:find('ry="20"', 1, true) ~= nil, "ry")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("line", function()
  T.it("produces <line/> with x1, y1, x2, y2", function()
    local doc = SVG.new(100, 100)
    doc:line(0, 0, 100, 100)
    local s = doc:to_string()
    T.ok(s:find("<line", 1, true) ~= nil, "<line tag")
    T.ok(s:find('x1="0"', 1, true) ~= nil, "x1")
    T.ok(s:find('y1="0"', 1, true) ~= nil, "y1")
    T.ok(s:find('x2="100"', 1, true) ~= nil, "x2")
    T.ok(s:find('y2="100"', 1, true) ~= nil, "y2")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("polyline", function()
  T.it("formats points array correctly", function()
    local doc = SVG.new(100, 100)
    doc:polyline({{0,0},{50,50},{100,0}})
    local s = doc:to_string()
    T.ok(s:find("<polyline", 1, true) ~= nil, "<polyline tag")
    T.ok(s:find('points="0,0 50,50 100,0"', 1, true) ~= nil, "points attr")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("polygon", function()
  T.it("formats points array correctly", function()
    local doc = SVG.new(100, 100)
    doc:polygon({{0,0},{50,100},{100,0}})
    local s = doc:to_string()
    T.ok(s:find("<polygon", 1, true) ~= nil, "<polygon tag")
    T.ok(s:find('points="0,0 50,100 100,0"', 1, true) ~= nil, "points attr")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("path", function()
  T.it("produces <path/> with d attribute", function()
    local doc = SVG.new(100, 100)
    doc:path("M 0 0 L 50 50 Z")
    local s = doc:to_string()
    T.ok(s:find("<path", 1, true) ~= nil, "<path tag")
    T.ok(s:find('d="M 0 0 L 50 50 Z"', 1, true) ~= nil, "d attr")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("Path builder", function()
  T.it("M produces moveto", function()
    local p = SVG.path()
    p:M(10, 20)
    T.eq(p:to_string(), "M 10 20")
  end)

  T.it("L produces lineto", function()
    local p = SVG.path()
    p:L(5, 10)
    T.eq(p:to_string(), "L 5 10")
  end)

  T.it("Z produces closepath", function()
    local p = SVG.path()
    p:Z()
    T.eq(p:to_string(), "Z")
  end)

  T.it("chained M L Z", function()
    local p = SVG.path()
    p:M(0, 0):L(100, 0):L(100, 100):Z()
    T.eq(p:to_string(), "M 0 0 L 100 0 L 100 100 Z")
  end)

  T.it("C cubic bezier", function()
    local p = SVG.path()
    p:C(10, 20, 30, 40, 50, 60)
    T.eq(p:to_string(), "C 10 20 30 40 50 60")
  end)

  T.it("Q quadratic bezier", function()
    local p = SVG.path()
    p:Q(10, 20, 50, 60)
    T.eq(p:to_string(), "Q 10 20 50 60")
  end)

  T.it("S smooth cubic bezier", function()
    local p = SVG.path()
    p:S(30, 40, 50, 60)
    T.eq(p:to_string(), "S 30 40 50 60")
  end)

  T.it("A arc", function()
    local p = SVG.path()
    p:A(10, 20, 0, 1, 0, 50, 60)
    T.eq(p:to_string(), "A 10 20 0 1 0 50 60")
  end)

  T.it("H horizontal lineto", function()
    local p = SVG.path()
    p:H(42)
    T.eq(p:to_string(), "H 42")
  end)

  T.it("V vertical lineto", function()
    local p = SVG.path()
    p:V(99)
    T.eq(p:to_string(), "V 99")
  end)

  T.it("add_path embeds d string", function()
    local doc = SVG.new(100, 100)
    local p = SVG.path()
    p:M(0, 0):L(50, 50):Z()
    doc:add_path(p, {stroke = "black"})
    local s = doc:to_string()
    T.ok(s:find('d="M 0 0 L 50 50 Z"', 1, true) ~= nil, "add_path d attr")
    T.ok(s:find('stroke="black"', 1, true) ~= nil, "add_path extra attr")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("text", function()
  T.it("produces <text> with content", function()
    local doc = SVG.new(100, 100)
    doc:text(10, 20, "Hello")
    local s = doc:to_string()
    T.ok(s:find("<text", 1, true) ~= nil, "<text tag")
    T.ok(s:find("Hello", 1, true) ~= nil, "content")
    T.ok(s:find('x="10"', 1, true) ~= nil, "x attr")
    T.ok(s:find('y="20"', 1, true) ~= nil, "y attr")
  end)

  T.it("escapes < in text content", function()
    local doc = SVG.new(100, 100)
    doc:text(0, 0, "a < b")
    local s = doc:to_string()
    T.ok(s:find("a &lt; b", 1, true) ~= nil, "< escaped")
    T.ok(s:find("a < b", 1, true) == nil, "raw < absent")
  end)

  T.it("escapes & in text content", function()
    local doc = SVG.new(100, 100)
    doc:text(0, 0, "A & B")
    local s = doc:to_string()
    T.ok(s:find("A &amp; B", 1, true) ~= nil, "& escaped")
  end)

  T.it("escapes > in text content", function()
    local doc = SVG.new(100, 100)
    doc:text(0, 0, "a > b")
    local s = doc:to_string()
    T.ok(s:find("a &gt; b", 1, true) ~= nil, "> escaped")
  end)

  T.it("tspan produces <tspan>", function()
    local doc = SVG.new(100, 100)
    doc:tspan(5, 15, "span text")
    local s = doc:to_string()
    T.ok(s:find("<tspan", 1, true) ~= nil, "<tspan tag")
    T.ok(s:find("span text", 1, true) ~= nil, "tspan content")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("group", function()
  T.it("wraps children in <g>", function()
    local doc = SVG.new(100, 100)
    local g = doc:group({fill = "blue"})
    g:rect(0, 0, 10, 10)
    g:circle(5, 5, 3)
    local s = doc:to_string()
    T.ok(s:find("<g", 1, true) ~= nil, "<g tag")
    T.ok(s:find("</g>", 1, true) ~= nil, "</g> close")
    T.ok(s:find('fill="blue"', 1, true) ~= nil, "fill attr on group")
    T.ok(s:find("<rect", 1, true) ~= nil, "rect inside group")
    T.ok(s:find("<circle", 1, true) ~= nil, "circle inside group")
  end)

  T.it("callback form (group with fn) works", function()
    local doc = SVG.new(100, 100)
    doc:group({transform = "translate(10,10)"}, function(g)
      g:rect(0, 0, 5, 5)
    end)
    local s = doc:to_string()
    T.ok(s:find("<g", 1, true) ~= nil, "<g present")
    T.ok(s:find("<rect", 1, true) ~= nil, "rect inside")
    T.ok(s:find('transform="translate(10,10)"', 1, true) ~= nil, "transform attr")
  end)

  T.it("nested groups", function()
    local doc = SVG.new(100, 100)
    local g = doc:group()
    local inner = g:group({id = "inner"})
    inner:line(0, 0, 10, 10)
    local s = doc:to_string()
    T.ok(s:find('id="inner"', 1, true) ~= nil, "inner group id")
    T.ok(s:find("<line", 1, true) ~= nil, "line inside inner group")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("transform helpers", function()
  T.it("translate(x,y)", function()
    T.eq(SVG.translate(10, 20), "translate(10,20)")
  end)

  T.it("translate(x) single arg", function()
    T.eq(SVG.translate(5), "translate(5)")
  end)

  T.it("scale(sx,sy)", function()
    T.eq(SVG.scale(2, 3), "scale(2,3)")
  end)

  T.it("scale(s) single arg", function()
    T.eq(SVG.scale(0.5), "scale(0.5)")
  end)

  T.it("rotate(angle)", function()
    T.eq(SVG.rotate(45), "rotate(45)")
  end)

  T.it("rotate(angle,cx,cy)", function()
    T.eq(SVG.rotate(90, 50, 50), "rotate(90,50,50)")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("defs / linear_gradient", function()
  T.it("produces <defs> and <linearGradient>", function()
    local doc = SVG.new(100, 100)
    local defs = doc:defs()
    defs:linear_gradient("grad1", {
      x1 = 0, y1 = 0, x2 = 1, y2 = 0,
      stops = {
        {offset = 0, color = "#ff0000"},
        {offset = 1, color = "#0000ff"},
      }
    })
    local s = doc:to_string()
    T.ok(s:find("<defs", 1, true) ~= nil, "<defs tag")
    T.ok(s:find("<linearGradient", 1, true) ~= nil, "<linearGradient tag")
    T.ok(s:find('id="grad1"', 1, true) ~= nil, "gradient id")
    T.ok(s:find("<stop", 1, true) ~= nil, "<stop element")
    T.ok(s:find("#ff0000", 1, true) ~= nil, "first stop color")
    T.ok(s:find("#0000ff", 1, true) ~= nil, "second stop color")
    T.ok(s:find('offset="0"', 1, true) ~= nil, "offset 0")
    T.ok(s:find('offset="1"', 1, true) ~= nil, "offset 1")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("defs / radial_gradient", function()
  T.it("produces <radialGradient>", function()
    local doc = SVG.new(100, 100)
    local defs = doc:defs()
    defs:radial_gradient("rgrad1", {
      cx = 0.5, cy = 0.5, r = 0.5,
      stops = {
        {offset = 0, color = "white"},
        {offset = 1, color = "black"},
      }
    })
    local s = doc:to_string()
    T.ok(s:find("<radialGradient", 1, true) ~= nil, "<radialGradient tag")
    T.ok(s:find('id="rgrad1"', 1, true) ~= nil, "radial gradient id")
    T.ok(s:find('cx="0.5"', 1, true) ~= nil, "cx attr")
    T.ok(s:find('r="0.5"', 1, true) ~= nil, "r attr")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("defs / pattern", function()
  T.it("produces <pattern> with children", function()
    local doc = SVG.new(100, 100)
    local defs = doc:defs()
    defs:pattern("pat1", {width = 10, height = 10}, function(p)
      p:rect(0, 0, 5, 5, {fill = "red"})
    end)
    local s = doc:to_string()
    T.ok(s:find("<pattern", 1, true) ~= nil, "<pattern tag")
    T.ok(s:find('id="pat1"', 1, true) ~= nil, "pattern id")
    T.ok(s:find('width="10"', 1, true) ~= nil, "pattern width")
    T.ok(s:find('fill="red"', 1, true) ~= nil, "fill inside pattern")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("defs / marker", function()
  T.it("produces <marker> with children", function()
    local doc = SVG.new(100, 100)
    local defs = doc:defs()
    defs:marker("arrow", {refX = 10, refY = 5, markerWidth = 6, markerHeight = 6}, function(m)
      m:path("M 0 0 L 10 5 L 0 10 z", {fill = "black"})
    end)
    local s = doc:to_string()
    T.ok(s:find("<marker", 1, true) ~= nil, "<marker tag")
    T.ok(s:find('id="arrow"', 1, true) ~= nil, "marker id")
    T.ok(s:find('refX="10"', 1, true) ~= nil, "refX")
    T.ok(s:find("<path", 1, true) ~= nil, "path inside marker")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("to_file", function()
  T.it("writes SVG to a file", function()
    local doc = SVG.new(100, 100)
    doc:rect(0, 0, 50, 50, {fill = "green"})
    local tmp = os.tmpname()
    local ok, err = doc:to_file(tmp)
    T.ok(ok == true, "to_file returns true: " .. tostring(err))
    local f = io.open(tmp, "r")
    T.ok(f ~= nil, "file exists")
    local contents = f:read("*a")
    f:close()
    os.remove(tmp)
    T.ok(contents:find("<svg", 1, true) ~= nil, "file has <svg")
    T.ok(contents:find('fill="green"', 1, true) ~= nil, "file has fill attr")
  end)

  T.it("returns nil, errmsg on bad path", function()
    local doc = SVG.new(10, 10)
    local ok, err = doc:to_file("/nonexistent_dir/bad.svg")
    T.ok(ok == nil, "nil on failure")
    T.ok(err ~= nil, "error message returned")
  end)
end)

-- ---------------------------------------------------------------------------
T.describe("attribute escaping", function()
  T.it("escapes & in attribute values", function()
    local doc = SVG.new(100, 100)
    doc:rect(0, 0, 10, 10, {fill = "url(#a&b)"})
    local s = doc:to_string()
    T.ok(s:find("url(#a&amp;b)", 1, true) ~= nil, "& escaped in attr")
  end)

  T.it("escapes \" in attribute values", function()
    local doc = SVG.new(100, 100)
    doc:rect(0, 0, 10, 10, {title = 'say "hi"'})
    local s = doc:to_string()
    T.ok(s:find("&quot;", 1, true) ~= nil, "quote escaped in attr")
  end)
end)
