-- lib/exec/ident_test.lua
-- Tests for lib/exec/ident.lua

if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T     = require("lib.test.assert")
local arb   = require("lib.test.arb")
local ident = require("lib.exec.ident")

-- ── is_valid_ident ─────────────────────────────────────────────────────────────

T.describe("ident.is_valid_ident", function()
	T.it("accepts simple lowercase", function()
		T.ok(ident.is_valid_ident("foo"))
	end)
	T.it("accepts leading underscore", function()
		T.ok(ident.is_valid_ident("_foo"))
	end)
	T.it("accepts double underscore prefix", function()
		T.ok(ident.is_valid_ident("__foo"))
	end)
	T.it("accepts mixed alphanumeric", function()
		T.ok(ident.is_valid_ident("foo_bar2"))
	end)
	T.it("rejects empty string", function()
		T.ok(not ident.is_valid_ident(""))
	end)
	T.it("rejects digit-start", function()
		T.ok(not ident.is_valid_ident("2fa"))
	end)
	T.it("rejects reserved word 'end'", function()
		T.ok(not ident.is_valid_ident("end"))
	end)
	T.it("rejects reserved word 'for'", function()
		T.ok(not ident.is_valid_ident("for"))
	end)
	T.it("rejects hyphen", function()
		T.ok(not ident.is_valid_ident("foo-bar"))
	end)
	T.it("rejects reserved word 'nil'", function()
		T.ok(not ident.is_valid_ident("nil"))
	end)
end)

-- ── normalize_one ──────────────────────────────────────────────────────────────

T.describe("ident.normalize_one", function()
	T.it("strips -- prefix", function()
		T.eq(ident.normalize_one("--foo", 1), "foo")
	end)
	T.it("strips - prefix", function()
		T.eq(ident.normalize_one("-f", 1), "f")
	end)
	T.it("converts hyphens to underscore", function()
		T.eq(ident.normalize_one("--foo-bar", 1), "foo_bar")
	end)
	T.it("escapes underscores in original", function()
		T.eq(ident.normalize_one("--foo_bar", 1), "foo__bar")
	end)
	T.it("handles dot as symbol run", function()
		T.eq(ident.normalize_one("--log.level", 1), "log_level")
	end)
	T.it("handles slash as symbol run", function()
		T.eq(ident.normalize_one("--http/proxy", 1), "http_proxy")
	end)
	T.it("collapses mixed symbols into one underscore", function()
		T.eq(ident.normalize_one("--foo.-bar", 1), "foo_bar")
	end)
	T.it("prefixes _ for digit-start", function()
		T.eq(ident.normalize_one("--2fa", 1), "_2fa")
	end)
	T.it("appends _ for reserved word 'end'", function()
		T.eq(ident.normalize_one("--end", 1), "end_")
	end)
	T.it("appends _ for reserved word 'for'", function()
		T.eq(ident.normalize_one("--for", 1), "for_")
	end)
	T.it("returns _N for empty result (all symbols)", function()
		T.eq(ident.normalize_one("--...", 3), "_3")
	end)
	T.it("lowercases result", function()
		T.eq(ident.normalize_one("--FooBar", 1), "foobar")
	end)
	T.it("no prefix strip → no collision between --foo-bar and --foo_bar", function()
		local a = ident.normalize_one("--foo-bar", 1)
		local b = ident.normalize_one("--foo_bar", 2)
		T.eq(a, "foo_bar")
		T.eq(b, "foo__bar")
		T.ok(a ~= b)
	end)
end)

-- ── normalize (list) ───────────────────────────────────────────────────────────

T.describe("ident.normalize: basic mapping", function()
	T.it("--foo-bar → foo_bar", function()
		local r = ident.normalize({ "--foo-bar" })
		T.eq(r["--foo-bar"], "foo_bar")
	end)
	T.it("underscore escaping: --foo_bar → foo__bar", function()
		local r = ident.normalize({ "--foo_bar" })
		T.eq(r["--foo_bar"], "foo__bar")
	end)
	T.it("both --foo-bar and --foo_bar in same list: no collision", function()
		local r = ident.normalize({ "--foo-bar", "--foo_bar" })
		T.eq(r["--foo-bar"], "foo_bar")
		T.eq(r["--foo_bar"], "foo__bar")
	end)
	T.it("symbol runs: --log.level → log_level", function()
		local r = ident.normalize({ "--log.level" })
		T.eq(r["--log.level"], "log_level")
	end)
	T.it("symbol runs: --http/proxy → http_proxy", function()
		local r = ident.normalize({ "--http/proxy" })
		T.eq(r["--http/proxy"], "http_proxy")
	end)
	T.it("mixed symbols: --foo.-bar → foo_bar", function()
		local r = ident.normalize({ "--foo.-bar" })
		T.eq(r["--foo.-bar"], "foo_bar")
	end)
	T.it("digit start: --2fa → _2fa", function()
		local r = ident.normalize({ "--2fa" })
		T.eq(r["--2fa"], "_2fa")
	end)
	T.it("reserved word: --end → end_", function()
		local r = ident.normalize({ "--end" })
		T.eq(r["--end"], "end_")
	end)
	T.it("reserved word: --for → for_", function()
		local r = ident.normalize({ "--for" })
		T.eq(r["--for"], "for_")
	end)
	T.it("pathological all-symbols → _1", function()
		local r = ident.normalize({ "---" })
		-- After stripping --, remainder is "-". Non-alnum run → "_". Then strip synthetic _ → "". Fallback → _1.
		T.eq(r["---"], "_1")
	end)
end)

T.describe("ident.normalize: deduplication", function()
	T.it("duplicate raw name appears once in output", function()
		local r = ident.normalize({ "--foo", "--foo" })
		local count = 0
		for _ in pairs(r) do count = count + 1 end
		T.eq(count, 1)
		T.eq(r["--foo"], "foo")
	end)
	T.it("index used for fallback based on first occurrence position", function()
		-- "---" at position 2 should give _2
		local r = ident.normalize({ "--foo", "---" })
		T.eq(r["---"], "_2")
	end)
end)

T.describe("ident.normalize: collision resolution", function()
	T.it("two names normalizing to same get distinct identifiers", function()
		-- --foo-bar and --foo.bar both normalize to foo_bar
		local r = ident.normalize({ "--foo-bar", "--foo.bar" })
		local a = r["--foo-bar"]
		local b = r["--foo.bar"]
		T.ok(a ~= nil)
		T.ok(b ~= nil)
		T.ok(a ~= b, "collision: " .. tostring(a) .. " == " .. tostring(b))
	end)
	T.it("first alphabetically keeps base identifier", function()
		local r = ident.normalize({ "--foo-bar", "--foo.bar" })
		-- "--foo-bar" < "--foo.bar" alphabetically
		T.eq(r["--foo-bar"], "foo_bar")
		T.eq(r["--foo.bar"], "foo_bar_2")
	end)
	T.it("three-way collision: _2 and _3 suffixes", function()
		-- --foo-bar, --foo.bar, --foo/bar all → foo_bar
		local r = ident.normalize({ "--foo-bar", "--foo.bar", "--foo/bar" })
		local vals = { r["--foo-bar"], r["--foo.bar"], r["--foo/bar"] }
		table.sort(vals)
		T.eq(vals[1], "foo_bar")
		T.eq(vals[2], "foo_bar_2")
		T.eq(vals[3], "foo_bar_3")
	end)
	T.it("--no-foo and --no_foo: no_foo vs no__foo (no collision)", function()
		local r = ident.normalize({ "--no-foo", "--no_foo" })
		T.eq(r["--no-foo"], "no_foo")
		T.eq(r["--no_foo"], "no__foo")
	end)
end)

-- ── property test ──────────────────────────────────────────────────────────────

T.describe("ident.normalize: property — all outputs valid and distinct", function()
	-- Generator: list of 1–8 printable ASCII strings of length 1–12
	local name_arb = arb.string({ min = 1, max = 12, charset = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~" })
	local list_arb = arb.array(name_arb, { min = 1, max = 8 })

	arb.it("all output identifiers are valid Lua identifiers", list_arb, function(names)
		local r = ident.normalize(names)
		for _, v in pairs(r) do
			T.ok(ident.is_valid_ident(v), "not valid ident: " .. tostring(v))
		end
	end)

	arb.it("all output identifiers are distinct", list_arb, function(names)
		local r = ident.normalize(names)
		local seen = {}
		for _, v in pairs(r) do
			T.ok(not seen[v], "duplicate ident: " .. tostring(v))
			seen[v] = true
		end
	end)
end)
