if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local bignum = require("lib.bignum")

-- ── Construction from string ──────────────────────────────────────────────────

T.describe("bignum.new from string", function()
  T.it("integer string", function()
    T.eq(bignum.new("42"):to_string(), "42")
  end)
  T.it("negative integer string", function()
    T.eq(bignum.new("-7"):to_string(), "-7")
  end)
  T.it("decimal string", function()
    T.eq(bignum.new("3.14"):to_string(), "3.14")
  end)
  T.it("negative decimal", function()
    T.eq(bignum.new("-0.001"):to_string(), "-0.001")
  end)
  T.it("leading zeros stripped in integer part", function()
    T.eq(bignum.new("007"):to_string(), "7")
  end)
  T.it("trailing zeros stripped in fractional part", function()
    T.eq(bignum.new("1.50000"):to_string(), "1.5")
  end)
  T.it("zero", function()
    T.eq(bignum.new("0"):to_string(), "0")
  end)
  T.it("negative zero normalizes to zero", function()
    T.eq(bignum.new("-0"):to_string(), "0")
    T.eq(bignum.new("-0"):sign(), 0)
  end)
  T.it("scientific notation positive exponent", function()
    T.eq(bignum.new("1e10"):to_string(), "10000000000")
  end)
  T.it("scientific notation negative exponent", function()
    T.eq(bignum.new("1e-3"):to_string(), "0.001")
  end)
  T.it("scientific notation with decimal", function()
    T.eq(bignum.new("1.5e2"):to_string(), "150")
  end)
  T.it("scientific notation 1.5e-2", function()
    T.eq(bignum.new("1.5e-2"):to_string(), "0.015")
  end)
  T.it("large integer string", function()
    local s = "12345678901234567890123456789012345678901234567890"
    T.eq(bignum.new(s):to_string(), s)
  end)
  T.it("very small number", function()
    T.eq(bignum.new("1e-20"):to_string(), "0." .. ("0"):rep(19) .. "1")
  end)
  T.it("pi digits", function()
    T.eq(bignum.new("3.14159265358979323846"):to_string(), "3.14159265358979323846")
  end)
  T.it("error on empty string", function()
    local v, err = bignum.new("")
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("error on non-numeric string", function()
    local v, err = bignum.new("abc")
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("error on bad type", function()
    local v, err = bignum.new(true)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

-- ── Construction from number ───────────────────────────────────────────────────

T.describe("bignum.from_number", function()
  T.it("from integer number", function()
    T.eq(bignum.from_number(42):to_string(), "42")
  end)
  T.it("from negative integer", function()
    T.eq(bignum.from_number(-7):to_string(), "-7")
  end)
  T.it("from zero", function()
    T.eq(bignum.from_number(0):to_string(), "0")
  end)
  T.it("from 3.14 is close to 3.14", function()
    local n = bignum.from_number(3.14)
    -- Lua float 3.14 may not be exactly 3.14; check it starts with "3.14"
    T.ok(n:to_string():sub(1, 4) == "3.14")
  end)
  T.it("error on non-number", function()
    local v, err = bignum.from_number("x")
    T.eq(v, nil)
    T.ok(err)
  end)
end)

-- ── to_string ─────────────────────────────────────────────────────────────────

T.describe("to_string", function()
  T.it("integer with trailing zeros in value", function()
    T.eq(bignum.new("100"):to_string(), "100")
  end)
  T.it("0.5", function()
    T.eq(bignum.new("0.5"):to_string(), "0.5")
  end)
  T.it("negative with fraction", function()
    T.eq(bignum.new("-123.456"):to_string(), "-123.456")
  end)
  T.it("tostring metamethod", function()
    T.eq(tostring(bignum.new("3.14")), "3.14")
  end)
end)

-- ── to_number / to_integer ────────────────────────────────────────────────────

T.describe("to_number", function()
  T.it("converts 42 to 42", function()
    T.eq(bignum.new("42"):to_number(), 42)
  end)
  T.it("converts -3.5 to -3.5", function()
    T.eq(bignum.new("-3.5"):to_number(), -3.5)
  end)
  T.it("converts zero", function()
    T.eq(bignum.new("0"):to_number(), 0)
  end)
end)

T.describe("to_integer", function()
  T.it("integer input", function()
    T.eq(bignum.new("42"):to_integer(), "42")
  end)
  T.it("truncates positive fraction", function()
    T.eq(bignum.new("3.99"):to_integer(), "3")
  end)
  T.it("truncates negative fraction toward zero", function()
    T.eq(bignum.new("-3.99"):to_integer(), "-3")
  end)
  T.it("zero", function()
    T.eq(bignum.new("0"):to_integer(), "0")
  end)
end)

-- ── Addition ──────────────────────────────────────────────────────────────────

T.describe("addition", function()
  T.it("two positive integers", function()
    T.eq((bignum.new("3") + bignum.new("4")):to_string(), "7")
  end)
  T.it("positive and negative cancel", function()
    T.eq((bignum.new("5") + bignum.new("-5")):to_string(), "0")
  end)
  T.it("decimals with same scale", function()
    T.eq((bignum.new("1.1") + bignum.new("2.2")):to_string(), "3.3")
  end)
  T.it("decimals with different scales", function()
    T.eq((bignum.new("1.5") + bignum.new("0.25")):to_string(), "1.75")
  end)
  T.it("add zero", function()
    T.eq((bignum.new("42") + bignum.new("0")):to_string(), "42")
  end)
  T.it("large + small", function()
    T.eq((bignum.new("1000") + bignum.new("0.001")):to_string(), "1000.001")
  end)
  T.it("negative + negative", function()
    T.eq((bignum.new("-3") + bignum.new("-4")):to_string(), "-7")
  end)
  T.it("high precision addition", function()
    local a = bignum.new("0.1")
    local b = bignum.new("0.2")
    T.eq((a + b):to_string(), "0.3")
  end)
end)

-- ── Subtraction ───────────────────────────────────────────────────────────────

T.describe("subtraction", function()
  T.it("positive - positive", function()
    T.eq((bignum.new("10") - bignum.new("3")):to_string(), "7")
  end)
  T.it("result is negative", function()
    T.eq((bignum.new("3") - bignum.new("10")):to_string(), "-7")
  end)
  T.it("equal values give zero", function()
    T.eq((bignum.new("42") - bignum.new("42")):to_string(), "0")
  end)
  T.it("decimal subtraction", function()
    T.eq((bignum.new("1.5") - bignum.new("0.25")):to_string(), "1.25")
  end)
  T.it("sub from zero", function()
    T.eq((bignum.new("0") - bignum.new("5")):to_string(), "-5")
  end)
end)

-- ── Multiplication ────────────────────────────────────────────────────────────

T.describe("multiplication", function()
  T.it("small integers", function()
    T.eq((bignum.new("6") * bignum.new("7")):to_string(), "42")
  end)
  T.it("by zero", function()
    T.eq((bignum.new("123") * bignum.new("0")):to_string(), "0")
  end)
  T.it("by one", function()
    T.eq((bignum.new("42") * bignum.new("1")):to_string(), "42")
  end)
  T.it("decimal * decimal", function()
    T.eq((bignum.new("1.5") * bignum.new("2")):to_string(), "3")
  end)
  T.it("0.1 * 0.1 = 0.01", function()
    T.eq((bignum.new("0.1") * bignum.new("0.1")):to_string(), "0.01")
  end)
  T.it("negative * positive", function()
    T.eq((bignum.new("-3") * bignum.new("4")):to_string(), "-12")
  end)
  T.it("negative * negative", function()
    T.eq((bignum.new("-3") * bignum.new("-4")):to_string(), "12")
  end)
  T.it("large integer multiplication", function()
    -- 12345678901234567890 * 10 = 123456789012345678900
    local a = bignum.new("12345678901234567890")
    T.eq((a * bignum.new("10")):to_string(), "123456789012345678900")
  end)
end)

-- ── Division ─────────────────────────────────────────────────────────────────

T.describe("division", function()
  T.it("exact integer division", function()
    T.eq((bignum.new("42") / bignum.new("6")):to_string(), "7")
  end)
  T.it("1/4 = 0.25 exact", function()
    T.eq((bignum.new("1") / bignum.new("4")):to_string(), "0.25")
  end)
  T.it("1/3 starts with 0.333", function()
    local result = (bignum.new("1") / bignum.new("3")):to_string()
    T.ok(result:sub(1, 5) == "0.333")
  end)
  T.it("division by zero returns nil,errmsg", function()
    local v, err = bignum.new("5"):div(bignum.new("0"))
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("negative / positive", function()
    local result = (bignum.new("-1") / bignum.new("4")):to_string()
    T.eq(result, "-0.25")
  end)
  T.it("zero / anything = 0", function()
    T.eq((bignum.new("0") / bignum.new("7")):to_string(), "0")
  end)
  T.it("10 / 2 = 5", function()
    T.eq((bignum.new("10") / bignum.new("2")):to_string(), "5")
  end)
  T.it("precision: 10 decimal places", function()
    local result = bignum.new("1"):div(bignum.new("7"), 10)
    local s = result:to_string()
    T.ok(s:sub(1, 12) == "0.1428571428")
  end)
end)

-- ── Modulo ────────────────────────────────────────────────────────────────────

T.describe("modulo", function()
  T.it("10 % 3 = 1", function()
    T.eq((bignum.new("10") % bignum.new("3")):to_string(), "1")
  end)
  T.it("42 % 6 = 0", function()
    T.eq((bignum.new("42") % bignum.new("6")):to_string(), "0")
  end)
  T.it("modulo by zero returns nil,errmsg", function()
    local v, err = bignum.new("5"):mod(bignum.new("0"))
    T.eq(v, nil)
    T.ok(err)
  end)
end)

-- ── Negation / abs ────────────────────────────────────────────────────────────

T.describe("unary", function()
  T.it("neg of positive", function()
    T.eq((-bignum.new("5")):to_string(), "-5")
  end)
  T.it("neg of negative", function()
    T.eq((-bignum.new("-5")):to_string(), "5")
  end)
  T.it("neg of zero", function()
    T.eq((-bignum.new("0")):to_string(), "0")
  end)
  T.it("abs of negative", function()
    T.eq(bignum.new("-3.14"):abs():to_string(), "3.14")
  end)
  T.it("abs of positive", function()
    T.eq(bignum.new("3.14"):abs():to_string(), "3.14")
  end)
  T.it("abs of zero", function()
    T.eq(bignum.new("0"):abs():to_string(), "0")
  end)
end)

-- ── Comparison ────────────────────────────────────────────────────────────────

T.describe("comparison", function()
  T.it("eq equal values", function()
    T.ok(bignum.new("3.14") == bignum.new("3.14"))
  end)
  T.it("eq different values", function()
    T.fail(bignum.new("3") == bignum.new("4"))
  end)
  T.it("eq zero variants", function()
    T.ok(bignum.new("0"):eq(bignum.new("-0")))
  end)
  T.it("lt positive", function()
    T.ok(bignum.new("3") < bignum.new("4"))
    T.fail(bignum.new("4") < bignum.new("3"))
  end)
  T.it("lt with decimals", function()
    T.ok(bignum.new("1.1") < bignum.new("1.2"))
  end)
  T.it("lt mixed sign", function()
    T.ok(bignum.new("-1") < bignum.new("1"))
  end)
  T.it("le equal", function()
    T.ok(bignum.new("5") <= bignum.new("5"))
  end)
  T.it("le less", function()
    T.ok(bignum.new("4") <= bignum.new("5"))
  end)
  T.it("gt", function()
    T.ok(bignum.new("10"):gt(bignum.new("3")))
    T.fail(bignum.new("3"):gt(bignum.new("10")))
  end)
  T.it("ge", function()
    T.ok(bignum.new("5"):ge(bignum.new("5")))
    T.ok(bignum.new("6"):ge(bignum.new("5")))
    T.fail(bignum.new("4"):ge(bignum.new("5")))
  end)
  T.it("compare large numbers", function()
    T.ok(bignum.new("1e50") > bignum.new("1e49"))
  end)
  T.it("compare negative numbers", function()
    T.ok(bignum.new("-10") < bignum.new("-3"))
    T.ok(bignum.new("-3") > bignum.new("-10"))
  end)
end)

-- ── sign / is_zero / is_integer ───────────────────────────────────────────────

T.describe("predicates", function()
  T.it("sign of positive", function()
    T.eq(bignum.new("5"):sign(), 1)
  end)
  T.it("sign of negative", function()
    T.eq(bignum.new("-5"):sign(), -1)
  end)
  T.it("sign of zero", function()
    T.eq(bignum.new("0"):sign(), 0)
  end)
  T.it("is_zero on zero", function()
    T.ok(bignum.new("0"):is_zero())
  end)
  T.it("is_zero on non-zero", function()
    T.fail(bignum.new("1"):is_zero())
  end)
  T.it("is_integer on integer", function()
    T.ok(bignum.new("42"):is_integer())
  end)
  T.it("is_integer on 1.0 (trailing zero already stripped)", function()
    -- 1.0 normalizes to 1 (trailing zero stripped)
    T.ok(bignum.new("1.0"):is_integer())
  end)
  T.it("is_integer on 3.14", function()
    T.fail(bignum.new("3.14"):is_integer())
  end)
  T.it("is_integer on zero", function()
    T.ok(bignum.new("0"):is_integer())
  end)
  T.it("is_integer on 0.001", function()
    T.fail(bignum.new("0.001"):is_integer())
  end)
end)

-- ── round / floor / ceil / trunc ─────────────────────────────────────────────

T.describe("rounding", function()
  T.it("round to 2 decimal places", function()
    T.eq(bignum.new("3.14159"):round(2):to_string(), "3.14")
  end)
  T.it("round up at .5", function()
    T.eq(bignum.new("2.345"):round(2):to_string(), "2.35")
  end)
  T.it("round to 0 places", function()
    T.eq(bignum.new("3.7"):round(0):to_string(), "4")
  end)
  T.it("round negative", function()
    T.eq(bignum.new("-3.14159"):round(2):to_string(), "-3.14")
  end)
  T.it("floor positive", function()
    T.eq(bignum.new("3.9"):floor():to_string(), "3")
  end)
  T.it("floor negative with fraction", function()
    T.eq(bignum.new("-3.1"):floor():to_string(), "-4")
  end)
  T.it("floor integer", function()
    T.eq(bignum.new("5"):floor():to_string(), "5")
  end)
  T.it("ceil positive with fraction", function()
    T.eq(bignum.new("3.1"):ceil():to_string(), "4")
  end)
  T.it("ceil negative", function()
    T.eq(bignum.new("-3.9"):ceil():to_string(), "-3")
  end)
  T.it("ceil integer", function()
    T.eq(bignum.new("5"):ceil():to_string(), "5")
  end)
  T.it("trunc positive", function()
    T.eq(bignum.new("3.99"):trunc():to_string(), "3")
  end)
  T.it("trunc negative toward zero", function()
    T.eq(bignum.new("-3.99"):trunc():to_string(), "-3")
  end)
  T.it("trunc integer unchanged", function()
    T.eq(bignum.new("42"):trunc():to_string(), "42")
  end)
  T.it("trunc zero", function()
    T.eq(bignum.new("0"):trunc():to_string(), "0")
  end)
end)

-- ── pow ────────────────────────────────────────────────────────────────────────

T.describe("pow", function()
  T.it("2^10 = 1024", function()
    T.eq(bignum.pow(bignum.new("2"), 10):to_string(), "1024")
  end)
  T.it("3^0 = 1", function()
    T.eq(bignum.pow(bignum.new("3"), 0):to_string(), "1")
  end)
  T.it("3^1 = 3", function()
    T.eq(bignum.pow(bignum.new("3"), 1):to_string(), "3")
  end)
  T.it("10^20", function()
    T.eq(bignum.pow(bignum.new("10"), 20):to_string(), "1" .. ("0"):rep(20))
  end)
  T.it("1.5^2 = 2.25", function()
    T.eq(bignum.pow(bignum.new("1.5"), 2):to_string(), "2.25")
  end)
  T.it("negative base even power", function()
    T.eq(bignum.pow(bignum.new("-2"), 4):to_string(), "16")
  end)
  T.it("negative base odd power", function()
    T.eq(bignum.pow(bignum.new("-2"), 3):to_string(), "-8")
  end)
  T.it("error on negative exponent", function()
    local v, err = bignum.pow(bignum.new("2"), -1)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("error on non-integer exponent", function()
    local v, err = bignum.pow(bignum.new("2"), 1.5)
    T.eq(v, nil)
    T.ok(err)
  end)
end)

-- ── sqrt ──────────────────────────────────────────────────────────────────────

T.describe("sqrt", function()
  T.it("sqrt(4) = 2", function()
    T.eq(bignum.sqrt(bignum.new("4"), 5):to_string(), "2")
  end)
  T.it("sqrt(9) = 3", function()
    T.eq(bignum.sqrt(bignum.new("9"), 5):to_string(), "3")
  end)
  T.it("sqrt(2) starts with 1.41421", function()
    local result = bignum.sqrt(bignum.new("2"), 10):to_string()
    T.ok(result:sub(1, 7) == "1.41421", "got: " .. result)
  end)
  T.it("sqrt(0) = 0", function()
    T.eq(bignum.sqrt(bignum.new("0"), 5):to_string(), "0")
  end)
  T.it("sqrt of negative returns nil,errmsg", function()
    local v, err = bignum.sqrt(bignum.new("-1"), 5)
    T.eq(v, nil)
    T.ok(err)
  end)
  T.it("sqrt(0.25) = 0.5", function()
    local result = bignum.sqrt(bignum.new("0.25"), 5):to_string()
    T.eq(result, "0.5")
  end)
  T.it("sqrt(100) = 10", function()
    T.eq(bignum.sqrt(bignum.new("100"), 5):to_string(), "10")
  end)
end)

-- ── pi ────────────────────────────────────────────────────────────────────────

T.describe("pi", function()
  T.it("pi(5) starts with 3.14159", function()
    local result = bignum.pi(5):to_string()
    T.ok(result:sub(1, 7) == "3.14159", "got: " .. result)
  end)
  T.it("pi(10) correct to 10 places", function()
    local result = bignum.pi(10):to_string()
    -- pi = 3.14159265358... rounds to 3.1415926536 at 10 decimal places
    T.ok(result:sub(1, 12) == "3.1415926536", "got: " .. result)
  end)
  T.it("pi(20) correct to 20 places", function()
    local result = bignum.pi(20):to_string()
    -- pi = 3.14159265358979323846...
    T.ok(result:sub(1, 22) == "3.14159265358979323846", "got: " .. result)
  end)
end)

-- ── precision setting ─────────────────────────────────────────────────────────

T.describe("precision", function()
  T.it("get_precision returns default 50", function()
    bignum.set_precision(50)
    T.eq(bignum.get_precision(), 50)
  end)
  T.it("set_precision changes default", function()
    bignum.set_precision(20)
    T.eq(bignum.get_precision(), 20)
    bignum.set_precision(50)  -- reset
  end)
end)

-- ── Edge cases ────────────────────────────────────────────────────────────────

T.describe("edge cases", function()
  T.it("1e50 round-trips", function()
    local s = bignum.new("1e50"):to_string()
    T.eq(s, "1" .. ("0"):rep(50))
  end)
  T.it("1e-20 round-trips", function()
    local s = bignum.new("1e-20"):to_string()
    T.eq(s, "0." .. ("0"):rep(19) .. "1")
  end)
  T.it("add two high-precision values", function()
    local a = bignum.new("3.14159265358979323846")
    local b = bignum.new("2.71828182845904523536")
    local s = (a + b):to_string()
    T.eq(s, "5.85987448204883847382")
  end)
  T.it("multiply then check identity: a*1=a", function()
    local a = bignum.new("3.14159265358979323846")
    T.eq((a * bignum.new("1")):to_string(), a:to_string())
  end)
  T.it("a - a = 0", function()
    local a = bignum.new("3.14159265358979323846")
    T.eq((a - a):to_string(), "0")
  end)
  T.it("a / a = 1 (to many places)", function()
    local a = bignum.new("3.14")
    local result = a:div(a, 10):to_string()
    T.ok(result:sub(1, 1) == "1", "got: " .. result)
  end)
  T.it("ZERO constant is zero", function()
    T.ok(bignum.ZERO:is_zero())
  end)
  T.it("ONE constant is one", function()
    T.eq(bignum.ONE:to_string(), "1")
  end)
  T.it("parse is alias for new", function()
    T.eq(bignum.parse("42"):to_string(), "42")
  end)
  T.it("clone via new(bignum)", function()
    local a = bignum.new("3.14")
    local b = bignum.new(a)
    T.eq(b:to_string(), "3.14")
  end)
  T.it("100 as integer", function()
    T.eq(bignum.new("100"):to_string(), "100")
    T.ok(bignum.new("100"):is_integer())
  end)
  T.it("0.001 is not integer", function()
    T.fail(bignum.new("0.001"):is_integer())
  end)
end)
