if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local ir = require("lib.ir")

T.describe("ir", function()

	T.describe("module", function()
		T.it("creates a module with a name", function()
			local mod = ir.module("test")
			T.eq(mod.name, "test")
		end)

		T.it("starts with no functions", function()
			local mod = ir.module("empty")
			T.eq(#mod:funcs(), 0)
		end)

		T.it("can add multiple functions", function()
			local mod = ir.module("multi")
			mod:func("a", {})
			mod:func("b", {"x"})
			T.eq(#mod:funcs(), 2)
			T.eq(mod:funcs()[1].name, "a")
			T.eq(mod:funcs()[2].name, "b")
		end)
	end)

	T.describe("func", function()
		T.it("creates a function with name and params", function()
			local mod = ir.module("t")
			local f = mod:func("main", {"x", "y"})
			T.eq(f.name, "main")
			T.eq(#f.params, 2)
			T.eq(f.params[1], "x")
			T.eq(f.params[2], "y")
		end)

		T.it("creates a function with no params", function()
			local mod = ir.module("t")
			local f = mod:func("noop", {})
			T.eq(#f.params, 0)
		end)

		T.it("starts with no blocks", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			T.eq(#f:blocks(), 0)
		end)

		T.it("can add blocks", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			f:block("entry")
			f:block("exit")
			T.eq(#f:blocks(), 2)
			T.eq(f:blocks()[1].name, "entry")
			T.eq(f:blocks()[2].name, "exit")
		end)
	end)

	T.describe("block", function()
		T.it("starts with no instructions", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			T.eq(#b:instructions(), 0)
		end)
	end)

	T.describe("instructions", function()
		T.it("const returns a value ID", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v = b:const(42)
			T.eq(v, "%1")
		end)

		T.it("param returns a value ID", function()
			local mod = ir.module("t")
			local f = mod:func("f", {"x"})
			local b = f:block("entry")
			local v = b:param("x")
			T.eq(v, "%1")
		end)

		T.it("value IDs are sequential", function()
			local mod = ir.module("t")
			local f = mod:func("f", {"x"})
			local b = f:block("entry")
			local v1 = b:const(1)
			local v2 = b:const(2)
			local v3 = b:param("x")
			T.eq(v1, "%1")
			T.eq(v2, "%2")
			T.eq(v3, "%3")
		end)

		T.it("value IDs are sequential across blocks", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b1 = f:block("a")
			local b2 = f:block("b")
			local v1 = b1:const(1)
			local v2 = b2:const(2)
			T.eq(v1, "%1")
			T.eq(v2, "%2")
		end)

		T.it("add instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(3)
			local v2 = b:const(4)
			local v3 = b:add(v1, v2)
			T.eq(v3, "%3")
			local instrs = b:instructions()
			T.eq(#instrs, 3)
			T.eq(instrs[3].op, "add")
			T.eq(instrs[3].args[1], "%1")
			T.eq(instrs[3].args[2], "%2")
		end)

		T.it("sub instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(10)
			local v2 = b:const(3)
			local v3 = b:sub(v1, v2)
			T.eq(v3, "%3")
			T.eq(b:instructions()[3].op, "sub")
		end)

		T.it("mul instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(5)
			local v2 = b:const(6)
			local v3 = b:mul(v1, v2)
			T.eq(v3, "%3")
			T.eq(b:instructions()[3].op, "mul")
		end)

		T.it("div instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(20)
			local v2 = b:const(4)
			local v3 = b:div(v1, v2)
			T.eq(v3, "%3")
			T.eq(b:instructions()[3].op, "div")
		end)

		T.it("mod instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(10)
			local v2 = b:const(3)
			local v3 = b:mod(v1, v2)
			T.eq(v3, "%3")
			T.eq(b:instructions()[3].op, "mod")
		end)

		T.it("cmp instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(1)
			local v2 = b:const(2)
			local v3 = b:cmp("lt", v1, v2)
			T.eq(v3, "%3")
			local instr = b:instructions()[3]
			T.eq(instr.op, "cmp")
			T.eq(instr.args[1], "lt")
			T.eq(instr.args[2], "%1")
			T.eq(instr.args[3], "%2")
		end)

		T.it("all cmp variants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(1)
			local v2 = b:const(2)
			for _, op in ipairs({"eq", "ne", "lt", "le", "gt", "ge"}) do
				local v = b:cmp(op, v1, v2)
				T.ok(v, "cmp " .. op .. " returns a value")
			end
		end)

		T.it("phi instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b1 = f:block("a")
			local b2 = f:block("b")
			local b3 = f:block("c")
			local v1 = b1:const(1)
			local v2 = b2:const(2)
			local v3 = b3:phi({b1, v1}, {b2, v2})
			T.eq(v3, "%3")
			local instr = b3:instructions()[1]
			T.eq(instr.op, "phi")
			T.eq(#instr.args, 2)
			T.eq(instr.args[1][1].name, "a")
			T.eq(instr.args[1][2], "%1")
			T.eq(instr.args[2][1].name, "b")
			T.eq(instr.args[2][2], "%2")
		end)

		T.it("call instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local fn_val = b:const(0) -- function reference
			local arg1 = b:const(1)
			local arg2 = b:const(2)
			local v = b:call(fn_val, arg1, arg2)
			T.eq(v, "%4")
			local instr = b:instructions()[4]
			T.eq(instr.op, "call")
			T.eq(instr.args[1], "%1")
			T.eq(instr.args[2], "%2")
			T.eq(instr.args[3], "%3")
		end)

		T.it("br instruction (conditional branch)", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local yes = f:block("yes")
			local no = f:block("no")
			local cond = entry:const(true)
			entry:br(cond, yes, no)
			local instrs = entry:instructions()
			T.eq(#instrs, 2)
			T.eq(instrs[2].op, "br")
			T.eq(instrs[2].id, nil)
		end)

		T.it("jmp instruction (unconditional)", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local target = f:block("target")
			entry:jmp(target)
			local instrs = entry:instructions()
			T.eq(#instrs, 1)
			T.eq(instrs[1].op, "jmp")
			T.eq(instrs[1].id, nil)
		end)

		T.it("ret instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v = b:const(42)
			b:ret(v)
			local instrs = b:instructions()
			T.eq(#instrs, 2)
			T.eq(instrs[2].op, "ret")
			T.eq(instrs[2].id, nil)
			T.eq(instrs[2].args[1], "%1")
		end)

		T.it("copy instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(5)
			local v2 = b:copy(v1)
			T.eq(v2, "%2")
			T.eq(b:instructions()[2].op, "copy")
			T.eq(b:instructions()[2].args[1], "%1")
		end)
	end)

	T.describe("successors", function()
		T.it("br has two successors", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local a = f:block("a")
			local b = f:block("b")
			local cond = entry:const(true)
			entry:br(cond, a, b)
			local succs = entry:successors()
			T.eq(#succs, 2)
			T.eq(succs[1].name, "a")
			T.eq(succs[2].name, "b")
		end)

		T.it("jmp has one successor", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local target = f:block("target")
			entry:jmp(target)
			local succs = entry:successors()
			T.eq(#succs, 1)
			T.eq(succs[1].name, "target")
		end)

		T.it("ret has no successors", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			b:ret(b:const(0))
			T.eq(#b:successors(), 0)
		end)

		T.it("empty block has no successors", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			T.eq(#b:successors(), 0)
		end)
	end)

	T.describe("predecessors", function()
		T.it("entry has no predecessors", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local b = f:block("b")
			entry:jmp(b)
			T.eq(#entry:predecessors(), 0)
		end)

		T.it("target of jmp has predecessor", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local b = f:block("b")
			entry:jmp(b)
			local preds = b:predecessors()
			T.eq(#preds, 1)
			T.eq(preds[1].name, "entry")
		end)

		T.it("loop block has itself as predecessor", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local loop = f:block("loop")
			local exit_b = f:block("exit")
			entry:jmp(loop)
			local cond = loop:const(true)
			loop:br(cond, exit_b, loop)
			local preds = loop:predecessors()
			T.eq(#preds, 2)
			-- entry and loop itself
			local names = {}
			for i = 1, #preds do names[preds[i].name] = true end
			T.ok(names["entry"])
			T.ok(names["loop"])
		end)

		T.it("br target has predecessor", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local a = f:block("a")
			local b = f:block("b")
			local cond = entry:const(true)
			entry:br(cond, a, b)
			T.eq(#a:predecessors(), 1)
			T.eq(a:predecessors()[1].name, "entry")
			T.eq(#b:predecessors(), 1)
			T.eq(b:predecessors()[1].name, "entry")
		end)
	end)

	T.describe("cfg", function()
		T.it("postorder returns reverse postorder", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local a = f:block("a")
			local b = f:block("b")
			local exit_b = f:block("exit")
			local cond = entry:const(true)
			entry:br(cond, a, b)
			a:jmp(exit_b)
			b:jmp(exit_b)
			local cfg = f:cfg()
			local rpo = cfg:postorder()
			T.eq(rpo[1], "entry")
			-- exit must come after a and b
			T.ok(#rpo == 4)
		end)

		T.it("dominators for diamond CFG", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local a = f:block("a")
			local b = f:block("b")
			local exit_b = f:block("exit")
			local cond = entry:const(true)
			entry:br(cond, a, b)
			a:jmp(exit_b)
			b:jmp(exit_b)
			local cfg = f:cfg()
			local doms = cfg:dominators()
			T.eq(doms["a"], "entry")
			T.eq(doms["b"], "entry")
			T.eq(doms["exit"], "entry")
			-- entry has no dominator (it is the root)
			T.eq(doms["entry"], nil)
		end)

		T.it("dominators for linear CFG", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local a = f:block("a")
			local b = f:block("b")
			local c = f:block("c")
			a:jmp(b)
			b:jmp(c)
			c:ret(nil)
			local cfg = f:cfg()
			local doms = cfg:dominators()
			T.eq(doms["b"], "a")
			T.eq(doms["c"], "b")
		end)

		T.it("dominators for loop", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local loop = f:block("loop")
			local exit_b = f:block("exit")
			entry:jmp(loop)
			local cond = loop:const(true)
			loop:br(cond, exit_b, loop)
			local cfg = f:cfg()
			local doms = cfg:dominators()
			T.eq(doms["loop"], "entry")
			T.eq(doms["exit"], "loop")
		end)
	end)

	T.describe("dce", function()
		T.it("removes unused instructions", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			b:const(42)       -- unused
			b:const(99)       -- unused
			local v3 = b:const(1)
			b:ret(v3)
			T.eq(#b:instructions(), 4)
			local removed = ir.dce(f)
			T.eq(removed, 2)
			T.eq(#b:instructions(), 2) -- const 1 + ret
		end)

		T.it("keeps used instructions", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(3)
			local v2 = b:const(4)
			local v3 = b:add(v1, v2)
			b:ret(v3)
			local removed = ir.dce(f)
			T.eq(removed, 0)
			T.eq(#b:instructions(), 4)
		end)

		T.it("cascading DCE", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(1)
			local v2 = b:const(2)
			local _ = b:add(v1, v2) -- v3, unused — removing it makes v1, v2 unused
			local v4 = b:const(99)
			b:ret(v4)
			local removed = ir.dce(f)
			T.eq(removed, 3) -- v1, v2, v3 all removed
			T.eq(#b:instructions(), 2) -- const 99 + ret
		end)

		T.it("keeps calls (side effects)", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local fn_val = b:const(0)
			b:call(fn_val) -- unused return but has side effects
			b:ret(nil)
			ir.dce(f)
			-- call should remain (fn_val used by call, call kept for side effects)
			local found_call = false
			for _, instr in ipairs(b:instructions()) do
				if instr.op == "call" then found_call = true end
			end
			T.ok(found_call)
		end)
	end)

	T.describe("const_fold", function()
		T.it("folds add of two constants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(3)
			local v2 = b:const(4)
			local v3 = b:add(v1, v2)
			b:ret(v3)
			local folded = ir.const_fold(f)
			T.eq(folded, 1)
			local instrs = b:instructions()
			T.eq(instrs[3].op, "const")
			T.eq(instrs[3].args[1], 7)
		end)

		T.it("folds sub of two constants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(10)
			local v2 = b:const(3)
			local v3 = b:sub(v1, v2)
			b:ret(v3)
			ir.const_fold(f)
			T.eq(b:instructions()[3].args[1], 7)
		end)

		T.it("folds mul of two constants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(5)
			local v2 = b:const(6)
			local v3 = b:mul(v1, v2)
			b:ret(v3)
			ir.const_fold(f)
			T.eq(b:instructions()[3].args[1], 30)
		end)

		T.it("folds div of two constants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(20)
			local v2 = b:const(4)
			local v3 = b:div(v1, v2)
			b:ret(v3)
			ir.const_fold(f)
			T.eq(b:instructions()[3].args[1], 5)
		end)

		T.it("folds mod of two constants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(10)
			local v2 = b:const(3)
			local v3 = b:mod(v1, v2)
			b:ret(v3)
			ir.const_fold(f)
			T.eq(b:instructions()[3].args[1], 1)
		end)

		T.it("folds cmp of two constants", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(3)
			local v2 = b:const(4)
			local v3 = b:cmp("lt", v1, v2)
			b:ret(v3)
			ir.const_fold(f)
			T.eq(b:instructions()[3].args[1], true)
		end)

		T.it("does not fold non-constant operands", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:param("x")
			local v2 = b:const(4)
			local v3 = b:add(v1, v2)
			b:ret(v3)
			local folded = ir.const_fold(f)
			T.eq(folded, 0)
			T.eq(b:instructions()[3].op, "add")
		end)

		T.it("chained constant folding", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(2)
			local v2 = b:const(3)
			local v3 = b:add(v1, v2)  -- folds to const 5
			local v4 = b:const(10)
			local v5 = b:mul(v3, v4)  -- can fold to const 50 since v3 is now const
			b:ret(v5)
			-- First pass folds v3
			ir.const_fold(f)
			-- Second pass folds v5
			ir.const_fold(f)
			T.eq(b:instructions()[5].op, "const")
			T.eq(b:instructions()[5].args[1], 50)
		end)
	end)

	T.describe("copy_prop", function()
		T.it("replaces copy with original value", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(42)
			local v2 = b:copy(v1)
			b:ret(v2)
			local propagated = ir.copy_prop(f)
			T.eq(propagated, 1)
			-- ret should now reference v1 directly
			local instrs = b:instructions()
			-- copy is removed
			T.eq(#instrs, 2) -- const + ret
			T.eq(instrs[2].args[1], "%1")
		end)

		T.it("propagates through chains", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(42)
			local v2 = b:copy(v1)
			local v3 = b:copy(v2)
			b:ret(v3)
			ir.copy_prop(f)
			local instrs = b:instructions()
			T.eq(#instrs, 2) -- const + ret
			T.eq(instrs[2].args[1], "%1")
		end)

		T.it("propagates into arithmetic", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("entry")
			local v1 = b:const(3)
			local v2 = b:copy(v1)
			local v3 = b:const(4)
			local v4 = b:add(v2, v3)
			b:ret(v4)
			ir.copy_prop(f)
			-- add should reference v1 instead of v2
			local instrs = b:instructions()
			local add_instr = nil
			for _, instr in ipairs(instrs) do
				if instr.op == "add" then add_instr = instr end
			end
			T.ok(add_instr)
			T.eq(add_instr.args[1], "%1") -- original const, not copy
		end)
	end)

	T.describe("dump", function()
		T.it("produces text format", function()
			local mod = ir.module("t")
			local f = mod:func("main", {"x", "y"})
			local entry = f:block("entry")
			local v1 = entry:const(42)
			local v2 = entry:param("x")
			local v3 = entry:add(v1, v2)
			entry:ret(v3)
			local text = f:dump()
			T.ok(text:find("func main%(x, y%):"), "header")
			T.ok(text:find("entry:"), "block label")
			T.ok(text:find("%%1 = const 42"), "const")
			T.ok(text:find("%%2 = param x"), "param")
			T.ok(text:find("%%3 = add %%1, %%2"), "add")
			T.ok(text:find("ret %%3"), "ret")
		end)

		T.it("dumps br instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local a = f:block("a")
			local b = f:block("b")
			local cond = entry:const(true)
			entry:br(cond, a, b)
			local text = f:dump()
			T.ok(text:find("br %%1, a, b"), "br format")
		end)

		T.it("dumps jmp instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local target = f:block("target")
			entry:jmp(target)
			local text = f:dump()
			T.ok(text:find("jmp target"), "jmp format")
		end)

		T.it("dumps phi instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local a = f:block("a")
			local b = f:block("b")
			local c = f:block("c")
			local v1 = a:const(1)
			local v2 = b:const(2)
			local v3 = c:phi({a, v1}, {b, v2})
			local _ = v3
			local text = f:dump()
			T.ok(text:find("%[a: %%1%]"), "phi edge a")
			T.ok(text:find("%[b: %%2%]"), "phi edge b")
		end)

		T.it("dumps cmp instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local v1 = entry:const(1)
			local v2 = entry:const(2)
			local _ = entry:cmp("lt", v1, v2)
			local text = f:dump()
			T.ok(text:find("cmp lt %%1, %%2"), "cmp format")
		end)

		T.it("dumps call instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local fn_val = entry:const(0)
			local arg = entry:const(1)
			local _ = entry:call(fn_val, arg)
			local text = f:dump()
			T.ok(text:find("call %%1%(%%2%)"), "call format")
		end)

		T.it("dumps copy instruction", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local entry = f:block("entry")
			local v1 = entry:const(5)
			local _ = entry:copy(v1)
			local text = f:dump()
			T.ok(text:find("copy %%1"), "copy format")
		end)

		T.it("dumps empty function", function()
			local mod = ir.module("t")
			local f = mod:func("empty", {})
			local text = f:dump()
			T.eq(text, "func empty():")
		end)

		T.it("dumps multiple blocks", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local a = f:block("a")
			local b = f:block("b")
			a:jmp(b)
			b:ret(nil)
			local text = f:dump()
			T.ok(text:find("a:"), "block a")
			T.ok(text:find("b:"), "block b")
		end)
	end)

	T.describe("multiple functions", function()
		T.it("value IDs are independent per function", function()
			local mod = ir.module("t")
			local f1 = mod:func("f1", {})
			local f2 = mod:func("f2", {})
			local b1 = f1:block("entry")
			local b2 = f2:block("entry")
			local v1 = b1:const(1)
			local v2 = b2:const(2)
			T.eq(v1, "%1")
			T.eq(v2, "%1") -- separate counter
		end)
	end)

	T.describe("empty blocks", function()
		T.it("empty block has no instructions", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("empty")
			T.eq(#b:instructions(), 0)
		end)

		T.it("empty block has no successors", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			local b = f:block("empty")
			T.eq(#b:successors(), 0)
		end)
	end)

	T.describe("chained operations", function()
		T.it("chain of arithmetic", function()
			local mod = ir.module("t")
			local f = mod:func("f", {"a", "b", "c"})
			local entry = f:block("entry")
			local va = entry:param("a")
			local vb = entry:param("b")
			local vc = entry:param("c")
			local v4 = entry:add(va, vb)
			local v5 = entry:mul(v4, vc)
			local v6 = entry:sub(v5, va)
			entry:ret(v6)
			T.eq(v4, "%4")
			T.eq(v5, "%5")
			T.eq(v6, "%6")
			T.eq(#entry:instructions(), 7) -- 3 params + add + mul + sub + ret
		end)

		T.it("full program: loop with countdown", function()
			local mod = ir.module("countdown")
			local f = mod:func("countdown", {"n"})
			local entry = f:block("entry")
			local loop = f:block("loop")
			local exit_b = f:block("exit")

			local n = entry:param("n")
			entry:jmp(loop)

			local phi_val = loop:phi({entry, n}, {loop, "%5"})
			local one = loop:const(1)
			local next_val = loop:sub(phi_val, one)
			local zero = loop:const(0)
			local done = loop:cmp("eq", next_val, zero)
			loop:br(done, exit_b, loop)

			exit_b:ret(next_val)

			-- Verify structure
			T.eq(#f:blocks(), 3)
			T.eq(#entry:instructions(), 2) -- param + jmp
			T.eq(#loop:instructions(), 6) -- phi + const + sub + const + cmp + br
			T.eq(#exit_b:instructions(), 1) -- ret

			-- Verify CFG
			T.eq(#entry:successors(), 1)
			T.eq(entry:successors()[1].name, "loop")
			T.eq(#loop:successors(), 2)
			T.eq(#exit_b:successors(), 0)

			-- Verify predecessors
			local loop_preds = loop:predecessors()
			T.eq(#loop_preds, 2)

			-- Dump should produce readable output
			local text = f:dump()
			T.ok(text:find("func countdown%(n%):"), "header")
			T.ok(text:find("phi"), "phi node")
		end)
	end)

	T.describe("block ordering", function()
		T.it("blocks() preserves insertion order", function()
			local mod = ir.module("t")
			local f = mod:func("f", {})
			f:block("c")
			f:block("a")
			f:block("b")
			local blocks = f:blocks()
			T.eq(blocks[1].name, "c")
			T.eq(blocks[2].name, "a")
			T.eq(blocks[3].name, "b")
		end)
	end)
end)
