if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.config")

T.describe("lib/config", function()

  T.describe("defaults", function()
    T.it("gets existing default key", function()
      local cfg = M.new():defaults({ port = 8080, host = "localhost" })
      T.eq(cfg:get("port"), 8080)
      T.eq(cfg:get("host"), "localhost")
    end)

    T.it("returns nil for missing key", function()
      local cfg = M.new():defaults({ port = 8080 })
      T.eq(cfg:get("missing"), nil)
    end)

    T.it("returns fallback default for missing key", function()
      local cfg = M.new():defaults({ port = 8080 })
      T.eq(cfg:get("missing", 42), 42)
    end)

    T.it("returns false as a valid default value", function()
      local cfg = M.new():defaults({ debug = false })
      T.eq(cfg:get("debug"), false)
    end)
  end)

  T.describe("layer", function()
    T.it("layer overrides default", function()
      local cfg = M.new()
        :defaults({ port = 8080 })
        :layer({ port = 9090 })
      T.eq(cfg:get("port"), 9090)
    end)

    T.it("layer does not affect unrelated defaults", function()
      local cfg = M.new()
        :defaults({ port = 8080, host = "localhost" })
        :layer({ port = 9090 })
      T.eq(cfg:get("host"), "localhost")
    end)

    T.it("later layer wins over earlier layer", function()
      local cfg = M.new()
        :defaults({ port = 8080 })
        :layer({ port = 9090 })
        :layer({ port = 7070 })
      T.eq(cfg:get("port"), 7070)
    end)

    T.it("multiple layers: earlier layer key survives if not overridden", function()
      local cfg = M.new()
        :defaults({ x = 1, y = 2 })
        :layer({ x = 10 })
        :layer({ y = 20 })
      T.eq(cfg:get("x"), 10)
      T.eq(cfg:get("y"), 20)
    end)
  end)

  T.describe("env layer", function()
    T.it("reads APP_PORT as 'port'", function()
      local env = { APP_PORT = "9090" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :defaults({ port = 8080 })
        :env("APP")
      T.eq(cfg:get("port"), "9090")
    end)

    T.it("nested APP_DB_HOST -> db.host", function()
      local env = { APP_DB_HOST = "dbserver" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :env("APP")
      T.eq(cfg:get("db.host"), "dbserver")
    end)

    T.it("env does not affect unrelated keys", function()
      local env = { APP_PORT = "9090" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :defaults({ host = "localhost" })
        :env("APP")
      T.eq(cfg:get("host"), "localhost")
    end)

    T.it("env overrides layer (higher priority)", function()
      local env = { APP_PORT = "5555" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :layer({ port = 9090 })
        :env("APP")
      T.eq(cfg:get("port"), "5555")
    end)

    T.it("missing env var falls through to layer", function()
      local env = {}
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :layer({ port = 9090 })
        :env("APP")
      T.eq(cfg:get("port"), 9090)
    end)
  end)

  T.describe("args layer", function()
    T.it("args override env", function()
      local env = { APP_PORT = "5555" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :defaults({ port = 8080 })
        :env("APP")
        :args({ port = 3000 })
      T.eq(cfg:get("port"), 3000)
    end)

    T.it("args override defaults", function()
      local cfg = M.new()
        :defaults({ port = 8080 })
        :args({ port = 1234 })
      T.eq(cfg:get("port"), 1234)
    end)

    T.it("nil args table is ignored", function()
      local cfg = M.new()
        :defaults({ port = 8080 })
        :args(nil)
      T.eq(cfg:get("port"), 8080)
    end)
  end)

  T.describe("typed accessors", function()
    T.it("int: returns integer from number", function()
      local cfg = M.new():defaults({ port = 8080 })
      T.eq(cfg:int("port"), 8080)
    end)

    T.it("int: returns integer from string", function()
      local env = { APP_PORT = "9090" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :env("APP")
      local v = cfg:int("port")
      T.eq(v, 9090)
    end)

    T.it("int: returns nil for missing key", function()
      local cfg = M.new()
      T.eq(cfg:int("port"), nil)
    end)

    T.it("int: returns nil+errmsg for non-numeric value", function()
      local cfg = M.new():defaults({ port = "nope" })
      local v, err = cfg:int("port")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)

    T.it("float: returns number", function()
      local cfg = M.new():defaults({ timeout = 1.5 })
      T.eq(cfg:float("timeout"), 1.5)
    end)

    T.it("float: coerces string", function()
      local cfg = M.new():defaults({ timeout = "2.5" })
      T.eq(cfg:float("timeout"), 2.5)
    end)

    T.it("string: returns tostring value", function()
      local cfg = M.new():defaults({ port = 8080 })
      T.eq(cfg:string("port"), "8080")
    end)

    T.it("string: returns nil for missing key", function()
      local cfg = M.new()
      T.eq(cfg:string("missing"), nil)
    end)

    T.it("bool: true literal", function()
      local cfg = M.new():defaults({ debug = true })
      T.eq(cfg:bool("debug"), true)
    end)

    T.it("bool: false literal", function()
      local cfg = M.new():defaults({ debug = false })
      T.eq(cfg:bool("debug"), false)
    end)

    T.it("bool: coerce 'true' string", function()
      local env = { APP_DEBUG = "true" }
      local cfg = M.new({ env_reader = function(n) return env[n] end }):env("APP")
      T.eq(cfg:bool("debug"), true)
    end)

    T.it("bool: coerce 'false' string", function()
      local env = { APP_DEBUG = "false" }
      local cfg = M.new({ env_reader = function(n) return env[n] end }):env("APP")
      T.eq(cfg:bool("debug"), false)
    end)

    T.it("bool: coerce '1' string", function()
      local env = { APP_DEBUG = "1" }
      local cfg = M.new({ env_reader = function(n) return env[n] end }):env("APP")
      T.eq(cfg:bool("debug"), true)
    end)

    T.it("bool: coerce '0' string", function()
      local env = { APP_DEBUG = "0" }
      local cfg = M.new({ env_reader = function(n) return env[n] end }):env("APP")
      T.eq(cfg:bool("debug"), false)
    end)

    T.it("bool: returns nil+errmsg for invalid string", function()
      local cfg = M.new():defaults({ debug = "yes" })
      local v, err = cfg:bool("debug")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)

    T.it("list: returns table as-is", function()
      local cfg = M.new():defaults({ tags = {"a", "b", "c"} })
      local v = cfg:list("tags")
      T.eq(#v, 3)
      T.eq(v[1], "a")
      T.eq(v[3], "c")
    end)

    T.it("list: splits comma-separated string", function()
      local cfg = M.new():defaults({ tags = "a,b,c" })
      local v = cfg:list("tags")
      T.eq(#v, 3)
      T.eq(v[1], "a")
      T.eq(v[2], "b")
    end)

    T.it("list: trims whitespace", function()
      local cfg = M.new():defaults({ tags = "a, b , c" })
      local v = cfg:list("tags")
      T.eq(v[2], "b")
    end)

    T.it("list: returns nil for missing key", function()
      local cfg = M.new()
      T.eq(cfg:list("tags"), nil)
    end)
  end)

  T.describe("require", function()
    T.it("returns value when present", function()
      local cfg = M.new():defaults({ port = 8080 })
      T.eq(cfg:require("port"), 8080)
    end)

    T.it("throws when key is missing", function()
      local cfg = M.new()
      T.throws(function() cfg:require("port") end)
    end)
  end)

  T.describe("namespace prefix", function()
    T.it("ns:get prepends prefix", function()
      local cfg = M.new():defaults({ ["db.host"] = "localhost" })
      local db = cfg:ns("db")
      T.eq(db:get("host"), "localhost")
    end)

    T.it("ns:get works with nested table", function()
      local cfg = M.new():defaults({ db = { host = "server1" } })
      local db = cfg:ns("db")
      T.eq(db:get("host"), "server1")
    end)

    T.it("ns does not leak keys without prefix", function()
      local cfg = M.new()
        :defaults({ port = 8080, ["db.host"] = "dbhost" })
      local db = cfg:ns("db")
      T.eq(db:get("port"), nil)
    end)

    T.it("ns:get forwards env reader", function()
      local env = { APP_DB_HOST = "envhost" }
      local cfg = M.new({ env_reader = function(n) return env[n] end }):env("APP")
      local db = cfg:ns("db")
      T.eq(db:get("host"), "envhost")
    end)
  end)

  T.describe("to_table", function()
    T.it("returns merged flat table", function()
      local cfg = M.new()
        :defaults({ port = 8080, host = "localhost" })
        :layer({ port = 9090 })
      local t = cfg:to_table()
      T.eq(t.port, 9090)
      T.eq(t.host, "localhost")
    end)

    T.it("later layer wins in to_table", function()
      local cfg = M.new()
        :defaults({ x = 1 })
        :layer({ x = 2 })
        :layer({ x = 3 })
      local t = cfg:to_table()
      T.eq(t.x, 3)
    end)

    T.it("args override in to_table", function()
      local cfg = M.new()
        :defaults({ port = 8080 })
        :args({ port = 1111 })
      local t = cfg:to_table()
      T.eq(t.port, 1111)
    end)

    T.it("env override in to_table for known keys", function()
      local env = { APP_PORT = "7777" }
      local cfg = M.new({ env_reader = function(n) return env[n] end })
        :defaults({ port = 8080 })
        :env("APP")
      local t = cfg:to_table()
      T.eq(t.port, "7777")
    end)
  end)

  T.describe("validate", function()
    T.it("passes when all required keys present", function()
      local cfg = M.new():defaults({ port = 8080, host = "localhost" })
      local ok, err = cfg:validate({ required = {"port", "host"} })
      T.eq(ok, true)
      T.eq(err, nil)
    end)

    T.it("fails when required key is missing", function()
      local cfg = M.new():defaults({ port = 8080 })
      local ok, err = cfg:validate({ required = {"port", "host"} })
      T.eq(ok, nil)
      T.ok(err ~= nil)
      T.ok(err:find("host") ~= nil)
    end)

    T.it("lists all missing keys in error message", function()
      local cfg = M.new()
      local ok, err = cfg:validate({ required = {"port", "host", "name"} })
      T.eq(ok, nil)
      T.ok(err:find("port") ~= nil)
      T.ok(err:find("host") ~= nil)
      T.ok(err:find("name") ~= nil)
    end)

    T.it("passes with correct types", function()
      local cfg = M.new():defaults({ port = 8080, debug = true })
      local ok = cfg:validate({ types = { port = "integer", debug = "boolean" } })
      T.eq(ok, true)
    end)

    T.it("fails on invalid integer type", function()
      local cfg = M.new():defaults({ port = "notanumber" })
      local ok, err = cfg:validate({ types = { port = "integer" } })
      T.eq(ok, nil)
      T.ok(err ~= nil)
    end)

    T.it("fails on invalid boolean type", function()
      local cfg = M.new():defaults({ debug = "yes" })
      local ok, err = cfg:validate({ types = { debug = "boolean" } })
      T.eq(ok, nil)
      T.ok(err ~= nil)
    end)

    T.it("combined required + types: all failures reported", function()
      local cfg = M.new():defaults({ debug = "badval" })
      local ok, err = cfg:validate({
        required = {"port"},
        types = { debug = "boolean" },
      })
      T.eq(ok, nil)
      T.ok(err:find("port") ~= nil)
      T.ok(err:find("debug") ~= nil)
    end)
  end)

  T.describe("dot-notation access", function()
    T.it("navigates nested tables", function()
      local cfg = M.new():defaults({ db = { host = "dbhost", port = 5432 } })
      T.eq(cfg:get("db.host"), "dbhost")
      T.eq(cfg:get("db.port"), 5432)
    end)

    T.it("flat dot-key takes priority over nested table", function()
      local cfg = M.new()
        :defaults({ db = { host = "nested" } })
        :layer({ ["db.host"] = "flat" })
      T.eq(cfg:get("db.host"), "flat")
    end)

    T.it("returns nil for missing nested key", function()
      local cfg = M.new():defaults({ db = { host = "dbhost" } })
      T.eq(cfg:get("db.port"), nil)
    end)
  end)

  T.describe("M._tier", function()
    T.it("is 'pure'", function()
      T.eq(M._tier, "pure")
    end)
  end)

end)
