if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local toml = require("lib.toml")
local T = require("lib.test.assert")

-- 1. Basic key-value
T.describe("basic key-value", function()
  T.it("parses simple string", function()
    local t = toml.decode('key = "value"')
    T.eq(t.key, "value")
  end)
  T.it("parses integer", function()
    local t = toml.decode("key = 42")
    T.eq(t.key, 42)
  end)
end)

-- 2. Dotted keys
T.describe("dotted keys", function()
  T.it("parses dotted key", function()
    local t = toml.decode("a.b.c = 1")
    T.eq(t.a.b.c, 1)
  end)
  T.it("merges dotted keys", function()
    local t = toml.decode("a.b = 1\na.c = 2")
    T.eq(t.a.b, 1)
    T.eq(t.a.c, 2)
  end)
end)

-- 3. Integer types
T.describe("integers", function()
  T.it("parses decimal", function()
    local t = toml.decode("x = 42")
    T.eq(t.x, 42)
  end)
  T.it("parses hex", function()
    local t = toml.decode("x = 0xDEAD")
    T.eq(t.x, 0xDEAD)
  end)
  T.it("parses octal", function()
    local t = toml.decode("x = 0o755")
    T.eq(t.x, 493)  -- 7*64 + 5*8 + 5
  end)
  T.it("parses binary", function()
    local t = toml.decode("x = 0b11010110")
    T.eq(t.x, 214)
  end)
  T.it("parses underscored integers", function()
    local t = toml.decode("x = 1_000_000")
    T.eq(t.x, 1000000)
  end)
  T.it("parses negative integers", function()
    local t = toml.decode("x = -17")
    T.eq(t.x, -17)
  end)
  T.it("parses positive integers", function()
    local t = toml.decode("x = +99")
    T.eq(t.x, 99)
  end)
end)

-- 4. Float types
T.describe("floats", function()
  T.it("parses standard float", function()
    local t = toml.decode("x = 3.14")
    T.ok(math.abs(t.x - 3.14) < 1e-10)
  end)
  T.it("parses exponent notation", function()
    local t = toml.decode("x = 5e+22")
    T.eq(t.x, 5e22)
  end)
  T.it("parses inf", function()
    local t = toml.decode("x = inf\ny = -inf\nz = +inf")
    T.eq(t.x, math.huge)
    T.eq(t.y, -math.huge)
    T.eq(t.z, math.huge)
  end)
  T.it("parses nan", function()
    local t = toml.decode("x = nan")
    T.ok(t.x ~= t.x, "nan ~= nan")
  end)
  T.it("parses underscored float", function()
    local t = toml.decode("x = 1_000.5")
    T.eq(t.x, 1000.5)
  end)
end)

-- 5. Booleans
T.describe("booleans", function()
  T.it("parses true and false", function()
    local t = toml.decode("a = true\nb = false")
    T.eq(t.a, true)
    T.eq(t.b, false)
  end)
end)

-- 6. Basic strings with escapes
T.describe("basic strings", function()
  T.it("handles escape sequences", function()
    local t = toml.decode('x = "hello\\nworld\\t!"')
    T.eq(t.x, "hello\nworld\t!")
  end)
  T.it("handles unicode escape \\u", function()
    local t = toml.decode('x = "\\u0041"')
    T.eq(t.x, "A")
  end)
  T.it("handles unicode escape \\U", function()
    local t = toml.decode('x = "\\U0001F600"')
    -- U+1F600 is the grinning face emoji
    T.eq(#t.x, 4)  -- 4 bytes in UTF-8
  end)
  T.it("handles backslash and quote escapes", function()
    local t = toml.decode('x = "a\\\\b\\"c"')
    T.eq(t.x, 'a\\b"c')
  end)
end)

-- 7. Literal strings
T.describe("literal strings", function()
  T.it("no escaping", function()
    local t = toml.decode("x = 'C:\\\\Users\\\\foo'")
    T.eq(t.x, "C:\\\\Users\\\\foo")
  end)
  T.it("preserves backslashes", function()
    local t = toml.decode("x = 'hello\\nworld'")
    T.eq(t.x, "hello\\nworld")
  end)
end)

-- 8. Multiline basic strings
T.describe("multiline basic strings", function()
  T.it("trims first newline", function()
    local t = toml.decode('x = """\nhello"""')
    T.eq(t.x, "hello")
  end)
  T.it("line ending backslash trims whitespace", function()
    local t = toml.decode('x = """\\\n  hello"""')
    T.eq(t.x, "hello")
  end)
end)

-- 9. Multiline literal strings
T.describe("multiline literal strings", function()
  T.it("trims first newline, preserves rest", function()
    local t = toml.decode("x = '''\nhello\nworld'''")
    T.eq(t.x, "hello\nworld")
  end)
end)

-- 10. Tables
T.describe("tables", function()
  T.it("parses [table] header", function()
    local t = toml.decode("[server]\nhost = \"localhost\"\nport = 8080")
    T.eq(t.server.host, "localhost")
    T.eq(t.server.port, 8080)
  end)
  T.it("parses nested [a.b]", function()
    local t = toml.decode("[a.b]\nc = 1")
    T.eq(t.a.b.c, 1)
  end)
end)

-- 11. Array of tables
T.describe("array of tables", function()
  T.it("parses [[products]]", function()
    local input = '[[products]]\nname = "Hammer"\n\n[[products]]\nname = "Nail"'
    local t = toml.decode(input)
    T.eq(#t.products, 2)
    T.eq(t.products[1].name, "Hammer")
    T.eq(t.products[2].name, "Nail")
  end)
end)

-- 12. Inline tables
T.describe("inline tables", function()
  T.it("parses inline table", function()
    local t = toml.decode("point = {x = 1, y = 2}")
    T.eq(t.point.x, 1)
    T.eq(t.point.y, 2)
  end)
  T.it("parses empty inline table", function()
    local t = toml.decode("empty = {}")
    T.ok(type(t.empty) == "table")
  end)
end)

-- 13. Arrays
T.describe("arrays", function()
  T.it("parses integer array", function()
    local t = toml.decode("arr = [1, 2, 3]")
    T.eq(#t.arr, 3)
    T.eq(t.arr[1], 1)
    T.eq(t.arr[3], 3)
  end)
  T.it("parses string array", function()
    local t = toml.decode('arr = ["a", "b"]')
    T.eq(t.arr[1], "a")
    T.eq(t.arr[2], "b")
  end)
  T.it("parses multiline array", function()
    local t = toml.decode("arr = [\n  1,\n  2,\n  3,\n]")
    T.eq(#t.arr, 3)
  end)
end)

-- 14. Mixed types in arrays (TOML v1.0 allows this)
T.describe("mixed arrays", function()
  T.it("allows mixed types", function()
    local t = toml.decode('arr = [1, "two", true]')
    T.eq(t.arr[1], 1)
    T.eq(t.arr[2], "two")
    T.eq(t.arr[3], true)
  end)
end)

-- 15. Datetime values
T.describe("datetime", function()
  T.it("parses offset datetime", function()
    local t = toml.decode("dt = 1979-05-27T07:32:00Z")
    T.eq(t.dt.__toml_type, "datetime")
    T.eq(t.dt.year, 1979)
    T.eq(t.dt.month, 5)
    T.eq(t.dt.day, 27)
    T.eq(t.dt.hour, 7)
    T.eq(t.dt.min, 32)
    T.eq(t.dt.sec, 0)
    T.eq(t.dt.tz, "Z")
  end)
  T.it("parses local date", function()
    local t = toml.decode("d = 1979-05-27")
    T.eq(t.d.__toml_type, "date-local")
    T.eq(t.d.year, 1979)
  end)
  T.it("parses local time", function()
    local t = toml.decode("t = 07:32:00")
    T.eq(t.t.__toml_type, "time-local")
    T.eq(t.t.hour, 7)
    T.eq(t.t.min, 32)
  end)
end)

-- 16. Comments
T.describe("comments", function()
  T.it("ignores comments", function()
    local t = toml.decode("# this is a comment\nkey = 42 # inline")
    T.eq(t.key, 42)
  end)
end)

-- 17. Round-trip
T.describe("round-trip", function()
  T.it("decode-encode-decode preserves structure", function()
    local input = 'name = "test"\nversion = 42\n\n[server]\nhost = "localhost"\nport = 8080\n'
    local t1 = toml.decode(input)
    T.ok(t1, "first decode")
    local encoded = toml.encode(t1)
    T.ok(encoded, "encode")
    local t2 = toml.decode(encoded)
    T.ok(t2, "second decode")
    T.eq(t2.name, t1.name)
    T.eq(t2.version, t1.version)
    T.eq(t2.server.host, t1.server.host)
    T.eq(t2.server.port, t1.server.port)
  end)
end)

-- 18. Error: duplicate key
T.describe("error: duplicate key", function()
  T.it("returns nil and error message", function()
    local val, err = toml.decode("x = 1\nx = 2")
    T.eq(val, nil)
    T.ok(err, "should have error message")
    T.ok(err:find("duplicate"), "error mentions duplicate: " .. tostring(err))
  end)
end)

-- 19. Error: malformed input with line number
T.describe("error: malformed input", function()
  T.it("returns nil with line number", function()
    local val, err = toml.decode("x = \n")
    T.eq(val, nil)
    T.ok(err, "should have error message")
    T.ok(err:find("line"), "error includes line: " .. tostring(err))
  end)
end)

-- 20. Nested tables and dotted keys combined
T.describe("nested + dotted", function()
  T.it("combines table headers and dotted keys", function()
    local input = "[a]\nb.c = 1\nb.d = 2"
    local t = toml.decode(input)
    T.eq(t.a.b.c, 1)
    T.eq(t.a.b.d, 2)
  end)
end)

-- 21. Empty table
T.describe("empty table", function()
  T.it("parses empty input", function()
    local t = toml.decode("")
    T.ok(type(t) == "table")
    T.eq(next(t), nil)
  end)
  T.it("parses empty table header", function()
    local t = toml.decode("[empty]")
    T.ok(type(t.empty) == "table")
    T.eq(next(t.empty), nil)
  end)
end)

-- 22. Encode: simple table
T.describe("encode simple", function()
  T.it("produces valid TOML", function()
    local s = toml.encode({name = "hello", count = 5, flag = true})
    T.ok(s:find('count = 5'), "has count")
    T.ok(s:find('flag = true'), "has flag")
    T.ok(s:find('name = "hello"'), "has name")
  end)
end)

-- 23. Encode: nested tables produce section headers
T.describe("encode nested", function()
  T.it("uses section headers for nested tables", function()
    local s = toml.encode({server = {host = "localhost", port = 8080}})
    T.ok(s:find("%[server%]"), "has [server] header")
    T.ok(s:find('host = "localhost"'), "has host")
    T.ok(s:find('port = 8080'), "has port")
  end)
end)

-- 24. Encode: array of tables
T.describe("encode array of tables", function()
  T.it("uses [[section]] for arrays of tables", function()
    local s = toml.encode({items = {{name = "a"}, {name = "b"}}})
    T.ok(s, "encode succeeded")
    local count = 0
    for _ in s:gmatch("%[%[items%]%]") do count = count + 1 end
    T.eq(count, 2, "two [[items]] headers")
  end)
end)

-- 25. Encode: datetime
T.describe("encode datetime", function()
  T.it("formats offset datetime", function()
    local dt = {__toml_type = "datetime", year = 1979, month = 5, day = 27,
                hour = 7, min = 32, sec = 0, tz = "Z"}
    local s = toml.encode({dt = dt})
    T.ok(s:find("1979%-05%-27T07:32:00Z"), "formatted datetime in output")
  end)
end)

-- 26. Quoted keys
T.describe("quoted keys", function()
  T.it("parses quoted keys", function()
    local t = toml.decode('"hello world" = 1')
    T.eq(t["hello world"], 1)
  end)
end)

-- 27. Alias names
T.describe("aliases", function()
  T.it("string_to_toml is decode", function()
    T.eq(toml.string_to_toml, toml.decode)
  end)
  T.it("toml_to_string is encode", function()
    T.eq(toml.toml_to_string, toml.encode)
  end)
end)
