if not package.path:find("?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local C = require("lib.canvas")

T.describe("canvas", function()

  T.it("_tier is pure", function()
    T.eq(C._tier, "pure")
  end)

  T.describe("new", function()
    T.it("has correct width and height", function()
      local cv = C.new(10, 20)
      T.eq(cv.width, 10)
      T.eq(cv.height, 20)
    end)

    T.it("default background is white", function()
      local cv = C.new(3, 3)
      local r, g, b, a = cv:get(0, 0)
      T.eq(r, 255)
      T.eq(g, 255)
      T.eq(b, 255)
      T.eq(a, 255)
    end)

    T.it("custom background color", function()
      local cv = C.new(5, 5, {background = {r=10, g=20, b=30, a=200}})
      local r, g, b, a = cv:get(2, 2)
      T.eq(r, 10)
      T.eq(g, 20)
      T.eq(b, 30)
      T.eq(a, 200)
    end)

    T.it("black background via background option", function()
      local cv = C.new(4, 4, {background = {r=0, g=0, b=0, a=255}})
      local r, g, b, a = cv:get(1, 1)
      T.eq(r, 0)
      T.eq(g, 0)
      T.eq(b, 0)
      T.eq(a, 255)
    end)
  end)

  T.describe("set/get", function()
    T.it("round-trips pixel values", function()
      local cv = C.new(10, 10)
      cv:set(3, 7, 100, 150, 200, 128)
      local r, g, b, a = cv:get(3, 7)
      T.eq(r, 100)
      T.eq(g, 150)
      T.eq(b, 200)
      T.eq(a, 128)
    end)

    T.it("alpha defaults to 255", function()
      local cv = C.new(5, 5)
      cv:set(1, 1, 10, 20, 30)
      local r, g, b, a = cv:get(1, 1)
      T.eq(r, 10)
      T.eq(g, 20)
      T.eq(b, 30)
      T.eq(a, 255)
    end)

    T.it("out-of-bounds get returns 0s", function()
      local cv = C.new(5, 5)
      local r, g, b, a = cv:get(10, 10)
      T.eq(r, 0)
      T.eq(g, 0)
      T.eq(b, 0)
      T.eq(a, 0)
    end)

    T.it("out-of-bounds set is a no-op", function()
      local cv = C.new(5, 5)
      cv:set(-1, -1, 0, 0, 0, 255)
      -- Should not error; canvas unchanged
      local r, g, b, a = cv:get(0, 0)
      T.eq(r, 255) -- still white background
    end)

    T.it("multiple pixels independent", function()
      local cv = C.new(10, 10)
      cv:set(0, 0, 1, 2, 3, 4)
      cv:set(9, 9, 5, 6, 7, 8)
      local r1, g1, b1, a1 = cv:get(0, 0)
      local r2, g2, b2, a2 = cv:get(9, 9)
      T.eq(r1, 1)
      T.eq(r2, 5)
      T.eq(a1, 4)
      T.eq(a2, 8)
    end)
  end)

  T.describe("line", function()
    T.it("sets endpoints", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:line(0, 0, 5, 5, 255, 0, 0, 255)
      local r0, g0, b0 = cv:get(0, 0)
      local r1, g1, b1 = cv:get(5, 5)
      T.eq(r0, 255)
      T.eq(r1, 255)
    end)

    T.it("horizontal line sets all pixels", function()
      local cv = C.new(20, 10, {background = {r=0, g=0, b=0, a=255}})
      cv:line(2, 3, 7, 3, 255, 255, 0, 255)
      for x = 2, 7 do
        local r = cv:get(x, 3)
        T.eq(r, 255)
      end
    end)

    T.it("vertical line sets all pixels", function()
      local cv = C.new(10, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:line(5, 2, 5, 8, 0, 255, 0, 255)
      for y = 2, 8 do
        local r, g = cv:get(5, y)
        T.eq(g, 255)
      end
    end)
  end)

  T.describe("fill_rect", function()
    T.it("all pixels in rect have correct color", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:fill_rect(2, 3, 5, 4, 200, 100, 50, 255)
      for py = 3, 6 do
        for px = 2, 6 do
          local r, g, b = cv:get(px, py)
          T.eq(r, 200)
          T.eq(g, 100)
          T.eq(b, 50)
        end
      end
    end)

    T.it("pixels outside rect unchanged", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:fill_rect(5, 5, 5, 5, 255, 0, 0, 255)
      local r = cv:get(0, 0)
      T.eq(r, 0)
    end)
  end)

  T.describe("rect outline", function()
    T.it("corners are set", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:rect(2, 2, 6, 6, 255, 255, 255, 255)
      local r, g, b = cv:get(2, 2)
      T.eq(r, 255)
      local r2 = cv:get(7, 7)
      T.eq(r2, 255)
    end)
  end)

  T.describe("circle", function()
    T.it("edge pixels are near the correct radius", function()
      local cv = C.new(50, 50, {background = {r=0, g=0, b=0, a=255}})
      local cx, cy, rad = 25, 25, 10
      cv:circle(cx, cy, rad, 255, 255, 255, 255)
      -- Check at least some pixels on cardinal axes
      local r1 = cv:get(cx + rad, cy)
      local r2 = cv:get(cx - rad, cy)
      local r3 = cv:get(cx, cy + rad)
      local r4 = cv:get(cx, cy - rad)
      T.eq(r1, 255)
      T.eq(r2, 255)
      T.eq(r3, 255)
      T.eq(r4, 255)
    end)
  end)

  T.describe("fill_circle", function()
    T.it("center pixel is filled", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:fill_circle(10, 10, 5, 255, 0, 0, 255)
      local r = cv:get(10, 10)
      T.eq(r, 255)
    end)

    T.it("outside pixel not filled", function()
      local cv = C.new(30, 30, {background = {r=0, g=0, b=0, a=255}})
      cv:fill_circle(15, 15, 5, 255, 0, 0, 255)
      local r = cv:get(25, 25)
      T.eq(r, 0)
    end)
  end)

  T.describe("triangle", function()
    T.it("fills interior pixels", function()
      local cv = C.new(30, 30, {background = {r=0, g=0, b=0, a=255}})
      cv:triangle(5, 5, 25, 5, 15, 20, 0, 255, 0, 255)
      -- The centroid should be inside
      local cx = math.floor((5 + 25 + 15) / 3)
      local cy = math.floor((5 + 5 + 20) / 3)
      local r, g = cv:get(cx, cy)
      T.eq(g, 255)
    end)
  end)

  T.describe("ellipse", function()
    T.it("draws points on major/minor axes", function()
      local cv = C.new(60, 60, {background = {r=0, g=0, b=0, a=255}})
      cv:ellipse(30, 30, 15, 10, 255, 0, 0, 255)
      -- Check endpoints on major axis
      local r1 = cv:get(30 + 15, 30)
      local r2 = cv:get(30 - 15, 30)
      T.eq(r1, 255)
      T.eq(r2, 255)
    end)
  end)

  T.describe("clear", function()
    T.it("fills entire canvas with new color", function()
      local cv = C.new(10, 10)
      cv:clear(0, 0, 0, 255)
      local r, g, b = cv:get(0, 0)
      T.eq(r, 0)
      T.eq(g, 0)
      T.eq(b, 0)
      local r2, g2, b2 = cv:get(9, 9)
      T.eq(r2, 0)
      T.eq(g2, 0)
      T.eq(b2, 0)
    end)
  end)

  T.describe("blit", function()
    T.it("copies pixels from other canvas at offset", function()
      local src = C.new(3, 3, {background = {r=100, g=150, b=200, a=255}})
      local dst = C.new(10, 10, {background = {r=0, g=0, b=0, a=255}})
      dst:blit(src, 2, 3)
      local r, g, b = dst:get(2, 3)
      T.eq(r, 100)
      T.eq(g, 150)
      T.eq(b, 200)
      -- Check last pixel of src
      local r2, g2, b2 = dst:get(4, 5)
      T.eq(r2, 100)
      T.eq(g2, 150)
      T.eq(b2, 200)
    end)

    T.it("pixels outside blit area unchanged", function()
      local src = C.new(2, 2, {background = {r=255, g=0, b=0, a=255}})
      local dst = C.new(10, 10, {background = {r=0, g=0, b=0, a=255}})
      dst:blit(src, 0, 0)
      local r = dst:get(5, 5)
      T.eq(r, 0)
    end)
  end)

  T.describe("crop", function()
    T.it("returns correct size", function()
      local cv = C.new(20, 20)
      local cropped = cv:crop(5, 5, 8, 6)
      T.eq(cropped.width, 8)
      T.eq(cropped.height, 6)
    end)

    T.it("has correct pixel values", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:set(5, 5, 100, 200, 50, 255)
      local cropped = cv:crop(5, 5, 3, 3)
      local r, g, b = cropped:get(0, 0)
      T.eq(r, 100)
      T.eq(g, 200)
      T.eq(b, 50)
    end)
  end)

  T.describe("scale", function()
    T.it("returns canvas of correct size", function()
      local cv = C.new(10, 10)
      local scaled = cv:scale(20, 30)
      T.eq(scaled.width, 20)
      T.eq(scaled.height, 30)
    end)

    T.it("scales down correctly", function()
      local cv = C.new(10, 10, {background = {r=128, g=64, b=32, a=255}})
      local scaled = cv:scale(5, 5)
      local r, g, b = scaled:get(0, 0)
      T.eq(r, 128)
      T.eq(g, 64)
      T.eq(b, 32)
    end)
  end)

  T.describe("flip_h", function()
    T.it("mirrors pixels horizontally", function()
      local cv = C.new(10, 10, {background = {r=0, g=0, b=0, a=255}})
      cv:set(0, 0, 255, 0, 0, 255)
      cv:set(9, 0, 0, 255, 0, 255)
      cv:flip_h()
      local r1, g1 = cv:get(0, 0)
      local r2, g2 = cv:get(9, 0)
      T.eq(r1, 0)
      T.eq(g1, 255)   -- was (9,0) before
      T.eq(r2, 255)   -- was (0,0) before
      T.eq(g2, 0)
    end)
  end)

  T.describe("flip_v", function()
    T.it("mirrors pixels vertically", function()
      local cv = C.new(10, 10, {background = {r=0, g=0, b=0, a=255}})
      cv:set(0, 0, 255, 0, 0, 255)
      cv:set(0, 9, 0, 255, 0, 255)
      cv:flip_v()
      local r1, g1 = cv:get(0, 0)
      local r2, g2 = cv:get(0, 9)
      T.eq(r1, 0)
      T.eq(g1, 255)
      T.eq(r2, 255)
      T.eq(g2, 0)
    end)
  end)

  T.describe("flood fill", function()
    T.it("fills connected region", function()
      local cv = C.new(10, 10, {background = {r=255, g=255, b=255, a=255}})
      -- Draw a 3x3 red square, then fill inside
      cv:fill_rect(0, 0, 10, 10, 0, 0, 0, 255)
      cv:fill_rect(2, 2, 6, 6, 255, 255, 255, 255)
      cv:fill(4, 4, 0, 255, 0, 255)
      local r, g, b = cv:get(4, 4)
      T.eq(g, 255)
      T.eq(r, 0)
    end)
  end)

  T.describe("to_ppm", function()
    T.it("starts with P6 header", function()
      local cv = C.new(4, 4)
      local ppm = cv:to_ppm()
      T.ok(ppm:sub(1, 2) == "P6")
    end)

    T.it("header contains dimensions", function()
      local cv = C.new(8, 6)
      local ppm = cv:to_ppm()
      T.ok(ppm:find("8 6", 1, true) ~= nil)
    end)

    T.it("correct total length", function()
      local cv = C.new(4, 4)
      local ppm = cv:to_ppm()
      local header = "P6\n4 4\n255\n"
      T.eq(#ppm, #header + 4 * 4 * 3)
    end)

    T.it("pixel data matches set pixel", function()
      local cv = C.new(2, 1, {background = {r=0, g=0, b=0, a=255}})
      cv:set(0, 0, 10, 20, 30, 255)
      local ppm = cv:to_ppm()
      local header = "P6\n2 1\n255\n"
      T.eq(ppm:byte(#header + 1), 10)
      T.eq(ppm:byte(#header + 2), 20)
      T.eq(ppm:byte(#header + 3), 30)
    end)
  end)

  T.describe("to_pgm", function()
    T.it("starts with P5 header", function()
      local cv = C.new(4, 4)
      local pgm = cv:to_pgm()
      T.ok(pgm:sub(1, 2) == "P5")
    end)

    T.it("correct total length", function()
      local cv = C.new(4, 4)
      local pgm = cv:to_pgm()
      local header = "P5\n4 4\n255\n"
      T.eq(#pgm, #header + 4 * 4)
    end)
  end)

  T.describe("to_bmp", function()
    T.it("starts with BM magic bytes", function()
      local cv = C.new(4, 4)
      local bmp = cv:to_bmp()
      T.ok(bmp:sub(1, 2) == "BM")
    end)

    T.it("file size field is correct", function()
      local cv = C.new(4, 4)
      local bmp = cv:to_bmp()
      -- File size at bytes 3-6 (little-endian)
      local sz = bmp:byte(3) + bmp:byte(4)*256 + bmp:byte(5)*65536 + bmp:byte(6)*16777216
      T.eq(sz, #bmp)
    end)

    T.it("pixel data offset is 54", function()
      local cv = C.new(4, 4)
      local bmp = cv:to_bmp()
      local offset = bmp:byte(11) + bmp:byte(12)*256 + bmp:byte(13)*65536 + bmp:byte(14)*16777216
      T.eq(offset, 54)
    end)

    T.it("minimum valid size", function()
      local cv = C.new(1, 1)
      local bmp = cv:to_bmp()
      T.ok(#bmp >= 54)
    end)
  end)

  T.describe("text", function()
    T.it("renders some pixels for letter A", function()
      local cv = C.new(20, 20, {background = {r=0, g=0, b=0, a=255}})
      cv:text(0, 0, "A", 255, 255, 255, 255)
      -- A is a wide character — should have some white pixels in rows 0-6
      local found = false
      for py = 0, 6 do
        for px = 0, 4 do
          local r = cv:get(px, py)
          if r == 255 then found = true end
        end
      end
      T.ok(found, "letter A rendered no pixels")
    end)

    T.it("renders different pixels for different chars", function()
      local cv1 = C.new(10, 10, {background = {r=0, g=0, b=0, a=255}})
      local cv2 = C.new(10, 10, {background = {r=0, g=0, b=0, a=255}})
      cv1:text(0, 0, "A", 255, 255, 255, 255)
      cv2:text(0, 0, "B", 255, 255, 255, 255)
      -- At least one pixel should differ
      local differ = false
      for py = 0, 6 do
        for px = 0, 4 do
          local r1 = cv1:get(px, py)
          local r2 = cv2:get(px, py)
          if r1 ~= r2 then differ = true end
        end
      end
      T.ok(differ, "A and B rendered identical pixels")
    end)
  end)

  T.describe("text_size", function()
    T.it("returns positive width and height for non-empty string", function()
      local sz = C.text_size("Hello")
      T.ok(sz.w > 0, "width should be positive")
      T.ok(sz.h > 0, "height should be positive")
    end)

    T.it("width scales with string length", function()
      local sz1 = C.text_size("A")
      local sz2 = C.text_size("AB")
      T.ok(sz2.w > sz1.w, "longer string should be wider")
    end)

    T.it("height is constant regardless of length", function()
      local sz1 = C.text_size("A")
      local sz2 = C.text_size("Hello World")
      T.eq(sz1.h, sz2.h)
    end)

    T.it("empty string returns zero size", function()
      local sz = C.text_size("")
      T.eq(sz.w, 0)
      T.eq(sz.h, 0)
    end)
  end)

  T.describe("from_raw", function()
    T.it("constructs canvas from raw RGB bytes", function()
      -- 2x1 canvas, RGB
      local bytes = string.char(10, 20, 30, 40, 50, 60)
      local cv = C.from_raw(2, 1, bytes, 3)
      local r1, g1, b1, a1 = cv:get(0, 0)
      local r2, g2, b2 = cv:get(1, 0)
      T.eq(r1, 10)
      T.eq(g1, 20)
      T.eq(b1, 30)
      T.eq(a1, 255)  -- alpha defaults to 255 for RGB
      T.eq(r2, 40)
      T.eq(g2, 50)
      T.eq(b2, 60)
    end)

    T.it("constructs canvas from raw RGBA bytes", function()
      local bytes = string.char(1, 2, 3, 128)
      local cv = C.from_raw(1, 1, bytes, 4)
      local r, g, b, a = cv:get(0, 0)
      T.eq(r, 1)
      T.eq(g, 2)
      T.eq(b, 3)
      T.eq(a, 128)
    end)
  end)

end)
