if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local json = require("lib.json")
local T = require("lib.test.assert")

-- ── Metadata ──────────────────────────────────────────────────────────────────

T.describe("metadata", function()
	T.it("_tier is pure", function()
		T.eq(json._tier, "pure")
	end)
	T.it("aliases are set", function()
		T.eq(json.parse, json.decode)
		T.eq(json.stringify, json.encode)
		T.eq(json.json_to_string, json.decode)
		T.eq(json.string_to_json, json.encode)
	end)
	T.it("null sentinel is a table", function()
		T.eq(type(json.null), "table")
		T.neq(json.null, nil)
	end)
end)

-- ── Decode: scalars ───────────────────────────────────────────────────────────

T.describe("decode scalars", function()
	T.it("null", function()
		local v, err = json.decode("null")
		T.eq(err, nil)
		T.eq(v, json.null)
	end)
	T.it("true", function()
		local v, err = json.decode("true")
		T.eq(err, nil)
		T.eq(v, true)
	end)
	T.it("false", function()
		local v, err = json.decode("false")
		T.eq(err, nil)
		T.eq(v, false)
	end)
	T.it("integer zero", function()
		local v, err = json.decode("0")
		T.eq(err, nil)
		T.eq(v, 0)
	end)
	T.it("positive integer", function()
		local v, err = json.decode("42")
		T.eq(err, nil)
		T.eq(v, 42)
	end)
	T.it("negative integer", function()
		local v, err = json.decode("-7")
		T.eq(err, nil)
		T.eq(v, -7)
	end)
	T.it("float", function()
		local v, err = json.decode("3.14")
		T.eq(err, nil)
		T.ok(math.abs(v - 3.14) < 1e-10)
	end)
	T.it("negative float", function()
		local v, err = json.decode("-0.5")
		T.eq(err, nil)
		T.eq(v, -0.5)
	end)
	T.it("exponent lowercase e", function()
		local v, err = json.decode("1e2")
		T.eq(err, nil)
		T.eq(v, 100)
	end)
	T.it("exponent uppercase E", function()
		local v, err = json.decode("1E2")
		T.eq(err, nil)
		T.eq(v, 100)
	end)
	T.it("positive exponent with sign", function()
		local v, err = json.decode("2.5e+3")
		T.eq(err, nil)
		T.eq(v, 2500)
	end)
	T.it("negative exponent", function()
		local v, err = json.decode("1e-3")
		T.eq(err, nil)
		T.ok(math.abs(v - 0.001) < 1e-10)
	end)
	T.it("large integer", function()
		local v, err = json.decode("1000000")
		T.eq(err, nil)
		T.eq(v, 1000000)
	end)
	T.it("empty string", function()
		local v, err = json.decode('""')
		T.eq(err, nil)
		T.eq(v, "")
	end)
	T.it("simple string", function()
		local v, err = json.decode('"hello"')
		T.eq(err, nil)
		T.eq(v, "hello")
	end)
	T.it("string with spaces", function()
		local v, err = json.decode('"hello world"')
		T.eq(err, nil)
		T.eq(v, "hello world")
	end)
end)

-- ── Decode: string escapes ────────────────────────────────────────────────────

T.describe("decode string escapes", function()
	T.it("\\n", function()
		local v, err = json.decode('"\\n"')
		T.eq(err, nil)
		T.eq(v, "\n")
	end)
	T.it("\\t", function()
		local v, err = json.decode('"\\t"')
		T.eq(err, nil)
		T.eq(v, "\t")
	end)
	T.it("\\r", function()
		local v, err = json.decode('"\\r"')
		T.eq(err, nil)
		T.eq(v, "\r")
	end)
	T.it("\\\\", function()
		local v, err = json.decode('"\\\\"')
		T.eq(err, nil)
		T.eq(v, "\\")
	end)
	T.it('\\"', function()
		local v, err = json.decode('"\\""')
		T.eq(err, nil)
		T.eq(v, '"')
	end)
	T.it("\\/", function()
		local v, err = json.decode('"\\/"')
		T.eq(err, nil)
		T.eq(v, "/")
	end)
	T.it("\\b", function()
		local v, err = json.decode('"\\b"')
		T.eq(err, nil)
		T.eq(v, "\b")
	end)
	T.it("\\f", function()
		local v, err = json.decode('"\\f"')
		T.eq(err, nil)
		T.eq(v, "\f")
	end)
	T.it("\\u0041 (A)", function()
		local v, err = json.decode('"\\u0041"')
		T.eq(err, nil)
		T.eq(v, "A")
	end)
	T.it("\\u0000 (NUL)", function()
		local v, err = json.decode('"\\u0000"')
		T.eq(err, nil)
		T.eq(v, "\0")
	end)
	T.it("\\u00E9 (é)", function()
		local v, err = json.decode('"\\u00E9"')
		T.eq(err, nil)
		T.eq(v, "\xC3\xA9")  -- UTF-8 for U+00E9
	end)
	T.it("\\u20AC (euro sign)", function()
		local v, err = json.decode('"\\u20AC"')
		T.eq(err, nil)
		T.eq(v, "\xE2\x82\xAC")  -- UTF-8 for U+20AC
	end)
	T.it("surrogate pair \\uD83D\\uDE00 (😀)", function()
		local v, err = json.decode('"\\uD83D\\uDE00"')
		T.eq(err, nil)
		T.eq(v, "\xF0\x9F\x98\x80")  -- UTF-8 for U+1F600
	end)
	T.it("multiple escapes in one string", function()
		local v, err = json.decode('"a\\nb\\tc"')
		T.eq(err, nil)
		T.eq(v, "a\nb\tc")
	end)
	T.it("lowercase hex in \\uXXXX", function()
		local v, err = json.decode('"\\u0061"')  -- 'a'
		T.eq(err, nil)
		T.eq(v, "a")
	end)
end)

-- ── Decode: arrays ────────────────────────────────────────────────────────────

T.describe("decode arrays", function()
	T.it("empty array", function()
		local v, err = json.decode("[]")
		T.eq(err, nil)
		T.eq(type(v), "table")
		T.eq(#v, 0)
	end)
	T.it("single element", function()
		local v, err = json.decode("[1]")
		T.eq(err, nil)
		T.eq(#v, 1)
		T.eq(v[1], 1)
	end)
	T.it("multiple elements", function()
		local v, err = json.decode("[1,2,3]")
		T.eq(err, nil)
		T.eq(#v, 3)
		T.eq(v[1], 1)
		T.eq(v[2], 2)
		T.eq(v[3], 3)
	end)
	T.it("mixed types", function()
		local v, err = json.decode('[1,"two",true,null]')
		T.eq(err, nil)
		T.eq(#v, 4)
		T.eq(v[1], 1)
		T.eq(v[2], "two")
		T.eq(v[3], true)
		T.eq(v[4], json.null)
	end)
	T.it("nested arrays", function()
		local v, err = json.decode("[[1,2],[3,4]]")
		T.eq(err, nil)
		T.eq(#v, 2)
		T.eq(v[1][1], 1)
		T.eq(v[1][2], 2)
		T.eq(v[2][1], 3)
		T.eq(v[2][2], 4)
	end)
	T.it("array with whitespace", function()
		local v, err = json.decode("[ 1 , 2 , 3 ]")
		T.eq(err, nil)
		T.eq(#v, 3)
	end)
	T.it("array with newlines", function()
		local v, err = json.decode("[\n  1,\n  2\n]")
		T.eq(err, nil)
		T.eq(#v, 2)
	end)
end)

-- ── Decode: objects ───────────────────────────────────────────────────────────

T.describe("decode objects", function()
	T.it("empty object", function()
		local v, err = json.decode("{}")
		T.eq(err, nil)
		T.eq(type(v), "table")
		T.eq(next(v), nil)
	end)
	T.it("single key", function()
		local v, err = json.decode('{"a":1}')
		T.eq(err, nil)
		T.eq(v.a, 1)
	end)
	T.it("multiple keys", function()
		local v, err = json.decode('{"x":1,"y":2,"z":3}')
		T.eq(err, nil)
		T.eq(v.x, 1)
		T.eq(v.y, 2)
		T.eq(v.z, 3)
	end)
	T.it("nested object", function()
		local v, err = json.decode('{"a":{"b":42}}')
		T.eq(err, nil)
		T.eq(v.a.b, 42)
	end)
	T.it("object with array value", function()
		local v, err = json.decode('{"nums":[1,2,3]}')
		T.eq(err, nil)
		T.eq(#v.nums, 3)
		T.eq(v.nums[2], 2)
	end)
	T.it("object with whitespace", function()
		local v, err = json.decode('{ "a" : 1 , "b" : 2 }')
		T.eq(err, nil)
		T.eq(v.a, 1)
		T.eq(v.b, 2)
	end)
	T.it("string value in object", function()
		local v, err = json.decode('{"name":"alice"}')
		T.eq(err, nil)
		T.eq(v.name, "alice")
	end)
	T.it("boolean and null values", function()
		local v, err = json.decode('{"ok":true,"missing":null}')
		T.eq(err, nil)
		T.eq(v.ok, true)
		T.eq(v.missing, json.null)
	end)
end)

-- ── Decode: whitespace handling ───────────────────────────────────────────────

T.describe("decode whitespace", function()
	T.it("leading whitespace", function()
		local v, err = json.decode("   42")
		T.eq(err, nil)
		T.eq(v, 42)
	end)
	T.it("trailing whitespace", function()
		local v, err = json.decode("42   ")
		T.eq(err, nil)
		T.eq(v, 42)
	end)
	T.it("tabs and newlines", function()
		local v, err = json.decode("\t\n42\r\n")
		T.eq(err, nil)
		T.eq(v, 42)
	end)
end)

-- ── Decode: error cases ───────────────────────────────────────────────────────

T.describe("decode errors", function()
	T.it("unclosed string", function()
		local v, err = json.decode('"hello')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("trailing comma in array", function()
		local v, err = json.decode("[1,2,]")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("trailing comma in object", function()
		local v, err = json.decode('{"a":1,}')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("invalid escape sequence", function()
		local v, err = json.decode('"\\x41"')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("incomplete \\uXXXX", function()
		local v, err = json.decode('"\\u004"')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("invalid hex in \\uXXXX", function()
		local v, err = json.decode('"\\uGGGG"')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("bare string (no quotes)", function()
		local v, err = json.decode("hello")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("unclosed array", function()
		local v, err = json.decode("[1,2")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("unclosed object", function()
		local v, err = json.decode('{"a":1')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("empty input", function()
		local v, err = json.decode("")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("trailing content after value", function()
		local v, err = json.decode("42 garbage")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("missing colon in object", function()
		local v, err = json.decode('{"a" 1}')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("non-string key in object", function()
		local v, err = json.decode("{1:2}")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("unescaped control character in string", function()
		local v, err = json.decode('"hello\nworld"')
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("non-string argument returns error", function()
		local v, err = json.decode(42)
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("whitespace only", function()
		local v, err = json.decode("   ")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
end)

-- ── Encode: scalars ───────────────────────────────────────────────────────────

T.describe("encode scalars", function()
	T.it("null sentinel", function()
		local s, err = json.encode(json.null)
		T.eq(err, nil)
		T.eq(s, "null")
	end)
	T.it("nil encodes as null", function()
		local s, err = json.encode(nil)
		T.eq(err, nil)
		T.eq(s, "null")
	end)
	T.it("true", function()
		local s, err = json.encode(true)
		T.eq(err, nil)
		T.eq(s, "true")
	end)
	T.it("false", function()
		local s, err = json.encode(false)
		T.eq(err, nil)
		T.eq(s, "false")
	end)
	T.it("zero", function()
		local s, err = json.encode(0)
		T.eq(err, nil)
		T.eq(s, "0")
	end)
	T.it("positive integer", function()
		local s, err = json.encode(42)
		T.eq(err, nil)
		T.eq(s, "42")
	end)
	T.it("negative integer", function()
		local s, err = json.encode(-7)
		T.eq(err, nil)
		T.eq(s, "-7")
	end)
	T.it("float", function()
		local s, err = json.encode(3.14)
		T.eq(err, nil)
		T.ok(s ~= nil)
		-- should parse back to approximately 3.14
		local v = tonumber(s)
		T.ok(math.abs(v - 3.14) < 1e-10)
	end)
	T.it("large integer", function()
		local s, err = json.encode(1000000)
		T.eq(err, nil)
		T.eq(s, "1000000")
	end)
	T.it("empty string", function()
		local s, err = json.encode("")
		T.eq(err, nil)
		T.eq(s, '""')
	end)
	T.it("simple string", function()
		local s, err = json.encode("hello")
		T.eq(err, nil)
		T.eq(s, '"hello"')
	end)
	T.it("string with quote", function()
		local s, err = json.encode('say "hi"')
		T.eq(err, nil)
		T.eq(s, '"say \\"hi\\""')
	end)
	T.it("string with backslash", function()
		local s, err = json.encode("a\\b")
		T.eq(err, nil)
		T.eq(s, '"a\\\\b"')
	end)
	T.it("string with newline", function()
		local s, err = json.encode("a\nb")
		T.eq(err, nil)
		T.eq(s, '"a\\nb"')
	end)
	T.it("string with tab", function()
		local s, err = json.encode("a\tb")
		T.eq(err, nil)
		T.eq(s, '"a\\tb"')
	end)
	T.it("string with carriage return", function()
		local s, err = json.encode("a\rb")
		T.eq(err, nil)
		T.eq(s, '"a\\rb"')
	end)
	T.it("NaN returns error", function()
		local s, err = json.encode(0/0)
		T.eq(s, nil)
		T.ok(err ~= nil)
	end)
	T.it("Infinity returns error", function()
		local s, err = json.encode(math.huge)
		T.eq(s, nil)
		T.ok(err ~= nil)
	end)
	T.it("-Infinity returns error", function()
		local s, err = json.encode(-math.huge)
		T.eq(s, nil)
		T.ok(err ~= nil)
	end)
	T.it("unsupported type returns error", function()
		local s, err = json.encode(function() end)
		T.eq(s, nil)
		T.ok(err ~= nil)
	end)
end)

-- ── Encode: arrays and objects ────────────────────────────────────────────────

T.describe("encode arrays", function()
	T.it("empty array", function()
		local s, err = json.encode({})
		T.eq(err, nil)
		T.eq(s, "[]")
	end)
	T.it("single element", function()
		local s, err = json.encode({1})
		T.eq(err, nil)
		T.eq(s, "[1]")
	end)
	T.it("multiple elements", function()
		local s, err = json.encode({1, 2, 3})
		T.eq(err, nil)
		T.eq(s, "[1,2,3]")
	end)
	T.it("mixed types", function()
		local s, err = json.encode({1, "two", true, json.null})
		T.eq(err, nil)
		T.eq(s, '[1,"two",true,null]')
	end)
	T.it("nested array", function()
		local s, err = json.encode({{1,2},{3,4}})
		T.eq(err, nil)
		T.eq(s, "[[1,2],[3,4]]")
	end)
end)

T.describe("encode objects", function()
	T.it("single key", function()
		local s, err = json.encode({a = 1})
		T.eq(err, nil)
		T.eq(s, '{"a":1}')
	end)
	T.it("nested object", function()
		local s, err = json.encode({a = {b = 42}})
		T.eq(err, nil)
		T.eq(s, '{"a":{"b":42}}')
	end)
	T.it("object with array", function()
		local s, err = json.encode({nums = {1, 2, 3}})
		T.eq(err, nil)
		T.eq(s, '{"nums":[1,2,3]}')
	end)
end)

-- ── Encode: sort_keys ─────────────────────────────────────────────────────────

T.describe("encode sort_keys", function()
	T.it("sorts keys alphabetically", function()
		local s, err = json.encode({z = 3, a = 1, m = 2}, {sort_keys = true})
		T.eq(err, nil)
		T.eq(s, '{"a":1,"m":2,"z":3}')
	end)
	T.it("no sort by default (order unspecified)", function()
		-- Just check it encodes successfully with multiple keys
		local s, err = json.encode({a = 1, b = 2})
		T.eq(err, nil)
		T.ok(s ~= nil)
	end)
	T.it("sort_keys with nested objects", function()
		local s, err = json.encode({b = {z = 1, a = 2}, a = 0}, {sort_keys = true})
		T.eq(err, nil)
		T.eq(s, '{"a":0,"b":{"a":2,"z":1}}')
	end)
end)

-- ── Encode: indent ────────────────────────────────────────────────────────────

T.describe("encode indent", function()
	T.it("array with indent=2", function()
		local s, err = json.encode({1, 2}, {indent = 2})
		T.eq(err, nil)
		T.eq(s, "[\n  1,\n  2\n]")
	end)
	T.it("object with indent=2 and sort_keys", function()
		local s, err = json.encode({b = 2, a = 1}, {indent = 2, sort_keys = true})
		T.eq(err, nil)
		T.eq(s, '{\n  "a": 1,\n  "b": 2\n}')
	end)
	T.it("indent=4", function()
		local s, err = json.encode({1}, {indent = 4})
		T.eq(err, nil)
		T.eq(s, "[\n    1\n]")
	end)
	T.it("nested with indent", function()
		local s, err = json.encode({{1}}, {indent = 2})
		T.eq(err, nil)
		T.eq(s, "[\n  [\n    1\n  ]\n]")
	end)
	T.it("empty array with indent", function()
		local s, err = json.encode({}, {indent = 2})
		T.eq(err, nil)
		T.eq(s, "[]")
	end)
end)

-- ── Round-trip ────────────────────────────────────────────────────────────────

T.describe("round-trip", function()
	local function rt(input)
		local val, err = json.decode(input)
		if err then return nil, "decode: " .. err end
		local out, err2 = json.encode(val)
		if err2 then return nil, "encode: " .. err2 end
		return out, nil
	end

	T.it("null", function()
		local s, err = rt("null")
		T.eq(err, nil)
		T.eq(s, "null")
	end)
	T.it("true", function()
		local s, err = rt("true")
		T.eq(err, nil)
		T.eq(s, "true")
	end)
	T.it("false", function()
		local s, err = rt("false")
		T.eq(err, nil)
		T.eq(s, "false")
	end)
	T.it("integer", function()
		local s, err = rt("123")
		T.eq(err, nil)
		T.eq(s, "123")
	end)
	T.it("negative integer", function()
		local s, err = rt("-99")
		T.eq(err, nil)
		T.eq(s, "-99")
	end)
	T.it("string", function()
		local s, err = rt('"hello"')
		T.eq(err, nil)
		T.eq(s, '"hello"')
	end)
	T.it("string with escapes", function()
		local s, err = rt('"line1\\nline2"')
		T.eq(err, nil)
		T.eq(s, '"line1\\nline2"')
	end)
	T.it("empty array", function()
		local s, err = rt("[]")
		T.eq(err, nil)
		T.eq(s, "[]")
	end)
	T.it("array of numbers", function()
		local s, err = rt("[1,2,3]")
		T.eq(err, nil)
		T.eq(s, "[1,2,3]")
	end)
	T.it("empty object/array (both encode as [])", function()
		-- An empty Lua table has no keys; Lua cannot distinguish {} from [].
		-- decode("{}") gives an empty table, which re-encodes as "[]".
		local s, err = rt("{}")
		T.eq(err, nil)
		T.eq(s, "[]")
	end)
	T.it("nested structure", function()
		local input = '{"a":[1,2],"b":{"c":true}}'
		local val, _ = json.decode(input)
		local s, err = json.encode(val, {sort_keys = true})
		T.eq(err, nil)
		T.eq(s, '{"a":[1,2],"b":{"c":true}}')
	end)
	T.it("decode then encode string with quote", function()
		local v, _ = json.decode('"say \\"hi\\""')
		local s, err = json.encode(v)
		T.eq(err, nil)
		T.eq(s, '"say \\"hi\\""')
	end)
end)

-- ── Edge cases ────────────────────────────────────────────────────────────────

T.describe("edge cases", function()
	T.it("very large number", function()
		local v, err = json.decode("1e308")
		T.eq(err, nil)
		T.ok(v > 1e307)
	end)
	T.it("number with leading minus only is error", function()
		local v, err = json.decode("-")
		T.eq(v, nil)
		T.ok(err ~= nil)
	end)
	T.it("string with only escapes", function()
		local v, err = json.decode('"\\n\\t\\r"')
		T.eq(err, nil)
		T.eq(v, "\n\t\r")
	end)
	T.it("deeply nested array", function()
		local s = "[[[[1]]]]"
		local v, err = json.decode(s)
		T.eq(err, nil)
		T.eq(v[1][1][1][1], 1)
	end)
	T.it("unicode passthrough in string", function()
		-- Non-ASCII bytes not requiring escape pass through as-is
		local v, err = json.decode('"\xC3\xA9"')  -- UTF-8 é
		T.eq(err, nil)
		T.eq(v, "\xC3\xA9")
	end)
	T.it("integer zero round-trip", function()
		local s, err = json.encode(0)
		T.eq(err, nil)
		T.eq(s, "0")
	end)
	T.it("negative zero encodes as 0", function()
		local s, err = json.encode(-0.0)
		T.eq(err, nil)
		T.eq(s, "0")
	end)
	T.it("string with control chars gets escaped on encode", function()
		local s, err = json.encode("a\x01b")
		T.eq(err, nil)
		T.eq(s, '"a\\u0001b"')
	end)
	T.it("number 1.0 encodes as integer", function()
		local s, err = json.encode(1.0)
		T.eq(err, nil)
		T.eq(s, "1")
	end)
	T.it("number -1.0 encodes as integer", function()
		local s, err = json.encode(-1.0)
		T.eq(err, nil)
		T.eq(s, "-1")
	end)
	T.it("null in array round-trips", function()
		local v, err = json.decode("[null,null]")
		T.eq(err, nil)
		T.eq(v[1], json.null)
		T.eq(v[2], json.null)
		local s, err2 = json.encode(v)
		T.eq(err2, nil)
		T.eq(s, "[null,null]")
	end)
	T.it("0.1 + 0.2 float", function()
		local s, err = json.encode(0.1)
		T.eq(err, nil)
		T.ok(s ~= nil)
		local v = tonumber(s)
		T.ok(math.abs(v - 0.1) < 1e-15)
	end)
end)
