if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local trie = require("lib.trie")

T.describe("trie", function()

  T.describe("new", function()
    T.it("creates an empty trie", function()
      local t = trie.new()
      T.eq(t:size(), 0)
    end)
  end)

  T.describe("insert and get", function()
    T.it("inserts and retrieves a value", function()
      local t = trie.new()
      t:insert("hello", 42)
      T.eq(t:get("hello"), 42)
    end)

    T.it("defaults value to true", function()
      local t = trie.new()
      t:insert("key")
      T.eq(t:get("key"), true)
    end)

    T.it("returns nil for missing key", function()
      local t = trie.new()
      T.eq(t:get("nope"), nil)
    end)

    T.it("overwrites existing value", function()
      local t = trie.new()
      t:insert("k", 1)
      t:insert("k", 2)
      T.eq(t:get("k"), 2)
      T.eq(t:size(), 1)
    end)

    T.it("handles empty string key", function()
      local t = trie.new()
      t:insert("", "root")
      T.eq(t:get(""), "root")
      T.eq(t:size(), 1)
    end)

    T.it("returns error for non-string key", function()
      local t = trie.new()
      local ok, err = t:insert(123)
      T.eq(ok, nil)
      T.ok(err)
    end)
  end)

  T.describe("has", function()
    T.it("returns true for existing key", function()
      local t = trie.new()
      t:insert("abc")
      T.ok(t:has("abc"))
    end)

    T.it("returns false for missing key", function()
      local t = trie.new()
      T.eq(t:has("abc"), false)
    end)

    T.it("returns false for prefix of existing key", function()
      local t = trie.new()
      t:insert("abc")
      T.eq(t:has("ab"), false)
    end)
  end)

  T.describe("remove", function()
    T.it("removes an existing key", function()
      local t = trie.new()
      t:insert("foo", 10)
      local old = t:remove("foo")
      T.eq(old, 10)
      T.eq(t:has("foo"), false)
      T.eq(t:size(), 0)
    end)

    T.it("returns nil for non-existent key", function()
      local t = trie.new()
      T.eq(t:remove("bar"), nil)
    end)

    T.it("does not affect other keys", function()
      local t = trie.new()
      t:insert("ab", 1)
      t:insert("abc", 2)
      t:insert("abcd", 3)
      t:remove("abc")
      T.eq(t:get("ab"), 1)
      T.eq(t:get("abc"), nil)
      T.eq(t:get("abcd"), 3)
      T.eq(t:size(), 2)
    end)

    T.it("remove middle of overlapping prefixes", function()
      local t = trie.new()
      t:insert("a", 1)
      t:insert("ab", 2)
      t:insert("abc", 3)
      t:remove("ab")
      T.ok(t:has("a"))
      T.eq(t:has("ab"), false)
      T.ok(t:has("abc"))
      T.eq(t:size(), 2)
    end)
  end)

  T.describe("size", function()
    T.it("tracks inserts and removes", function()
      local t = trie.new()
      T.eq(t:size(), 0)
      t:insert("a")
      T.eq(t:size(), 1)
      t:insert("b")
      T.eq(t:size(), 2)
      t:remove("a")
      T.eq(t:size(), 1)
    end)
  end)

  T.describe("has_prefix", function()
    T.it("returns true when keys share prefix", function()
      local t = trie.new()
      t:insert("apple")
      t:insert("app")
      T.ok(t:has_prefix("ap"))
      T.ok(t:has_prefix("app"))
      T.ok(t:has_prefix("apple"))
    end)

    T.it("returns false for unmatched prefix", function()
      local t = trie.new()
      t:insert("apple")
      T.eq(t:has_prefix("ban"), false)
    end)

    T.it("returns true for empty prefix when trie has keys", function()
      local t = trie.new()
      t:insert("x")
      T.ok(t:has_prefix(""))
    end)

    T.it("returns false for empty trie", function()
      local t = trie.new()
      T.eq(t:has_prefix(""), false)
    end)
  end)

  T.describe("find_prefix", function()
    T.it("finds all keys with prefix", function()
      local t = trie.new()
      t:insert("cat", 1)
      t:insert("car", 2)
      t:insert("card", 3)
      t:insert("dog", 4)
      local results = t:find_prefix("car")
      T.eq(#results, 2)
      T.eq(results[1][1], "car")
      T.eq(results[1][2], 2)
      T.eq(results[2][1], "card")
      T.eq(results[2][2], 3)
    end)

    T.it("returns empty for no match", function()
      local t = trie.new()
      t:insert("abc")
      T.eq(#t:find_prefix("xyz"), 0)
    end)
  end)

  T.describe("count_prefix", function()
    T.it("counts keys with prefix", function()
      local t = trie.new()
      t:insert("tea")
      t:insert("team")
      t:insert("tear")
      t:insert("ten")
      T.eq(t:count_prefix("tea"), 3)
      T.eq(t:count_prefix("te"), 4)
      T.eq(t:count_prefix("ten"), 1)
      T.eq(t:count_prefix("z"), 0)
    end)
  end)

  T.describe("longest_prefix", function()
    T.it("finds longest key that is prefix of input", function()
      local t = trie.new()
      t:insert("/", "root")
      t:insert("/api", "api")
      t:insert("/api/users", "users")
      local key, val = t:longest_prefix("/api/users/123")
      T.eq(key, "/api/users")
      T.eq(val, "users")
    end)

    T.it("returns nil when no prefix matches", function()
      local t = trie.new()
      t:insert("abc")
      T.eq(t:longest_prefix("xyz"), nil)
    end)

    T.it("matches empty string key as prefix", function()
      local t = trie.new()
      t:insert("", "fallback")
      local key, val = t:longest_prefix("anything")
      T.eq(key, "")
      T.eq(val, "fallback")
    end)

    T.it("returns exact match when it is longest", function()
      local t = trie.new()
      t:insert("ab", 1)
      t:insert("abc", 2)
      local key, val = t:longest_prefix("abc")
      T.eq(key, "abc")
      T.eq(val, 2)
    end)
  end)

  T.describe("autocomplete", function()
    T.it("returns all matches sorted", function()
      local t = trie.new()
      t:insert("banana")
      t:insert("band")
      t:insert("ban")
      t:insert("apple")
      local results = t:autocomplete("ban")
      T.eq(#results, 3)
      T.eq(results[1], "ban")
      T.eq(results[2], "banana")
      T.eq(results[3], "band")
    end)

    T.it("respects limit", function()
      local t = trie.new()
      t:insert("aa")
      t:insert("ab")
      t:insert("ac")
      t:insert("ad")
      local results = t:autocomplete("a", 2)
      T.eq(#results, 2)
      T.eq(results[1], "aa")
      T.eq(results[2], "ab")
    end)

    T.it("returns empty for no match", function()
      local t = trie.new()
      T.eq(#t:autocomplete("x"), 0)
    end)
  end)

  T.describe("keys", function()
    T.it("returns all keys sorted", function()
      local t = trie.new()
      t:insert("cherry")
      t:insert("apple")
      t:insert("banana")
      local k = t:keys()
      T.eq(#k, 3)
      T.eq(k[1], "apple")
      T.eq(k[2], "banana")
      T.eq(k[3], "cherry")
    end)

    T.it("returns empty for empty trie", function()
      local t = trie.new()
      T.eq(#t:keys(), 0)
    end)
  end)

  T.describe("values", function()
    T.it("returns values in key-sorted order", function()
      local t = trie.new()
      t:insert("b", 2)
      t:insert("a", 1)
      t:insert("c", 3)
      local v = t:values()
      T.eq(#v, 3)
      T.eq(v[1], 1)
      T.eq(v[2], 2)
      T.eq(v[3], 3)
    end)
  end)

  T.describe("pairs", function()
    T.it("iterates in sorted order", function()
      local t = trie.new()
      t:insert("z", 26)
      t:insert("a", 1)
      t:insert("m", 13)
      local keys = {}
      local vals = {}
      for k, v in t:pairs() do
        keys[#keys + 1] = k
        vals[#vals + 1] = v
      end
      T.eq(#keys, 3)
      T.eq(keys[1], "a")
      T.eq(keys[2], "m")
      T.eq(keys[3], "z")
      T.eq(vals[1], 1)
      T.eq(vals[2], 13)
      T.eq(vals[3], 26)
    end)
  end)

  T.describe("clear", function()
    T.it("removes all keys", function()
      local t = trie.new()
      t:insert("a")
      t:insert("b")
      t:clear()
      T.eq(t:size(), 0)
      T.eq(t:has("a"), false)
      T.eq(#t:keys(), 0)
    end)
  end)

  T.describe("single char keys", function()
    T.it("handles single character keys", function()
      local t = trie.new()
      t:insert("a", 1)
      t:insert("b", 2)
      t:insert("c", 3)
      T.eq(t:get("a"), 1)
      T.eq(t:get("b"), 2)
      T.eq(t:get("c"), 3)
      T.eq(t:size(), 3)
    end)
  end)

  T.describe("overlapping prefixes", function()
    T.it("handles a, ab, abc correctly", function()
      local t = trie.new()
      t:insert("a", 1)
      t:insert("ab", 2)
      t:insert("abc", 3)
      T.eq(t:get("a"), 1)
      T.eq(t:get("ab"), 2)
      T.eq(t:get("abc"), 3)
      T.eq(t:size(), 3)
      T.eq(t:count_prefix("a"), 3)
      T.eq(t:count_prefix("ab"), 2)
      T.eq(t:count_prefix("abc"), 1)
      local k = t:keys()
      T.eq(k[1], "a")
      T.eq(k[2], "ab")
      T.eq(k[3], "abc")
    end)
  end)

  T.describe("unicode keys", function()
    T.it("handles multibyte UTF-8 keys", function()
      local t = trie.new()
      t:insert("café", "french")
      t:insert("caféine", "chemical")
      t:insert("cat", "animal")
      T.eq(t:get("café"), "french")
      T.eq(t:get("caféine"), "chemical")
      T.eq(t:get("cat"), "animal")
      T.ok(t:has("café"))
      T.eq(t:size(), 3)
    end)

    T.it("prefix search with unicode", function()
      local t = trie.new()
      t:insert("日本語", "japanese")
      t:insert("日本食", "food")
      T.eq(t:count_prefix("日本"), 2)
      T.ok(t:has_prefix("日"))
    end)
  end)

  T.describe("edge cases", function()
    T.it("get on empty trie returns nil", function()
      local t = trie.new()
      T.eq(t:get("anything"), nil)
    end)

    T.it("remove on empty trie returns nil", function()
      local t = trie.new()
      T.eq(t:remove("anything"), nil)
    end)

    T.it("double remove returns nil second time", function()
      local t = trie.new()
      t:insert("x", 10)
      T.eq(t:remove("x"), 10)
      T.eq(t:remove("x"), nil)
    end)

    T.it("insert after remove", function()
      local t = trie.new()
      t:insert("key", 1)
      t:remove("key")
      t:insert("key", 2)
      T.eq(t:get("key"), 2)
      T.eq(t:size(), 1)
    end)

    T.it("value can be false", function()
      local t = trie.new()
      t:insert("f", false)
      T.ok(t:has("f"))
      T.eq(t:get("f"), false)
    end)
  end)

end)
