if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local csv = require("lib.csv")

T.describe("csv.decode", function()
  T.it("parses a simple row", function()
    local rows = csv.decode("a,b,c\n")
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")
    T.eq(rows[1][3], "c")
  end)

  T.it("parses multiple rows", function()
    local rows = csv.decode("a,b\nc,d\n")
    T.eq(#rows, 2)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")
    T.eq(rows[2][1], "c")
    T.eq(rows[2][2], "d")
  end)

  T.it("parses without trailing newline", function()
    local rows = csv.decode("a,b\nc,d")
    T.eq(#rows, 2)
    T.eq(rows[2][1], "c")
    T.eq(rows[2][2], "d")
  end)

  T.it("handles empty input", function()
    local rows = csv.decode("")
    T.eq(#rows, 0)
  end)

  T.it("handles single field", function()
    local rows = csv.decode("hello")
    T.eq(#rows, 1)
    T.eq(rows[1][1], "hello")
  end)

  T.it("handles single row with newline", function()
    local rows = csv.decode("x,y,z\n")
    T.eq(#rows, 1)
    T.eq(#rows[1], 3)
  end)

  T.it("returns error for non-string input", function()
    local result, err = csv.decode(42)
    T.eq(result, nil)
    T.ok(err:find("expected string"))
  end)
end)

T.describe("csv.decode quoting", function()
  T.it("handles quoted fields with commas", function()
    local rows = csv.decode('"a,b",c\n')
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a,b")
    T.eq(rows[1][2], "c")
  end)

  T.it("handles quoted fields with newlines", function()
    local rows = csv.decode('"line1\nline2",b\n')
    T.eq(#rows, 1)
    T.eq(rows[1][1], "line1\nline2")
    T.eq(rows[1][2], "b")
  end)

  T.it("handles escaped quotes", function()
    local rows = csv.decode('"a""b",c\n')
    T.eq(#rows, 1)
    T.eq(rows[1][1], 'a"b')
    T.eq(rows[1][2], "c")
  end)

  T.it("handles multiple escaped quotes", function()
    local rows = csv.decode('"a""b""c"\n')
    T.eq(#rows, 1)
    T.eq(rows[1][1], 'a"b"c')
  end)

  T.it("handles empty quoted field", function()
    local rows = csv.decode('"",b\n')
    T.eq(#rows, 1)
    T.eq(rows[1][1], "")
    T.eq(rows[1][2], "b")
  end)

  T.it("returns error for unterminated quote", function()
    local result, err = csv.decode('"unterminated')
    T.eq(result, nil)
    T.ok(err:find("unterminated"))
  end)

  T.it("handles quoted field with CRLF inside", function()
    local rows = csv.decode('"a\r\nb",c\n')
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a\r\nb")
    T.eq(rows[1][2], "c")
  end)
end)

T.describe("csv.decode empty fields", function()
  T.it("handles leading empty field", function()
    local rows = csv.decode(",b,c\n")
    T.eq(#rows, 1)
    T.eq(rows[1][1], "")
    T.eq(rows[1][2], "b")
    T.eq(rows[1][3], "c")
  end)

  T.it("handles trailing empty field", function()
    local rows = csv.decode("a,b,\n")
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")
    T.eq(rows[1][3], "")
  end)

  T.it("handles all empty fields", function()
    local rows = csv.decode(",,,\n")
    T.eq(#rows, 1)
    T.eq(#rows[1], 4)
    T.eq(rows[1][1], "")
    T.eq(rows[1][4], "")
  end)

  T.it("handles middle empty field", function()
    local rows = csv.decode("a,,c\n")
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "")
    T.eq(rows[1][3], "c")
  end)
end)

T.describe("csv.decode line endings", function()
  T.it("handles CRLF line endings", function()
    local rows = csv.decode("a,b\r\nc,d\r\n")
    T.eq(#rows, 2)
    T.eq(rows[1][1], "a")
    T.eq(rows[2][1], "c")
  end)

  T.it("handles LF line endings", function()
    local rows = csv.decode("a,b\nc,d\n")
    T.eq(#rows, 2)
    T.eq(rows[1][2], "b")
    T.eq(rows[2][2], "d")
  end)

  T.it("handles mixed line endings", function()
    local rows = csv.decode("a,b\r\nc,d\n")
    T.eq(#rows, 2)
    T.eq(rows[1][1], "a")
    T.eq(rows[2][1], "c")
  end)

  T.it("handles CRLF without trailing newline", function()
    local rows = csv.decode("a,b\r\nc,d")
    T.eq(#rows, 2)
    T.eq(rows[2][2], "d")
  end)
end)

T.describe("csv.decode header mode", function()
  T.it("returns keyed tables with header=true", function()
    local records = csv.decode("name,age\nAlice,30\nBob,25\n", { header = true })
    T.eq(#records, 2)
    T.eq(records[1].name, "Alice")
    T.eq(records[1].age, "30")
    T.eq(records[2].name, "Bob")
    T.eq(records[2].age, "25")
  end)

  T.it("handles header mode with empty data", function()
    local records = csv.decode("name,age\n", { header = true })
    T.eq(#records, 0)
  end)

  T.it("handles missing fields in header mode", function()
    local records = csv.decode("a,b,c\n1,2\n", { header = true })
    T.eq(#records, 1)
    T.eq(records[1].a, "1")
    T.eq(records[1].b, "2")
    T.eq(records[1].c, "")
  end)
end)

T.describe("csv.decode custom delimiter", function()
  T.it("handles tab delimiter", function()
    local rows = csv.decode("a\tb\tc\n", { delimiter = "\t" })
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")
    T.eq(rows[1][3], "c")
  end)

  T.it("handles semicolon delimiter", function()
    local rows = csv.decode("a;b;c\n", { delimiter = ";" })
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")
    T.eq(rows[1][3], "c")
  end)

  T.it("handles pipe delimiter with quoting", function()
    local rows = csv.decode('"a|b"|c\n', { delimiter = "|" })
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a|b")
    T.eq(rows[1][2], "c")
  end)
end)

T.describe("csv.decode skip_empty", function()
  T.it("skips empty rows when skip_empty=true", function()
    local rows = csv.decode("a,b\n\nc,d\n", { skip_empty = true })
    T.eq(#rows, 2)
    T.eq(rows[1][1], "a")
    T.eq(rows[2][1], "c")
  end)
end)

T.describe("csv.encode", function()
  T.it("encodes simple rows", function()
    local s = csv.encode({ { "a", "b", "c" } })
    T.eq(s, "a,b,c\n")
  end)

  T.it("encodes multiple rows", function()
    local s = csv.encode({ { "a", "b" }, { "c", "d" } })
    T.eq(s, "a,b\nc,d\n")
  end)

  T.it("quotes fields with commas", function()
    local s = csv.encode({ { "a,b", "c" } })
    T.eq(s, '"a,b",c\n')
  end)

  T.it("quotes fields with quotes", function()
    local s = csv.encode({ { 'a"b', "c" } })
    T.eq(s, '"a""b",c\n')
  end)

  T.it("quotes fields with newlines", function()
    local s = csv.encode({ { "a\nb", "c" } })
    T.eq(s, '"a\nb",c\n')
  end)

  T.it("encodes empty fields", function()
    local s = csv.encode({ { "", "b", "" } })
    T.eq(s, ",b,\n")
  end)

  T.it("uses custom delimiter", function()
    local s = csv.encode({ { "a", "b" } }, { delimiter = "\t" })
    T.eq(s, "a\tb\n")
  end)

  T.it("uses custom line ending", function()
    local s = csv.encode({ { "a", "b" } }, { line_ending = "\r\n" })
    T.eq(s, "a,b\r\n")
  end)

  T.it("prepends header row", function()
    local s = csv.encode({ { "1", "2" } }, { header = { "a", "b" } })
    T.eq(s, "a,b\n1,2\n")
  end)
end)

T.describe("csv roundtrip", function()
  T.it("decode(encode(rows)) equals original rows", function()
    local original = { { "a", "b", "c" }, { "d", "e", "f" } }
    local encoded = csv.encode(original)
    local decoded = csv.decode(encoded)
    T.eq(#decoded, 2)
    T.eq(decoded[1][1], "a")
    T.eq(decoded[1][3], "c")
    T.eq(decoded[2][1], "d")
    T.eq(decoded[2][3], "f")
  end)

  T.it("roundtrips fields with special characters", function()
    local original = { { 'he said "hi"', "a,b", "line1\nline2" } }
    local encoded = csv.encode(original)
    local decoded = csv.decode(encoded)
    T.eq(#decoded, 1)
    T.eq(decoded[1][1], 'he said "hi"')
    T.eq(decoded[1][2], "a,b")
    T.eq(decoded[1][3], "line1\nline2")
  end)

  T.it("roundtrips empty fields", function()
    local original = { { "", "", "" } }
    local encoded = csv.encode(original)
    local decoded = csv.decode(encoded)
    T.eq(#decoded, 1)
    T.eq(decoded[1][1], "")
    T.eq(decoded[1][2], "")
    T.eq(decoded[1][3], "")
  end)

  T.it("roundtrips with custom delimiter", function()
    local original = { { "a", "b" }, { "c", "d" } }
    local opts = { delimiter = ";" }
    local encoded = csv.encode(original, opts)
    local decoded = csv.decode(encoded, opts)
    T.eq(#decoded, 2)
    T.eq(decoded[1][1], "a")
    T.eq(decoded[2][2], "d")
  end)
end)

T.describe("csv.decoder (streaming)", function()
  T.it("processes chunks and returns completed rows", function()
    local d = csv.decoder()
    d:push("a,b\nc")
    local rows = d:rows()
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")

    d:push(",d\n")
    rows = d:rows()
    T.eq(#rows, 1)
    T.eq(rows[1][1], "c")
    T.eq(rows[1][2], "d")
  end)

  T.it("handles data split across chunks", function()
    local d = csv.decoder()
    d:push("hel")
    d:push("lo,wor")
    d:push("ld\n")
    local rows = d:rows()
    T.eq(#rows, 1)
    T.eq(rows[1][1], "hello")
    T.eq(rows[1][2], "world")
  end)

  T.it("finish processes remaining buffer", function()
    local d = csv.decoder()
    d:push("a,b")
    local rows = d:rows()
    T.eq(#rows, 0)

    rows = d:finish()
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a")
    T.eq(rows[1][2], "b")
  end)

  T.it("handles quoted fields across chunks", function()
    local d = csv.decoder()
    d:push('"a,')
    d:push('b",c\n')
    local rows = d:rows()
    T.eq(#rows, 1)
    T.eq(rows[1][1], "a,b")
    T.eq(rows[1][2], "c")
  end)

  T.it("streaming with header mode", function()
    local d = csv.decoder({ header = true })
    d:push("name,age\nAlice,30\n")
    local rows = d:rows()
    T.eq(#rows, 1)
    T.eq(rows[1].name, "Alice")
    T.eq(rows[1].age, "30")
  end)
end)

T.describe("csv aliases", function()
  T.it("string_to_rows is decode", function()
    T.eq(csv.string_to_rows, csv.decode)
  end)

  T.it("rows_to_string is encode", function()
    T.eq(csv.rows_to_string, csv.encode)
  end)
end)
