-- lib/roman_numeral/roman_numeral_test.lua
-- Tests for lib/roman_numeral

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local R = require("lib.roman_numeral")

T.describe("roman_numeral", function()

  -- -------------------------------------------------------------------------
  T.describe("to_roman — subtractive pairs", function()
    T.it("4  -> IV",  function() T.eq(R.to_roman(4),   "IV") end)
    T.it("9  -> IX",  function() T.eq(R.to_roman(9),   "IX") end)
    T.it("40 -> XL",  function() T.eq(R.to_roman(40),  "XL") end)
    T.it("90 -> XC",  function() T.eq(R.to_roman(90),  "XC") end)
    T.it("400 -> CD", function() T.eq(R.to_roman(400), "CD") end)
    T.it("900 -> CM", function() T.eq(R.to_roman(900), "CM") end)
  end)

  T.describe("to_roman — symbol values", function()
    T.it("1    -> I",    function() T.eq(R.to_roman(1),    "I") end)
    T.it("5    -> V",    function() T.eq(R.to_roman(5),    "V") end)
    T.it("10   -> X",    function() T.eq(R.to_roman(10),   "X") end)
    T.it("50   -> L",    function() T.eq(R.to_roman(50),   "L") end)
    T.it("100  -> C",    function() T.eq(R.to_roman(100),  "C") end)
    T.it("500  -> D",    function() T.eq(R.to_roman(500),  "D") end)
    T.it("1000 -> M",    function() T.eq(R.to_roman(1000), "M") end)
  end)

  T.describe("to_roman — edge and common cases", function()
    T.it("14   -> XIV",       function() T.eq(R.to_roman(14),   "XIV") end)
    T.it("1994 -> MCMXCIV",   function() T.eq(R.to_roman(1994), "MCMXCIV") end)
    T.it("2024 -> MMXXIV",    function() T.eq(R.to_roman(2024), "MMXXIV") end)
    T.it("3999 -> MMMCMXCIX", function() T.eq(R.to_roman(3999), "MMMCMXCIX") end)
  end)

  T.describe("to_roman — errors", function()
    T.it("0 -> nil, err", function()
      local r, e = R.to_roman(0)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("4000 -> nil, err", function()
      local r, e = R.to_roman(4000)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("-1 -> nil, err", function()
      local r, e = R.to_roman(-1)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("1.5 -> nil, err", function()
      local r, e = R.to_roman(1.5)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("string -> nil, err", function()
      local r, e = R.to_roman("XIV")
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("from_roman — known values", function()
    T.it("MCMXCIV -> 1994", function() T.eq(R.from_roman("MCMXCIV"), 1994) end)
    T.it("XIV -> 14",       function() T.eq(R.from_roman("XIV"), 14) end)
    T.it("IV  -> 4",        function() T.eq(R.from_roman("IV"),  4) end)
    T.it("IX  -> 9",        function() T.eq(R.from_roman("IX"),  9) end)
    T.it("XL  -> 40",       function() T.eq(R.from_roman("XL"),  40) end)
    T.it("XC  -> 90",       function() T.eq(R.from_roman("XC"),  90) end)
    T.it("CD  -> 400",      function() T.eq(R.from_roman("CD"),  400) end)
    T.it("CM  -> 900",      function() T.eq(R.from_roman("CM"),  900) end)
  end)

  T.describe("from_roman — case insensitive", function()
    T.it("mcmxciv -> 1994", function() T.eq(R.from_roman("mcmxciv"), 1994) end)
    T.it("xiv -> 14",       function() T.eq(R.from_roman("xiv"), 14) end)
    T.it("Mi -> 1001 (mixed case)",  function() T.eq(R.from_roman("Mi"), 1001) end)
  end)

  T.describe("from_roman — round-trip spot check", function()
    T.it("round-trips 100 values across 1-3999", function()
      -- Spot check ~100 values evenly spread
      local step = math.floor(3999 / 100)
      local ok = true
      for i = 1, 3999, step do
        local r = R.to_roman(i)
        local n = R.from_roman(r)
        if n ~= i then ok = false; break end
      end
      T.ok(ok)
    end)
    T.it("full round-trip 1..3999", function()
      local ok = true
      for i = 1, 3999 do
        local r = R.to_roman(i)
        local n = R.from_roman(r)
        if n ~= i then ok = false; break end
      end
      T.ok(ok)
    end)
  end)

  T.describe("from_roman — nil on invalid input", function()
    T.it("empty string -> nil", function()
      local r, e = R.from_roman("")
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("invalid char Z -> nil", function()
      local r, e = R.from_roman("Z")
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("digits mixed in -> nil", function()
      local r, e = R.from_roman("XIV2")
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("nil -> nil", function()
      local r, e = R.from_roman(nil)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("valid — strict canonical", function()
    T.it("XIV -> true",       function() T.ok(R.valid("XIV")) end)
    T.it("MCMXCIV -> true",   function() T.ok(R.valid("MCMXCIV")) end)
    T.it("I -> true",         function() T.ok(R.valid("I")) end)
    T.it("MMMCMXCIX -> true", function() T.ok(R.valid("MMMCMXCIX")) end)
    T.it("lowercase iv -> true", function() T.ok(R.valid("iv")) end)
    -- Non-canonical forms
    T.it("IIII -> false",     function() T.ok(not R.valid("IIII")) end)
    T.it("IIX -> false",      function() T.ok(not R.valid("IIX")) end)
    T.it("empty -> false",    function() T.ok(not R.valid("")) end)
    T.it("non-roman A -> false", function() T.ok(not R.valid("A")) end)
    T.it("number -> false",   function() T.ok(not R.valid(42)) end)
    T.it("IIIII -> false",    function() T.ok(not R.valid("IIIII")) end)
    T.it("VV -> false (double V)", function() T.ok(not R.valid("VV")) end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("to_roman_additive", function()
    T.it("4 -> IIII",    function() T.eq(R.to_roman_additive(4),   "IIII") end)
    T.it("9 -> VIIII",   function() T.eq(R.to_roman_additive(9),   "VIIII") end)
    T.it("14 -> XIIII",  function() T.eq(R.to_roman_additive(14),  "XIIII") end)
    T.it("40 -> XXXX",   function() T.eq(R.to_roman_additive(40),  "XXXX") end)
    T.it("90 -> LXXXX",  function() T.eq(R.to_roman_additive(90),  "LXXXX") end)
    T.it("400 -> CCCC",  function() T.eq(R.to_roman_additive(400), "CCCC") end)
    T.it("900 -> DCCCC", function() T.eq(R.to_roman_additive(900), "DCCCC") end)
    T.it("1 -> I",       function() T.eq(R.to_roman_additive(1),   "I") end)
    T.it("3999 additive", function()
      -- 3999 = MMM+DCCCC+LXXXX+VIIII additive
      T.eq(R.to_roman_additive(3999), "MMMDCCCCLXXXXVIIII")
    end)
    T.it("error on 0", function()
      local r, e = R.to_roman_additive(0)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("error on 4000", function()
      local r, e = R.to_roman_additive(4000)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("to_roman_large / from_roman_large — vinculum", function()
    T.it("5000 -> (V)",       function() T.eq(R.to_roman_large(5000),    "(V)") end)
    T.it("4000 -> (IV)",      function() T.eq(R.to_roman_large(4000),    "(IV)") end)
    T.it("10000 -> (X)",      function() T.eq(R.to_roman_large(10000),   "(X)") end)
    T.it("50000 -> (L)",      function() T.eq(R.to_roman_large(50000),   "(L)") end)
    T.it("100000 -> (C)",     function() T.eq(R.to_roman_large(100000),  "(C)") end)
    T.it("500000 -> (D)",     function() T.eq(R.to_roman_large(500000),  "(D)") end)
    T.it("1000000 -> (M)",    function() T.eq(R.to_roman_large(1000000), "(M)") end)
    T.it("3999999 -> (MMMCMXCIX)CMXCIX", function()
      T.eq(R.to_roman_large(3999999), "(MMMCMXCIX)CMXCIX")
    end)
    T.it("5445 = (V)CDXLV",  function() T.eq(R.to_roman_large(5445), "(V)CDXLV") end)
    T.it("1-3999 same as to_roman", function()
      T.eq(R.to_roman_large(1994), "MCMXCIV")
      T.eq(R.to_roman_large(1), "I")
      T.eq(R.to_roman_large(3999), "MMMCMXCIX")
    end)
    -- from_roman_large
    T.it("(IV) -> 4000",       function() T.eq(R.from_roman_large("(IV)"),     4000) end)
    T.it("(V)CDXLV -> 5445",   function() T.eq(R.from_roman_large("(V)CDXLV"), 5445) end)
    T.it("(V) -> 5000",        function() T.eq(R.from_roman_large("(V)"),      5000) end)
    T.it("(M) -> 1000000",     function() T.eq(R.from_roman_large("(M)"),      1000000) end)
    T.it("(MMMCMXCIX)CMXCIX -> 3999999", function()
      T.eq(R.from_roman_large("(MMMCMXCIX)CMXCIX"), 3999999)
    end)
    -- round-trip large
    T.it("round-trips 5000", function()
      local s = R.to_roman_large(5000)
      T.eq(R.from_roman_large(s), 5000)
    end)
    T.it("round-trips 1234567 (within range)", function()
      local s = R.to_roman_large(1234567)
      T.eq(R.from_roman_large(s), 1234567)
    end)
    -- errors
    T.it("error on 0", function()
      local r, e = R.to_roman_large(0)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("error on 4000000", function()
      local r, e = R.to_roman_large(4000000)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("from_roman_large error: unclosed paren", function()
      local r, e = R.from_roman_large("(V")
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    T.it("from_roman_large error: invalid vinculum char", function()
      local r, e = R.from_roman_large("(Z)")
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("to_ordinal", function()
    T.it("1  -> Ist",   function() T.eq(R.to_ordinal(1),  "Ist") end)
    T.it("2  -> IInd",  function() T.eq(R.to_ordinal(2),  "IInd") end)
    T.it("3  -> IIIrd", function() T.eq(R.to_ordinal(3),  "IIIrd") end)
    T.it("4  -> IVth",  function() T.eq(R.to_ordinal(4),  "IVth") end)
    T.it("5  -> Vth",   function() T.eq(R.to_ordinal(5),  "Vth") end)
    T.it("10 -> Xth",   function() T.eq(R.to_ordinal(10), "Xth") end)
    T.it("11 -> XIth (special)", function() T.eq(R.to_ordinal(11), "XIth") end)
    T.it("12 -> XIIth (special)", function() T.eq(R.to_ordinal(12), "XIIth") end)
    T.it("13 -> XIIIth (special)", function() T.eq(R.to_ordinal(13), "XIIIth") end)
    T.it("21 -> XXIst",  function() T.eq(R.to_ordinal(21), "XXIst") end)
    T.it("22 -> XXIInd", function() T.eq(R.to_ordinal(22), "XXIInd") end)
    T.it("23 -> XXIIIrd",function() T.eq(R.to_ordinal(23), "XXIIIrd") end)
    T.it("error on 0",  function()
      local r, e = R.to_ordinal(0)
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("to_unicode", function()
    T.it("1  -> Ⅰ (U+2160)", function() T.eq(R.to_unicode(1),  "\xE2\x85\xA0") end)
    T.it("2  -> Ⅱ (U+2161)", function() T.eq(R.to_unicode(2),  "\xE2\x85\xA1") end)
    T.it("3  -> Ⅲ (U+2162)", function() T.eq(R.to_unicode(3),  "\xE2\x85\xA2") end)
    T.it("4  -> Ⅳ (U+2163)", function() T.eq(R.to_unicode(4),  "\xE2\x85\xA3") end)
    T.it("5  -> Ⅴ (U+2164)", function() T.eq(R.to_unicode(5),  "\xE2\x85\xA4") end)
    T.it("6  -> Ⅵ (U+2165)", function() T.eq(R.to_unicode(6),  "\xE2\x85\xA5") end)
    T.it("7  -> Ⅶ (U+2166)", function() T.eq(R.to_unicode(7),  "\xE2\x85\xA6") end)
    T.it("8  -> Ⅷ (U+2167)", function() T.eq(R.to_unicode(8),  "\xE2\x85\xA7") end)
    T.it("9  -> Ⅸ (U+2168)", function() T.eq(R.to_unicode(9),  "\xE2\x85\xA8") end)
    T.it("10 -> Ⅹ (U+2169)", function() T.eq(R.to_unicode(10), "\xE2\x85\xA9") end)
    T.it("11 -> Ⅺ (U+216A)", function() T.eq(R.to_unicode(11), "\xE2\x85\xAA") end)
    T.it("12 -> Ⅻ (U+216B)", function() T.eq(R.to_unicode(12), "\xE2\x85\xAB") end)
    T.it("50   -> Ⅼ (U+216C)", function() T.eq(R.to_unicode(50),   "\xE2\x85\xAC") end)
    T.it("100  -> Ⅽ (U+216D)", function() T.eq(R.to_unicode(100),  "\xE2\x85\xAD") end)
    T.it("500  -> Ⅾ (U+216E)", function() T.eq(R.to_unicode(500),  "\xE2\x85\xAE") end)
    T.it("1000 -> Ⅿ (U+216F)", function() T.eq(R.to_unicode(1000), "\xE2\x85\xAF") end)
    -- Values with no precomposed form
    T.it("13 -> nil (no precomposed form)", function() T.eq(R.to_unicode(13), nil) end)
    T.it("14 -> nil", function() T.eq(R.to_unicode(14), nil) end)
    T.it("999 -> nil", function() T.eq(R.to_unicode(999), nil) end)
    T.it("string arg -> nil", function() T.eq(R.to_unicode("XII"), nil) end)
  end)

  T.describe("from_unicode", function()
    -- Round-trip 1-12
    T.it("round-trips 1-12", function()
      local ok = true
      for i = 1, 12 do
        local u = R.to_unicode(i)
        local n = R.from_unicode(u)
        if n ~= i then ok = false; break end
      end
      T.ok(ok)
    end)
    T.it("round-trips 50",   function() T.eq(R.from_unicode(R.to_unicode(50)),   50) end)
    T.it("round-trips 100",  function() T.eq(R.from_unicode(R.to_unicode(100)),  100) end)
    T.it("round-trips 500",  function() T.eq(R.from_unicode(R.to_unicode(500)),  500) end)
    T.it("round-trips 1000", function() T.eq(R.from_unicode(R.to_unicode(1000)), 1000) end)
    -- Lowercase Unicode forms (U+2170-U+217F)
    T.it("lowercase U+2170 (ⅰ) -> 1",  function() T.eq(R.from_unicode("\xE2\x85\xB0"), 1) end)
    T.it("lowercase U+217B (ⅻ) -> 12", function() T.eq(R.from_unicode("\xE2\x85\xBB"), 12) end)
    -- Unknown
    T.it("nil arg -> nil", function() T.eq(R.from_unicode(nil), nil) end)
    T.it("ASCII 'I' -> nil (not Unicode)", function() T.eq(R.from_unicode("I"), nil) end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("format", function()
    T.it("style=standard default",    function() T.eq(R.format(4),    "IV") end)
    T.it("style=standard explicit",   function() T.eq(R.format(1994, { style="standard" }), "MCMXCIV") end)
    T.it("style=additive 4 -> IIII",  function() T.eq(R.format(4, { style="additive" }), "IIII") end)
    T.it("style=additive 9 -> VIIII", function() T.eq(R.format(9, { style="additive" }), "VIIII") end)
    T.it("style=large 5000 -> (V)",   function() T.eq(R.format(5000, { style="large" }), "(V)") end)
    T.it("style=unicode 12 -> Ⅻ",    function() T.eq(R.format(12, { style="unicode" }), "\xE2\x85\xAB") end)
    T.it("style=unicode missing -> nil", function()
      local r, e = R.format(13, { style="unicode" })
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
    -- case
    T.it("case=lower 1994", function() T.eq(R.format(1994, { case="lower" }), "mcmxciv") end)
    T.it("case=upper 4",    function() T.eq(R.format(4, { case="upper" }), "IV") end)
    -- ordinal
    T.it("ordinal=true 1 -> Ist",  function() T.eq(R.format(1, { ordinal=true }), "Ist") end)
    T.it("ordinal=true 2 -> IInd", function() T.eq(R.format(2, { ordinal=true }), "IInd") end)
    T.it("ordinal=true 3 -> IIIrd",function() T.eq(R.format(3, { ordinal=true }), "IIIrd") end)
    T.it("ordinal=true 4 -> IVth", function() T.eq(R.format(4, { ordinal=true }), "IVth") end)
    T.it("ordinal=true + lower",   function() T.eq(R.format(1, { ordinal=true, case="lower" }), "ist") end)
    -- additive + ordinal
    T.it("additive + ordinal 4 -> IIIIth", function()
      T.eq(R.format(4, { style="additive", ordinal=true }), "IIIIth")
    end)
    -- unknown style
    T.it("unknown style -> nil", function()
      local r, e = R.format(1, { style="foo" })
      T.eq(r, nil)
      T.ok(e ~= nil)
    end)
  end)

  -- -------------------------------------------------------------------------
  T.describe("_tier", function()
    T.it("_tier is pure", function() T.eq(R._tier, "pure") end)
  end)

end)
