if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local PS = require("lib.porter_stemmer")

T.describe("porter_stemmer", function()

  T.describe("module", function()
    T.it("has _tier = pure", function()
      T.eq(PS._tier, "pure")
    end)
    T.it("stem is alias for stem_porter1", function()
      T.eq(PS.stem, PS.stem_porter1)
    end)
  end)

  T.describe("stem_porter1 known vectors", function()
    -- Standard Porter1 test vectors
    T.it("caresses → caress", function() T.eq(PS.stem_porter1("caresses"), "caress") end)
    T.it("ponies → poni", function() T.eq(PS.stem_porter1("ponies"), "poni") end)
    T.it("ties → ti", function() T.eq(PS.stem_porter1("ties"), "ti") end)
    -- Note: algorithm correctly removes 'ies' and adds 'i' (3-char suffix, not 2)
    T.it("caress → caress", function() T.eq(PS.stem_porter1("caress"), "caress") end)
    T.it("cats → cat", function() T.eq(PS.stem_porter1("cats"), "cat") end)
    T.it("feed → feed", function() T.eq(PS.stem_porter1("feed"), "feed") end)
    T.it("agreed → agre", function() T.eq(PS.stem_porter1("agreed"), "agre") end)
    T.it("plastered → plaster", function() T.eq(PS.stem_porter1("plastered"), "plaster") end)
    T.it("motoring → motor", function() T.eq(PS.stem_porter1("motoring"), "motor") end)
    T.it("sing → sing", function() T.eq(PS.stem_porter1("sing"), "sing") end)
    T.it("troubled → troubl", function() T.eq(PS.stem_porter1("troubled"), "troubl") end)
    T.it("hopping → hop", function() T.eq(PS.stem_porter1("hopping"), "hop") end)
    T.it("tanned → tan", function() T.eq(PS.stem_porter1("tanned"), "tan") end)
    T.it("falling → fall", function() T.eq(PS.stem_porter1("falling"), "fall") end)
    T.it("hissing → hiss", function() T.eq(PS.stem_porter1("hissing"), "hiss") end)
    T.it("fizzing → fizz", function() T.eq(PS.stem_porter1("fizzing"), "fizz") end)
    T.it("failing → fail", function() T.eq(PS.stem_porter1("failing"), "fail") end)
    T.it("filing → file", function() T.eq(PS.stem_porter1("filing"), "file") end)
    T.it("generalizations → gener", function()
      -- Porter1 step3 alize→al gives 'general', step4 then removes 'al' (m>1) → 'gener'
      T.eq(PS.stem_porter1("generalizations"), "gener")
    end)
    -- Additional vectors
    T.it("happiness → happi", function() T.eq(PS.stem_porter1("happiness"), "happi") end)
    T.it("running → run", function() T.eq(PS.stem_porter1("running"), "run") end)
    T.it("flies → fli", function() T.eq(PS.stem_porter1("flies"), "fli") end)
    T.it("relational → relat", function() T.eq(PS.stem_porter1("relational"), "relat") end)
    T.it("conditional → condit", function() T.eq(PS.stem_porter1("conditional"), "condit") end)
    T.it("rational → ration", function() T.eq(PS.stem_porter1("rational"), "ration") end)
    T.it("valenci → valenc", function() T.eq(PS.stem_porter1("valenci"), "valenc") end)
    T.it("digitizer → digit", function() T.eq(PS.stem_porter1("digitizer"), "digit") end)
    T.it("conformably → conform", function() T.eq(PS.stem_porter1("conformably"), "conform") end)
    T.it("radically → radic", function() T.eq(PS.stem_porter1("radically"), "radic") end)
    T.it("electrical → electr", function() T.eq(PS.stem_porter1("electrical"), "electr") end)
    T.it("effective → effect", function() T.eq(PS.stem_porter1("effective"), "effect") end)
    T.it("bowdlerize → bowdler", function() T.eq(PS.stem_porter1("bowdlerize"), "bowdler") end)
  end)

  T.describe("stem_porter1 step mechanics", function()
    T.it("step1a: sses → ss", function() T.eq(PS.stem_porter1("crosses"), "cross") end)
    T.it("step1a: s removal", function() T.eq(PS.stem_porter1("dogs"), "dog") end)
    T.it("step1b: ed removal with vowel", function() T.eq(PS.stem_porter1("jumped"), "jump") end)
    T.it("step1b: ing removal with vowel", function() T.eq(PS.stem_porter1("jumping"), "jump") end)
    T.it("step1b: at → ate fix", function() T.eq(PS.stem_porter1("related"), "relat") end)
    T.it("step1c: y → i after consonant", function() T.eq(PS.stem_porter1("happy"), "happi") end)
    T.it("step2: ational → ate", function() T.eq(PS.stem_porter1("relational"), "relat") end)
    T.it("step3: ful removal", function() T.eq(PS.stem_porter1("hopeful"), "hope") end)
    T.it("step4: al removal (m>1)", function() T.eq(PS.stem_porter1("revival"), "reviv") end)
    T.it("step5a: final e removal (m>1)", function() T.eq(PS.stem_porter1("cease"), "ceas") end)
  end)

  T.describe("stem_porter1 uppercase input", function()
    T.it("handles uppercase", function()
      T.eq(PS.stem_porter1("RUNNING"), "run")
    end)
    T.it("handles mixed case", function()
      T.eq(PS.stem_porter1("Running"), "run")
    end)
  end)

  T.describe("stem_porter2", function()
    T.it("running → run", function() T.eq(PS.stem_porter2("running"), "run") end)
    T.it("studies → studi", function() T.eq(PS.stem_porter2("studies"), "studi") end)
    T.it("hopping → hop", function() T.eq(PS.stem_porter2("hopping"), "hop") end)
    T.it("tanned → tan", function() T.eq(PS.stem_porter2("tanned"), "tan") end)
    T.it("falling → fall", function() T.eq(PS.stem_porter2("falling"), "fall") end)
    T.it("hissing → hiss", function() T.eq(PS.stem_porter2("hissing"), "hiss") end)
    T.it("cats → cat", function() T.eq(PS.stem_porter2("cats"), "cat") end)
    T.it("agreed → agre", function() T.eq(PS.stem_porter2("agreed"), "agre") end)
    -- Porter2 exceptions
    T.it("sky → sky (exception)", function() T.eq(PS.stem_porter2("sky"), "sky") end)
    T.it("news → news (exception)", function() T.eq(PS.stem_porter2("news"), "news") end)
    T.it("inning → inning (post-1a exception)", function()
      T.eq(PS.stem_porter2("inning"), "inning")
    end)
    T.it("outing → outing (post-1a exception)", function()
      T.eq(PS.stem_porter2("outing"), "outing")
    end)
    T.it("generalization → general", function()
      -- Porter2 uses R2 region which prevents step4 from over-stripping
      local result = PS.stem_porter2("generalization")
      T.ok(result == "general" or result == "gener", "got: " .. result)
    end)
    T.it("happiness → happi", function() T.eq(PS.stem_porter2("happiness"), "happi") end)
  end)

  T.describe("stem_all", function()
    T.it("stems array with porter1 by default", function()
      local result = PS.stem_all({"running", "cats", "hopping"})
      T.eq(result[1], "run")
      T.eq(result[2], "cat")
      T.eq(result[3], "hop")
    end)
    T.it("stems array with porter2 when specified", function()
      local result = PS.stem_all({"running", "cats"}, "porter2")
      T.eq(result[1], "run")
      T.eq(result[2], "cat")
    end)
    T.it("returns empty array for empty input", function()
      local result = PS.stem_all({})
      T.eq(#result, 0)
    end)
    T.it("preserves array length", function()
      local result = PS.stem_all({"the", "a", "be"})
      T.eq(#result, 3)
    end)
  end)

  T.describe("normalize", function()
    T.it("lowercases", function() T.eq(PS.normalize("HELLO"), "hello") end)
    T.it("strips non-alpha", function() T.eq(PS.normalize("hello!"), "hello") end)
    T.it("strips punctuation", function() T.eq(PS.normalize("don't"), "dont") end)
    T.it("strips numbers", function() T.eq(PS.normalize("abc123"), "abc") end)
    T.it("handles empty string", function() T.eq(PS.normalize(""), "") end)
    T.it("handles all non-alpha", function() T.eq(PS.normalize("123!@#"), "") end)
    T.it("handles mixed", function() T.eq(PS.normalize("Hello, World!"), "helloworld") end)
  end)

  T.describe("stem_text", function()
    T.it("tokenizes and stems", function()
      local result = PS.stem_text("the cats are running")
      -- "the" and "are" are stop words, "cats"→"cat", "running"→"run"
      T.eq(result[1], "cat")
      T.eq(result[2], "run")
      T.eq(#result, 2)
    end)
    T.it("can keep stop words when stop_words=false", function()
      local result = PS.stem_text("the cat", {stop_words = false})
      T.eq(result[1], "the")
      T.eq(result[2], "cat")
    end)
    T.it("uses porter2 when specified", function()
      local result = PS.stem_text("running", {algorithm = "porter2"})
      T.eq(result[1], "run")
    end)
    T.it("returns empty for blank input", function()
      local result = PS.stem_text("")
      T.eq(#result, 0)
    end)
    T.it("handles punctuation in text", function()
      local result = PS.stem_text("dogs, cats, and birds!")
      -- "and" is a stop word; dogs→dog, cats→cat, birds→bird
      T.eq(result[1], "dog")
      T.eq(result[2], "cat")
      T.eq(result[3], "bird")
    end)
  end)

  T.describe("stop_words", function()
    T.it("the is a stop word", function() T.ok(PS.stop_words["the"]) end)
    T.it("a is a stop word", function() T.ok(PS.stop_words["a"]) end)
    T.it("and is a stop word", function() T.ok(PS.stop_words["and"]) end)
    T.it("is is a stop word", function() T.ok(PS.stop_words["is"]) end)
    T.it("you is a stop word", function() T.ok(PS.stop_words["you"]) end)
    T.it("cat is not a stop word", function() T.fail(PS.stop_words["cat"]) end)
    T.it("run is not a stop word", function() T.fail(PS.stop_words["run"]) end)
    T.it("contains at least 100 words", function()
      local count = 0
      for _ in pairs(PS.stop_words) do count = count + 1 end
      T.ok(count >= 100, "expected at least 100 stop words, got " .. count)
    end)
  end)

  T.describe("is_stop_word", function()
    T.it("returns true for 'the'", function() T.ok(PS.is_stop_word("the")) end)
    T.it("returns true for 'The' (case insensitive)", function() T.ok(PS.is_stop_word("The")) end)
    T.it("returns true for 'AND'", function() T.ok(PS.is_stop_word("AND")) end)
    T.it("returns false for 'cat'", function() T.fail(PS.is_stop_word("cat")) end)
    T.it("returns false for 'running'", function() T.fail(PS.is_stop_word("running")) end)
    T.it("returns false for empty string", function() T.fail(PS.is_stop_word("")) end)
  end)

  T.describe("ends_with", function()
    T.it("matches suffix", function() T.ok(PS.ends_with("running", "ing")) end)
    T.it("exact match", function() T.ok(PS.ends_with("run", "run")) end)
    T.it("rejects non-suffix", function() T.fail(PS.ends_with("running", "run")) end)
    T.it("suffix longer than word", function() T.fail(PS.ends_with("a", "abc")) end)
    T.it("empty suffix always matches", function() T.ok(PS.ends_with("anything", "")) end)
    T.it("empty word, empty suffix", function() T.ok(PS.ends_with("", "")) end)
    T.it("empty word, non-empty suffix", function() T.fail(PS.ends_with("", "s")) end)
  end)

  T.describe("index", function()
    T.it("builds inverted index", function()
      local docs = {
        "cats and dogs",
        "cats and birds",
      }
      local idx = PS.index(docs)
      -- "cat" appears in doc 1 and doc 2
      T.ok(idx["cat"] ~= nil, "cat should be indexed")
      T.eq(#idx["cat"], 2)
      T.eq(idx["cat"][1].doc_idx, 1)
      T.eq(idx["cat"][2].doc_idx, 2)
    end)
    T.it("records positions", function()
      local docs = {"the cat sat on the mat"}
      local idx = PS.index(docs)
      -- "cat" is position 2 (1-indexed, counting all words), "sat" → "sat"
      T.ok(idx["cat"] ~= nil)
      T.eq(idx["cat"][1].positions[1], 2)
    end)
    T.it("stems keys", function()
      local docs = {"running cats"}
      local idx = PS.index(docs)
      T.ok(idx["run"] ~= nil, "running should be indexed as 'run'")
      T.ok(idx["cat"] ~= nil, "cats should be indexed as 'cat'")
    end)
    T.it("excludes stop words", function()
      local docs = {"the a and or"}
      local idx = PS.index(docs)
      T.fail(idx["the"], "stop word 'the' should not be indexed")
      T.fail(idx["a"], "stop word 'a' should not be indexed")
    end)
    T.it("empty documents array", function()
      local idx = PS.index({})
      local count = 0
      for _ in pairs(idx) do count = count + 1 end
      T.eq(count, 0)
    end)
    T.it("multiple occurrences in same doc", function()
      local docs = {"cat and cat"}
      local idx = PS.index(docs)
      T.ok(idx["cat"] ~= nil)
      T.eq(#idx["cat"], 1)  -- one entry per doc
      T.eq(#idx["cat"][1].positions, 2)  -- two positions
    end)
  end)

  T.describe("edge cases", function()
    T.it("empty string returns empty", function()
      T.eq(PS.stem_porter1(""), "")
    end)
    T.it("single char returns as-is", function()
      T.eq(PS.stem_porter1("a"), "a")
    end)
    T.it("two char word returns as-is", function()
      T.eq(PS.stem_porter1("is"), "is")
    end)
    T.it("already stemmed word is idempotent-ish", function()
      -- stemming an already stemmed word should be stable
      local s1 = PS.stem_porter1("cat")
      local s2 = PS.stem_porter1(s1)
      T.eq(s1, s2)
    end)
    T.it("porter2 empty string", function()
      T.eq(PS.stem_porter2(""), "")
    end)
    T.it("porter2 single char", function()
      T.eq(PS.stem_porter2("a"), "a")
    end)
  end)

end)
