-- lib/formats/ccv2/ccv2_types.lua
-- Type declarations for the CCv2 (Character Card v2) format.
-- Declaration-only file — no runtime code.

--:: CardData = {
--::   name: string,
--::   description: string,
--::   personality: string,
--::   scenario: string,
--::   first_mes: string,
--::   mes_example: string,
--::   creator_notes: string,
--::   system_prompt: string,
--::   post_history_instructions: string,
--::   creator: string,
--::   character_version: string,
--::   alternate_greetings: string[],
--::   tags: string[],
--::   extensions: { [string]: unknown },
--::   character_book: CharacterBook?,
--:: }

--:: CharacterBook = {
--::   entries: CharacterBookEntry[],
--::   name: string?,
--::   description: string?,
--::   scan_depth: number?,
--::   token_budget: number?,
--::   recursive_scanning: boolean?,
--::   extensions: { [string]: unknown }?,
--:: }

--:: CharacterBookEntry = {
--::   keys: string[],
--::   content: string,
--::   extensions: { [string]: unknown },
--::   enabled: boolean,
--::   insertion_order: number,
--::   case_sensitive: boolean?,
--::   name: string?,
--::   priority: number?,
--::   id: number?,
--::   comment: string?,
--::   selective: boolean?,
--::   secondary_keys: string[]?,
--::   constant: boolean?,
--::   position: string?,
--:: }

--:: CardEnvelope = {
--::   spec: string,
--::   spec_version: string,
--::   data: CardData,
--:: }

-- Normalized internal representation (after lorebook extraction)
--:: NormalizedEntry = {
--::   uid: string,
--::   key: string[],
--::   secondaryKey: string[]?,
--::   content: string,
--::   comment: string,
--::   enabled: boolean,
--::   selective: boolean,
--::   caseSensitive: boolean,
--::   constant: boolean,
--::   position: number,
--::   depth: number,
--::   order: number,
--::   selectiveLogic: number,
--::   role: number,
--:: }

--:: ImportResult = {
--::   card: CardData,
--::   lorebook: NormalizedEntry[]?,
--:: }
