-- lib/type/static/v2/v2_test.lua
-- Tests for the v2 typechecker: defs, intern, arena, lex, parse, ann, checker.

local ffi = require("ffi")
local assert = require("lib.test.assert")
local defs = require("lib.type.static.v2.defs")
local intern = require("lib.type.static.v2.intern")
local arena = require("lib.type.static.v2.arena")
local lex = require("lib.type.static.v2.lex")
local parse = require("lib.type.static.v2.parse")
local ann = require("lib.type.static.v2.ann")
local types_mod = require("lib.type.static.v2.types")
local env_mod   = require("lib.type.static.v2.env")
local unify_mod = require("lib.type.static.v2.unify")
local errors_mod = require("lib.type.static.v2.errors")
local match_mod = require("lib.type.static.v2.match")
local infer_mod = require("lib.type.static.v2.infer")

---------------------------------------------------------------------------
-- defs.lua
---------------------------------------------------------------------------

assert.describe("defs: FFI struct sizes", function()
    assert.it("ASTNode is 32 bytes", function()
        assert.eq(ffi.sizeof("ASTNode"), 32)
    end)
    assert.it("TypeSlot is 32 bytes", function()
        assert.eq(ffi.sizeof("TypeSlot"), 32)
    end)
    assert.it("FieldEntry is 12 bytes", function()
        assert.eq(ffi.sizeof("FieldEntry"), 12)
    end)
end)

assert.describe("defs: constants", function()
    assert.it("keywords list length matches NUM_KEYWORDS", function()
        assert.eq(#defs.keywords, defs.NUM_KEYWORDS)
    end)
    assert.it("token_name covers all tokens up to TK_EOF", function()
        for i = 0, defs.TK_EOF do
            assert.ok(defs.token_name[i], "missing token_name for " .. i)
        end
    end)
    assert.it("binop_priority has entries", function()
        assert.ok(defs.binop_priority[defs.OP_ADD])
        assert.ok(defs.binop_priority[defs.OP_OR])
    end)
end)

---------------------------------------------------------------------------
-- intern.lua
---------------------------------------------------------------------------

assert.describe("intern: basics", function()
    assert.it("round-trip string -> id -> string", function()
        local pool = intern.new()
        local id = intern.intern(pool, "hello")
        assert.eq(intern.get(pool, id), "hello")
    end)
    assert.it("idempotent: same string returns same id", function()
        local pool = intern.new()
        local id1 = intern.intern(pool, "world")
        local id2 = intern.intern(pool, "world")
        assert.eq(id1, id2)
    end)
    assert.it("different strings get different ids", function()
        local pool = intern.new()
        local id1 = intern.intern(pool, "foo")
        local id2 = intern.intern(pool, "bar")
        assert.ok(id1 ~= id2, "expected different ids")
    end)
    assert.it("sequential IDs starting from 0", function()
        local pool = intern.new()
        -- Keywords are pre-interned at 0..NUM_KEYWORDS-1
        -- Next ID should be NUM_KEYWORDS
        local id = intern.intern(pool, "custom_name")
        assert.eq(id, defs.NUM_KEYWORDS)
        local id2 = intern.intern(pool, "another_name")
        assert.eq(id2, defs.NUM_KEYWORDS + 1)
    end)
end)

assert.describe("intern: keywords pre-interned", function()
    assert.it("keyword lookup returns known IDs", function()
        local pool = intern.new()
        for i = 1, #defs.keywords do
            local kw = defs.keywords[i]
            local id = pool.map[kw]
            assert.ok(id ~= nil, "keyword not found: " .. kw)
            assert.eq(id, i - 1, "keyword ID mismatch for " .. kw)
            assert.ok(id < defs.NUM_KEYWORDS)
        end
    end)
    assert.it("'and' is ID 0, 'while' is ID 21", function()
        local pool = intern.new()
        assert.eq(pool.map["and"], 0)
        assert.eq(pool.map["while"], 21)
    end)
end)

---------------------------------------------------------------------------
-- arena.lua
---------------------------------------------------------------------------

assert.describe("arena: node arena", function()
    assert.it("alloc and read back", function()
        local a = arena.new_node_arena(4)
        local i = a:alloc()
        assert.eq(i, 0)
        local node = a:get(i)
        node.kind = defs.NODE_LITERAL
        node.line = 42
        node.col = 7
        assert.eq(a:get(0).kind, defs.NODE_LITERAL)
        assert.eq(a:get(0).line, 42)
        assert.eq(a:get(0).col, 7)
    end)
    assert.it("reset and reuse", function()
        local a = arena.new_node_arena(4)
        a:alloc()
        a:alloc()
        assert.eq(a.len, 2)
        a:reset()
        assert.eq(a.len, 0)
        local i = a:alloc()
        assert.eq(i, 0)
    end)
    assert.it("grow beyond initial capacity", function()
        local a = arena.new_node_arena(2)
        for j = 0, 9 do
            local i = a:alloc()
            a:get(i).kind = j
        end
        assert.eq(a.len, 10)
        for j = 0, 9 do
            assert.eq(a:get(j).kind, j)
        end
    end)
end)

assert.describe("arena: type arena", function()
    assert.it("alloc and read back", function()
        local a = arena.new_type_arena(4)
        local i = a:alloc()
        a:get(i).tag = defs.TAG_NUMBER
        assert.eq(a:get(0).tag, defs.TAG_NUMBER)
    end)
end)

assert.describe("arena: field arena", function()
    assert.it("alloc and read back", function()
        local a = arena.new_field_arena(4)
        local i = a:alloc()
        local f = a:get(i)
        f.name_id = 42
        f.type_id = 7
        f.optional = 1
        assert.eq(a:get(0).name_id, 42)
        assert.eq(a:get(0).type_id, 7)
        assert.eq(a:get(0).optional, 1)
    end)
end)

assert.describe("arena: list pool", function()
    assert.it("mark/push/since", function()
        local lp = arena.new_list_pool(8)
        local m = lp:mark()
        lp:push(10)
        lp:push(20)
        lp:push(30)
        local start, len = lp:since(m)
        assert.eq(start, 0)
        assert.eq(len, 3)
        assert.eq(lp:get(start), 10)
        assert.eq(lp:get(start + 1), 20)
        assert.eq(lp:get(start + 2), 30)
    end)
    assert.it("nested lists", function()
        local lp = arena.new_list_pool(8)
        local m1 = lp:mark()
        lp:push(1)
        lp:push(2)
        local s1, l1 = lp:since(m1)
        local m2 = lp:mark()
        lp:push(10)
        lp:push(20)
        lp:push(30)
        local s2, l2 = lp:since(m2)
        assert.eq(l1, 2)
        assert.eq(l2, 3)
        assert.eq(lp:get(s1), 1)
        assert.eq(lp:get(s2), 10)
    end)
    assert.it("grow beyond initial capacity", function()
        local lp = arena.new_list_pool(2)
        for i = 0, 99 do lp:push(i) end
        assert.eq(lp.len, 100)
        for i = 0, 99 do
            assert.eq(lp:get(i), i)
        end
    end)
    assert.it("reset", function()
        local lp = arena.new_list_pool(8)
        lp:push(1)
        lp:push(2)
        lp:reset()
        assert.eq(lp.len, 0)
    end)
end)

---------------------------------------------------------------------------
-- lex.lua
---------------------------------------------------------------------------

assert.describe("lex: simple tokens", function()
    assert.it("empty source yields EOF", function()
        local L = lex.new("", "test")
        assert.eq(L.tk, defs.TK_EOF)
    end)
    assert.it("single keyword", function()
        local L = lex.new("local", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
    end)
    assert.it("multiple keywords", function()
        local L = lex.new("local function end", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        L:next()
        assert.eq(L.tk, defs.TK_FUNCTION)
        L:next()
        assert.eq(L.tk, defs.TK_END)
        L:next()
        assert.eq(L.tk, defs.TK_EOF)
    end)
    assert.it("identifier", function()
        local L = lex.new("foo", "test")
        assert.eq(L.tk, defs.TK_NAME)
        assert.eq(intern.get(L.pool, L.val), "foo")
    end)
    assert.it("operators", function()
        local L = lex.new("+ - * / % ^ # == ~= <= >= < > = ( ) [ ] { } ; : , .", "test")
        local expected = {
            defs.TK_PLUS, defs.TK_MINUS, defs.TK_STAR, defs.TK_SLASH,
            defs.TK_PERCENT, defs.TK_CARET, defs.TK_HASH,
            defs.TK_EQ, defs.TK_NE, defs.TK_LE, defs.TK_GE,
            defs.TK_LT, defs.TK_GT, defs.TK_ASSIGN,
            defs.TK_LPAREN, defs.TK_RPAREN,
            defs.TK_LBRACKET, defs.TK_RBRACKET,
            defs.TK_LBRACE, defs.TK_RBRACE,
            defs.TK_SEMICOLON, defs.TK_COLON, defs.TK_COMMA, defs.TK_DOT,
            defs.TK_EOF,
        }
        for i, exp in ipairs(expected) do
            assert.eq(L.tk, exp, "token " .. i .. ": expected " .. exp .. " got " .. L.tk)
            if exp ~= defs.TK_EOF then L:next() end
        end
    end)
    assert.it("concat and dots", function()
        local L = lex.new(".. ...", "test")
        assert.eq(L.tk, defs.TK_CONCAT)
        L:next()
        assert.eq(L.tk, defs.TK_DOTS)
    end)
    assert.it("label", function()
        local L = lex.new("::foo::", "test")
        assert.eq(L.tk, defs.TK_LABEL)
        L:next()
        assert.eq(L.tk, defs.TK_NAME)
        L:next()
        assert.eq(L.tk, defs.TK_LABEL)
    end)
end)

assert.describe("lex: numbers", function()
    assert.it("integer", function()
        local L = lex.new("42", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
        assert.eq(L.numvals[L.val], 42)
    end)
    assert.it("float", function()
        local L = lex.new("3.14", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
        assert.ok(math.abs(L.numvals[L.val] - 3.14) < 1e-10)
    end)
    assert.it("hex", function()
        local L = lex.new("0xFF", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
        assert.eq(L.numvals[L.val], 255)
    end)
    assert.it("scientific notation", function()
        local L = lex.new("1e10", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
        assert.eq(L.numvals[L.val], 1e10)
    end)
    assert.it("number starting with dot", function()
        local L = lex.new(".5", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
        assert.eq(L.numvals[L.val], 0.5)
    end)
end)

assert.describe("lex: strings", function()
    assert.it("double-quoted string", function()
        local L = lex.new('"hello"', "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "hello")
    end)
    assert.it("single-quoted string", function()
        local L = lex.new("'world'", "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "world")
    end)
    assert.it("string with escapes", function()
        local L = lex.new('"hello\\nworld"', "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "hello\nworld")
    end)
    assert.it("string with hex escape", function()
        local L = lex.new('"\\x41"', "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "A")
    end)
    assert.it("string with decimal escape", function()
        local L = lex.new('"\\65"', "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "A")
    end)
    assert.it("long string", function()
        local L = lex.new("[[hello world]]", "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "hello world")
    end)
    assert.it("long string with equals", function()
        local L = lex.new("[=[hello]=]", "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "hello")
    end)
    assert.it("empty string", function()
        local L = lex.new('""', "test")
        assert.eq(L.tk, defs.TK_STRING)
        assert.eq(intern.get(L.pool, L.val), "")
    end)
    assert.it("unterminated string errors", function()
        assert.throws(function()
            lex.new('"hello', "test")
        end)
    end)
end)

assert.describe("lex: comments", function()
    assert.it("line comment is skipped", function()
        local L = lex.new("-- a comment\n42", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
    end)
    assert.it("block comment is skipped", function()
        local L = lex.new("--[[ block comment ]] 42", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
    end)
    assert.it("long block comment is skipped", function()
        local L = lex.new("--[=[ block\ncomment ]=] 42", "test")
        assert.eq(L.tk, defs.TK_NUMBER)
    end)
end)

assert.describe("lex: annotations", function()
    assert.it("captures --: type annotation", function()
        local L = lex.new("--: number\nlocal x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        local ann = L.annotations[1]
        assert.ok(ann, "annotation on line 1")
        assert.eq(ann.kind, defs.ANN_TYPE)
        assert.eq(ann.content, "number")
    end)
    assert.it("captures --:: declaration annotation", function()
        local L = lex.new("--:: Foo = { x: number }\nlocal x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        local ann = L.annotations[1]
        assert.ok(ann, "annotation on line 1")
        assert.eq(ann.kind, defs.ANN_DECL)
        assert.eq(ann.content, "Foo = { x: number }")
    end)
    assert.it("captures block annotation --[[: type ]]", function()
        local L = lex.new("--[[:number]] local x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        local ann = L.annotations[1]
        assert.ok(ann, "annotation on line 1")
        assert.eq(ann.kind, defs.ANN_TYPE)
        assert.eq(ann.content, "number")
    end)
    assert.it("captures block declaration --[[:: Name = T ]]", function()
        local L = lex.new("--[[::Foo = number]] local x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        local ann = L.annotations[1]
        assert.ok(ann, "annotation on line 1")
        assert.eq(ann.kind, defs.ANN_DECL)
        assert.eq(ann.content, "Foo = number")
    end)
    assert.it("captures --:<T> type args annotation", function()
        local L = lex.new("--:<T, U>\nlocal x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        local ann = L.annotations[1]
        assert.ok(ann, "annotation on line 1")
        assert.eq(ann.kind, defs.ANN_TYPE_ARGS)
        assert.eq(ann.content, "<T, U>")
    end)
end)

assert.describe("lex: line and column tracking", function()
    assert.it("tracks line numbers across newlines", function()
        local L = lex.new("a\nb\nc", "test")
        assert.eq(L.tk, defs.TK_NAME)
        -- After first next(), we consumed 'a' and are on line 1
        -- Exact line tracking depends on when _lex records _tk_line
        L:next()
        assert.eq(L.tk, defs.TK_NAME)
        L:next()
        assert.eq(L.tk, defs.TK_NAME)
        L:next()
        assert.eq(L.tk, defs.TK_EOF)
    end)
end)

assert.describe("lex: lookahead", function()
    assert.it("lookahead returns next token without consuming", function()
        local L = lex.new("local x", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
        local la = L:lookahead()
        assert.eq(la, defs.TK_NAME)
        -- Current token unchanged
        assert.eq(L.tk, defs.TK_LOCAL)
        -- Now consume
        L:next()
        assert.eq(L.tk, defs.TK_NAME)
    end)
end)

assert.describe("lex: expect and opt", function()
    assert.it("expect succeeds on correct token", function()
        local L = lex.new("local x", "test")
        L:expect(defs.TK_LOCAL)
        assert.eq(L.tk, defs.TK_NAME)
    end)
    assert.it("expect errors on wrong token", function()
        assert.throws(function()
            local L = lex.new("local x", "test")
            L:expect(defs.TK_IF)
        end)
    end)
    assert.it("opt returns true and advances on match", function()
        local L = lex.new("local x", "test")
        assert.ok(L:opt(defs.TK_LOCAL))
        assert.eq(L.tk, defs.TK_NAME)
    end)
    assert.it("opt returns false and does not advance on mismatch", function()
        local L = lex.new("local x", "test")
        assert.eq(L:opt(defs.TK_IF), false)
        assert.eq(L.tk, defs.TK_LOCAL)
    end)
end)

assert.describe("lex: edge cases", function()
    assert.it("shebang is skipped", function()
        local L = lex.new("#!/usr/bin/env luajit\nlocal x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
    end)
    assert.it("BOM is skipped", function()
        local L = lex.new("\xEF\xBB\xBFlocal x = 1", "test")
        assert.eq(L.tk, defs.TK_LOCAL)
    end)
    assert.it("all keywords tokenize correctly", function()
        local pool = intern.new()
        for i, kw in ipairs(defs.keywords) do
            local L = lex.new(kw, "test", pool)
            assert.eq(L.tk, i - 1, "keyword '" .. kw .. "' should be token " .. (i - 1))
        end
    end)
end)

assert.describe("lex: real Lua code", function()
    assert.it("tokenizes a simple function", function()
        local src = "local function add(a, b) return a + b end"
        local L = lex.new(src, "test")
        local tokens = {}
        while L.tk ~= defs.TK_EOF do
            tokens[#tokens + 1] = L.tk
            L:next()
        end
        assert.eq(tokens[1], defs.TK_LOCAL)
        assert.eq(tokens[2], defs.TK_FUNCTION)
        assert.eq(tokens[3], defs.TK_NAME)     -- add
        assert.eq(tokens[4], defs.TK_LPAREN)
        assert.eq(tokens[5], defs.TK_NAME)     -- a
        assert.eq(tokens[6], defs.TK_COMMA)
        assert.eq(tokens[7], defs.TK_NAME)     -- b
        assert.eq(tokens[8], defs.TK_RPAREN)
        assert.eq(tokens[9], defs.TK_RETURN)
        assert.eq(tokens[10], defs.TK_NAME)    -- a
        assert.eq(tokens[11], defs.TK_PLUS)
        assert.eq(tokens[12], defs.TK_NAME)    -- b
        assert.eq(tokens[13], defs.TK_END)
        assert.eq(#tokens, 13)
    end)
    assert.it("tokenizes table constructor", function()
        local src = '{ x = 1, ["y"] = true, 3 }'
        local L = lex.new(src, "test")
        assert.eq(L.tk, defs.TK_LBRACE)
        L:next(); assert.eq(L.tk, defs.TK_NAME)      -- x
        L:next(); assert.eq(L.tk, defs.TK_ASSIGN)     -- =
        L:next(); assert.eq(L.tk, defs.TK_NUMBER)     -- 1
        L:next(); assert.eq(L.tk, defs.TK_COMMA)
        L:next(); assert.eq(L.tk, defs.TK_LBRACKET)
        L:next(); assert.eq(L.tk, defs.TK_STRING)     -- "y"
        L:next(); assert.eq(L.tk, defs.TK_RBRACKET)
        L:next(); assert.eq(L.tk, defs.TK_ASSIGN)
        L:next(); assert.eq(L.tk, defs.TK_TRUE)
        L:next(); assert.eq(L.tk, defs.TK_COMMA)
        L:next(); assert.eq(L.tk, defs.TK_NUMBER)     -- 3
        L:next(); assert.eq(L.tk, defs.TK_RBRACE)
    end)
end)

---------------------------------------------------------------------------
-- parse.lua
---------------------------------------------------------------------------

-- Helper: parse source, return result table
local function p(src)
    return parse.parse(src, "test")
end

-- Helper: get the single statement from a chunk
local function first_stmt(r)
    local root = r.nodes:get(r.root)
    local id = r.lists:get(root.data[0])
    return r.nodes:get(id), id
end

assert.describe("parse: literals", function()
    assert.it("parses number literal", function()
        local r = p("return 42")
        local ret = first_stmt(r)
        assert.eq(ret.kind, defs.NODE_RETURN_STMT)
        local expr_id = r.lists:get(ret.data[0])
        local expr = r.nodes:get(expr_id)
        assert.eq(expr.kind, defs.NODE_LITERAL)
        assert.eq(expr.data[0], defs.LIT_NUMBER)
    end)
    assert.it("parses string literal", function()
        local r = p('return "hello"')
        local ret = first_stmt(r)
        local expr = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(expr.kind, defs.NODE_LITERAL)
        assert.eq(expr.data[0], defs.LIT_STRING)
        assert.eq(intern.get(r.pool, expr.data[1]), "hello")
    end)
    assert.it("parses nil", function()
        local r = p("return nil")
        local ret = first_stmt(r)
        local expr = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(expr.data[0], defs.LIT_NIL)
    end)
    assert.it("parses true and false", function()
        local r = p("return true, false")
        local ret = first_stmt(r)
        assert.eq(ret.data[1], 2)
        local t = r.nodes:get(r.lists:get(ret.data[0]))
        local f = r.nodes:get(r.lists:get(ret.data[0] + 1))
        assert.eq(t.data[0], defs.LIT_BOOLEAN)
        assert.eq(t.data[1], 1)
        assert.eq(f.data[0], defs.LIT_BOOLEAN)
        assert.eq(f.data[1], 0)
    end)
    assert.it("parses vararg", function()
        local r = p("return ...")
        local ret = first_stmt(r)
        local expr = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(expr.kind, defs.NODE_VARARG_EXPR)
    end)
end)

assert.describe("parse: expressions", function()
    assert.it("parses identifier", function()
        local r = p("return x")
        local ret = first_stmt(r)
        local expr = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(expr.kind, defs.NODE_IDENTIFIER)
        assert.eq(intern.get(r.pool, expr.data[0]), "x")
    end)
    assert.it("binary precedence: + vs *", function()
        local r = p("return 1 + 2 * 3")
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.kind, defs.NODE_BINARY_EXPR)
        assert.eq(top.data[0], defs.OP_ADD)
        local rhs = r.nodes:get(top.data[2])
        assert.eq(rhs.data[0], defs.OP_MUL)
    end)
    assert.it("right-associative power", function()
        local r = p("return 2 ^ 3 ^ 4")
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.data[0], defs.OP_POW)
        -- right child should also be POW
        local rhs = r.nodes:get(top.data[2])
        assert.eq(rhs.data[0], defs.OP_POW)
    end)
    assert.it("right-associative concat", function()
        local r = p('return a .. b .. c')
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.data[0], defs.OP_CONCAT)
        local rhs = r.nodes:get(top.data[2])
        assert.eq(rhs.data[0], defs.OP_CONCAT)
    end)
    assert.it("unary minus and power", function()
        -- -a^2 should be -(a^2)
        local r = p("return -a^2")
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.kind, defs.NODE_UNARY_EXPR)
        assert.eq(top.data[0], defs.OP_UNM)
        local inner = r.nodes:get(top.data[1])
        assert.eq(inner.kind, defs.NODE_BINARY_EXPR)
        assert.eq(inner.data[0], defs.OP_POW)
    end)
    assert.it("not a and b", function()
        local r = p("return not a and b")
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.kind, defs.NODE_BINARY_EXPR)
        assert.eq(top.data[0], defs.OP_AND)
        local lhs = r.nodes:get(top.data[1])
        assert.eq(lhs.kind, defs.NODE_UNARY_EXPR)
        assert.eq(lhs.data[0], defs.OP_NOT)
    end)
    assert.it("length operator", function()
        local r = p("return #t")
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.kind, defs.NODE_UNARY_EXPR)
        assert.eq(top.data[0], defs.OP_LEN)
    end)
end)

assert.describe("parse: suffixed expressions", function()
    assert.it("field access", function()
        local r = p("return a.b")
        local ret = first_stmt(r)
        local expr = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(expr.kind, defs.NODE_FIELD_EXPR)
        local obj = r.nodes:get(expr.data[0])
        assert.eq(obj.kind, defs.NODE_IDENTIFIER)
        assert.eq(intern.get(r.pool, expr.data[1]), "b")
    end)
    assert.it("index access", function()
        local r = p("return a[1]")
        local ret = first_stmt(r)
        local expr = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(expr.kind, defs.NODE_INDEX_EXPR)
    end)
    assert.it("function call", function()
        local r = p("return f(x, y)")
        local ret = first_stmt(r)
        local call = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(call.kind, defs.NODE_CALL_EXPR)
        assert.eq(call.data[2], 2)  -- 2 args
    end)
    assert.it("method call", function()
        local r = p("return a:b(x)")
        local ret = first_stmt(r)
        local call = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(call.kind, defs.NODE_METHOD_CALL)
        assert.eq(intern.get(r.pool, call.data[1]), "b")
        assert.eq(call.data[3], 1)  -- 1 arg
    end)
    assert.it("string call", function()
        local r = p('f "hello"')
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_EXPR_STMT)
        local call = r.nodes:get(stmt.data[0])
        assert.eq(call.kind, defs.NODE_CALL_EXPR)
        assert.eq(call.data[2], 1)
    end)
    assert.it("table call", function()
        local r = p("f {1, 2}")
        local stmt = first_stmt(r)
        local call = r.nodes:get(stmt.data[0])
        assert.eq(call.kind, defs.NODE_CALL_EXPR)
        assert.eq(call.data[2], 1)
    end)
    assert.it("chained access", function()
        local r = p("return a.b.c[d]:e(f)")
        local ret = first_stmt(r)
        local top = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(top.kind, defs.NODE_METHOD_CALL)
    end)
end)

assert.describe("parse: table constructors", function()
    assert.it("empty table", function()
        local r = p("return {}")
        local ret = first_stmt(r)
        local tbl = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(tbl.kind, defs.NODE_TABLE_EXPR)
        assert.eq(tbl.data[1], 0)
    end)
    assert.it("positional fields", function()
        local r = p("return {1, 2, 3}")
        local ret = first_stmt(r)
        local tbl = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(tbl.data[1], 3)
        local f0 = r.nodes:get(r.lists:get(tbl.data[0]))
        assert.eq(f0.kind, defs.NODE_TABLE_FIELD)
        assert.eq(f0.data[0], -1)  -- positional
    end)
    assert.it("named fields", function()
        local r = p("return {x = 1, y = 2}")
        local ret = first_stmt(r)
        local tbl = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(tbl.data[1], 2)
        local f0 = r.nodes:get(r.lists:get(tbl.data[0]))
        assert.eq(f0.kind, defs.NODE_TABLE_FIELD)
        assert.ok(f0.data[0] ~= -1)  -- has key
    end)
    assert.it("computed fields", function()
        local r = p("return {[1] = 'a'}")
        local ret = first_stmt(r)
        local tbl = r.nodes:get(r.lists:get(ret.data[0]))
        local f0 = r.nodes:get(r.lists:get(tbl.data[0]))
        assert.eq(bit.band(f0.flags, defs.FLAG_COMPUTED), defs.FLAG_COMPUTED)
    end)
    assert.it("mixed fields", function()
        local r = p("return {1, x = 2, [3] = 4}")
        local ret = first_stmt(r)
        local tbl = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(tbl.data[1], 3)
    end)
end)

assert.describe("parse: function expressions", function()
    assert.it("simple function", function()
        local r = p("return function(a, b) return a + b end")
        local ret = first_stmt(r)
        local func = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(func.kind, defs.NODE_FUNC_EXPR)
        assert.eq(func.data[1], 2)  -- 2 params
        assert.eq(func.data[3], 1)  -- 1 body stmt
    end)
    assert.it("vararg function", function()
        local r = p("return function(...) end")
        local ret = first_stmt(r)
        local func = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(func.kind, defs.NODE_FUNC_EXPR)
        assert.eq(bit.band(func.flags, defs.FLAG_VARARG), defs.FLAG_VARARG)
    end)
    assert.it("params then vararg", function()
        local r = p("return function(a, b, ...) end")
        local ret = first_stmt(r)
        local func = r.nodes:get(r.lists:get(ret.data[0]))
        assert.eq(func.data[1], 2)  -- 2 named params
        assert.eq(bit.band(func.flags, defs.FLAG_VARARG), defs.FLAG_VARARG)
    end)
end)

assert.describe("parse: statements", function()
    assert.it("local declaration", function()
        local r = p("local x = 1")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_LOCAL_STMT)
        assert.eq(stmt.data[1], 1)  -- 1 name
        assert.eq(stmt.data[3], 1)  -- 1 expr
    end)
    assert.it("local multi-decl", function()
        local r = p("local a, b, c = 1, 2")
        local stmt = first_stmt(r)
        assert.eq(stmt.data[1], 3)  -- 3 names
        assert.eq(stmt.data[3], 2)  -- 2 exprs
    end)
    assert.it("local without init", function()
        local r = p("local x")
        local stmt = first_stmt(r)
        assert.eq(stmt.data[1], 1)
        assert.eq(stmt.data[3], 0)
    end)
    assert.it("assignment", function()
        local r = p("x = 1")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_ASSIGN_STMT)
        assert.eq(stmt.data[1], 1)  -- 1 target
        assert.eq(stmt.data[3], 1)  -- 1 expr
    end)
    assert.it("multi-assignment", function()
        local r = p("a, b = 1, 2")
        local stmt = first_stmt(r)
        assert.eq(stmt.data[1], 2)
        assert.eq(stmt.data[3], 2)
    end)
    assert.it("expression statement (call)", function()
        local r = p("print(x)")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_EXPR_STMT)
        local call = r.nodes:get(stmt.data[0])
        assert.eq(call.kind, defs.NODE_CALL_EXPR)
    end)
    assert.it("return empty", function()
        local r = p("return")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_RETURN_STMT)
        assert.eq(stmt.data[1], 0)
    end)
    assert.it("return with values", function()
        local r = p("return 1, 2, 3")
        local stmt = first_stmt(r)
        assert.eq(stmt.data[1], 3)
    end)
    assert.it("break", function()
        local r = p("while true do break end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_WHILE_STMT)
        local body_id = r.lists:get(stmt.data[1])
        local brk = r.nodes:get(body_id)
        assert.eq(brk.kind, defs.NODE_BREAK_STMT)
    end)
    assert.it("goto and label", function()
        local r = p("goto done; ::done::")
        local root = r.nodes:get(r.root)
        assert.eq(root.data[1], 2)  -- 2 statements
        local goto_stmt = r.nodes:get(r.lists:get(root.data[0]))
        assert.eq(goto_stmt.kind, defs.NODE_GOTO_STMT)
        local label_stmt = r.nodes:get(r.lists:get(root.data[0] + 1))
        assert.eq(label_stmt.kind, defs.NODE_LABEL_STMT)
        -- Both should reference the same label name
        assert.eq(goto_stmt.data[0], label_stmt.data[0])
    end)
end)

assert.describe("parse: control flow", function()
    assert.it("if/then/end", function()
        local r = p("if x then return 1 end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_IF_STMT)
        assert.eq(stmt.data[1], 1)  -- 1 clause
    end)
    assert.it("if/elseif/else", function()
        local r = p("if a then x() elseif b then y() else z() end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_IF_STMT)
        assert.eq(stmt.data[1], 3)  -- 3 clauses
        -- else clause has test = -1
        local else_id = r.lists:get(stmt.data[0] + 2)
        local else_c = r.nodes:get(else_id)
        assert.eq(else_c.kind, defs.NODE_IF_CLAUSE)
        assert.eq(else_c.data[0], -1)
    end)
    assert.it("while loop", function()
        local r = p("while x > 0 do x = x - 1 end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_WHILE_STMT)
        -- test is a binary expr
        local test = r.nodes:get(stmt.data[0])
        assert.eq(test.kind, defs.NODE_BINARY_EXPR)
    end)
    assert.it("repeat/until", function()
        local r = p("repeat x = x + 1 until x > 10")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_REPEAT_STMT)
    end)
    assert.it("do block", function()
        local r = p("do local x = 1 end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_DO_STMT)
        assert.eq(stmt.data[1], 1)  -- 1 body stmt
    end)
    assert.it("numeric for", function()
        local r = p("for i = 1, 10, 2 do print(i) end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_FOR_NUM)
        assert.eq(stmt.data[5], 1)  -- 1 body stmt
        -- step is a node (not -1)
        assert.ok(stmt.data[3] >= 0, "step should be a node id")
    end)
    assert.it("numeric for without step", function()
        local r = p("for i = 1, 10 do end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_FOR_NUM)
        assert.eq(stmt.data[3], -1)  -- no step
    end)
    assert.it("generic for", function()
        local r = p("for k, v in pairs(t) do print(k, v) end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_FOR_IN)
        assert.eq(stmt.data[1], 2)  -- 2 names
        assert.eq(stmt.data[3], 1)  -- 1 expr (pairs(t))
        assert.eq(stmt.data[5], 1)  -- 1 body stmt
    end)
end)

assert.describe("parse: function declarations", function()
    assert.it("global function", function()
        local r = p("function foo(a) return a end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_FUNC_DECL)
        local name = r.nodes:get(stmt.data[0])
        assert.eq(name.kind, defs.NODE_IDENTIFIER)
        assert.eq(intern.get(r.pool, name.data[0]), "foo")
        assert.eq(stmt.data[2], 1)  -- 1 param
    end)
    assert.it("local function", function()
        local r = p("local function bar(x) end")
        local stmt = first_stmt(r)
        assert.eq(stmt.kind, defs.NODE_FUNC_DECL)
        assert.eq(bit.band(stmt.flags, defs.FLAG_LOCAL), defs.FLAG_LOCAL)
    end)
    assert.it("dotted function name", function()
        local r = p("function M.foo.bar(x) end")
        local stmt = first_stmt(r)
        local name = r.nodes:get(stmt.data[0])
        assert.eq(name.kind, defs.NODE_FIELD_EXPR)
        assert.eq(intern.get(r.pool, name.data[1]), "bar")
        local inner = r.nodes:get(name.data[0])
        assert.eq(inner.kind, defs.NODE_FIELD_EXPR)
    end)
    assert.it("method declaration adds self", function()
        local r = p("function M:method(a) end")
        local stmt = first_stmt(r)
        assert.eq(stmt.data[2], 2)  -- 2 params: self, a
        local p0 = r.lists:get(stmt.data[1])
        assert.eq(intern.get(r.pool, p0), "self")
        local p1 = r.lists:get(stmt.data[1] + 1)
        assert.eq(intern.get(r.pool, p1), "a")
    end)
    assert.it("vararg function declaration", function()
        local r = p("function f(...) end")
        local stmt = first_stmt(r)
        assert.eq(bit.band(stmt.flags, defs.FLAG_VARARG), defs.FLAG_VARARG)
    end)
end)

assert.describe("parse: real code", function()
    assert.it("parses a complete module pattern", function()
        local src = [[
local M = {}

function M.new(x, y)
    return { x = x, y = y }
end

function M:length()
    return (self.x^2 + self.y^2)^0.5
end

return M
]]
        local r = p(src)
        local root = r.nodes:get(r.root)
        assert.eq(root.kind, defs.NODE_CHUNK)
        assert.eq(root.data[1], 4)  -- local, function, function, return
    end)
    assert.it("parses nested control flow", function()
        local src = [[
if a then
    for i = 1, 10 do
        if i > 5 then
            break
        end
    end
elseif b then
    repeat
        x = x + 1
    until x > 100
else
    do
        local y = 42
    end
end
]]
        local r = p(src)
        local root = r.nodes:get(r.root)
        assert.eq(root.data[1], 1)  -- 1 top-level if stmt
    end)
    assert.it("parses its own source files", function()
        local files = {
            "lib/type/static/v2/intern.lua",
            "lib/type/static/v2/arena.lua",
            "lib/type/static/v2/defs.lua",
            "lib/type/static/v2/lex.lua",
            "lib/type/static/v2/parse.lua",
        }
        for _, path in ipairs(files) do
            local f = io.open(path, "r")
            if f then
                local src = f:read("*a")
                f:close()
                local ok, err = pcall(parse.parse, src, path)
                assert.ok(ok, path .. ": " .. tostring(err))
            end
        end
    end)
end)

---------------------------------------------------------------------------
-- ann.lua
---------------------------------------------------------------------------

assert.describe("ann: primitive types", function()
    assert.it("parses number", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "number" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_NUMBER)
    end)
    assert.it("parses string", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "string" } }, nil, "test")
        assert.eq(r.types:get(r.results[1].type_id).tag, defs.TAG_STRING)
    end)
    assert.it("parses nil", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "nil" } }, nil, "test")
        assert.eq(r.types:get(r.results[1].type_id).tag, defs.TAG_NIL)
    end)
    assert.it("parses boolean", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "boolean" } }, nil, "test")
        assert.eq(r.types:get(r.results[1].type_id).tag, defs.TAG_BOOLEAN)
    end)
    assert.it("parses any", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "any" } }, nil, "test")
        assert.eq(r.types:get(r.results[1].type_id).tag, defs.TAG_ANY)
    end)
    assert.it("parses integer", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "integer" } }, nil, "test")
        assert.eq(r.types:get(r.results[1].type_id).tag, defs.TAG_INTEGER)
    end)
end)

assert.describe("ann: composite types", function()
    assert.it("parses union", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "string | number" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_UNION)
        assert.eq(t.data[1], 2)  -- 2 members
    end)
    assert.it("parses nullable", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "string?" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_UNION)
        assert.eq(t.data[1], 2)  -- string | nil
    end)
    assert.it("parses array", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "number[]" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_TABLE)
        -- Should have indexer [number]: number
        assert.eq(t.data[3], 2)  -- indexer list len (key_type, val_type)
    end)
    assert.it("parses function type", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "(number, string) -> boolean" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_FUNCTION)
        assert.eq(t.data[1], 2)  -- 2 params
        assert.eq(t.data[3], 1)  -- 1 return
    end)
    assert.it("parses function with multi-return", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "(string) -> (number, string)" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_FUNCTION)
        assert.eq(t.data[1], 1)  -- 1 param
        assert.eq(t.data[3], 2)  -- 2 returns
    end)
    assert.it("parses table type", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "{ x: number, y?: string }" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_TABLE)
        assert.eq(t.data[1], 2)  -- 2 fields
        -- Second field should be optional
        local f1_idx = r.lists:get(t.data[0] + 1)
        local f1 = r.fields:get(f1_idx)
        assert.eq(f1.optional, 1)
    end)
    assert.it("parses table with indexer", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "{ [string]: number }" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_TABLE)
        assert.eq(t.data[3], 2)  -- indexer list: (key_type, val_type)
    end)
    assert.it("parses named type", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "Foo" } }, pool, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_NAMED)
        assert.eq(intern.get(pool, t.data[0]), "Foo")
    end)
    assert.it("parses generic instantiation", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "Array<number>" } }, pool, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_NAMED)
        assert.eq(intern.get(pool, t.data[0]), "Array")
        assert.eq(t.data[2], 1)  -- 1 type arg
    end)
    assert.it("parses forall", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "<T>(T) -> T" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_FORALL)
        assert.eq(t.data[1], 1)  -- 1 type param
        -- body should be a function
        local body = r.types:get(t.data[2])
        assert.eq(body.tag, defs.TAG_FUNCTION)
    end)
    assert.it("parses string literal type", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = '"hello"' } }, pool, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_LITERAL)
        assert.eq(t.data[0], defs.LIT_STRING)
        assert.eq(intern.get(pool, t.data[1]), "hello")
    end)
    assert.it("parses intrinsic", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE, content = "$Keys<Point>" } }, pool, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_TYPE_CALL)
        local callee = r.types:get(t.data[0])
        assert.eq(callee.tag, defs.TAG_INTRINSIC)
    end)
end)

assert.describe("ann: declarations", function()
    assert.it("parses simple type alias", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_DECL, content = "Name = string" } }, pool, "test")
        local res = r.results[1]
        assert.eq(res.kind, defs.ANN_DECL)
        assert.eq(intern.get(pool, res.name_id), "Name")
        assert.eq(r.types:get(res.type_id).tag, defs.TAG_STRING)
    end)
    assert.it("parses generic type alias", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_DECL, content = "Pair<A, B> = { first: A, second: B }" } }, pool, "test")
        local res = r.results[1]
        assert.eq(intern.get(pool, res.name_id), "Pair")
        assert.eq(res.type_params_len, 2)
        assert.eq(r.types:get(res.type_id).tag, defs.TAG_TABLE)
    end)
    assert.it("parses newtype", function()
        local pool = intern.new()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_DECL, content = "newtype UserId = number" } }, pool, "test")
        local res = r.results[1]
        assert.ok(res.newtype)
        assert.eq(intern.get(pool, res.name_id), "UserId")
        assert.eq(r.types:get(res.type_id).tag, defs.TAG_NOMINAL)
    end)
end)

assert.describe("ann: match types", function()
    assert.it("parses match type", function()
        local r = ann.parse_annotations(
            { [1] = { kind = defs.ANN_TYPE,
                content = "match T { number => string, boolean => string }" } }, nil, "test")
        local t = r.types:get(r.results[1].type_id)
        assert.eq(t.tag, defs.TAG_MATCH_TYPE)
        assert.eq(t.data[2], 4)  -- 4 items in arms list (2 pairs)
    end)
end)

assert.describe("ann: integration with parser", function()
    assert.it("round-trip: parse source with annotations, then parse annotations", function()
        local src = [[
--: number
local x = 1
--:: Pair<A, B> = { first: A, second: B }
--: string | number
local y
]]
        local r = parse.parse(src, "test")
        local ann_result = ann.parse_annotations(r.lexer.annotations, r.pool, "test")
        -- Line 1: type annotation = number
        assert.ok(ann_result.results[1])
        assert.eq(ann_result.results[1].kind, defs.ANN_TYPE)
        assert.eq(r.types or true, true)  -- just checking it doesn't crash
        local t1 = ann_result.types:get(ann_result.results[1].type_id)
        assert.eq(t1.tag, defs.TAG_NUMBER)
        -- Line 3: declaration
        assert.ok(ann_result.results[3])
        assert.eq(ann_result.results[3].kind, defs.ANN_DECL)
        -- Line 4: union
        assert.ok(ann_result.results[4])
        local t4 = ann_result.types:get(ann_result.results[4].type_id)
        assert.eq(t4.tag, defs.TAG_UNION)
    end)
end)

---------------------------------------------------------------------------
-- types.lua: type construction + union-find
---------------------------------------------------------------------------

local function new_ctx()
    local pool = intern.new()
    return types_mod.new_ctx(pool), pool
end

assert.describe("types: singletons", function()
    assert.it("singletons are at fixed IDs 0-6", function()
        local ctx = new_ctx()
        assert.eq(ctx.T_NIL,     0)
        assert.eq(ctx.T_BOOLEAN, 1)
        assert.eq(ctx.T_NUMBER,  2)
        assert.eq(ctx.T_STRING,  3)
        assert.eq(ctx.T_ANY,     4)
        assert.eq(ctx.T_NEVER,   5)
        assert.eq(ctx.T_INTEGER, 6)
    end)
    assert.it("singleton tags are correct", function()
        local ctx = new_ctx()
        assert.eq(ctx.types:get(ctx.T_NIL).tag,     defs.TAG_NIL)
        assert.eq(ctx.types:get(ctx.T_BOOLEAN).tag, defs.TAG_BOOLEAN)
        assert.eq(ctx.types:get(ctx.T_NUMBER).tag,  defs.TAG_NUMBER)
        assert.eq(ctx.types:get(ctx.T_STRING).tag,  defs.TAG_STRING)
        assert.eq(ctx.types:get(ctx.T_ANY).tag,     defs.TAG_ANY)
        assert.eq(ctx.types:get(ctx.T_NEVER).tag,   defs.TAG_NEVER)
        assert.eq(ctx.types:get(ctx.T_INTEGER).tag, defs.TAG_INTEGER)
    end)
    assert.it("find on singleton returns self", function()
        local ctx = new_ctx()
        assert.eq(types_mod.find(ctx, ctx.T_NUMBER), ctx.T_NUMBER)
        assert.eq(types_mod.find(ctx, ctx.T_STRING), ctx.T_STRING)
    end)
end)

assert.describe("types: type variables", function()
    assert.it("make_var creates a TAG_VAR", function()
        local ctx = new_ctx()
        local v = types_mod.make_var(ctx, 0)
        assert.eq(ctx.types:get(v).tag, defs.TAG_VAR)
    end)
    assert.it("find on unbound var returns self", function()
        local ctx = new_ctx()
        local v = types_mod.make_var(ctx, 0)
        assert.eq(types_mod.find(ctx, v), v)
    end)
    assert.it("bound var follows chain", function()
        local ctx = new_ctx()
        local v = types_mod.make_var(ctx, 0)
        -- bind v to T_NUMBER
        ctx.types:get(v).data[2] = ctx.T_NUMBER
        assert.eq(types_mod.find(ctx, v), ctx.T_NUMBER)
    end)
    assert.it("find does path compression on chain of vars", function()
        local ctx = new_ctx()
        local v1 = types_mod.make_var(ctx, 0)
        local v2 = types_mod.make_var(ctx, 0)
        local v3 = types_mod.make_var(ctx, 0)
        -- v1 -> v2 -> v3 -> T_STRING
        ctx.types:get(v1).data[2] = v2
        ctx.types:get(v2).data[2] = v3
        ctx.types:get(v3).data[2] = ctx.T_STRING
        assert.eq(types_mod.find(ctx, v1), ctx.T_STRING)
        -- After find, v1 should be compressed to T_STRING
        assert.eq(ctx.types:get(v1).data[2], ctx.T_STRING)
    end)
end)

assert.describe("types: literals", function()
    assert.it("make_literal creates TAG_LITERAL", function()
        local ctx, pool = new_ctx()
        local sid = intern.intern(pool, "hello")
        local lit = types_mod.make_literal(ctx, defs.LIT_STRING, sid)
        local t = ctx.types:get(lit)
        assert.eq(t.tag, defs.TAG_LITERAL)
        assert.eq(t.data[0], defs.LIT_STRING)
        assert.eq(t.data[1], sid)
    end)
    assert.it("make_literal for boolean", function()
        local ctx = new_ctx()
        local lit = types_mod.make_literal(ctx, defs.LIT_BOOLEAN, 1)
        assert.eq(ctx.types:get(lit).data[0], defs.LIT_BOOLEAN)
        assert.eq(ctx.types:get(lit).data[1], 1)
    end)
end)

assert.describe("types: functions", function()
    assert.it("make_func creates TAG_FUNCTION", function()
        local ctx = new_ctx()
        local fn = types_mod.make_func(ctx, {ctx.T_NUMBER}, {ctx.T_STRING}, -1)
        local t = ctx.types:get(fn)
        assert.eq(t.tag, defs.TAG_FUNCTION)
        assert.eq(t.data[1], 1)  -- 1 param
        assert.eq(t.data[3], 1)  -- 1 return
        assert.eq(t.data[4], -1) -- no vararg
    end)
    assert.it("make_func with no returns", function()
        local ctx = new_ctx()
        local fn = types_mod.make_func(ctx, {}, {}, -1)
        assert.eq(ctx.types:get(fn).data[1], 0)
        assert.eq(ctx.types:get(fn).data[3], 0)
    end)
    assert.it("make_func with vararg", function()
        local ctx = new_ctx()
        local fn = types_mod.make_func(ctx, {}, {ctx.T_NUMBER}, ctx.T_ANY)
        assert.eq(ctx.types:get(fn).data[4], ctx.T_ANY)
    end)
end)

assert.describe("types: tables", function()
    assert.it("make_table creates TAG_TABLE", function()
        local ctx, pool = new_ctx()
        local nid = intern.intern(pool, "x")
        local fid = types_mod.make_field(ctx, nid, ctx.T_NUMBER, false)
        local tbl = types_mod.make_table(ctx, {fid}, {}, -1, {})
        local t = ctx.types:get(tbl)
        assert.eq(t.tag, defs.TAG_TABLE)
        assert.eq(t.data[1], 1)  -- 1 field
        assert.eq(t.data[3], 0)  -- 0 indexer type_ids
    end)
    assert.it("table_field retrieves field by name", function()
        local ctx, pool = new_ctx()
        local xid = intern.intern(pool, "x")
        local fid = types_mod.make_field(ctx, xid, ctx.T_NUMBER, false)
        local tbl = types_mod.make_table(ctx, {fid}, {}, -1, {})
        local fe = types_mod.table_field(ctx, tbl, xid)
        assert.ok(fe)
        assert.eq(fe.name_id, xid)
        assert.eq(fe.type_id, ctx.T_NUMBER)
    end)
    assert.it("table_field returns nil for missing field", function()
        local ctx, pool = new_ctx()
        local xid = intern.intern(pool, "x")
        local yid = intern.intern(pool, "y")
        local fid = types_mod.make_field(ctx, xid, ctx.T_NUMBER, false)
        local tbl = types_mod.make_table(ctx, {fid}, {}, -1, {})
        local fe = types_mod.table_field(ctx, tbl, yid)
        assert.eq(fe, nil)
    end)
end)

assert.describe("types: unions", function()
    assert.it("make_union creates TAG_UNION", function()
        local ctx = new_ctx()
        local u = types_mod.make_union(ctx, {ctx.T_STRING, ctx.T_NIL})
        local t = ctx.types:get(u)
        assert.eq(t.tag, defs.TAG_UNION)
        assert.eq(t.data[1], 2)
    end)
    assert.it("make_union with 1 member returns that member", function()
        local ctx = new_ctx()
        local u = types_mod.make_union(ctx, {ctx.T_NUMBER})
        assert.eq(u, ctx.T_NUMBER)
    end)
    assert.it("make_union with 0 members returns T_NEVER", function()
        local ctx = new_ctx()
        local u = types_mod.make_union(ctx, {})
        assert.eq(u, ctx.T_NEVER)
    end)
end)

assert.describe("types: display", function()
    assert.it("display primitives", function()
        local ctx = new_ctx()
        assert.eq(types_mod.display(ctx, ctx.T_NUMBER), "number")
        assert.eq(types_mod.display(ctx, ctx.T_STRING), "string")
        assert.eq(types_mod.display(ctx, ctx.T_NIL),    "nil")
        assert.eq(types_mod.display(ctx, ctx.T_BOOLEAN),"boolean")
        assert.eq(types_mod.display(ctx, ctx.T_ANY),    "any")
        assert.eq(types_mod.display(ctx, ctx.T_NEVER),  "never")
        assert.eq(types_mod.display(ctx, ctx.T_INTEGER),"integer")
    end)
    assert.it("display typevar", function()
        local ctx = new_ctx()
        local v = types_mod.make_var(ctx, 0)
        local s = types_mod.display(ctx, v)
        assert.ok(s:find("'", 1, true))  -- e.g. 'a
    end)
    assert.it("display function", function()
        local ctx = new_ctx()
        local fn = types_mod.make_func(ctx, {ctx.T_NUMBER}, {ctx.T_STRING}, -1)
        local s = types_mod.display(ctx, fn)
        assert.ok(s:find("number"), "should mention number: " .. s)
        assert.ok(s:find("string"), "should mention string: " .. s)
    end)
    assert.it("display union", function()
        local ctx = new_ctx()
        local u = types_mod.make_union(ctx, {ctx.T_STRING, ctx.T_NIL})
        local s = types_mod.display(ctx, u)
        assert.ok(s:find("string"), s)
        assert.ok(s:find("nil"), s)
    end)
end)

assert.describe("types: widen", function()
    assert.it("widen string literal to string", function()
        local ctx, pool = new_ctx()
        local sid = intern.intern(pool, "hello")
        local lit = types_mod.make_literal(ctx, defs.LIT_STRING, sid)
        assert.eq(types_mod.widen(ctx, lit), ctx.T_STRING)
    end)
    assert.it("widen number literal to number", function()
        local ctx, pool = new_ctx()
        local nid = intern.intern(pool, "42")
        local lit = types_mod.make_literal(ctx, defs.LIT_NUMBER, nid)
        assert.eq(types_mod.widen(ctx, lit), ctx.T_NUMBER)
    end)
    assert.it("widen non-literal is identity", function()
        local ctx = new_ctx()
        assert.eq(types_mod.widen(ctx, ctx.T_STRING), ctx.T_STRING)
        assert.eq(types_mod.widen(ctx, ctx.T_NUMBER), ctx.T_NUMBER)
    end)
end)

---------------------------------------------------------------------------
-- env.lua: scoping
---------------------------------------------------------------------------

assert.describe("env: basic scoping", function()
    assert.it("bind and lookup in same scope", function()
        local ctx, pool = new_ctx()
        local scope = env_mod.new(0)
        local xid = intern.intern(pool, "x")
        env_mod.bind(scope, xid, ctx.T_NUMBER)
        assert.eq(env_mod.lookup(scope, xid), ctx.T_NUMBER)
    end)
    assert.it("lookup in parent scope", function()
        local ctx, pool = new_ctx()
        local parent = env_mod.new(0)
        local child  = env_mod.child(parent)
        local xid = intern.intern(pool, "x")
        env_mod.bind(parent, xid, ctx.T_STRING)
        assert.eq(env_mod.lookup(child, xid), ctx.T_STRING)
    end)
    assert.it("child binding shadows parent", function()
        local ctx, pool = new_ctx()
        local parent = env_mod.new(0)
        local child  = env_mod.child(parent)
        local xid = intern.intern(pool, "x")
        env_mod.bind(parent, xid, ctx.T_NUMBER)
        env_mod.bind(child,  xid, ctx.T_STRING)
        assert.eq(env_mod.lookup(child,  xid), ctx.T_STRING)
        assert.eq(env_mod.lookup(parent, xid), ctx.T_NUMBER)
    end)
    assert.it("lookup missing returns nil", function()
        local scope = env_mod.new(0)
        assert.eq(env_mod.lookup(scope, 999), nil)
    end)
    assert.it("level increments with child", function()
        local parent = env_mod.new(0)
        local child  = env_mod.child(parent)
        assert.eq(parent.level, 0)
        assert.eq(child.level,  1)
    end)
end)

assert.describe("env: type bindings", function()
    assert.it("bind_type and lookup_type", function()
        local ctx, pool = new_ctx()
        local scope = env_mod.new(0)
        local Nid = intern.intern(pool, "Point")
        env_mod.bind_type(scope, Nid, { body = ctx.T_NUMBER, params = nil })
        local alias = env_mod.lookup_type(scope, Nid)
        assert.ok(alias)
        assert.eq(alias.body, ctx.T_NUMBER)
    end)
    assert.it("lookup_type returns nil for missing", function()
        local scope = env_mod.new(0)
        assert.eq(env_mod.lookup_type(scope, 42), nil)
    end)
end)

assert.describe("env: generalize + instantiate", function()
    assert.it("generalize marks free var as generic", function()
        local ctx, pool = new_ctx()
        local scope = env_mod.new(0)
        ctx.scope = scope
        local v = types_mod.make_var(ctx, 1)
        -- v is at level 1, generalize from level 0 marks it generic
        env_mod.generalize(ctx, v, 0)
        assert.eq(ctx.types:get(v).flags, defs.FLAG_GENERIC)
    end)
    assert.it("instantiate replaces generic var with fresh var", function()
        local ctx, pool = new_ctx()
        local scope = env_mod.new(0)
        ctx.scope = scope
        local v = types_mod.make_var(ctx, 1)
        ctx.types:get(v).flags = defs.FLAG_GENERIC
        -- instantiate at level 0 — fresh var
        local fresh = env_mod.instantiate(ctx, v, 0)
        -- should be a different var
        assert.ok(fresh ~= v)
        assert.eq(ctx.types:get(fresh).tag, defs.TAG_VAR)
        -- fresh should NOT be generic
        assert.eq(ctx.types:get(fresh).flags, 0)
    end)
    assert.it("instantiate on non-generic returns a function type", function()
        local ctx = new_ctx()
        ctx.scope = env_mod.new(0)
        local fn = types_mod.make_func(ctx, {ctx.T_NUMBER}, {ctx.T_STRING}, -1)
        -- no generics — instantiate returns equivalent type (may or may not be same id)
        local inst = env_mod.instantiate(ctx, fn, 0)
        assert.eq(ctx.types:get(inst).tag, defs.TAG_FUNCTION)
    end)
end)

---------------------------------------------------------------------------
-- unify.lua: unification
---------------------------------------------------------------------------

local function make_unify_ctx()
    local pool = intern.new()
    local ctx = types_mod.new_ctx(pool)
    ctx.scope = env_mod.new(0)
    return ctx, pool
end

assert.describe("unify: primitives", function()
    assert.it("number unifies with number", function()
        local ctx = make_unify_ctx()
        local ok, err = unify_mod.unify(ctx, ctx.T_NUMBER, ctx.T_NUMBER)
        assert.ok(ok)
        assert.eq(err, nil)
    end)
    assert.it("string unifies with string", function()
        local ctx = make_unify_ctx()
        local ok = unify_mod.unify(ctx, ctx.T_STRING, ctx.T_STRING)
        assert.ok(ok)
    end)
    assert.it("string does not unify with number", function()
        local ctx = make_unify_ctx()
        local ok = unify_mod.unify(ctx, ctx.T_STRING, ctx.T_NUMBER)
        assert.ok(not ok)
    end)
    assert.it("any unifies with anything", function()
        local ctx = make_unify_ctx()
        assert.ok(unify_mod.unify(ctx, ctx.T_NUMBER, ctx.T_ANY))
        assert.ok(unify_mod.unify(ctx, ctx.T_ANY, ctx.T_STRING))
    end)
    assert.it("integer unifies with number (subtype)", function()
        local ctx = make_unify_ctx()
        local ok = unify_mod.unify(ctx, ctx.T_INTEGER, ctx.T_NUMBER)
        assert.ok(ok)
    end)
    assert.it("number unifies with integer (LuaJIT: no runtime distinction)", function()
        local ctx = make_unify_ctx()
        -- In LuaJIT, integers and numbers are bidirectionally compatible
        local ok = unify_mod.unify(ctx, ctx.T_NUMBER, ctx.T_INTEGER)
        assert.ok(ok)
    end)
end)

assert.describe("unify: literals", function()
    assert.it("literal string unifies with string", function()
        local ctx, pool = make_unify_ctx()
        local sid = intern.intern(pool, "hello")
        local lit = types_mod.make_literal(ctx, defs.LIT_STRING, sid)
        assert.ok(unify_mod.unify(ctx, lit, ctx.T_STRING))
    end)
    assert.it("same literal string unifies with itself", function()
        local ctx, pool = make_unify_ctx()
        local sid = intern.intern(pool, "x")
        local lit1 = types_mod.make_literal(ctx, defs.LIT_STRING, sid)
        local lit2 = types_mod.make_literal(ctx, defs.LIT_STRING, sid)
        assert.ok(unify_mod.unify(ctx, lit1, lit2))
    end)
    assert.it("different string literals don't unify", function()
        local ctx, pool = make_unify_ctx()
        local sid1 = intern.intern(pool, "a")
        local sid2 = intern.intern(pool, "b")
        local lit1 = types_mod.make_literal(ctx, defs.LIT_STRING, sid1)
        local lit2 = types_mod.make_literal(ctx, defs.LIT_STRING, sid2)
        assert.ok(not unify_mod.unify(ctx, lit1, lit2))
    end)
end)

assert.describe("unify: type variables", function()
    assert.it("var unifies with concrete type (binds)", function()
        local ctx = make_unify_ctx()
        local v = types_mod.make_var(ctx, 0)
        assert.ok(unify_mod.unify(ctx, v, ctx.T_NUMBER))
        -- v should now resolve to number
        assert.eq(types_mod.find(ctx, v), ctx.T_NUMBER)
    end)
    assert.it("concrete type unifies with var (binds)", function()
        local ctx = make_unify_ctx()
        local v = types_mod.make_var(ctx, 0)
        assert.ok(unify_mod.unify(ctx, ctx.T_STRING, v))
        assert.eq(types_mod.find(ctx, v), ctx.T_STRING)
    end)
    assert.it("two vars unify (one binds to other)", function()
        local ctx = make_unify_ctx()
        local v1 = types_mod.make_var(ctx, 0)
        local v2 = types_mod.make_var(ctx, 0)
        assert.ok(unify_mod.unify(ctx, v1, v2))
        -- after unification, both should resolve to same root
        assert.eq(types_mod.find(ctx, v1), types_mod.find(ctx, v2))
    end)
end)

assert.describe("unify: functions", function()
    assert.it("same-shaped function unifies", function()
        local ctx = make_unify_ctx()
        local f1 = types_mod.make_func(ctx, {ctx.T_NUMBER}, {ctx.T_STRING}, -1)
        local f2 = types_mod.make_func(ctx, {ctx.T_NUMBER}, {ctx.T_STRING}, -1)
        assert.ok(unify_mod.unify(ctx, f1, f2))
    end)
    assert.it("different return types don't unify", function()
        local ctx = make_unify_ctx()
        local f1 = types_mod.make_func(ctx, {}, {ctx.T_NUMBER}, -1)
        local f2 = types_mod.make_func(ctx, {}, {ctx.T_STRING}, -1)
        assert.ok(not unify_mod.unify(ctx, f1, f2))
    end)
    assert.it("different param counts don't unify", function()
        local ctx = make_unify_ctx()
        local f1 = types_mod.make_func(ctx, {ctx.T_NUMBER}, {}, -1)
        local f2 = types_mod.make_func(ctx, {ctx.T_NUMBER, ctx.T_STRING}, {}, -1)
        assert.ok(not unify_mod.unify(ctx, f1, f2))
    end)
    assert.it("function with var param unifies and binds", function()
        local ctx = make_unify_ctx()
        local v = types_mod.make_var(ctx, 0)
        local f1 = types_mod.make_func(ctx, {v}, {ctx.T_STRING}, -1)
        local f2 = types_mod.make_func(ctx, {ctx.T_NUMBER}, {ctx.T_STRING}, -1)
        assert.ok(unify_mod.unify(ctx, f1, f2))
        assert.eq(types_mod.find(ctx, v), ctx.T_NUMBER)
    end)
end)

assert.describe("unify: try_unify (non-mutating)", function()
    assert.it("try_unify returns ok=true for compatible types", function()
        local ctx = make_unify_ctx()
        local _, ok = unify_mod.try_unify(ctx, ctx.T_NUMBER, ctx.T_NUMBER)
        assert.ok(ok)
    end)
    assert.it("try_unify returns ok=false for incompatible types", function()
        local ctx = make_unify_ctx()
        local _, ok = unify_mod.try_unify(ctx, ctx.T_STRING, ctx.T_NUMBER)
        assert.ok(not ok)
    end)
    assert.it("try_unify does not bind vars", function()
        local ctx = make_unify_ctx()
        local v = types_mod.make_var(ctx, 0)
        -- try_unify should NOT bind v
        unify_mod.try_unify(ctx, v, ctx.T_NUMBER)
        -- v should still be unbound
        assert.eq(types_mod.find(ctx, v), v)
    end)
end)

assert.describe("unify: tables", function()
    assert.it("empty tables unify", function()
        local ctx = make_unify_ctx()
        local t1 = types_mod.make_table(ctx, {}, {}, -1, {})
        local t2 = types_mod.make_table(ctx, {}, {}, -1, {})
        assert.ok(unify_mod.unify(ctx, t1, t2))
    end)
    assert.it("table with field unifies with table with same field", function()
        local ctx, pool = make_unify_ctx()
        local xid = intern.intern(pool, "x")
        local f1 = types_mod.make_field(ctx, xid, ctx.T_NUMBER, false)
        local f2 = types_mod.make_field(ctx, xid, ctx.T_NUMBER, false)
        local t1 = types_mod.make_table(ctx, {f1}, {}, -1, {})
        local t2 = types_mod.make_table(ctx, {f2}, {}, -1, {})
        assert.ok(unify_mod.unify(ctx, t1, t2))
    end)
end)

assert.describe("unify: unions", function()
    assert.it("string | nil unifies with string | nil", function()
        local ctx = make_unify_ctx()
        local u1 = types_mod.make_union(ctx, {ctx.T_STRING, ctx.T_NIL})
        local u2 = types_mod.make_union(ctx, {ctx.T_STRING, ctx.T_NIL})
        assert.ok(unify_mod.unify(ctx, u1, u2))
    end)
    assert.it("string unifies with string | nil", function()
        local ctx = make_unify_ctx()
        local u = types_mod.make_union(ctx, {ctx.T_STRING, ctx.T_NIL})
        assert.ok(unify_mod.unify(ctx, ctx.T_STRING, u))
    end)
end)

---------------------------------------------------------------------------
-- match.lua: match types
---------------------------------------------------------------------------

assert.describe("match: pattern matching", function()
    assert.it("any pattern matches everything", function()
        local ctx = make_unify_ctx()
        local ok, _ = match_mod.match_pattern(ctx, ctx.T_NUMBER, ctx.T_ANY)
        assert.ok(ok)
    end)
    assert.it("exact primitive match", function()
        local ctx = make_unify_ctx()
        local ok, _ = match_mod.match_pattern(ctx, ctx.T_NUMBER, ctx.T_NUMBER)
        assert.ok(ok)
    end)
    assert.it("integer matches number (subtype)", function()
        local ctx = make_unify_ctx()
        local ok, _ = match_mod.match_pattern(ctx, ctx.T_INTEGER, ctx.T_NUMBER)
        assert.ok(ok)
    end)
    assert.it("string does not match number", function()
        local ctx = make_unify_ctx()
        local ok, _ = match_mod.match_pattern(ctx, ctx.T_STRING, ctx.T_NUMBER)
        assert.ok(not ok)
    end)
end)

---------------------------------------------------------------------------
-- infer.check_string: end-to-end checker
---------------------------------------------------------------------------

local function check(src)
    return infer_mod.check_string(src, "test")
end

local function no_errors(src)
    local ec = check(src)
    if errors_mod.has_errors(ec) then
        local msg = errors_mod.format_plain(ec)
        error("expected no errors but got:\n" .. msg, 2)
    end
end

local function has_error(src, pattern)
    local ec = check(src)
    if not errors_mod.has_errors(ec) then
        error("expected error matching '" .. pattern .. "' but got none", 2)
    end
    if pattern then
        local msg = errors_mod.format_plain(ec)
        if not msg:find(pattern) then
            error("expected error matching '" .. pattern .. "' but got:\n" .. msg, 2)
        end
    end
end

assert.describe("checker: literals", function()
    assert.it("number literal has no errors", function()
        no_errors("local x = 1")
    end)
    assert.it("string literal has no errors", function()
        no_errors([[local x = "hello"]])
    end)
    assert.it("boolean literal has no errors", function()
        no_errors("local x = true")
    end)
    assert.it("nil literal has no errors", function()
        no_errors("local x = nil")
    end)
end)

assert.describe("checker: arithmetic", function()
    assert.it("number + number is valid", function()
        no_errors("local x = 1 + 2")
    end)
    assert.it("string concat is valid", function()
        no_errors([[local x = "a" .. "b"]])
    end)
    assert.it("negation of number is valid", function()
        no_errors("local x = -1")
    end)
    assert.it("length of string is valid", function()
        no_errors([[local x = #"hello"]])
    end)
    assert.it("not true is valid", function()
        no_errors("local x = not true")
    end)
end)

assert.describe("checker: variables and assignment", function()
    assert.it("local variable declaration", function()
        no_errors("local x = 1; local y = x + 2")
    end)
    assert.it("multiple assignment", function()
        no_errors("local x, y = 1, 2")
    end)
    assert.it("assignment to annotated variable checks type", function()
        has_error([[
--: number
local x = "hello"
]], "mismatch")
    end)
    assert.it("annotation type is respected", function()
        no_errors([[
--: string
local x = "hello"
]])
    end)
end)

assert.describe("checker: functions", function()
    assert.it("function declaration", function()
        no_errors("function foo(x) return x end")
    end)
    assert.it("local function declaration", function()
        no_errors("local function bar(x, y) return x + y end")
    end)
    assert.it("function call", function()
        no_errors("local function f(x) return x end; local y = f(1)")
    end)
    assert.it("function with annotation", function()
        no_errors([[
--: (number) -> number
local function double(x)
    return x * 2
end
]])
    end)
    assert.it("calling non-function reports error", function()
        has_error([[
local x = 42
x()
]], "cannot call")
    end)
end)

assert.describe("checker: tables", function()
    assert.it("table construction", function()
        no_errors("local t = { x = 1, y = 2 }")
    end)
    assert.it("table field access", function()
        no_errors("local t = { x = 1 }; local y = t.x")
    end)
    assert.it("nested table", function()
        no_errors("local t = { a = { b = 1 } }; local x = t.a.b")
    end)
    assert.it("method declaration and call", function()
        no_errors([[
local M = {}
function M:greet(name)
    return name
end
local s = M:greet("world")
]])
    end)
end)

assert.describe("checker: control flow", function()
    assert.it("if/then/end", function()
        no_errors("local x = 0; if x > 0 then x = 1 end")
    end)
    assert.it("if/elseif/else", function()
        no_errors("local x = 0; if x > 0 then x = 1 elseif x < 0 then x = -1 else x = 0 end")
    end)
    assert.it("while loop", function()
        no_errors("local i = 0; while i < 10 do i = i + 1 end")
    end)
    assert.it("numeric for", function()
        no_errors("for i = 1, 10 do end")
    end)
    assert.it("generic for", function()
        no_errors("for k, v in pairs({}) do end")
    end)
    assert.it("repeat/until", function()
        no_errors("local x = 0; repeat x = x + 1 until x >= 10")
    end)
    assert.it("do block", function()
        no_errors("do local x = 1 end")
    end)
end)

assert.describe("checker: nil narrowing", function()
    assert.it("nil check narrows type in truthy branch", function()
        -- Should not error: x is narrowed to non-nil in the if body
        no_errors([[
--: string?
local x = "hello"
if x ~= nil then
    local y = x .. " world"
end
]])
    end)
end)

assert.describe("checker: type declarations", function()
    assert.it("simple type alias", function()
        no_errors([[
--:: Name = string
--: Name
local x = "hello"
]])
    end)
    assert.it("table type alias", function()
        no_errors([[
--:: Point = { x: number, y: number }
--: Point
local p = { x = 1.0, y = 2.0 }
]])
    end)
end)

assert.describe("checker: module pattern", function()
    assert.it("local M = {} with function M.foo", function()
        no_errors([[
local M = {}

function M.new(x)
    return { value = x }
end

function M.get(obj)
    return obj.value
end

return M
]])
    end)
    assert.it("return statement", function()
        no_errors("local x = 1; return x")
    end)
    assert.it("multiple return values", function()
        no_errors("return 1, 2, 3")
    end)
end)

assert.describe("checker: parse errors", function()
    assert.it("syntax error returns error context", function()
        local ec = check("local x = +++")
        assert.ok(errors_mod.has_errors(ec))
    end)
end)

assert.describe("checker: self-check (parses own source)", function()
    assert.it("checks types.lua without crashing", function()
        local f = io.open("lib/type/static/v2/types.lua", "r")
        if f then
            local src = f:read("*a"); f:close()
            local ec = check(src)
            -- Any errors are acceptable — just mustn't crash
            assert.ok(true)
        end
    end)
    assert.it("checks env.lua without crashing", function()
        local f = io.open("lib/type/static/v2/env.lua", "r")
        if f then
            local src = f:read("*a"); f:close()
            local ec = check(src)
            assert.ok(true)
        end
    end)
    assert.it("checks errors.lua without crashing", function()
        local f = io.open("lib/type/static/v2/errors.lua", "r")
        if f then
            local src = f:read("*a"); f:close()
            local ec = check(src)
            assert.ok(true)
        end
    end)
end)

assert.describe("errors: formatting", function()
    assert.it("format_plain produces readable output", function()
        local ec = errors_mod.new_ctx()
        errors_mod.error(ec, "foo.lua", 5, 3, "type mismatch")
        local out = errors_mod.format_plain(ec)
        assert.ok(out:find("foo.lua"), out)
        assert.ok(out:find("error"), out)
        assert.ok(out:find("type mismatch"), out)
    end)
    assert.it("format_json produces valid-looking JSON", function()
        local ec = errors_mod.new_ctx()
        errors_mod.error(ec, "bar.lua", 1, 0, "bad type")
        local out = errors_mod.format_json(ec)
        assert.ok(out:sub(1,1) == "[", "should start with [")
        assert.ok(out:find('"kind"'), out)
    end)
    assert.it("has_errors returns false for empty context", function()
        local ec = errors_mod.new_ctx()
        assert.ok(not errors_mod.has_errors(ec))
    end)
    assert.it("has_errors returns true after adding error", function()
        local ec = errors_mod.new_ctx()
        errors_mod.error(ec, "x", 1, 0, "oops")
        assert.ok(errors_mod.has_errors(ec))
    end)
    assert.it("warnings do not trigger has_errors", function()
        local ec = errors_mod.new_ctx()
        errors_mod.warning(ec, "x", 1, 0, "note")
        assert.ok(not errors_mod.has_errors(ec))
    end)
end)
