if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local DSU = require("lib.disjoint_set")

T.describe("DSU.new (basic union-find)", function()
  T.it("initially all elements are their own component", function()
    local uf = DSU.new(5)
    for i = 0, 4 do
      T.eq(uf:find(i), i)
    end
  end)

  T.it("count equals n initially", function()
    local uf = DSU.new(5)
    T.eq(uf:count(), 5)
  end)

  T.it("connected: false before union", function()
    local uf = DSU.new(4)
    T.eq(uf:connected(0, 1), false)
    T.eq(uf:connected(2, 3), false)
  end)

  T.it("union: two elements in same component", function()
    local uf = DSU.new(4)
    local changed = uf:union(0, 1)
    T.eq(changed, true)
    T.eq(uf:connected(0, 1), true)
  end)

  T.it("union: returns false when already connected", function()
    local uf = DSU.new(4)
    uf:union(0, 1)
    local changed = uf:union(0, 1)
    T.eq(changed, false)
  end)

  T.it("connected: true after union", function()
    local uf = DSU.new(5)
    uf:union(1, 2)
    uf:union(2, 3)
    T.eq(uf:connected(1, 3), true)
    T.eq(uf:connected(0, 1), false)
  end)

  T.it("component_size grows correctly", function()
    local uf = DSU.new(5)
    T.eq(uf:component_size(0), 1)
    uf:union(0, 1)
    T.eq(uf:component_size(0), 2)
    T.eq(uf:component_size(1), 2)
    uf:union(0, 2)
    T.eq(uf:component_size(0), 3)
    T.eq(uf:component_size(2), 3)
  end)

  T.it("count decreases with each successful union", function()
    local uf = DSU.new(5)
    T.eq(uf:count(), 5)
    uf:union(0, 1)
    T.eq(uf:count(), 4)
    uf:union(2, 3)
    T.eq(uf:count(), 3)
    uf:union(0, 2)
    T.eq(uf:count(), 2)
    -- repeated union does not decrease count
    uf:union(0, 3)
    T.eq(uf:count(), 2)
  end)

  T.it("components: correct grouping after several unions", function()
    local uf = DSU.new(6)
    uf:union(0, 1)
    uf:union(1, 2)
    uf:union(3, 4)
    local comps = uf:components()
    T.eq(#comps, 3)
    -- Find group sizes (sort by size)
    local sizes = {}
    for _, g in ipairs(comps) do
      sizes[#sizes + 1] = #g
    end
    table.sort(sizes)
    T.eq(sizes[1], 1)
    T.eq(sizes[2], 2)
    T.eq(sizes[3], 3)
  end)

  T.it("path compression: find returns same root after compression", function()
    local uf = DSU.new(6)
    -- chain: 0-1-2-3-4-5 via sequential unions
    for i = 0, 4 do
      uf:union(i, i + 1)
    end
    local root = uf:find(0)
    for i = 1, 5 do
      T.eq(uf:find(i), root)
    end
  end)

  T.it("dynamic mode: elements created on demand", function()
    local uf = DSU.new()
    T.eq(uf:find(100), 100)
    T.eq(uf:find(200), 200)
    T.eq(uf:connected(100, 200), false)
    uf:union(100, 200)
    T.eq(uf:connected(100, 200), true)
  end)

  T.it("large: 1000 elements, union pairs → 500 components", function()
    local uf = DSU.new(1000)
    for i = 0, 998, 2 do
      uf:union(i, i + 1)
    end
    T.eq(uf:count(), 500)
    for i = 0, 998, 2 do
      T.eq(uf:connected(i, i + 1), true)
    end
    T.eq(uf:connected(0, 2), false)
    T.eq(uf:connected(998, 996), false)
  end)
end)

T.describe("DSU.named", function()
  T.it("auto-create on find", function()
    local n = DSU.named()
    local r = n:find("alice")
    T.eq(type(r), "string")
    T.eq(n:find("alice"), r)
  end)

  T.it("connected: false before union", function()
    local n = DSU.named()
    n:find("alice")
    n:find("bob")
    T.eq(n:connected("alice", "bob"), false)
  end)

  T.it("union by name", function()
    local n = DSU.named()
    local changed = n:union("alice", "bob")
    T.eq(changed, true)
    T.eq(n:connected("alice", "bob"), true)
  end)

  T.it("union returns false when already connected", function()
    local n = DSU.named()
    n:union("alice", "bob")
    T.eq(n:union("alice", "bob"), false)
  end)

  T.it("transitive connectivity", function()
    local n = DSU.named()
    n:union("alice", "bob")
    n:union("bob", "carol")
    T.eq(n:connected("alice", "carol"), true)
    T.eq(n:connected("alice", "dave"), false)
  end)

  T.it("component membership", function()
    local n = DSU.named()
    n:union("alice", "bob")
    n:union("bob", "carol")
    local comp = n:component("alice")
    table.sort(comp)
    T.eq(#comp, 3)
    T.eq(comp[1], "alice")
    T.eq(comp[2], "bob")
    T.eq(comp[3], "carol")
  end)

  T.it("component: singleton", function()
    local n = DSU.named()
    n:find("solo")
    local comp = n:component("solo")
    T.eq(#comp, 1)
    T.eq(comp[1], "solo")
  end)

  T.it("components: correct grouping", function()
    local n = DSU.named()
    n:union("a", "b")
    n:union("c", "d")
    n:find("e")
    local comps = n:components()
    -- Count total members
    local total = 0
    local group_sizes = {}
    for _, members in pairs(comps) do
      total = total + #members
      group_sizes[#group_sizes + 1] = #members
    end
    T.eq(total, 5)
    table.sort(group_sizes)
    T.eq(group_sizes[1], 1)
    T.eq(group_sizes[2], 2)
    T.eq(group_sizes[3], 2)
  end)

  T.it("find returns the representative name", function()
    local n = DSU.named()
    n:union("x", "y")
    local rx = n:find("x")
    local ry = n:find("y")
    T.eq(rx, ry)
  end)
end)

T.describe("DSU.persistent", function()
  T.it("initially each element is its own component", function()
    local puf = DSU.persistent(4)
    for i = 0, 3 do
      T.eq(puf:find(i), i)
    end
    T.eq(puf:count(), 4)
  end)

  T.it("union then restore reverts to pre-union state", function()
    local puf = DSU.persistent(4)
    local save = puf:save()
    puf:union(0, 1)
    T.eq(puf:connected(0, 1), true)
    T.eq(puf:count(), 3)
    puf:restore(save)
    T.eq(puf:connected(0, 1), false)
    T.eq(puf:count(), 4)
    T.eq(puf:find(0), 0)
    T.eq(puf:find(1), 1)
  end)

  T.it("nested: save at A, union, save at B, union, restore B", function()
    local puf = DSU.persistent(5)
    local saveA = puf:save()
    puf:union(0, 1)
    local saveB = puf:save()
    puf:union(2, 3)
    T.eq(puf:connected(0, 1), true)
    T.eq(puf:connected(2, 3), true)
    puf:restore(saveB)
    T.eq(puf:connected(0, 1), true)   -- this union persists
    T.eq(puf:connected(2, 3), false)  -- this was undone
    T.eq(puf:count(), 4)
  end)

  T.it("restore A restores to before both unions", function()
    local puf = DSU.persistent(5)
    local saveA = puf:save()
    puf:union(0, 1)
    puf:union(2, 3)
    T.eq(puf:connected(0, 1), true)
    T.eq(puf:connected(2, 3), true)
    T.eq(puf:count(), 3)
    puf:restore(saveA)
    T.eq(puf:connected(0, 1), false)
    T.eq(puf:connected(2, 3), false)
    T.eq(puf:count(), 5)
  end)

  T.it("union returns false when already connected", function()
    local puf = DSU.persistent(3)
    T.eq(puf:union(0, 1), true)
    T.eq(puf:union(0, 1), false)
  end)

  T.it("component_size correct after union", function()
    local puf = DSU.persistent(4)
    puf:union(0, 1)
    puf:union(0, 2)
    T.eq(puf:component_size(0), 3)
    T.eq(puf:component_size(3), 1)
  end)

  T.it("restore restores component_size", function()
    local puf = DSU.persistent(4)
    local s = puf:save()
    puf:union(0, 1)
    puf:union(0, 2)
    T.eq(puf:component_size(0), 3)
    puf:restore(s)
    T.eq(puf:component_size(0), 1)
    T.eq(puf:component_size(1), 1)
    T.eq(puf:component_size(2), 1)
  end)

  T.it("multiple save/restore cycles", function()
    local puf = DSU.persistent(6)
    local s0 = puf:save()
    puf:union(0, 1)
    local s1 = puf:save()
    puf:union(2, 3)
    local s2 = puf:save()
    puf:union(4, 5)
    T.eq(puf:count(), 3)
    puf:restore(s2)
    T.eq(puf:count(), 4)
    puf:restore(s1)
    T.eq(puf:count(), 5)
    puf:restore(s0)
    T.eq(puf:count(), 6)
  end)
end)

T.describe("DSU.weighted (bipartite)", function()
  T.it("basic merge and diff", function()
    local wuf = DSU.weighted(4)
    wuf:merge(0, 1, 1)
    T.eq(wuf:diff(0, 1), 1)
  end)

  T.it("diff is symmetric (XOR)", function()
    local wuf = DSU.weighted(4)
    wuf:merge(0, 1, 1)
    T.eq(wuf:diff(0, 1), 1)
    T.eq(wuf:diff(1, 0), 1)
  end)

  T.it("diff: same component, weight 0", function()
    local wuf = DSU.weighted(4)
    wuf:merge(0, 1, 0)
    T.eq(wuf:diff(0, 1), 0)
  end)

  T.it("diff: transitive parity", function()
    local wuf = DSU.weighted(4)
    wuf:merge(0, 1, 1)  -- 0 and 1 differ
    wuf:merge(1, 2, 1)  -- 1 and 2 differ
    -- 0 and 2 should be same parity (1 XOR 1 = 0)
    T.eq(wuf:diff(0, 2), 0)
  end)

  T.it("diff: returns nil for different components", function()
    local wuf = DSU.weighted(4)
    wuf:merge(0, 1, 1)
    T.eq(wuf:diff(0, 2), nil)
    T.eq(wuf:diff(2, 3), nil)
  end)

  T.it("bipartite graph: is_bipartite true", function()
    -- Bipartite: 0-1-2-3-0 cycle of length 4 (even)
    local wuf = DSU.weighted(4)
    wuf:merge(0, 1, 1)
    wuf:merge(1, 2, 1)
    wuf:merge(2, 3, 1)
    wuf:merge(3, 0, 1)
    T.eq(wuf:is_bipartite(), true)
  end)

  T.it("odd cycle: is_bipartite false", function()
    -- Triangle: 0-1-2-0, all edges weight 1 → odd cycle
    local wuf = DSU.weighted(3)
    wuf:merge(0, 1, 1)
    wuf:merge(1, 2, 1)
    wuf:merge(2, 0, 1)  -- creates odd cycle
    T.eq(wuf:is_bipartite(), false)
  end)

  T.it("disconnected components: diff returns nil", function()
    local wuf = DSU.weighted(6)
    wuf:merge(0, 1, 1)
    wuf:merge(2, 3, 1)
    T.eq(wuf:diff(0, 2), nil)
    T.eq(wuf:diff(1, 3), nil)
    T.eq(wuf:diff(4, 5), nil)
  end)

  T.it("connected check", function()
    local wuf = DSU.weighted(4)
    T.eq(wuf:connected(0, 1), false)
    wuf:merge(0, 1, 0)
    T.eq(wuf:connected(0, 1), true)
    T.eq(wuf:connected(0, 2), false)
  end)

  T.it("count decreases on merge", function()
    local wuf = DSU.weighted(4)
    T.eq(wuf:count(), 4)
    wuf:merge(0, 1, 1)
    T.eq(wuf:count(), 3)
    wuf:merge(2, 3, 0)
    T.eq(wuf:count(), 2)
    wuf:merge(0, 2, 1)
    T.eq(wuf:count(), 1)
  end)

  T.it("merge returns false when already in same component", function()
    local wuf = DSU.weighted(4)
    T.eq(wuf:merge(0, 1, 1), true)
    T.eq(wuf:merge(0, 1, 1), false)
  end)

  T.it("bipartite: independent components are each valid", function()
    local wuf = DSU.weighted(6)
    -- two separate bipartite components
    wuf:merge(0, 1, 1)
    wuf:merge(2, 3, 1)
    wuf:merge(4, 5, 1)
    T.eq(wuf:is_bipartite(), true)
  end)
end)
