if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local PT = require("lib.patricia_trie")

T.describe("patricia_trie: basics", function()
  T.it("new trie is empty", function()
    local t = PT.new()
    T.ok(t:is_empty())
    T.eq(t:size(), 0)
  end)

  T.it("insert and get single key", function()
    local t = PT.new()
    t:insert("hello", 42)
    T.eq(t:get("hello"), 42)
    T.eq(t:size(), 1)
    T.ok(not t:is_empty())
  end)

  T.it("get returns nil for missing key", function()
    local t = PT.new()
    t:insert("hello", 1)
    T.eq(t:get("world"), nil)
    T.eq(t:get("hell"), nil)
    T.eq(t:get("helloo"), nil)
  end)

  T.it("default value is true", function()
    local t = PT.new()
    t:insert("x")
    T.eq(t:get("x"), true)
  end)

  T.it("update existing key", function()
    local t = PT.new()
    t:insert("foo", 1)
    t:insert("foo", 2)
    T.eq(t:get("foo"), 2)
    T.eq(t:size(), 1)
  end)

  T.it("contains: true for present, false for absent", function()
    local t = PT.new()
    t:insert("abc", 99)
    T.ok(t:contains("abc"))
    T.ok(not t:contains("ab"))
    T.ok(not t:contains("abcd"))
    T.ok(not t:contains("xyz"))
  end)
end)

T.describe("patricia_trie: remove", function()
  T.it("remove existing key returns true", function()
    local t = PT.new()
    t:insert("key", 7)
    T.ok(t:remove("key"))
    T.eq(t:size(), 0)
    T.eq(t:get("key"), nil)
    T.ok(t:is_empty())
  end)

  T.it("remove missing key returns false", function()
    local t = PT.new()
    t:insert("key", 7)
    T.ok(not t:remove("other"))
    T.eq(t:size(), 1)
  end)

  T.it("remove does not affect siblings", function()
    local t = PT.new()
    t:insert("foo", 1)
    t:insert("bar", 2)
    t:insert("baz", 3)
    t:remove("bar")
    T.eq(t:get("foo"), 1)
    T.eq(t:get("bar"), nil)
    T.eq(t:get("baz"), 3)
    T.eq(t:size(), 2)
  end)

  T.it("remove prefix key leaves longer keys intact", function()
    local t = PT.new()
    t:insert("test", 1)
    t:insert("testing", 2)
    t:remove("test")
    T.eq(t:get("test"), nil)
    T.eq(t:get("testing"), 2)
    T.eq(t:size(), 1)
  end)

  T.it("remove longer key leaves prefix key intact", function()
    local t = PT.new()
    t:insert("test", 1)
    t:insert("testing", 2)
    t:remove("testing")
    T.eq(t:get("test"), 1)
    T.eq(t:get("testing"), nil)
    T.eq(t:size(), 1)
  end)
end)

T.describe("patricia_trie: common prefix splitting", function()
  T.it("test / testing / tester / tested all findable", function()
    local t = PT.new()
    t:insert("test", 10)
    t:insert("testing", 20)
    t:insert("tester", 30)
    t:insert("tested", 40)
    T.eq(t:get("test"), 10)
    T.eq(t:get("testing"), 20)
    T.eq(t:get("tester"), 30)
    T.eq(t:get("tested"), 40)
    T.eq(t:size(), 4)
  end)

  T.it("overlapping prefixes: a, ab, abc, abcd", function()
    local t = PT.new()
    t:insert("a", 1)
    t:insert("ab", 2)
    t:insert("abc", 3)
    t:insert("abcd", 4)
    T.eq(t:get("a"), 1)
    T.eq(t:get("ab"), 2)
    T.eq(t:get("abc"), 3)
    T.eq(t:get("abcd"), 4)
    T.eq(t:get("abcde"), nil)
    T.eq(t:size(), 4)
  end)

  T.it("diverging keys at first character", function()
    local t = PT.new()
    t:insert("apple", 1)
    t:insert("banana", 2)
    t:insert("cherry", 3)
    T.eq(t:get("apple"), 1)
    T.eq(t:get("banana"), 2)
    T.eq(t:get("cherry"), 3)
  end)

  T.it("split in the middle of an edge label", function()
    local t = PT.new()
    t:insert("foobar", 1)
    t:insert("foobaz", 2)
    T.eq(t:get("foobar"), 1)
    T.eq(t:get("foobaz"), 2)
    T.eq(t:get("fooba"), nil)
    T.eq(t:size(), 2)
  end)
end)

T.describe("patricia_trie: prefix_search", function()
  T.it("returns all keys with given prefix", function()
    local t = PT.new()
    t:insert("test", 1)
    t:insert("testing", 2)
    t:insert("tester", 3)
    t:insert("toast", 4)
    t:insert("other", 5)
    local res = t:prefix_search("test")
    -- Should contain test, testing, tester but not toast or other.
    T.eq(#res, 3)
    local found = {}
    for i = 1, #res do found[res[i][1]] = res[i][2] end
    T.eq(found["test"], 1)
    T.eq(found["testing"], 2)
    T.eq(found["tester"], 3)
    T.eq(found["toast"], nil)
  end)

  T.it("prefix_search with empty prefix returns all", function()
    local t = PT.new()
    t:insert("a", 1)
    t:insert("b", 2)
    t:insert("c", 3)
    local res = t:prefix_search("")
    T.eq(#res, 3)
  end)

  T.it("prefix_search returns empty for no matches", function()
    local t = PT.new()
    t:insert("hello", 1)
    local res = t:prefix_search("world")
    T.eq(#res, 0)
  end)

  T.it("prefix_search results are sorted", function()
    local t = PT.new()
    t:insert("tester", 3)
    t:insert("test", 1)
    t:insert("testing", 2)
    local res = t:prefix_search("test")
    T.eq(res[1][1], "test")
    T.eq(res[2][1], "tester")
    T.eq(res[3][1], "testing")
  end)

  T.it("prefix_search on exact key returns just that key", function()
    local t = PT.new()
    t:insert("exact", 99)
    local res = t:prefix_search("exact")
    T.eq(#res, 1)
    T.eq(res[1][1], "exact")
    T.eq(res[1][2], 99)
  end)
end)

T.describe("patricia_trie: longest_prefix", function()
  T.it("returns longest stored prefix of query", function()
    local t = PT.new()
    t:insert("a", 1)
    t:insert("ab", 2)
    t:insert("abc", 3)
    local k, v = t:longest_prefix("abcdef")
    T.eq(k, "abc")
    T.eq(v, 3)
  end)

  T.it("returns nil when no prefix matches", function()
    local t = PT.new()
    t:insert("xyz", 1)
    local k = t:longest_prefix("abc")
    T.eq(k, nil)
  end)

  T.it("returns exact match when query == key", function()
    local t = PT.new()
    t:insert("hello", 42)
    local k, v = t:longest_prefix("hello")
    T.eq(k, "hello")
    T.eq(v, 42)
  end)

  T.it("prefers longer match over shorter", function()
    local t = PT.new()
    t:insert("foo", 1)
    t:insert("foobar", 2)
    local k, v = t:longest_prefix("foobarbaz")
    T.eq(k, "foobar")
    T.eq(v, 2)
  end)

  T.it("returns shortest match when only one fits", function()
    local t = PT.new()
    t:insert("foo", 1)
    t:insert("foobar", 2)
    local k, v = t:longest_prefix("foot")
    T.eq(k, "foo")
    T.eq(v, 1)
  end)

  T.it("empty-string key matches any query", function()
    local t = PT.new()
    t:insert("", 0)
    t:insert("ab", 2)
    local k, v = t:longest_prefix("abcdef")
    T.eq(k, "ab")
    T.eq(v, 2)
  end)
end)

T.describe("patricia_trie: autocomplete", function()
  T.it("returns keys (not pairs) with prefix", function()
    local t = PT.new()
    t:insert("go", 1)
    t:insert("golang", 2)
    t:insert("goodbye", 3)
    t:insert("good", 4)
    t:insert("python", 5)
    local keys = t:autocomplete("go")
    T.eq(#keys, 4)
    T.eq(keys[1], "go")
    T.eq(keys[2], "golang")
    T.eq(keys[3], "good")
    T.eq(keys[4], "goodbye")
  end)

  T.it("autocomplete with no match returns empty", function()
    local t = PT.new()
    t:insert("hello", 1)
    T.eq(#t:autocomplete("xyz"), 0)
  end)
end)

T.describe("patricia_trie: each and to_array", function()
  T.it("each visits all keys in sorted order", function()
    local t = PT.new()
    t:insert("banana", 2)
    t:insert("apple", 1)
    t:insert("cherry", 3)
    local seen = {}
    t:each(function(k, v) seen[#seen + 1] = { k, v } end)
    T.eq(#seen, 3)
    T.eq(seen[1][1], "apple")
    T.eq(seen[2][1], "banana")
    T.eq(seen[3][1], "cherry")
    T.eq(seen[1][2], 1)
    T.eq(seen[2][2], 2)
    T.eq(seen[3][2], 3)
  end)

  T.it("to_array returns sorted pairs", function()
    local t = PT.new()
    t:insert("z", 26)
    t:insert("a", 1)
    t:insert("m", 13)
    local arr = t:to_array()
    T.eq(#arr, 3)
    T.eq(arr[1][1], "a")
    T.eq(arr[2][1], "m")
    T.eq(arr[3][1], "z")
  end)

  T.it("to_array on empty trie returns empty table", function()
    local t = PT.new()
    T.eq(#t:to_array(), 0)
  end)
end)

T.describe("patricia_trie: height", function()
  T.it("height of empty trie is 0", function()
    local t = PT.new()
    T.eq(t:height(), 0)
  end)

  T.it("height of single key is 1", function()
    local t = PT.new()
    t:insert("abc", 1)
    T.eq(t:height(), 1)
  end)

  T.it("height grows with nesting", function()
    local t = PT.new()
    t:insert("a", 1)
    t:insert("ab", 2)
    t:insert("abc", 3)
    -- Patricia trie compresses: a / b / c might be 3 edges deep or 1 depending on splits.
    -- At least 1, at most 3.
    local h = t:height()
    T.ok(h >= 1)
    T.ok(h <= 3)
  end)
end)

T.describe("patricia_trie: empty key", function()
  T.it("empty string key can be inserted and retrieved", function()
    local t = PT.new()
    t:insert("", "root")
    T.eq(t:get(""), "root")
    T.ok(t:contains(""))
    T.eq(t:size(), 1)
  end)

  T.it("empty key can be removed", function()
    local t = PT.new()
    t:insert("", "root")
    T.ok(t:remove(""))
    T.eq(t:get(""), nil)
    T.eq(t:size(), 0)
  end)

  T.it("empty key coexists with other keys", function()
    local t = PT.new()
    t:insert("", 0)
    t:insert("a", 1)
    t:insert("ab", 2)
    T.eq(t:get(""), 0)
    T.eq(t:get("a"), 1)
    T.eq(t:get("ab"), 2)
    T.eq(t:size(), 3)
  end)
end)

T.describe("patricia_trie: stress test", function()
  T.it("insert 100 keys, get all", function()
    local t = PT.new()
    for i = 1, 100 do
      t:insert("key" .. i, i)
    end
    T.eq(t:size(), 100)
    for i = 1, 100 do
      T.eq(t:get("key" .. i), i)
    end
  end)

  T.it("insert 100, remove 50, verify remainder", function()
    local t = PT.new()
    for i = 1, 100 do
      t:insert("item" .. i, i)
    end
    -- Remove even-numbered items.
    for i = 1, 100 do
      if i % 2 == 0 then
        T.ok(t:remove("item" .. i))
      end
    end
    T.eq(t:size(), 50)
    for i = 1, 100 do
      if i % 2 == 0 then
        T.eq(t:get("item" .. i), nil)
      else
        T.eq(t:get("item" .. i), i)
      end
    end
  end)

  T.it("to_array after stress returns sorted list", function()
    local t = PT.new()
    local expected = {}
    for i = 1, 20 do
      local k = string.format("key%03d", i)
      t:insert(k, i)
      expected[#expected + 1] = k
    end
    table.sort(expected)
    local arr = t:to_array()
    T.eq(#arr, 20)
    for i = 1, #arr do
      T.eq(arr[i][1], expected[i])
    end
  end)
end)

T.describe("patricia_trie: unicode / binary keys", function()
  T.it("multi-byte UTF-8 keys treated as byte strings", function()
    local t = PT.new()
    -- These are valid UTF-8 strings; patricia trie treats them as byte sequences.
    t:insert("héllo", 1)
    t:insert("héllo world", 2)
    t:insert("café", 3)
    T.eq(t:get("héllo"), 1)
    T.eq(t:get("héllo world"), 2)
    T.eq(t:get("café"), 3)
    T.eq(t:size(), 3)
  end)

  T.it("prefix_search works on UTF-8 prefix", function()
    local t = PT.new()
    t:insert("héllo", 1)
    t:insert("héllo world", 2)
    t:insert("café", 3)
    local res = t:prefix_search("héllo")
    T.eq(#res, 2)
  end)

  T.it("binary / arbitrary byte keys", function()
    local t = PT.new()
    t:insert("\x00\x01\x02", "bin1")
    t:insert("\x00\x01\x03", "bin2")
    t:insert("\xFF", "maxbyte")
    T.eq(t:get("\x00\x01\x02"), "bin1")
    T.eq(t:get("\x00\x01\x03"), "bin2")
    T.eq(t:get("\xFF"), "maxbyte")
    T.eq(t:size(), 3)
  end)
end)

T.describe("patricia_trie: edge cases", function()
  T.it("single character keys", function()
    local t = PT.new()
    for i = 97, 122 do  -- a-z
      t:insert(string.char(i), i)
    end
    T.eq(t:size(), 26)
    for i = 97, 122 do
      T.eq(t:get(string.char(i)), i)
    end
  end)

  T.it("very long key", function()
    local t = PT.new()
    local long = string.rep("a", 1000)
    t:insert(long, "long")
    T.eq(t:get(long), "long")
    T.eq(t:get(long:sub(1, 999)), nil)
  end)

  T.it("insert same key multiple times only counts once", function()
    local t = PT.new()
    t:insert("dup", 1)
    t:insert("dup", 2)
    t:insert("dup", 3)
    T.eq(t:size(), 1)
    T.eq(t:get("dup"), 3)
  end)

  T.it("removing non-existent key from empty trie", function()
    local t = PT.new()
    T.ok(not t:remove("nope"))
    T.eq(t:size(), 0)
  end)

  T.it("prefix_search where prefix is a full key in trie", function()
    local t = PT.new()
    t:insert("pre", 1)
    t:insert("prefix", 2)
    t:insert("preface", 3)
    local res = t:prefix_search("pre")
    T.eq(#res, 3)
    local found = {}
    for i = 1, #res do found[res[i][1]] = true end
    T.ok(found["pre"])
    T.ok(found["prefix"])
    T.ok(found["preface"])
  end)

  T.it("prefix_search on prefix longer than any key", function()
    local t = PT.new()
    t:insert("hi", 1)
    local res = t:prefix_search("highlight")
    T.eq(#res, 0)
  end)

  T.it("is_empty after insertions and full removal", function()
    local t = PT.new()
    t:insert("a", 1)
    t:insert("b", 2)
    t:remove("a")
    t:remove("b")
    T.ok(t:is_empty())
    T.eq(t:size(), 0)
  end)
end)
