if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T    = require("lib.test.assert")
local crdt = require("lib.crdt")

-- ─── helpers ─────────────────────────────────────────────────────────────────

-- Returns true when two plain key→true tables have identical key sets.
local function set_eq(a, b)
  for k in pairs(a) do
    if not b[k] then return false end
  end
  for k in pairs(b) do
    if not a[k] then return false end
  end
  return true
end

-- ─── G-Counter ───────────────────────────────────────────────────────────────

T.describe("GCounter", function()
  T.it("starts at zero", function()
    local gc = crdt.gcounter("r1")
    T.eq(gc:value(), 0)
  end)

  T.it("increments by 1", function()
    local gc = crdt.gcounter("r1")
    gc:increment()
    T.eq(gc:value(), 1)
  end)

  T.it("increments by n", function()
    local gc = crdt.gcounter("r1")
    gc:increment(5)
    T.eq(gc:value(), 5)
  end)

  T.it("merge takes per-replica max", function()
    local a = crdt.gcounter("r1")
    local b = crdt.gcounter("r2")
    a:increment(3)
    b:increment(2)
    a:merge(b)
    T.eq(a:value(), 5)
  end)

  T.it("merge does not shrink own count", function()
    local a = crdt.gcounter("r1")
    local b = crdt.gcounter("r1")
    a:increment(10)
    b:increment(3)
    a:merge(b)
    T.eq(a:value(), 10)
  end)

  T.it("commutativity: merge(a,b) == merge(b,a)", function()
    local a = crdt.gcounter("r1")
    local b = crdt.gcounter("r2")
    a:increment(4)
    b:increment(7)
    local ab = a:clone(); ab:merge(b)
    local ba = b:clone(); ba:merge(a)
    T.eq(ab:value(), ba:value())
  end)

  T.it("idempotency: merge(a,a) == a", function()
    local a = crdt.gcounter("r1")
    a:increment(6)
    local before = a:value()
    a:merge(a:clone())
    T.eq(a:value(), before)
  end)

  T.it("associativity: merge(merge(a,b),c) == merge(a,merge(b,c))", function()
    local a = crdt.gcounter("r1")
    local b = crdt.gcounter("r2")
    local c = crdt.gcounter("r3")
    a:increment(1); b:increment(2); c:increment(3)
    local left  = a:clone(); left:merge(b);  left:merge(c)
    local right = a:clone(); local bc = b:clone(); bc:merge(c); right:merge(bc)
    T.eq(left:value(), right:value())
  end)

  T.it("clone is independent", function()
    local a = crdt.gcounter("r1")
    a:increment(5)
    local b = a:clone()
    b:increment(10)
    T.eq(a:value(), 5)
    T.eq(b:value(), 15)
  end)
end)

-- ─── PN-Counter ──────────────────────────────────────────────────────────────

T.describe("PNCounter", function()
  T.it("starts at zero", function()
    local pn = crdt.pncounter("r1")
    T.eq(pn:value(), 0)
  end)

  T.it("increment and decrement", function()
    local pn = crdt.pncounter("r1")
    pn:increment(5)
    pn:decrement(3)
    T.eq(pn:value(), 2)
  end)

  T.it("can go negative", function()
    local pn = crdt.pncounter("r1")
    pn:decrement(4)
    T.eq(pn:value(), -4)
  end)

  T.it("merge from multiple replicas", function()
    local a = crdt.pncounter("r1")
    local b = crdt.pncounter("r2")
    a:increment(10)
    b:decrement(3)
    a:merge(b)
    T.eq(a:value(), 7)
  end)

  T.it("commutativity", function()
    local a = crdt.pncounter("r1")
    local b = crdt.pncounter("r2")
    a:increment(5); a:decrement(1)
    b:increment(3); b:decrement(2)
    local ab = a:clone(); ab:merge(b)
    local ba = b:clone(); ba:merge(a)
    T.eq(ab:value(), ba:value())
  end)

  T.it("idempotency", function()
    local pn = crdt.pncounter("r1")
    pn:increment(7); pn:decrement(2)
    local before = pn:value()
    pn:merge(pn:clone())
    T.eq(pn:value(), before)
  end)

  T.it("associativity", function()
    local a = crdt.pncounter("r1")
    local b = crdt.pncounter("r2")
    local c = crdt.pncounter("r3")
    a:increment(3); b:decrement(1); c:increment(2)
    local left  = a:clone(); left:merge(b); left:merge(c)
    local right = a:clone(); local bc = b:clone(); bc:merge(c); right:merge(bc)
    T.eq(left:value(), right:value())
  end)
end)

-- ─── LWW-Register ────────────────────────────────────────────────────────────

T.describe("LWWRegister", function()
  T.it("get returns nil before set", function()
    local reg = crdt.lww_register("r1")
    local v, ts = reg:get()
    T.eq(v,  nil)
    T.eq(ts, -1)
  end)

  T.it("set and get", function()
    local reg = crdt.lww_register("r1")
    reg:set("hello", 1)
    local v, ts = reg:get()
    T.eq(v,  "hello")
    T.eq(ts, 1)
  end)

  T.it("higher timestamp wins", function()
    local reg = crdt.lww_register("r1")
    reg:set("a", 1)
    reg:set("b", 3)
    reg:set("c", 2)  -- older — should not overwrite
    local v = reg:get()
    T.eq(v, "b")
  end)

  T.it("merge keeps higher timestamp", function()
    local a = crdt.lww_register("r1")
    local b = crdt.lww_register("r2")
    a:set("old", 1)
    b:set("new", 5)
    a:merge(b)
    local v, ts = a:get()
    T.eq(v,  "new")
    T.eq(ts, 5)
  end)

  T.it("merge does not downgrade", function()
    local a = crdt.lww_register("r1")
    local b = crdt.lww_register("r2")
    a:set("high", 10)
    b:set("low",   2)
    a:merge(b)
    local v = a:get()
    T.eq(v, "high")
  end)

  T.it("commutativity", function()
    local a = crdt.lww_register("r1")
    local b = crdt.lww_register("r2")
    a:set("A", 3)
    b:set("B", 7)
    local ab = a:clone(); ab:merge(b)
    local ba = b:clone(); ba:merge(a)
    local vab = ab:get()
    local vba = ba:get()
    T.eq(vab, vba)
  end)

  T.it("idempotency", function()
    local reg = crdt.lww_register("r1")
    reg:set("x", 4)
    reg:merge(reg:clone())
    local v, ts = reg:get()
    T.eq(v,  "x")
    T.eq(ts, 4)
  end)
end)

-- ─── 2P-Set ──────────────────────────────────────────────────────────────────

T.describe("TPSet", function()
  T.it("empty set contains nothing", function()
    local s = crdt.tpset()
    T.fail(s:contains("a"))
  end)

  T.it("add and contains", function()
    local s = crdt.tpset()
    s:add("a")
    T.ok(s:contains("a"))
  end)

  T.it("remove works", function()
    local s = crdt.tpset()
    s:add("a")
    s:remove("a")
    T.fail(s:contains("a"))
  end)

  T.it("removed elements cannot be re-added", function()
    local s = crdt.tpset()
    s:add("a")
    s:remove("a")
    s:add("a")        -- silently ignored — remove wins
    T.fail(s:contains("a"))
  end)

  T.it("value returns live elements", function()
    local s = crdt.tpset()
    s:add("a"); s:add("b"); s:add("c")
    s:remove("b")
    local v = s:value()
    T.ok(v["a"])
    T.fail(v["b"])
    T.ok(v["c"])
  end)

  T.it("merge unions both sets", function()
    local a = crdt.tpset()
    local b = crdt.tpset()
    a:add("x"); a:add("y")
    b:add("y"); b:add("z"); b:remove("y")
    a:merge(b)
    T.ok(a:contains("x"))
    T.fail(a:contains("y"))   -- removal from b propagates
    T.ok(a:contains("z"))
  end)

  T.it("commutativity", function()
    local a = crdt.tpset()
    local b = crdt.tpset()
    a:add("p"); a:add("q"); a:remove("q")
    b:add("q"); b:add("r")
    local ab = a:clone(); ab:merge(b)
    local ba = b:clone(); ba:merge(a)
    T.ok(ab:eq(ba))
  end)

  T.it("idempotency", function()
    local s = crdt.tpset()
    s:add("a"); s:remove("a"); s:add("b")
    local c = s:clone(); s:merge(c)
    T.ok(s:eq(c))
  end)

  T.it("associativity", function()
    local a = crdt.tpset(); a:add("x")
    local b = crdt.tpset(); b:add("y"); b:remove("y")
    local c = crdt.tpset(); c:add("z"); c:add("x"); c:remove("x")
    local left  = a:clone(); left:merge(b); left:merge(c)
    local right = a:clone(); local bc = b:clone(); bc:merge(c); right:merge(bc)
    T.ok(left:eq(right))
  end)
end)

-- ─── OR-Set ──────────────────────────────────────────────────────────────────

T.describe("ORSet", function()
  T.it("empty set contains nothing", function()
    local s = crdt.orset("r1")
    T.fail(s:contains("a"))
  end)

  T.it("add and contains", function()
    local s = crdt.orset("r1")
    s:add("a")
    T.ok(s:contains("a"))
  end)

  T.it("remove wipes element", function()
    local s = crdt.orset("r1")
    s:add("a")
    s:remove("a")
    T.fail(s:contains("a"))
  end)

  T.it("re-add after remove", function()
    local s = crdt.orset("r1")
    s:add("a")
    s:remove("a")
    s:add("a")
    T.ok(s:contains("a"))
  end)

  T.it("value reflects live elements", function()
    local s = crdt.orset("r1")
    s:add("a"); s:add("b"); s:remove("a")
    local v = s:value()
    T.fail(v["a"])
    T.ok(v["b"])
  end)

  T.it("merge unions observed tags", function()
    local a = crdt.orset("r1")
    local b = crdt.orset("r2")
    a:add("x")
    b:add("x")
    b:remove("x")      -- b removes its own tag only
    a:merge(b)
    -- a still has its own tag for "x", so it should still be present
    T.ok(a:contains("x"))
  end)

  T.it("remove then merge: concurrent add wins in OR-set semantics", function()
    -- replica A adds "x"; replica B concurrently removes "x"
    -- after merge, A's add tag survives because B only knew B's tags (none here)
    local a = crdt.orset("r1")
    local b = crdt.orset("r2")
    a:add("x")
    -- B has not observed A's add, so B's remove removes nothing
    b:remove("x")
    a:merge(b)
    T.ok(a:contains("x"))
  end)

  T.it("commutativity", function()
    local a = crdt.orset("r1")
    local b = crdt.orset("r2")
    a:add("p"); a:add("q")
    b:add("q"); b:remove("q"); b:add("r")
    local ab = a:clone(); ab:merge(b)
    local ba = b:clone(); ba:merge(a)
    T.ok(ab:eq(ba))
  end)

  T.it("idempotency", function()
    local s = crdt.orset("r1")
    s:add("a"); s:remove("a"); s:add("b")
    local c = s:clone()
    s:merge(c)
    T.ok(s:eq(c))
  end)

  T.it("associativity", function()
    local a = crdt.orset("r1"); a:add("x")
    local b = crdt.orset("r2"); b:add("y")
    local c = crdt.orset("r3"); c:add("z"); c:add("y"); c:remove("y")
    local left  = a:clone(); left:merge(b); left:merge(c)
    local right = a:clone(); local bc = b:clone(); bc:merge(c); right:merge(bc)
    T.ok(left:eq(right))
  end)
end)

-- ─── LWW-Map ─────────────────────────────────────────────────────────────────

T.describe("LWWMap", function()
  T.it("get on missing key returns nil", function()
    local m = crdt.lww_map("r1")
    T.eq(m:get("k"), nil)
  end)

  T.it("set and get", function()
    local m = crdt.lww_map("r1")
    m:set("k", "v", 1)
    local v, ts = m:get("k")
    T.eq(v,  "v")
    T.eq(ts, 1)
  end)

  T.it("higher-timestamp update wins", function()
    local m = crdt.lww_map("r1")
    m:set("k", "old", 1)
    m:set("k", "new", 5)
    T.eq(m:get("k"), "new")
  end)

  T.it("lower-timestamp update is ignored", function()
    local m = crdt.lww_map("r1")
    m:set("k", "new", 5)
    m:set("k", "old", 1)
    T.eq(m:get("k"), "new")
  end)

  T.it("delete tombstones the key", function()
    local m = crdt.lww_map("r1")
    m:set("k", "v", 1)
    m:delete("k", 3)
    T.eq(m:get("k"), nil)
  end)

  T.it("set after delete with higher ts revives key", function()
    local m = crdt.lww_map("r1")
    m:set("k", "v", 1)
    m:delete("k", 3)
    m:set("k", "revived", 5)
    T.eq(m:get("k"), "revived")
  end)

  T.it("set with lower ts after delete does not revive", function()
    local m = crdt.lww_map("r1")
    m:set("k", "v", 3)
    m:delete("k", 5)
    m:set("k", "old", 2)  -- lower ts than tombstone
    T.eq(m:get("k"), nil)
  end)

  T.it("keys returns only live keys", function()
    local m = crdt.lww_map("r1")
    m:set("a", 1, 1); m:set("b", 2, 1); m:set("c", 3, 1)
    m:delete("b", 2)
    local ks = m:keys()
    table.sort(ks)
    T.eq(#ks, 2)
    T.eq(ks[1], "a")
    T.eq(ks[2], "c")
  end)

  T.it("merge keeps higher-ts entries", function()
    local a = crdt.lww_map("r1")
    local b = crdt.lww_map("r2")
    a:set("x", "from_a", 1)
    b:set("x", "from_b", 5)
    a:merge(b)
    T.eq(a:get("x"), "from_b")
  end)

  T.it("merge propagates tombstones", function()
    local a = crdt.lww_map("r1")
    local b = crdt.lww_map("r2")
    a:set("x", "val", 1)
    b:delete("x", 3)
    a:merge(b)
    T.eq(a:get("x"), nil)
  end)

  T.it("commutativity", function()
    local a = crdt.lww_map("r1")
    local b = crdt.lww_map("r2")
    a:set("p", "ap", 2); a:set("q", "aq", 1)
    b:set("p", "bp", 5); b:delete("q", 3)
    local ab = a:clone(); ab:merge(b)
    local ba = b:clone(); ba:merge(a)
    T.ok(ab:eq(ba))
  end)

  T.it("idempotency", function()
    local m = crdt.lww_map("r1")
    m:set("a", 1, 1); m:delete("b", 2)
    local c = m:clone()
    m:merge(c)
    T.ok(m:eq(c))
  end)

  T.it("associativity", function()
    local a = crdt.lww_map("r1"); a:set("x", "a", 1)
    local b = crdt.lww_map("r2"); b:set("x", "b", 3); b:set("y", "by", 1)
    local c = crdt.lww_map("r3"); c:delete("y", 5)
    local left  = a:clone(); left:merge(b); left:merge(c)
    local right = a:clone(); local bc = b:clone(); bc:merge(c); right:merge(bc)
    T.ok(left:eq(right))
  end)
end)

-- ─── _tier ───────────────────────────────────────────────────────────────────

T.describe("module", function()
  T.it("_tier is 'pure'", function()
    T.eq(crdt._tier, "pure")
  end)
end)
