-- lib/web/js_types.lua
-- DOM and browser API type declarations for use with the crescent typechecker.
-- Covers the full browser API surface area for use in WebAssembly / WASM Lua environments.
-- No executable code — type annotations only.

---------------------------------------------------------------------------
-- DOMTokenList (classList)
---------------------------------------------------------------------------

--:: DOMTokenList = {
--::   length:   integer,
--::   value:    string,
--::   add:      (...string) -> (),
--::   remove:   (...string) -> (),
--::   toggle:   (string, boolean | nil) -> boolean,
--::   contains: (string) -> boolean,
--::   replace:  (string, string) -> (),
--::   supports: (string) -> boolean,
--::   item:     (integer) -> string | nil,
--::   [integer]: string,
--::   ...
--:: }

---------------------------------------------------------------------------
-- CSSStyleDeclaration (element.style)
---------------------------------------------------------------------------

--:: CSSStyleDeclaration = {
--::   cssText:             string,
--::   length:              integer,
--::   setProperty:         (string, string, string | nil) -> (),
--::   getPropertyValue:    (string) -> string,
--::   getPropertyPriority: (string) -> string,
--::   removeProperty:      (string) -> string,
--::   item:                (integer) -> string,
--::   [string]:            string,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Events
---------------------------------------------------------------------------

--:: Event = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   ...
--:: }

--:: UIEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   ...
--:: }

--:: MouseEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   clientX:                  number,
--::   clientY:                  number,
--::   screenX:                  number,
--::   screenY:                  number,
--::   pageX:                    number,
--::   pageY:                    number,
--::   offsetX:                  number,
--::   offsetY:                  number,
--::   movementX:                number,
--::   movementY:                number,
--::   x:                        number,
--::   y:                        number,
--::   button:                   integer,
--::   buttons:                  integer,
--::   altKey:                   boolean,
--::   ctrlKey:                  boolean,
--::   shiftKey:                 boolean,
--::   metaKey:                  boolean,
--::   relatedTarget:            EventTarget | nil,
--::   getModifierState:         (string) -> boolean,
--::   ...
--:: }

--:: PointerEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   clientX:                  number,
--::   clientY:                  number,
--::   screenX:                  number,
--::   screenY:                  number,
--::   pageX:                    number,
--::   pageY:                    number,
--::   offsetX:                  number,
--::   offsetY:                  number,
--::   movementX:                number,
--::   movementY:                number,
--::   x:                        number,
--::   y:                        number,
--::   button:                   integer,
--::   buttons:                  integer,
--::   altKey:                   boolean,
--::   ctrlKey:                  boolean,
--::   shiftKey:                 boolean,
--::   metaKey:                  boolean,
--::   relatedTarget:            EventTarget | nil,
--::   pointerId:                integer,
--::   width:                    number,
--::   height:                   number,
--::   pressure:                 number,
--::   tangentialPressure:       number,
--::   tiltX:                    integer,
--::   tiltY:                    integer,
--::   twist:                    integer,
--::   pointerType:              string,
--::   isPrimary:                boolean,
--::   getCoalescedEvents:       () -> { [integer]: PointerEvent, ... },
--::   getPredictedEvents:       () -> { [integer]: PointerEvent, ... },
--::   getModifierState:         (string) -> boolean,
--::   ...
--:: }

--:: WheelEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   clientX:                  number,
--::   clientY:                  number,
--::   screenX:                  number,
--::   screenY:                  number,
--::   pageX:                    number,
--::   pageY:                    number,
--::   offsetX:                  number,
--::   offsetY:                  number,
--::   movementX:                number,
--::   movementY:                number,
--::   button:                   integer,
--::   buttons:                  integer,
--::   altKey:                   boolean,
--::   ctrlKey:                  boolean,
--::   shiftKey:                 boolean,
--::   metaKey:                  boolean,
--::   deltaX:                   number,
--::   deltaY:                   number,
--::   deltaZ:                   number,
--::   deltaMode:                integer,
--::   ...
--:: }

--:: KeyboardEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   key:                      string,
--::   code:                     string,
--::   location:                 integer,
--::   repeat:                   boolean,
--::   isComposing:              boolean,
--::   altKey:                   boolean,
--::   ctrlKey:                  boolean,
--::   shiftKey:                 boolean,
--::   metaKey:                  boolean,
--::   getModifierState:         (string) -> boolean,
--::   ...
--:: }

--:: FocusEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   relatedTarget:            EventTarget | nil,
--::   ...
--:: }

--:: InputEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   data:                     string | nil,
--::   dataTransfer:             DataTransfer | nil,
--::   inputType:                string,
--::   isComposing:              boolean,
--::   ...
--:: }

--:: DragEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   clientX:                  number,
--::   clientY:                  number,
--::   screenX:                  number,
--::   screenY:                  number,
--::   button:                   integer,
--::   buttons:                  integer,
--::   altKey:                   boolean,
--::   ctrlKey:                  boolean,
--::   shiftKey:                 boolean,
--::   metaKey:                  boolean,
--::   dataTransfer:             DataTransfer | nil,
--::   ...
--:: }

--:: ClipboardEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   clipboardData:            DataTransfer | nil,
--::   ...
--:: }

--:: CompositionEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   integer,
--::   data:                     string,
--::   ...
--:: }

--:: AnimationEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   animationName:            string,
--::   elapsedTime:              number,
--::   pseudoElement:            string,
--::   ...
--:: }

--:: TransitionEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   propertyName:             string,
--::   elapsedTime:              number,
--::   pseudoElement:            string,
--::   ...
--:: }

--:: ProgressEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   lengthComputable:         boolean,
--::   loaded:                   integer,
--::   total:                    integer,
--::   ...
--:: }

--:: ErrorEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   message:                  string,
--::   filename:                 string,
--::   lineno:                   integer,
--::   colno:                    integer,
--::   error:                    unknown,
--::   ...
--:: }

--:: MessageEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   data:                     unknown,
--::   lastEventId:              string,
--::   origin:                   string,
--::   ports:                    { [integer]: MessagePort, ... },
--::   ...
--:: }

--:: CloseEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   code:                     integer,
--::   reason:                   string,
--::   wasClean:                 boolean,
--::   ...
--:: }

--:: CustomEvent = {
--::   type:                     string,
--::   target:                   EventTarget | nil,
--::   currentTarget:            EventTarget | nil,
--::   bubbles:                  boolean,
--::   cancelable:               boolean,
--::   composed:                 boolean,
--::   defaultPrevented:         boolean,
--::   eventPhase:               integer,
--::   isTrusted:                boolean,
--::   timeStamp:                number,
--::   preventDefault:           () -> (),
--::   stopPropagation:          () -> (),
--::   stopImmediatePropagation: () -> (),
--::   composedPath:             () -> { [integer]: EventTarget, ... },
--::   detail:                   unknown,
--::   ...
--:: }

-- Union of all event types for addEventListener callbacks.
--:: AnyEvent = Event | UIEvent | MouseEvent | PointerEvent | WheelEvent | KeyboardEvent | FocusEvent | InputEvent | DragEvent | ClipboardEvent | CompositionEvent | AnimationEvent | TransitionEvent | ProgressEvent | ErrorEvent | MessageEvent | CloseEvent | CustomEvent

---------------------------------------------------------------------------
-- DataTransfer
---------------------------------------------------------------------------

--:: DataTransferItem = {
--::   kind:        string,
--::   type:        string,
--::   getAsFile:   () -> File | nil,
--::   getAsString: ((string) -> ()) -> (),
--::   ...
--:: }

--:: DataTransferItemList = {
--::   length: integer,
--::   add:    (string, string) -> DataTransferItem | nil,
--::   clear:  () -> (),
--::   remove: (integer) -> (),
--::   [integer]: DataTransferItem,
--::   ...
--:: }

--:: DataTransfer = {
--::   dropEffect:   string,
--::   effectAllowed: string,
--::   items:        DataTransferItemList,
--::   types:        { [integer]: string, ... },
--::   clearData:    (string | nil) -> (),
--::   getData:      (string) -> string,
--::   setData:      (string, string) -> (),
--::   setDragImage: (Element, integer, integer) -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- File / Blob
---------------------------------------------------------------------------

--:: Blob = {
--::   size:        integer,
--::   type:        string,
--::   arrayBuffer: () -> Promise,
--::   slice:       (integer | nil, integer | nil, string | nil) -> Blob,
--::   stream:      () -> ReadableStream,
--::   text:        () -> Promise,
--::   ...
--:: }

--:: File = {
--::   size:               integer,
--::   type:               string,
--::   arrayBuffer:        () -> Promise,
--::   slice:              (integer | nil, integer | nil, string | nil) -> Blob,
--::   stream:             () -> ReadableStream,
--::   text:               () -> Promise,
--::   lastModified:       integer,
--::   name:               string,
--::   webkitRelativePath: string,
--::   ...
--:: }

--:: FileList = {
--::   length: integer,
--::   item:   (integer) -> File | nil,
--::   [integer]: File,
--::   ...
--:: }

---------------------------------------------------------------------------
-- EventTarget (base for Node and Window)
---------------------------------------------------------------------------

--:: EventTarget = {
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- AbortSignal / AbortController
---------------------------------------------------------------------------

--:: AbortSignal = {
--::   aborted:            boolean,
--::   reason:             unknown,
--::   throwIfAborted:     () -> (),
--::   addEventListener:   (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener:(string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:      (Event) -> boolean,
--::   ...
--:: }

--:: AbortController = {
--::   signal: AbortSignal,
--::   abort:  (unknown | nil) -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- Node
---------------------------------------------------------------------------

--:: Node = {
--::   parentNode:       Node | nil,
--::   parentElement:    Element | nil,
--::   childNodes:       { [integer]: Node, length: integer, ... },
--::   firstChild:       Node | nil,
--::   lastChild:        Node | nil,
--::   nextSibling:      Node | nil,
--::   previousSibling:  Node | nil,
--::   textContent:      string | nil,
--::   nodeType:         integer,
--::   nodeName:         string,
--::   nodeValue:        string | nil,
--::   baseURI:          string,
--::   isConnected:      boolean,
--::   ownerDocument:    Document | nil,
--::   appendChild:      (Node) -> Node,
--::   removeChild:      (Node) -> Node,
--::   insertBefore:     (Node, Node | nil) -> Node,
--::   replaceChild:     (Node, Node) -> Node,
--::   cloneNode:        (boolean | nil) -> Node,
--::   contains:         (Node | nil) -> boolean,
--::   hasChildNodes:    () -> boolean,
--::   normalize:        () -> (),
--::   isEqualNode:      (Node | nil) -> boolean,
--::   compareDocumentPosition: (Node) -> integer,
--::   getRootNode:      () -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- NodeList (querySelectorAll result)
---------------------------------------------------------------------------

--:: NodeList = {
--::   length: integer,
--::   item:   (integer) -> Node | nil,
--::   forEach: ((Node, integer, NodeList) -> ()) -> (),
--::   [integer]: Node,
--::   ...
--:: }

---------------------------------------------------------------------------
-- HTMLCollection (element.children)
---------------------------------------------------------------------------

--:: HTMLCollection = {
--::   length: integer,
--::   item:       (integer) -> Element | nil,
--::   namedItem:  (string) -> Element | nil,
--::   [integer]:  Element,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Element: Node
---------------------------------------------------------------------------

--:: Element = {
--::   parentNode:         Node | nil,
--::   parentElement:      Element | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   firstChild:         Node | nil,
--::   lastChild:          Node | nil,
--::   nextSibling:        Node | nil,
--::   previousSibling:    Node | nil,
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   nodeValue:          string | nil,
--::   baseURI:            string,
--::   isConnected:        boolean,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   removeChild:        (Node) -> Node,
--::   insertBefore:       (Node, Node | nil) -> Node,
--::   replaceChild:       (Node, Node) -> Node,
--::   cloneNode:          (boolean | nil) -> Element,
--::   contains:           (Node | nil) -> boolean,
--::   hasChildNodes:      () -> boolean,
--::   normalize:          () -> (),
--::   isEqualNode:        (Node | nil) -> boolean,
--::   compareDocumentPosition: (Node) -> integer,
--::   getRootNode:        () -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   innerHTML:           string,
--::   outerHTML:           string,
--::   children:            HTMLCollection,
--::   childElementCount:   integer,
--::   firstElementChild:   Element | nil,
--::   lastElementChild:    Element | nil,
--::   nextElementSibling:  Element | nil,
--::   previousElementSibling: Element | nil,
--::   scrollTop:           number,
--::   scrollLeft:          number,
--::   scrollWidth:         integer,
--::   scrollHeight:        integer,
--::   clientTop:           integer,
--::   clientLeft:          integer,
--::   clientWidth:         integer,
--::   clientHeight:        integer,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   removeAttribute:     (string) -> (),
--::   hasAttribute:        (string) -> boolean,
--::   toggleAttribute:     (string, boolean | nil) -> boolean,
--::   getAttributeNames:   () -> { [integer]: string, ... },
--::   getAttributeNS:      (string | nil, string) -> string | nil,
--::   setAttributeNS:      (string | nil, string, string) -> (),
--::   removeAttributeNS:   (string | nil, string) -> (),
--::   hasAttributeNS:      (string | nil, string) -> boolean,
--::   getBoundingClientRect: () -> DOMRect,
--::   getClientRects:      () -> { [integer]: DOMRect, ... },
--::   scrollIntoView:      (boolean | nil) -> (),
--::   scroll:              (number | nil, number | nil) -> (),
--::   scrollTo:            (number | nil, number | nil) -> (),
--::   scrollBy:            (number | nil, number | nil) -> (),
--::   closest:             (string) -> Element | nil,
--::   matches:             (string) -> boolean,
--::   querySelector:       (string) -> Element | nil,
--::   querySelectorAll:    (string) -> NodeList,
--::   getElementsByTagName:      (string) -> HTMLCollection,
--::   getElementsByClassName:    (string) -> HTMLCollection,
--::   insertAdjacentElement:     (string, Element) -> Element | nil,
--::   insertAdjacentHTML:        (string, string) -> (),
--::   insertAdjacentText:        (string, string) -> (),
--::   after:               (...unknown) -> (),
--::   before:              (...unknown) -> (),
--::   remove:              () -> (),
--::   replaceWith:         (...unknown) -> (),
--::   append:              (...unknown) -> (),
--::   prepend:             (...unknown) -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- DOMRect
---------------------------------------------------------------------------

--:: DOMRect = {
--::   x:      number,
--::   y:      number,
--::   width:  number,
--::   height: number,
--::   top:    number,
--::   right:  number,
--::   bottom: number,
--::   left:   number,
--::   ...
--:: }

---------------------------------------------------------------------------
-- HTMLElement: Element
---------------------------------------------------------------------------

--:: HTMLElement = {
--::   parentNode:         Node | nil,
--::   parentElement:      Element | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   firstChild:         Node | nil,
--::   lastChild:          Node | nil,
--::   nextSibling:        Node | nil,
--::   previousSibling:    Node | nil,
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   nodeValue:          string | nil,
--::   baseURI:            string,
--::   isConnected:        boolean,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   removeChild:        (Node) -> Node,
--::   insertBefore:       (Node, Node | nil) -> Node,
--::   replaceChild:       (Node, Node) -> Node,
--::   cloneNode:          (boolean | nil) -> HTMLElement,
--::   contains:           (Node | nil) -> boolean,
--::   hasChildNodes:      () -> boolean,
--::   normalize:          () -> (),
--::   isEqualNode:        (Node | nil) -> boolean,
--::   compareDocumentPosition: (Node) -> integer,
--::   getRootNode:        () -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   innerHTML:           string,
--::   outerHTML:           string,
--::   children:            HTMLCollection,
--::   childElementCount:   integer,
--::   firstElementChild:   Element | nil,
--::   lastElementChild:    Element | nil,
--::   nextElementSibling:  Element | nil,
--::   previousElementSibling: Element | nil,
--::   scrollTop:           number,
--::   scrollLeft:          number,
--::   scrollWidth:         integer,
--::   scrollHeight:        integer,
--::   clientTop:           integer,
--::   clientLeft:          integer,
--::   clientWidth:         integer,
--::   clientHeight:        integer,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   removeAttribute:     (string) -> (),
--::   hasAttribute:        (string) -> boolean,
--::   toggleAttribute:     (string, boolean | nil) -> boolean,
--::   getAttributeNames:   () -> { [integer]: string, ... },
--::   getAttributeNS:      (string | nil, string) -> string | nil,
--::   setAttributeNS:      (string | nil, string, string) -> (),
--::   removeAttributeNS:   (string | nil, string) -> (),
--::   hasAttributeNS:      (string | nil, string) -> boolean,
--::   getBoundingClientRect: () -> DOMRect,
--::   getClientRects:      () -> { [integer]: DOMRect, ... },
--::   scrollIntoView:      (boolean | nil) -> (),
--::   scroll:              (number | nil, number | nil) -> (),
--::   scrollTo:            (number | nil, number | nil) -> (),
--::   scrollBy:            (number | nil, number | nil) -> (),
--::   closest:             (string) -> Element | nil,
--::   matches:             (string) -> boolean,
--::   querySelector:       (string) -> Element | nil,
--::   querySelectorAll:    (string) -> NodeList,
--::   getElementsByTagName:      (string) -> HTMLCollection,
--::   getElementsByClassName:    (string) -> HTMLCollection,
--::   insertAdjacentElement:     (string, Element) -> Element | nil,
--::   insertAdjacentHTML:        (string, string) -> (),
--::   insertAdjacentText:        (string, string) -> (),
--::   after:               (...unknown) -> (),
--::   before:              (...unknown) -> (),
--::   remove:              () -> (),
--::   replaceWith:         (...unknown) -> (),
--::   append:              (...unknown) -> (),
--::   prepend:             (...unknown) -> (),
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   accessKey:           string,
--::   accessKeyLabel:      string,
--::   contentEditable:     string,
--::   dir:                 string,
--::   draggable:           boolean,
--::   enterKeyHint:        string,
--::   hidden:              boolean,
--::   inert:               boolean,
--::   innerText:           string,
--::   inputMode:           string,
--::   isContentEditable:   boolean,
--::   lang:                string,
--::   nonce:               string,
--::   offsetWidth:         integer,
--::   offsetHeight:        integer,
--::   offsetLeft:          integer,
--::   offsetTop:           integer,
--::   offsetParent:        HTMLElement | nil,
--::   outerText:           string,
--::   tabIndex:            integer,
--::   title:               string,
--::   focus:               () -> (),
--::   blur:                () -> (),
--::   click:               () -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- Form elements
---------------------------------------------------------------------------

--:: HTMLInputElement = {
--::   parentNode:         Node | nil,
--::   parentElement:      Element | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   removeChild:        (Node) -> Node,
--::   insertBefore:       (Node, Node | nil) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   innerHTML:           string,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   removeAttribute:     (string) -> (),
--::   hasAttribute:        (string) -> boolean,
--::   getBoundingClientRect: () -> DOMRect,
--::   querySelector:       (string) -> Element | nil,
--::   querySelectorAll:    (string) -> NodeList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   tabIndex:            integer,
--::   focus:               () -> (),
--::   blur:                () -> (),
--::   click:               () -> (),
--::   accept:              string,
--::   alt:                 string,
--::   autocomplete:        string,
--::   checked:             boolean,
--::   defaultChecked:      boolean,
--::   defaultValue:        string,
--::   disabled:            boolean,
--::   files:               FileList | nil,
--::   form:                HTMLFormElement | nil,
--::   formAction:          string,
--::   formEnctype:         string,
--::   formMethod:          string,
--::   formNoValidate:      boolean,
--::   formTarget:          string,
--::   height:              integer,
--::   indeterminate:       boolean,
--::   list:                HTMLElement | nil,
--::   max:                 string,
--::   maxLength:           integer,
--::   min:                 string,
--::   minLength:           integer,
--::   multiple:            boolean,
--::   name:                string,
--::   pattern:             string,
--::   placeholder:         string,
--::   readOnly:            boolean,
--::   required:            boolean,
--::   selectionDirection:  string | nil,
--::   selectionEnd:        integer | nil,
--::   selectionStart:      integer | nil,
--::   size:                integer,
--::   src:                 string,
--::   step:                string,
--::   type:                string,
--::   validity:            ValidityState,
--::   value:               string,
--::   valueAsDate:         unknown,
--::   valueAsNumber:       number,
--::   width:               integer,
--::   willValidate:        boolean,
--::   checkValidity:       () -> boolean,
--::   reportValidity:      () -> boolean,
--::   select:              () -> (),
--::   setCustomValidity:   (string) -> (),
--::   setRangeText:        (string, integer | nil, integer | nil, string | nil) -> (),
--::   setSelectionRange:   (integer, integer, string | nil) -> (),
--::   stepDown:            (integer | nil) -> (),
--::   stepUp:              (integer | nil) -> (),
--::   ...
--:: }

--:: HTMLSelectElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   focus:               () -> (),
--::   blur:                () -> (),
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   getBoundingClientRect: () -> DOMRect,
--::   autocomplete:        string,
--::   disabled:            boolean,
--::   form:                HTMLFormElement | nil,
--::   labels:              NodeList,
--::   length:              integer,
--::   multiple:            boolean,
--::   name:                string,
--::   options:             HTMLCollection,
--::   required:            boolean,
--::   selectedIndex:       integer,
--::   selectedOptions:     HTMLCollection,
--::   size:                integer,
--::   type:                string,
--::   validity:            ValidityState,
--::   value:               string,
--::   willValidate:        boolean,
--::   add:                 (HTMLElement, HTMLElement | integer | nil) -> (),
--::   checkValidity:       () -> boolean,
--::   item:                (integer) -> HTMLElement | nil,
--::   namedItem:           (string) -> HTMLElement | nil,
--::   remove:              (integer | nil) -> (),
--::   reportValidity:      () -> boolean,
--::   setCustomValidity:   (string) -> (),
--::   [integer]:           HTMLElement,
--::   ...
--:: }

--:: HTMLTextAreaElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   focus:               () -> (),
--::   blur:                () -> (),
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   getBoundingClientRect: () -> DOMRect,
--::   autocomplete:        string,
--::   cols:                integer,
--::   defaultValue:        string,
--::   disabled:            boolean,
--::   form:                HTMLFormElement | nil,
--::   inputMode:           string,
--::   labels:              NodeList,
--::   maxLength:           integer,
--::   minLength:           integer,
--::   name:                string,
--::   placeholder:         string,
--::   readOnly:            boolean,
--::   required:            boolean,
--::   rows:                integer,
--::   selectionDirection:  string,
--::   selectionEnd:        integer,
--::   selectionStart:      integer,
--::   textLength:          integer,
--::   type:                string,
--::   validity:            ValidityState,
--::   value:               string,
--::   willValidate:        boolean,
--::   wrap:                string,
--::   checkValidity:       () -> boolean,
--::   reportValidity:      () -> boolean,
--::   select:              () -> (),
--::   setCustomValidity:   (string) -> (),
--::   setRangeText:        (string, integer | nil, integer | nil, string | nil) -> (),
--::   setSelectionRange:   (integer, integer, string | nil) -> (),
--::   ...
--:: }

--:: HTMLFormElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   getBoundingClientRect: () -> DOMRect,
--::   acceptCharset:       string,
--::   action:              string,
--::   autocomplete:        string,
--::   elements:            HTMLCollection,
--::   encoding:            string,
--::   enctype:             string,
--::   length:              integer,
--::   method:              string,
--::   name:                string,
--::   noValidate:          boolean,
--::   target:              string,
--::   checkValidity:       () -> boolean,
--::   reportValidity:      () -> boolean,
--::   requestSubmit:       (HTMLElement | nil) -> (),
--::   reset:               () -> (),
--::   submit:              () -> (),
--::   [integer]:           HTMLElement,
--::   [string]:            HTMLElement,
--::   ...
--:: }

--:: ValidityState = {
--::   badInput:        boolean,
--::   customError:     boolean,
--::   patternMismatch: boolean,
--::   rangeOverflow:   boolean,
--::   rangeUnderflow:  boolean,
--::   stepMismatch:    boolean,
--::   tooLong:         boolean,
--::   tooShort:        boolean,
--::   typeMismatch:    boolean,
--::   valid:           boolean,
--::   valueMissing:    boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Canvas API
---------------------------------------------------------------------------

--:: HTMLCanvasElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   getBoundingClientRect: () -> DOMRect,
--::   width:               integer,
--::   height:              integer,
--::   getContext:          (string) -> CanvasRenderingContext2D | unknown,
--::   toDataURL:           (string | nil, number | nil) -> string,
--::   toBlob:              ((Blob | nil) -> (), string | nil, number | nil) -> (),
--::   transferControlToOffscreen: () -> unknown,
--::   ...
--:: }

--:: CanvasRenderingContext2D = {
--::   canvas:                  HTMLCanvasElement,
--::   fillStyle:               string,
--::   strokeStyle:             string,
--::   globalAlpha:             number,
--::   globalCompositeOperation: string,
--::   lineWidth:               number,
--::   lineCap:                 string,
--::   lineJoin:                string,
--::   miterLimit:              number,
--::   lineDashOffset:          number,
--::   shadowOffsetX:           number,
--::   shadowOffsetY:           number,
--::   shadowBlur:              number,
--::   shadowColor:             string,
--::   filter:                  string,
--::   imageSmoothingEnabled:   boolean,
--::   imageSmoothingQuality:   string,
--::   font:                    string,
--::   textAlign:               string,
--::   textBaseline:            string,
--::   direction:               string,
--::   save:             () -> (),
--::   restore:          () -> (),
--::   scale:            (number, number) -> (),
--::   rotate:           (number) -> (),
--::   translate:        (number, number) -> (),
--::   transform:        (number, number, number, number, number, number) -> (),
--::   setTransform:     (number, number, number, number, number, number) -> (),
--::   resetTransform:   () -> (),
--::   getTransform:     () -> unknown,
--::   createLinearGradient: (number, number, number, number) -> CanvasGradient,
--::   createRadialGradient: (number, number, number, number, number, number) -> CanvasGradient,
--::   createConicGradient:  (number, number, number) -> CanvasGradient,
--::   createPattern:    (unknown, string | nil) -> CanvasPattern | nil,
--::   clearRect:        (number, number, number, number) -> (),
--::   fillRect:         (number, number, number, number) -> (),
--::   strokeRect:       (number, number, number, number) -> (),
--::   fillText:         (string, number, number, number | nil) -> (),
--::   strokeText:       (string, number, number, number | nil) -> (),
--::   measureText:      (string) -> TextMetrics,
--::   drawImage:        (unknown, number, number, number | nil, number | nil, number | nil, number | nil, number | nil, number | nil) -> (),
--::   createImageData:  (integer, integer) -> ImageData,
--::   getImageData:     (integer, integer, integer, integer) -> ImageData,
--::   putImageData:     (ImageData, integer, integer, integer | nil, integer | nil, integer | nil, integer | nil) -> (),
--::   beginPath:        () -> (),
--::   closePath:        () -> (),
--::   moveTo:           (number, number) -> (),
--::   lineTo:           (number, number) -> (),
--::   bezierCurveTo:    (number, number, number, number, number, number) -> (),
--::   quadraticCurveTo: (number, number, number, number) -> (),
--::   arc:              (number, number, number, number, number, boolean | nil) -> (),
--::   arcTo:            (number, number, number, number, number) -> (),
--::   ellipse:          (number, number, number, number, number, number, number, boolean | nil) -> (),
--::   rect:             (number, number, number, number) -> (),
--::   fill:             (string | nil) -> (),
--::   stroke:           () -> (),
--::   clip:             (string | nil) -> (),
--::   isPointInPath:    (number, number, string | nil) -> boolean,
--::   isPointInStroke:  (number, number) -> boolean,
--::   setLineDash:      ({ [integer]: number, ... }) -> (),
--::   getLineDash:      () -> { [integer]: number, ... },
--::   drawFocusIfNeeded: (Element) -> (),
--::   ...
--:: }

--:: CanvasGradient = {
--::   addColorStop: (number, string) -> (),
--::   ...
--:: }

--:: CanvasPattern = {
--::   setTransform: (unknown | nil) -> (),
--::   ...
--:: }

--:: TextMetrics = {
--::   width:                    number,
--::   actualBoundingBoxLeft:    number,
--::   actualBoundingBoxRight:   number,
--::   fontBoundingBoxAscent:    number,
--::   fontBoundingBoxDescent:   number,
--::   actualBoundingBoxAscent:  number,
--::   actualBoundingBoxDescent: number,
--::   emHeightAscent:           number,
--::   emHeightDescent:          number,
--::   hangingBaseline:          number,
--::   alphabeticBaseline:       number,
--::   ideographicBaseline:      number,
--::   ...
--:: }

--:: ImageData = {
--::   data:   unknown,
--::   width:  integer,
--::   height: integer,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Media elements
---------------------------------------------------------------------------

--:: TimeRanges = {
--::   length: integer,
--::   start:  (integer) -> number,
--::   end:    (integer) -> number,
--::   ...
--:: }

--:: HTMLMediaElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   getBoundingClientRect: () -> DOMRect,
--::   autoplay:            boolean,
--::   buffered:            TimeRanges,
--::   controls:            boolean,
--::   crossOrigin:         string | nil,
--::   currentSrc:          string,
--::   currentTime:         number,
--::   defaultMuted:        boolean,
--::   defaultPlaybackRate: number,
--::   disableRemotePlayback: boolean,
--::   duration:            number,
--::   ended:               boolean,
--::   error:               unknown,
--::   loop:                boolean,
--::   mediaKeys:           unknown,
--::   muted:               boolean,
--::   networkState:        integer,
--::   paused:              boolean,
--::   playbackRate:        number,
--::   played:              TimeRanges,
--::   preload:             string,
--::   preservesPitch:      boolean,
--::   readyState:          integer,
--::   seekable:            TimeRanges,
--::   seeking:             boolean,
--::   src:                 string,
--::   srcObject:           unknown,
--::   textTracks:          unknown,
--::   videoTracks:         unknown,
--::   volume:              number,
--::   canPlayType:         (string) -> string,
--::   fastSeek:            (number) -> (),
--::   load:                () -> (),
--::   pause:               () -> (),
--::   play:                () -> Promise,
--::   ...
--:: }

--:: HTMLVideoElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   getBoundingClientRect: () -> DOMRect,
--::   autoplay:            boolean,
--::   buffered:            TimeRanges,
--::   controls:            boolean,
--::   crossOrigin:         string | nil,
--::   currentSrc:          string,
--::   currentTime:         number,
--::   defaultMuted:        boolean,
--::   defaultPlaybackRate: number,
--::   duration:            number,
--::   ended:               boolean,
--::   loop:                boolean,
--::   muted:               boolean,
--::   networkState:        integer,
--::   paused:              boolean,
--::   playbackRate:        number,
--::   played:              TimeRanges,
--::   preload:             string,
--::   readyState:          integer,
--::   seekable:            TimeRanges,
--::   seeking:             boolean,
--::   src:                 string,
--::   volume:              number,
--::   canPlayType:         (string) -> string,
--::   load:                () -> (),
--::   pause:               () -> (),
--::   play:                () -> Promise,
--::   height:              integer,
--::   width:               integer,
--::   videoHeight:         integer,
--::   videoWidth:          integer,
--::   poster:              string,
--::   playsInline:         boolean,
--::   requestPictureInPicture: () -> Promise,
--::   ...
--:: }

--:: HTMLAudioElement = {
--::   parentNode:         Node | nil,
--::   childNodes:         { [integer]: Node, length: integer, ... },
--::   textContent:        string | nil,
--::   nodeType:           integer,
--::   nodeName:           string,
--::   ownerDocument:      Document | nil,
--::   appendChild:        (Node) -> Node,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   tagName:             string,
--::   id:                  string,
--::   className:           string,
--::   classList:           DOMTokenList,
--::   dataset:             { [string]: string, ... },
--::   style:               CSSStyleDeclaration,
--::   getAttribute:        (string) -> string | nil,
--::   setAttribute:        (string, string) -> (),
--::   autoplay:            boolean,
--::   buffered:            TimeRanges,
--::   controls:            boolean,
--::   currentSrc:          string,
--::   currentTime:         number,
--::   duration:            number,
--::   ended:               boolean,
--::   loop:                boolean,
--::   muted:               boolean,
--::   paused:              boolean,
--::   playbackRate:        number,
--::   src:                 string,
--::   volume:              number,
--::   canPlayType:         (string) -> string,
--::   load:                () -> (),
--::   pause:               () -> (),
--::   play:                () -> Promise,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Text: Node
---------------------------------------------------------------------------

--:: Text = {
--::   parentNode:     Node | nil,
--::   parentElement:  Element | nil,
--::   childNodes:     { [integer]: Node, length: integer, ... },
--::   textContent:    string | nil,
--::   nodeType:       integer,
--::   nodeName:       string,
--::   nodeValue:      string | nil,
--::   baseURI:        string,
--::   isConnected:    boolean,
--::   ownerDocument:  Document | nil,
--::   appendChild:    (Node) -> Node,
--::   removeChild:    (Node) -> Node,
--::   insertBefore:   (Node, Node | nil) -> Node,
--::   cloneNode:      (boolean | nil) -> Text,
--::   contains:       (Node | nil) -> boolean,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   data:           string,
--::   length:         integer,
--::   wholeText:      string,
--::   splitText:      (integer) -> Text,
--::   appendData:     (string) -> (),
--::   deleteData:     (integer, integer) -> (),
--::   insertData:     (integer, string) -> (),
--::   replaceData:    (integer, integer, string) -> (),
--::   substringData:  (integer, integer) -> string,
--::   ...
--:: }

---------------------------------------------------------------------------
-- DocumentFragment: Node
---------------------------------------------------------------------------

--:: DocumentFragment = {
--::   parentNode:    Node | nil,
--::   childNodes:    { [integer]: Node, length: integer, ... },
--::   textContent:   string | nil,
--::   nodeType:      integer,
--::   nodeName:      string,
--::   ownerDocument: Document | nil,
--::   appendChild:   (Node) -> Node,
--::   removeChild:   (Node) -> Node,
--::   insertBefore:  (Node, Node | nil) -> Node,
--::   cloneNode:     (boolean | nil) -> DocumentFragment,
--::   contains:      (Node | nil) -> boolean,
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   querySelector:       (string) -> Element | nil,
--::   querySelectorAll:    (string) -> NodeList,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Document
---------------------------------------------------------------------------

--:: Document = {
--::   createElement:              (string) -> HTMLElement,
--::   createElementNS:            (string | nil, string) -> Element,
--::   createTextNode:             (string) -> Text,
--::   createDocumentFragment:     () -> DocumentFragment,
--::   createComment:              (string) -> unknown,
--::   createEvent:                (string) -> Event,
--::   createRange:                () -> unknown,
--::   querySelector:              (string) -> Element | nil,
--::   querySelectorAll:           (string) -> NodeList,
--::   getElementById:             (string) -> HTMLElement | nil,
--::   getElementsByClassName:     (string) -> HTMLCollection,
--::   getElementsByTagName:       (string) -> HTMLCollection,
--::   getElementsByName:          (string) -> NodeList,
--::   importNode:                 (Node, boolean | nil) -> Node,
--::   adoptNode:                  (Node) -> Node,
--::   body:                       HTMLElement | nil,
--::   head:                       HTMLElement | nil,
--::   title:                      string,
--::   URL:                        string,
--::   documentURI:                string,
--::   characterSet:               string,
--::   contentType:                string,
--::   doctype:                    unknown,
--::   documentElement:            HTMLElement,
--::   readyState:                 string,
--::   referrer:                   string,
--::   cookie:                     string,
--::   lastModified:               string,
--::   location:                   Location,
--::   domain:                     string,
--::   hidden:                     boolean,
--::   visibilityState:            string,
--::   activeElement:              Element | nil,
--::   fullscreenElement:          Element | nil,
--::   fullscreenEnabled:          boolean,
--::   pointerLockElement:         Element | nil,
--::   scrollingElement:           Element | nil,
--::   children:                   HTMLCollection,
--::   childElementCount:          integer,
--::   firstElementChild:          Element | nil,
--::   lastElementChild:           Element | nil,
--::   implementation:             unknown,
--::   styleSheets:                unknown,
--::   fonts:                      unknown,
--::   timeline:                   unknown,
--::   defaultView:                Window | nil,
--::   designMode:                 string,
--::   dir:                        string,
--::   compatMode:                 string,
--::   currentScript:              HTMLElement | nil,
--::   hasFocus:                   () -> boolean,
--::   execCommand:                (string, boolean | nil, string | nil) -> boolean,
--::   exitFullscreen:             () -> Promise,
--::   exitPointerLock:            () -> (),
--::   addEventListener:           (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener:        (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:              (Event) -> boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Location
---------------------------------------------------------------------------

--:: Location = {
--::   href:       string,
--::   protocol:   string,
--::   host:       string,
--::   hostname:   string,
--::   port:       string,
--::   pathname:   string,
--::   search:     string,
--::   hash:       string,
--::   origin:     string,
--::   assign:     (string) -> (),
--::   replace:    (string) -> (),
--::   reload:     () -> (),
--::   toString:   () -> string,
--::   ...
--:: }

---------------------------------------------------------------------------
-- History
---------------------------------------------------------------------------

--:: History = {
--::   length:            integer,
--::   scrollRestoration: string,
--::   state:             unknown,
--::   pushState:         (unknown, string, string | nil) -> (),
--::   replaceState:      (unknown, string, string | nil) -> (),
--::   go:                (integer | nil) -> (),
--::   back:              () -> (),
--::   forward:           () -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- URL, URLSearchParams
---------------------------------------------------------------------------

--:: URLSearchParams = {
--::   append:   (string, string) -> (),
--::   delete:   (string) -> (),
--::   get:      (string) -> string | nil,
--::   getAll:   (string) -> { [integer]: string, ... },
--::   has:      (string) -> boolean,
--::   set:      (string, string) -> (),
--::   sort:     () -> (),
--::   toString: () -> string,
--::   forEach:  ((string, string, URLSearchParams) -> ()) -> (),
--::   ...
--:: }

--:: URL = {
--::   hash:         string,
--::   host:         string,
--::   hostname:     string,
--::   href:         string,
--::   origin:       string,
--::   password:     string,
--::   pathname:     string,
--::   port:         string,
--::   protocol:     string,
--::   search:       string,
--::   searchParams: URLSearchParams,
--::   username:     string,
--::   toJSON:       () -> string,
--::   toString:     () -> string,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Storage (localStorage / sessionStorage)
---------------------------------------------------------------------------

--:: Storage = {
--::   length:     integer,
--::   key:        (integer) -> string | nil,
--::   getItem:    (string) -> string | nil,
--::   setItem:    (string, string) -> (),
--::   removeItem: (string) -> (),
--::   clear:      () -> (),
--::   [string]:   string | nil,
--::   ...
--:: }

---------------------------------------------------------------------------
-- XMLHttpRequest
---------------------------------------------------------------------------

--:: XMLHttpRequest = {
--::   readyState:          integer,
--::   response:            unknown,
--::   responseText:        string,
--::   responseType:        string,
--::   responseURL:         string,
--::   responseXML:         unknown,
--::   status:              integer,
--::   statusText:          string,
--::   timeout:             integer,
--::   upload:              unknown,
--::   withCredentials:     boolean,
--::   abort:               () -> (),
--::   getAllResponseHeaders: () -> string,
--::   getResponseHeader:   (string) -> string | nil,
--::   open:                (string, string, boolean | nil, string | nil, string | nil) -> (),
--::   overrideMimeType:    (string) -> (),
--::   send:                (unknown) -> (),
--::   setRequestHeader:    (string, string) -> (),
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Fetch API
---------------------------------------------------------------------------

--:: Headers = {
--::   append:   (string, string) -> (),
--::   delete:   (string) -> (),
--::   entries:  () -> unknown,
--::   get:      (string) -> string | nil,
--::   getSetCookie: () -> { [integer]: string, ... },
--::   has:      (string) -> boolean,
--::   keys:     () -> unknown,
--::   set:      (string, string) -> (),
--::   values:   () -> unknown,
--::   forEach:  ((string, string, Headers) -> ()) -> (),
--::   ...
--:: }

--:: Request = {
--::   body:             unknown,
--::   bodyUsed:         boolean,
--::   cache:            string,
--::   credentials:      string,
--::   destination:      string,
--::   headers:          Headers,
--::   integrity:        string,
--::   keepalive:        boolean,
--::   method:           string,
--::   mode:             string,
--::   redirect:         string,
--::   referrer:         string,
--::   referrerPolicy:   string,
--::   signal:           AbortSignal,
--::   url:              string,
--::   arrayBuffer:      () -> Promise,
--::   blob:             () -> Promise,
--::   clone:            () -> Request,
--::   formData:         () -> Promise,
--::   json:             () -> Promise,
--::   text:             () -> Promise,
--::   ...
--:: }

--:: Response = {
--::   body:         unknown,
--::   bodyUsed:     boolean,
--::   headers:      Headers,
--::   ok:           boolean,
--::   redirected:   boolean,
--::   status:       integer,
--::   statusText:   string,
--::   type:         string,
--::   url:          string,
--::   arrayBuffer:  () -> Promise,
--::   blob:         () -> Promise,
--::   clone:        () -> Response,
--::   formData:     () -> Promise,
--::   json:         () -> Promise,
--::   text:         () -> Promise,
--::   ...
--:: }

-- Promises are opaque; browser Promises resolve via callbacks/then, not coroutines.
--:: Promise = {
--::   andThen:  ((unknown) -> unknown, ((unknown) -> unknown) | nil) -> Promise,
--::   catch:    ((unknown) -> unknown) -> Promise,
--::   finally:  (() -> ()) -> Promise,
--::   ...
--:: }

---------------------------------------------------------------------------
-- WebSocket
---------------------------------------------------------------------------

--:: WebSocket = {
--::   binaryType:      string,
--::   bufferedAmount:  integer,
--::   extensions:      string,
--::   protocol:        string,
--::   readyState:      integer,
--::   url:             string,
--::   close:           (integer | nil, string | nil) -> (),
--::   send:            (unknown) -> (),
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Worker, MessagePort, BroadcastChannel
---------------------------------------------------------------------------

--:: MessagePort = {
--::   postMessage:         (unknown, unknown | nil) -> (),
--::   start:               () -> (),
--::   close:               () -> (),
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

--:: Worker = {
--::   postMessage:         (unknown, unknown | nil) -> (),
--::   terminate:           () -> (),
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

--:: BroadcastChannel = {
--::   name:                string,
--::   postMessage:         (unknown) -> (),
--::   close:               () -> (),
--::   addEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener: (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:       (Event) -> boolean,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Observers
---------------------------------------------------------------------------

--:: MutationRecord = {
--::   type:               string,
--::   target:             Node,
--::   addedNodes:         NodeList,
--::   removedNodes:       NodeList,
--::   previousSibling:    Node | nil,
--::   nextSibling:        Node | nil,
--::   attributeName:      string | nil,
--::   attributeNamespace: string | nil,
--::   oldValue:           string | nil,
--::   ...
--:: }

--:: MutationObserver = {
--::   observe:    (Node, unknown) -> (),
--::   disconnect: () -> (),
--::   takeRecords: () -> { [integer]: MutationRecord, ... },
--::   ...
--:: }

--:: IntersectionObserverEntry = {
--::   boundingClientRect:  DOMRect,
--::   intersectionRatio:   number,
--::   intersectionRect:    DOMRect,
--::   isIntersecting:      boolean,
--::   rootBounds:          DOMRect | nil,
--::   target:              Element,
--::   time:                number,
--::   ...
--:: }

--:: IntersectionObserver = {
--::   root:       Element | Document | nil,
--::   rootMargin: string,
--::   thresholds: { [integer]: number, ... },
--::   disconnect: () -> (),
--::   observe:    (Element) -> (),
--::   takeRecords: () -> { [integer]: IntersectionObserverEntry, ... },
--::   unobserve:  (Element) -> (),
--::   ...
--:: }

--:: ResizeObserverEntry = {
--::   borderBoxSize:       { [integer]: unknown, ... },
--::   contentBoxSize:      { [integer]: unknown, ... },
--::   contentRect:         DOMRect,
--::   devicePixelContentBoxSize: { [integer]: unknown, ... },
--::   target:              Element,
--::   ...
--:: }

--:: ResizeObserver = {
--::   disconnect: () -> (),
--::   observe:    (Element, unknown | nil) -> (),
--::   unobserve:  (Element) -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- Performance API
---------------------------------------------------------------------------

--:: PerformanceEntry = {
--::   duration:   number,
--::   entryType:  string,
--::   name:       string,
--::   startTime:  number,
--::   toJSON:     () -> unknown,
--::   ...
--:: }

--:: Performance = {
--::   timeOrigin:          number,
--::   navigation:          unknown,
--::   timing:              unknown,
--::   eventCounts:         unknown,
--::   now:                 () -> number,
--::   clearMarks:          (string | nil) -> (),
--::   clearMeasures:       (string | nil) -> (),
--::   clearResourceTimings: () -> (),
--::   getEntries:          () -> { [integer]: PerformanceEntry, ... },
--::   getEntriesByName:    (string, string | nil) -> { [integer]: PerformanceEntry, ... },
--::   getEntriesByType:    (string) -> { [integer]: PerformanceEntry, ... },
--::   mark:                (string) -> PerformanceEntry,
--::   measure:             (string, string | nil, string | nil) -> PerformanceEntry,
--::   setResourceTimingBufferSize: (integer) -> (),
--::   toJSON:              () -> unknown,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Console
---------------------------------------------------------------------------

--:: Console = {
--::   log:          (...any) -> (),
--::   info:         (...any) -> (),
--::   warn:         (...any) -> (),
--::   error:        (...any) -> (),
--::   debug:        (...any) -> (),
--::   trace:        (...any) -> (),
--::   dir:          (any, any | nil) -> (),
--::   dirxml:       (...any) -> (),
--::   table:        (any, any | nil) -> (),
--::   group:        (...any) -> (),
--::   groupCollapsed: (...any) -> (),
--::   groupEnd:     () -> (),
--::   count:        (string | nil) -> (),
--::   countReset:   (string | nil) -> (),
--::   time:         (string | nil) -> (),
--::   timeLog:      (string | nil, ...any) -> (),
--::   timeEnd:      (string | nil) -> (),
--::   assert:       (boolean, ...any) -> (),
--::   clear:        () -> (),
--::   profile:      (string | nil) -> (),
--::   profileEnd:   (string | nil) -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- Navigator
---------------------------------------------------------------------------

--:: Navigator = {
--::   appCodeName:        string,
--::   appName:            string,
--::   appVersion:         string,
--::   connection:         unknown,
--::   cookieEnabled:      boolean,
--::   credentials:        unknown,
--::   deviceMemory:       number,
--::   doNotTrack:         string | nil,
--::   geolocation:        unknown,
--::   hardwareConcurrency: integer,
--::   language:           string,
--::   languages:          { [integer]: string, ... },
--::   locks:              unknown,
--::   maxTouchPoints:     integer,
--::   mediaCapabilities:  unknown,
--::   mediaDevices:       unknown,
--::   mediaSession:       unknown,
--::   onLine:             boolean,
--::   pdfViewerEnabled:   boolean,
--::   permissions:        unknown,
--::   platform:           string,
--::   plugins:            unknown,
--::   product:            string,
--::   productSub:         string,
--::   scheduling:         unknown,
--::   serviceWorker:      unknown,
--::   storage:            unknown,
--::   userActivation:     unknown,
--::   userAgent:          string,
--::   userAgentData:      unknown,
--::   vendor:             string,
--::   vendorSub:          string,
--::   vibrate:            (unknown) -> boolean,
--::   sendBeacon:         (string, unknown | nil) -> boolean,
--::   canShare:           (unknown | nil) -> boolean,
--::   clipboard:          unknown,
--::   share:              (unknown | nil) -> Promise,
--::   ...
--:: }

---------------------------------------------------------------------------
-- Screen
---------------------------------------------------------------------------

--:: Screen = {
--::   availHeight:    integer,
--::   availWidth:     integer,
--::   colorDepth:     integer,
--::   height:         integer,
--::   orientation:    unknown,
--::   pixelDepth:     integer,
--::   width:          integer,
--::   ...
--:: }

---------------------------------------------------------------------------
-- ReadableStream
---------------------------------------------------------------------------

--:: ReadableStream = {
--::   locked:   boolean,
--::   cancel:   (unknown | nil) -> Promise,
--::   getReader: () -> unknown,
--::   pipeThrough: (unknown, unknown | nil) -> ReadableStream,
--::   pipeTo:   (unknown, unknown | nil) -> Promise,
--::   tee:      () -> { [integer]: ReadableStream, ... },
--::   ...
--:: }

---------------------------------------------------------------------------
-- FormData
---------------------------------------------------------------------------

--:: FormData = {
--::   append:   (string, unknown, string | nil) -> (),
--::   delete:   (string) -> (),
--::   entries:  () -> unknown,
--::   get:      (string) -> unknown,
--::   getAll:   (string) -> { [integer]: unknown, ... },
--::   has:      (string) -> boolean,
--::   keys:     () -> unknown,
--::   set:      (string, unknown, string | nil) -> (),
--::   values:   () -> unknown,
--::   forEach:  ((unknown, string, FormData) -> ()) -> (),
--::   ...
--:: }

---------------------------------------------------------------------------
-- Window / globals
---------------------------------------------------------------------------

--:: Window = {
--::   setTimeout:             ((any) -> (), integer, ...any) -> integer,
--::   clearTimeout:           (integer) -> (),
--::   setInterval:            ((any) -> (), integer, ...any) -> integer,
--::   clearInterval:          (integer) -> (),
--::   requestAnimationFrame:  ((number) -> ()) -> integer,
--::   cancelAnimationFrame:   (integer) -> (),
--::   queueMicrotask:         (() -> ()) -> (),
--::   location:               Location,
--::   history:                History,
--::   document:               Document,
--::   navigator:              Navigator,
--::   screen:                 Screen,
--::   performance:            Performance,
--::   console:                Console,
--::   localStorage:           Storage,
--::   sessionStorage:         Storage,
--::   innerWidth:             integer,
--::   innerHeight:            integer,
--::   outerWidth:             integer,
--::   outerHeight:            integer,
--::   scrollX:                number,
--::   scrollY:                number,
--::   pageXOffset:            number,
--::   pageYOffset:            number,
--::   screenX:                integer,
--::   screenY:                integer,
--::   devicePixelRatio:       number,
--::   name:                   string,
--::   status:                 string,
--::   closed:                 boolean,
--::   parent:                 Window,
--::   top:                    Window | nil,
--::   opener:                 Window | nil,
--::   self:                   Window,
--::   window:                 Window,
--::   frames:                 Window,
--::   frameElement:           Element | nil,
--::   length:                 integer,
--::   origin:                 string,
--::   crossOriginIsolated:    boolean,
--::   isSecureContext:        boolean,
--::   crypto:                 unknown,
--::   indexedDB:              unknown,
--::   caches:                 unknown,
--::   fetch:                  (unknown, unknown | nil) -> Promise,
--::   alert:                  (string | nil) -> (),
--::   confirm:                (string | nil) -> boolean,
--::   prompt:                 (string | nil, string | nil) -> string | nil,
--::   open:                   (string | nil, string | nil, string | nil) -> Window | nil,
--::   close:                  () -> (),
--::   stop:                   () -> (),
--::   focus:                  () -> (),
--::   blur:                   () -> (),
--::   scroll:                 (number | nil, number | nil) -> (),
--::   scrollTo:               (number | nil, number | nil) -> (),
--::   scrollBy:               (number | nil, number | nil) -> (),
--::   getComputedStyle:       (Element, string | nil) -> CSSStyleDeclaration,
--::   getSelection:           () -> unknown,
--::   matchMedia:             (string) -> unknown,
--::   resizeTo:               (integer, integer) -> (),
--::   resizeBy:               (integer, integer) -> (),
--::   moveTo:                 (integer, integer) -> (),
--::   moveBy:                 (integer, integer) -> (),
--::   postMessage:            (unknown, string, unknown | nil) -> (),
--::   atob:                   (string) -> string,
--::   btoa:                   (string) -> string,
--::   addEventListener:       (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   removeEventListener:    (string, (AnyEvent) -> (), boolean | nil) -> (),
--::   dispatchEvent:          (Event) -> boolean,
--::   ...
--:: }

--:: declare document  = Document
--:: declare window    = Window
--:: declare navigator = Navigator
--:: declare screen    = Screen
--:: declare location  = Location
--:: declare history   = History
--:: declare performance = Performance
--:: declare console   = Console
--:: declare localStorage   = Storage
--:: declare sessionStorage  = Storage
