if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local queue = require("lib.queue")

-- ============================================================================
-- Priority Queue (min-heap)
-- ============================================================================

T.describe("priority_new: basic push/pop order", function()
  T.it("pops in ascending order (min-heap)", function()
    local pq = queue.priority_new()
    pq:push(5)
    pq:push(3)
    pq:push(7)
    pq:push(1)
    pq:push(9)
    T.eq(pq:pop(), 1)
    T.eq(pq:pop(), 3)
    T.eq(pq:pop(), 5)
    T.eq(pq:pop(), 7)
    T.eq(pq:pop(), 9)
  end)

  T.it("pop on empty returns nil", function()
    local pq = queue.priority_new()
    T.eq(pq:pop(), nil)
  end)

  T.it("single element push/pop", function()
    local pq = queue.priority_new()
    pq:push(42)
    T.eq(pq:pop(), 42)
    T.eq(pq:pop(), nil)
  end)
end)

T.describe("priority_new: peek", function()
  T.it("peek returns top without removing", function()
    local pq = queue.priority_new()
    pq:push(10)
    pq:push(2)
    pq:push(8)
    T.eq(pq:peek(), 2)
    T.eq(pq:size(), 3)
    T.eq(pq:peek(), 2)  -- still there
  end)

  T.it("peek on empty returns nil", function()
    local pq = queue.priority_new()
    T.eq(pq:peek(), nil)
  end)
end)

T.describe("priority_new: size and is_empty", function()
  T.it("tracks size correctly", function()
    local pq = queue.priority_new()
    T.eq(pq:size(), 0)
    T.ok(pq:is_empty())
    pq:push(1)
    T.eq(pq:size(), 1)
    T.ok(not pq:is_empty())
    pq:push(2)
    T.eq(pq:size(), 2)
    pq:pop()
    T.eq(pq:size(), 1)
    pq:pop()
    T.eq(pq:size(), 0)
    T.ok(pq:is_empty())
  end)
end)

T.describe("priority_new: custom comparator (max-heap)", function()
  T.it("pops in descending order", function()
    local pq = queue.priority_new(function(a, b) return a > b end)
    pq:push(5)
    pq:push(3)
    pq:push(7)
    pq:push(1)
    pq:push(9)
    T.eq(pq:pop(), 9)
    T.eq(pq:pop(), 7)
    T.eq(pq:pop(), 5)
    T.eq(pq:pop(), 3)
    T.eq(pq:pop(), 1)
  end)
end)

T.describe("priority_new: priority pairs", function()
  T.it("sorts by first element of pair", function()
    local pq = queue.priority_new(function(a, b) return a[1] < b[1] end)
    pq:push({10, "high priority"})
    pq:push({1,  "low priority"})
    pq:push({5,  "mid priority"})
    local top = pq:pop()
    T.eq(top[1], 1)
    T.eq(top[2], "low priority")
    local mid = pq:pop()
    T.eq(mid[1], 5)
    local last = pq:pop()
    T.eq(last[1], 10)
  end)
end)

T.describe("priority_new: push_all", function()
  T.it("pushes all values and heap property holds", function()
    local pq = queue.priority_new()
    pq:push_all({8, 2, 4, 6, 1, 9, 3})
    T.eq(pq:size(), 7)
    local prev = -math.huge
    -- pop-all should give ascending order
    local ok = true
    for _ = 1, 7 do
      local v = pq:pop()
      if v < prev then ok = false end
      prev = v
    end
    T.ok(ok, "expected ascending order")
  end)

  T.it("push_all on empty array is a no-op", function()
    local pq = queue.priority_new()
    pq:push_all({})
    T.eq(pq:size(), 0)
  end)
end)

T.describe("priority_new: interleaved push/pop", function()
  T.it("heap property maintained across interleaved ops", function()
    local pq = queue.priority_new()
    pq:push(5)
    pq:push(3)
    T.eq(pq:pop(), 3)
    pq:push(1)
    pq:push(4)
    T.eq(pq:pop(), 1)
    T.eq(pq:pop(), 4)
    T.eq(pq:pop(), 5)
    T.ok(pq:is_empty())
  end)
end)

-- ============================================================================
-- heapify
-- ============================================================================

T.describe("heapify", function()
  T.it("builds correct min-heap from unsorted array", function()
    local pq = queue.heapify({5, 3, 7, 1, 9, 2})
    T.eq(pq:pop(), 1)
    T.eq(pq:pop(), 2)
    T.eq(pq:pop(), 3)
    T.eq(pq:pop(), 5)
    T.eq(pq:pop(), 7)
    T.eq(pq:pop(), 9)
  end)

  T.it("does not modify source array", function()
    local src = {5, 3, 7, 1}
    queue.heapify(src)
    T.eq(src[1], 5)
    T.eq(src[2], 3)
    T.eq(src[3], 7)
    T.eq(src[4], 1)
  end)

  T.it("single-element array", function()
    local pq = queue.heapify({42})
    T.eq(pq:pop(), 42)
    T.eq(pq:pop(), nil)
  end)

  T.it("empty array", function()
    local pq = queue.heapify({})
    T.ok(pq:is_empty())
    T.eq(pq:pop(), nil)
  end)

  T.it("custom comparator (max-heap)", function()
    local pq = queue.heapify({5, 3, 7, 1, 9}, function(a, b) return a > b end)
    T.eq(pq:pop(), 9)
    T.eq(pq:pop(), 7)
    T.eq(pq:pop(), 5)
  end)
end)

-- ============================================================================
-- heapsort
-- ============================================================================

T.describe("heapsort", function()
  T.it("sorts ascending by default", function()
    local sorted = queue.heapsort({5, 3, 7, 1, 9})
    T.eq(sorted[1], 1)
    T.eq(sorted[2], 3)
    T.eq(sorted[3], 5)
    T.eq(sorted[4], 7)
    T.eq(sorted[5], 9)
  end)

  T.it("does not modify source array", function()
    local src = {5, 3, 7, 1}
    queue.heapsort(src)
    T.eq(src[1], 5)
    T.eq(src[2], 3)
    T.eq(src[3], 7)
    T.eq(src[4], 1)
  end)

  T.it("empty array returns empty", function()
    local sorted = queue.heapsort({})
    T.eq(#sorted, 0)
  end)

  T.it("single element", function()
    local sorted = queue.heapsort({42})
    T.eq(#sorted, 1)
    T.eq(sorted[1], 42)
  end)

  T.it("already sorted array", function()
    local sorted = queue.heapsort({1, 2, 3, 4, 5})
    T.eq(sorted[1], 1)
    T.eq(sorted[5], 5)
  end)

  T.it("reverse sorted array", function()
    local sorted = queue.heapsort({9, 7, 5, 3, 1})
    T.eq(sorted[1], 1)
    T.eq(sorted[5], 9)
  end)

  T.it("custom comparator (descending)", function()
    local sorted = queue.heapsort({5, 3, 7, 1, 9}, function(a, b) return a > b end)
    T.eq(sorted[1], 9)
    T.eq(sorted[2], 7)
    T.eq(sorted[3], 5)
    T.eq(sorted[4], 3)
    T.eq(sorted[5], 1)
  end)

  T.it("duplicate values", function()
    local sorted = queue.heapsort({3, 1, 4, 1, 5, 9, 2, 6})
    T.eq(sorted[1], 1)
    T.eq(sorted[2], 1)
    T.eq(sorted[3], 2)
    T.eq(sorted[4], 3)
  end)
end)

-- ============================================================================
-- FIFO Queue
-- ============================================================================

T.describe("queue.new: basic push/pop", function()
  T.it("FIFO order preserved", function()
    local q = queue.new()
    q:push(1)
    q:push(2)
    q:push(3)
    T.eq(q:pop(), 1)
    T.eq(q:pop(), 2)
    T.eq(q:pop(), 3)
  end)

  T.it("pop on empty returns nil", function()
    local q = queue.new()
    T.eq(q:pop(), nil)
  end)

  T.it("enqueue/dequeue aliases work", function()
    local q = queue.new()
    q:enqueue(10)
    q:enqueue(20)
    T.eq(q:dequeue(), 10)
    T.eq(q:dequeue(), 20)
    T.eq(q:dequeue(), nil)
  end)
end)

T.describe("queue.new: peek", function()
  T.it("peek returns front without removing", function()
    local q = queue.new()
    q:push(1)
    q:push(2)
    T.eq(q:peek(), 1)
    T.eq(q:size(), 2)
    T.eq(q:peek(), 1)
  end)

  T.it("peek on empty returns nil", function()
    local q = queue.new()
    T.eq(q:peek(), nil)
  end)
end)

T.describe("queue.new: size and is_empty", function()
  T.it("tracks size correctly", function()
    local q = queue.new()
    T.eq(q:size(), 0)
    T.ok(q:is_empty())
    q:push("a")
    T.eq(q:size(), 1)
    T.ok(not q:is_empty())
    q:push("b")
    T.eq(q:size(), 2)
    q:pop()
    T.eq(q:size(), 1)
    q:pop()
    T.eq(q:size(), 0)
    T.ok(q:is_empty())
  end)
end)

T.describe("queue.new: clear", function()
  T.it("empties the queue", function()
    local q = queue.new()
    q:push(1)
    q:push(2)
    q:push(3)
    q:clear()
    T.eq(q:size(), 0)
    T.ok(q:is_empty())
    T.eq(q:pop(), nil)
  end)

  T.it("can push after clear", function()
    local q = queue.new()
    q:push(1)
    q:clear()
    q:push(2)
    T.eq(q:pop(), 2)
  end)
end)

T.describe("queue.new: push_front / pop_back", function()
  T.it("push_front adds to front", function()
    local q = queue.new()
    q:push(2)
    q:push(3)
    q:push_front(1)
    T.eq(q:pop(), 1)
    T.eq(q:pop(), 2)
    T.eq(q:pop(), 3)
  end)

  T.it("pop_back removes from back", function()
    local q = queue.new()
    q:push(1)
    q:push(2)
    q:push(3)
    T.eq(q:pop_back(), 3)
    T.eq(q:pop_back(), 2)
    T.eq(q:pop_back(), 1)
    T.eq(q:pop_back(), nil)
  end)

  T.it("pop_back on empty returns nil", function()
    local q = queue.new()
    T.eq(q:pop_back(), nil)
  end)

  T.it("deque pattern: push front + pop front", function()
    local q = queue.new()
    q:push_front(3)
    q:push_front(2)
    q:push_front(1)
    T.eq(q:pop(), 1)
    T.eq(q:pop(), 2)
    T.eq(q:pop(), 3)
  end)

  T.it("deque pattern: push back + pop back (stack)", function()
    local q = queue.new()
    q:push(1)
    q:push(2)
    q:push(3)
    T.eq(q:pop_back(), 3)
    T.eq(q:pop_back(), 2)
    T.eq(q:pop_back(), 1)
  end)
end)

T.describe("queue.new: push_all", function()
  T.it("appends all in order", function()
    local q = queue.new()
    q:push(1)
    q:push_all({2, 3, 4})
    T.eq(q:pop(), 1)
    T.eq(q:pop(), 2)
    T.eq(q:pop(), 3)
    T.eq(q:pop(), 4)
  end)

  T.it("push_all on empty array is a no-op", function()
    local q = queue.new()
    q:push_all({})
    T.eq(q:size(), 0)
  end)
end)

T.describe("queue.new: to_array", function()
  T.it("snapshot in FIFO order", function()
    local q = queue.new()
    q:push(10)
    q:push(20)
    q:push(30)
    local arr = q:to_array()
    T.eq(#arr, 3)
    T.eq(arr[1], 10)
    T.eq(arr[2], 20)
    T.eq(arr[3], 30)
  end)

  T.it("to_array does not consume queue", function()
    local q = queue.new()
    q:push(1)
    q:push(2)
    q:to_array()
    T.eq(q:size(), 2)
    T.eq(q:pop(), 1)
  end)

  T.it("empty queue returns empty array", function()
    local q = queue.new()
    local arr = q:to_array()
    T.eq(#arr, 0)
  end)
end)

T.describe("queue.new: growth (ring-buffer wrap-around)", function()
  T.it("handles many pushes beyond initial capacity", function()
    local q = queue.new()
    -- Push more than initial cap (8) to force growth
    for i = 1, 20 do q:push(i) end
    T.eq(q:size(), 20)
    for i = 1, 20 do
      T.eq(q:pop(), i)
    end
    T.ok(q:is_empty())
  end)

  T.it("interleaved push/pop with wrap-around", function()
    local q = queue.new()
    -- Fill nearly to initial capacity, drain halfway, then fill again
    for i = 1, 6 do q:push(i) end
    for i = 1, 3 do q:pop() end  -- head wraps
    for i = 7, 20 do q:push(i) end  -- forces growth across wrap
    T.eq(q:pop(), 4)
    T.eq(q:pop(), 5)
    T.eq(q:pop(), 6)
    T.eq(q:pop(), 7)
  end)

  T.it("push_front with growth preserves order", function()
    local q = queue.new()
    for i = 1, 8 do q:push(i) end  -- fill to initial cap
    q:push_front(0)  -- triggers growth; queue is now [0,1,2,3,4,5,6,7,8]
    T.eq(q:size(), 9)
    T.eq(q:pop(), 0)   -- front
    T.eq(q:pop(), 1)   -- next
    T.eq(q:pop(), 2)   -- next
    -- drain the rest
    for i = 3, 8 do q:pop() end
    T.eq(q:size(), 0)
    T.ok(q:is_empty())
  end)
end)

-- ============================================================================
-- Fixed-capacity Ring Buffer
-- ============================================================================

T.describe("ring_new: capacity and basic ops", function()
  T.it("capacity returns the configured capacity", function()
    local rb = queue.ring_new(4)
    T.eq(rb:capacity(), 4)
  end)

  T.it("is_empty and size on fresh buffer", function()
    local rb = queue.ring_new(4)
    T.ok(rb:is_empty())
    T.eq(rb:size(), 0)
    T.ok(not rb:is_full())
  end)

  T.it("push/pop in FIFO order", function()
    local rb = queue.ring_new(4)
    rb:push(1)
    rb:push(2)
    rb:push(3)
    T.eq(rb:pop(), 1)
    T.eq(rb:pop(), 2)
    T.eq(rb:pop(), 3)
    T.eq(rb:pop(), nil)
  end)

  T.it("pop on empty returns nil", function()
    local rb = queue.ring_new(3)
    T.eq(rb:pop(), nil)
  end)
end)

T.describe("ring_new: peek", function()
  T.it("peek returns oldest without removing", function()
    local rb = queue.ring_new(4)
    rb:push(10)
    rb:push(20)
    T.eq(rb:peek(), 10)
    T.eq(rb:size(), 2)
    T.eq(rb:peek(), 10)
  end)

  T.it("peek on empty returns nil", function()
    local rb = queue.ring_new(2)
    T.eq(rb:peek(), nil)
  end)
end)

T.describe("ring_new: is_full and overwrite", function()
  T.it("is_full when at capacity", function()
    local rb = queue.ring_new(3)
    rb:push(1)
    rb:push(2)
    T.ok(not rb:is_full())
    rb:push(3)
    T.ok(rb:is_full())
  end)

  T.it("push when full overwrites oldest", function()
    local rb = queue.ring_new(4)
    rb:push(1)
    rb:push(2)
    rb:push(3)
    rb:push(4)
    T.ok(rb:is_full())
    rb:push(5)  -- overwrites 1
    T.eq(rb:size(), 4)
    T.eq(rb:pop(), 2)
    T.eq(rb:pop(), 3)
    T.eq(rb:pop(), 4)
    T.eq(rb:pop(), 5)
  end)

  T.it("multiple overwrites keep correct oldest", function()
    local rb = queue.ring_new(3)
    rb:push(1)
    rb:push(2)
    rb:push(3)
    rb:push(4)  -- overwrites 1
    rb:push(5)  -- overwrites 2
    T.eq(rb:size(), 3)
    T.eq(rb:pop(), 3)
    T.eq(rb:pop(), 4)
    T.eq(rb:pop(), 5)
    T.ok(rb:is_empty())
  end)
end)

T.describe("ring_new: to_array", function()
  T.it("returns elements in oldest-to-newest order", function()
    local rb = queue.ring_new(4)
    rb:push(10)
    rb:push(20)
    rb:push(30)
    local arr = rb:to_array()
    T.eq(#arr, 3)
    T.eq(arr[1], 10)
    T.eq(arr[2], 20)
    T.eq(arr[3], 30)
  end)

  T.it("to_array after overflow shows correct order", function()
    local rb = queue.ring_new(4)
    rb:push(1)
    rb:push(2)
    rb:push(3)
    rb:push(4)
    rb:push(5)  -- overwrites 1
    local arr = rb:to_array()
    T.eq(#arr, 4)
    T.eq(arr[1], 2)
    T.eq(arr[2], 3)
    T.eq(arr[3], 4)
    T.eq(arr[4], 5)
  end)

  T.it("to_array does not consume the buffer", function()
    local rb = queue.ring_new(3)
    rb:push(1)
    rb:push(2)
    rb:to_array()
    T.eq(rb:size(), 2)
    T.eq(rb:pop(), 1)
  end)

  T.it("empty buffer returns empty array", function()
    local rb = queue.ring_new(4)
    local arr = rb:to_array()
    T.eq(#arr, 0)
  end)
end)

T.describe("ring_new: mixed push/pop with wrap-around", function()
  T.it("correct order after partial drain and refill", function()
    local rb = queue.ring_new(4)
    rb:push(1)
    rb:push(2)
    rb:push(3)
    rb:pop()   -- remove 1
    rb:push(4)
    rb:push(5)  -- full now: {2,3,4,5}
    rb:push(6)  -- overwrites 2: {3,4,5,6}
    local arr = rb:to_array()
    T.eq(arr[1], 3)
    T.eq(arr[2], 4)
    T.eq(arr[3], 5)
    T.eq(arr[4], 6)
  end)
end)

T.describe("ring_new: capacity-1 edge case", function()
  T.it("capacity 1: second push overwrites first", function()
    local rb = queue.ring_new(1)
    rb:push(1)
    T.ok(rb:is_full())
    rb:push(2)
    T.eq(rb:size(), 1)
    T.eq(rb:pop(), 2)
  end)
end)

T.describe("ring_new: error on bad capacity", function()
  T.it("returns nil, errmsg for zero capacity", function()
    local rb, err = queue.ring_new(0)
    T.eq(rb, nil)
    T.ok(err ~= nil)
  end)

  T.it("returns nil, errmsg for negative capacity", function()
    local rb, err = queue.ring_new(-1)
    T.eq(rb, nil)
    T.ok(err ~= nil)
  end)
end)
