if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local queue = require("lib.queue")
local sqlite = require("lib.sqlite")

-- ── helpers ──────────────────────────────────────────────────────────────────

local function mem()
	local q, err = queue.open(":memory:")
	assert(q, "queue.open(:memory:) failed: " .. tostring(err))
	return q
end

-- ── tests ────────────────────────────────────────────────────────────────────

T.describe("queue: open", function()
	T.it("creates a queue", function()
		local q, err = queue.open(":memory:")
		T.ok(q, "open should succeed")
		T.eq(err, nil)
		q:close()
	end)
end)

T.describe("queue: push", function()
	T.it("returns a job id", function()
		local q = mem()
		local id, err = q:push("email", { to = "alice@example.com" })
		T.ok(id, "push should return an id")
		T.eq(type(id), "number")
		T.eq(err, nil)
		q:close()
	end)
end)

T.describe("queue: pop", function()
	T.it("returns the job with correct payload", function()
		local q = mem()
		q:push("email", { to = "bob@example.com", subject = "Hi" })
		local job = q:pop("email")
		T.ok(job, "pop should return a job")
		T.eq(job.queue, "email")
		T.eq(job.payload.to, "bob@example.com")
		T.eq(job.payload.subject, "Hi")
		T.eq(job.attempts, 1)
		q:close()
	end)

	T.it("returns nil on empty queue", function()
		local q = mem()
		local job = q:pop("email")
		T.eq(job, nil)
		q:close()
	end)
end)

T.describe("queue: ack", function()
	T.it("marks job completed, not returned by subsequent pop", function()
		local q = mem()
		q:push("email", { x = 1 })
		local job = q:pop("email")
		T.ok(job)
		local ok = q:ack(job.id)
		T.ok(ok)
		local job2 = q:pop("email")
		T.eq(job2, nil)
		q:close()
	end)
end)

T.describe("queue: fail", function()
	T.it("with retries remaining: job status goes back to pending", function()
		local q = mem()
		-- Use max_retries=3 (default). After pop, attempts=1.
		q:push("email", { x = 1 })
		local job = q:pop("email")
		T.ok(job)
		T.eq(job.attempts, 1)
		T.eq(job.max_retries, 3)
		local ok = q:fail(job.id, "transient error")
		T.ok(ok)
		-- Job should be pending again (but with future available_at due to backoff).
		-- Verify via direct query that status is pending.
		local iter = q.db:query("SELECT status FROM _queue_jobs WHERE id = ?", job.id)
		local status = iter()
		T.eq(status, "pending")
		q:close()
	end)

	T.it("exceeding max_retries: job goes to dead letter", function()
		local q = mem()
		q:push("email", { x = 1 }, { max_retries = 1 })
		local job = q:pop("email") -- attempts becomes 1
		T.ok(job)
		T.eq(job.attempts, 1)
		T.eq(job.max_retries, 1)
		local ok = q:fail(job.id, "permanent error")
		T.ok(ok)
		-- Should be dead now
		local iter = q.db:query("SELECT status FROM _queue_jobs WHERE id = ?", job.id)
		local status = iter()
		T.eq(status, "dead")
		q:close()
	end)
end)

T.describe("queue: priority", function()
	T.it("higher priority popped first", function()
		local q = mem()
		q:push("work", { name = "low" }, { priority = 1 })
		q:push("work", { name = "high" }, { priority = 10 })
		q:push("work", { name = "mid" }, { priority = 5 })
		local j1 = q:pop("work")
		local j2 = q:pop("work")
		local j3 = q:pop("work")
		T.eq(j1.payload.name, "high")
		T.eq(j2.payload.name, "mid")
		T.eq(j3.payload.name, "low")
		q:close()
	end)
end)

T.describe("queue: delay", function()
	T.it("job with delay not available immediately", function()
		local q = mem()
		q:push("email", { x = 1 }, { delay = 3600 })
		local job = q:pop("email")
		T.eq(job, nil) -- not available yet
		q:close()
	end)
end)

T.describe("queue: length", function()
	T.it("returns correct count", function()
		local q = mem()
		T.eq(q:length("email"), 0)
		q:push("email", { x = 1 })
		q:push("email", { x = 2 })
		T.eq(q:length("email"), 2)
		q:pop("email")
		T.eq(q:length("email"), 1)
		q:close()
	end)
end)

T.describe("queue: pending", function()
	T.it("returns list of pending jobs", function()
		local q = mem()
		q:push("email", { x = 1 })
		q:push("email", { x = 2 })
		local jobs = q:pending("email")
		T.eq(#jobs, 2)
		T.eq(jobs[1].payload.x, 1)
		T.eq(jobs[2].payload.x, 2)
		q:close()
	end)
end)

T.describe("queue: failed", function()
	T.it("returns dead-letter jobs", function()
		local q = mem()
		q:push("email", { x = 1 }, { max_retries = 1 })
		local job = q:pop("email")
		q:fail(job.id, "fatal")
		local dead = q:failed("email")
		T.eq(#dead, 1)
		T.eq(dead[1].payload.x, 1)
		q:close()
	end)
end)

T.describe("queue: clear", function()
	T.it("removes all jobs from a queue", function()
		local q = mem()
		q:push("email", { x = 1 })
		q:push("email", { x = 2 })
		q:push("other", { x = 3 })
		local ok = q:clear("email")
		T.ok(ok)
		T.eq(q:length("email"), 0)
		-- other queue unaffected
		T.eq(q:length("other"), 1)
		q:close()
	end)
end)

T.describe("queue: queues", function()
	T.it("lists queue names with jobs", function()
		local q = mem()
		q:push("email", { x = 1 })
		q:push("sms", { x = 2 })
		q:push("email", { x = 3 })
		local names = q:queues()
		T.eq(#names, 2)
		-- Sorted alphabetically
		T.eq(names[1], "email")
		T.eq(names[2], "sms")
		q:close()
	end)
end)

T.describe("queue: process", function()
	T.it("handler called, job acked", function()
		local q = mem()
		q:push("email", { to = "alice" })
		local called = false
		local result = q:process("email", function(job)
			called = true
			T.eq(job.payload.to, "alice")
			return true
		end)
		T.ok(called)
		T.eq(result, true)
		-- Queue should be empty now
		T.eq(q:length("email"), 0)
		local job = q:pop("email")
		T.eq(job, nil)
		q:close()
	end)

	T.it("handler error: job failed", function()
		local q = mem()
		q:push("email", { x = 1 })
		local result = q:process("email", function(job)
			error("boom")
		end)
		T.eq(result, true) -- process itself succeeded
		-- Job should be back in pending (with future available_at)
		local iter = q.db:query("SELECT status, error_message FROM _queue_jobs WHERE queue = 'email'")
		local status, errmsg = iter()
		T.eq(status, "pending")
		T.ok(errmsg and errmsg:find("boom"), "error message should contain 'boom'")
		q:close()
	end)

	T.it("on empty queue returns false", function()
		local q = mem()
		local result = q:process("email", function() return true end)
		T.eq(result, false)
		q:close()
	end)
end)

T.describe("queue: schedule", function()
	T.it("after ack, new job created with delay", function()
		local q = mem()
		local id = q:schedule("cleanup", { interval = 3600 })
		T.ok(id)
		-- The scheduled job has a future available_at, so manually make it available
		q.db:execute("UPDATE _queue_jobs SET available_at = datetime('now') WHERE id = ?", id)
		local job = q:pop("cleanup")
		T.ok(job, "should be able to pop the scheduled job")
		T.eq(job.scheduled_interval, 3600)
		-- Ack it — should create a new job
		q:ack(job.id)
		-- New job should exist (with future available_at)
		local iter = q.db:query("SELECT COUNT(*) FROM _queue_jobs WHERE queue = 'cleanup' AND status = 'pending'")
		local count = iter()
		T.eq(count, 1)
		q:close()
	end)
end)

T.describe("queue: multiple queues", function()
	T.it("jobs isolated by queue name", function()
		local q = mem()
		q:push("email", { x = 1 })
		q:push("sms", { x = 2 })
		local j1 = q:pop("email")
		T.ok(j1)
		T.eq(j1.payload.x, 1)
		local j2 = q:pop("sms")
		T.ok(j2)
		T.eq(j2.payload.x, 2)
		-- No cross-contamination
		local j3 = q:pop("email")
		T.eq(j3, nil)
		q:close()
	end)
end)

T.describe("queue: FIFO ordering", function()
	T.it("within same priority, FIFO order preserved", function()
		local q = mem()
		q:push("work", { order = 1 })
		q:push("work", { order = 2 })
		q:push("work", { order = 3 })
		local j1 = q:pop("work")
		local j2 = q:pop("work")
		local j3 = q:pop("work")
		T.eq(j1.payload.order, 1)
		T.eq(j2.payload.order, 2)
		T.eq(j3.payload.order, 3)
		q:close()
	end)
end)

T.describe("queue: wrap", function()
	T.it("wraps existing db", function()
		local db, err = sqlite.open(":memory:")
		T.ok(db, "sqlite.open should succeed")
		local q, wrap_err = queue.wrap(db)
		T.ok(q, "wrap should succeed")
		T.eq(wrap_err, nil)
		local id = q:push("test", { x = 1 })
		T.ok(id)
		local job = q:pop("test")
		T.ok(job)
		T.eq(job.payload.x, 1)
		q:close()
	end)
end)
