if not package.path:find("?/init.lua", 1, true) then
  package.path = package.path .. ";./?/init.lua"
end

local T = require("lib.test.assert")
local glob = require("lib.glob")

T.describe("glob", function()

  T.describe("is_glob", function()
    T.it("detects * as glob", function()
      T.ok(glob.is_glob("*.lua"))
    end)
    T.it("detects ** as glob", function()
      T.ok(glob.is_glob("src/**/*.lua"))
    end)
    T.it("detects ? as glob", function()
      T.ok(glob.is_glob("?.lua"))
    end)
    T.it("detects [...] as glob", function()
      T.ok(glob.is_glob("[abc].lua"))
    end)
    T.it("detects {a,b} as glob", function()
      T.ok(glob.is_glob("{a,b}.lua"))
    end)
    T.it("detects backslash escape as glob", function()
      T.ok(glob.is_glob("\\*.lua"))
    end)
    T.it("returns false for plain strings", function()
      T.fail(glob.is_glob("foo.lua"))
      T.fail(glob.is_glob("src/lib/foo.lua"))
      T.fail(glob.is_glob(""))
      T.fail(glob.is_glob("hello world"))
    end)
  end)

  T.describe("exact match", function()
    T.it("matches exact string", function()
      T.ok(glob.match("foo.lua", "foo.lua"))
    end)
    T.it("does not match different string", function()
      T.fail(glob.match("foo.lua", "bar.lua"))
    end)
    T.it("empty pattern matches empty string", function()
      T.ok(glob.match("", ""))
    end)
    T.it("empty pattern does not match non-empty string", function()
      T.fail(glob.match("", "foo"))
    end)
    T.it("non-empty pattern does not match empty string", function()
      T.fail(glob.match("foo", ""))
    end)
  end)

  T.describe("* wildcard", function()
    T.it("matches zero characters", function()
      T.ok(glob.match("*.lua", ".lua"))
    end)
    T.it("matches one character", function()
      T.ok(glob.match("*.lua", "a.lua"))
    end)
    T.it("matches multiple characters", function()
      T.ok(glob.match("*.lua", "init.lua"))
    end)
    T.it("does not match /", function()
      T.fail(glob.match("*.lua", "src/init.lua"))
    end)
    T.it("matches at end", function()
      T.ok(glob.match("foo.*", "foo.txt"))
      T.ok(glob.match("foo.*", "foo."))
    end)
    T.it("matches in middle", function()
      T.ok(glob.match("f*o", "foo"))
      T.ok(glob.match("f*o", "fooo"))
      T.ok(glob.match("f*o", "fxyz_o"))
    end)
    T.it("pattern with only * matches any non-slash string", function()
      T.ok(glob.match("*", "anything"))
      T.ok(glob.match("*", ""))
      T.fail(glob.match("*", "a/b"))
    end)
    T.it("multiple * in pattern", function()
      T.ok(glob.match("*.*", "foo.bar"))
      T.ok(glob.match("*.*", ".hidden"))
      T.fail(glob.match("*.*", "noext"))
    end)
  end)

  T.describe("** globstar", function()
    T.it("matches across directories", function()
      T.ok(glob.match("src/**/*.lua", "src/lib/foo.lua"))
      T.ok(glob.match("src/**/*.lua", "src/a/b/c.lua"))
    end)
    T.it("matches zero directories", function()
      T.ok(glob.match("src/**/*.lua", "src/foo.lua"))
    end)
    T.it("at start of pattern", function()
      T.ok(glob.match("**/*.lua", "foo.lua"))
      T.ok(glob.match("**/*.lua", "src/foo.lua"))
      T.ok(glob.match("**/*.lua", "a/b/c/d.lua"))
    end)
    T.it("at end of pattern", function()
      T.ok(glob.match("src/**", "src/foo.lua"))
      T.ok(glob.match("src/**", "src/a/b/c"))
      T.ok(glob.match("src/**", "src/"))
    end)
    T.it("** alone matches everything", function()
      T.ok(glob.match("**", "anything"))
      T.ok(glob.match("**", "a/b/c"))
      T.ok(glob.match("**", ""))
    end)
    T.it("consecutive ** are treated as one", function()
      T.ok(glob.match("src/**/**/*.lua", "src/a/b.lua"))
    end)
    T.it("does not match partial directory names with adjacent text", function()
      T.fail(glob.match("src/**/*.lua", "srcx/foo.lua"))
    end)
  end)

  T.describe("? wildcard", function()
    T.it("matches exactly one character", function()
      T.ok(glob.match("?.lua", "a.lua"))
    end)
    T.it("does not match zero characters", function()
      T.fail(glob.match("?.lua", ".lua"))
    end)
    T.it("does not match /", function()
      T.fail(glob.match("?", "/"))
    end)
    T.it("multiple ? in a row", function()
      T.ok(glob.match("???.lua", "abc.lua"))
      T.fail(glob.match("???.lua", "ab.lua"))
      T.fail(glob.match("???.lua", "abcd.lua"))
    end)
  end)

  T.describe("character classes", function()
    T.it("[abc] matches listed chars", function()
      T.ok(glob.match("[abc].lua", "a.lua"))
      T.ok(glob.match("[abc].lua", "b.lua"))
      T.ok(glob.match("[abc].lua", "c.lua"))
      T.fail(glob.match("[abc].lua", "d.lua"))
    end)
    T.it("[a-z] matches range", function()
      T.ok(glob.match("[a-z].txt", "m.txt"))
      T.fail(glob.match("[a-z].txt", "M.txt"))
      T.fail(glob.match("[a-z].txt", "1.txt"))
    end)
    T.it("[!abc] negated class", function()
      T.fail(glob.match("[!abc].lua", "a.lua"))
      T.ok(glob.match("[!abc].lua", "d.lua"))
      T.ok(glob.match("[!abc].lua", "z.lua"))
    end)
    T.it("[^abc] negated class (caret)", function()
      T.fail(glob.match("[^abc].lua", "a.lua"))
      T.ok(glob.match("[^abc].lua", "x.lua"))
    end)
    T.it("[!a-z] negated range", function()
      T.fail(glob.match("[!a-z].txt", "m.txt"))
      T.ok(glob.match("[!a-z].txt", "M.txt"))
      T.ok(glob.match("[!a-z].txt", "5.txt"))
    end)
    T.it("character class does not match /", function()
      T.fail(glob.match("[/]", "/"))
    end)
    T.it("character class with ] as first char", function()
      T.ok(glob.match("[]abc]", "]"))
      T.ok(glob.match("[]abc]", "a"))
    end)
  end)

  T.describe("brace expansion", function()
    T.it("{a,b} matches alternatives", function()
      T.ok(glob.match("{a,b}.txt", "a.txt"))
      T.ok(glob.match("{a,b}.txt", "b.txt"))
      T.fail(glob.match("{a,b}.txt", "c.txt"))
    end)
    T.it("{a,b,c} three alternatives", function()
      T.ok(glob.match("{a,b,c}", "a"))
      T.ok(glob.match("{a,b,c}", "b"))
      T.ok(glob.match("{a,b,c}", "c"))
      T.fail(glob.match("{a,b,c}", "d"))
    end)
    T.it("brace with extensions", function()
      T.ok(glob.match("*.{lua,moon}", "foo.lua"))
      T.ok(glob.match("*.{lua,moon}", "bar.moon"))
      T.fail(glob.match("*.{lua,moon}", "baz.txt"))
    end)
    T.it("nested braces", function()
      T.ok(glob.match("{a,{b,c}}", "a"))
      T.ok(glob.match("{a,{b,c}}", "b"))
      T.ok(glob.match("{a,{b,c}}", "c"))
      T.fail(glob.match("{a,{b,c}}", "d"))
    end)
    T.it("brace with wildcards inside", function()
      T.ok(glob.match("{*.lua,*.txt}", "foo.lua"))
      T.ok(glob.match("{*.lua,*.txt}", "bar.txt"))
      T.fail(glob.match("{*.lua,*.txt}", "baz.rs"))
    end)
    T.it("single alternative in braces", function()
      T.ok(glob.match("{abc}", "abc"))
      T.fail(glob.match("{abc}", "def"))
    end)
    T.it("empty alternative in braces", function()
      T.ok(glob.match("foo{,bar}", "foo"))
      T.ok(glob.match("foo{,bar}", "foobar"))
    end)
  end)

  T.describe("escape", function()
    T.it("\\* matches literal *", function()
      T.ok(glob.match("\\*", "*"))
      T.fail(glob.match("\\*", "a"))
    end)
    T.it("\\? matches literal ?", function()
      T.ok(glob.match("\\?", "?"))
      T.fail(glob.match("\\?", "a"))
    end)
    T.it("\\[ matches literal [", function()
      T.ok(glob.match("\\[a]", "[a]"))
      T.fail(glob.match("\\[a]", "a"))
    end)
    T.it("\\{ matches literal {", function()
      T.ok(glob.match("\\{a,b}", "{a,b}"))
    end)
  end)

  T.describe("complex patterns", function()
    T.it("src/**/*.{lua,moon}", function()
      T.ok(glob.match("src/**/*.{lua,moon}", "src/foo.lua"))
      T.ok(glob.match("src/**/*.{lua,moon}", "src/a/b/c.moon"))
      T.fail(glob.match("src/**/*.{lua,moon}", "src/a/b/c.txt"))
      T.fail(glob.match("src/**/*.{lua,moon}", "lib/a.lua"))
    end)
    T.it("**/test_*.lua", function()
      T.ok(glob.match("**/test_*.lua", "test_foo.lua"))
      T.ok(glob.match("**/test_*.lua", "src/test_bar.lua"))
      T.ok(glob.match("**/test_*.lua", "a/b/test_baz.lua"))
      T.fail(glob.match("**/test_*.lua", "a/b/foo.lua"))
    end)
    T.it("lib/*/init.lua", function()
      T.ok(glob.match("lib/*/init.lua", "lib/glob/init.lua"))
      T.ok(glob.match("lib/*/init.lua", "lib/ansi/init.lua"))
      T.fail(glob.match("lib/*/init.lua", "lib/a/b/init.lua"))
    end)
    T.it("[A-Z]*.lua matches capitalized files", function()
      T.ok(glob.match("[A-Z]*.lua", "Makefile.lua"))
      T.fail(glob.match("[A-Z]*.lua", "makefile.lua"))
    end)
    T.it("path with multiple * segments", function()
      T.ok(glob.match("src/*/test/*.lua", "src/foo/test/bar.lua"))
      T.fail(glob.match("src/*/test/*.lua", "src/foo/baz/bar.lua"))
    end)
  end)

  T.describe("compile", function()
    T.it("returns a matcher object", function()
      local m, err = glob.compile("*.lua")
      T.ok(m, "compile should succeed")
      T.eq(err, nil)
    end)
    T.it("matcher:match works", function()
      local m = glob.compile("*.lua")
      T.ok(m:match("foo.lua"))
      T.fail(m:match("foo.txt"))
    end)
    T.it("returns nil, errmsg for bad pattern", function()
      local m, err = glob.compile("[unterminated")
      T.eq(m, nil)
      T.ok(err, "should return error message")
    end)
    T.it("returns nil, errmsg for unterminated brace", function()
      local m, err = glob.compile("{a,b")
      T.eq(m, nil)
      T.ok(err)
    end)
  end)

  T.describe("filter", function()
    T.it("filters matching strings", function()
      local result = glob.filter({"a.lua", "b.txt", "c.lua", "d.rs"}, "*.lua")
      T.eq(#result, 2)
      T.eq(result[1], "a.lua")
      T.eq(result[2], "c.lua")
    end)
    T.it("returns empty table for no matches", function()
      local result = glob.filter({"a.txt", "b.rs"}, "*.lua")
      T.eq(#result, 0)
    end)
    T.it("returns nil, errmsg for bad pattern", function()
      local result, err = glob.filter({"a"}, "[bad")
      T.eq(result, nil)
      T.ok(err)
    end)
    T.it("filter with ** pattern", function()
      local result = glob.filter({
        "src/a.lua", "src/b/c.lua", "lib/d.lua", "src/e.txt"
      }, "src/**/*.lua")
      T.eq(#result, 2)
      T.eq(result[1], "src/a.lua")
      T.eq(result[2], "src/b/c.lua")
    end)
  end)

  T.describe("to_pattern", function()
    T.it("converts * to [^/]*", function()
      local p = glob.to_pattern("*.lua")
      T.eq(p, "^[^/]*%.lua$")
    end)
    T.it("converts ** to .*", function()
      local p = glob.to_pattern("**/*.lua")
      T.ok(p:find("%.%*"), "should contain .*")
    end)
    T.it("converts ? to [^/]", function()
      local p = glob.to_pattern("?.lua")
      T.eq(p, "^[^/]%.lua$")
    end)
    T.it("escapes lua pattern metacharacters", function()
      local p = glob.to_pattern("foo.lua")
      T.ok(p:find("%%%."), "dot should be escaped")
    end)
    T.it("simple pattern works with string.find", function()
      local p = glob.to_pattern("*.lua")
      T.ok(("init.lua"):find(p))
      T.fail(("init.txt"):find(p))
    end)
    T.it("returns nil, errmsg for bad pattern", function()
      local p, err = glob.to_pattern("[bad")
      T.eq(p, nil)
      T.ok(err)
    end)
  end)

  T.describe("edge cases", function()
    T.it("pattern with only *", function()
      T.ok(glob.match("*", ""))
      T.ok(glob.match("*", "foo"))
      T.fail(glob.match("*", "a/b"))
    end)
    T.it("pattern with only **", function()
      T.ok(glob.match("**", ""))
      T.ok(glob.match("**", "a"))
      T.ok(glob.match("**", "a/b/c"))
    end)
    T.it("dot files", function()
      T.ok(glob.match("*", ".hidden"))
      T.ok(glob.match(".*", ".hidden"))
    end)
    T.it("trailing slash in path", function()
      T.ok(glob.match("src/*", "src/foo"))
      T.fail(glob.match("src/*", "src/foo/"))
    end)
    T.it("multiple slashes in path", function()
      T.ok(glob.match("a/b/c", "a/b/c"))
      T.fail(glob.match("a/b/c", "a//b/c"))
    end)
  end)

  T.describe("path separators", function()
    T.it("/ in pattern matches / in string", function()
      T.ok(glob.match("src/lib/foo.lua", "src/lib/foo.lua"))
    end)
    T.it("* does not cross /", function()
      T.fail(glob.match("src/*.lua", "src/sub/foo.lua"))
    end)
    T.it("** crosses /", function()
      T.ok(glob.match("src/**.lua", "src/sub/foo.lua"))
    end)
  end)

end)
