if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local P = require("lib.parser_combinators")

T.describe("parser_combinators", function()

  T.describe("P.lit", function()
    T.it("matches literal string", function()
      local r, np = P.lit("hello")("hello world", 1)
      T.eq(r, "hello")
      T.eq(np, 6)
    end)
    T.it("fails on mismatch", function()
      local r, err = P.lit("hello")("world", 1)
      T.eq(r, nil)
      T.ok(err:find("position"))
    end)
    T.it("matches at offset", function()
      local r, np = P.lit("world")("hello world", 7)
      T.eq(r, "world")
      T.eq(np, 12)
    end)
    T.it("matches empty string", function()
      local r, np = P.lit("")("abc", 1)
      T.eq(r, "")
      T.eq(np, 1)
    end)
  end)

  T.describe("P.char", function()
    T.it("matches single char", function()
      local r, np = P.char("a")("abc", 1)
      T.eq(r, "a")
      T.eq(np, 2)
    end)
    T.it("fails on mismatch", function()
      local r, err = P.char("a")("bcd", 1)
      T.eq(r, nil)
      T.ok(err:find("position"))
    end)
  end)

  T.describe("P.char_class", function()
    T.it("matches digit class", function()
      local r, np = P.char_class("[0-9]")("5abc", 1)
      T.eq(r, "5")
      T.eq(np, 2)
    end)
    T.it("matches lowercase class", function()
      local r, np = P.char_class("[a-z]")("hello", 1)
      T.eq(r, "h")
      T.eq(np, 2)
    end)
    T.it("fails on mismatch", function()
      local r, err = P.char_class("[a-z]")("ABC", 1)
      T.eq(r, nil)
      T.ok(err:find("position"))
    end)
    T.it("matches negated class", function()
      local r, np = P.char_class("[^abc]")("xyz", 1)
      T.eq(r, "x")
      T.eq(np, 2)
    end)
    T.it("fails negated class on match", function()
      local r, _ = P.char_class("[^abc]")("abc", 1)
      T.eq(r, nil)
    end)
  end)

  T.describe("P.any_char", function()
    T.it("matches any character", function()
      local r, np = P.any_char("xyz", 1)
      T.eq(r, "x")
      T.eq(np, 2)
    end)
    T.it("fails at end of input", function()
      local r, err = P.any_char("", 1)
      T.eq(r, nil)
      T.ok(err:find("end of input"))
    end)
  end)

  T.describe("P.digit", function()
    T.it("matches digit", function()
      local r, np = P.digit("42", 1)
      T.eq(r, "4")
      T.eq(np, 2)
    end)
    T.it("fails on non-digit", function()
      local r, _ = P.digit("abc", 1)
      T.eq(r, nil)
    end)
  end)

  T.describe("P.letter", function()
    T.it("matches lowercase letter", function()
      local r, np = P.letter("abc", 1)
      T.eq(r, "a")
      T.eq(np, 2)
    end)
    T.it("matches uppercase letter", function()
      local r, np = P.letter("XYZ", 1)
      T.eq(r, "X")
      T.eq(np, 2)
    end)
    T.it("fails on digit", function()
      local r, _ = P.letter("123", 1)
      T.eq(r, nil)
    end)
  end)

  T.describe("P.whitespace", function()
    T.it("matches space", function()
      local r, np = P.whitespace(" abc", 1)
      T.eq(r, " ")
      T.eq(np, 2)
    end)
    T.it("matches tab", function()
      local r, np = P.whitespace("\tabc", 1)
      T.eq(r, "\t")
      T.eq(np, 2)
    end)
    T.it("fails on non-whitespace", function()
      local r, _ = P.whitespace("abc", 1)
      T.eq(r, nil)
    end)
  end)

  T.describe("P.eof", function()
    T.it("matches end of input", function()
      local r, np = P.eof("", 1)
      T.eq(r, true)
      T.eq(np, 1)
    end)
    T.it("fails before end", function()
      local r, err = P.eof("abc", 1)
      T.eq(r, nil)
      T.ok(err:find("position"))
    end)
    T.it("matches after full consumption", function()
      local r, np = P.eof("ab", 3)
      T.eq(r, true)
      T.eq(np, 3)
    end)
  end)

  T.describe("P.succeed", function()
    T.it("always succeeds with given value", function()
      local r, np = P.succeed(42)("anything", 1)
      T.eq(r, 42)
      T.eq(np, 1)
    end)
    T.it("consumes nothing", function()
      local r, np = P.succeed("x")("hello", 3)
      T.eq(r, "x")
      T.eq(np, 3)
    end)
  end)

  T.describe("P.fail", function()
    T.it("always fails", function()
      local r, err = P.fail("my error")("anything", 1)
      T.eq(r, nil)
      T.ok(err:find("my error"))
      T.ok(err:find("position"))
    end)
  end)

  T.describe("P.seq", function()
    T.it("matches sequence in order", function()
      local r, np = P.seq(P.lit("foo"), P.lit("bar"))("foobar", 1)
      T.eq(r[1], "foo")
      T.eq(r[2], "bar")
      T.eq(np, 7)
    end)
    T.it("fails if any element fails", function()
      local r, err = P.seq(P.lit("foo"), P.lit("bar"))("foobaz", 1)
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
    T.it("returns array of all results", function()
      local r, _ = P.seq(P.char("a"), P.char("b"), P.char("c"))("abc", 1)
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[2], "b")
      T.eq(r[3], "c")
    end)
  end)

  T.describe("P.choice", function()
    T.it("first match wins", function()
      local r, np = P.choice(P.lit("foo"), P.lit("bar"))("foo", 1)
      T.eq(r, "foo")
      T.eq(np, 4)
    end)
    T.it("falls through to second", function()
      local r, np = P.choice(P.lit("foo"), P.lit("bar"))("bar", 1)
      T.eq(r, "bar")
      T.eq(np, 4)
    end)
    T.it("fails if none match", function()
      local r, _ = P.choice(P.lit("foo"), P.lit("bar"))("baz", 1)
      T.eq(r, nil)
    end)
    T.it("ordered: first match is returned even if second is longer", function()
      local r, _ = P.choice(P.lit("fo"), P.lit("foo"))("foo", 1)
      T.eq(r, "fo")
    end)
  end)

  T.describe("P.many", function()
    T.it("matches zero occurrences", function()
      local r, np = P.many(P.digit)("abc", 1)
      T.eq(#r, 0)
      T.eq(np, 1)
    end)
    T.it("matches multiple occurrences", function()
      local r, np = P.many(P.digit)("123abc", 1)
      T.eq(#r, 3)
      T.eq(r[1], "1")
      T.eq(r[2], "2")
      T.eq(r[3], "3")
      T.eq(np, 4)
    end)
    T.it("matches all", function()
      local r, np = P.many(P.digit)("9876", 1)
      T.eq(#r, 4)
      T.eq(np, 5)
    end)
  end)

  T.describe("P.many1", function()
    T.it("fails on zero occurrences", function()
      local r, _ = P.many1(P.digit)("abc", 1)
      T.eq(r, nil)
    end)
    T.it("matches one occurrence", function()
      local r, np = P.many1(P.digit)("1abc", 1)
      T.eq(#r, 1)
      T.eq(r[1], "1")
      T.eq(np, 2)
    end)
    T.it("matches multiple", function()
      local r, np = P.many1(P.digit)("123abc", 1)
      T.eq(#r, 3)
      T.eq(np, 4)
    end)
  end)

  T.describe("P.optional", function()
    T.it("returns value when present", function()
      local r, np = P.optional(P.digit)("1abc", 1)
      T.eq(r, "1")
      T.eq(np, 2)
    end)
    T.it("returns false when absent (no consume)", function()
      local r, np = P.optional(P.digit)("abc", 1)
      T.eq(r, false)
      T.eq(np, 1)
    end)
  end)

  T.describe("P.skip", function()
    T.it("matches and discards result", function()
      local r, np = P.skip(P.lit("--"))("-- comment", 1)
      T.eq(r, true)
      T.eq(np, 3)
    end)
    T.it("fails if parser fails", function()
      local r, _ = P.skip(P.lit("--"))("++", 1)
      T.eq(r, nil)
    end)
  end)

  T.describe("P.map", function()
    T.it("transforms result", function()
      local r, np = P.map(P.many1(P.digit), table.concat)("123abc", 1)
      T.eq(r, "123")
      T.eq(np, 4)
    end)
    T.it("propagates failure", function()
      local r, _ = P.map(P.digit, tonumber)("abc", 1)
      T.eq(r, nil)
    end)
    T.it("can convert types", function()
      local num_parser = P.map(P.many1(P.digit), function(ds)
        return tonumber(table.concat(ds))
      end)
      local r, np = num_parser("42xyz", 1)
      T.eq(r, 42)
      T.eq(np, 3)
    end)
  end)

  T.describe("P.between", function()
    T.it("matches content between delimiters", function()
      local content = P.map(P.many1(P.letter), table.concat)
      local r, np = P.between(P.lit("("), content, P.lit(")"))("(hello)", 1)
      T.eq(r, "hello")
      T.eq(np, 8)
    end)
    T.it("fails if open missing", function()
      local r, _ = P.between(P.lit("("), P.letter, P.lit(")"))("hello)", 1)
      T.eq(r, nil)
    end)
    T.it("fails if close missing", function()
      local r, _ = P.between(P.lit("("), P.letter, P.lit(")"))("(hello", 1)
      T.eq(r, nil)
    end)
  end)

  T.describe("P.sep_by", function()
    T.it("matches zero items", function()
      local r, np = P.sep_by(P.digit, P.lit(","))("abc", 1)
      T.eq(#r, 0)
      T.eq(np, 1)
    end)
    T.it("matches one item", function()
      local r, np = P.sep_by(P.digit, P.lit(","))("5abc", 1)
      T.eq(#r, 1)
      T.eq(r[1], "5")
      T.eq(np, 2)
    end)
    T.it("matches multiple items", function()
      local r, np = P.sep_by(P.digit, P.lit(","))("1,2,3", 1)
      T.eq(#r, 3)
      T.eq(r[1], "1")
      T.eq(r[2], "2")
      T.eq(r[3], "3")
      T.eq(np, 6)
    end)
    T.it("stops before trailing sep", function()
      local r, np = P.sep_by(P.digit, P.lit(","))("1,2,abc", 1)
      T.eq(#r, 2)
      T.eq(np, 4)
    end)
  end)

  T.describe("P.sep_by1", function()
    T.it("fails on zero items", function()
      local r, _ = P.sep_by1(P.digit, P.lit(","))("abc", 1)
      T.eq(r, nil)
    end)
    T.it("matches one item", function()
      local r, np = P.sep_by1(P.digit, P.lit(","))("5", 1)
      T.eq(#r, 1)
      T.eq(r[1], "5")
      T.eq(np, 2)
    end)
    T.it("matches multiple items", function()
      local r, np = P.sep_by1(P.digit, P.lit(","))("1,2,3xyz", 1)
      T.eq(#r, 3)
      T.eq(np, 6)
    end)
  end)

  T.describe("P.lazy", function()
    T.it("allows recursive grammars (nested parens)", function()
      -- Grammar: expr = '(' expr ')' | 'x'
      local expr
      expr = P.lazy(function()
        return P.choice(
          P.between(P.lit("("), expr, P.lit(")")),
          P.lit("x")
        )
      end)
      local r1, _ = P.parse(expr, "x")
      T.eq(r1, "x")
      local r2, _ = P.parse(expr, "(x)")
      T.eq(r2, "x")
      local r3, _ = P.parse(expr, "((x))")
      T.eq(r3, "x")
      local r4, _ = P.parse(expr, "(((x)))")
      T.eq(r4, "x")
    end)
    T.it("fails on invalid nested parens", function()
      local expr
      expr = P.lazy(function()
        return P.choice(
          P.between(P.lit("("), expr, P.lit(")")),
          P.lit("x")
        )
      end)
      local r, _ = P.parse(expr, "(x")
      T.eq(r, nil)
    end)
  end)

  T.describe("P.not_followed_by", function()
    T.it("succeeds when p fails", function()
      local r, np = P.not_followed_by(P.digit)("abc", 1)
      T.eq(r, true)
      T.eq(np, 1)  -- consumes nothing
    end)
    T.it("fails when p succeeds", function()
      local r, _ = P.not_followed_by(P.digit)("123", 1)
      T.eq(r, nil)
    end)
    T.it("can be used to reject keyword continuation", function()
      -- keyword "if" not followed by letter/digit
      local keyword = P.seq(
        P.lit("if"),
        P.not_followed_by(P.choice(P.letter, P.digit))
      )
      local r1, _ = P.parse(keyword, "if ")
      T.ok(r1 ~= nil)
      local r2, _ = P.parse(keyword, "iff")
      T.eq(r2, nil)
    end)
  end)

  T.describe("P.parse", function()
    T.it("returns result on success", function()
      local r, err = P.parse(P.lit("hello"), "hello world")
      T.eq(r, "hello")
      T.eq(err, nil)
    end)
    T.it("returns nil and errmsg on failure", function()
      local r, err = P.parse(P.lit("hello"), "world")
      T.eq(r, nil)
      T.ok(err ~= nil)
      T.ok(err:find("position"))
    end)
  end)

  T.describe("P.parse_all", function()
    T.it("succeeds when all input consumed", function()
      local r, err = P.parse_all(P.lit("hello"), "hello")
      T.eq(r, "hello")
      T.eq(err, nil)
    end)
    T.it("fails when input remains", function()
      local r, err = P.parse_all(P.lit("hello"), "hello world")
      T.eq(r, nil)
      T.ok(err:find("position"))
    end)
    T.it("fails on parse failure", function()
      local r, err = P.parse_all(P.lit("hello"), "world")
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
  end)

  T.describe("non-trivial: JSON number parser", function()
    -- JSON number: -?[0-9]+(\.[0-9]+)?([eE][+-]?[0-9]+)?
    local digits = P.map(P.many1(P.digit), table.concat)
    local sign = P.optional(P.char("-"))
    local dot_part = P.map(
      P.seq(P.lit("."), digits),
      function(parts) return "." .. parts[2] end
    )
    local exp_sign = P.optional(P.choice(P.char("+"), P.char("-")))
    local exp_part = P.map(
      P.seq(P.choice(P.char("e"), P.char("E")), exp_sign, digits),
      function(parts)
        local s = parts[1]
        if parts[2] ~= false then s = s .. parts[2] end
        return s .. parts[3]
      end
    )
    local json_number = P.map(
      P.seq(sign, digits, P.optional(dot_part), P.optional(exp_part)),
      function(parts)
        local s = ""
        if parts[1] ~= false then s = s .. parts[1] end
        s = s .. parts[2]
        if parts[3] ~= false then s = s .. parts[3] end
        if parts[4] ~= false then s = s .. parts[4] end
        return tonumber(s)
      end
    )

    T.it("parses integer", function()
      local r, err = P.parse_all(json_number, "42")
      T.eq(err, nil)
      T.eq(r, 42)
    end)
    T.it("parses negative integer", function()
      local r, err = P.parse_all(json_number, "-7")
      T.eq(err, nil)
      T.eq(r, -7)
    end)
    T.it("parses float", function()
      local r, err = P.parse_all(json_number, "3.14")
      T.eq(err, nil)
      T.eq(r, 3.14)
    end)
    T.it("parses with exponent", function()
      local r, err = P.parse_all(json_number, "1e10")
      T.eq(err, nil)
      T.eq(r, 1e10)
    end)
    T.it("parses full form", function()
      local r, err = P.parse_all(json_number, "-2.5e-3")
      T.eq(err, nil)
      T.eq(r, -2.5e-3)
    end)
    T.it("fails on non-number", function()
      local r, _ = P.parse_all(json_number, "abc")
      T.eq(r, nil)
    end)
  end)

  T.describe("non-trivial: simple arithmetic expression", function()
    -- expr = term (('+' | '-') term)*
    -- term = factor (('*' | '/') factor)*
    -- factor = number | '(' expr ')'
    -- number = [0-9]+

    local ws = P.many(P.whitespace)
    local function token(p)
      return P.map(P.seq(ws, p, ws), function(parts) return parts[2] end)
    end

    local number_p = token(P.map(P.many1(P.digit), function(ds)
      return tonumber(table.concat(ds))
    end))

    local expr, term, factor
    factor = P.lazy(function()
      return P.choice(
        P.between(token(P.lit("(")), expr, token(P.lit(")"))),
        number_p
      )
    end)
    term = P.lazy(function()
      return P.map(
        P.seq(factor, P.many(P.seq(token(P.choice(P.char("*"), P.char("/"))), factor))),
        function(parts)
          local result = parts[1]
          for _, pair in ipairs(parts[2]) do
            local op, rhs = pair[1], pair[2]
            if op == "*" then result = result * rhs
            else result = result / rhs end
          end
          return result
        end
      )
    end)
    expr = P.lazy(function()
      return P.map(
        P.seq(term, P.many(P.seq(token(P.choice(P.char("+"), P.char("-"))), term))),
        function(parts)
          local result = parts[1]
          for _, pair in ipairs(parts[2]) do
            local op, rhs = pair[1], pair[2]
            if op == "+" then result = result + rhs
            else result = result - rhs end
          end
          return result
        end
      )
    end)

    T.it("parses single number", function()
      local r, err = P.parse_all(expr, "42")
      T.eq(err, nil)
      T.eq(r, 42)
    end)
    T.it("addition", function()
      local r, err = P.parse_all(expr, "1 + 2")
      T.eq(err, nil)
      T.eq(r, 3)
    end)
    T.it("subtraction", function()
      local r, err = P.parse_all(expr, "10 - 3")
      T.eq(err, nil)
      T.eq(r, 7)
    end)
    T.it("multiplication", function()
      local r, err = P.parse_all(expr, "3 * 4")
      T.eq(err, nil)
      T.eq(r, 12)
    end)
    T.it("operator precedence", function()
      local r, err = P.parse_all(expr, "2 + 3 * 4")
      T.eq(err, nil)
      T.eq(r, 14)
    end)
    T.it("parenthesized expression", function()
      local r, err = P.parse_all(expr, "(2 + 3) * 4")
      T.eq(err, nil)
      T.eq(r, 20)
    end)
    T.it("nested parentheses", function()
      local r, err = P.parse_all(expr, "((2 + 3)) * 4")
      T.eq(err, nil)
      T.eq(r, 20)
    end)
    T.it("complex expression", function()
      local r, err = P.parse_all(expr, "10 - 2 * 3 + 1")
      T.eq(err, nil)
      T.eq(r, 5)
    end)
  end)

  T.describe("non-trivial: CSV row parser", function()
    -- CSV row: field (',' field)*
    -- field: quoted | unquoted
    -- quoted: '"' (any char except '"')* '"'
    -- unquoted: (any char except ',' and newline)*
    local unquoted = P.map(
      P.many(P.char_class("[^,\n]")),
      table.concat
    )
    local quoted_char = P.choice(
      P.map(P.lit("\"\""), function() return "\"" end),
      P.char_class("[^\"]")
    )
    local quoted = P.between(
      P.char("\""),
      P.map(P.many(quoted_char), table.concat),
      P.char("\"")
    )
    local field = P.choice(quoted, unquoted)
    local csv_row = P.sep_by(field, P.char(","))

    T.it("parses simple CSV", function()
      local r, err = P.parse_all(csv_row, "a,b,c")
      T.eq(err, nil)
      T.eq(#r, 3)
      T.eq(r[1], "a")
      T.eq(r[2], "b")
      T.eq(r[3], "c")
    end)
    T.it("parses quoted field", function()
      local r, err = P.parse_all(csv_row, "\"hello world\",foo")
      T.eq(err, nil)
      T.eq(#r, 2)
      T.eq(r[1], "hello world")
      T.eq(r[2], "foo")
    end)
    T.it("parses empty fields", function()
      local r, err = P.parse_all(csv_row, "a,,c")
      T.eq(err, nil)
      T.eq(#r, 3)
      T.eq(r[2], "")
    end)
    T.it("parses quoted field with escaped quote", function()
      local r, err = P.parse_all(csv_row, "\"say \"\"hi\"\"\"")
      T.eq(err, nil)
      T.eq(#r, 1)
      T.eq(r[1], "say \"hi\"")
    end)
  end)

end)
