if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local N = require("lib.netstring")

-- ========================
-- NETSTRING encode
-- ========================

T.describe("netstring encode", function()
  T.it("encodes simple string", function()
    T.eq(N.encode("hello"), "5:hello,")
  end)
  T.it("encodes empty string", function()
    T.eq(N.encode(""), "0:,")
  end)
  T.it("encodes string with special chars", function()
    T.eq(N.encode("a:b,c"), "5:a:b,c,")
  end)
  T.it("encodes binary data", function()
    T.eq(N.encode("\0\1\2"), "3:\0\1\2,")
  end)
end)

-- ========================
-- NETSTRING decode
-- ========================

T.describe("netstring decode", function()
  T.it("decodes simple netstring", function()
    local data, rest = N.decode("5:hello,")
    T.eq(data, "hello")
    T.eq(rest, "")
  end)
  T.it("decodes empty netstring", function()
    local data, rest = N.decode("0:,")
    T.eq(data, "")
    T.eq(rest, "")
  end)
  T.it("returns rest of buffer", function()
    local data, rest = N.decode("5:hello,world")
    T.eq(data, "hello")
    T.eq(rest, "world")
  end)
  T.it("error: no colon", function()
    local data, err = N.decode("hello")
    T.eq(data, nil)
    T.ok(err ~= nil)
  end)
  T.it("error: invalid length (non-numeric)", function()
    local data, err = N.decode("abc:hello,")
    T.eq(data, nil)
    T.ok(err ~= nil)
  end)
  T.it("error: wrong length (buffer too short)", function()
    local data, err = N.decode("10:hi,")
    T.eq(data, nil)
    T.ok(err ~= nil)
  end)
  T.it("error: missing trailing comma", function()
    local data, err = N.decode("5:hello!")
    T.eq(data, nil)
    T.ok(err ~= nil)
  end)
  T.it("decodes netstring with colon in data", function()
    local data, rest = N.decode("5:a:b,c,")
    T.eq(data, "a:b,c")
    T.eq(rest, "")
  end)
end)

-- ========================
-- NETSTRING decode_all
-- ========================

T.describe("netstring decode_all", function()
  T.it("decodes multiple netstrings", function()
    local strings, rest = N.decode_all("5:hello,5:world,")
    T.eq(#strings, 2)
    T.eq(strings[1], "hello")
    T.eq(strings[2], "world")
    T.eq(rest, "")
  end)
  T.it("stops at incomplete netstring", function()
    local strings, rest = N.decode_all("5:hello,5:wor")
    T.eq(#strings, 1)
    T.eq(strings[1], "hello")
    T.eq(rest, "5:wor")
  end)
  T.it("handles empty buffer", function()
    local strings, rest = N.decode_all("")
    T.eq(#strings, 0)
    T.eq(rest, "")
  end)
  T.it("decodes single empty netstring", function()
    local strings, rest = N.decode_all("0:,")
    T.eq(#strings, 1)
    T.eq(strings[1], "")
    T.eq(rest, "")
  end)
end)

-- ========================
-- NETSTRING encode_all
-- ========================

T.describe("netstring encode_all", function()
  T.it("encodes multiple strings", function()
    local buf = N.encode_all({"hello", "world"})
    T.eq(buf, "5:hello,5:world,")
  end)
  T.it("encodes empty list", function()
    T.eq(N.encode_all({}), "")
  end)
  T.it("round-trips through decode_all", function()
    local strs = {"foo", "bar", "", "baz"}
    local buf = N.encode_all(strs)
    local decoded, rest = N.decode_all(buf)
    T.eq(#decoded, 4)
    T.eq(decoded[1], "foo")
    T.eq(decoded[2], "bar")
    T.eq(decoded[3], "")
    T.eq(decoded[4], "baz")
    T.eq(rest, "")
  end)
end)

-- ========================
-- STREAMING DECODER
-- ========================

T.describe("streaming decoder", function()
  T.it("decodes complete message in one feed", function()
    local d = N.decoder()
    local results, err = d:feed("5:hello,")
    T.eq(err, nil)
    T.eq(#results, 1)
    T.eq(results[1], "hello")
  end)
  T.it("decodes fragmented input across feeds", function()
    local d = N.decoder()
    local r1, _ = d:feed("5:he")
    T.eq(#r1, 0)
    local r2, _ = d:feed("llo,")
    T.eq(#r2, 1)
    T.eq(r2[1], "hello")
  end)
  T.it("returns multiple messages from one feed", function()
    local d = N.decoder()
    local results, err = d:feed("3:foo,3:bar,")
    T.eq(err, nil)
    T.eq(#results, 2)
    T.eq(results[1], "foo")
    T.eq(results[2], "bar")
  end)
  T.it("accumulates partial data across feeds", function()
    local d = N.decoder()
    d:feed("5:")
    d:feed("hel")
    local results, _ = d:feed("lo,3:end,")
    T.eq(#results, 2)
    T.eq(results[1], "hello")
    T.eq(results[2], "end")
  end)
  T.it("handles empty string netstring via streaming", function()
    local d = N.decoder()
    local results, err = d:feed("0:,")
    T.eq(err, nil)
    T.eq(#results, 1)
    T.eq(results[1], "")
  end)
end)

-- ========================
-- VARINT
-- ========================

T.describe("varint encode", function()
  T.it("encodes 0", function()
    T.eq(N.encode_varint(0), "\x00")
  end)
  T.it("encodes 1", function()
    T.eq(N.encode_varint(1), "\x01")
  end)
  T.it("encodes 127", function()
    T.eq(N.encode_varint(127), "\x7f")
  end)
  T.it("encodes 128 (two bytes)", function()
    T.eq(N.encode_varint(128), "\x80\x01")
  end)
  T.it("encodes 255", function()
    T.eq(N.encode_varint(255), "\xff\x01")
  end)
  T.it("encodes 300", function()
    T.eq(N.encode_varint(300), "\xac\x02")
  end)
  T.it("encodes 16383", function()
    T.eq(N.encode_varint(16383), "\xff\x7f")
  end)
  T.it("encodes 16384", function()
    T.eq(N.encode_varint(16384), "\x80\x80\x01")
  end)
end)

T.describe("varint decode", function()
  T.it("decodes 0", function()
    local v, pos = N.decode_varint("\x00", 1)
    T.eq(v, 0)
    T.eq(pos, 2)
  end)
  T.it("decodes 1", function()
    local v, _ = N.decode_varint("\x01", 1)
    T.eq(v, 1)
  end)
  T.it("decodes 127", function()
    local v, _ = N.decode_varint("\x7f", 1)
    T.eq(v, 127)
  end)
  T.it("decodes 128", function()
    local v, pos = N.decode_varint("\x80\x01", 1)
    T.eq(v, 128)
    T.eq(pos, 3)
  end)
  T.it("decodes 255", function()
    local v, _ = N.decode_varint("\xff\x01", 1)
    T.eq(v, 255)
  end)
  T.it("decodes 300", function()
    local v, _ = N.decode_varint("\xac\x02", 1)
    T.eq(v, 300)
  end)
  T.it("decodes 16383", function()
    local v, _ = N.decode_varint("\xff\x7f", 1)
    T.eq(v, 16383)
  end)
  T.it("decodes 16384", function()
    local v, pos = N.decode_varint("\x80\x80\x01", 1)
    T.eq(v, 16384)
    T.eq(pos, 4)
  end)
  T.it("error: buffer ends mid-varint", function()
    local v, err = N.decode_varint("\x80", 1)
    T.eq(v, nil)
    T.ok(err ~= nil)
  end)
  T.it("round-trips encode/decode for various values", function()
    for _, n in ipairs({0, 1, 63, 64, 127, 128, 255, 300, 1000, 16383, 16384}) do
      local encoded = N.encode_varint(n)
      local decoded, _ = N.decode_varint(encoded, 1)
      T.eq(decoded, n)
    end
  end)
end)

-- ========================
-- LENGTH-DELIMITED
-- ========================

T.describe("length-delimited framing", function()
  T.it("encodes and decodes round-trip", function()
    local encoded = N.ld_encode("hello")
    local data, pos = N.ld_decode(encoded, 1)
    T.eq(data, "hello")
    T.eq(pos, #encoded + 1)
  end)
  T.it("handles empty string", function()
    local encoded = N.ld_encode("")
    local data, pos = N.ld_decode(encoded, 1)
    T.eq(data, "")
    T.eq(pos, 2)
  end)
  T.it("handles binary data", function()
    local s = "\x00\x01\x02\xff"
    local encoded = N.ld_encode(s)
    local data, _ = N.ld_decode(encoded, 1)
    T.eq(data, s)
  end)
  T.it("decodes at offset within larger buffer", function()
    local buf = N.ld_encode("first") .. N.ld_encode("second")
    local d1, pos1 = N.ld_decode(buf, 1)
    T.eq(d1, "first")
    local d2, _ = N.ld_decode(buf, pos1)
    T.eq(d2, "second")
  end)
  T.it("error: buffer too short", function()
    local data, err = N.ld_decode("\x05hel", 1)
    T.eq(data, nil)
    T.ok(err ~= nil)
  end)
  T.it("round-trips large data (128+ bytes)", function()
    local s = string.rep("x", 200)
    local encoded = N.ld_encode(s)
    local data, _ = N.ld_decode(encoded, 1)
    T.eq(data, s)
    T.eq(#encoded, 2 + 200)  -- varint(200) = 2 bytes: \xc8\x01
  end)
end)

-- ========================
-- PACK / UNPACK
-- ========================

T.describe("pack_u8 / unpack_u8", function()
  T.it("packs 0", function()
    T.eq(N.pack_u8(0), "\x00")
  end)
  T.it("packs 255", function()
    T.eq(N.pack_u8(255), "\xff")
  end)
  T.it("round-trips 127", function()
    local v, pos = N.unpack_u8(N.pack_u8(127), 1)
    T.eq(v, 127)
    T.eq(pos, 2)
  end)
end)

T.describe("pack_u16 / unpack_u16", function()
  T.it("packs 0", function()
    T.eq(N.pack_u16(0), "\x00\x00")
  end)
  T.it("packs 256", function()
    T.eq(N.pack_u16(256), "\x01\x00")
  end)
  T.it("packs 65535 (max u16)", function()
    T.eq(N.pack_u16(65535), "\xff\xff")
  end)
  T.it("round-trips 1000", function()
    local v, pos = N.unpack_u16(N.pack_u16(1000), 1)
    T.eq(v, 1000)
    T.eq(pos, 3)
  end)
  T.it("round-trips max u16", function()
    local v, _ = N.unpack_u16(N.pack_u16(65535), 1)
    T.eq(v, 65535)
  end)
end)

T.describe("pack_u32 / unpack_u32", function()
  T.it("packs 0", function()
    T.eq(N.pack_u32(0), "\x00\x00\x00\x00")
  end)
  T.it("packs 65536", function()
    T.eq(N.pack_u32(65536), "\x00\x01\x00\x00")
  end)
  T.it("round-trips 100000", function()
    local v, pos = N.unpack_u32(N.pack_u32(100000), 1)
    T.eq(v, 100000)
    T.eq(pos, 5)
  end)
  T.it("round-trips max u16 value", function()
    local v, _ = N.unpack_u32(N.pack_u32(65535), 1)
    T.eq(v, 65535)
  end)
  T.it("round-trips large value (2^24)", function()
    local v, _ = N.unpack_u32(N.pack_u32(16777216), 1)
    T.eq(v, 16777216)
  end)
end)

T.describe("pack_i8 / unpack_i8", function()
  T.it("packs 0", function()
    T.eq(N.pack_i8(0), "\x00")
  end)
  T.it("packs 127", function()
    T.eq(N.pack_i8(127), "\x7f")
  end)
  T.it("packs -1", function()
    T.eq(N.pack_i8(-1), "\xff")
  end)
  T.it("packs -128 (min i8)", function()
    T.eq(N.pack_i8(-128), "\x80")
  end)
  T.it("round-trips -50", function()
    local v, _ = N.unpack_i8(N.pack_i8(-50), 1)
    T.eq(v, -50)
  end)
end)

T.describe("pack_i16 / unpack_i16", function()
  T.it("packs 0", function()
    T.eq(N.pack_i16(0), "\x00\x00")
  end)
  T.it("packs -1", function()
    T.eq(N.pack_i16(-1), "\xff\xff")
  end)
  T.it("packs -32768 (min i16)", function()
    T.eq(N.pack_i16(-32768), "\x80\x00")
  end)
  T.it("packs 32767 (max i16)", function()
    T.eq(N.pack_i16(32767), "\x7f\xff")
  end)
  T.it("round-trips -1000", function()
    local v, pos = N.unpack_i16(N.pack_i16(-1000), 1)
    T.eq(v, -1000)
    T.eq(pos, 3)
  end)
  T.it("round-trips min i16", function()
    local v, _ = N.unpack_i16(N.pack_i16(-32768), 1)
    T.eq(v, -32768)
  end)
end)

T.describe("pack_i32 / unpack_i32", function()
  T.it("packs 0", function()
    T.eq(N.pack_i32(0), "\x00\x00\x00\x00")
  end)
  T.it("packs -1", function()
    T.eq(N.pack_i32(-1), "\xff\xff\xff\xff")
  end)
  T.it("round-trips -1000000", function()
    local v, pos = N.unpack_i32(N.pack_i32(-1000000), 1)
    T.eq(v, -1000000)
    T.eq(pos, 5)
  end)
  T.it("round-trips -2147483648 (min i32)", function()
    local v, _ = N.unpack_i32(N.pack_i32(-2147483648), 1)
    T.eq(v, -2147483648)
  end)
  T.it("round-trips 2147483647 (max i32)", function()
    local v, _ = N.unpack_i32(N.pack_i32(2147483647), 1)
    T.eq(v, 2147483647)
  end)
end)

-- ========================
-- TLV
-- ========================

T.describe("TLV encode/decode 1-byte type, 1-byte length", function()
  T.it("encodes type=1, value=hello", function()
    local bytes, err = N.tlv_encode(1, "hello")
    T.eq(err, nil)
    T.eq(bytes, "\x01\x05hello")
  end)
  T.it("decodes type=1, value=hello", function()
    local t, v, pos, err = N.tlv_decode("\x01\x05hello", 1)
    T.eq(err, nil)
    T.eq(t, 1)
    T.eq(v, "hello")
    T.eq(pos, 8)
  end)
  T.it("round-trips type=255, value=data", function()
    local encoded, _ = N.tlv_encode(255, "data")
    local t, v, _, err = N.tlv_decode(encoded, 1)
    T.eq(err, nil)
    T.eq(t, 255)
    T.eq(v, "data")
  end)
  T.it("encodes/decodes empty value", function()
    local encoded, _ = N.tlv_encode(5, "")
    local t, v, pos, err = N.tlv_decode(encoded, 1)
    T.eq(err, nil)
    T.eq(t, 5)
    T.eq(v, "")
    T.eq(pos, 3)
  end)
end)

T.describe("TLV encode/decode 2-byte type", function()
  T.it("encodes and decodes 2-byte type tag", function()
    local encoded, err = N.tlv_encode(1000, "hello", {type_bytes=2})
    T.eq(err, nil)
    local t, v, _, derr = N.tlv_decode(encoded, 1, {type_bytes=2})
    T.eq(derr, nil)
    T.eq(t, 1000)
    T.eq(v, "hello")
  end)
  T.it("encodes 2-byte type=0x0102", function()
    local encoded, _ = N.tlv_encode(0x0102, "ab", {type_bytes=2})
    T.eq(string.byte(encoded, 1), 0x01)
    T.eq(string.byte(encoded, 2), 0x02)
  end)
end)

T.describe("TLV encode/decode 2-byte length", function()
  T.it("round-trips with 2-byte length field", function()
    local s = string.rep("x", 300)
    local encoded, err = N.tlv_encode(1, s, {length_bytes=2})
    T.eq(err, nil)
    local t, v, _, derr = N.tlv_decode(encoded, 1, {length_bytes=2})
    T.eq(derr, nil)
    T.eq(t, 1)
    T.eq(v, s)
  end)
end)

T.describe("TLV encode/decode 4-byte length", function()
  T.it("round-trips with 4-byte length field", function()
    local s = "binary data here"
    local encoded, err = N.tlv_encode(42, s, {length_bytes=4})
    T.eq(err, nil)
    local t, v, _, derr = N.tlv_decode(encoded, 1, {length_bytes=4})
    T.eq(derr, nil)
    T.eq(t, 42)
    T.eq(v, s)
  end)
end)

T.describe("TLV decode_all", function()
  T.it("decodes multiple TLV records", function()
    local buf = N.tlv_encode(1, "foo") .. N.tlv_encode(2, "bar") .. N.tlv_encode(3, "baz")
    local records, err = N.tlv_decode_all(buf)
    T.eq(err, nil)
    T.eq(#records, 3)
    T.eq(records[1][1], 1)
    T.eq(records[1][2], "foo")
    T.eq(records[2][1], 2)
    T.eq(records[2][2], "bar")
    T.eq(records[3][1], 3)
    T.eq(records[3][2], "baz")
  end)
  T.it("handles empty buffer", function()
    local records, err = N.tlv_decode_all("")
    T.eq(err, nil)
    T.eq(#records, 0)
  end)
  T.it("error on truncated buffer", function()
    local records, err = N.tlv_decode_all("\x01\x05hel")
    T.ok(err ~= nil)
  end)
end)

T.describe("TLV error cases", function()
  T.it("error: type tag out of range for 1-byte", function()
    local bytes, err = N.tlv_encode(256, "x")
    T.eq(bytes, nil)
    T.ok(err ~= nil)
  end)
  T.it("error: value too long for 1-byte length", function()
    local bytes, err = N.tlv_encode(1, string.rep("x", 256))
    T.eq(bytes, nil)
    T.ok(err ~= nil)
  end)
  T.it("error: invalid type_bytes", function()
    local bytes, err = N.tlv_encode(1, "x", {type_bytes=3})
    T.eq(bytes, nil)
    T.ok(err ~= nil)
  end)
  T.it("error: invalid length_bytes", function()
    local bytes, err = N.tlv_encode(1, "x", {length_bytes=3})
    T.eq(bytes, nil)
    T.ok(err ~= nil)
  end)
end)

-- ========================
-- EDGE CASES AND ROUND-TRIPS
-- ========================

T.describe("edge cases", function()
  T.it("netstring round-trip for various lengths", function()
    for _, s in ipairs({"", "a", "hello world", string.rep("x", 100)}) do
      local encoded = N.encode(s)
      local decoded, _ = N.decode(encoded)
      T.eq(decoded, s)
    end
  end)
  T.it("unpack_u16 at offset", function()
    local buf = "\x00\x00\x01\x02"
    local v, pos = N.unpack_u16(buf, 3)
    T.eq(v, 0x0102)
    T.eq(pos, 5)
  end)
  T.it("unpack_u32 at offset", function()
    local buf = "\x00\x00\x00\x00\x01\x02\x03\x04"
    local v, pos = N.unpack_u32(buf, 5)
    T.eq(v, 0x01020304)
    T.eq(pos, 9)
  end)
  T.it("TLV 2-byte type + 4-byte length round-trip", function()
    local opts = {type_bytes=2, length_bytes=4}
    local s = "complex data"
    local encoded, _ = N.tlv_encode(0x1234, s, opts)
    local t, v, _, err = N.tlv_decode(encoded, 1, opts)
    T.eq(err, nil)
    T.eq(t, 0x1234)
    T.eq(v, s)
  end)
  T.it("varint round-trips large value", function()
    local n = 2097151  -- 3-byte varint max (21 bits)
    local enc = N.encode_varint(n)
    local dec, _ = N.decode_varint(enc, 1)
    T.eq(dec, n)
  end)
end)
