if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local units = require("lib.units")

local function approx(a, b, eps)
  T.ok(math.abs(a - b) < (eps or 1e-6),
    "expected " .. tostring(a) .. " ≈ " .. tostring(b))
end

T.describe("lib.units", function()

  T.describe("tier", function()
    T.it("M._tier is pure", function()
      T.eq(units._tier, "pure")
    end)
  end)

  T.describe("length conversions", function()
    T.it("1 km = 1000 m", function()
      local v, err = units.convert(1, "km", "m")
      T.eq(err, nil)
      approx(v, 1000)
    end)
    T.it("1000 m = 1 km", function()
      local v = units.convert(1000, "m", "km")
      approx(v, 1)
    end)
    T.it("1 mile ≈ 1.609344 km", function()
      local v = units.convert(1, "mi", "km")
      approx(v, 1.609344, 1e-5)
    end)
    T.it("1 inch = 2.54 cm", function()
      local v = units.convert(1, "in", "cm")
      approx(v, 2.54, 1e-10)
    end)
    T.it("1 foot = 12 inches", function()
      local v = units.convert(1, "ft", "in")
      approx(v, 12, 1e-9)
    end)
    T.it("1 yard = 3 feet", function()
      local v = units.convert(1, "yd", "ft")
      approx(v, 3, 1e-9)
    end)
    T.it("1 nautical mile = 1852 m", function()
      local v = units.convert(1, "nmi", "m")
      approx(v, 1852)
    end)
    T.it("light year in meters (approximate)", function()
      local v = units.convert(1, "ly", "m")
      approx(v, 9.461e15, 1e12)
    end)
    T.it("alias: meter == m", function()
      local v = units.convert(1, "meter", "m")
      approx(v, 1)
    end)
    T.it("alias: kilometers == km", function()
      local v = units.convert(2, "kilometers", "m")
      approx(v, 2000)
    end)
  end)

  T.describe("mass", function()
    T.it("1 kg ≈ 2.20462 lb", function()
      local v = units.convert(1, "kg", "lb")
      approx(v, 2.20462, 1e-4)
    end)
    T.it("1 lb ≈ 453.592 g", function()
      local v = units.convert(1, "lb", "g")
      approx(v, 453.592, 1e-3)
    end)
    T.it("1 oz ≈ 28.3495 g", function()
      local v = units.convert(1, "oz", "g")
      approx(v, 28.3495, 1e-3)
    end)
    T.it("1 tonne = 1000 kg", function()
      local v = units.convert(1, "tonne", "kg")
      approx(v, 1000)
    end)
    T.it("1 stone ≈ 6.35029 kg", function()
      local v = units.convert(1, "stone", "kg")
      approx(v, 6.35029, 1e-4)
    end)
  end)

  T.describe("time", function()
    T.it("1 hour = 3600 seconds", function()
      local v = units.convert(1, "h", "s")
      approx(v, 3600)
    end)
    T.it("1 hour = 60 minutes", function()
      local v = units.convert(1, "hr", "min")
      approx(v, 60)
    end)
    T.it("1 day = 24 hours", function()
      local v = units.convert(1, "day", "h")
      approx(v, 24)
    end)
    T.it("1 week = 7 days", function()
      local v = units.convert(1, "wk", "d")
      approx(v, 7)
    end)
    T.it("1 year ≈ 365.25 days (Julian year)", function()
      local v = units.convert(1, "yr", "d")
      approx(v, 365.25, 1e-9)
    end)
    T.it("1000 ms = 1 s", function()
      local v = units.convert(1000, "ms", "s")
      approx(v, 1)
    end)
  end)

  T.describe("temperature", function()
    T.it("0°C = 32°F", function()
      local v = units.convert(0, "C", "F")
      approx(v, 32)
    end)
    T.it("100°C = 212°F", function()
      local v = units.convert(100, "C", "F")
      approx(v, 212)
    end)
    T.it("0°C = 273.15 K", function()
      local v = units.convert(0, "C", "K")
      approx(v, 273.15)
    end)
    T.it("-40°C = -40°F (crossover)", function()
      local v = units.convert(-40, "C", "F")
      approx(v, -40)
    end)
    T.it("0 K = -273.15°C", function()
      local v = units.convert(0, "K", "C")
      approx(v, -273.15)
    end)
    T.it("212°F = 100°C", function()
      local v = units.convert(212, "F", "C")
      approx(v, 100, 1e-10)
    end)
    T.it("32°F = 273.15 K", function()
      local v = units.convert(32, "F", "K")
      approx(v, 273.15, 1e-10)
    end)
    T.it("0 R = -273.15°C (approximately)", function()
      local v = units.convert(491.67, "R", "C")
      approx(v, 0, 1e-4)
    end)
    T.it("alias: celsius == C", function()
      local v = units.convert(100, "celsius", "fahrenheit")
      approx(v, 212, 1e-10)
    end)
    T.it("alias: degC / degF", function()
      local v = units.convert(0, "degC", "degF")
      approx(v, 32)
    end)
  end)

  T.describe("area", function()
    T.it("1 km2 = 1e6 m2", function()
      local v = units.convert(1, "km2", "m2")
      approx(v, 1e6)
    end)
    T.it("1 hectare = 10000 m2", function()
      local v = units.convert(1, "ha", "m2")
      approx(v, 10000)
    end)
    T.it("1 acre ≈ 4046.86 m2", function()
      local v = units.convert(1, "acre", "m2")
      approx(v, 4046.86, 0.01)
    end)
    T.it("1 ft2 ≈ 0.092903 m2", function()
      local v = units.convert(1, "ft2", "m2")
      approx(v, 0.092903, 1e-6)
    end)
  end)

  T.describe("volume", function()
    T.it("1 L = 1000 mL", function()
      local v = units.convert(1, "L", "mL")
      approx(v, 1000)
    end)
    T.it("1 US gallon ≈ 3.78541 L", function()
      local v = units.convert(1, "gal", "L")
      approx(v, 3.78541, 1e-5)
    end)
    T.it("1 m3 = 1000 L", function()
      local v = units.convert(1, "m3", "L")
      approx(v, 1000)
    end)
    T.it("1 ft3 ≈ 28.3168 L", function()
      local v = units.convert(1, "ft3", "L")
      approx(v, 28.3168, 1e-4)
    end)
    T.it("1 tbsp = 3 tsp (approximately)", function()
      local v = units.convert(1, "tbsp", "tsp")
      approx(v, 3, 1e-4)
    end)
    T.it("alias: liter == L", function()
      local v = units.convert(1, "liter", "mL")
      approx(v, 1000)
    end)
  end)

  T.describe("speed", function()
    T.it("1 m/s = 3.6 km/h", function()
      local v = units.convert(1, "m/s", "km/h")
      approx(v, 3.6, 1e-10)
    end)
    T.it("1 mph ≈ 0.44704 m/s", function()
      local v = units.convert(1, "mph", "m/s")
      approx(v, 0.44704, 1e-10)
    end)
    T.it("1 knot ≈ 1.852 km/h", function()
      local v = units.convert(1, "knot", "km/h")
      approx(v, 1.852, 1e-4)
    end)
    T.it("alias: kph == km/h", function()
      local v = units.convert(1, "kph", "m/s")
      approx(v, 1/3.6, 1e-10)
    end)
  end)

  T.describe("pressure", function()
    T.it("1 atm = 101325 Pa", function()
      local v = units.convert(1, "atm", "Pa")
      approx(v, 101325)
    end)
    T.it("1 bar = 100000 Pa", function()
      local v = units.convert(1, "bar", "Pa")
      approx(v, 1e5)
    end)
    T.it("1 psi ≈ 6894.76 Pa", function()
      local v = units.convert(1, "psi", "Pa")
      approx(v, 6894.76, 0.01)
    end)
    T.it("1 mmHg = 133.322 Pa", function()
      local v = units.convert(1, "mmHg", "Pa")
      approx(v, 133.322, 1e-3)
    end)
  end)

  T.describe("energy", function()
    T.it("1 kJ = 1000 J", function()
      local v = units.convert(1, "kJ", "J")
      approx(v, 1000)
    end)
    T.it("1 kcal = 4184 J", function()
      local v = units.convert(1, "kcal", "J")
      approx(v, 4184)
    end)
    T.it("1 kWh = 3.6e6 J", function()
      local v = units.convert(1, "kWh", "J")
      approx(v, 3.6e6)
    end)
    T.it("1 BTU ≈ 1055.06 J", function()
      local v = units.convert(1, "BTU", "J")
      approx(v, 1055.06, 0.01)
    end)
  end)

  T.describe("digital storage", function()
    T.it("1 KB = 1024 bytes", function()
      local v = units.convert(1, "KB", "B")
      approx(v, 1024)
    end)
    T.it("1 MB = 1024 KB", function()
      local v = units.convert(1, "MB", "KB")
      approx(v, 1024)
    end)
    T.it("1 GB = 1024 MB", function()
      local v = units.convert(1, "GB", "MB")
      approx(v, 1024)
    end)
    T.it("1 byte = 8 bits", function()
      local v = units.convert(1, "B", "b")
      approx(v, 8)
    end)
    T.it("1 TB = 1024 GB", function()
      local v = units.convert(1, "TB", "GB")
      approx(v, 1024)
    end)
  end)

  T.describe("angle", function()
    T.it("180 degrees = π radians", function()
      local v = units.convert(180, "deg", "rad")
      approx(v, math.pi, 1e-12)
    end)
    T.it("π radians = 180 degrees", function()
      local v = units.convert(math.pi, "rad", "deg")
      approx(v, 180, 1e-10)
    end)
    T.it("1 turn = 360 degrees", function()
      local v = units.convert(1, "turn", "deg")
      approx(v, 360, 1e-10)
    end)
    T.it("1 turn = 2π radians", function()
      local v = units.convert(1, "turn", "rad")
      approx(v, 2 * math.pi, 1e-12)
    end)
    T.it("90 degrees = 100 grads", function()
      local v = units.convert(90, "deg", "grad")
      approx(v, 100, 1e-9)
    end)
    T.it("1 degree = 60 arcminutes", function()
      local v = units.convert(1, "deg", "arcmin")
      approx(v, 60, 1e-9)
    end)
    T.it("1 arcmin = 60 arcseconds", function()
      local v = units.convert(1, "arcmin", "arcsec")
      approx(v, 60, 1e-9)
    end)
  end)

  T.describe("parse", function()
    T.it("'5 km' → {value=5, unit='km'}", function()
      local r, err = units.parse("5 km")
      T.eq(err, nil)
      T.eq(r.value, 5)
      T.eq(r.unit, "km")
    end)
    T.it("'72 F' → temperature", function()
      local r, err = units.parse("72 F")
      T.eq(err, nil)
      T.eq(r.value, 72)
      T.eq(r.unit, "F")
    end)
    T.it("'72°F' (with degree sign) → temperature", function()
      local r, err = units.parse("72°F")
      T.eq(err, nil)
      T.eq(r.value, 72)
      T.eq(r.unit, "F")
    end)
    T.it("'3.14 rad' → angle", function()
      local r, err = units.parse("3.14 rad")
      T.eq(err, nil)
      approx(r.value, 3.14)
      T.eq(r.unit, "rad")
    end)
    T.it("'1e3 m' → length", function()
      local r, err = units.parse("1e3 m")
      T.eq(err, nil)
      approx(r.value, 1000)
      T.eq(r.unit, "m")
    end)
    T.it("'2.5kg' (no space) → mass", function()
      local r, err = units.parse("2.5kg")
      T.eq(err, nil)
      approx(r.value, 2.5)
      T.eq(r.unit, "kg")
    end)
    T.it("unknown unit returns error", function()
      local r, err = units.parse("5 xyz")
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
    T.it("unparseable string returns error", function()
      local r, err = units.parse("hello world")
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
    T.it("leading/trailing whitespace is stripped", function()
      local r, err = units.parse("  10 m  ")
      T.eq(err, nil)
      T.eq(r.value, 10)
      T.eq(r.unit, "m")
    end)
  end)

  T.describe("format", function()
    T.it("default precision=2, space=true", function()
      local s = units.format(5, "km")
      T.eq(s, "5.00 km")
    end)
    T.it("precision=0", function()
      local s = units.format(5.7, "m", { precision = 0 })
      T.eq(s, "6 m")
    end)
    T.it("precision=4", function()
      local s = units.format(3.14159, "rad", { precision = 4 })
      T.eq(s, "3.1416 rad")
    end)
    T.it("space=false", function()
      local s = units.format(100, "C", { space = false })
      T.eq(s, "100.00C")
    end)
    T.it("negative value", function()
      local s = units.format(-40, "F")
      T.eq(s, "-40.00 F")
    end)
  end)

  T.describe("list / categories / known", function()
    T.it("list('length') contains 'm' and 'km'", function()
      local lst = units.list("length")
      local has_m, has_km = false, false
      for _, u in ipairs(lst) do
        if u == "m" then has_m = true end
        if u == "km" then has_km = true end
      end
      T.ok(has_m, "list('length') should contain 'm'")
      T.ok(has_km, "list('length') should contain 'km'")
    end)
    T.it("list('temperature') contains 'C', 'F', 'K'", function()
      local lst = units.list("temperature")
      local found = {}
      for _, u in ipairs(lst) do found[u] = true end
      T.ok(found["C"])
      T.ok(found["F"])
      T.ok(found["K"])
    end)
    T.it("list returns sorted array", function()
      local lst = units.list("mass")
      T.ok(#lst > 0)
      for i = 2, #lst do
        T.ok(lst[i-1] <= lst[i], "list should be sorted")
      end
    end)
    T.it("list of unknown category returns nil + errmsg", function()
      local r, err = units.list("unknown_category")
      T.eq(r, nil)
      T.ok(err ~= nil)
    end)
    T.it("categories() returns array including expected names", function()
      local cats = units.categories()
      local found = {}
      for _, c in ipairs(cats) do found[c] = true end
      T.ok(found["length"])
      T.ok(found["mass"])
      T.ok(found["temperature"])
      T.ok(found["time"])
      T.ok(found["energy"])
      T.ok(found["digital_storage"])
      T.ok(found["angle"])
    end)
    T.it("known('km') == true", function()
      T.ok(units.known("km"))
    end)
    T.it("known('xyz') == false", function()
      T.ok(not units.known("xyz"))
    end)
    T.it("known('C') == true", function()
      T.ok(units.known("C"))
    end)
  end)

  T.describe("errors", function()
    T.it("unknown from_unit returns nil + errmsg", function()
      local v, err = units.convert(1, "furlongs", "m")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("unknown to_unit returns nil + errmsg", function()
      local v, err = units.convert(1, "m", "furlongs")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("cross-category conversion returns nil + errmsg", function()
      local v, err = units.convert(1, "km", "kg")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("cross-category temperature → length is an error", function()
      local v, err = units.convert(100, "C", "m")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
    T.it("non-number value returns nil + errmsg", function()
      local v, err = units.convert("five", "km", "m")
      T.eq(v, nil)
      T.ok(err ~= nil)
    end)
  end)

end)
