if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local doc_registry = require("lib.platform.apps.finance.doc_registry")

T.describe("finance.doc_registry", function()

  T.describe("M.new", function()
    T.it("creates a registry with an accounts doc", function()
      local reg = doc_registry.new({ client_id = 1 })
      local accounts_doc = doc_registry.accounts_doc(reg)
      T.ok(accounts_doc ~= nil)
      T.eq(accounts_doc.client_id, 1)
    end)

    T.it("works with no opts at all", function()
      local reg = doc_registry.new()
      T.ok(doc_registry.accounts_doc(reg) ~= nil)
    end)

    T.it("starts with no registered periods", function()
      local reg = doc_registry.new({ client_id = 1 })
      T.eq(#doc_registry.list_periods(reg), 0)
    end)

    T.it("starts with no active period", function()
      local reg = doc_registry.new({ client_id = 1 })
      T.eq(doc_registry.active_period(reg), nil)
    end)
  end)

  T.describe("M.get_or_create_period", function()
    T.it("creates a new period doc on first call", function()
      local reg = doc_registry.new({ client_id = 1 })
      local d, err = doc_registry.get_or_create_period(reg, "2026-Q3")
      T.ok(d ~= nil, err)
    end)

    T.it("returns the same doc on repeated calls for the same period_id", function()
      local reg = doc_registry.new({ client_id = 1 })
      local d1 = doc_registry.get_or_create_period(reg, "2026-Q3")
      local d2 = doc_registry.get_or_create_period(reg, "2026-Q3")
      T.eq(d1, d2)
    end)

    T.it("returns distinct docs for distinct period_ids", function()
      local reg = doc_registry.new({ client_id = 1 })
      local d1 = doc_registry.get_or_create_period(reg, "2026-Q3")
      local d2 = doc_registry.get_or_create_period(reg, "2026-Q4")
      T.ok(d1 ~= d2)
    end)

    T.it("rejects an empty period_id", function()
      local reg = doc_registry.new({ client_id = 1 })
      local d, err = doc_registry.get_or_create_period(reg, "")
      T.eq(d, nil)
      T.ok(type(err) == "string")
    end)
  end)

  T.describe("M.add_period / M.list_periods", function()
    T.it("registers a period visible via list_periods", function()
      local reg = doc_registry.new({ client_id = 1 })
      local ok, err = doc_registry.add_period(reg, "2026-Q3", { start_date = "2026-07-01", end_date = "2026-09-30" })
      T.ok(ok, err)

      local periods = doc_registry.list_periods(reg)
      T.eq(#periods, 1)
      T.eq(periods[1].id, "2026-Q3")
      T.eq(periods[1].start_date, "2026-07-01")
      T.eq(periods[1].end_date, "2026-09-30")
    end)

    T.it("rejects registering the same period_id twice", function()
      local reg = doc_registry.new({ client_id = 1 })
      doc_registry.add_period(reg, "2026-Q3", { start_date = "2026-07-01", end_date = "2026-09-30" })
      local ok, err = doc_registry.add_period(reg, "2026-Q3", { start_date = "2026-01-01", end_date = "2026-01-31" })
      T.eq(ok, nil)
      T.ok(type(err) == "string")
    end)

    T.it("rejects an empty period_id", function()
      local reg = doc_registry.new({ client_id = 1 })
      local ok, err = doc_registry.add_period(reg, "", { start_date = "2026-01-01", end_date = "2026-01-31" })
      T.eq(ok, nil)
      T.ok(type(err) == "string")
    end)

    T.it("lists multiple registered periods", function()
      local reg = doc_registry.new({ client_id = 1 })
      doc_registry.add_period(reg, "2026-Q3", { start_date = "2026-07-01", end_date = "2026-09-30" })
      doc_registry.add_period(reg, "2026-Q4", { start_date = "2026-10-01", end_date = "2026-12-31" })
      local periods = doc_registry.list_periods(reg)
      T.eq(#periods, 2)
    end)
  end)

  T.describe("M.active_period / M.set_active_period", function()
    T.it("sets and reads back the active period", function()
      local reg = doc_registry.new({ client_id = 1 })
      doc_registry.add_period(reg, "2026-Q3", { start_date = "2026-07-01", end_date = "2026-09-30" })
      local ok, err = doc_registry.set_active_period(reg, "2026-Q3")
      T.ok(ok, err)
      T.eq(doc_registry.active_period(reg), "2026-Q3")
    end)

    T.it("overwrites a previously-set active period", function()
      local reg = doc_registry.new({ client_id = 1 })
      doc_registry.set_active_period(reg, "2026-Q3")
      doc_registry.set_active_period(reg, "2026-Q4")
      T.eq(doc_registry.active_period(reg), "2026-Q4")
    end)

    T.it("rejects an empty period_id", function()
      local reg = doc_registry.new({ client_id = 1 })
      local ok, err = doc_registry.set_active_period(reg, "")
      T.eq(ok, nil)
      T.ok(type(err) == "string")
    end)
  end)

end)
