if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.calendar")

T.describe("lib.calendar", function()

  T.describe("M.date construction", function()
    T.it("creates a valid date", function()
      local d, err = M.date(2024, 3, 15)
      T.ok(d ~= nil, "date created")
      T.ok(err == nil, "no error")
      T.eq(d.year, 2024)
      T.eq(d.month, 3)
      T.eq(d.day, 15)
    end)

    T.it("rejects invalid month 0", function()
      local d, err = M.date(2024, 0, 1)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("rejects invalid month 13", function()
      local d, err = M.date(2024, 13, 1)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("rejects day 0", function()
      local d, err = M.date(2024, 1, 0)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("rejects day 32", function()
      local d, err = M.date(2024, 1, 32)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("allows Feb 29 on leap year", function()
      local d, err = M.date(2024, 2, 29)
      T.ok(d ~= nil, "Feb 29 2024 is valid")
      T.eq(err, nil)
    end)

    T.it("rejects Feb 29 on non-leap year", function()
      local d, err = M.date(2023, 2, 29)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("allows Feb 28 on non-leap year", function()
      local d, err = M.date(2023, 2, 28)
      T.ok(d ~= nil, "Feb 28 2023 is valid")
      T.eq(err, nil)
    end)

    T.it("rejects Feb 29 on year 1900 (no leap)", function()
      local d, err = M.date(1900, 2, 29)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("allows Feb 29 on year 2000 (leap)", function()
      local d, err = M.date(2000, 2, 29)
      T.ok(d ~= nil, "Feb 29 2000 is valid")
      T.eq(err, nil)
    end)
  end)

  T.describe("to_ordinal / from_ordinal", function()
    T.it("0001-01-01 = ordinal 1", function()
      local d = M.date(1, 1, 1)
      T.eq(d:to_ordinal(), 1)
    end)

    T.it("round-trip 2024-01-01", function()
      local d = M.date(2024, 1, 1)
      local ord = d:to_ordinal()
      local d2 = M.from_ordinal(ord)
      T.eq(d2.year, 2024)
      T.eq(d2.month, 1)
      T.eq(d2.day, 1)
    end)

    T.it("round-trip 2000-02-29", function()
      local d = M.date(2000, 2, 29)
      local ord = d:to_ordinal()
      local d2 = M.from_ordinal(ord)
      T.eq(d2.year, 2000)
      T.eq(d2.month, 2)
      T.eq(d2.day, 29)
    end)

    T.it("round-trip 1900-03-01", function()
      local d = M.date(1900, 3, 1)
      local ord = d:to_ordinal()
      local d2 = M.from_ordinal(ord)
      T.eq(d2.year, 1900)
      T.eq(d2.month, 3)
      T.eq(d2.day, 1)
    end)

    T.it("round-trip 2024-12-31", function()
      local d = M.date(2024, 12, 31)
      local ord = d:to_ordinal()
      local d2 = M.from_ordinal(ord)
      T.eq(d2.year, 2024)
      T.eq(d2.month, 12)
      T.eq(d2.day, 31)
    end)

    T.it("consecutive ordinals differ by 1", function()
      local d1 = M.date(2024, 1, 31)
      local d2 = M.date(2024, 2, 1)
      T.eq(d2:to_ordinal() - d1:to_ordinal(), 1)
    end)
  end)

  T.describe("to_iso / from_iso", function()
    T.it("to_iso formats correctly", function()
      local d = M.date(2024, 3, 5)
      T.eq(d:to_iso(), "2024-03-05")
    end)

    T.it("to_iso pads single digits", function()
      local d = M.date(9, 1, 7)
      T.eq(d:to_iso(), "0009-01-07")
    end)

    T.it("from_iso parses correctly", function()
      local d, err = M.from_iso("2024-03-15")
      T.ok(d ~= nil)
      T.eq(err, nil)
      T.eq(d.year, 2024)
      T.eq(d.month, 3)
      T.eq(d.day, 15)
    end)

    T.it("from_iso round-trip", function()
      local d = M.date(2000, 12, 31)
      local d2 = M.from_iso(d:to_iso())
      T.eq(d2.year, d.year)
      T.eq(d2.month, d.month)
      T.eq(d2.day, d.day)
    end)

    T.it("from_iso rejects invalid format", function()
      local d, err = M.from_iso("20240315")
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("from_iso rejects non-string", function()
      local d, err = M.from_iso(12345)
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("from_iso rejects bad date", function()
      local d, err = M.from_iso("2023-02-29")
      T.eq(d, nil)
      T.ok(err ~= nil, "has error")
    end)

    T.it("__tostring equals to_iso", function()
      local d = M.date(2024, 6, 15)
      T.eq(tostring(d), d:to_iso())
    end)
  end)

  T.describe("day_of_week", function()
    -- 2024-01-01 is Monday
    T.it("2024-01-01 is Monday (1)", function()
      local d = M.date(2024, 1, 1)
      T.eq(d:day_of_week(), 1)
    end)

    T.it("2024-01-06 is Saturday (6)", function()
      local d = M.date(2024, 1, 6)
      T.eq(d:day_of_week(), 6)
    end)

    T.it("2024-01-07 is Sunday (7)", function()
      local d = M.date(2024, 1, 7)
      T.eq(d:day_of_week(), 7)
    end)

    T.it("2024-03-31 is Easter Sunday (7)", function()
      -- 2024-03-31 = Sunday
      local d = M.date(2024, 3, 31)
      T.eq(d:day_of_week(), 7)
    end)
  end)

  T.describe("day_of_year", function()
    T.it("Jan 1 = 1", function()
      local d = M.date(2024, 1, 1)
      T.eq(d:day_of_year(), 1)
    end)

    T.it("Jan 31 = 31", function()
      local d = M.date(2024, 1, 31)
      T.eq(d:day_of_year(), 31)
    end)

    T.it("Feb 28 non-leap = 59", function()
      local d = M.date(2023, 2, 28)
      T.eq(d:day_of_year(), 59)
    end)

    T.it("Dec 31 leap = 366", function()
      local d = M.date(2024, 12, 31)
      T.eq(d:day_of_year(), 366)
    end)

    T.it("Dec 31 non-leap = 365", function()
      local d = M.date(2023, 12, 31)
      T.eq(d:day_of_year(), 365)
    end)
  end)

  T.describe("is_leap_year", function()
    T.it("2000 is leap", function()
      T.ok(M.date(2000, 1, 1):is_leap_year())
    end)

    T.it("1900 is not leap", function()
      T.ok(not M.date(1900, 1, 1):is_leap_year())
    end)

    T.it("2024 is leap", function()
      T.ok(M.date(2024, 1, 1):is_leap_year())
    end)

    T.it("2023 is not leap", function()
      T.ok(not M.date(2023, 1, 1):is_leap_year())
    end)

    T.it("2100 is not leap", function()
      T.ok(not M.date(2100, 1, 1):is_leap_year())
    end)
  end)

  T.describe("days_in_month", function()
    T.it("Jan has 31 days", function()
      T.eq(M.date(2024, 1, 1):days_in_month(), 31)
    end)

    T.it("Feb has 29 days in leap year", function()
      T.eq(M.date(2024, 2, 1):days_in_month(), 29)
    end)

    T.it("Feb has 28 days in non-leap year", function()
      T.eq(M.date(2023, 2, 1):days_in_month(), 28)
    end)

    T.it("Apr has 30 days", function()
      T.eq(M.date(2024, 4, 1):days_in_month(), 30)
    end)
  end)

  T.describe("add_days", function()
    T.it("add 1 day", function()
      local d = M.date(2024, 1, 31):add_days(1)
      T.eq(d.year, 2024)
      T.eq(d.month, 2)
      T.eq(d.day, 1)
    end)

    T.it("add negative days", function()
      local d = M.date(2024, 3, 1):add_days(-1)
      T.eq(d.year, 2024)
      T.eq(d.month, 2)
      T.eq(d.day, 29)  -- 2024 is leap
    end)

    T.it("add 365 days to non-leap year", function()
      local d = M.date(2023, 1, 1):add_days(365)
      T.eq(d.year, 2024)
      T.eq(d.month, 1)
      T.eq(d.day, 1)
    end)

    T.it("add 366 days to leap year", function()
      local d = M.date(2024, 1, 1):add_days(366)
      T.eq(d.year, 2025)
      T.eq(d.month, 1)
      T.eq(d.day, 1)
    end)
  end)

  T.describe("add_months", function()
    T.it("add 1 month normal", function()
      local d = M.date(2024, 3, 15):add_months(1)
      T.eq(d.year, 2024)
      T.eq(d.month, 4)
      T.eq(d.day, 15)
    end)

    T.it("Jan 31 + 1 month = Feb 28 (non-leap)", function()
      local d = M.date(2023, 1, 31):add_months(1)
      T.eq(d.year, 2023)
      T.eq(d.month, 2)
      T.eq(d.day, 28)
    end)

    T.it("Jan 31 + 1 month = Feb 29 (leap)", function()
      local d = M.date(2024, 1, 31):add_months(1)
      T.eq(d.year, 2024)
      T.eq(d.month, 2)
      T.eq(d.day, 29)
    end)

    T.it("add 12 months = same date next year", function()
      local d = M.date(2024, 6, 15):add_months(12)
      T.eq(d.year, 2025)
      T.eq(d.month, 6)
      T.eq(d.day, 15)
    end)

    T.it("add months crossing year boundary", function()
      local d = M.date(2024, 11, 30):add_months(3)
      T.eq(d.year, 2025)
      T.eq(d.month, 2)
      T.eq(d.day, 28)
    end)

    T.it("subtract months", function()
      local d = M.date(2024, 3, 15):add_months(-1)
      T.eq(d.year, 2024)
      T.eq(d.month, 2)
      T.eq(d.day, 15)
    end)
  end)

  T.describe("add_years", function()
    T.it("add 1 year", function()
      local d = M.date(2024, 6, 15):add_years(1)
      T.eq(d.year, 2025)
      T.eq(d.month, 6)
      T.eq(d.day, 15)
    end)

    T.it("Feb 29 + 1 year = Feb 28", function()
      local d = M.date(2024, 2, 29):add_years(1)
      T.eq(d.year, 2025)
      T.eq(d.month, 2)
      T.eq(d.day, 28)
    end)

    T.it("Feb 29 + 4 years = Feb 29 (next leap)", function()
      local d = M.date(2024, 2, 29):add_years(4)
      T.eq(d.year, 2028)
      T.eq(d.month, 2)
      T.eq(d.day, 29)
    end)
  end)

  T.describe("diff_days", function()
    T.it("same date = 0", function()
      local d = M.date(2024, 6, 15)
      T.eq(d:diff_days(d), 0)
    end)

    T.it("one day apart", function()
      local d1 = M.date(2024, 1, 2)
      local d2 = M.date(2024, 1, 1)
      T.eq(d1:diff_days(d2), 1)
    end)

    T.it("negative diff", function()
      local d1 = M.date(2024, 1, 1)
      local d2 = M.date(2024, 1, 10)
      T.eq(d1:diff_days(d2), -9)
    end)

    T.it("year boundary", function()
      local d1 = M.date(2024, 1, 1)
      local d2 = M.date(2023, 12, 31)
      T.eq(d1:diff_days(d2), 1)
    end)
  end)

  T.describe("metamethods", function()
    T.it("subtraction returns days", function()
      local d1 = M.date(2024, 1, 10)
      local d2 = M.date(2024, 1, 1)
      T.eq(d1 - d2, 9)
    end)

    T.it("equality", function()
      local d1 = M.date(2024, 6, 15)
      local d2 = M.date(2024, 6, 15)
      T.ok(d1 == d2)
    end)

    T.it("inequality", function()
      local d1 = M.date(2024, 6, 15)
      local d2 = M.date(2024, 6, 16)
      T.ok(not (d1 == d2))
    end)

    T.it("less than", function()
      local d1 = M.date(2024, 1, 1)
      local d2 = M.date(2024, 1, 2)
      T.ok(d1 < d2)
      T.ok(not (d2 < d1))
    end)

    T.it("less than or equal", function()
      local d1 = M.date(2024, 1, 1)
      local d2 = M.date(2024, 1, 1)
      T.ok(d1 <= d2)
      T.ok(d2 <= d1)
    end)

    T.it("less-than across year", function()
      local d1 = M.date(2023, 12, 31)
      local d2 = M.date(2024, 1, 1)
      T.ok(d1 < d2)
    end)
  end)

  T.describe("M.range", function()
    T.it("collects 5 dates", function()
      local dates = {}
      for d in M.range(M.date(2024, 1, 1), M.date(2024, 1, 5)) do
        dates[#dates + 1] = d:to_iso()
      end
      T.eq(#dates, 5)
      T.eq(dates[1], "2024-01-01")
      T.eq(dates[5], "2024-01-05")
    end)

    T.it("step 2 yields correct dates", function()
      local dates = {}
      for d in M.range(M.date(2024, 1, 1), M.date(2024, 1, 7), 2) do
        dates[#dates + 1] = d:to_iso()
      end
      T.eq(#dates, 4)
      T.eq(dates[1], "2024-01-01")
      T.eq(dates[2], "2024-01-03")
      T.eq(dates[3], "2024-01-05")
      T.eq(dates[4], "2024-01-07")
    end)

    T.it("single date range", function()
      local dates = {}
      for d in M.range(M.date(2024, 6, 1), M.date(2024, 6, 1)) do
        dates[#dates + 1] = d:to_iso()
      end
      T.eq(#dates, 1)
    end)

    T.it("range crossing month boundary", function()
      local dates = {}
      for d in M.range(M.date(2024, 1, 29), M.date(2024, 2, 2)) do
        dates[#dates + 1] = d:to_iso()
      end
      T.eq(#dates, 5)
      T.eq(dates[3], "2024-01-31")
      T.eq(dates[4], "2024-02-01")
    end)
  end)

  T.describe("M.recur daily", function()
    T.it("take 3 daily from 2024-01-01", function()
      local r = M.recur({start = M.date(2024, 1, 1), freq = "daily", count = 3})
      local dates = r:take(3)
      T.eq(#dates, 3)
      T.eq(dates[1]:to_iso(), "2024-01-01")
      T.eq(dates[2]:to_iso(), "2024-01-02")
      T.eq(dates[3]:to_iso(), "2024-01-03")
    end)

    T.it("count limits iteration", function()
      local r = M.recur({start = M.date(2024, 1, 1), freq = "daily", count = 5})
      local all = r:all()
      T.eq(#all, 5)
    end)

    T.it("until limits iteration", function()
      local r = M.recur({
        start = M.date(2024, 1, 1),
        freq = "daily",
        ["until"] = M.date(2024, 1, 7)
      })
      local all = r:all()
      T.eq(#all, 7)
      T.eq(all[7]:to_iso(), "2024-01-07")
    end)

    T.it("interval=2 yields every other day", function()
      local r = M.recur({start = M.date(2024, 1, 1), freq = "daily", interval = 2, count = 3})
      local dates = r:take(3)
      T.eq(dates[1]:to_iso(), "2024-01-01")
      T.eq(dates[2]:to_iso(), "2024-01-03")
      T.eq(dates[3]:to_iso(), "2024-01-05")
    end)

    T.it("reset restarts from start", function()
      local r = M.recur({start = M.date(2024, 1, 1), freq = "daily", count = 3})
      r:take(3)
      r:reset()
      local d = r:next()
      T.eq(d:to_iso(), "2024-01-01")
    end)
  end)

  T.describe("M.recur weekly", function()
    T.it("weekly count=3", function()
      local r = M.recur({start = M.date(2024, 1, 1), freq = "weekly", count = 3})
      local dates = r:take(3)
      T.eq(#dates, 3)
      T.eq(dates[1]:to_iso(), "2024-01-01")
      T.eq(dates[2]:to_iso(), "2024-01-08")
      T.eq(dates[3]:to_iso(), "2024-01-15")
    end)

    T.it("weekly interval=2", function()
      local r = M.recur({start = M.date(2024, 1, 1), freq = "weekly", interval = 2, count = 2})
      local dates = r:take(2)
      T.eq(dates[1]:to_iso(), "2024-01-01")
      T.eq(dates[2]:to_iso(), "2024-01-15")
    end)
  end)

  T.describe("M.recur monthly", function()
    T.it("monthly count=3 from Jan 15", function()
      local r = M.recur({start = M.date(2024, 1, 15), freq = "monthly", count = 3})
      local dates = r:take(3)
      T.eq(dates[1]:to_iso(), "2024-01-15")
      T.eq(dates[2]:to_iso(), "2024-02-15")
      T.eq(dates[3]:to_iso(), "2024-03-15")
    end)

    T.it("monthly from Jan 31 clamps to Feb 29 (leap)", function()
      local r = M.recur({start = M.date(2024, 1, 31), freq = "monthly", count = 2})
      local dates = r:take(2)
      T.eq(dates[1]:to_iso(), "2024-01-31")
      T.eq(dates[2]:to_iso(), "2024-02-29")
    end)

    T.it("monthly from Jan 31 clamps to Feb 28 (non-leap)", function()
      local r = M.recur({start = M.date(2023, 1, 31), freq = "monthly", count = 2})
      local dates = r:take(2)
      T.eq(dates[1]:to_iso(), "2023-01-31")
      T.eq(dates[2]:to_iso(), "2023-02-28")
    end)
  end)

  T.describe("M.recur yearly", function()
    T.it("yearly count=3", function()
      local r = M.recur({start = M.date(2024, 3, 15), freq = "yearly", count = 3})
      local dates = r:take(3)
      T.eq(dates[1]:to_iso(), "2024-03-15")
      T.eq(dates[2]:to_iso(), "2025-03-15")
      T.eq(dates[3]:to_iso(), "2026-03-15")
    end)
  end)

  T.describe("M.easter", function()
    T.it("Easter 2024 = March 31", function()
      local e = M.easter(2024)
      T.eq(e.month, 3)
      T.eq(e.day, 31)
    end)

    T.it("Easter 2025 = April 20", function()
      local e = M.easter(2025)
      T.eq(e.month, 4)
      T.eq(e.day, 20)
    end)

    T.it("Easter 2019 = April 21", function()
      local e = M.easter(2019)
      T.eq(e.month, 4)
      T.eq(e.day, 21)
    end)

    T.it("Easter 2000 = April 23", function()
      local e = M.easter(2000)
      T.eq(e.month, 4)
      T.eq(e.day, 23)
    end)
  end)

  T.describe("M.is_weekend", function()
    T.it("Saturday is weekend", function()
      -- 2024-01-06 = Saturday
      T.ok(M.is_weekend(M.date(2024, 1, 6)))
    end)

    T.it("Sunday is weekend", function()
      -- 2024-01-07 = Sunday
      T.ok(M.is_weekend(M.date(2024, 1, 7)))
    end)

    T.it("Monday is not weekend", function()
      -- 2024-01-01 = Monday
      T.ok(not M.is_weekend(M.date(2024, 1, 1)))
    end)

    T.it("Friday is not weekend", function()
      -- 2024-01-05 = Friday
      T.ok(not M.is_weekend(M.date(2024, 1, 5)))
    end)
  end)

  T.describe("week_of_year", function()
    T.it("2024-01-01 is week 1", function()
      T.eq(M.date(2024, 1, 1):week_of_year(), 1)
    end)

    T.it("2024-01-07 is week 1", function()
      T.eq(M.date(2024, 1, 7):week_of_year(), 1)
    end)

    T.it("2024-01-08 is week 2", function()
      T.eq(M.date(2024, 1, 8):week_of_year(), 2)
    end)

    T.it("2024-12-28 is week 52", function()
      T.eq(M.date(2024, 12, 28):week_of_year(), 52)
    end)
  end)

  T.describe("name tables", function()
    T.it("MONTH_NAMES has 12 entries", function()
      T.eq(#M.MONTH_NAMES, 12)
      T.eq(M.MONTH_NAMES[1], "January")
      T.eq(M.MONTH_NAMES[12], "December")
    end)

    T.it("WEEKDAY_NAMES has 7 entries", function()
      T.eq(#M.WEEKDAY_NAMES, 7)
      T.eq(M.WEEKDAY_NAMES[1], "Monday")
      T.eq(M.WEEKDAY_NAMES[7], "Sunday")
    end)

    T.it("MONTH_ABBR has 12 entries", function()
      T.eq(#M.MONTH_ABBR, 12)
      T.eq(M.MONTH_ABBR[1], "Jan")
      T.eq(M.MONTH_ABBR[12], "Dec")
    end)

    T.it("WEEKDAY_ABBR has 7 entries", function()
      T.eq(#M.WEEKDAY_ABBR, 7)
      T.eq(M.WEEKDAY_ABBR[1], "Mon")
      T.eq(M.WEEKDAY_ABBR[7], "Sun")
    end)
  end)

  T.describe("M.today", function()
    T.it("returns a date with valid fields", function()
      local d = M.today()
      T.ok(d.year >= 2024)
      T.ok(d.month >= 1 and d.month <= 12)
      T.ok(d.day >= 1 and d.day <= 31)
    end)
  end)

end)
