if not package.path:find("./?/init.lua", 1, true) then package.path = "./?/init.lua;" .. package.path end

local T = require("lib.test.assert")
local embed = require("lib.embed")
local vec = require("lib.vec")

local function approx(a, b, tol)
  tol = tol or 1e-6
  T.ok(math.abs(a - b) < tol, "expected " .. a .. " ~ " .. b)
end

-- Helper: make a simple vector of given dimension with a pattern
local function make_vec(dims, base)
  local t = {}
  for i = 1, dims do t[i] = base + i * 0.1 end
  return vec.new(t)
end

T.describe("embed.index creation", function()
  T.it("creates an index with defaults", function()
    local idx = embed.index({ dims = 3 })
    T.ok(idx ~= nil, "index created")
    T.eq(idx:count(), 0)
  end)

  T.it("creates an index with explicit metric", function()
    local idx = embed.index({ dims = 3, metric = "euclidean" })
    T.ok(idx ~= nil, "index created with euclidean")
  end)

  T.it("rejects missing dims", function()
    local idx, err = embed.index({ dims = 0 })
    T.eq(idx, nil)
    T.ok(err ~= nil, "error returned")
  end)

  T.it("rejects invalid metric", function()
    local idx, err = embed.index({ dims = 3, metric = "manhattan" })
    T.eq(idx, nil)
    T.ok(err ~= nil, "error returned for bad metric")
  end)
end)

T.describe("embed add and get", function()
  T.it("adds a vector and retrieves it", function()
    local idx = embed.index({ dims = 3 })
    local v = vec.new({1, 2, 3})
    local ok = idx:add("a", v, { title = "hello" })
    T.eq(ok, true)
    T.eq(idx:count(), 1)
    local entry = idx:get("a")
    T.ok(entry ~= nil, "entry found")
    T.eq(entry.id, "a")
    T.eq(entry.metadata.title, "hello")
    approx(vec.get(entry.vector, 1), 1)
    approx(vec.get(entry.vector, 2), 2)
    approx(vec.get(entry.vector, 3), 3)
  end)

  T.it("returns nil for missing id", function()
    local idx = embed.index({ dims = 3 })
    T.eq(idx:get("nope"), nil)
  end)

  T.it("rejects dimension mismatch on add", function()
    local idx = embed.index({ dims = 3 })
    local v = vec.new({1, 2})
    local ok, err = idx:add("a", v)
    T.eq(ok, nil)
    T.ok(err:find("mismatch") ~= nil, "error mentions mismatch")
  end)

  T.it("adds without metadata", function()
    local idx = embed.index({ dims = 2 })
    local ok = idx:add("x", vec.new({1, 0}))
    T.eq(ok, true)
    local entry = idx:get("x")
    T.eq(entry.metadata, nil)
  end)

  T.it("duplicate id overwrites", function()
    local idx = embed.index({ dims = 2 })
    idx:add("a", vec.new({1, 0}), { v = 1 })
    idx:add("a", vec.new({0, 1}), { v = 2 })
    T.eq(idx:count(), 1)
    local entry = idx:get("a")
    T.eq(entry.metadata.v, 2)
    approx(vec.get(entry.vector, 1), 0)
    approx(vec.get(entry.vector, 2), 1)
  end)
end)

T.describe("embed batch add", function()
  T.it("adds multiple vectors", function()
    local idx = embed.index({ dims = 2 })
    local ok = idx:add_batch({
      { id = "a", vector = vec.new({1, 0}), metadata = { n = 1 } },
      { id = "b", vector = vec.new({0, 1}), metadata = { n = 2 } },
      { id = "c", vector = vec.new({1, 1}) },
    })
    T.eq(ok, true)
    T.eq(idx:count(), 3)
    T.eq(idx:get("a").metadata.n, 1)
    T.eq(idx:get("b").metadata.n, 2)
    T.eq(idx:get("c").metadata, nil)
  end)

  T.it("rejects batch with dimension mismatch", function()
    local idx = embed.index({ dims = 2 })
    local ok, err = idx:add_batch({
      { id = "a", vector = vec.new({1, 0}) },
      { id = "b", vector = vec.new({1, 2, 3}) },
    })
    T.eq(ok, nil)
    T.ok(err:find("item 2") ~= nil, "error mentions item index")
  end)
end)

T.describe("embed remove", function()
  T.it("removes an existing entry", function()
    local idx = embed.index({ dims = 2 })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({0, 1}))
    T.eq(idx:count(), 2)
    local ok = idx:remove("a")
    T.eq(ok, true)
    T.eq(idx:count(), 1)
    T.eq(idx:get("a"), nil)
    T.ok(idx:get("b") ~= nil, "b still exists")
  end)

  T.it("returns false for missing id", function()
    local idx = embed.index({ dims = 2 })
    T.eq(idx:remove("nope"), false)
  end)

  T.it("removed entry excluded from search", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({0, 1}))
    idx:remove("a")
    local results = idx:search(vec.new({1, 0}), 5)
    T.eq(#results, 1)
    T.eq(results[1].id, "b")
  end)
end)

T.describe("embed ids", function()
  T.it("lists all ids", function()
    local idx = embed.index({ dims = 2 })
    idx:add("c", vec.new({1, 0}))
    idx:add("a", vec.new({0, 1}))
    idx:add("b", vec.new({1, 1}))
    local ids = idx:ids()
    T.eq(#ids, 3)
    -- insertion order preserved
    T.eq(ids[1], "c")
    T.eq(ids[2], "a")
    T.eq(ids[3], "b")
  end)

  T.it("empty index returns empty list", function()
    local idx = embed.index({ dims = 2 })
    T.eq(#idx:ids(), 0)
  end)
end)

T.describe("embed search - cosine", function()
  T.it("finds nearest by cosine similarity", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("right", vec.new({1, 0}))
    idx:add("up", vec.new({0, 1}))
    idx:add("diag", vec.new({1, 1}))

    local results = idx:search(vec.new({1, 0.1}), 3)
    T.eq(#results, 3)
    -- "right" should be most similar to {1, 0.1}
    T.eq(results[1].id, "right")
    -- "diag" should be second
    T.eq(results[2].id, "diag")
    -- "up" should be least similar
    T.eq(results[3].id, "up")
  end)

  T.it("returns scores between -1 and 1 for cosine", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({-1, 0}))
    local results = idx:search(vec.new({1, 0}), 2)
    T.ok(results[1].score > 0.99, "identical direction ~ 1.0")
    T.ok(results[2].score < -0.99, "opposite direction ~ -1.0")
  end)

  T.it("respects k limit", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({0, 1}))
    idx:add("c", vec.new({1, 1}))
    local results = idx:search(vec.new({1, 0}), 1)
    T.eq(#results, 1)
    T.eq(results[1].id, "a")
  end)

  T.it("k larger than count returns all", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    local results = idx:search(vec.new({1, 0}), 10)
    T.eq(#results, 1)
  end)
end)

T.describe("embed search - euclidean", function()
  T.it("finds nearest by euclidean distance", function()
    local idx = embed.index({ dims = 2, metric = "euclidean" })
    idx:add("origin", vec.new({0, 0}))
    idx:add("near", vec.new({1, 0}))
    idx:add("far", vec.new({10, 10}))

    local results = idx:search(vec.new({0.9, 0}), 3)
    T.eq(#results, 3)
    -- "near" is closest to {0.9, 0} (dist 0.1)
    T.eq(results[1].id, "near")
    -- "origin" is next (dist 0.9)
    T.eq(results[2].id, "origin")
    T.eq(results[3].id, "far")
  end)

  T.it("scores are negative distances", function()
    local idx = embed.index({ dims = 2, metric = "euclidean" })
    idx:add("a", vec.new({0, 0}))
    local results = idx:search(vec.new({3, 4}), 1)
    approx(results[1].score, -5.0)
  end)
end)

T.describe("embed search - dot product", function()
  T.it("finds nearest by dot product", function()
    local idx = embed.index({ dims = 2, metric = "dot" })
    idx:add("big", vec.new({10, 10}))
    idx:add("small", vec.new({1, 1}))
    idx:add("neg", vec.new({-5, -5}))

    local results = idx:search(vec.new({1, 1}), 3)
    T.eq(#results, 3)
    T.eq(results[1].id, "big")
    T.eq(results[2].id, "small")
    T.eq(results[3].id, "neg")
  end)

  T.it("dot product scores match vec.dot", function()
    local idx = embed.index({ dims = 3, metric = "dot" })
    local v1 = vec.new({1, 2, 3})
    local v2 = vec.new({4, 5, 6})
    idx:add("a", v1)
    local results = idx:search(v2, 1)
    approx(results[1].score, vec.dot(v2, v1))
  end)
end)

T.describe("embed search - empty index", function()
  T.it("returns empty results", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    local results = idx:search(vec.new({1, 0}), 5)
    T.eq(#results, 0)
  end)
end)

T.describe("embed search - dimension mismatch", function()
  T.it("returns error for wrong query dims", function()
    local idx = embed.index({ dims = 3, metric = "cosine" })
    idx:add("a", vec.new({1, 2, 3}))
    local results, err = idx:search(vec.new({1, 2}), 1)
    T.eq(results, nil)
    T.ok(err:find("mismatch") ~= nil, "error mentions mismatch")
  end)
end)

T.describe("embed search - filter", function()
  T.it("filters by metadata predicate", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}), { tag = "keep" })
    idx:add("b", vec.new({1, 0.01}), { tag = "exclude" })
    idx:add("c", vec.new({0.9, 0.1}), { tag = "keep" })

    local results = idx:search(vec.new({1, 0}), 10, {
      filter = function(meta) return meta and meta.tag == "keep" end,
    })
    T.eq(#results, 2)
    T.eq(results[1].id, "a")
    T.eq(results[2].id, "c")
  end)

  T.it("filter excludes all returns empty", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    local results = idx:search(vec.new({1, 0}), 10, {
      filter = function() return false end,
    })
    T.eq(#results, 0)
  end)
end)

T.describe("embed search - ordering", function()
  T.it("results are sorted most similar first", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({0.7, 0.7}))
    idx:add("c", vec.new({0, 1}))
    idx:add("d", vec.new({-1, 0}))

    local results = idx:search(vec.new({1, 0}), 4)
    for i = 1, #results - 1 do
      T.ok(results[i].score >= results[i + 1].score,
        "result " .. i .. " score >= result " .. (i + 1) .. " score")
    end
  end)
end)

T.describe("embed serialize/deserialize", function()
  T.it("roundtrips data correctly", function()
    local idx = embed.index({ dims = 3, metric = "dot" })
    idx:add("x", vec.new({1, 2, 3}), { tag = "first" })
    idx:add("y", vec.new({4, 5, 6}), { tag = "second" })

    local data = idx:serialize()
    T.eq(data.dims, 3)
    T.eq(data.metric, "dot")
    T.eq(#data.items, 2)
    T.eq(data.items[1].id, "x")
    T.eq(data.items[2].id, "y")
    T.eq(data.items[1].metadata.tag, "first")

    local idx2 = embed.deserialize(data)
    T.eq(idx2:count(), 2)
    local entry = idx2:get("x")
    T.ok(entry ~= nil, "x exists in deserialized index")
    T.eq(entry.metadata.tag, "first")
    approx(vec.get(entry.vector, 1), 1)
    approx(vec.get(entry.vector, 2), 2)
    approx(vec.get(entry.vector, 3), 3)
  end)

  T.it("deserialized index searches correctly", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({0, 1}))

    local data = idx:serialize()
    local idx2 = embed.deserialize(data)
    local results = idx2:search(vec.new({1, 0}), 2)
    T.eq(results[1].id, "a")
    T.eq(results[2].id, "b")
  end)

  T.it("preserves insertion order", function()
    local idx = embed.index({ dims = 2 })
    idx:add("c", vec.new({1, 0}))
    idx:add("a", vec.new({0, 1}))
    idx:add("b", vec.new({1, 1}))
    local data = idx:serialize()
    T.eq(data.items[1].id, "c")
    T.eq(data.items[2].id, "a")
    T.eq(data.items[3].id, "b")

    local idx2 = embed.deserialize(data)
    local ids = idx2:ids()
    T.eq(ids[1], "c")
    T.eq(ids[2], "a")
    T.eq(ids[3], "b")
  end)

  T.it("rejects missing dims", function()
    local idx, err = embed.deserialize({ metric = "cosine", items = {} })
    T.eq(idx, nil)
    T.ok(err ~= nil, "error returned")
  end)

  T.it("vectors stored as plain tables in serialized form", function()
    local idx = embed.index({ dims = 2 })
    idx:add("a", vec.new({3.5, 7.5}))
    local data = idx:serialize()
    -- vector should be a plain Lua table, not a Vec object
    local v = data.items[1].vector
    T.eq(type(v), "table")
    T.eq(#v, 2)
    approx(v[1], 3.5)
    approx(v[2], 7.5)
  end)
end)

T.describe("embed higher dimensions", function()
  T.it("works with 384-dim vectors", function()
    local idx = embed.index({ dims = 384, metric = "cosine" })
    local v1 = make_vec(384, 1.0)
    local v2 = make_vec(384, 2.0)
    local v3 = make_vec(384, 1.01)  -- very close to v1

    idx:add("a", v1)
    idx:add("b", v2)
    idx:add("c", v3)

    local results = idx:search(v1, 3)
    T.eq(#results, 3)
    -- v1 itself is most similar, then v3 (very close), then v2
    T.eq(results[1].id, "a")
    T.eq(results[2].id, "c")
    T.eq(results[3].id, "b")
    approx(results[1].score, 1.0, 1e-6)
  end)
end)

T.describe("embed edge cases", function()
  T.it("search with k=0 returns empty", function()
    local idx = embed.index({ dims = 2, metric = "cosine" })
    idx:add("a", vec.new({1, 0}))
    local results = idx:search(vec.new({1, 0}), 0)
    T.eq(#results, 0)
  end)

  T.it("add and remove same id multiple times", function()
    local idx = embed.index({ dims = 2 })
    idx:add("a", vec.new({1, 0}))
    idx:remove("a")
    T.eq(idx:count(), 0)
    idx:add("a", vec.new({0, 1}))
    T.eq(idx:count(), 1)
    approx(vec.get(idx:get("a").vector, 2), 1)
  end)

  T.it("remove then add preserves correct order", function()
    local idx = embed.index({ dims = 2 })
    idx:add("a", vec.new({1, 0}))
    idx:add("b", vec.new({0, 1}))
    idx:add("c", vec.new({1, 1}))
    idx:remove("b")
    idx:add("d", vec.new({0.5, 0.5}))
    local ids = idx:ids()
    T.eq(#ids, 3)
    T.eq(ids[1], "a")
    T.eq(ids[2], "c")
    T.eq(ids[3], "d")
  end)
end)
