if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local h = require("lib.html")

T.describe("escape", function()
	T.it("escapes ampersand", function()
		T.eq(h.escape("a&b"), "a&amp;b")
	end)
	T.it("escapes less-than", function()
		T.eq(h.escape("<tag>"), "&lt;tag&gt;")
	end)
	T.it("escapes double quote", function()
		T.eq(h.escape([[say "hi"]]), "say &quot;hi&quot;")
	end)
	T.it("escapes single quote", function()
		T.eq(h.escape("it's"), "it&#039;s")
	end)
	T.it("leaves plain text alone", function()
		T.eq(h.escape("hello world"), "hello world")
	end)
end)

T.describe("element with string child", function()
	T.it("wraps in tag and escapes", function()
		T.eq(h.p("hello <world>"), "<p>hello &lt;world&gt;</p>")
	end)
	T.it("h1 wraps text", function()
		T.eq(h.h1("Title"), "<h1>Title</h1>")
	end)
end)

T.describe("element with attrs table", function()
	T.it("renders single attribute", function()
		T.eq(h.div({ class = "card" }), '<div class="card"></div>')
	end)
	T.it("renders boolean attribute (true = bare attr)", function()
		T.eq(h.input({ required = true }), "<input required />")
	end)
	T.it("boolean false omits attribute", function()
		T.eq(h.input({ disabled = false }), "<input />")
	end)
	T.it("escapes attribute values", function()
		T.eq(h.div({ title = 'say "hi"' }), '<div title="say &quot;hi&quot;"></div>')
	end)
	T.it("renders children from integer keys", function()
		T.eq(h.ul({ h.li("a"), h.li("b") }), "<ul><li>a</li><li>b</li></ul>")
	end)
	T.it("renders attrs and children together", function()
		T.eq(h.div({ class = "box", "child" }), '<div class="box">child</div>')
	end)
	T.it("no attrs, no children → empty element", function()
		T.eq(h.div({}), "<div></div>")
	end)
end)

T.describe("void elements", function()
	T.it("br is a string constant", function()
		T.eq(h.br, "<br />")
	end)
	T.it("void br_ with no attrs", function()
		T.eq(h.br_({}), "<br />")
	end)
	T.it("hr with class", function()
		T.eq(h.hr({ class = "sep" }), '<hr class="sep" />')
	end)
	T.it("img with src and alt", function()
		local s = h.img({ src = "/logo.png", alt = "Logo" })
		T.ok(s:find('src="/logo.png"') ~= nil, "has src")
		T.ok(s:find('alt="Logo"') ~= nil, "has alt")
		T.ok(s:sub(1, 4) == "<img", "starts with <img")
		T.ok(s:sub(-3) == " />", "self-closes")
	end)
	T.it("input with type and name", function()
		local s = h.input({ type = "email", name = "email" })
		T.ok(s:find('type="email"') ~= nil, "has type")
		T.ok(s:find('name="email"') ~= nil, "has name")
	end)
	T.it("link rel and href", function()
		local s = h.link({ rel = "stylesheet", href = "/style.css" })
		T.ok(s:find('rel="stylesheet"') ~= nil, "has rel")
		T.ok(s:find('href="/style.css"') ~= nil, "has href")
	end)
	T.it("meta charset", function()
		T.eq(h.meta({ charset = "utf-8" }), '<meta charset="utf-8" />')
	end)
end)

T.describe("anchor", function()
	T.it("basic href", function()
		T.eq(h.a({ href = "/about", "About" }), '<a href="/about">About</a>')
	end)
	T.it("target blank and rel", function()
		local s = h.a({ href = "https://example.com", target = "_blank", rel = "noopener", "Link" })
		T.ok(s:find('href="https://example.com"') ~= nil, "has href")
		T.ok(s:find('target="_blank"') ~= nil, "has target")
		T.ok(s:find('rel="noopener"') ~= nil, "has rel")
		T.ok(s:find(">Link</a>") ~= nil, "has child text")
	end)
end)

T.describe("raw elements", function()
	T.it("script content not escaped", function()
		T.eq(h.script({ 'if (a < b) { return; }' }), "<script>if (a < b) { return; }</script>")
	end)
	T.it("script with src attr", function()
		local s = h.script({ src = "/app.js", defer = true })
		T.ok(s:find('src="/app.js"') ~= nil, "has src")
		T.ok(s:find(" defer") ~= nil, "has defer")
		T.ok(s:find("</script>") ~= nil, "has closing tag")
	end)
	T.it("style content not escaped", function()
		T.eq(h.style({ "body { color: red; }" }), "<style>body { color: red; }</style>")
	end)
end)

T.describe("html document", function()
	T.it("prepends DOCTYPE", function()
		local doc = h.html({ lang = "en",
			h.head({ h.title("Test"), h.meta({ charset = "utf-8" }) }),
			h.body({ h.p("Hello") }),
		})
		T.ok(doc:sub(1, 15) == "<!DOCTYPE html>", "starts with doctype")
		T.ok(doc:find('<html lang="en">') ~= nil, "has lang attr")
		T.ok(doc:find("<title>Test</title>") ~= nil, "has title")
		T.ok(doc:find("<p>Hello</p>") ~= nil, "has body content")
	end)
end)

T.describe("tables", function()
	T.it("renders table with thead and tbody", function()
		local tbl = h.table({
			h.thead({ h.tr({ h.th("Name"), h.th("Age") }) }),
			h.tbody({
				h.tr({ h.td("Alice"), h.td("30") }),
				h.tr({ h.td("Bob"), h.td("25") }),
			}),
		})
		T.ok(tbl:find("<table>") ~= nil, "has table tag")
		T.ok(tbl:find("<th>Name</th>") ~= nil, "has header")
		T.ok(tbl:find("<td>Alice</td>") ~= nil, "has cell")
	end)
end)

T.describe("forms", function()
	T.it("renders a login form", function()
		local frm = h.form({ action = "/login", method = "post",
			h.label({ ["for"] = "email", "Email" }),
			h.input({ type = "email", name = "email", required = true }),
			h.button({ type = "submit", "Log in" }),
		})
		T.ok(frm:find('action="/login"') ~= nil, "has action")
		T.ok(frm:find('type="email"') ~= nil, "has input type")
		T.ok(frm:find("required") ~= nil, "has required")
		T.ok(frm:find(">Log in</button>") ~= nil, "has submit label")
	end)
end)
