local T = require("lib.test.assert")
local mimetype = require("lib.mimetype")

T.describe("mimetype.by_name", function()
	T.it("should detect common web types", function()
		T.eq(mimetype.by_name("index.html"), "text/html")
		T.eq(mimetype.by_name("data.json"), "application/json")
		T.eq(mimetype.by_name("style.css"), "text/css")
		T.eq(mimetype.by_name("app.js"), "application/javascript")
		T.eq(mimetype.by_name("module.wasm"), "application/wasm")
	end)

	T.it("should detect image types", function()
		T.eq(mimetype.by_name("photo.png"), "image/png")
		T.eq(mimetype.by_name("photo.jpg"), "image/jpeg")
		T.eq(mimetype.by_name("icon.gif"), "image/gif")
		T.eq(mimetype.by_name("icon.svg"), "image/svg+xml")
	end)

	T.it("should detect other common types", function()
		T.eq(mimetype.by_name("doc.xml"), "application/xml")
		T.eq(mimetype.by_name("doc.pdf"), "application/pdf")
		T.eq(mimetype.by_name("archive.zip"), "application/zip")
		T.eq(mimetype.by_name("readme.txt"), "text/plain")
	end)

	T.it("should return nil for files with no extension", function()
		T.eq(mimetype.by_name("Makefile"), nil)
		T.eq(mimetype.by_name("LICENSE"), nil)
	end)

	T.it("should be case insensitive", function()
		T.eq(mimetype.by_name("FILE.HTML"), "text/html")
		T.eq(mimetype.by_name("IMAGE.PNG"), "image/png")
		T.eq(mimetype.by_name("data.JSON"), "application/json")
	end)

	T.it("should use the last extension for dotted names", function()
		T.eq(mimetype.by_name("archive.tar.gz"), "application/x-gzip")
		T.eq(mimetype.by_name("file.backup.json"), "application/json")
	end)

	T.it("should handle paths with directories", function()
		T.eq(mimetype.by_name("some/path/to/file.html"), "text/html")
		T.eq(mimetype.by_name("/absolute/path/file.png"), "image/png")
	end)
end)

T.describe("mimetype.detect", function()
	T.it("should prefer name-based detection", function()
		T.eq(mimetype.detect("file.html", "not html content"), "text/html")
	end)

	T.it("should fall back to content-based detection when name fails", function()
		-- PNG magic bytes
		local png_header = "\137PNG\r\n\026\n"
		local result = mimetype.detect("noext", png_header .. string.rep("\0", 24))
		T.eq(result, "image/png")
	end)

	T.it("should return nil when neither name nor contents match", function()
		T.eq(mimetype.detect("noext", "random bytes"), nil)
	end)
end)

T.describe("mimetype.by_contents", function()
	T.it("should detect PNG from magic bytes", function()
		local png = "\137PNG\r\n\026\n" .. string.rep("\0", 24)
		local ext, mt = mimetype.by_contents(png)
		T.eq(ext, "png")
		T.eq(mt, "image/png")
	end)

	T.it("should detect GIF from magic bytes", function()
		local gif = "GIF89a" .. string.rep("\0", 10)
		local ext, mt = mimetype.by_contents(gif)
		T.eq(ext, "gif")
		T.eq(mt, "image/gif")
	end)

	T.it("should return nil for empty buffer", function()
		local ext, mt = mimetype.by_contents("")
		T.eq(ext, nil)
		T.eq(mt, nil)
	end)

	T.it("should return nil for unrecognized bytes", function()
		local ext, mt = mimetype.by_contents("just some text")
		T.eq(ext, nil)
		T.eq(mt, nil)
	end)
end)
