-- lib/roman/roman_test.lua
-- Tests for lib/roman Roman numeral encoding/decoding.

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.roman")

T.describe("roman", function()

  T.describe("encode — milestone values", function()
    T.it("encodes 1", function() T.eq(M.encode(1), "I") end)
    T.it("encodes 2", function() T.eq(M.encode(2), "II") end)
    T.it("encodes 3", function() T.eq(M.encode(3), "III") end)
    T.it("encodes 4", function() T.eq(M.encode(4), "IV") end)
    T.it("encodes 5", function() T.eq(M.encode(5), "V") end)
    T.it("encodes 6", function() T.eq(M.encode(6), "VI") end)
    T.it("encodes 7", function() T.eq(M.encode(7), "VII") end)
    T.it("encodes 8", function() T.eq(M.encode(8), "VIII") end)
    T.it("encodes 9", function() T.eq(M.encode(9), "IX") end)
    T.it("encodes 10", function() T.eq(M.encode(10), "X") end)
    T.it("encodes 11", function() T.eq(M.encode(11), "XI") end)
    T.it("encodes 12", function() T.eq(M.encode(12), "XII") end)
    T.it("encodes 13", function() T.eq(M.encode(13), "XIII") end)
    T.it("encodes 14", function() T.eq(M.encode(14), "XIV") end)
    T.it("encodes 15", function() T.eq(M.encode(15), "XV") end)
    T.it("encodes 16", function() T.eq(M.encode(16), "XVI") end)
    T.it("encodes 17", function() T.eq(M.encode(17), "XVII") end)
    T.it("encodes 18", function() T.eq(M.encode(18), "XVIII") end)
    T.it("encodes 19", function() T.eq(M.encode(19), "XIX") end)
    T.it("encodes 20", function() T.eq(M.encode(20), "XX") end)
    T.it("encodes 40",   function() T.eq(M.encode(40),   "XL") end)
    T.it("encodes 49",   function() T.eq(M.encode(49),   "XLIX") end)
    T.it("encodes 50",   function() T.eq(M.encode(50),   "L") end)
    T.it("encodes 90",   function() T.eq(M.encode(90),   "XC") end)
    T.it("encodes 99",   function() T.eq(M.encode(99),   "XCIX") end)
    T.it("encodes 100",  function() T.eq(M.encode(100),  "C") end)
    T.it("encodes 400",  function() T.eq(M.encode(400),  "CD") end)
    T.it("encodes 500",  function() T.eq(M.encode(500),  "D") end)
    T.it("encodes 900",  function() T.eq(M.encode(900),  "CM") end)
    T.it("encodes 1000", function() T.eq(M.encode(1000), "M") end)
    T.it("encodes 1994", function() T.eq(M.encode(1994), "MCMXCIV") end)
    T.it("encodes 1999", function() T.eq(M.encode(1999), "MCMXCIX") end)
    T.it("encodes 2024", function() T.eq(M.encode(2024), "MMXXIV") end)
    T.it("encodes 3999", function() T.eq(M.encode(3999), "MMMCMXCIX") end)
  end)

  T.describe("decode — milestone values", function()
    T.it("decodes I",         function() T.eq(M.decode("I"),         1) end)
    T.it("decodes IV",        function() T.eq(M.decode("IV"),        4) end)
    T.it("decodes IX",        function() T.eq(M.decode("IX"),        9) end)
    T.it("decodes XIV",       function() T.eq(M.decode("XIV"),       14) end)
    T.it("decodes XL",        function() T.eq(M.decode("XL"),        40) end)
    T.it("decodes XC",        function() T.eq(M.decode("XC"),        90) end)
    T.it("decodes CD",        function() T.eq(M.decode("CD"),        400) end)
    T.it("decodes CM",        function() T.eq(M.decode("CM"),        900) end)
    T.it("decodes M",         function() T.eq(M.decode("M"),         1000) end)
    T.it("decodes MCMXCIV",   function() T.eq(M.decode("MCMXCIV"),   1994) end)
    T.it("decodes MCMXCIX",   function() T.eq(M.decode("MCMXCIX"),   1999) end)
    T.it("decodes MMXXIV",    function() T.eq(M.decode("MMXXIV"),    2024) end)
    T.it("decodes MMMCMXCIX", function() T.eq(M.decode("MMMCMXCIX"), 3999) end)
  end)

  T.describe("decode — case insensitive", function()
    T.it("decodes lowercase iv",      function() T.eq(M.decode("iv"),      4) end)
    T.it("decodes lowercase mcmxciv", function() T.eq(M.decode("mcmxciv"), 1994) end)
    T.it("decodes mixed case XiV",    function() T.eq(M.decode("XiV"),     14) end)
  end)

  T.describe("encode — lowercase option", function()
    T.it("encodes 4 lowercase",    function() T.eq(M.encode(4,    { lower = true }), "iv") end)
    T.it("encodes 1994 lowercase", function() T.eq(M.encode(1994, { lower = true }), "mcmxciv") end)
    T.it("encodes 3999 lowercase", function() T.eq(M.encode(3999, { lower = true }), "mmmcmxcix") end)
  end)

  T.describe("encode — additive option", function()
    T.it("additive: 4 is IIII",    function() T.eq(M.encode(4,  { additive = true }), "IIII") end)
    T.it("additive: 9 is VIIII",   function() T.eq(M.encode(9,  { additive = true }), "VIIII") end)
    T.it("additive: 14 is XIIII",  function() T.eq(M.encode(14, { additive = true }), "XIIII") end)
    T.it("additive: 40 is XXXX",   function() T.eq(M.encode(40, { additive = true }), "XXXX") end)
    T.it("additive: 90 is LXXXX",  function() T.eq(M.encode(90, { additive = true }), "LXXXX") end)
    T.it("additive: 400 is CCCC",  function() T.eq(M.encode(400, { additive = true }), "CCCC") end)
    T.it("additive: 900 is DCCCC", function() T.eq(M.encode(900, { additive = true }), "DCCCC") end)
  end)

  T.describe("round-trip encode->decode", function()
    T.it("round-trips 1..3999", function()
      local ok = true
      for i = 1, 3999 do
        local r = M.encode(i)
        local n = M.decode(r)
        if n ~= i then ok = false; break end
      end
      T.ok(ok)
    end)
  end)

  T.describe("is_valid", function()
    T.it("valid: I",         function() T.ok(M.is_valid("I")) end)
    T.it("valid: IV",        function() T.ok(M.is_valid("IV")) end)
    T.it("valid: MCMXCIV",   function() T.ok(M.is_valid("MCMXCIV")) end)
    T.it("valid: lowercase", function() T.ok(M.is_valid("mcmxciv")) end)
    T.it("valid: IIII",      function() T.ok(M.is_valid("IIII")) end)
    T.it("invalid: empty",   function() T.ok(not M.is_valid("")) end)
    T.it("invalid: A",       function() T.ok(not M.is_valid("A")) end)
    T.it("invalid: IVX2",    function() T.ok(not M.is_valid("IVX2")) end)
    T.it("invalid: number",  function() T.ok(not M.is_valid(42)) end)
    T.it("invalid: nil",     function() T.ok(not M.is_valid(nil)) end)
  end)

  T.describe("normalize", function()
    T.it("normalizes IIII -> IV",    function() T.eq(M.normalize("IIII"),    "IV") end)
    T.it("normalizes VIIII -> IX",   function() T.eq(M.normalize("VIIII"),   "IX") end)
    T.it("normalizes XXXX -> XL",    function() T.eq(M.normalize("XXXX"),    "XL") end)
    T.it("normalizes LXXXX -> XC",   function() T.eq(M.normalize("LXXXX"),   "XC") end)
    T.it("normalizes CCCC -> CD",    function() T.eq(M.normalize("CCCC"),    "CD") end)
    T.it("normalizes DCCCC -> CM",   function() T.eq(M.normalize("DCCCC"),   "CM") end)
    T.it("keeps canonical IV as-is", function() T.eq(M.normalize("IV"),      "IV") end)
    T.it("keeps canonical MCMXCIV",  function() T.eq(M.normalize("MCMXCIV"), "MCMXCIV") end)
    T.it("normalizes lowercase iiii", function() T.eq(M.normalize("iiii"),   "IV") end)
    T.it("error on invalid input",    function()
      local result, err = M.normalize("IIVX2")
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
  end)

  T.describe("encode — error cases", function()
    T.it("errors on 0", function()
      local result, err = M.encode(0)
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on 4000", function()
      local result, err = M.encode(4000)
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on negative", function()
      local result, err = M.encode(-1)
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on float", function()
      local result, err = M.encode(1.5)
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on string", function()
      local result, err = M.encode("XIV")
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
  end)

  T.describe("decode — error cases", function()
    T.it("errors on empty string", function()
      local result, err = M.decode("")
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on invalid char", function()
      local result, err = M.decode("IVZ")
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on digits", function()
      local result, err = M.decode("XIV2")
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    T.it("errors on nil", function()
      local result, err = M.decode(nil)
      T.eq(result, nil)
      T.ok(err ~= nil)
    end)
    -- IIII is additive notation for 4 — decode accepts it
    T.it("decodes additive IIII as 4", function()
      T.eq(M.decode("IIII"), 4)
    end)
    T.it("decodes additive VIIII as 9", function()
      T.eq(M.decode("VIIII"), 9)
    end)
  end)

  T.describe("aliases", function()
    T.it("to_roman is encode", function()
      T.eq(M.to_roman, M.encode)
    end)
    T.it("from_roman is decode", function()
      T.eq(M.from_roman, M.decode)
    end)
    T.it("to_roman(1994) works", function()
      T.eq(M.to_roman(1994), "MCMXCIV")
    end)
    T.it("from_roman('MCMXCIV') works", function()
      T.eq(M.from_roman("MCMXCIV"), 1994)
    end)
  end)

  T.describe("range constants", function()
    T.it("MIN is 1",    function() T.eq(M.MIN, 1) end)
    T.it("MAX is 3999", function() T.eq(M.MAX, 3999) end)
    T.it("_tier is pure", function() T.eq(M._tier, "pure") end)
  end)

end)
