if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local P = require("lib.pipeline_dsl")

-- Deep equality helpers --

local function deep_eq(a, b)
  if type(a) ~= type(b) then return false end
  if type(a) ~= "table" then return a == b end
  if #a ~= #b then return false end
  for k, v in pairs(a) do
    if not deep_eq(v, b[k]) then return false end
  end
  for k, v in pairs(b) do
    if not deep_eq(v, a[k]) then return false end
  end
  return true
end

local function teq(a, b, msg)
  T.ok(deep_eq(a, b), msg or ("tables differ: got " .. tostring(a) .. " expected " .. tostring(b)))
end

-- Tests --

T.describe("pipeline_dsl", function()

  T.it("_tier is pure", function()
    T.eq(P._tier, "pure")
  end)

  T.it("map + filter + collect: basic chain", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5, 6, 7, 8, 9, 10}))
      :filter(function(x) return x % 2 == 0 end)
      :map(function(x) return x * x end)
      :take(3)
      :collect()
    teq(result, {4, 16, 36})
  end)

  T.it("take: limits output count", function()
    local result = P.pipeline()
      :source(P.from_array({10, 20, 30, 40, 50}))
      :take(3)
      :collect()
    teq(result, {10, 20, 30})
  end)

  T.it("flat_map: flattens correctly", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3}))
      :flat_map(function(x) return {x, x * 10} end)
      :collect()
    teq(result, {1, 10, 2, 20, 3, 30})
  end)

  T.it("zip: pairs two sources", function()
    local result = P.pipeline()
      :source(P.from_array({"a", "b", "c"}))
      :zip(P.from_array({1, 2, 3}))
      :collect()
    T.eq(#result, 3)
    T.eq(result[1][1], "a") T.eq(result[1][2], 1)
    T.eq(result[2][1], "b") T.eq(result[2][2], 2)
    T.eq(result[3][1], "c") T.eq(result[3][2], 3)
  end)

  T.it("zip: stops at shorter source", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4}))
      :zip(P.from_array({10, 20}))
      :collect()
    T.eq(#result, 2)
    T.eq(result[1][1], 1)  T.eq(result[1][2], 10)
    T.eq(result[2][1], 2)  T.eq(result[2][2], 20)
  end)

  T.it("chunk: groups correctly", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :chunk(2)
      :collect()
    T.eq(#result, 3)
    teq(result[1], {1, 2})
    teq(result[2], {3, 4})
    teq(result[3], {5})
  end)

  T.it("scan: running sum", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :scan(function(acc, x) return acc + x end, 0)
      :collect()
    teq(result, {1, 3, 6, 10, 15})
  end)

  T.it("unique: deduplicates (full, not just adjacent)", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 1, 3, 2, 4}))
      :unique()
      :collect()
    teq(result, {1, 2, 3, 4})
  end)

  T.it("enumerate: adds 1-based index", function()
    local result = P.pipeline()
      :source(P.from_array({"x", "y", "z"}))
      :enumerate()
      :collect()
    T.eq(#result, 3)
    T.eq(result[1][1], 1) T.eq(result[1][2], "x")
    T.eq(result[2][1], 2) T.eq(result[2][2], "y")
    T.eq(result[3][1], 3) T.eq(result[3][2], "z")
  end)

  T.it("sort: sorts output ascending", function()
    local result = P.pipeline()
      :source(P.from_array({3, 1, 4, 1, 5, 9, 2, 6}))
      :sort()
      :collect()
    teq(result, {1, 1, 2, 3, 4, 5, 6, 9})
  end)

  T.it("sort: sorts with comparator descending", function()
    local result = P.pipeline()
      :source(P.from_array({3, 1, 4, 1, 5}))
      :sort(function(a, b) return a > b end)
      :collect()
    teq(result, {5, 4, 3, 1, 1})
  end)

  T.it("reverse: reverses the stream", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :reverse()
      :collect()
    teq(result, {5, 4, 3, 2, 1})
  end)

  T.it("flatten: flattens one level", function()
    local result = P.pipeline()
      :source(P.from_array({{1, 2}, {3, 4}, {5}}))
      :flatten()
      :collect()
    teq(result, {1, 2, 3, 4, 5})
  end)

  T.it("reduce: accumulates to single value", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :reduce(function(acc, x) return acc + x end, 0)
    T.eq(result, 15)
  end)

  T.it("sum: sums numeric elements", function()
    local result = P.pipeline()
      :source(P.from_array({10, 20, 30}))
      :sum()
    T.eq(result, 60)
  end)

  T.it("count: counts elements", function()
    local result = P.pipeline()
      :source(P.from_array({7, 8, 9}))
      :count()
    T.eq(result, 3)
  end)

  T.it("first: returns first element", function()
    local result = P.pipeline()
      :source(P.from_array({42, 99, 1}))
      :first()
    T.eq(result, 42)
  end)

  T.it("last: returns last element", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3}))
      :last()
    T.eq(result, 3)
  end)

  T.it("first: nil on empty", function()
    local result = P.pipeline()
      :source(P.empty())
      :first()
    T.eq(result, nil)
  end)

  T.it("last: nil on empty", function()
    local result = P.pipeline()
      :source(P.empty())
      :last()
    T.eq(result, nil)
  end)

  T.it("each: side-effects fire in order", function()
    local fired = {}
    P.pipeline()
      :source(P.from_array({10, 20, 30}))
      :each(function(x) fired[#fired + 1] = x end)
    teq(fired, {10, 20, 30})
  end)

  T.it("each: returns count", function()
    local n = P.pipeline()
      :source(P.from_array({1, 2, 3}))
      :each(function(_) end)
    T.eq(n, 3)
  end)

  T.it("to_set: collects into set", function()
    local result = P.pipeline()
      :source(P.from_array({"a", "b", "a", "c"}))
      :to_set()
    T.eq(result["a"], true)
    T.eq(result["b"], true)
    T.eq(result["c"], true)
    T.eq(result["d"], nil)
  end)

  T.it("group_by: groups correctly", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5, 6}))
      :group_by(function(x) return x % 2 == 0 and "even" or "odd" end)
    teq(result.odd, {1, 3, 5})
    teq(result.even, {2, 4, 6})
  end)

  T.it("partition: splits by predicate", function()
    local yes, no = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5, 6}))
      :partition(function(x) return x % 2 == 0 end)
    teq(yes, {2, 4, 6})
    teq(no, {1, 3, 5})
  end)

  T.it("tap: side-effects without transforming", function()
    local tapped = {}
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3}))
      :tap(function(x) tapped[#tapped + 1] = x end)
      :map(function(x) return x * 2 end)
      :collect()
    teq(result, {2, 4, 6})
    teq(tapped, {1, 2, 3})
  end)

  T.it("drop: skips first n", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :drop(2)
      :collect()
    teq(result, {3, 4, 5})
  end)

  T.it("take_while: stops at first failing element", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :take_while(function(x) return x < 4 end)
      :collect()
    teq(result, {1, 2, 3})
  end)

  T.it("drop_while: drops prefix, keeps rest", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5}))
      :drop_while(function(x) return x < 3 end)
      :collect()
    teq(result, {3, 4, 5})
  end)

  T.it("batch: alias for chunk", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4}))
      :batch(2)
      :collect()
    T.eq(#result, 2)
    teq(result[1], {1, 2})
    teq(result[2], {3, 4})
  end)

  T.it("compose: reusable step composition", function()
    local double_evens = P.compose(
      P.steps.filter(function(x) return x % 2 == 0 end),
      P.steps.map(function(x) return x * 2 end)
    )
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5, 6}))
      :apply(double_evens)
      :collect()
    teq(result, {4, 8, 12})
  end)

  T.it("range source: generates range", function()
    local result = P.pipeline()
      :source(P.range(1, 5))
      :collect()
    teq(result, {1, 2, 3, 4, 5})
  end)

  T.it("range source: step=2", function()
    local result = P.pipeline()
      :source(P.range(0, 10, 2))
      :collect()
    teq(result, {0, 2, 4, 6, 8, 10})
  end)

  T.it("empty pipeline: collect returns empty array", function()
    local result = P.pipeline()
      :source(P.empty())
      :collect()
    T.eq(#result, 0)
  end)

  T.it("empty pipeline: count is 0", function()
    local n = P.pipeline()
      :source(P.empty())
      :count()
    T.eq(n, 0)
  end)

  T.it("infinite source + take: terminates correctly", function()
    local result = P.pipeline()
      :source(P.repeat_value(7))
      :take(5)
      :collect()
    teq(result, {7, 7, 7, 7, 7})
  end)

  T.it("repeat_value: finite repeat", function()
    local result = P.pipeline()
      :source(P.repeat_value("x", 3))
      :collect()
    teq(result, {"x", "x", "x"})
  end)

  T.it("concat_sources: exhaust s1 then s2", function()
    local result = P.pipeline()
      :source(P.concat_sources(P.from_array({1, 2}), P.from_array({3, 4, 5})))
      :collect()
    teq(result, {1, 2, 3, 4, 5})
  end)

  T.it("from_iter: iterator source", function()
    local vals = {10, 20, 30}
    local i = 0
    local result = P.pipeline()
      :source(P.from_iter(function()
        i = i + 1
        return vals[i]
      end))
      :collect()
    teq(result, {10, 20, 30})
  end)

  T.it("steps.scan: composable scan", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4}))
      :apply(P.steps.scan(function(acc, x) return acc + x end, 0))
      :collect()
    teq(result, {1, 3, 6, 10})
  end)

  T.it("steps.unique: composable unique", function()
    local result = P.pipeline()
      :source(P.from_array({1, 1, 2, 3, 2}))
      :apply(P.steps.unique())
      :collect()
    teq(result, {1, 2, 3})
  end)

  T.it("steps.chunk: composable chunk", function()
    local result = P.pipeline()
      :source(P.from_array({1, 2, 3, 4, 5, 6}))
      :apply(P.steps.chunk(3))
      :collect()
    T.eq(#result, 2)
    teq(result[1], {1, 2, 3})
    teq(result[2], {4, 5, 6})
  end)

end)
