-- lib/tracing/tracing_test.lua

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T  = require("lib.test.assert")
local Tr = require("lib.tracing")

-- ── helpers ─────────────────────────────────────────────────────────────────

local function make_provider(seed)
  local exp = Tr.memory_exporter()
  local prov = Tr.provider({ exporter = exp, id_seed = seed or 1 })
  return prov, exp
end

-- ── _tier ────────────────────────────────────────────────────────────────────

T.describe("tracing module", function()
  T.it("_tier is pure", function()
    T.eq(Tr._tier, "pure")
  end)
end)

-- ── Span creation ────────────────────────────────────────────────────────────

T.describe("span creation", function()
  T.it("name is set", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("my-op")
    sp:finish()
    local spans = exp:spans()
    T.eq(spans[1].name, "my-op")
  end)

  T.it("trace_id is 32 hex chars", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    T.eq(type(s.trace_id), "string")
    T.eq(#s.trace_id, 32)
    T.ok(s.trace_id:match("^%x+$"), "trace_id is hex")
  end)

  T.it("span_id is 16 hex chars", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    T.eq(type(s.span_id), "string")
    T.eq(#s.span_id, 16)
    T.ok(s.span_id:match("^%x+$"), "span_id is hex")
  end)

  T.it("root span has no parent_span_id", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    T.eq(s.parent_span_id, nil)
  end)

  T.it("initial status is unset", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    T.eq(exp:spans()[1].status, "unset")
  end)

  T.it("start_time is a number", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    T.eq(type(exp:spans()[1].start_time), "number")
  end)
end)

-- ── Parent / child spans ──────────────────────────────────────────────────────

T.describe("parent/child spans", function()
  T.it("child has parent_span_id equal to parent span_id", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local parent = tr:start_span("parent")
    local child  = tr:start_span("child", { parent = parent })
    child:finish()
    parent:finish()
    local spans = exp:spans()
    -- child finishes first
    T.eq(spans[1].parent_span_id, parent.span_id)
  end)

  T.it("child shares trace_id with parent", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local parent = tr:start_span("parent")
    local child  = tr:start_span("child", { parent = parent })
    child:finish()
    parent:finish()
    local spans = exp:spans()
    T.eq(spans[1].trace_id, spans[2].trace_id)
  end)

  T.it("child via context() carries same trace_id", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local root = tr:start_span("root")
    local ctx  = root:context()
    local child = tr:start_span("child", { context = ctx })
    child:finish()
    root:finish()
    local spans = exp:spans()
    T.eq(spans[1].trace_id, root.trace_id)
    T.eq(spans[1].parent_span_id, root.span_id)
  end)

  T.it("multiple spans in same trace share trace_id", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local root = tr:start_span("root")
    local s1 = tr:start_span("s1", { parent = root })
    local s2 = tr:start_span("s2", { parent = root })
    s1:finish()
    s2:finish()
    root:finish()
    local spans = exp:spans()
    T.eq(#spans, 3)
    T.eq(spans[1].trace_id, spans[2].trace_id)
    T.eq(spans[2].trace_id, spans[3].trace_id)
  end)
end)

-- ── set_attribute ─────────────────────────────────────────────────────────────

T.describe("set_attribute", function()
  T.it("stores string value", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_attribute("http.method", "GET")
    sp:finish()
    T.eq(exp:spans()[1].attributes["http.method"], "GET")
  end)

  T.it("stores number value", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_attribute("http.status", 200)
    sp:finish()
    T.eq(exp:spans()[1].attributes["http.status"], 200)
  end)

  T.it("stores boolean value", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_attribute("cached", true)
    sp:finish()
    T.eq(exp:spans()[1].attributes["cached"], true)
  end)

  T.it("multiple attributes stored independently", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_attribute("a", 1)
    sp:set_attribute("b", 2)
    sp:finish()
    local attrs = exp:spans()[1].attributes
    T.eq(attrs["a"], 1)
    T.eq(attrs["b"], 2)
  end)
end)

-- ── add_event ─────────────────────────────────────────────────────────────────

T.describe("add_event", function()
  T.it("event is appended to events array", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:add_event("cache_miss")
    sp:finish()
    local evts = exp:spans()[1].events
    T.eq(#evts, 1)
    T.eq(evts[1].name, "cache_miss")
  end)

  T.it("event time is a number", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:add_event("e")
    sp:finish()
    T.eq(type(exp:spans()[1].events[1].time), "number")
  end)

  T.it("event attributes stored", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:add_event("db_query", { table = "users", rows = 5 })
    sp:finish()
    local e = exp:spans()[1].events[1]
    T.eq(e.attributes.table, "users")
    T.eq(e.attributes.rows, 5)
  end)

  T.it("multiple events in order", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:add_event("first")
    sp:add_event("second")
    sp:finish()
    local evts = exp:spans()[1].events
    T.eq(#evts, 2)
    T.eq(evts[1].name, "first")
    T.eq(evts[2].name, "second")
  end)

  T.it("event without attributes has empty attributes table", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:add_event("evt")
    sp:finish()
    T.eq(type(exp:spans()[1].events[1].attributes), "table")
  end)
end)

-- ── set_status ────────────────────────────────────────────────────────────────

T.describe("set_status", function()
  T.it("set ok", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_status("ok")
    sp:finish()
    T.eq(exp:spans()[1].status, "ok")
  end)

  T.it("set error without message", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_status("error")
    sp:finish()
    T.eq(exp:spans()[1].status, "error")
    T.eq(exp:spans()[1].status_message, nil)
  end)

  T.it("set error with message", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:set_status("error", "connection refused")
    sp:finish()
    local s = exp:spans()[1]
    T.eq(s.status, "error")
    T.eq(s.status_message, "connection refused")
  end)
end)

-- ── finish ────────────────────────────────────────────────────────────────────

T.describe("finish", function()
  T.it("sets end_time", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    T.ok(exp:spans()[1].end_time ~= nil, "end_time set")
    T.eq(type(exp:spans()[1].end_time), "number")
  end)

  T.it("sets duration_ms", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    T.ok(s.duration_ms ~= nil, "duration_ms set")
    T.ok(s.duration_ms >= 0, "duration_ms non-negative")
  end)

  T.it("duration_ms = (end_time - start_time) * 1000", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    local expected = (s.end_time - s.start_time) * 1000
    T.eq(s.duration_ms, expected)
  end)

  T.it("span exported after finish", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    T.eq(#exp:spans(), 0)
    sp:finish()
    T.eq(#exp:spans(), 1)
  end)

  T.it("finish is idempotent", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    sp:finish()  -- second call is a no-op
    T.eq(#exp:spans(), 1)
  end)
end)

-- ── with_span ─────────────────────────────────────────────────────────────────

T.describe("with_span", function()
  T.it("span is auto-finished", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    tr:with_span("op", function(sp)
      sp:set_attribute("x", 1)
    end)
    local spans = exp:spans()
    T.eq(#spans, 1)
    T.ok(spans[1].end_time ~= nil, "end_time set")
  end)

  T.it("span name is set correctly", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    tr:with_span("my-op", function(_sp) end)
    T.eq(exp:spans()[1].name, "my-op")
  end)

  T.it("attributes set inside fn are preserved", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    tr:with_span("op", function(sp)
      sp:set_attribute("key", "value")
    end)
    T.eq(exp:spans()[1].attributes["key"], "value")
  end)

  T.it("error in fn sets status to error", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local ok = pcall(function()
      tr:with_span("failing", function(_sp)
        error("boom")
      end)
    end)
    T.ok(not ok, "error propagated")
    local s = exp:spans()[1]
    T.eq(s.status, "error")
    T.ok(s.status_message ~= nil, "status_message set on error")
  end)

  T.it("error in fn still finishes span", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    pcall(function()
      tr:with_span("failing", function(_sp)
        error("boom")
      end)
    end)
    T.eq(#exp:spans(), 1)
    T.ok(exp:spans()[1].end_time ~= nil)
  end)

  T.it("accepts opts table before fn", function()
    local prov, exp = make_provider()
    local tr = prov:tracer("svc")
    local parent = tr:start_span("root")
    tr:with_span("child", { parent = parent }, function(sp)
      T.eq(sp.parent_span_id, parent.span_id)
    end)
    parent:finish()
    T.eq(#exp:spans(), 2)
  end)
end)

-- ── memory_exporter ───────────────────────────────────────────────────────────

T.describe("memory_exporter", function()
  T.it("spans() returns all finished spans", function()
    local exp = Tr.memory_exporter()
    local prov = Tr.provider({ exporter = exp, id_seed = 99 })
    local tr = prov:tracer("svc")
    tr:with_span("a", function(_s) end)
    tr:with_span("b", function(_s) end)
    T.eq(#exp:spans(), 2)
  end)

  T.it("spans() returns a copy", function()
    local exp = Tr.memory_exporter()
    local prov = Tr.provider({ exporter = exp, id_seed = 100 })
    local tr = prov:tracer("svc")
    tr:with_span("a", function(_s) end)
    local copy = exp:spans()
    tr:with_span("b", function(_s) end)
    T.eq(#copy, 1)
    T.eq(#exp:spans(), 2)
  end)

  T.it("reset() clears spans", function()
    local exp = Tr.memory_exporter()
    local prov = Tr.provider({ exporter = exp, id_seed = 101 })
    local tr = prov:tracer("svc")
    tr:with_span("a", function(_s) end)
    T.eq(#exp:spans(), 1)
    exp:reset()
    T.eq(#exp:spans(), 0)
  end)

  T.it("reset() then new spans accumulate again", function()
    local exp = Tr.memory_exporter()
    local prov = Tr.provider({ exporter = exp, id_seed = 102 })
    local tr = prov:tracer("svc")
    tr:with_span("a", function(_s) end)
    exp:reset()
    tr:with_span("b", function(_s) end)
    T.eq(#exp:spans(), 1)
    T.eq(exp:spans()[1].name, "b")
  end)
end)

-- ── W3C TraceContext ──────────────────────────────────────────────────────────

T.describe("W3C TraceContext", function()
  T.it("inject produces correctly formatted header", function()
    local prov, exp = make_provider(42)
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    local header = Tr.inject(s)
    T.eq(type(header), "string")
    -- format: 00-{32hex}-{16hex}-01
    T.ok(header:match("^00%-%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%-%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%-01$"),
      "header matches W3C pattern")
  end)

  T.it("extract parses a valid header", function()
    local header = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01"
    local ctx, err = Tr.extract(header)
    T.ok(err == nil, "no error")
    T.eq(ctx.trace_id, "4bf92f3577b34da6a3ce929d0e0e4736")
    T.eq(ctx.span_id,  "00f067aa0ba902b7")
    T.eq(ctx.flags,    "01")
  end)

  T.it("inject/extract round-trip", function()
    local prov, exp = make_provider(55)
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    sp:finish()
    local s = exp:spans()[1]
    local header = Tr.inject(s)
    local ctx, err = Tr.extract(header)
    T.ok(err == nil, "no extract error")
    T.eq(ctx.trace_id, s.trace_id)
    T.eq(ctx.span_id,  s.span_id)
    T.eq(ctx.flags,    "01")
  end)

  T.it("extract returns nil,errmsg for invalid header", function()
    local ctx, err = Tr.extract("not-a-header")
    T.eq(ctx, nil)
    T.ok(type(err) == "string", "error message returned")
  end)

  T.it("extract returns nil,errmsg for non-string", function()
    local ctx, err = Tr.extract(42)
    T.eq(ctx, nil)
    T.ok(type(err) == "string")
  end)

  T.it("child span from extracted context shares trace_id", function()
    local prov, exp = make_provider(77)
    local tr = prov:tracer("svc")
    local sp = tr:start_span("root")
    local header = Tr.inject(sp)
    local ctx = Tr.extract(header)
    local child = tr:start_span("child", { context = ctx })
    child:finish()
    sp:finish()
    local spans = exp:spans()
    T.eq(spans[1].trace_id, spans[2].trace_id)
    T.eq(spans[1].parent_span_id, sp.span_id)
  end)
end)

-- ── to_json ───────────────────────────────────────────────────────────────────

T.describe("to_json", function()
  T.it("returns a non-empty string", function()
    local prov, exp = make_provider(33)
    local tr = prov:tracer("svc")
    tr:with_span("op", function(sp)
      sp:set_attribute("x", 1)
    end)
    local json = Tr.to_json(exp:spans())
    T.ok(type(json) == "string", "returns string")
    T.ok(#json > 0, "non-empty")
  end)

  T.it("contains span name", function()
    local prov, exp = make_provider(34)
    local tr = prov:tracer("svc")
    tr:with_span("my-operation", function(_s) end)
    local json = Tr.to_json(exp:spans())
    T.ok(json:find("my-operation", 1, true), "name present in JSON")
  end)

  T.it("contains trace_id", function()
    local prov, exp = make_provider(35)
    local tr = prov:tracer("svc")
    tr:with_span("op", function(_s) end)
    local s = exp:spans()[1]
    local json = Tr.to_json(exp:spans())
    T.ok(json:find(s.trace_id, 1, true), "trace_id present in JSON")
  end)

  T.it("contains span_id", function()
    local prov, exp = make_provider(36)
    local tr = prov:tracer("svc")
    tr:with_span("op", function(_s) end)
    local s = exp:spans()[1]
    local json = Tr.to_json(exp:spans())
    T.ok(json:find(s.span_id, 1, true), "span_id present in JSON")
  end)

  T.it("contains attribute key and value", function()
    local prov, exp = make_provider(37)
    local tr = prov:tracer("svc")
    tr:with_span("op", function(sp)
      sp:set_attribute("db.table", "orders")
    end)
    local json = Tr.to_json(exp:spans())
    T.ok(json:find("db.table", 1, true), "attr key in JSON")
    T.ok(json:find("orders", 1, true), "attr value in JSON")
  end)

  T.it("returns [] for empty span list", function()
    local json = Tr.to_json({})
    T.eq(json, "[]")
  end)

  T.it("multiple spans produce array with correct count", function()
    local prov, exp = make_provider(38)
    local tr = prov:tracer("svc")
    tr:with_span("a", function(_s) end)
    tr:with_span("b", function(_s) end)
    local json = Tr.to_json(exp:spans())
    -- Count occurrences of "name": which appears once per span
    local count = 0
    for _ in json:gmatch('"name":') do count = count + 1 end
    T.eq(count, 2)
  end)
end)

-- ── deterministic IDs ─────────────────────────────────────────────────────────

T.describe("deterministic IDs via id_seed", function()
  T.it("same seed produces same trace_id", function()
    local exp1 = Tr.memory_exporter()
    local exp2 = Tr.memory_exporter()
    local p1 = Tr.provider({ exporter = exp1, id_seed = 999 })
    local p2 = Tr.provider({ exporter = exp2, id_seed = 999 })
    p1:tracer("svc"):with_span("op", function(_s) end)
    p2:tracer("svc"):with_span("op", function(_s) end)
    T.eq(exp1:spans()[1].trace_id, exp2:spans()[1].trace_id)
  end)

  T.it("same seed produces same span_id", function()
    local exp1 = Tr.memory_exporter()
    local exp2 = Tr.memory_exporter()
    local p1 = Tr.provider({ exporter = exp1, id_seed = 999 })
    local p2 = Tr.provider({ exporter = exp2, id_seed = 999 })
    p1:tracer("svc"):with_span("op", function(_s) end)
    p2:tracer("svc"):with_span("op", function(_s) end)
    T.eq(exp1:spans()[1].span_id, exp2:spans()[1].span_id)
  end)

  T.it("different seeds produce different trace_ids", function()
    local exp1 = Tr.memory_exporter()
    local exp2 = Tr.memory_exporter()
    local p1 = Tr.provider({ exporter = exp1, id_seed = 1 })
    local p2 = Tr.provider({ exporter = exp2, id_seed = 2 })
    p1:tracer("svc"):with_span("op", function(_s) end)
    p2:tracer("svc"):with_span("op", function(_s) end)
    T.neq(exp1:spans()[1].trace_id, exp2:spans()[1].trace_id)
  end)
end)

-- ── noop_exporter ────────────────────────────────────────────────────────────

T.describe("noop_exporter", function()
  T.it("spans() returns empty table", function()
    local exp = Tr.noop_exporter()
    T.eq(#exp:spans(), 0)
  end)

  T.it("does not accumulate spans", function()
    local exp = Tr.noop_exporter()
    local prov = Tr.provider({ exporter = exp, id_seed = 5 })
    prov:tracer("svc"):with_span("op", function(_s) end)
    T.eq(#exp:spans(), 0)
  end)
end)

-- ── span:context() ────────────────────────────────────────────────────────────

T.describe("span:context()", function()
  T.it("returns table with trace_id and span_id", function()
    local prov, _ = make_provider(7)
    local tr = prov:tracer("svc")
    local sp = tr:start_span("op")
    local ctx = sp:context()
    T.eq(ctx.trace_id, sp.trace_id)
    T.eq(ctx.span_id,  sp.span_id)
    sp:finish()
  end)
end)

-- ── span data fields ──────────────────────────────────────────────────────────

T.describe("span data fields", function()
  T.it("attributes is a table", function()
    local prov, exp = make_provider(8)
    local tr = prov:tracer("svc")
    tr:with_span("op", function(_s) end)
    T.eq(type(exp:spans()[1].attributes), "table")
  end)

  T.it("events is an array", function()
    local prov, exp = make_provider(9)
    local tr = prov:tracer("svc")
    tr:with_span("op", function(_s) end)
    T.eq(type(exp:spans()[1].events), "table")
  end)

  T.it("finished span has all required fields", function()
    local prov, exp = make_provider(10)
    local tr = prov:tracer("svc")
    tr:with_span("full-op", function(sp)
      sp:set_attribute("k", "v")
      sp:add_event("e")
      sp:set_status("ok")
    end)
    local s = exp:spans()[1]
    T.ok(s.name ~= nil,        "name")
    T.ok(s.trace_id ~= nil,    "trace_id")
    T.ok(s.span_id ~= nil,     "span_id")
    T.ok(s.start_time ~= nil,  "start_time")
    T.ok(s.end_time ~= nil,    "end_time")
    T.ok(s.duration_ms ~= nil, "duration_ms")
    T.ok(s.attributes ~= nil,  "attributes")
    T.ok(s.events ~= nil,      "events")
    T.ok(s.status ~= nil,      "status")
  end)
end)
