if not package.path:find("./?/init.lua", 1, true) then
	package.path = "./?/init.lua;" .. package.path
end

local P = require("lib.path")
local T = require("lib.test.assert")

T.describe("path.join", function()
	T.it("joins relative components", function()
		T.eq(P.join("a", "b", "c"), "a/b/c")
	end)
	T.it("joins under absolute base", function()
		T.eq(P.join("/foo", "bar", "baz"), "/foo/bar/baz")
	end)
	T.it("absolute component resets path", function()
		T.eq(P.join("a/b", "/c"), "/c")
	end)
	T.it("trailing sep on first component", function()
		T.eq(P.join("a/", "b"), "a/b")
	end)
	T.it("empty components are skipped", function()
		T.eq(P.join("", "a", "", "b"), "a/b")
	end)
	T.it("single component returns it", function()
		T.eq(P.join("foo"), "foo")
	end)
	T.it("two absolute components — last wins", function()
		T.eq(P.join("/a", "/b"), "/b")
	end)
end)

T.describe("path.split", function()
	T.it("normal path", function()
		local d, f = P.split("/foo/bar.txt")
		T.eq(d, "/foo")
		T.eq(f, "bar.txt")
	end)
	T.it("no directory", function()
		local d, f = P.split("file.txt")
		T.eq(d, ".")
		T.eq(f, "file.txt")
	end)
	T.it("root file", function()
		local d, f = P.split("/file.txt")
		T.eq(d, "/")
		T.eq(f, "file.txt")
	end)
	T.it("trailing slash — empty filename", function()
		local d, f = P.split("a/b/")
		T.eq(d, "a/b")
		T.eq(f, "")
	end)
end)

T.describe("path.basename", function()
	T.it("normal path", function()
		T.eq(P.basename("a/b/c.txt"), "c.txt")
	end)
	T.it("trailing slash stripped", function()
		T.eq(P.basename("a/b/"), "b")
	end)
	T.it("no separator", function()
		T.eq(P.basename("file.txt"), "file.txt")
	end)
	T.it("root returns empty", function()
		T.eq(P.basename("/"), "")
	end)
end)

T.describe("path.dirname", function()
	T.it("normal path", function()
		T.eq(P.dirname("a/b/c.txt"), "a/b")
	end)
	T.it("no dir returns dot", function()
		T.eq(P.dirname("file.txt"), ".")
	end)
	T.it("root returns root", function()
		T.eq(P.dirname("/"), "/")
	end)
	T.it("one level deep", function()
		T.eq(P.dirname("/foo"), "/")
	end)
end)

T.describe("path.splitext", function()
	T.it("simple extension", function()
		local r, e = P.splitext("file.txt")
		T.eq(r, "file")
		T.eq(e, ".txt")
	end)
	T.it("multiple dots — only last is ext", function()
		local r, e = P.splitext("file.tar.gz")
		T.eq(r, "file.tar")
		T.eq(e, ".gz")
	end)
	T.it("no extension", function()
		local r, e = P.splitext("file")
		T.eq(r, "file")
		T.eq(e, "")
	end)
	T.it("dotfile has no extension", function()
		local r, e = P.splitext(".dotfile")
		T.eq(r, ".dotfile")
		T.eq(e, "")
	end)
	T.it("dotfile with extension", function()
		local r, e = P.splitext(".dotfile.bak")
		T.eq(r, ".dotfile")
		T.eq(e, ".bak")
	end)
	T.it("path with directory", function()
		local r, e = P.splitext("a/b/file.txt")
		T.eq(r, "a/b/file")
		T.eq(e, ".txt")
	end)
end)

T.describe("path.ext", function()
	T.it("returns extension", function()
		T.eq(P.ext("file.txt"), ".txt")
	end)
	T.it("no extension returns empty", function()
		T.eq(P.ext("file"), "")
	end)
	T.it("dotfile returns empty", function()
		T.eq(P.ext(".bashrc"), "")
	end)
end)

T.describe("path.is_absolute", function()
	T.it("unix absolute", function()
		T.ok(P.is_absolute("/foo/bar"))
	end)
	T.it("relative is not absolute", function()
		T.ok(not P.is_absolute("foo/bar"))
	end)
	T.it("empty is not absolute", function()
		T.ok(not P.is_absolute(""))
	end)
	T.it("root is absolute", function()
		T.ok(P.is_absolute("/"))
	end)
	T.it("dot is not absolute", function()
		T.ok(not P.is_absolute("."))
	end)
end)

T.describe("path.normalize", function()
	T.it("removes dot", function()
		T.eq(P.normalize("a/./b"), "a/b")
	end)
	T.it("resolves dotdot", function()
		T.eq(P.normalize("a/b/../c"), "a/c")
	end)
	T.it("collapses double slash", function()
		T.eq(P.normalize("a//b"), "a/b")
	end)
	T.it("dotdot at root does not go above root", function()
		T.eq(P.normalize("/a/b/../../c"), "/c")
	end)
	T.it("dotdot clamped at absolute root", function()
		T.eq(P.normalize("/a/../../b"), "/b")
	end)
	T.it("relative dotdot accumulates", function()
		T.eq(P.normalize("a/../../b"), "../b")
	end)
	T.it("empty-like reduces to dot", function()
		T.eq(P.normalize("a/b/.."), "a")
	end)
	T.it("just dot stays dot", function()
		T.eq(P.normalize("."), ".")
	end)
	T.it("root stays root", function()
		T.eq(P.normalize("/"), "/")
	end)
end)

T.describe("path.relative", function()
	T.it("child path", function()
		T.eq(P.relative("a/b/c", "a/b"), "c")
	end)
	T.it("absolute paths", function()
		T.eq(P.relative("/foo/bar", "/foo"), "bar")
	end)
	T.it("cross-directory uses dotdot", function()
		T.eq(P.relative("a/b", "a/c"), "../b")
	end)
	T.it("same path returns dot", function()
		T.eq(P.relative("a/b", "a/b"), ".")
	end)
	T.it("ancestor", function()
		T.eq(P.relative("a", "a/b/c"), "../..")
	end)
end)

T.describe("path.parts", function()
	T.it("relative path", function()
		local p = P.parts("a/b/c")
		T.eq(#p, 3)
		T.eq(p[1], "a")
		T.eq(p[2], "b")
		T.eq(p[3], "c")
	end)
	T.it("absolute unix path", function()
		local p = P.parts("/a/b/c")
		T.eq(p[1], "/")
		T.eq(p[2], "a")
		T.eq(p[3], "b")
		T.eq(p[4], "c")
	end)
	T.it("single component", function()
		local p = P.parts("foo")
		T.eq(#p, 1)
		T.eq(p[1], "foo")
	end)
	T.it("root only", function()
		local p = P.parts("/")
		T.eq(#p, 1)
		T.eq(p[1], "/")
	end)
end)

T.describe("path.commonpath", function()
	T.it("same prefix two paths", function()
		T.eq(P.commonpath({"a/b/c", "a/b/d"}), "a/b")
	end)
	T.it("different depths", function()
		T.eq(P.commonpath({"a/b/c/d", "a/b"}), "a/b")
	end)
	T.it("no common prefix", function()
		T.eq(P.commonpath({"a/b", "c/d"}), "")
	end)
	T.it("single path returns itself normalized", function()
		T.eq(P.commonpath({"a/b/c"}), "a/b/c")
	end)
	T.it("identical paths", function()
		T.eq(P.commonpath({"a/b", "a/b"}), "a/b")
	end)
	T.it("three paths", function()
		T.eq(P.commonpath({"a/b/c", "a/b/d", "a/b/e"}), "a/b")
	end)
end)

T.describe("path.expanduser", function()
	T.it("non-tilde path unchanged", function()
		T.eq(P.expanduser("/foo/bar"), "/foo/bar")
	end)
	T.it("tilde-only returns home", function()
		local home = os.getenv("HOME") or os.getenv("USERPROFILE") or ""
		T.eq(P.expanduser("~"), home)
	end)
	T.it("tilde prefix expanded", function()
		local home = os.getenv("HOME") or os.getenv("USERPROFILE") or ""
		local result = P.expanduser("~/foo")
		if home ~= "" then
			T.eq(result, home .. "/foo")
		else
			T.eq(result, "~/foo")
		end
	end)
end)

T.describe("safe_resolve", function()
	T.it("resolves normal relative path", function()
		T.eq(P.safe_resolve("static", "index.html"), "static/index.html")
	end)
	T.it("resolves nested path", function()
		T.eq(P.safe_resolve("static", "css/style.css"), "static/css/style.css")
	end)
	T.it("rejects traversal above base", function()
		T.eq(P.safe_resolve("static", "../etc/passwd"), nil)
	end)
	T.it("rejects double traversal", function()
		T.eq(P.safe_resolve("static", "../../etc/passwd"), nil)
	end)
	T.it("rejects absolute path", function()
		T.eq(P.safe_resolve("static", "/etc/passwd"), nil)
	end)
	T.it("rejects empty string", function()
		T.eq(P.safe_resolve("static", ""), nil)
	end)
	T.it("rejects nil", function()
		T.eq(P.safe_resolve("static", nil), nil)
	end)
	T.it("allows dot (base itself)", function()
		T.eq(P.safe_resolve("static", "."), "static")
	end)
	T.it("resolves with dot-dot that stays in base", function()
		T.eq(P.safe_resolve("static", "sub/../file.txt"), "static/file.txt")
	end)
end)
