-- lib/metric/metric_test.lua
-- Tests for lib/metric: counter, gauge, histogram, summary, render, registry.

if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local M = require("lib.metric")

-- ── Counter ───────────────────────────────────────────────────────────────────

T.describe("counter", function()
  T.it("starts at zero for unseen label sets", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    T.eq(c:get({method="GET"}), 0)
    T.eq(c:get({method="POST"}), 0)
  end)

  T.it("inc by 1", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    c:inc({method="GET"})
    T.eq(c:get({method="GET"}), 1)
  end)

  T.it("inc by N", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    c:inc({method="GET"}, 5)
    T.eq(c:get({method="GET"}), 5)
  end)

  T.it("inc accumulates", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    c:inc({method="GET"})
    c:inc({method="GET"}, 3)
    T.eq(c:get({method="GET"}), 4)
  end)

  T.it("multi-label sets are independent", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method", "status"})
    c:inc({method="GET", status="200"})
    c:inc({method="POST", status="500"}, 3)
    T.eq(c:get({method="GET", status="200"}), 1)
    T.eq(c:get({method="POST", status="500"}), 3)
    T.eq(c:get({method="GET", status="500"}), 0)
  end)

  T.it("no labels counter works", function()
    local reg = M.registry()
    local c = reg:counter("simple_total", "help", {})
    c:inc({})
    c:inc({}, 9)
    T.eq(c:get({}), 10)
  end)

  T.it("errors on negative increment", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    T.throws(function() c:inc({method="GET"}, -1) end)
  end)

  T.it("errors on missing label", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method", "status"})
    T.throws(function() c:inc({method="GET"}) end)
  end)

  T.it("errors on extra label", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    T.throws(function() c:inc({method="GET", extra="bad"}) end)
  end)
end)

-- ── Gauge ─────────────────────────────────────────────────────────────────────

T.describe("gauge", function()
  T.it("starts at zero for unseen label sets", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    T.eq(g:get({queue="main"}), 0)
  end)

  T.it("set absolute value", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:set({queue="main"}, 42)
    T.eq(g:get({queue="main"}), 42)
  end)

  T.it("set can decrease", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:set({queue="main"}, 10)
    g:set({queue="main"}, 3)
    T.eq(g:get({queue="main"}), 3)
  end)

  T.it("inc by 1", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:inc({queue="main"})
    T.eq(g:get({queue="main"}), 1)
  end)

  T.it("inc by N", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:inc({queue="main"}, 5)
    T.eq(g:get({queue="main"}), 5)
  end)

  T.it("dec by 1", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:set({queue="main"}, 10)
    g:dec({queue="main"})
    T.eq(g:get({queue="main"}), 9)
  end)

  T.it("dec by N", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:set({queue="main"}, 20)
    g:dec({queue="main"}, 5)
    T.eq(g:get({queue="main"}), 15)
  end)

  T.it("gauge can go negative", function()
    local reg = M.registry()
    local g = reg:gauge("temp", "help", {})
    g:dec({}, 3)
    T.eq(g:get({}), -3)
  end)

  T.it("multi-label sets are independent", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:set({queue="main"}, 5)
    g:set({queue="other"}, 99)
    T.eq(g:get({queue="main"}), 5)
    T.eq(g:get({queue="other"}), 99)
  end)
end)

-- ── Histogram ─────────────────────────────────────────────────────────────────

T.describe("histogram", function()
  T.it("observe increases count", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5, 1})
    h:observe({method="GET"}, 0.042)
    T.eq(h:count({method="GET"}), 1)
  end)

  T.it("observe accumulates sum", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5, 1})
    h:observe({method="GET"}, 0.1)
    h:observe({method="GET"}, 0.3)
    T.eq(h:sum({method="GET"}), 0.4)
  end)

  T.it("observe multiple times accumulates count", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5, 1})
    h:observe({method="GET"}, 0.05)
    h:observe({method="GET"}, 0.2)
    h:observe({method="GET"}, 0.8)
    T.eq(h:count({method="GET"}), 3)
  end)

  T.it("bucket distribution is cumulative", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5, 1})
    h:observe({method="GET"}, 0.05)  -- fits in 0.1, 0.5, 1, +Inf
    h:observe({method="GET"}, 0.2)   -- fits in 0.5, 1, +Inf
    h:observe({method="GET"}, 0.8)   -- fits in 1, +Inf
    local bkts = h:buckets({method="GET"})
    T.eq(bkts[0.1], 1)
    T.eq(bkts[0.5], 2)
    T.eq(bkts[1],   3)
    T.eq(bkts[math.huge], 3)  -- +Inf always equals count
  end)

  T.it("+Inf bucket always equals total count", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {}, {0.1})
    h:observe({}, 1000)
    h:observe({}, 2000)
    local bkts = h:buckets({})
    T.eq(bkts[math.huge], 2)
    T.eq(h:count({}), 2)
  end)

  T.it("zero for unseen label set (count/sum)", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1})
    T.eq(h:count({method="GET"}), 0)
    T.eq(h:sum({method="GET"}), 0)
  end)

  T.it("zero for unseen label set (buckets)", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5})
    local bkts = h:buckets({method="GET"})
    T.eq(bkts[0.1], 0)
    T.eq(bkts[0.5], 0)
    T.eq(bkts[math.huge], 0)
  end)

  T.it("uses default buckets when none provided", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {})
    h:observe({}, 0.003)
    local bkts = h:buckets({})
    -- default has 0.005 as first bucket
    T.eq(bkts[0.005], 1)
    T.eq(bkts[0.01],  1)
    T.eq(bkts[10],    1)
    T.eq(bkts[math.huge], 1)
  end)

  T.it("multi-label sets are independent", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.5})
    h:observe({method="GET"}, 0.1)
    h:observe({method="POST"}, 0.9)
    T.eq(h:count({method="GET"}), 1)
    T.eq(h:count({method="POST"}), 1)
    T.eq(h:sum({method="GET"}), 0.1)
    T.eq(h:sum({method="POST"}), 0.9)
  end)
end)

-- ── Summary ───────────────────────────────────────────────────────────────────

T.describe("summary", function()
  T.it("observe increases count", function()
    local reg = M.registry()
    local s = reg:summary("resp_size", "help", {"endpoint"})
    s:observe({endpoint="/api"}, 1024)
    T.eq(s:count({endpoint="/api"}), 1)
  end)

  T.it("observe accumulates sum", function()
    local reg = M.registry()
    local s = reg:summary("resp_size", "help", {"endpoint"})
    s:observe({endpoint="/api"}, 1024)
    s:observe({endpoint="/api"}, 2048)
    T.eq(s:sum({endpoint="/api"}), 3072)
  end)

  T.it("zero for unseen label set", function()
    local reg = M.registry()
    local s = reg:summary("resp_size", "help", {"endpoint"})
    T.eq(s:count({endpoint="/api"}), 0)
    T.eq(s:sum({endpoint="/api"}), 0)
  end)

  T.it("multi-label sets are independent", function()
    local reg = M.registry()
    local s = reg:summary("resp_size", "help", {"endpoint"})
    s:observe({endpoint="/api"}, 100)
    s:observe({endpoint="/home"}, 200)
    T.eq(s:sum({endpoint="/api"}), 100)
    T.eq(s:sum({endpoint="/home"}), 200)
  end)

  T.it("no labels summary works", function()
    local reg = M.registry()
    local s = reg:summary("simple", "help", {})
    s:observe({}, 5)
    s:observe({}, 5)
    T.eq(s:count({}), 2)
    T.eq(s:sum({}), 10)
  end)
end)

-- ── render() ─────────────────────────────────────────────────────────────────

T.describe("render", function()
  T.it("counter emits HELP and TYPE lines", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "Total HTTP requests", {"method"})
    c:inc({method="GET"})
    local text = reg:render()
    T.ok(text:find("# HELP req_total Total HTTP requests", 1, true), "HELP line")
    T.ok(text:find("# TYPE req_total counter", 1, true), "TYPE line")
  end)

  T.it("counter emits label=value pairs", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method", "status"})
    c:inc({method="GET", status="200"})
    local text = reg:render()
    T.ok(text:find('method="GET"', 1, true), "method label")
    T.ok(text:find('status="200"', 1, true), "status label")
    T.ok(text:find("req_total{", 1, true), "metric name with labels")
  end)

  T.it("counter value is correct in output", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    c:inc({method="GET"}, 7)
    local text = reg:render()
    T.ok(text:find("} 7", 1, true), "value 7 in output")
  end)

  T.it("gauge emits TYPE gauge", function()
    local reg = M.registry()
    local g = reg:gauge("queue_depth", "help", {"queue"})
    g:set({queue="main"}, 42)
    local text = reg:render()
    T.ok(text:find("# TYPE queue_depth gauge", 1, true), "TYPE gauge")
    T.ok(text:find("} 42", 1, true), "value 42")
  end)

  T.it("histogram emits _bucket, _sum, _count", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5})
    h:observe({method="GET"}, 0.05)
    local text = reg:render()
    T.ok(text:find("# TYPE latency histogram", 1, true), "TYPE histogram")
    T.ok(text:find("latency_bucket{", 1, true), "_bucket lines")
    T.ok(text:find("latency_sum{", 1, true), "_sum line")
    T.ok(text:find("latency_count{", 1, true), "_count line")
  end)

  T.it("histogram bucket has le label", function()
    local reg = M.registry()
    local h = reg:histogram("latency", "help", {"method"}, {0.1, 0.5})
    h:observe({method="GET"}, 0.05)
    local text = reg:render()
    T.ok(text:find('le="0.1"', 1, true), "le=0.1 bucket")
    T.ok(text:find('le="0.5"', 1, true), "le=0.5 bucket")
    T.ok(text:find('le="+Inf"', 1, true), "+Inf bucket")
  end)

  T.it("summary emits _sum and _count", function()
    local reg = M.registry()
    local s = reg:summary("resp_size", "help", {"endpoint"})
    s:observe({endpoint="/api"}, 512)
    local text = reg:render()
    T.ok(text:find("# TYPE resp_size summary", 1, true), "TYPE summary")
    T.ok(text:find("resp_size_sum{", 1, true), "_sum line")
    T.ok(text:find("resp_size_count{", 1, true), "_count line")
  end)

  T.it("no-label metric renders without braces", function()
    local reg = M.registry()
    local c = reg:counter("simple_total", "help", {})
    c:inc({})
    local text = reg:render()
    T.ok(text:find("simple_total 1", 1, true), "no-label counter line")
  end)

  T.it("multiple metrics rendered in registration order", function()
    local reg = M.registry()
    reg:counter("aaa", "help", {})
    reg:gauge("bbb", "help", {})
    local text = reg:render()
    local pos_a = text:find("aaa", 1, true)
    local pos_b = text:find("bbb", 1, true)
    T.ok(pos_a ~= nil, "aaa present")
    T.ok(pos_b ~= nil, "bbb present")
    T.ok(pos_a < pos_b, "aaa before bbb")
  end)

  T.it("labels are sorted alphabetically in output", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"z_label", "a_label"})
    c:inc({z_label="Z", a_label="A"})
    local text = reg:render()
    -- a_label should appear before z_label in the label string
    local pa = text:find('a_label="A"', 1, true)
    local pz = text:find('z_label="Z"', 1, true)
    T.ok(pa ~= nil, "a_label present")
    T.ok(pz ~= nil, "z_label present")
    T.ok(pa < pz, "a_label before z_label (sorted)")
  end)

  T.it("render ends with newline", function()
    local reg = M.registry()
    reg:counter("x", "h", {})
    local text = reg:render()
    T.eq(text:sub(-1), "\n", "ends with newline")
  end)
end)

-- ── reset() ───────────────────────────────────────────────────────────────────

T.describe("reset", function()
  T.it("counter values cleared after reset", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    c:inc({method="GET"}, 10)
    reg:reset()
    T.eq(c:get({method="GET"}), 0)
  end)

  T.it("gauge values cleared after reset", function()
    local reg = M.registry()
    local g = reg:gauge("q", "help", {})
    g:set({}, 99)
    reg:reset()
    T.eq(g:get({}), 0)
  end)

  T.it("histogram cleared after reset", function()
    local reg = M.registry()
    local h = reg:histogram("lat", "help", {}, {1})
    h:observe({}, 0.5)
    reg:reset()
    T.eq(h:count({}), 0)
    T.eq(h:sum({}), 0)
  end)

  T.it("summary cleared after reset", function()
    local reg = M.registry()
    local s = reg:summary("sz", "help", {})
    s:observe({}, 100)
    reg:reset()
    T.eq(s:count({}), 0)
    T.eq(s:sum({}), 0)
  end)

  T.it("metrics still registered (name/type intact) after reset", function()
    local reg = M.registry()
    reg:counter("req_total", "help", {"method"})
    reg:reset()
    -- registering the same name again should fail (still registered)
    T.throws(function() reg:counter("req_total", "help", {"method"}) end)
  end)
end)

-- ── Error: duplicate metric name ──────────────────────────────────────────────

T.describe("duplicate metric name", function()
  T.it("registering same name twice throws", function()
    local reg = M.registry()
    reg:counter("foo_total", "help", {})
    T.throws(function() reg:counter("foo_total", "other help", {}) end)
  end)

  T.it("registering same name as different type throws", function()
    local reg = M.registry()
    reg:counter("foo_total", "help", {})
    T.throws(function() reg:gauge("foo_total", "help", {}) end)
  end)
end)

-- ── Error: wrong label set ────────────────────────────────────────────────────

T.describe("wrong label set", function()
  T.it("missing label on counter:get throws", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method", "status"})
    T.throws(function() c:get({method="GET"}) end)
  end)

  T.it("extra label on counter:inc throws", function()
    local reg = M.registry()
    local c = reg:counter("req_total", "help", {"method"})
    T.throws(function() c:inc({method="GET", bogus="x"}) end)
  end)

  T.it("missing label on gauge:set throws", function()
    local reg = M.registry()
    local g = reg:gauge("q", "help", {"queue"})
    T.throws(function() g:set({}, 1) end)
  end)

  T.it("missing label on histogram:observe throws", function()
    local reg = M.registry()
    local h = reg:histogram("lat", "help", {"method"}, {1})
    T.throws(function() h:observe({}, 0.5) end)
  end)

  T.it("missing label on summary:observe throws", function()
    local reg = M.registry()
    local s = reg:summary("sz", "help", {"endpoint"})
    T.throws(function() s:observe({}, 100) end)
  end)
end)

-- ── Global default registry convenience ──────────────────────────────────────

T.describe("global registry", function()
  T.it("M.counter/gauge/histogram/summary are functions", function()
    T.eq(type(M.counter), "function")
    T.eq(type(M.gauge), "function")
    T.eq(type(M.histogram), "function")
    T.eq(type(M.summary), "function")
    T.eq(type(M.render), "function")
  end)

  T.it("M.render returns a string", function()
    -- reset default registry to known state
    M._reset_default()
    local text = M.render()
    T.eq(type(text), "string")
  end)

  T.it("M.counter adds to default registry and appears in M.render", function()
    M._reset_default()
    local c = M.counter("global_req", "help", {"method"})
    c:inc({method="GET"}, 2)
    local text = M.render()
    T.ok(text:find("global_req", 1, true), "metric in render output")
    T.ok(text:find("} 2", 1, true), "value in render output")
  end)

  T.it("M.gauge adds to default registry", function()
    M._reset_default()
    local g = M.gauge("global_depth", "help", {})
    g:set({}, 7)
    local text = M.render()
    T.ok(text:find("global_depth", 1, true))
    T.ok(text:find("# TYPE global_depth gauge", 1, true))
  end)

  T.it("M.histogram adds to default registry", function()
    M._reset_default()
    local h = M.histogram("global_lat", "help", {}, {1})
    h:observe({}, 0.5)
    local text = M.render()
    T.ok(text:find("global_lat_bucket", 1, true))
  end)

  T.it("M.summary adds to default registry", function()
    M._reset_default()
    local s = M.summary("global_sz", "help", {})
    s:observe({}, 100)
    local text = M.render()
    T.ok(text:find("global_sz_sum", 1, true))
  end)
end)
