if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local set = require("lib.set")

T.describe("set", function()

  T.describe("construction", function()
    T.it("creates an empty set with new()", function()
      local s = set.new()
      T.eq(s:size(), 0)
      T.ok(s:empty())
    end)

    T.it("creates a set from an array", function()
      local s = set.from_array({1, 2, 3})
      T.eq(s:size(), 3)
      T.ok(s:has(1))
      T.ok(s:has(2))
      T.ok(s:has(3))
    end)

    T.it("deduplicates values from array", function()
      local s = set.from_array({1, 2, 2, 3, 3, 3})
      T.eq(s:size(), 3)
    end)

    T.it("handles empty array", function()
      local s = set.from_array({})
      T.eq(s:size(), 0)
      T.ok(s:empty())
    end)
  end)

  T.describe("add/remove/has", function()
    T.it("adds and checks membership", function()
      local s = set.new()
      s:add(42)
      T.ok(s:has(42))
      T.ok(not s:has(99))
      T.eq(s:size(), 1)
    end)

    T.it("ignores duplicate adds", function()
      local s = set.new()
      s:add(1)
      s:add(1)
      s:add(1)
      T.eq(s:size(), 1)
    end)

    T.it("removes an element", function()
      local s = set.from_array({1, 2, 3})
      s:remove(2)
      T.eq(s:size(), 2)
      T.ok(not s:has(2))
      T.ok(s:has(1))
      T.ok(s:has(3))
    end)

    T.it("removing non-existent element is a no-op", function()
      local s = set.from_array({1})
      s:remove(99)
      T.eq(s:size(), 1)
    end)

    T.it("returns error when adding nil", function()
      local s = set.new()
      local ok, err = s:add(nil)
      T.eq(ok, nil)
      T.ok(err:find("nil"))
    end)

    T.it("supports string values", function()
      local s = set.from_array({"a", "b", "c"})
      T.eq(s:size(), 3)
      T.ok(s:has("a"))
      T.ok(not s:has("d"))
    end)

    T.it("supports boolean values", function()
      local s = set.new()
      s:add(true)
      s:add(false)
      T.eq(s:size(), 2)
      T.ok(s:has(true))
      T.ok(s:has(false))
    end)

    T.it("supports mixed types", function()
      local s = set.new()
      s:add(1)
      s:add("1")
      s:add(true)
      T.eq(s:size(), 3)
    end)
  end)

  T.describe("to_array/values", function()
    T.it("converts to array", function()
      local s = set.from_array({3, 1, 2})
      local arr = s:to_array()
      T.eq(#arr, 3)
      table.sort(arr)
      T.eq(arr[1], 1)
      T.eq(arr[2], 2)
      T.eq(arr[3], 3)
    end)

    T.it("empty set gives empty array", function()
      local s = set.new()
      T.eq(#s:to_array(), 0)
    end)

    T.it("values() iterates all elements", function()
      local s = set.from_array({10, 20, 30})
      local seen = {}
      for v in s:values() do
        seen[v] = true
      end
      T.ok(seen[10])
      T.ok(seen[20])
      T.ok(seen[30])
    end)
  end)

  T.describe("union", function()
    T.it("unions two sets", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({3, 4, 5})
      local c = a:union(b)
      T.eq(c:size(), 5)
      T.ok(c:has(1))
      T.ok(c:has(5))
    end)

    T.it("union with empty set returns copy", function()
      local a = set.from_array({1, 2})
      local c = a:union(set.new())
      T.eq(c:size(), 2)
      T.ok(c:has(1))
    end)

    T.it("module-level union works", function()
      local a = set.from_array({1})
      local b = set.from_array({2})
      local c = set.union(a, b)
      T.eq(c:size(), 2)
    end)
  end)

  T.describe("intersection", function()
    T.it("intersects two sets", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({2, 3, 4})
      local c = a:intersection(b)
      T.eq(c:size(), 2)
      T.ok(c:has(2))
      T.ok(c:has(3))
      T.ok(not c:has(1))
      T.ok(not c:has(4))
    end)

    T.it("intersection of disjoint sets is empty", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({3, 4})
      local c = a:intersection(b)
      T.eq(c:size(), 0)
    end)

    T.it("module-level intersection works", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({2, 3, 4})
      local c = set.intersection(a, b)
      T.eq(c:size(), 2)
    end)
  end)

  T.describe("difference", function()
    T.it("computes set difference", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({2, 3, 4})
      local c = a:difference(b)
      T.eq(c:size(), 1)
      T.ok(c:has(1))
      T.ok(not c:has(2))
    end)

    T.it("difference with empty set returns copy", function()
      local a = set.from_array({1, 2})
      local c = a:difference(set.new())
      T.eq(c:size(), 2)
    end)

    T.it("difference from superset is empty", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({1, 2, 3})
      local c = a:difference(b)
      T.eq(c:size(), 0)
    end)
  end)

  T.describe("symmetric_difference", function()
    T.it("computes symmetric difference", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({2, 3, 4})
      local c = a:symmetric_difference(b)
      T.eq(c:size(), 2)
      T.ok(c:has(1))
      T.ok(c:has(4))
      T.ok(not c:has(2))
    end)

    T.it("symmetric difference of identical sets is empty", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({1, 2, 3})
      local c = a:symmetric_difference(b)
      T.eq(c:size(), 0)
    end)

    T.it("symmetric difference of disjoint sets is union", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({3, 4})
      local c = a:symmetric_difference(b)
      T.eq(c:size(), 4)
    end)
  end)

  T.describe("subset/superset/disjoint", function()
    T.it("subset check", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({1, 2, 3})
      T.ok(a:is_subset(b))
      T.ok(not b:is_subset(a))
    end)

    T.it("set is subset of itself", function()
      local a = set.from_array({1, 2, 3})
      T.ok(a:is_subset(a))
    end)

    T.it("empty set is subset of everything", function()
      local e = set.new()
      local a = set.from_array({1})
      T.ok(e:is_subset(a))
      T.ok(e:is_subset(e))
    end)

    T.it("superset check", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({1, 2})
      T.ok(a:is_superset(b))
      T.ok(not b:is_superset(a))
    end)

    T.it("disjoint check", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({3, 4})
      T.ok(a:is_disjoint(b))
    end)

    T.it("overlapping sets are not disjoint", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({2, 3})
      T.ok(not a:is_disjoint(b))
    end)

    T.it("empty set is disjoint with everything", function()
      local e = set.new()
      local a = set.from_array({1})
      T.ok(e:is_disjoint(a))
      T.ok(e:is_disjoint(e))
    end)
  end)

  T.describe("eq", function()
    T.it("equal sets", function()
      local a = set.from_array({1, 2, 3})
      local b = set.from_array({3, 2, 1})
      T.ok(a:eq(b))
    end)

    T.it("unequal sets (different size)", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({1, 2, 3})
      T.ok(not a:eq(b))
    end)

    T.it("unequal sets (same size)", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({1, 3})
      T.ok(not a:eq(b))
    end)

    T.it("empty sets are equal", function()
      T.ok(set.new():eq(set.new()))
    end)
  end)

  T.describe("map/filter/reduce/for_each", function()
    T.it("maps values", function()
      local s = set.from_array({1, 2, 3})
      local doubled = s:map(function(v) return v * 2 end)
      T.eq(doubled:size(), 3)
      T.ok(doubled:has(2))
      T.ok(doubled:has(4))
      T.ok(doubled:has(6))
    end)

    T.it("map can collapse values", function()
      local s = set.from_array({1, 2, 3, 4})
      local modded = s:map(function(v) return v % 2 end)
      T.eq(modded:size(), 2)
      T.ok(modded:has(0))
      T.ok(modded:has(1))
    end)

    T.it("filters values", function()
      local s = set.from_array({1, 2, 3, 4, 5})
      local evens = s:filter(function(v) return v % 2 == 0 end)
      T.eq(evens:size(), 2)
      T.ok(evens:has(2))
      T.ok(evens:has(4))
    end)

    T.it("reduce accumulates", function()
      local s = set.from_array({1, 2, 3})
      local sum = s:reduce(0, function(acc, v) return acc + v end)
      T.eq(sum, 6)
    end)

    T.it("reduce on empty set returns init", function()
      local s = set.new()
      local result = s:reduce(42, function(acc, v) return acc + v end)
      T.eq(result, 42)
    end)

    T.it("for_each visits all elements", function()
      local s = set.from_array({10, 20, 30})
      local total = 0
      s:for_each(function(v) total = total + v end)
      T.eq(total, 60)
    end)
  end)

  T.describe("copy/clear", function()
    T.it("copy creates independent set", function()
      local a = set.from_array({1, 2, 3})
      local b = a:copy()
      T.ok(a:eq(b))
      b:add(4)
      T.ok(not a:has(4))
      T.eq(a:size(), 3)
      T.eq(b:size(), 4)
    end)

    T.it("clear empties the set", function()
      local s = set.from_array({1, 2, 3})
      s:clear()
      T.eq(s:size(), 0)
      T.ok(s:empty())
      T.ok(not s:has(1))
    end)
  end)

  T.describe("tostring", function()
    T.it("empty set", function()
      T.eq(tostring(set.new()), "Set{}")
    end)

    T.it("single element", function()
      T.eq(tostring(set.from_array({1})), "Set{1}")
    end)

    T.it("sorted output", function()
      local s = set.from_array({3, 1, 2})
      T.eq(tostring(s), "Set{1, 2, 3}")
    end)
  end)

  T.describe("edge cases", function()
    T.it("single element set operations", function()
      local a = set.from_array({1})
      local b = set.from_array({1})
      T.ok(a:eq(b))
      T.eq(a:union(b):size(), 1)
      T.eq(a:intersection(b):size(), 1)
      T.eq(a:difference(b):size(), 0)
      T.eq(a:symmetric_difference(b):size(), 0)
    end)

    T.it("operations do not mutate originals", function()
      local a = set.from_array({1, 2})
      local b = set.from_array({2, 3})
      a:union(b)
      a:intersection(b)
      a:difference(b)
      a:symmetric_difference(b)
      T.eq(a:size(), 2)
      T.eq(b:size(), 2)
    end)

    T.it("large set", function()
      local s = set.new()
      for i = 1, 1000 do s:add(i) end
      T.eq(s:size(), 1000)
      T.ok(s:has(500))
      s:remove(500)
      T.eq(s:size(), 999)
      T.ok(not s:has(500))
    end)
  end)
end)
