if not package.path:find("./?/init.lua", 1, true) then
  package.path = "./?/init.lua;" .. package.path
end

local T = require("lib.test.assert")
local cron = require("lib.cron")

-- Helper: make a timestamp for a specific date/time
local function mktime(year, month, day, hour, min, sec)
  return os.time({ year = year, month = month, day = day, hour = hour, min = min or 0, sec = sec or 0 })
end

-- Wrap cron.parse to inject os.date/os.time for tests
local _cron_parse = cron.parse
cron.parse = function(expr, opts)
  opts = opts or {}
  if not opts.date_fn then opts.date_fn = os.date end
  if not opts.time_fn then opts.time_fn = os.time end
  return _cron_parse(expr, opts)
end

T.describe("cron.parse", function()
  T.it("parses wildcard expression", function()
    local expr, err = cron.parse("* * * * *")
    T.ok(expr, "should parse")
    T.eq(err, nil)
  end)

  T.it("parses specific values", function()
    local expr = cron.parse("0 * * * *")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.eq(expr.minutes[1], nil)
  end)

  T.it("parses step expression */5", function()
    local expr = cron.parse("*/5 * * * *")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.ok(expr.minutes[5])
    T.ok(expr.minutes[10])
    T.ok(expr.minutes[55])
    T.eq(expr.minutes[1], nil)
    T.eq(expr.minutes[3], nil)
  end)

  T.it("parses range expression", function()
    local expr = cron.parse("* * * * 1-5")
    T.ok(expr)
    T.ok(expr.dows[1])
    T.ok(expr.dows[5])
    T.eq(expr.dows[0], nil)
    T.eq(expr.dows[6], nil)
  end)

  T.it("parses list expression", function()
    local expr = cron.parse("1,3,5 * * * *")
    T.ok(expr)
    T.ok(expr.minutes[1])
    T.ok(expr.minutes[3])
    T.ok(expr.minutes[5])
    T.eq(expr.minutes[0], nil)
    T.eq(expr.minutes[2], nil)
    T.eq(expr.minutes[4], nil)
  end)

  T.it("parses range with step", function()
    local expr = cron.parse("1-10/3 * * * *")
    T.ok(expr)
    T.ok(expr.minutes[1])
    T.ok(expr.minutes[4])
    T.ok(expr.minutes[7])
    T.ok(expr.minutes[10])
    T.eq(expr.minutes[2], nil)
    T.eq(expr.minutes[5], nil)
  end)

  T.it("parses named months (case-insensitive)", function()
    local expr = cron.parse("0 0 1 JAN *")
    T.ok(expr)
    T.ok(expr.months[1])
    T.eq(expr.months[2], nil)

    local expr2 = cron.parse("0 0 1 jan,mar,dec *")
    T.ok(expr2)
    T.ok(expr2.months[1])
    T.ok(expr2.months[3])
    T.ok(expr2.months[12])
    T.eq(expr2.months[2], nil)
  end)

  T.it("parses named days of week (case-insensitive)", function()
    local expr = cron.parse("0 0 * * MON")
    T.ok(expr)
    T.ok(expr.dows[1])
    T.eq(expr.dows[0], nil)

    local expr2 = cron.parse("0 0 * * mon-fri")
    T.ok(expr2)
    T.ok(expr2.dows[1])
    T.ok(expr2.dows[5])
    T.eq(expr2.dows[0], nil)
    T.eq(expr2.dows[6], nil)
  end)

  T.it("treats dow 7 as Sunday (0)", function()
    local expr = cron.parse("0 0 * * 7")
    T.ok(expr)
    T.ok(expr.dows[0])
  end)

  T.it("parses @hourly", function()
    local expr = cron.parse("@hourly")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.eq(expr.minutes[1], nil)
    -- all hours
    T.ok(expr.hours[0])
    T.ok(expr.hours[23])
  end)

  T.it("parses @daily", function()
    local expr = cron.parse("@daily")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.ok(expr.hours[0])
    T.eq(expr.hours[1], nil)
  end)

  T.it("parses @weekly", function()
    local expr = cron.parse("@weekly")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.ok(expr.hours[0])
    T.ok(expr.dows[0])
    T.eq(expr.dows[1], nil)
  end)

  T.it("parses @monthly", function()
    local expr = cron.parse("@monthly")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.ok(expr.hours[0])
    T.ok(expr.doms[1])
    T.eq(expr.doms[2], nil)
  end)

  T.it("parses @yearly", function()
    local expr = cron.parse("@yearly")
    T.ok(expr)
    T.ok(expr.minutes[0])
    T.ok(expr.hours[0])
    T.ok(expr.doms[1])
    T.ok(expr.months[1])
    T.eq(expr.months[2], nil)
  end)

  T.it("returns nil+errmsg for invalid field count", function()
    local expr, err = cron.parse("* * *")
    T.eq(expr, nil)
    T.ok(err)
    T.ok(err:find("expected 5 fields"), "error mentions field count")
  end)

  T.it("returns nil+errmsg for out-of-range value", function()
    local expr, err = cron.parse("60 * * * *")
    T.eq(expr, nil)
    T.ok(err)
    T.ok(err:find("out of range"), "error mentions out of range")
  end)

  T.it("returns nil+errmsg for invalid token", function()
    local expr, err = cron.parse("abc * * * *")
    T.eq(expr, nil)
    T.ok(err)
  end)

  T.it("returns nil+errmsg for non-string input", function()
    local expr, err = cron.parse(123)
    T.eq(expr, nil)
    T.ok(err:find("expected string"))
  end)

  T.it("returns nil+errmsg for step of zero", function()
    local expr, err = cron.parse("*/0 * * * *")
    T.eq(expr, nil)
    T.ok(err)
    T.ok(err:find("invalid step"))
  end)

  T.it("parses value/step like 5/15", function()
    local expr = cron.parse("5/15 * * * *")
    T.ok(expr)
    T.ok(expr.minutes[5])
    T.ok(expr.minutes[20])
    T.ok(expr.minutes[35])
    T.ok(expr.minutes[50])
    T.eq(expr.minutes[0], nil)
    T.eq(expr.minutes[10], nil)
  end)
end)

T.describe("expr:matches", function()
  T.it("matches every minute", function()
    local expr = cron.parse("* * * * *")
    -- Any time should match
    local t = mktime(2026, 4, 11, 14, 30)
    T.ok(expr:matches(t))
  end)

  T.it("matches specific minute", function()
    local expr = cron.parse("30 * * * *")
    T.ok(expr:matches(mktime(2026, 4, 11, 14, 30)))
    T.eq(expr:matches(mktime(2026, 4, 11, 14, 31)), false)
  end)

  T.it("matches specific hour and minute", function()
    local expr = cron.parse("0 9 * * *")
    T.ok(expr:matches(mktime(2026, 4, 11, 9, 0)))
    T.eq(expr:matches(mktime(2026, 4, 11, 10, 0)), false)
    T.eq(expr:matches(mktime(2026, 4, 11, 9, 1)), false)
  end)

  T.it("matches weekday expression", function()
    local expr = cron.parse("0 9 * * 1-5")
    -- 2026-04-13 is Monday (wday=2 in os.date, dow=1)
    T.ok(expr:matches(mktime(2026, 4, 13, 9, 0)))
    -- 2026-04-12 is Sunday
    T.eq(expr:matches(mktime(2026, 4, 12, 9, 0)), false)
    -- 2026-04-11 is Saturday
    T.eq(expr:matches(mktime(2026, 4, 11, 9, 0)), false)
  end)

  T.it("matches first of month", function()
    local expr = cron.parse("0 0 1 * *")
    T.ok(expr:matches(mktime(2026, 4, 1, 0, 0)))
    T.eq(expr:matches(mktime(2026, 4, 2, 0, 0)), false)
  end)

  T.it("matches specific month", function()
    local expr = cron.parse("0 0 1 1 *")
    T.ok(expr:matches(mktime(2026, 1, 1, 0, 0)))
    T.eq(expr:matches(mktime(2026, 2, 1, 0, 0)), false)
  end)

  T.it("matches combined fields: 9am weekdays", function()
    local expr = cron.parse("0 9 * * 1-5")
    -- Monday 2026-04-13 at 9:00
    T.ok(expr:matches(mktime(2026, 4, 13, 9, 0)))
    -- Monday 2026-04-13 at 10:00 - wrong hour
    T.eq(expr:matches(mktime(2026, 4, 13, 10, 0)), false)
    -- Sunday 2026-04-12 at 9:00 - wrong dow
    T.eq(expr:matches(mktime(2026, 4, 12, 9, 0)), false)
  end)
end)

T.describe("expr:next", function()
  T.it("finds next occurrence of every-5-minutes", function()
    local expr = cron.parse("*/5 * * * *")
    local base = mktime(2026, 4, 11, 14, 32)
    local nxt = expr:next(base)
    T.ok(nxt)
    local t = os.date("*t", nxt)
    T.eq(t.min, 35)
    T.eq(t.hour, 14)
  end)

  T.it("finds next occurrence across hour boundary", function()
    local expr = cron.parse("0 * * * *")
    local base = mktime(2026, 4, 11, 14, 30)
    local nxt = expr:next(base)
    T.ok(nxt)
    local t = os.date("*t", nxt)
    T.eq(t.min, 0)
    T.eq(t.hour, 15)
  end)

  T.it("finds next occurrence across day boundary", function()
    local expr = cron.parse("0 9 * * *")
    local base = mktime(2026, 4, 11, 10, 0)
    local nxt = expr:next(base)
    T.ok(nxt)
    local t = os.date("*t", nxt)
    T.eq(t.min, 0)
    T.eq(t.hour, 9)
    T.eq(t.day, 12)
  end)

  T.it("finds next occurrence across month boundary", function()
    local expr = cron.parse("0 0 1 * *")
    local base = mktime(2026, 4, 15, 0, 0)
    local nxt = expr:next(base)
    T.ok(nxt)
    local t = os.date("*t", nxt)
    T.eq(t.day, 1)
    T.eq(t.month, 5)
  end)

  T.it("finds next weekday occurrence", function()
    local expr = cron.parse("0 9 * * 1")  -- every Monday at 9am
    -- 2026-04-11 is Saturday
    local base = mktime(2026, 4, 11, 0, 0)
    local nxt = expr:next(base)
    T.ok(nxt)
    local t = os.date("*t", nxt)
    T.eq(t.day, 13)  -- next Monday
    T.eq(t.hour, 9)
    T.eq(t.min, 0)
  end)

  T.it("result always matches the expression", function()
    local expr = cron.parse("*/15 9-17 * * 1-5")
    local base = mktime(2026, 4, 11, 0, 0)
    local nxt = expr:next(base)
    T.ok(nxt)
    T.ok(expr:matches(nxt))
  end)

  T.it("finds Feb 29 in leap year", function()
    local expr = cron.parse("0 0 29 2 *")
    local base = mktime(2026, 1, 1, 0, 0)
    local nxt = expr:next(base)
    T.ok(nxt)
    local t = os.date("*t", nxt)
    T.eq(t.month, 2)
    T.eq(t.day, 29)
    -- 2028 is the next leap year after 2026
    T.eq(t.year, 2028)
  end)
end)

T.describe("expr:prev", function()
  T.it("finds previous occurrence", function()
    local expr = cron.parse("0 * * * *")
    local base = mktime(2026, 4, 11, 14, 30)
    local prv = expr:prev(base)
    T.ok(prv)
    local t = os.date("*t", prv)
    T.eq(t.min, 0)
    T.eq(t.hour, 14)
  end)

  T.it("finds previous occurrence across hour boundary", function()
    local expr = cron.parse("30 * * * *")
    local base = mktime(2026, 4, 11, 14, 10)
    local prv = expr:prev(base)
    T.ok(prv)
    local t = os.date("*t", prv)
    T.eq(t.min, 30)
    T.eq(t.hour, 13)
  end)

  T.it("finds previous occurrence across day boundary", function()
    local expr = cron.parse("0 9 * * *")
    local base = mktime(2026, 4, 11, 8, 0)
    local prv = expr:prev(base)
    T.ok(prv)
    local t = os.date("*t", prv)
    T.eq(t.hour, 9)
    T.eq(t.day, 10)
  end)

  T.it("result always matches the expression", function()
    local expr = cron.parse("*/15 9-17 * * 1-5")
    local base = mktime(2026, 4, 14, 12, 0)  -- Monday
    local prv = expr:prev(base)
    T.ok(prv)
    T.ok(expr:matches(prv))
  end)
end)

T.describe("expr:next_n", function()
  T.it("returns correct count", function()
    local expr = cron.parse("0 * * * *")
    local base = mktime(2026, 4, 11, 14, 0)
    local times = expr:next_n(base, 5)
    T.eq(#times, 5)
  end)

  T.it("returns sequential times", function()
    local expr = cron.parse("0 * * * *")
    local base = mktime(2026, 4, 11, 14, 0)
    local times = expr:next_n(base, 3)
    T.eq(#times, 3)
    -- Each should be 1 hour apart
    for i = 2, #times do
      T.ok(times[i] > times[i - 1], "times should be ascending")
    end
    local t1 = os.date("*t", times[1])
    local t2 = os.date("*t", times[2])
    local t3 = os.date("*t", times[3])
    T.eq(t1.hour, 15)
    T.eq(t2.hour, 16)
    T.eq(t3.hour, 17)
  end)

  T.it("all results match the expression", function()
    local expr = cron.parse("*/10 9-17 * * 1-5")
    local base = mktime(2026, 4, 11, 0, 0)
    local times = expr:next_n(base, 10)
    T.eq(#times, 10)
    for i = 1, #times do
      T.ok(expr:matches(times[i]), "result " .. i .. " should match")
    end
  end)
end)

T.describe("expr:describe", function()
  T.it("describes every minute", function()
    local expr = cron.parse("* * * * *")
    local desc = expr:describe()
    T.ok(desc:find("every minute"), "should mention every minute, got: " .. desc)
  end)

  T.it("describes every 5 minutes", function()
    local expr = cron.parse("*/5 * * * *")
    local desc = expr:describe()
    T.ok(desc:find("every 5 minutes"), "should mention every 5 minutes, got: " .. desc)
  end)

  T.it("describes specific time", function()
    local expr = cron.parse("0 9 * * *")
    local desc = expr:describe()
    T.ok(desc:find("09:00"), "should mention 09:00, got: " .. desc)
  end)

  T.it("describes weekdays", function()
    local expr = cron.parse("0 9 * * 1-5")
    local desc = expr:describe()
    T.ok(desc:find("weekday"), "should mention weekdays, got: " .. desc)
  end)

  T.it("describes weekends", function()
    local expr = cron.parse("0 9 * * 0,6")
    local desc = expr:describe()
    T.ok(desc:find("weekend"), "should mention weekends, got: " .. desc)
  end)

  T.it("describes specific month", function()
    local expr = cron.parse("0 0 1 1 *")
    local desc = expr:describe()
    T.ok(desc:find("January"), "should mention January, got: " .. desc)
  end)

  T.it("describes specific day of month", function()
    local expr = cron.parse("0 0 15 * *")
    local desc = expr:describe()
    T.ok(desc:find("day 15"), "should mention day 15, got: " .. desc)
  end)

  T.it("describes specific day of week", function()
    local expr = cron.parse("0 9 * * 1")
    local desc = expr:describe()
    T.ok(desc:find("Monday"), "should mention Monday, got: " .. desc)
  end)
end)

T.describe("edge cases", function()
  T.it("handles midnight boundary", function()
    local expr = cron.parse("0 0 * * *")
    T.ok(expr:matches(mktime(2026, 4, 11, 0, 0)))
    T.eq(expr:matches(mktime(2026, 4, 11, 0, 1)), false)
    T.eq(expr:matches(mktime(2026, 4, 11, 23, 59)), false)
  end)

  T.it("handles day-of-week wrapping (Sun=0 and Sun=7)", function()
    local expr0 = cron.parse("0 0 * * 0")
    local expr7 = cron.parse("0 0 * * 7")
    -- 2026-04-12 is Sunday
    local sunday = mktime(2026, 4, 12, 0, 0)
    T.ok(expr0:matches(sunday))
    T.ok(expr7:matches(sunday))
  end)

  T.it("handles all-stars with matches", function()
    local expr = cron.parse("* * * * *")
    -- Should match literally any time
    T.ok(expr:matches(mktime(2026, 1, 1, 0, 0)))
    T.ok(expr:matches(mktime(2026, 12, 31, 23, 59)))
    T.ok(expr:matches(mktime(2026, 6, 15, 12, 30)))
  end)

  T.it("handles month range with names", function()
    local expr = cron.parse("0 0 1 jan-mar *")
    T.ok(expr)
    T.ok(expr.months[1])
    T.ok(expr.months[2])
    T.ok(expr.months[3])
    T.eq(expr.months[4], nil)
  end)

  T.it("trims whitespace in expression", function()
    local expr = cron.parse("  0 0 * * *  ")
    T.ok(expr)
    T.ok(expr:matches(mktime(2026, 4, 11, 0, 0)))
  end)
end)
